### ISSUE TITLE
SVG import of gradient fails on Firefox

### ISSUE THREAD

**Issue by iconexperience** [paperjs/paper.js#1001]
I have run into an SVG file that loads correctly on Chrome, but on Firefox the gradients are not handled correctly. This seems to be a similar issue as #666, but while that issue is closed and the examples work now, my example still fails. Here is the SVG:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xml:space="preserve" width="1024px" height="1024px" version="1.1" viewBox="0 0 1024 1024">
 <defs>
  <style type="text/css">
   <![CDATA[
    .grad1 {fill:url(#id0)}
   ]]>
  </style>
  <linearGradient id="id0" gradientUnits="userSpaceOnUse" x1="512" y1="31.9984" x2="512" y2="991.999">
   <stop offset="0" style="stop-opacity:1; stop-color:green"/>
   <stop offset="1" style="stop-opacity:1; stop-color:blue"/>
  </linearGradient>
 </defs>
 <g>
  <path class="grad1" d="M512 32c265,0 480,215 480,480 0,265 -215,480 -480,480 -265,0 -480,-215 -480,-480 0,-265 215,-480 480,-480z"/>
 </g>
</svg>
```

<a href="http://sketch.paperjs.org/#S/jVNfT9swEP8qxnsApCaO0xY1oQVBy9CkbSC13TQ1fQiJm3gNTmS7bTrEd9+dCxrTeNhDkrvfn/PdyXmiKn0UNKbTtbBZSTs0q3PMt6kmZluQETkeXraPFdkKbWStRgnlfpBQIhQopSoAmM8+eoOEXl6Q4dHkbjz7cX/jvPfz68+fxiShHmPfu2PGJrMJmX67JdznjN18hSoJLa1tYsZ2u52/6/q1LtitTptSZoaBlKEUbAzqce7nNk8oHIPVoSllRu8VCIMgQAPUd6K4raRavyvlURQxRx/EsWnSTIC00cIIvRUA72RuS5w7CHtNC0ApZFHat8jb5XDMpdhd1y3kAQkIytzL9Z6LlcER7L4SxO4bPM2K1rLMGCc4WownV7OrBfELneacPK1kVcUbXZ18kHlw+kyWS1AxVwACaF6kGpaWS6EskTnUAx10UbxgcyUtbmoDE01xvjs1NzhZywHt8xDCPYZd7kfRoIdM+IfBMIqQig7Lt3VD6tXKCNwBHuRagRgZr4YTpN3H/Jy4PKurWseFFkIllP3j5//nf6g24mBnfw+MiFvpsEltSbIqNTirWx2Uxm18gUFIN8zCs34nIL1B0Al5333hIZCd9YkHkEu9V9w7yF2O7Et0sCBJ0OLyV+IXdjjEq3dxfJ6oRtc/RWZ9+djU2sJtPgHmFIhEwY/2oEW6bmqprKHxYvn8Gw==">And here is the Sketch</a> The circle should have a gradient from green to blue, but on Firefox it is just black.

**Comment by iconexperience** [comment]
Oh, and I think this issue should be labeled *priority: low*

**Comment by iconexperience** [comment]
I found that the gradient definition seems to be imported correctly on Chrome and Firefox, but when <a href="https://github.com/paperjs/paper.js/blob/develop/src/svg/SvgImport.js#L537">`getDefinition()`</a> is called, the argument `value` is `"url("#id0")"` on Chrome, but `"url("http://sketch.paperjs.org/#id0") transparent"` on Firefox. Not sure what happened before, but I will find out.

**Comment by iconexperience** [comment]
For the path in the SVG `DomElement.getStyles()` returns 237 styles on Firefox, and one of them is

`fill: "url("http://sketch.paperjs.org/#id0") transparent"`

On Chrome there are 261 styles, an the `fill`style is simply

`fill: "url("#id0")"`

**Comment by iconexperience** [comment]
If I understand this correctly, the Firefox value `fill: "url("http://sketch.paperjs.org/#id0") transparent"` contains a *functional notation for an IRI* and a fallback value (`transparent`). The fallback value is mentioned in the SVG spec at https://www.w3.org/TR/SVGTiny12/painting.html#SpecifyingPaint , but I was not able to find any details about this. The word "fallback" occurs only once.

I will dig further.

**Comment by iconexperience** [comment]
So I found that we can get the leading path `'http://sketch.paperjs.org/'` from the value of  `window.location.origin + '/'`. If we remove the path from url or if we manage to include it into the regular expression when parsing the url, this issue should be solved.

**Comment by ActionScripted** [comment]
Whenever I try to load a gradient the error is: `TypeError: this._color is undefined`

Even this simple circle with a black/white gradient causes problems:
```
<svg id="Layer_1" data-name="Layer 1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 338 338">
  <defs>
    <linearGradient id="linear-gradient" y1="169" x2="338" y2="169" gradientUnits="userSpaceOnUse">
      <stop offset="0" stop-color="#fff"/>
      <stop offset="1"/>
    </linearGradient>
  </defs>
  <title>Untitled-1</title>
  <circle cx="169" cy="169" r="169" style="fill: url(#linear-gradient)"/>
</svg>
```

**Comment by lehni** [comment]
@ActionScripted I don't think this is the same issue as @iconexperience's. On sketch, your 2nd example [already works](http://sketch.paperjs.org/#S/dVJha9swEP0rN/dDG6htOR1lcdyUlW0hUNggtF/mERz54mpRJCPJsU3pf9/JWUI2NoHh9N67u3dnvQaq2GGQBsstOv4SXAdcl/6+LwzYfQV3cJnddzsJezRWaHWXB0nE8gBQkVKoioDGbcIPeXA/y96FIcxRoSmcNil8LPUaYSFlY90AQTKJxlFyDcvnOXzuam0cfJNNFS4URAP4fGiTwm3EGDw0QpbARhCGs8zbOXeRkAtRUvhY9GhW/kpGlSXkxbk6jeO2baP2JtKmiseMsZgqHEVpJ4Xa/lOaTCaTeKC9mCSs7ijqT9FeYPugBwYYvGfDR7h1vURCURVrieG64NvK6EaVqcIWzrTTg4vU1gX3CbVBi2aPeUBT+iLg+toTDjsXc2uJgMg69roRUqaNkVcXtKzFp1WyGk3fIIuHrFlGprEwc1OUApU7bOcopJ7Vb+JJCefX1FDXpffwVT1Z9KYSQm/8JnsfjYexurEHbyceHR9Rb1TXoDcbi85v4mx+z4RcS3oCF1+Gkwfx3wnJfxLYcIaE+M9xZhkXhtNyuCysHdJ8V96dnPL+FBrfwnv2dei/zy6nuaqN/oncRWLnXx4t5oqYERH07tcGi22thXI2SL//ePsF) 
I'll look into what's wrong with the first.

**Comment by iconexperience** [comment]
Without having looked at what is really going on I would say that the problem in the first example is that there is no stop color defined for the second stop of the gradient. Maybe the constructor of `GradientStop` should handle the case when no color and ramp point are defined and then at least set the color to opaque black. 

Of course, this would mean that a few color objects would unnecessarily created when importing SVGs, but the number should generally be quite low, so it's not a big deal.

**Comment by lehni** [comment]
@iconexperience I've already fixed both, no need to look into this part :) I'm just wrapping up the code before committing. Haven't worked on gradients for a long while, and realized there are some odd things in there.

**Comment by iconexperience** [comment]
Great! BTW, original example of this issue is an export from CorelDraw, so if we fix all those bugs Paper.js should be able to import SVGs from CorelDraw and Illustrator. Now that would be something.

**Comment by lehni** [comment]
Wow! I think InkScape works pretty well too : )

**Comment by iconexperience** [comment]
Yes, but Inkscape produces cleaner SVGs, so I would just assume that Paper.js can handle the SVGs created by Inkscape. With Illustrator and CorelDraw I sometimes have the feeling that they are not trying too hard to achieve flawless SVG support.

The only reason why I am using CorelDraw is that Inkscape has not object-tree view, and I cannot work without one.
