### ISSUE TITLE
Key / Mouse Event Issues

### ISSUE THREAD

**Issue by FeaRCODE** [paperjs/paper.js#1006]
First I wanted to point out that documentation is pretty unorganized on the site. It makes it extremely difficult to learn how PaperJS works and everything it has to offer. Hopefully sometime in the future there will be Type Definitions or a better implementation for documentation (which I would happily write if I had more experience with Paper).

On the issue at hand, I noticed that handling multiple Key events is terrible! Take this piece of code for instance:

```
function onKeyDown(event) {
    if(Key.isDown("z") && Key.isDown("control")) {
        // Only Works when Z is pressed, THEN Control.
    }
}
```
Like explained in the comment, you have to press Z FIRST, then Control. Implementing `Control+Z` or something similar would require more code rather than the provided "API".

Also missing are events for `onMouseWheelDown`, `onMouseScroll`, `onRightMouseDown`, and `onLeftMouseDown` (Even handling context menus). I probably could think of more (I do understand that browsers enforce their Global key combinations, but this should at least be an option to use).

**Comment by lehni** [comment]
Could you tell me which browser and system you're experiencing this on? If it's on Window, it's probably simply because the browser does not route all events through. But I'd like to analyze this properly first.

**Comment by FeaRCODE** [comment]
@lehni Sure! I am on Windows 10 using Google Chrome. However, I did find a fix which allows me to pick up `Control + Z`. Please note that of course some browsers "IE mostly" doesnt allow most shortcuts, but allows `Control + Z` to be routed.

Here is simply the workaround:
```
var control = event.event.ctrlKey;
if(control && event.key == "z") {
	// Do something (assuming this gets routed from the browser) 
}
```

**Comment by lehni** [comment]
Hmm, on that browser I seem to only get the keydown events right before the keyup events. And since I use those to internally keep track of the state of shit, control, etc, this doesn't work as it should. That's indeed a bug that needs fixing. I shall investigate.

**Comment by lehni** [comment]
It appears to be a Chrome issue on Windows. Even with this fiddle, I only get keydown events when I actually release the shift / control keys: http://jsfiddle.net/mxqvu2fb/

So the workaround for this will be to not use these events to track the modifiers anymore, and use the flags on the event object instead.

**Comment by FeaRCODE** [comment]
Alright, sounds good to me. As long as I was able to at least capture those events, I would be fine. Off-topic, since PaperScript is it's own subset of JavaScript, could it be possible to add something like `require("myPaperScript.js")` and it include that file? Just some thoughts.

**Comment by lehni** [comment]
In the Browser or in Node.js? This works in node already, but in the browser `require()` is provided by whatever library you use to emulate that functionality, so it's not possible AFAIK to add such hooks to it.

**Comment by FeaRCODE** [comment]
Ok, thank you. I haven't looking into node, but I think it might be something worth diving into.

**Comment by lehni** [comment]
Not done yet : )

**Comment by FeaRCODE** [comment]
Hahaha I just thought you forgot to close it :D

**Comment by lehni** [comment]
So it turns out I was wrong [here](https://github.com/paperjs/paper.js/issues/1006#issuecomment-196485339): This happened because of a setting on Parallels (I am running Windows in a virtual machine on my Mac). I need to look more into what exactly is going wrong with `modifier.control`.

**Comment by lehni** [comment]
I can't reproduce this on the develop build. Have you tried with that?

https://github.com/paperjs/paper.js/tree/prebuilt/module
https://github.com/paperjs/paper.js/tree/prebuilt/dist

**Comment by FeaRCODE** [comment]
@lehni When I had this issue, I was using an older build. I have continued to use the way i discussed above and it works fine.
