### ISSUE TITLE
New xhr loader doesn't work in IE9 Standards Mode

### ISSUE THREAD

**Issue by photonstorm** [paperjs/paper.js#1008]
I'm drowning in deadlines at the moment, so don't have time for more details - but I just wanted to post this as a heads-up:

I pulled down the latest paper.js and built it from source (it's a v0.9.25-develop base). On IE9 in Standards Mode the Http object fails when you try to load anything. The cause of the error is this:

```
var Http = {
	request: function(options) {
		var ctor = window.ActiveXObject || window.XMLHttpRequest,
			xhr = new ctor('Microsoft.XMLHTTP');
```

When it then tries to call `xhr.onload` it throws a script error as `onload` is undefined. I've not dug deeper yet, but it's possible `onload` isn't a valid method in the ActiveX XMLHTTP object. You don't see this in the current stable / pre-built version of v0.9.5 because it only uses `open`.

Because I was in a rush I locally patched the above to:

```
var Http = {
    request: function(options) {

        var xhr = new XMLHttpRequest('Microsoft.XMLHTTP');
```

And it works fine in IE9+ and all our other test browsers. It's probably not a valid solution for paper.js, but is a good workaround for us.

**Comment by lehni** [comment]
Thanks for the heads up! This needs more testing indeed, then.

**Comment by lehni** [comment]
I guess onload doesn't work with the ActiveXObject, so we can just drop that. And luckily it sounds like this aligns with the modern browsers that paper.js covers. I am pretty sure you can drop the `'Microsoft.XMLHTTP'` from your constructor call.

**Comment by photonstorm** [comment]
I guess it depends what browsers you want to support, but I can confirm that IE9 is perfectly happy with just `XMLHttpRequest` and doesn't need the ActiveX object.

The only downside is that in some setups it'll fail due to cross-origin issues, where IE9 needs to use XDR instead. This is edge-case stuff, but sadly happens (details here http://blogs.msdn.com/b/ieinternals/archive/2010/05/13/xdomainrequest-restrictions-limitations-and-workarounds.aspx). IE10 supports CORs properly, so no worries there.

**Comment by lehni** [comment]
Did the use of `ActiveXObject` on IE9 support those edge cases?

**Comment by photonstorm** [comment]
Nope, but like I said it's really edge-case. We're talking IE Security Zone policies here, check out the table on this page: https://msdn.microsoft.com/en-us/library/ms537505(v=vs.85).aspx - the kinda stuff most of us haven't worried about in a decade :)

Honestly I wouldn't worry about it too much. What we did in our game framework was to let the developer [specifically enable XDR](https://github.com/photonstorm/phaser/blob/master/src/loader/Loader.js#L2384) and then use that in preference to XMLHttpRequest, rather than try to guess it within the lib. We don't use the ActiveX component at all (there is even an option in IE9 settings to block the ActiveX component and only use 'native' XMLHttpRequest!).
