### ISSUE TITLE
Layers inserted via project.addLayer() can't be accessed by name

### ISSUE THREAD

**Issue by georeith** [paperjs/paper.js#1009]
Given I insert a layer via `project.addLayer()`:
```js
var layer = new paper.Layer({ name: "test" });
paper.project.addLayer(layer);
```

Then it is not accessible via name unless I re-set its name:
```js
console.log(paper.project.layers.test); // undefined
layer.name = "test";
console.log(paper.project.layers.test); // Layer "test"
```
[Example sketch](http://sketch.paperjs.org/#S/lZDNCsIwDMdfJeQ0QQrbseIbePNoPdQu+LHalrYoMvbuLisOPDmPCb//R9Kj03dCifuOsrngGo1veX7oCFa/KNawBUdPCDpQFDteVT2wSoLCTCnXCmFYbZSbNc1PTfPRFCREfyOThW7bQpdoBpQz3iVvSVh/rr7xiUpiKsHsIrJhsvgLrjR2ne9Y6vFX2vjUUyTdBX91OaE8HIc3).

**Comment by lehni** [comment]
Hmmm. I get this output with your sketch:

```
Layer 'test1'
Layer 'test2'
Layer 'test1'
Layer 'test2'
```

**Comment by lehni** [comment]
But once I set `settings.insertItems = false;` as the original title suggests, I can see your issue. Is there a reason why you changed the title and removed this statement?

**Comment by georeith** [comment]
Strange it wasn't working for me before even with `settings.insertItems = true` on sketch but locally it did which is why I modified it and thought it was just a flaw in `Project#addLayer()`. Was the version on sketch changed in-between?

Anyway it looks like you fixed it which is all that really matters.

**Comment by lehni** [comment]
Yes the version has changed.That must be it.
