### ISSUE TITLE
Origin x,y coordinates on Point object

### ISSUE THREAD

**Issue by teolaz** [paperjs/paper.js#1011]
Hi,
i'm wondering if it is possible to add 2 properties (xOrigin and yOrigin) onto the Point object, in case you animate it and want to check in function onFrame the origin coordinates if you animate the point coordinates.
Thanks
Matteo

**Comment by lehni** [comment]
No, this will not be added to the API as it would double the memory consumption of every point and path, and will rarely be used. But there is nothing stopping you from adding your own properties to JS objects.
