### ISSUE TITLE
canvas repeat in firefox

### ISSUE THREAD

**Issue by Krispomoho** [paperjs/paper.js#1013]
I have a problem: I develop a webgame with paper, it works fine on chrome and safari , but can't on firefox. When i try set `canvas[resize]{width: 100%;height:100%;}`, it still doesn't work;
here is the info: paper V0.9.25, chrome 49.0.2623.87, firefox 44.0.2

![image](https://cloud.githubusercontent.com/assets/6927337/13800905/4f02dbf6-eb68-11e5-98cb-3bd6753a2d43.png)

![image](https://cloud.githubusercontent.com/assets/6927337/13800912/592a1f68-eb68-11e5-8e13-8c9359eb7d57.png)

**Comment by lehni** [comment]
Can you share some actual code so we can reproduce this? It's impossible to say what's wrong otherwise.

**Comment by Krispomoho** [comment]
`
<style>
		html, body {
			height: 100%;
			width: 100%;
			margin: 0;
			padding: 0;
		}

		#myCanvas {
			width: 100%;
			height: 100%;
		}
	</style>
`

**Comment by Krispomoho** [comment]
I found that if there is a Raster object in the page , this bug will appear in firefox;
here is the demo link: [demo](https://jsfiddle.net/5sex4nmd/)

you can replace the picture and try again.
I import the v0.9.25 paper-full.min.js

**Comment by lehni** [comment]
I only see this in the output window, I think your example is broken:

<img width="52" alt="screen shot 2016-03-17 at 13 31 45" src="https://cloud.githubusercontent.com/assets/213275/13846058/a850a1ac-ec44-11e5-8b1d-e7a9ab836fb2.png">

**Comment by Krispomoho** [comment]
you can just copy my code and run yourselt, i don't know how to import paper.js in jsfiddle

**Comment by lehni** [comment]
Could you make a zip file of a collection of files where I'm sure the error occurs, and post a download link here? Your example seems to make reference to an image file also, so please included that too.

**Comment by lehni** [comment]
Still waiting for a way to reproduce this. A ZIP file with the full example is appreciated. Thanks.

**Comment by lehni** [comment]
still waiting...
