### ISSUE TITLE
Creating a stamp/symbol brush

### ISSUE THREAD

**Issue by viiiyears** [paperjs/paper.js#1016]
I am trying to create a symbol from an imported .svg that will then be cloned to canvas on every onmousemove. The below code clones the symbol once - but then fires an error.

I'm new to javascript and paper.js so any help would be very much appreciated!

```javascript
function onMouseMove(event) {
  
  var symbol =  new Symbol(project.importSVG("../img/brush.svg"));
      
  var clone = symbol.clone({
        center: event.middlePoint
      });
}
```

**Comment by lehni** [comment]
Can you share the svg data also?

**Comment by viiiyears** [comment]
Hey Lehni,

Thank you for looking at this. 

I have setup a paper.js sketch with the svg [here](http://sketch.paperjs.org/#S/nVVbb5swFP4rFn1Jq8SAgZSQtA+Tpj1sVatW2sPGNDlgiBewI9u5Ncp/3zHkQjRtU5uLfXzO8cf3neM4O0fQmjmJ8zJnJps5fSeTuV0XS5EZLgWS4kEuNXuQK9ZjKybMNdqlIhUIrahCelWiO4QWSv5imcG8XkhlXr5+6qXOzJhF4rpZLjDj5cxsGVUaZxIv5y6vS5dqzYx2mVJSYcBJneuxhT1Bb+uprABdsDV6aRY9SLNJx5SpWuoZZLSpOKukYL2djbavDOgylaCGN655nlfsSXJhjil7i7a3gO5NKiZWDc/vUucL3TL1008dlFNDB7ZGRy+y3k1dCX130rher/E6wFKVLvE8z23UoDXPzQySIjLCkd01a+oAHjIMW8+Ks/UHuQGXhzzUJqJj9B54mUnOCt1YYGuzrdg96NQDv99MYTtFu4JXVXJVFMV438Z32ig5Z8kVEBq39qDmUI6Kw5T4J2dDM/FwtNgc9pIWNDg8Yse1rKg9DElrsUPeKaGQwgw0f2UJ8fAQcBpHQWtebZOnigpm6Hh/EOG2Khpx7kndRMH5QVkFpwKq0SiwdbaVwSQCc3s2u4X1/iis9bgtZnkBSA4lhYBhm8uHBYBiFBW6kKoGX2NbqT0/inE0RL4XYHJ7DRBPE9dufw/UcITJqANFS4YyKpCQBk0Zejdw4MfYJx3g4v1QJMSjuAMllyLvoE3c8j/98kcx9sJDx/woxGG3Z34Q4DDs9iyEB0anlr2BKgkj7APVOMBDYqk+fu4SbQi+9QCFPnTo72TCf/QWB/ani0cjS+Xj8/Pjc5fNgprZBZTlYa+ah8gnmMR94kOhKuhj2LfDwMPxLXwGzeI0nGMD+PYvg23GRfA8nIPN8K0VObF3lWV4eN+48BcwVYzOF/ae1E7y/cf+Nw==) 


this is the test svg code i'm working with
```html
<svg id="Layer_1" data-name="Layer 1" xmlns="http://www.w3.org/2000/svg" width="529.51" height="264.51" viewBox="0 0 529.51 264.51">
	<defs>
		<style>.cls-1,.cls-4,.cls-5{fill:#fff;}.cls-1{stroke:#000;stroke-miterlimit:10;stroke-width:0.5px;}.cls-2,.cls-3,.cls-4{isolation:isolate;}.cls-3,.cls-4{font-size:20.6px;font-family:Planeta;}
		</style>
	</defs>
	<rect class="cls-1" x="0.25" y="0.25" width="529.01" height="264.01"/>
	<g class="cls-2">
		<text class="cls-3" transform="translate(158.56 103.27)">P</text>
		<text class="cls-3" transform="translate(169.29 103.27)">age can not be </text>
		<text class="cls-3" transform="translate(318.12 103.27)">f</text>
		<text class="cls-3" transform="translate(324.98 103.27)">ound</text>
	</g>
	<rect class="cls-1" x="198.04" y="154.45" width="133.44" height="44.95"/>
	<text class="cls-3" transform="translate(245.18 183.62)">OK</text>
	<rect x="0.25" y="0.25" width="529.01" height="41.29"/>
	<text class="cls-4" transform="translate(16.31 26.99)">ERROR</text>
	<path class="cls-5" d="M512.28,21.45l8.14,8.14-0.87.87-8.14-8.14-8.14,8.14-0.87-.87,8.14-8.14-8.14-8.14,0.87-.87,8.14,8.14,8.14-8.14,0.87,0.87Z"/>
</svg>
```

svg file is also hosted [here](http://cdn.eightyears.co.uk/img/assets/error.svg)

**Comment by lehni** [comment]
I'm seeing this error:

    Could not load "http://cdn.eightyears.co.uk/img/assets/error.svg" (Status: 0)

**Comment by lehni** [comment]
There are multiple problems with your code:

- symbols are placed, not cloned.
- you should create your symbol once outside of the mouse handler, and then use it inside.
- you should use a `onLoad` callback for importSVG(), as it won't return a SVG right away (not fixed in the code below):

```js
var svg =  project.importSVG("http://cdn.eightyears.co.uk/img/assets/error.svg");
var symbol = new SymbolDefinition(svg);

function onMouseDrag(event) {
  var brush = symbol.place(event.middlePoint);
}
```

**Comment by viiiyears** [comment]
cheers again @lehni 

Managed to get it working by doing;

```javascript
function SVGSymbol(svg){
	var brush = new Symbol(paper.project.importSVG(svg));
	svg.parentNode.removeChild(svg);
	return brush;
}
var brush = SVGSymbol(document.getElementById('svgError'));

function onMouseMove(event) {
	var paint = brush.place(event.middlePoint);
}
```
