### ISSUE TITLE
Scaling Canvas (View) and Contents?

### ISSUE THREAD

**Issue by FeaRCODE** [paperjs/paper.js#1018]
I have the following code:
```
window.addEventListener("resize", onResize, true);
function onResize() {
	myRaster.fitBounds(view.bounds, true); // How to pan if this image goes OFF the canvas?
        // Re-size all other draw content??
}
```
This simply re-sizes the image I have with the canvas when the window re-sizes. Is there a way for me to also scale anything I have drawn on the canvas? I am trying to make an editor, and how would we achieve this functionality AND how would we achieve the panning if the image scales off the canvas?

**Comment by lehni** [comment]
Could you ask this question on the mailing list instead? I'd like to keep the bug database free from support request. Thanks!
