### ISSUE TITLE
Windows Chrome onKeyDown event issue

### ISSUE THREAD

**Issue by ber8749** [paperjs/paper.js#1022]
When using Chrome v48 on Windows 10 and pressing both the _Control_ key and the _C_ key at the same time, only the _Control_ key seems to trigger and onKeyDown event. The _C_ key does not. I believe the scope of this problem may be even bigger than just _Control_ and _C_, it also appears to crop up when a user holds other modifier keys along with a character key. For example, _Alt_ + _Z_ displays the same issue.

**Comment by FeaRCODE** [comment]
I had the same issue here: https://github.com/paperjs/paper.js/issues/1006. 

My fixed implementation of this was:
```
var control = event.event.ctrlKey;
if(control && event.key == "z") {
    // Do something (assuming this gets routed from the browser) 
}
```
Keep in mind that some shortcuts **CAN NOT** be overridden (this is browser specific: chrome, IE, etc.).

**Comment by ber8749** [comment]
To clarify, my issue comes into play when holding _Control_ and then pressing _C_, which should trigger 2 separate events. I don't believe your fix will address my issue, because in my case there is only a single event triggered for the _Control_ key, there is no event for the _C_ key.

**Comment by FeaRCODE** [comment]
I just threw up a simple example [here](http://sketch.paperjs.org/#S/jZHBisIwEIZfZZyLFUpRoZdKT+5tLwsejYc0na4h2YykURHpu2+itCvsxYFkJvP/zHyQOzr5Q1jhzlBQR8xRcZveF+nhJMNxBTU4usJXrIut9spSdhdeOIihyAXyFezLZQ7l8pCPgpetPvcVrMup1Wlrt2w52ueNlcrMkzIsNiml052dCpodsPuk2wdfXUaXuGAB0z7dPVuFoRvUNQhUAl/0FA/oYtoGyeWpFbh5dSl2PVsqLH9nAh9DYTWLwybXMBZjJtvTH8HzVsHbCPsGQiOtMm9ArP9DDPFXGk/SnFi70GO1Pwy/)!

I am using the same browser on Windows 10 and whenever I press both at the same time, I get both events printed in console. Also, keep in mind that when you hold control the event keeps firing.

**Comment by ber8749** [comment]
You're right, this seems to be an issue with our code base. Thanks for your help!
