### ISSUE TITLE
Tool no longer receiving onMouseMove events

### ISSUE THREAD

**Issue by tjunnone** [paperjs/paper.js#1032]
Commit e054b760ed05c0909b "Fix cases where toolPoint was null" broke my tools :p

After this commit, a previously unused tool will no longer receive events to the onMouseMove handler after being activated unless I click the canvas first. My tools are activated by HTML controls outside of the canvas, so there would normally be no onMouseDown/onMouseUp events, only activate() followed by a stream of onMouseMove() events when the cursor re-enters the canvas.

**Comment by lehni** [comment]
Oh no, that's not good! Could you share a simple example for me to reproduce this?
