### ISSUE TITLE
rasterize() changes width and height of rasters in certain browser zoom levels

### ISSUE THREAD

**Issue by lafisrap** [paperjs/paper.js#1034]
I need to rasterize a raster before I handle it (e.g. if it is rotated or scaled up). 

I use the current dist/paper-full.js and following test program:

```
    console.log("Resolution: "+project.activeLayer.getView().getResolution());
    var raster = new Raster("rect.png");
    raster.onLoad = function() {
        console.log(raster.bounds);
        raster = raster.rasterize();
        console.log(raster.bounds); 
    }

```

For resolution of 100% (and 50%, 150%) in Firefox and Chrome the output is ok.

Firefox:

> Resolution: 72
> Object { _x: -50, _y: -50, _width: 100, _height: 100, _owner: Object, _setter: "setBounds" }
> Object { _x: -50, _y: -50, _width: 100, _height: 100, _owner: Object, _setter: "setBounds" }

Chrome:

> Resolution: 72
> Rectangle {_x: -50, _y: -50, _width: 100, _height: 100, _owner: Raster…}
> Rectangle {_x: -50, _y: -50, _width: 100, _height: 100, _owner: Raster…}

But for example 90% (and other intermediary resolutions) show:

Firefox:

> Resolution: 64.47761392593384
> Object { _x: -50, _y: -50, _width: 100, _height: 100, _owner: Object, _setter: "setBounds" }
> Object { _x: -49.69166513637541, _y: -49.69166513637541, _width: 99.38333027275083, _height: 99.38333027275083, _owner: Object, _setter: "setBounds" }

Chrome:

> Resolution: 64.79999828338623
> Rectangle {_x: -50, _y: -50, _width: 100, _height: 100, _owner: Raster…}
> Rectangle {_x: -49.444445754274945, _y: -49.444445754274945, _width: 98.88889150854989, _height: 98.88889150854989, _owner: Raster…}

**Comment by lehni** [comment]
Here are the resolution value at different zoom levels in different browsers:

Chrome:

150%: 108
125%: 90
110%: 79.20000171661377
100%: 72
90%: 64.79999828338623
75%: 54

etc.

Firefox:

150%: 108
133%: 96.00000286102295
120%: 86.40000343322754
110%: 78.5454568862915
100%: 72
90%: 64.47761392593384
80%: 57.600000858306885
67%: 48.000001430511475

As you can see, paper.js calculates the view resolution based on the current zoom level. The only weirdness I can see here are the slightly different values at 110% and 90%.

Paper.js uses this resolution by default when rasterizing items. You can provide your own resolution value when calling `item.rasterize()`, e.g. `item.rasterize(72)` to always rasterize at 72 dpi.

This explains why you end up with different resolution Raster objects. 

I can't see a bug here, actually.

[Here a sketch](http://sketch.paperjs.org/#S/XVDBasMwDP0V4UsyCKbk6LLL9gOjO/RQ9+A6ojHJpGI7LbT03yvP29img9DTe5IeuilyH6iMep8w+1F1yvNQsGdKPKOe+dg2G5R6yYHJNB2cA150/Gk9rS1ZOrsIJ5dHeAbCC7xJqTfos6PjjO3NEkh4pIzR1A0VdJVJ4YoGdv1q1YGk/Xc7R57wlWeWqSbi0PwhtmHIo4He0r24+O25eNFV9cILDakIisnokpwVm5+KiuR4+39BZfThaxgsyXMOEd104kA5KbPb3x8=) to reproduce the above example.
