### ISSUE TITLE
Path self-intersection divide: "Cannot read property '_remove' of null" Line 3845

### ISSUE THREAD

**Issue by techninja** [paperjs/paper.js#1036]
I've finally been given the go-ahead to make my path boolean based flood fill! One of my first tests I made a loopy path with plenty of self intersection and attempted a divide, and it errored out :P

[Check this live sketch to see the error.](http://sketch.paperjs.org/#S/fZfBbly5EUV/RdDGE4BNsEhWFelBVvmBAFnKWnjGnYxhjzSQncliMP+eUyQ7sLyIFurXr1+RrFv33qr3x/3T+1+v92/v//Hp+vXnX+7T/c/PH+L77+9f7j5/fLre/fXu6fqfu7+///rLD3+8e7rj78v1X79en75+eXv3sG/E38ODtZGrmngSqXk2NX1MDyWV9f+iWW1Oe+Tbg9WRRWxYktJz7X0It7nSOVPNqjo7Ny5iedTOvYuUXCZXK1yt5zZ66WnM7FbK4G4tbDDceFaya1OPFerMo0+VJJ4Lv+/9tXgenHAkMc/T3WI76VmLFFYgqpQqNVaYuXmvSUb2PvoK72xbrHG31paLTIsnax7SO2etkqWMlf1Fcq06eppZZiPL78KVQ/diso6anaTYnWfriBWd4Oqeas/F9eSuklt3H6lVzcOkrlNyvD50ePrf1Yq3VtnmfO54J8vamqbWOUazsZP0SJIi9VYkjgP0rVWrnLx4PLXqRmFlNCN4WLbp6+DUZjgJsXfPfXYZq5h9cOikwNtbO+Ez92qlpl6gQ/WqC7dG8Iy8wUpX4Ru/AgXrlTnarergMfieeu9kZKXFOYWNWhtxdu9ic0HJibR70IsNgfVUnWWhmqXuJXsZurYHT5+69herG4+VSGk9Wa5SRHfdTIivvaU+K0BtgvOoVQoSB4Bqc0PCYaYBCShKUGHFF4NgpSvxM5uPEqULYlo3g/fS2qLypedpAJkuhbWL7cq12XK3LpNwXcVZMDuqSqSDOsam0Zg2NWL7CB6t2MGDHlXvrDJGl81YpZqIgE9ZaAbbretKxmT45nsDrjoGZOgKILUtdpYU4mtlX19gY6GQdvaL52TU1CauMKD80bM73xIFkkq5Iv8MDg3y1IDf58k11Oy1Ey+59Kp158ZFpazZxjwZTBGBeXnCsnaCYZKOMl6xlIqNIQOY4XPfFAX3ieBAhK18F4nSyZQ6U3OuymxrZ+DQVpEifKpjEY8SSLPAWb3oONEzazOX19G3Z2+PpgdE2m3E1hS4bNCC1mIhGrgdpFpPXsJV66DqQEZttjYLMoIfA/eJCqzw6fge+kLZBpfm2A4UqpndiZ/nXmhGdWhsjzq2K5EeNHCK3BoWofBuhWOmJB6YT8QZ9xpsYKkWJClUdpfMGqTUWVtqEpKCwAv2EaTlrEjRvC+2YPSb3hBvYsM7nkNzzAJ09ARpm6KXsL5eVtmgYV/QIW2sm584/CEMS+cAtKJMTtmWi2DywkJ4EIaowYIa6vDIHFgEQexox/C1zGg+2IG6iO69EYPBwRJ49LDUFlIRnBJPVlx4C8SF+46icSxcpHvfNZ5UI9YEGPOlLyqH8UTq0MN9Q2/hbLROQKoOwUqLcJ5ge9yKPGzU7Qwh1TArBK/zlrvOjEvCTvoGLQGlLn5iXCUawr7YtloNfOP/iaTp9DJpj71xSOq3RGVucUawF623PjbCuWABxPBTMdoFjOqvso5mgGhjX+++pHJZtS+V8kTzKnriqTPdAqnVYCRG2XbaOuhqLEC3cNvKbyA0OU2CJXQh25kDFZlrqNpqdM0ou67KrloCxrTT31qjFCH1Gerffgx/gRNVM7pM3brGZDXseESLMduwQW6qwzJlzDK/c5lvTx8uBgd10b3jZxuROaQFnjSVA943m5ddhCUX8inYd4otGWZ2tPp2qdjkWEX03B79XmIEKmB//JFuiwHEfFGjGnScLuCDU3iVm0spzC4FckgMIPDpgKSYUopOUSMXRqcmtoQ2Cb3NPkGfqS2hrGxkqDsWqDHiMJm++ipWjyjj2G00Pw2Yn1dblBpzgexmiVkxPsTGqNV9MRCTDYOJ5q5naFSJLleUWSzax2mfl7pSgcF5qQZZtRgs2beMGOFWaOU0tXl7NZrGtFOjAoAtfd2KMY3JL8WZqp2pR2E3Lte+nTZ5ANGXmc7nIo6YROs8F2dcg42I2JNDPaaLo8P96O3JNerFeBpaXxc7OLCW6PiUyVTaaQeNVBZatkYtHG+EuEKkaGTXib4IlRh56PgsWW/s9FGpHTSjcLLwwm582QRt8QyZDPExFStyWz2lHbiahfPhRrtx0+mYHqgKN04gQANbe3Vi2gUy9nS7iFiqANHDsfbFieY0wgiVGBo6hnzrADErx/AQpd1vCo3JtcdQDz5q/8eOLvGm4WOu+Mpbwdgap6s4xWNkn/q9F1IqrFkPYko79WXCq/0g4rUell+j1R8HH9HdEAA+HRF73tEY1et6e7HZ1zsGPhr9h2X9ZoO+3iGoSpXVB/xsHCrT8/pUHh/3u9ZjOi9hX1+eP13/9vz5+eXt3ZufPv/7+ubd059/+fHd07uneHd7uX7h1S3e4PKHj79//HD9Ia737/yW//nx8+cVzVNvXq4f3vALb38/vVzff/rt+SOvd/dvHx7//C8=)

Note the sketch app notes a slightly different line number, I believe it's the same error. Any ideas?

For what it's worth, I actually made this work once... but now I can't seem to :/

**Comment by techninja** [comment]
In addition to this wacky, open, single multi-self intersection path
![Squiggle](http://i.imgur.com/lTGvq16.png)

I'm looking for divide support for [two open overlapping curves:](http://sketch.paperjs.org/#S/jVTLbhtHEPwVghc5wHAw/ZruVpBTfsBADjlQOsjW2iIkUwElOwfD/56a2VWAnGIeyOVsV7+qar7vz3dflv31/o/H5fXjw77sPz7fj//f7i67p9N5od1vu/Py9+793evDu+835x0+L8vnL8v59eV6d1wPxud4lGaVmgsXalRFPfptObbS8N25JpPiGX+Omlm5sWuhnlW5E+H4wFklnHo59KjmrSlOrXokI6dUa0GxJfDqBmBhJoQSGY5Ro/VG5TBiOw30IUecaFGrNkqucOq1S3ovIlS7GTGO8ZhsWQ7SqjbrPHui6s6hhVt16WhpJBBrtbXMLJJUm7KNYJaRwAMNRGVO8plBqkiEFULPQblOwO7VoosURV3L9BHMXhXP2AC12j1iZkALHM3KOMIMK96AIgkC3qukdJ/LxrpIbdv77UrPbdl4e708Py6/Pz89X653V58vy3K++s+rP0/3rw/XO7k5//jl15vzzflNBfzzKjB1rIall4gqRJ3+FQEGkW5dNhWYKvRiSiWsKmkfcqHKaTZmxV7CVgpDnA28VPZs6/6sQSzK2EowFuE+ymBpwh1sH0aa5jmLNmitISXO3NqmgFG7N7eSs925Mh/yRTsHra1jtwOtNcUgXK6BLJv6wBixakLoVnsKj1BF+qZeDlxJjKf6CHD1jAJeXTJXeHOcQtRQhEEn69SQe0zlithKu6DD7EOjlWO0M5U3rGOBWOwCg4+eEIs2qCsGR3DP6DaTuig5moSc9a04waRJDOWijSaYeMVnODo6BIqa6HSTa08tgl8L2SbHsp3TC2aGs4K2TgPOo8lQcuurF4eTBzeqG1iRkpgDE2k1WwOBaQRixt60a8YES44jGNIGsysadwKKoLRishxZh7uqgFQejKcnDbQMz6fpWBwJ5LQKxqNGDwceT611ntVt+F95UInNt3llEeiIzpNK+JnXBJ1AbEDARXqHXkNjkxcSeAH9nWLWh4w6VjREqGBpQ4N0dxtorrgl34anzKbTHv/r2A9PX5efMOxleYFd5+Vd70/fTvfLu+nhNQJv66fT09NMiriry3J/hTe4+j9clrvHv55PMPX++nj74x8=)
![Open Curves](http://i.imgur.com/QM5YX4Q.png)

To make a clickable vector boolean fill work, every "enclosed" area of the path must become a complete and closed path. You can sort of get this to work by setting one of the curves above to closed, [though this leads to some very odd shapes](http://sketch.paperjs.org/#S/jVXLbhtHEPwVghc5wHAw/ZruZpBTfiBADjlIOsjm2iJEkwFFOwfD/56a3VUAAwESHsjZ3n5X1fDb9vz0edrut7+/TLcPz9uy/XA5jOevT9fN6XieaPPL5jz9tfnt6fb87tvDeYPP6/Tp83S+ve4394thfO7vpVml5sKFGlVRj/5Y7ltp+O5ck0lxxsO9ZlZu7FqoZ1XuRDDvOKuEUy+7HtW8NYXVqkcyckq1FhRrAq9uCCzMBFcigxk1Wm9UdsO304je5fATLWrVRsklnHrtkt6LCNVuRgwzjsmWZSetarPOc09U3Tm0cKsuHS2NBGKttpaZRZJqU7bhzDISeKCBqMxJPmeQKhJhhdBzUC4TsHu16CJFUdcyfTizV8UZG6BWu0fMGdACR7MyTJhhiTdEkQQh3qukdJ+XjXWR2rr3xwWex7LidrteXqZfL6fLdb+5+3SdpvPdD6/+OB5uz/uNPJy///Tzw/nh/MYC/v8sMHWshqWXiCpEnf4hAQaRbl1WFpgq+GJKJawqaR90ocppNmbFXsIWCEOcDbhU9mzL/qyBLMrYSjAW4T7KYGnCHWjvRprmORdt4FpDStjc2sqAUbs3t5Jzu/PKfNAX7ey0to7djmitKQbicg1kWdkHxIhVE0S32lN4uCrSN/Wy40piPLOPEK6eUYCrS+YS3hxWkBqMMPBkmRp0j5m5IrbALugw++Bo5RjtzMwb0rGAL3aBwUdP8EUb1BWDw7lndJuTuig5mgSd9a04QaRJDOaijSaYeInPcHS0CxQ10VlNrj21CH4tZJ0cy3ZOL5gZygpaOw0oj2aEkltftDiUPLBRXYMVKYk5MJFWs8URMY0AzNibds2YgyWHCYK0gewSjTsBRVBaMVmOrENdVQAqD8TTk0a0DM2n6VgcCei0EMajRg9HPE6tdZ6r29C/8oASm2/zlUWAIzrPUELPvCToBGADBC7SO/gaGiu9kMAL4O8Uc33QqGNFg4QKlNZogO5uI5orbsm34Smz6SyP/1Ts+9OX6d8Fuxo/nC6v02G/uV2/TD9o+Dq9QsHzfV4Px6/Hw/RulvXigbf14/F0muvA7+46He7wBv8G76/T08uflyN0vt3fP37/Gw==).

![Odd shapes](http://i.imgur.com/AEoTFav.png)

**Comment by techninja** [comment]
Another somewhat complex open curve example, but this time I ran it through illustrator's divide to see if I even had the right idea. Turns out I do!
![Illustrator Curve Divide](http://i.imgur.com/eBEt8Or.png)

On the right are two open, overlapping paths, and on the left is the result of the divide "pathfinder" command, four closed paths I've colored to emphasize separation. A result like this is absolutely ideal, too bad it's closed source!

Faking these as closed before running them in paper.js does not seem to help much, if anything it just seems to confuse the algorithm more. I'm starting to suspect that we're not quite ready for prime time on this. I'd hate to have to do some kind of [clipper-lib thing](https://www.npmjs.com/package/clipper-lib) to make this work :P

**Comment by lehni** [comment]
I think you should use whatever works for you.

**Comment by lehni** [comment]
I am not sure that Cilpper will get you what you want though, as I have a feeling it is going to work for closed polygons only.

Just because Illustrator does something in a certain way doesn't mean it, or somebody has "the right idea". Illustrator is wrong and buggy in many areas. While boolean operations for closed paths are well defined, it is up for debate for open paths.

Have you tried subtracting one path from an other with open paths in Illustrator, for example? Clearly Illustrator has a pretty wrong idea there...

Regarding your last sample: Since the paths are open and not filled, I would argue, you don't expect closed paths as a result, but open paths divided along the intersections... Both results can be defined as the correct behavior, because there is no defined behavior for open boolean operations.

The first example is clearly an error that I need to look into. But what outcome to you expect? Closed paths as well? Same discussion.

**Comment by techninja** [comment]
Well, that's not a bad idea. It is commercial. Who can I throw money at to make this happen? :D
