### ISSUE TITLE
item._parent is nulled after item.importJSON()

### ISSUE THREAD

**Issue by Drahoslav7** [paperjs/paper.js#1041]
In devel branch this happens:
```
path = new Path();
path.getParent(); // == project.activeLayer
path.importJSON(someValidJsonPath);
path.getParent(); // == null
```
It causes that paths imported from JSON can't be removed, because `path.remove()` fails.

**Comment by lehni** [comment]
You're right, and that's indeed a bug. [Here the sketch for it](http://sketch.paperjs.org/#S/ZZFfa4MwFMW/iuRFC6loqRu0+NS3MbZBHxMf0nitWaORmHWM0u++Gwui9S3nnt/9w8mNtKIBsiPHCzhZE0qkKb2+Cht0wtVBHrTwG3zhM1rteevrWvyBRaOz5huki4V06grvvoqENG1vNMTanKPwYYX00bN6tk9QGettvyruhIXWeWiQqumMdW/Hz48oZJz4EzihN056ODcI9pzsGGNZQtMkKShL6OY1fkm3m+0g1qNCyRChmafGMvVqIgZqMmw9m7YYlmZP/fPRyHEitemhxDOd/QHUldL6YLSx/vKUJsjdi3CRiqgc2GUoU2aIM66U7d2hVroM8nzAZ02+OOaOX3uyIC6dURgd7i/u/w==)
