### ISSUE TITLE
Question about performance of custom game loop

### ISSUE THREAD

**Issue by cjsauer** [paperjs/paper.js#1042]
Just a real quick question: if I implement a very simple game loop like this:

```js
setInterval(() => {
  paper.project.clear();
  myApp.updateEverything();
  myApp.drawEverything();
  paper.view.draw();
}, 100);
```

Does this perform well? In `myApp.drawEverything()` I'm creating all the paths, symbols, etc. What is the cost of clearing the whole scene and recreating the paths?

I'm running a simple simulation, so I don't need 60fps; I only need maybe 10fps maximum.

**Comment by Saltallica** [comment]
I don't think clearing the project each frame would be useful. Also, recreating everything from scratch every frame would be expensive. You lose the benefit of it's internal bounds caching,etc. Simply update the position or other properties of your items in your updateEverything() method.

You can also get rid of drawEverything(). Paper will handle the drawing for you using paper.view.draw().

Better yet, scrap all of it.

Look here:
http://paperjs.org/reference/view/#onframe

Instead, do the following:

```
view.onFrame = function(event) {
  myApp.updateEverything();
}
```

Paper will handle the drawing for you, and onFrame is a wrapper around requestAnimationFrame/setTimout (depending on your browser) will run up to 60fps, depending of course on your computer and the complexity of what you are trying to draw.

**Comment by cjsauer** [comment]
Is clearing the scene still expensive if I'm pre-building all of the graphics in an initialize step? Meaning I'm only actually newing Paths and Symbols *once*. Then each iteration I clear the scene and simply place symbols. Would that still be considered wasteful? The reason being that with my current setup it'd be a bit more convenient to do it this way.

**Comment by cjsauer** [comment]
I ended up refactoring my code around to fit your recommendation more closely. I'm now only updating the parts of the scene that have changed between ticks. It performs _considerably_ well when nothing has changed between ticks (surprise!), and performs just a bit better when even once symbol has changed between ticks. Granted my scene is very simple, so I imagine that margin would increase quite a bit in a more complex one. 

Thanks for your help @Saltallica
