### ISSUE TITLE
Meta keyup fires wrong event

### ISSUE THREAD

**Issue by georeith** [paperjs/paper.js#1051]
Use this to test: http://jsbin.com/dewatunazo/1/edit?js,output

To reproduce:
- press and hold `meta` key
- press and hold `c` key
- release `meta` key.

`keyup` event fires for both `meta` key and `c` although `c` is still depressed. This is not a browser issue as the link above also logs browser keyup events of which only one fires for the meta modifier.

**Comment by lehni** [comment]
You're right... Here [the sketch](http://sketch.paperjs.org/#S/Vc5NCoMwEAXgq4TZqCAeQOkJuixdNV3EOG0lOhPy0yLi3ZsIhTq7eTw+3gqkZoQWLgaDfkENmof8PyLpMDIJpjMuV1viGylUYpUk0mkmzxM2Ez/LwiqLrqjFXmkMLlUnaZMkaWAd5xwypThacRI/+AAeuN7xx/+BedEudmle71AZyyMFD+3tvn0B) for the issue.

**Comment by lehni** [comment]
Could you specify which browser and OS you're experiencing this on? I'm assuming it's on OSX and Chrome?

**Comment by lehni** [comment]
The problem is [this code here](https://github.com/paperjs/paper.js/blob/develop/src/event/Key.js#L111), and the comment explains why:
```js
// Fix a strange behavior on Mac where no keyup events are
// received for any keys pressed while the meta key is down.
// Keep track of the normal keys being pressed and trigger keyup
// events for all these keys when meta is released:
```
If we take this code out, then we go back to the issue where no key gets up events when it was pressed while the meat key was down. Irritating...

**Comment by lehni** [comment]
So this is known behavior... Without a workaround: http://web.archive.org/web/20160202174726/http://bitspushedaround.com/on-a-few-things-you-may-not-know-about-the-hellish-command-key-and-javascript-events/

**Comment by lehni** [comment]
I'm thinking that the current behavior is less bad than the one where keys get "stuck" while pressing meta. You can try it out by yourself here: http://codepen.io/alexduloz/pen/nteqG

Press: C
Press: Meta
Release: C
Release: Meta

And see C remain stuck.

And we might be stuck with this odd workaround... Shame.

**Comment by georeith** [comment]
Ah wow that's really horrendous. Neither prospect is great but I think you are right damned if you do, damned if you don't.

**Comment by lehni** [comment]
:(
