### ISSUE TITLE
Bug when asking for average color at point (0, 0)

### ISSUE THREAD

**Issue by arthursw** [paperjs/paper.js#1053]
There is a bug when asking for the pixel at (0, 0):

			raster = new Raster(image);
			raster.getAverageColor(new Point(0, 0));

[Here](http://sketch.paperjs.org/#S/bVHBboMwDP2VCE1qkKqIM2iHanSnHSa2nUoPGRgaFRLkBHao+Pc5oSB12il23vPzs32LtOwhSqOPK7jqEu2jytQ+L3Uz6sopo5nRuanGHrTL0QwcJopidit16UIsBgxvDo0cO8fjjCACJ4msUR2wZ7bwDKpWadkdQ1ZLJz9RatsACs+zp+ScrYUIsgakUg0/7JXQInxs4gsujO6MrIm2uX3wt2ipXrbeRX0fQ1RU7eDYgc/4TvXtLugSP3D/k90Uqbe0bvNWhISHulVkpYgW3GECJOjFdAa5L3g3ipome5bEK39+aG6x2lbmJJKGQLC02cBauPfx/XOwOW3yq3jjfolecvYreuLruDGNw4P5mu6X/rnnnvhxRof/JrHr4M3ZKD2d518=) is a sketch showing the problem.

This is due to the object type test in getAverageColor, line 5061 of paper-full.js:

```

// object.x == false when x is zero:

getAverageColor: function(object) {
		var bounds, path;
		if (!object) {
			bounds = this.getBounds();
		} else if (object instanceof PathItem) {
			path = object;
			bounds = object.getBounds();
		} else if (object.width) {
			bounds = new Rectangle(object);
		} else if (object.x) {                                                                       // false when x is zero:
			bounds = new Rectangle(object.x - 0.5, object.y - 0.5, 1, 1);
		}

```

**Comment by lehni** [comment]
Oops, that check is bad indeed. Fix coming up shortly!

**Comment by lehni** [comment]
[Updated Sketch](http://sketch.paperjs.org/#S/jVLBasMwDP0VEwZ1oISeE3YoS3faYXTbqe1BS5TM1LGL7GaHkn+f7DSBlh52suX39CQ965IY6DDJk48j+uonWSaVrUPcnE3llTXCmtJW5w6NL8meJPZ8S8Vlb/Y+3rMTxbPEBs7ay7RgiMEeSDRKo3gWI8+SapUBvYlRDR4+CYxrkLLAc7vVoZgSCaFG4lSDv+KV0W18mMVHPLNGW6iZNnd709+opTpoQxf1dYys4myPG40hkgvVtYuoy/zIfSQ7K3JtcH7ubRsDGfMmkYmStejXPRJDL1ZbkiHh3SouulqKVTrxh5vijqrZMg/EGhmhY2cja+Rexw/H2pXs5Nf2TQYTg+QQLHr4fdD+7/uiwpOcDEvZEBkzat6A/G4jliMAreVR87t6M6gRerxHuVJa8Mp98yDHUzDGJfnuMPwB) where drag'n'drop actually works : )
