### ISSUE TITLE
Working with Paths without adding them to the current layer

### ISSUE THREAD

**Issue by JCWolf** [paperjs/paper.js#1055]
I have two paths and I want to do some calculations before I render them on the canvas. The thing is I want the paper.Path object no to add to the current layer and add it manually after I do my calculations. 

Why? Because I want the user to see a list of what Path he has , the calculation result and then if he's satisfied, he can press the render button. 

When I run `var path =  new paper.Path()`  I get the error:' paper.js:2581 Uncaught TypeError: Cannot read property 'activeLayer' of null ' on the Initialize method for the Item here `layer = project.activeLayer;`. Of course , he can't read the paper.project member because I don't have any canvases on the page...yet. I need to skip these steps. 

Is this possible? 

Thank you!

EDIT:

I found that I can use paper.PaperScope and then create a new Project under the new PaperScope instance without the need of a paper.setup call(wich means I don't need an html element to use paperJS. It's pretty much what I want). Is this the correct way?

**Comment by iconexperience** [comment]
`var path = new paper.Path({insert: false})` or `var path = new paper.Path(paper.Item.NO_INSERT)` should do the job.

But your questions should be posted to the mailing list at http://groups.google.com/group/paperjs . Please help this keep this bug database free from support questions. Thanks.

**Comment by JCWolf** [comment]
Question asked on the [Google Group Here](https://groups.google.com/forum/#!topic/paperjs/MrHeOiKQ25I)
