### ISSUE TITLE
unite() operation causes "Uncaught TypeError"

### ISSUE THREAD

**Issue by iconexperience** [paperjs/paper.js#1056]
The following example causes a `"Uncaught TypeError: Cannot read property '_intersection' of null"`:

```javascript
var compPath = new CompoundPath();
compPath.addChild(new Path({segments:[
    [37, 41.61026653223258, 0, 0, 0, 0], 
    [70, 70],
    [137, 41.6102664209145, 0, 0.0002762135864031734, 0, 0], 
    ], closed:true}));
compPath.addChild(new Path({segments:[
    [136, 41.61026653223258, 0, 0, -0.00033133055456843977, 0], 
    [36, 41.6102664209145, 0, 0, 0.00007585019543654425, 0],    
    ], closed:true}));

var res = compPath.unite();
```

<a href="http://sketch.paperjs.org/#S/lVHLasMwEPwVoZMDrpG0Wsl26Sk/EOjRzsG1RGwSy8GP9BDy75UfDbjQQoUOGs3OMsPcqSsaS1P6frZDWdGQlq2ZcO5uRUfKtrkeiqEib8TZT7L3sB2dmb6C3WvuvvmoMGZf1RcTTGMzfe/tqbFu6NMsd8SfDHRIJI8UZ0IpBCFAYBwS9rzHkKyj2kPt8Qr5RioFS7jERRMxxoRWggPGSjLgGuSPbf5RXtremnToRvvY/ds4B/WH85fZAwAHYIgSVSwh0XqTZ7Ng43+NwDTGyHiCEhRKKXCWL+rfUywldbb3/TwTja4ebLDQvs+Pzhbna1v7QDTNjo8v">Here is the sketch</a>

The error occurs in <a href="https://github.com/paperjs/paper.js/blob/develop/src/path/PathItem.Boolean.js#L512">`tracePaths().findBestIntersections()`</a>, because `seg.getNext()` returns `null`. This again happens because `seg._path`is `null`.

The reason why `seg._path`is `null` is that the `Segment` has been removed in <a href="https://github.com/paperjs/paper.js/blob/develop/src/path/PathItem.Boolean.js#L787">`resolveCrossings()`</a>, but the intersection containing the segment is still lingering around. 

The easiest solution to solve this issue is to expect that `nextSeg` may be `null` in `tracePaths().findBestIntersections()` and adjust the `if`-condition accordingly (also, `isValid()` must be able to handle `null` values in this case). This solution is very simple, but I am not sure if the problem should not be tackled before, so the intersection is removed when the segment is removed.

@lehni Sorry for another boolean code issue, but this one is not simply another edge case that fails. This one throws an error causing a bit more damage and it seems to be happening fairly randomly. Also, the solution may be quite simple.

**Comment by lehni** [comment]
That's strange. `seg.getNext()` should only ever be `null` on open paths. I'll look into it.

**Comment by lehni** [comment]
This bug has disappeared, I guess it was linked to one of the other issues that I recently closed?

**Comment by lehni** [comment]
I just realized that I didn't read your suggestion thoroughly before. You are right, we should probably write bullet proof code for such potential scenarios. I am going to do that and then close this bug.
