### ISSUE TITLE
Very subtle, intermittent failure occurring during Path.unite(path). Only seems to occur when `this` is a CompundPath.

### ISSUE THREAD

**Issue by makoConstruct** [paperjs/paper.js#1058]
The problem boils down to failure during `p[0].unite(p[1]).unite(p[2])` . You'll have to open the dev console to see it because it doesn't always get fired by paper.js synchronously. Each of the ps were generated by relatively simple functions that calls closePath(true) at the end, so it's very difficult to figure out how a union operation between them could cause the following errors:
```
Boolean operation resulted in open path segments = 10 length = 238.68644220271852tracePaths @ paper-full.js:9726
Boolean operation resulted in open path segments = 4 length = 62.36701836567618 @ paper-full.js:9726
```

In the application, this error only occurs about every 1/27 specimens.

I've tried to reduce the problem further by just importing the Paths of a failing specimen from JSON instead of generating them from the `spec`, but some precision seems to be lost in the translation to and from JSON and the error stops happening.

I wish I knew more about what's happening here to refine the test case further, but giving you the spec rendering code seems to be the only way to get it to trigger.

I am using chrome 50.

http://goo.gl/b2BSlj

**Comment by iconexperience** [comment]
Here is an image for the two paths where the `unite()` operation fails:
![image](https://cloud.githubusercontent.com/assets/2122773/15672426/f0dd1c8a-2730-11e6-9819-d3c083d41069.png)
Actually, with the two overlaps in the outer path, this looks very similar to the example in #1054 and may have the same cause.

**Comment by lehni** [comment]
Nice, my fix in 648beb33e90821843f1b19143aaaf04f119bcc6d for #1054 appears to have resolved this. @makoConstruct could you please confirm?

**Comment by makoConstruct** [comment]
Ayyy, it works. :confetti_ball: :confetti_ball: :confetti_ball:

**Comment by lehni** [comment]
Bingo!
