### ISSUE TITLE
unite() operation produces wrong result, but no errors

### ISSUE THREAD

**Issue by iconexperience** [paperjs/paper.js#1059]
In the following example an incorrect result is produced, but no error messages appear. These examples are quite difficult to detect, because they can only be found visually.

```javascript
var p1 = new paper.Path({segments:[
    [428.48408954611784, 189.03444010371618, 0, 0, -21.46171522996096, 0],
    [369.18465116477694, 213.5984519858447, 16.376007921419017, -16.376007921419017, 0, 0],
    [209.1846511647769, 213.5984519858447, 0, 0, 16.376007921419017, -16.376007921419017], 
    [268.48408954611784, 189.03444010371618, -21.46171522996096, 0, 0, 0]
    ], closed:true})
var p2 = new paper.Path({segments:[
    [369.18465470031083, 213.59844845031083, 0, 0, -32.75201584283798, 32.752015842838006],
    [369.18465470031083, 332.1973252129927, -32.752015842838034, -32.75201584283809, 0, 0], 
    [209.1846547003108, 332.1973252129927, 0, 0, 0, 0],
    [209.1846547003108, 213.59844845031083, -32.75201584283798, 32.752015842838006, 0, 0]
    ], closed:true})

var res = p1.unite(p2);
p1.fillColor = "palegreen";
p2.fillColor = "mistyrose";
res.fullySelected = true;
```

<a href="http://sketch.paperjs.org/#S/jZPLbsJADEV/ZZQVldKRPe8BddUfqMSSsEjBPNSQREloVVX995pXoRCpRNnMtXPG11f5Ssp8Q8kwGb9RN1slaTKr5rvze96IGsWTKOlD1HlNjXzJu9Xgq6XlhsquHU6yUvAzMSpIEwyEaI1D9MGkAkOUoI0xgKA9OgypgP37qFBym0erVIwOomN5mh5Z2kWJwTiL6Iz3LjJLoZY2BmMxBhuM8Yx3UnsH4KNCgxGQtcc+ES7hCq7gvezDmHfeME3FCe7u20Kv/+OgBxQzZ0XV0nzYNVv6fsjKfRbqnix+92c8gEYI+uyRp7Mn7ZiFVtJbBcjWVdA+8nx/pQDgbsO5gGvux+i1sgrZj/I31MAb6BHjKRxxnc6J3guH87ZuYj1/2Gf5PrP/JHHIoqGWw6hRbst1R4NaPYyyko+LdVE8V0XVcDVL6rygZUNUZsmurK7Km3XbfTZM35cZKRfbovgcU0Gzjubcs7t0xH/ka0P5W12tOehkOJl+/wA=">Here is the sketch</a>

![image](https://cloud.githubusercontent.com/assets/2122773/15687394/bc0ec0dc-2774-11e6-8a5a-164b12fe7575.png)

The result is really strange, because a new point appears which is not part of either of the original paths. Also it is not near any of the found intersections, which are at the touching corners..

Here are the found intersections:
![image](https://cloud.githubusercontent.com/assets/2122773/15687523/8cc076c6-2775-11e6-9ed3-fbc29f79ead8.png)

**Comment by iconexperience** [comment]
So the extra point is added in `divideLocations()`. There is something in `<a href="https://github.com/paperjs/paper.js/blob/develop/src/path/PathItem.Boolean.js#L251">PathItem.Boolean line 251</a>` that I do not understand. In our case one location is at `1.9224074100213855e-8`
 and the other is at `3.5982861857463216e-8`, so basically at the very beginning of the curve. In `divideLocations()` these two time parameters are divided and the result is `0.5342563961800771` (basically in the middle of the curve), where the curve is split. This cannot be correct, I am confident there is a bug in `divideLocations()`.

**Comment by iconexperience** [comment]
Here is what I think is wrong in `divideLocations()`:

- if multiple locations are on the same curve, the `time` values after dividing the curve must be adjusted to the remaining sub curve, which is done by `time /= prevTime`. **But** if the curve was not divided previously because the previous `time`value was less than `tMin`. this must not be done. One way to do this would be to change <a href="https://github.com/paperjs/paper.js/blob/develop/src/path/PathItem.Boolean.js#L248">PathItem.Boolean line 248</a> to 

`if (prevTime >= tMin) {`

There may be a better place to handle these cases and maybe we have to handle cases for `prevTime >= tMax`, too, but this is basically all that is needed for the fix.

**Comment by iconexperience** [comment]
Oh, I have not run the unit tests against the proposed bugfix. Will do so tomorrow.

**Comment by lehni** [comment]
Great! But it's weird that this is required. Doesn't the sorting of locations mean that this shouldn't ever occur?

**Comment by lehni** [comment]
Oh sorry, I misread. Yes this makes sense!
