### ISSUE TITLE
What are Guides?

### ISSUE THREAD

**Issue by NerdGr8** [paperjs/paper.js#1061]
What do you call the squares that mark the corners of a selected path?

Are they handles or guides?

**Comment by sapics** [comment]
Sorry, I fail to get the meaning in "the corners of a selected path".

If it means bounds of path, you can get bounds of path by `path.bounds` which is Rectangle.
From the Rectangle, you can get all corners of bounds as http://paperjs.org/reference/rectangle/.

If it means the segment, you can get all segments by `path.segments`.
Each segment has handles. 

BTW, support questions should be posted to the mailing list: http://groups.google.com/group/paperjs
This is a bug database, thus, please help to keep free from support questions. Thank you for your undestanding.
