### ISSUE TITLE
How to implement mouse capture?

### ISSUE THREAD

**Issue by SebastianStehle** [paperjs/paper.js#1062]
Hi, I have a small control that I would like to use to resize another control. But I need mouse capture, so I received the mouseUp event, although when my mouse pointer is not over the control.

How would you implement it? I tried to capture the event from the layer but it is not bubbling up.

**Comment by sapics** [comment]
I guess that you need to receive `mouseup` event from `window`.

BTW, support questions should be posted to the mailing list: http://groups.google.com/group/paperjs
This is a bug database, thus, please help to keep free from support questions. Thank you for your undestanding.
