### ISSUE TITLE
Draging view with mouse

### ISSUE THREAD

**Issue by olivbau** [paperjs/paper.js#1063]
Hello, I just want to drag the 'global' view with the mouse.

I tryed this:

```HTML
function onMouseDrag(event) {
  view.center -= event.delta;
}
```

But the results isn't really great : https://youtu.be/5fygEzR61eA
Globally it's work but there is some 'bumps'.

note : i prefer do not use jQuery

Thank you

**Comment by sapics** [comment]
Below code might be less fluctuation. Please try it.

```javascript
var c;
function onMouseDown(event){
  c = view.center.subtract(event.point)
}
function onMouseDrag(event){
  view.center = c.add(event.point);
}
```

Btw, support questions should be posted to the mailing list: http://groups.google.com/group/paperjs
This is a bug database, thus, please help to keep free from support questions. Thanks.

**Comment by Domvel** [comment]
The example above pans the view relative on each step (drag event). It's a very annoying behavior. Try this to absolutely drag the view like expected. It's 1:1 pixel perfect position.

```js
function onMouseDrag(event) {
  // The first lastMousePoint comes from onMouseDown.
  lastViewCenter = paper.view.center;
  paper.view.center = paper.view.center.add(
    lastMousePoint.subtract(event.point)
  );
  lastMousePoint = event.point.add(paper.view.center.subtract(lastViewCenter));
}
```

![demo](https://user-images.githubusercontent.com/35452565/58245349-e2f5df80-7d54-11e9-9436-63ab37c82436.gif)

**Comment by ledhieu** [comment]
I wish I came upon Domvel's  comment earlier. Another approach without onMouseDown would be

```javascript
let oldDelta = new Point(0, 0)
function onMouseDrag(event){
    view.translate(event.delta.subtract(oldDelta))
    oldDelta = oldDelta.subtract(e.delta)
}
```
