### ISSUE TITLE
getInteriorPoint() is not reliable

### ISSUE THREAD

**Issue by iconexperience** [paperjs/paper.js#1064]
In rather simple cases the function `Path.getInteriorPoint()` can return a point that is outside the path.

Here is a simple example (<a href="http://sketch.paperjs.org/#S/bZFNa8MwDIb/ivApgZBmHYPhsVNPuxV2THpwEyUxcaxgK+uh9L/P7pY2HZPBWA/68CudhVUjCik+B+S6F5moqYn+l3IwwTtYPMGkJnT5XnGfnD12I1r2sqwsBCufiiKDcB0yWMjLQh7A6x1si3/BKmX7t8YVbNdFi1/w44f2tSGPjWQ3YwaeHQ24I0NOQiVGbPQ8eqMYj2bGSlzSylY2qtSW0WlyewqvoHjKO+SPNUzStxi82QCjZ9BtmAj3wL22gwfNUJNlpa0PCGGKKZUNzJPB3FCXTPkSkTx0S2NhuNu1R+PUCRpiUAwtzba5/XApHXcSt5HvtKsNJucaY4R8lJKBU0G0l/CcQauNuQ2DaVRMywziCXs/OlTDtYEXsjxcvgE=">Sketch</a>):

```javascript
var p = new paper.Path({segments:[
    [100, 100], 
    [150, 100],
    [150, 180],
    [200, 180],
    [200, 100],
    [250, 100],
    [250, 200],
    [100, 200]
    ], closed:true})

var interiorPoint = p.getInteriorPoint();
```

![image](https://cloud.githubusercontent.com/assets/2122773/15859096/e3349ade-2cc3-11e6-891a-e97f66822d34.png)

This behavior is caused in `getInteriorPoint()` by the algorithm to find an alternative point after the first guess failed. This algorithm seems to be broken.

A better algorithm may be this:

1. Get y-monotonic curves of path
2. Cast a horizontal ray through the center point of the bounds
3. Find the x-value of all (!) intersections with non-horizontal y-monotonic curves (make sure that crossings at curve's start/end point do not get counted twice)
4. Sort intersections (!)
5. Use the middle between intersections at index 0 and 1 for the x-coordinate of the interor point.

I am a bit puzzled that this bug has not been found previously, but a little testing showed that the first guess of `getInteriorPoint()`, which is simply the center of the path's bounds, is usually correct, and the algorithm for finding an alternative point is not called often. And in those cases the current algorithm usually produces a correct result.

**Comment by iconexperience** [comment]
There are three problems with the current algorithm for finding an alternative interior point.

1. If the horizontal crosses at a curves start point, the intercept is counted twice, because on a closed path a curve's start point is always another curve's end point. <a href="http://sketch.paperjs.org/#S/bVJBasMwEPzKopMNxnFTAkUlp5x6C/QY56BYm1hY1hpp3RxC/l4prZO4VALBDqOdnZEuwqkehRSfHXLTikI0pFP9pTwMsAaHZxjUgL7cKm6zS8BTj46D3NUO4tq9VFUB8dgXMCGrCZkBq0RZLEBpjRq4NQEGMo5npLfHrWX1L/DUd/lX6AYsn5WrX+CnjgM0lgJqyX7EAgJ76nBDlryEWvSozdgHqxgPdsRaXPPa1S5FEedEb8hv08QxlqE8IX88g1n+nsjRIGNgMMcYG7fJp+sCGIaGHCvjQoRwch6xQBZLS6dsKCdGNlPLU2N4rJuG9uoMmhgUw5FGp+8TTq3Tw6UnKzfGNxazS4OJIedWCvAqmg4SXgs4GmvvYTD1imnKIO34OQ4eVXcTCELu9tdv">Here is a modification of the example</a> in which the first and second found intercepts are the same. As a result a point on, not inside the path is found.
2. The algorithm stops after finding two intercepts. This is what causes the issue in this example, because the intercepts are not counted from the left.
3. Even if the algorithms did not stop after finding two intercepts, the intercepts would sill have to be sorted by x-value to ensure that the intercepts at index 0 and 1 are the leftmost ones.

<a href="http://sketch.paperjs.org/#S/bVVNj9owEP0r0xy2iTabDVSrVrD0UE49VFqpxySqTOKAl2BHtgOLKP+9YzsfZrdEIvh5Zt543ni4BJwcaLAIfu+pLndBHJSiMusXondJK4UW+tzSZEv1T66pZEK+CMY1rKDueKmZ4GEEl5zn+kgkbETHK4WbeseUcfphgTCKjUWu297X2RmDNTVhQy07Gi2NEash/GTdS8E1YVyF1ivqaRxR2ckjHYn+YKBfgou1RUe2XEshtLHKihE649IGTM4jxkwOJW1726XDayEhNGQM0TSGBl+ON2ko3+rdEneeocHX/f2YncvvSJrO5uccMlYkDloOVo+PUAngQkOJxcBvKZRifKuAaCDO77MCpYnULmHQAlpJj1ixmyDdpqEuCLqPR8IyhhP5ifEKd2G1WsFssDHP3R2c4XufbzYrwALPqwH5WvjWf/8aa2+zN5/8I68QvVT2eCuw4iRKNEe67jasDJ1PDLMYzjFYqWJT51m0nCKMIryaYtpQDzBb4hLTSPH98HDD6IuZtJ3ahY4XO8Q27shq+bLXIkrefL7r8PP6USilRQukxvBQ9/XUJwETYQwbWpJOUWxL6kvnxRK13WzxfgHhlVlIiqd0Po0oiblUg1nNpNKGxYvgdWtJOFLajuFnUHR7GJujzx/tlcA0JqecQ//xKmVsQlOHYc9dkTcsejiZZWkB956b0RseYW79ekpJdSe580f8amqLj5GwxWicnsDMlvDSZ6sWmWPNZqkRP02LGAbkaUBugKf3wLcJmKf/BbwY8/dBLTD3WdIecGvMp2yEotXCTKkYdZViT9eiEXIBeXCgFesOqiGabrC18uAaDQdm70Zm+2GO2prnHFXSFIXGW2sbA6ca3ytgZji4IeiaxvUSYniNaNKIbdhOY/KGLfLFxI/lqCQ5YTNr0zC1GcFjhkPoQZ5kzWTZ0PBS2vm8uD0K3h6Ch1YL+BJjizbNWAwtDkSLoQbmwb+UjaRkbwlUsMiK6z8=">Here is a sketch with an improved implementation of `getInteriorPoint()`</a>. This should work in all cases.

**Comment by lehni** [comment]
Looks great! Could you add some unit tests for the currently failing edge-cases?

**Comment by iconexperience** [comment]
@lehni
Yes, I will do that. But currently I am very busy with testing. There may be more new issues before I find time to work on that.

**Comment by lehni** [comment]
@iconexperience I've taken care of it now, so you can see what it takes. It's not much at all, but it's super useful to have it included, as context-switching for people not close to a given issue (e.g. me) is hard and takes time...
