### ISSUE TITLE
No intersections reported between two straight paths

### ISSUE THREAD

**Issue by iconexperience** [paperjs/paper.js#1066]
This is a stunning example where our intersection finding fails. The two paths consist of a straight curve each. Both paths clearly cross, but no intersection between the paths is reported.

![image](https://cloud.githubusercontent.com/assets/2122773/15928741/03c4df62-2e49-11e6-8f76-d27a387ff7d0.png)

```javascript
var p0 = new paper.Path({segments:[
    [230.4447915660904, 300],
    [230.4447915660904, 180]
    ]});
var p1 = new paper.Path({segments:[
    [221.5842044289023, 189.47264666691018, 0, 0, 9.363067822501023, 28.089207003036847],
    [249.67341143193917, 273.74026767602066, -9.363067822501023, -28.08920700303679, 0, 0]
    ]});

console.log(p0.getIntersections(p1).length);
```
<a http://sketch.paperjs.org/#S/jZJNb8IwDIb/SpUTSCVyPkga0E477TaJI+2htKZUhKRKA9OE+O8LoGnf0pxcrOf1a1vJmbj6gGRBVnuMzY7kpPHtNT/VIRsge8gcvmRDPWCgz3XcTc4jdgd0cVysS5elWHMBVEqpDZsrBQZkngmAKv8bswKqO60u02Xpbr3Yv3pxRueF5CAlLwxwcTUzVGqupEphGLAiz+B2DRVKgNIF53NgNzEvKBSGgwYQIFQh9cec0lClhWRMCmaEYTrJtaBaAlc6HeCgVJ7NfrGdffPV5j7Dly0HoGMMfo+P3vqQti2JD82ub0typewntf0J21Bv7oL38lVT2951SbKt7Yifa39F26O1ryu02ERsE4rheCWla7wbvUVqfTdJ7h3GJxcxjEnYJzQZ2JRadF3cTZfpY2wC1vvB9+k9yGJNmCLV5Q0=</a>

As you can see on the image above, `p1` is not actually a line, but a curve of which ìsStraight()` reports `true`. If you remove the handles and make a real line of it, the intersection is found.

This issue occurs because `isStraight()` for both curves returns `true`, therefore `addLineIntersection()` is used to find an intersection between the two. An intersection is found, but the problem occurs in `addLocation()`, where calling 'Curve.getTimeOf(v1, p1)' returns `null`, because `p1` is a slight curve and the found intersection is not exactly on that curve. Therefore the intersection is not added to the found intersections and no intersections are reported.

**Comment by lehni** [comment]
Oh dear :) What do you suggest we should do?

**Comment by sapics** [comment]
@iconexperience

> isStraight() being not strikt enough

means that the green path isStraight() is false?
(Sorry, my bad English)

http://sketch.paperjs.org/#S/vVZdb9owFP0rHg9N0kJGnD7RD6maphWppdVaaZOgD05iICLYzDFMGu1/37VjiB2Iur4sSPnwOb73nmNfi22HkSXtDDpPCyrTeafbSXmmvjdEoCJnFF0hRn+jRyLn4R18+9sJQ3BNBV8OxlG/30Vwe+lWo5IPxrgxVkrBF/QLL7gYeElB0oU3YW/BxYRNmMqygtARpFHZwrTgkCOYMD0aSkFYWRBJ/SrmHrCCwlRP0MzbQ3S2pEyW4/4LvMtbwrKCPqylr4vtq8QNYmQRh8zv1cSUs5IXNCz4zPd6cKHHm+dbFCH17gUNwujrD5SXT1B0PptLr4skLaWvkwWBLRdDzVUNRq+pCbcJxk3BM0Ep8/Zgm2TsSMbtkvF7kvFHJWNXcmwk44bkuE1y3JTMgTej3h5t03zuaI7bNZ+/pzn+qOa40jxds1TmnNVAYLrGifPwffhtOLq5c4MpepiuxYZqaTXmq+AqSHXXxvKcycg46ziiEdOA6tLf+IAZHTI3iqTZYblOIHcKEnSewGLNj2ad7xbBZh7NOjercFER8ynyN2HGpQ+tgi5RH72+IjOAA3QNy4S2dUxB5VowNCVFSU2EN8uVPmSsJh8WvopdEDtgtAehN0mW7QI4JFyTcE3CDoko0bB/YA+dqhln1QscHFCexUsUD3oL+kvDZy6cKvhgUpaXqciXOSNMAiGBqQlwCDxTy1CHdnncQinWloO1h+UvoULf63WDdyeYLVRvvx7yEyhdEQP0GREbxzu8V+Mm475PEvonp8KXgVWgqmIJc5V6eXFQ+PIUfsqzPjqrQXXFCjmVxs9DTFYYbmJyh8RNQ5SZoPP6CvblyYmSfAl1OXbqfafWwiiJAqvkfOp/8ldq/koHWKn5q9hOD9u9GjUExYXTZOuW6Bwf9zc/0ePDcPQcqVPDztdOxUDdlYh350nDWburjA3WQ3uBay/w+17g/+gFPubFPwlzGwIG4b9QIihZ6O4uO4Pxy9tf

**Comment by sapics** [comment]
Uups, sorry I miss understand.
Your suggestion is that isStraight() should be same as !hasHandles()?

**Comment by sapics** [comment]
Oh, sorry again. I understand that you need calm :)

**Comment by iconexperience** [comment]
@sapics  ごゆっくりどうぞ  :)  (can you say that in this case?)

`getTimeOf()` has a tolerance of `GEOMETRIC_EPSILON`, which is `2e-7`. If on a curve that returns `true` for `isStraight()` there is a point that is further away than `2e-7` from the direct line between the end points, we can have that case that `getTimeOf()` can return `null` for points on the direct line between the end points.

I guess the following image is easier to understand (the curve is certainly exaggerated):
![image](https://cloud.githubusercontent.com/assets/2122773/15930166/afa1d8a0-2e51-11e6-8447-d4d47da9023a.png)

Now the question is, does 'isStraight()` make sure that the distance is always < `2e-7`?

**Comment by lehni** [comment]
Nope :)

**Comment by lehni** [comment]
I feel like I will have less and less time to focus on such details in Paper.js... I'm not sure how to handle this in the future. Would you be interested in taking the lead in the geometry department, @iconexperience ? I need to find back to being able to manage the project itself, including healthy release cycles and the implementation of other urgently needed features. It is really tricky to handle all this, especially when zooming into the range of < 2e-7... What do you think?

**Comment by sapics** [comment]
Sorry for late response, I eat dinner 🍙.
And I take several long breaths to calm myself down :)

Your japanese is very well! I guess that you mean "take your time".
It's perfect :)

Thank you for your explanation with kind image. I understand what you mean.
The consistency of each EPSILON looks very difficult problem.
The epsilon for CURVETIME is come from time which is 0<=t<=1, but GEOMETRIC epsilon come from the path size which is not limited :)

**Comment by iconexperience** [comment]
@sapics Yes, the different epsilons make things difficult. I think we have been testing with curves up to around 1000 pixels, and maybe we should stay in this range with our tests.

Currently we are using `isCollinear()` to determine if a curve is straight. This normalizes the length of the handles to 1, so it does not take the absolute difference between the curve and a straight line into account. We could additionally check if the distance from the handles to the line are < `2e-7`. This would be easy, but not so great for performance.

But what does `isCollinear()` doing anyway? Do you understand what
` Math.abs(x1 * y2 - y1 * x2)
                    <= Math.sqrt((x1 * x1 + y1 * y1) * (x2 * x2 + y2 * y2))
                        * Numerical.TRIGONOMETRIC_EPSILON`
actually calculates?

**Comment by iconexperience** [comment]
@lehni I can fully understand (BTW, conratulations to SFMOMA, that is just great) and I would rather spend my time on other things right now. The only  reason why I am posting the issues is I am testing the paper boolean operations on thousands of Graphics and these are the remaining issues that keep popping up.
Let me think about how I can handle this.

**Comment by sapics** [comment]
1000px looks reasonable value for real usage.

I don't understand well for the `isCollinear()` calculation.
I only understand, if `Math.abs(x1 * y2 - y1 * x2) / Math.sqrt((x1 * x1 + y1 * y1) * (x2 * x2 + y2 * y2))` is enough small, the path looks straight :)

If isStraight is much slower than before, by caching the result of isStraight to _isStraight, we might be possible to reduce the performance problem. (Of course, it is necessary to set this._isStraight=null in changing the curve everytime :))

**Comment by lehni** [comment]
See here, in `Point.isCollinear()`:

        isCollinear: function(x1, y1, x2, y2) {
            // NOTE: We use normalized vectors so that the epsilon comparison is
            // reliable. We could instead scale the epsilon based on the vector
            // length. But instead of normalizing the vectors before calculating
            // the cross product, we can scale the epsilon accordingly.
            return Math.abs(x1 * y2 - y1 * x2)
                    <= Math.sqrt((x1 * x1 + y1 * y1) * (x2 * x2 + y2 * y2))
                        * /*#=*/Numerical.TRIGONOMETRIC_EPSILON;
        },

**Comment by iconexperience** [comment]
`Math.sqrt((x1 * x1 + y1 * y1) * (x2 * x2 + y2 * y2))`  is the same as `length1 * length2`, which is the normalization mentioned in the comment.

**Comment by iconexperience** [comment]
A simple additional check in `isStraight()` would be this:

```javascript
if (Math.abs(Line.getSignedDistance(0, 0, l.x, l.y, h1.x, h1.y)) > Numerical.GEOMETRIC_EPSILON ||
  Math.abs(Line.getSignedDistance(0, 0, l.x, l.y, h2.x, h2.y)) > Numerical.GEOMETRIC_EPSILON) {
  return false;
}
```
This would do the job, but it's a bit clumsy and has at least a small negative performance impact. Let's look for a more elegant solution.

**Comment by lehni** [comment]
What if that's the only check performed?

**Comment by iconexperience** [comment]
That alone would probably not be enough, think of curves where the handles are on the line but pointing outwards. I would not consider them "straight" curves. But maybe testing if the distance is below geometric epsilon and if handles are pointing towards each other would be sufficient. If they are not pointing towards each other, we can still check their length with `isZero()`.

But even if the handles are pointing towards each other we should check if their length sum does not exceed the distance between the paths, because there may exist some freak cases with extremely long handles.

This could work
```
if (distance of handles from line is less than geometric epsilon) {
  if ((handles 1 is pointing towards p2 or length is zero)
      and (handle 2 is pointing towards point 1 or length is zero)
      and length sum is less than length of line) {
    return true;
  }
}
return false;
```

**Comment by lehni** [comment]
Yeah you're right of course. That's all handled quite well by the projection, though.

**Comment by lehni** [comment]
This bit I mean:
```js
// Collinear handles. Project them onto line to see if they are
// within the line's range:
var div = l.dot(l),
    p1 = l.dot(h1) / div,
    p2 = l.dot(h2) / div;
return p1 >= 0 && p1 <= 1 && p2 <= 0 && p2 >= -1;
```

So we could just replace this...
```js
} else if (h1.isCollinear(l) && h2.isCollinear(l)) {
```

...with your `Line.getSignedDistance()` checks.

**Comment by lehni** [comment]
Also, are you sure it should be `Line.getSignedDistance() > Numerical.GEOMETRIC_EPSILON`, and not `Line.getDistance()`?

**Comment by lehni** [comment]
@iconexperience this works like a charm, not breaking any existing tests, and I like the implementation. Please let me know your thoughts, and thanks for debugging this!

**Comment by lehni** [comment]
@iconexperience we made a mistake here, see #1269...
