### ISSUE TITLE
Unite operation wrongly fills inner path

### ISSUE THREAD

**Issue by iconexperience** [paperjs/paper.js#1075]
Here is an example that may be caused by the `tracePath()` function. The unite operation should result in a path with a rectangular hole, but the hole is filled instead:

```javascript
var p1 = new paper.Path({segments:[
     [150, 120], 
     [150, 85], 
     [178, 85],
     [178, 110], 
     [315, 110], 
     [315, 85], 
     [342, 85],
     [342, 120],
     ], closed:true})
var p2 = new paper.Path({segments:[
    [350, 60],
    [350, 125],
    [315, 125],
    [315, 85],
    [178, 85], 
    [178, 125], 
    [140, 125], 
    [140, 60]
    ], closed:true})

var r = p1.unite(p2);
r.fillColor = new Color(1, 1, 0, .2);
p2.strokeColor = "red";
p1.strokeColor = "green";
```

<a href="http://sketch.paperjs.org/#S/jZLBboMwDIZfJcqJSgjhULaKaqe9wKQdSQ8ZeC2CJpFJt0PVd18IXYG1h+UUf7Z/+49y5lodkRf8vUVXHXjMK1MP8ZciZoG9MI3fzCqLlLwpd4jOPe6PqF1flFKz4ZSQpzEDke5itkCbfE6eNyNZAIB5Vwb5Q7QQytZiKRRAGH8lvrjqTI914eiEl5XUwYz4h5kyGxZ/ummNMYh8AmHHv2DaZzLK5iB03Mg6fUT82DG8NzBaIO/AQnLSjcPIitVWako+m657NZ2hq71wj8APiJkXTUKZFUnvyLT4Wyk5YS35kIK71J4QdUj6//BBqFprGv9KvCh3lx8=">Here is the sketch</a>

Expected result:
![image](https://cloud.githubusercontent.com/assets/2122773/16009912/01626b02-317f-11e6-831c-0592194bd0d1.png)

Actual result:
![image](https://cloud.githubusercontent.com/assets/2122773/16009894/ef70d3de-317e-11e6-8d4a-aa7247db08d8.png)

**Comment by iconexperience** [comment]
Sice intersections are found, four are overlaps (green dots), two are crossings (red dots). All looks correct.
![image](https://cloud.githubusercontent.com/assets/2122773/16010078/d555701c-317f-11e6-9b81-fdd139d5994a.png)

**Comment by lehni** [comment]
Just when I thought we were in a great place with the boolean code base. What's your feeling about the other stuff I worked on today? I want to release v0.10.0 soon, wether boolean is perfect or not. Seemed like now was a good time.

**Comment by iconexperience** [comment]
Here is the windings of the tested points and of the curves (green = 1, blue = 2). The horizontal curves marked with an arrow should be green to get a correct result.

![image](https://cloud.githubusercontent.com/assets/2122773/16010335/00af9ee4-3181-11e6-9aee-fcf89f5fc5d1.png)

**Comment by lehni** [comment]
@iconexperience do you mean vertical? and does the fact they're not green mean that it's an error in `propagateWinding()` or `getWinding()`?

**Comment by iconexperience** [comment]
Yes, vertical. And I think it's an error in `getWinding()`, but I have to check in detail.

**Comment by lehni** [comment]
I'm pretty sure that the top two intersections are crossings, not just touching points. That's the problem here IMO (code used to draw them):

```js
p1.getIntersections(p2).forEach(function(inter) {
   new Path.Circle({
       center: inter.point,
       radius: 3,
       strokeColor: inter.isCrossing() ? 'red' : 'green'
   }) 
});
```

**Comment by lehni** [comment]
This could be a case of using the wrong boundaries in angle comparisons?

**Comment by lehni** [comment]
Oh wait, it's more complicated.. In both places have two overlaps that follow each other. Neither of those is considered to be a crossing, but together they cross. I was aware that this will probably come to bite us at one point, here it does. I think I wrote about this before somewhere. Darn...

**Comment by iconexperience** [comment]
I think I understand. The crossing does not happen in one point, but the paths come together in the first point, run an identical way and then separate to opposite directions than before. How about giving an overlap some information on how the curves are ordered? If the order changes between two overlaps, there must have been a crossing inbetween.

**Comment by lehni** [comment]
Yes we need something along these lines. The problem right now is that when we get the list of intersections, the intersections know about the curves they belong to, but the curves don't know about the found intersections, and we don't have a way to connect them all until later when we start splitting. We might need some post-processing in `getIntersections()` that walks through all found intersections and realizes that there are such overlaps following each other, and then has one of them turn into a crossing... Tricky stuff.

**Comment by iconexperience** [comment]
You probably understood what I mean, but here is an illustration:
![image](https://cloud.githubusercontent.com/assets/2122773/16011029/14c0162c-3184-11e6-8cba-c0cf00780a98.png)

At the first intersection we have overlap -> green -> red, at the second we have overlap -> red -> green. The direction has changed, therefore a crossing must have taken place.

**Comment by lehni** [comment]
Yes but we can only decide that if we can compare the two following intersections. And we can only do so, if they know of each other, which currently they don't.

**Comment by iconexperience** [comment]
Ah, ok. I though it was a problem about knowing which curve belongs to which path. For this we could simply use the path ids. If the lower path id is first when walking clockwise, the overlap is of type 1, if the higher id is encountered first, the type is 2, otherwise the type is 0.

**Comment by lehni** [comment]
Déjà vu: https://github.com/paperjs/paper.js/issues/874#issuecomment-168332391

: )

**Comment by lehni** [comment]
The difference being that there we were looking at those in context of `#resolveCrossings()`, within the same path.

**Comment by lehni** [comment]
And there is this code comment here: https://github.com/paperjs/paper.js/blob/develop/src/path/PathItem.js#L333

This requires some substantial refactoring. I don't think I have the time to focus on this any time soon... Do you feel like tackling it? I could outline what I believe is required.

**Comment by iconexperience** [comment]
Well, if you have no time I will have to do this :)

**Comment by lehni** [comment]
I have just done a test: In the `_path1.getCrossings(_path2);` call in computeBoolean(), all overlaps are returned as crossings currently. I then manually delete two of the four out, one on each side:
```js
crossings.splice(0, 1);
crossings.splice(2, 1);
```
And then I get this result:
![screen shot 2016-06-13 at 17 17 01](https://cloud.githubusercontent.com/assets/213275/16012648/b00dc696-318a-11e6-950b-d2817cbe1fe9.png)

So I think we can take this as confirmation that we're on the right track.

**Comment by lehni** [comment]
As for the time, like I said before: boolean operations have taken so much more time than I have ever wanted to devote to it, without any funding for this work whatsoever, and no personal need for it in any of my current projects, that I have a hard time rectifying all the time I'm spending on it, other than the fact that it's very interesting and addicting work. But it gets harder and harder to make time for it.

**Comment by lehni** [comment]
@iconexperience let me see what I can come up with. It may be easier to tackle than I thought. Meanwhile you should focus on those mono-curves : )

**Comment by iconexperience** [comment]
@lehni I will. And I have some nice little otimizations waiting here for you :)

**Comment by lehni** [comment]
Sounds great! I may I have to roll out v0.10.0 first, though, as otherwise it will never happen...

**Comment by lehni** [comment]
Hmmm! I'm starting to think that maybe what I wrote above isn't actually the issue, after all.

Having too many intersections returned shouldn't be problem, because the code that walks and crosses the contours should decide correctly where to walk to. So perhaps you were right, and the actual issue is in the winding contributions? I'm weary of changing the code that filters intersections because there are a ton of side effects...

**Comment by iconexperience** [comment]
With my new winding propagation implemented the windings are found correctly, but the hole is still filled:
![image](https://cloud.githubusercontent.com/assets/2122773/16018167/90577dec-31a3-11e6-896e-fe8e15d1bf58.png)

This almost looks like `tracePath()` is missing something really trivial.

**Comment by lehni** [comment]
Oh well that's good news already. If you merge this in, I can look at the `tracePath()` part!

**Comment by lehni** [comment]
@iconexperience so I wait for your code here?

**Comment by iconexperience** [comment]
Yes,I should have it ready before the weekend.

**Comment by iconexperience** [comment]
@lehni I have something now on https://github.com/iconexperience/paper.js/tree/new-propagateWinding
It is far from perfect, but it works and it gives the correct winding for this example (the two inner points on the vertical lines have a winding of 2 and `contour` set to `true`). 

If you create a `propagateWinding` path I can create a pull request. I do not think this should go into the `develop` branch yet.

**Comment by lehni** [comment]
You mean branch, right? No need for a PR, I can just move your branch over.

**Comment by lehni** [comment]
BTW, another convention detail: Branch names should not contain camelCasing. Short, lowercase, with dashes, and descriptive is the general convention. So perhaps `new-winding` (which is better than `patch1`, ...).

**Comment by lehni** [comment]
But I will first roll `v0.10.0` out I think. I can't wait longer and this risks opening other cans of worms again...

**Comment by iconexperience** [comment]
No problem. I will try to write some explanation on what I have done meanwhile.

**Comment by lehni** [comment]
So here it is: https://github.com/paperjs/paper.js/tree/new-winding

**Comment by lehni** [comment]
I did some quick changes that I saw right away. I love it when things simplify this way :)

**Comment by lehni** [comment]
BTW, I wonder if we should make `path.getInteriorPoint()` a private function? It seems kind of random, but is of course useful...

**Comment by lehni** [comment]
Out of curiosity, when you say far from perfect: What are you not happy with in the code as it is? If it's just formatting, then I am happy to brush it up.

**Comment by lehni** [comment]
@iconexperience couldn't help myself and brushed things up a little: e80b2ff043a3e835d98e0a12efebd2baee4d3a02

**Comment by iconexperience** [comment]
No, there is more. The iteration in `getWinding` is quite clumsy, comments are missing, and the winding adjustments in `addWindingContribution` can certainly be more concise. Give me one or two days and it will become better.

**Comment by lehni** [comment]
It tumbles out naturally : ) Would you mind calling `splitToMonoCurves()` just `getMonoCurves()`?

**Comment by iconexperience** [comment]
I looked at what is happening with the original example of this issue and found that <a href="https://github.com/paperjs/paper.js/blob/develop/src/path/PathItem.Boolean.js#L579">line 579</a> in `Path.Boolean` prevents the start point of the inner path from being found. I am not exactly sure what the line does exactly. Here it is:
`|| !seg._path._validOverlapsOnly && inter && inter._overlap`

**Comment by lehni** [comment]
@iconexperience now that v0.10.0 is out, can we merge this into `develop`?

**Comment by lehni** [comment]
@iconexperience there's still that one failing test (open, filled path). Here is how the path looks and which point gets tested. It's probably just a question of making sure that we "close" open paths with a straight line in these checks.

<img width="229" alt="screen shot 2016-07-13 at 10 09 55" src="https://cloud.githubusercontent.com/assets/213275/16796264/0dc7485c-48e2-11e6-9b41-05fab9ead4bc.png">

**Comment by lehni** [comment]
@iconexperience here the code that used to handle this: https://github.com/paperjs/paper.js/commit/a328f5b04b56b37d4052bdd0a56c5911cc3e8b90#diff-83b0f841b43dce90324008de0d976e25L1010

**Comment by lehni** [comment]
@iconexperience I was trying to add support for this, but I don't understand the current implementation of `getWinding()` (it needs more code comments). Could you explain this part?

```js
                prevV = null;
                var prevCurve = curve.getPrevious();
                while (prevCurve && prevCurve != curve) {
                    var v2 = prevCurve.getValues();
                    if (v2[1 - coord] != v2[7 - coord]) {
                        prevV = v2;
                        break;
                    }
                    prevCurve = prevCurve.getPrevious();
                }
```

**Comment by iconexperience** [comment]
@lehni This part of the code walks backwards through the curves of the path and tries to find the last non-horizontal/non-vertical (depending on the `coord` value) curve in the path.

I have just pushed my new changes to `iconexperience/new-winding`. This is the code that I am working with currently. The changes are here:  https://github.com/iconexperience/paper.js/commits/new-winding

I am again quite busy at the moment, but if you have some time I will put priority on this issue.

**Comment by iconexperience** [comment]
There is another failing test with my current code, which is "nested touching circles". IMHO it is not quite clear what the correct result of this test is.

**Comment by lehni** [comment]
Yes I have some time right now, would be great to wrap this one up! Let me check this out.

**Comment by lehni** [comment]
@iconexperience some git-digging unveiled that I created "nested touching circles" after a discussion between us in https://github.com/paperjs/paper.js/pull/944#issuecomment-180370569
Let's discuss it further and figure out what we should expect.
I'd argue, since we consider the border of path to be inside, this should also be considered inside...

**Comment by iconexperience** [comment]
This is really difficult. If we subtract one rectangle from another as in the image below, we would not expect the red dot to be inside the result.

![image](https://cloud.githubusercontent.com/assets/2122773/16831996/65b37d26-49a8-11e6-8ed3-3eaacc3d3d53.png)

The dot on the two circles is basically the same case. But the big difference is that if we actually subtract the two circles, the red dot is part of the resulting shape (even a segment point). From this point of view the dot should be inside the path.

**Comment by lehni** [comment]
Damn... I'm not sure what to add to that. It's an edge case, for sure. It also sort of links to our ongoing discussion regarding `#isCrossing()`. If we had overlap information available at this point, we could use it to determine how to deal with it, but we don't. We could perhaps call `#getOverlaps()` on the two involved curves in such a case. But is it really necessary? What do you suggest?

**Comment by lehni** [comment]
Also, is there an easy way to actually know we're encountering such a case in `getWinding()`?

**Comment by lehni** [comment]
@iconexperience I just rebased your changes into https://github.com/paperjs/paper.js/tree/new-winding It contains some changes from me too, maybe branch of that again for further changes, to avoid merging issues.

**Comment by lehni** [comment]
@iconexperience I just moved `addWinding()` into `getWinding()` and it allowed for a lot of simplifications. I think it's better this way, maybe also a wee bit faster: 7da70181cc39b492fc9c539140633d4917a9acfd

**Comment by lehni** [comment]
@iconexperience I added back support for open paths now, and did some more code refactoring: b1037f89f15983e4e137528fe9ea10bd0214524b 

I hope you agree with the changes. I felt the code was easier to understand for me this way.

**Comment by lehni** [comment]
@iconexperience this is also interesting: 8513144ae1d6139501f1a1cf8047846efa7d4c49

It seems we don't need to do this filtering anymore, which I like.

**Comment by lehni** [comment]
@iconexperience 064cee162954bfe4f8bf9c7614e392d58a44921c fixes this issue here, but introduces one new glitch that I still need to look at.

**Comment by lehni** [comment]
@iconexperience 09785a504b575cc6a053d56ba8d5a9bbb5eb9f52 contains more good news. I consider this issue fully fixed now. The only problem that prevents me from merging this back into `develop` is that one failing test (https://github.com/paperjs/paper.js/issues/1075#issuecomment-232584185). I'm curious to hear your thoughts on this.

And then I'm still wondering what to do with this line. If it's not required, then the code of `#getInteriorPoint()` could be simplified a bit further. I remember asking you before, but can't find the discussion anymore. Why was it commented out again?

                // if (y != v[1] || winding != windingPrev)
                    intercepts.push(x);

**Comment by iconexperience** [comment]
Sorry for the long silence, I was only briefly online this weekend.

`getInteriorPoint()` in the Paper.js version that I am using does not contain that line. And I am using with a lot of differnt cases, so I seems to work well without.

I think the line is supposed to handle cases like these:

![image](https://cloud.githubusercontent.com/assets/2122773/16902434/869eaff2-4c5e-11e6-8406-e0469004946d.png)

But if we take the line out, the intersection is added twice, which is alright, because the green point will then be used as the interior point. That's why I think we do not need that line and can get rid of `windingPrev` altogether.

**Comment by lehni** [comment]
@iconexperience apologies for the flow of posts... I was a bit too quick in removing the my `#_validOverlapsOnly`: There are still situations where this is required, I'm pretty sure it's due to imprecisions. So I reverted those changes again in 4bb2f7a8fcce98db320f31173e85bc93f00d6fde.

A good example is the sketch in #1091 that merges multiple shapes that have overlapping and near-overlapping contours. Adobe Illustrator really struggles with this one, BTW. But with the changes in 4bb2f7a8fcce98db320f31173e85bc93f00d6fde, Paper.js doesn't, and everything else still passes too. 

[Here a modified version of the sketch](http://sketch.paperjs.org/#S/pVfbbuM2EP0Vwn2wjZVoXiRRSnb3ZVssCnSLBQL0Jc6DItOOGkUyJOXWIP/eGZK6xcpugSqxJXKGw5kzZ0b0y6JM7/TibHFxq9vsZuEtsmqH42Nd/a2zlmaFTuvV+nxbbsuHtCbNw4F8IsuPeH/QdZNX5aftglO+XZCnu6JsYHTTtsezzebx8ZE+SlrVh41gjG1gSad09lTk5e2sKk+SZGPEoKzL9LrQ/nWa3R7q6r7cwZJSPxIGf6BIWcSGKyKCB5QxPkzJ7eLzxwPZ50WBK6tS48QxbW8ImvomGOp75jvzOacsUB4jvmBeTJMwME9WqWAeV5ImSZzBk9EkqCOdnPSamZGGYAemfNQJzVNvx7eGksy329uNI2J1UdHsC59/AAPn/C8ijIMsRP83GMA4jCSmLIw9F37hKztmb0JyvvgTZ9j/D0ewInQ7GoN+v+ItkJkNeLRfeLIfwXBiJodwGFVoDRYHMgGrjMZKeQY8STiVPLSDGAHlcWLyCXEyKpUdxDgIlX0eg6p3XIT7WVAdN5wXP4UyYy6PocMR02jFBdwQGYjfnwDgTxAYuDb2MNxLEakfpT2wifBHOfAR6imvgs7RSf6BKSpSBlseS4OtjEKDk4DnMLCYKXQ84A50A20MqTAjCINTETqZ+kH2LUxo2nOeoTTyDFAW7AnjlbjeB8Fs6AHrwxZsnuhBF+gIiT4zHeXGdTDmuTUwmxAOMQbvJCQBxiFxsbxlxoG4MUdcJKDJE6Cv5yeUS9UN4IaKA3WGVHXeD/SXIZUmxIjbtiFiypXqh5E6LedgAu5pKUvSYxRBuiV4EAigBGSIRVQkUDgQVBQrMwZfx0jspWKC/5eOdNoVflpA4biATP04GN5JE8YNrAwN3aMg9gDbKAG2W6gd0khjqYYGEauwaxC2kcx1iEzMk9C+gWBbNfFf9Vk0myY2SPs8JapJi01DN7JqLpG+hE4oBAhDGqHBCGxP042wsKSDRXl9tv0OG8cVWwYQcSQNQhE3PilooQaisKMjvGQg06ZZRqALMSLuQYTAdSNLhmBChjSNePoeGVQ09KnO4xlCvFez4UzN4uuAx/Z1EHjdy0CEXcfC6kugpQGLOXERYvH1Axct86avXzGk5k070nEs598VXFkmCDWTYH+a4Z7PHhtRZsqYTtWR5i3lTdUOTJmWvd/Xve26kyTxMBJyFMLmAB84mH1ewgmvO/Pld8eqbi/++roCiUde9NMxLXcXN+lRN2dtfa89kh6PxfO3tK3zJzPzak+InYU0a/MH/Uf6rGvaZGmhV4IKaIXE3Rj82xWbDfmqW2KgzCrYuNRl29izJk42cNqcs3rQ7e+tvmtWL1mRNs2fcIo9W36HBUvjSrccVuN58QtahuMjKqwujd1LdnVlXdhX9Qr1c1Dm53D7SDjeP3xYb8uXbUngyqqyqQpNi+qwynEZTprz8P2128daza+c0Alore+qB73q1uT7VSfJm9/uju3zar1G821e3uuR4WOtH5zVYaldV7Zw8AZAms4UWHB+4tXWz+MhXiMX6X2Zt7pfeT4ovg6PWQo/Bla6rtdvLY2BQPn5++IlhvGduxQY6Lfb7WJJPpjgMIU4+Wvapqvyvig8wqM1CJeotT5f/ty2mLPdwXti/sfWr2ud3p6i4W66aPQgM/bT3e7LTV7sxlC+miJAKVbcl6qoavy1VOvd0lANfl+ZfY4VJLFZnF1evf4L) that I used to test. The final shape should be fully filled letter 'D'.

But there is one curiosity, which I need to ask you about: One of the changes I needed to revert for this to work was these [two lines from your commit](https://github.com/paperjs/paper.js/commit/46ea9da423f8b272e0eb3c2c86b2619c52687329#diff-83b0f841b43dce90324008de0d976e25R454) 46ea9da423f8b272e0eb3c2c86b2619c52687329: Weirdly, deactivating them didn't change anything else in all my unit tests, so I wondering why these were added? Are you sure they're correct?

If you want to replicate this, just pull the latest stage of the `new-winding` branch, and use the linked sketch. Once you remove the comment on those two lines again, it'll fail.

**Comment by iconexperience** [comment]
I can confirm that with my codebase the example fails currently, and it works if I remove the two lines. I searched through my test cases to find why I added them, but all my tests work without the two lines. This means that they are either not necessary or I forgot to store that test case.

BTW, are you interested in more failing test cases?

**Comment by lehni** [comment]
@iconexperience that's great news. Are there many differences between your code-base and this now, btw?

Regarding failing test cases. I guess the answer should be yes, even though I'm afraid of those :)

**Comment by lehni** [comment]
@iconexperience if you post them, please do su under a new issue. Thanks!

**Comment by iconexperience** [comment]
Regarding the code base: I have a different `propagateWinding()` implementation, that is better in handling cases like these:
https://github.com/paperjs/paper.js/issues/1073#issuecomment-225674361

It tries to assess the "quality" of a winding calculation, and if the quality is low, it tries again on anothe point of the propagation chain. Far from perfect, but handles more cases than the current code.

For `isCrossing()` I am using a slightly modiified version (you remember, we both had our own implementation. I guess mine is a mix of both). That's about it, I think. It's a bit hacky, but I just had to get things working.

**Comment by lehni** [comment]
@iconexperience interesting. I'd love to see your `propagateWinding()` and merge it back in. As for `isCrossing()`, that issue is still open, and I'm aware it needs to improve, so here too it'd be nice to see your code : )

**Comment by iconexperience** [comment]
@lehni I will put together a version that is compatible with all the changes on `new-winding`. 

But the algorithm is very simple:

My `propagateWinding` test three points on the chain, at 0.05, 0.95 and 0.5 of the chain length. If in `getWinding()` the `onPathCount` is less or equal one, the quality is good enough and we do not have to test the other points. `onPathCount` is greater than one if there is a second curve very close at point `p`.

This is not perfect (I still have one failing case), but it does a pretty good job for being such a primitive algorithm.

**Comment by lehni** [comment]
@iconexperience this sounds great! Do you check 0.05 first, or do you start with 0.5?

**Comment by iconexperience** [comment]
I start with 0.05. If the quality of all three points is not good, the last one was 0.5 and we will go with that. Actually, I am using 0.47, because I sometimes landed on a segment point when I used 0.5, which causes problems with the winding calculation. But I think the resulting issues have been solved elsewhere, so we can probably use 0.5 (although I will stick with 0.47, just to be sure).

**Comment by lehni** [comment]
is there any reason why you don't use 0.5 first?

**Comment by lehni** [comment]
@iconexperience so what do we do about https://github.com/paperjs/paper.js/issues/1075#issuecomment-232584185? I keep getting failing build notifications from Travis CI because of it, would love to come to a conclusion here soon...

**Comment by lehni** [comment]
@iconexperience I've merged `new-winding` into `develop` now.

This issue could be closed, but I'm leaving it hope to hear back from you regarding the failing unit test in https://github.com/paperjs/paper.js/issues/1075#issuecomment-232584185

**Comment by lehni** [comment]
@iconexperience or maybe I'm thinking about this all wrong... What we maybe want is this:

The current `reorient()` is quite destructive, it removes children when the `nonzero` fill-rule applies, and it sorts the children according to their area. Perhaps we wan to keep it as part of `resolveCrossings()` like we had it, but behind a switch. 

And then we could offer a new `reorient()`, which keeps the order of children intact (after all, the user inserted them in this way), but figures out what to do with their orientation, perhaps based on the same algorithm that the current `reorient()` uses. Underneath it could be same code, even.

For example, what happens if we keep the code but don't sort by area first? Can you help me figure a good approach out here?

**Comment by lehni** [comment]
The part that would have to change if there is no sorting is this:

```js
// We run through the paths from largest to smallest, meaning that for
// any current path, all potentially containing paths have already been
// processed and their orientation has been fixed. Since we want to
// achieve alternating orientation of contained paths, all we have to do
// is to find one include path that contains the current path, and then
// set the orientation to the opposite of the containing path.
```

Can the algorithm be changed to support non-sorted paths?

**Comment by lehni** [comment]
https://github.com/paperjs/paper.js/issues/1075#issuecomment-232584185 was moved to #1116, closing now.
