### ISSUE TITLE
Add set() function to Point

### ISSUE THREAD

**Issue by iconexperience** [paperjs/paper.js#1076]
I am frequently running into situations where I have to change the values of a point. Instead of 

```
myPath.segment[i],point.x = myX;
myPath.segment[i],point.y = myYX;
```
it would be nice to have something like
```
myPath.segment[i],point.set(myX, myY);
```

Internally the `set()` function could take the functionality of the `initialize()` function, and initially would call `set()`. This feature is not really important, but it would help from time to time.

**Comment by lehni** [comment]
Have you tried it? It long exists, even propagates the change on SegmentPoint! : )

**Comment by iconexperience** [comment]
Sorry, did not try it. I just looked at the documentation and did not see it.

**Comment by lehni** [comment]
The documentation is not complete. It only exists for the things that a human had time to write documentation about...

**Comment by iconexperience** [comment]
If I find time I will try to help with updating that. There are a few other things that confused me at the beginning.

**Comment by lehni** [comment]
Yes it would be great to get a fresh view on those things. I can't see the forest from the trees, sometimes.
