### ISSUE TITLE
Chrome cannot optimize Numerical.solveQuadratic()

### ISSUE THREAD

**Issue by iconexperience** [paperjs/paper.js#1078]
This is not an important issue at all, but I think it is quite interesting and I have a solution ready that even results in slightly shorter code.

While profiling some Paper.js operations with Chrome I noticed a little warning icon next to the <a href="https://github.com/paperjs/paper.js/blob/develop/src/util/Numerical.js#L217">`Numerical.solveQuadratic()`</a> function's data.

![image](https://cloud.githubusercontent.com/assets/2122773/16079733/593fa290-3305-11e6-8f39-0f0fac05c11b.png)

The lillte icon indicates that Chrome's V8 failed to optimize the function.

Hovering over the icon gave the extra information *Not optimized: Optimized too many times*. This again means that Chrome's V8 tried to optimize it several times, but the behavior was inconsistent, so it gave up eventually.

After some googling I found that wrong handling of `NaN`s can lead to failed optimizations and further digging showed that this part of the function was the culprit:
```javascript
var mult = pow(10,
    abs(Math.floor(Math.log(gmC) * Math.LOG10E)));
if (!isFinite(mult))
    mult = 0;
``` 
As I understand this (and tests indicate that I am correct)  `isFinite(mult)` can only be false if `gmC <= 0`. In this case, already the `Math.floor()` is called with a `NaN` or `Infinity` argument. Actually, the way `gmC` is calculated it cannot be negative (but it can be zero), so I tried changing the part of the code to
```javascript
var mult = gmC === 0 ? 0 : pow(10,
    abs(Math.floor(Math.log(gmC) * Math.LOG10E)));
``` 

This passes all tests and results in V8 being able to optimize `Numerical.solveQuadratic` function!

**Comment by lehni** [comment]
Great detective work, @iconexperience. And very interesting to read about this V8 stuff. I spent quite a bit of time a while back optimizing for it, but haven't looked back into all this. Thanks!

**Comment by iconexperience** [comment]
Just for the record and for future reference, there are some other functions that currently cannot be optimized, such as `Point.isClose()`, `Segment.setHandleIn()`, `Rectangle.touches()` and others. The reason why these functions cannot be optimized is that the `arguments` are 'leaked' to another function. More information on why this blocks optimization and on workarounds can be found at  https://github.com/petkaantonov/bluebird/wiki/Optimization-killers

In order to make these functions optimizable one would first have to create a copy of the `arguments` and pass the copy to the other function. For `isClose()` it would look like this:

Current code:
```javascript
isClose: function() {
	var point = Point.read(arguments),
		tolerance = Base.read(arguments);
	return this.getDistance(point) <= tolerance;
}
```

Optimizable code:
```javascript
isClose: function() {
	var args = new Array(arguments.length);
	for(var i = 0; i < args.length; ++i) {
		args[i] = arguments[i];
	}
	var point = Point.read(args),
		tolerance = Base.read(args);
	return this.getDistance(point) <= tolerance;
}
```

This is certainly quite ugly and the performance improvement is minimal, so I suggest we keep the current, non-optimizable code. If someone urgently needs to squeeze the last bit of performance out of Paper.js, he/she can modify the functions accordingly.

**Comment by lehni** [comment]
I am aware of this, it's a side-effect of the argument reading that we support to have the flexible treatment of points. This was added to the library before the JS people did all these crazy optimizations, and there is little we can do about it now. What we could do is separate each such function into an optimizable and non-optimizable function..., with the optimizable function doing the hard work and the other function just the magic and the call.

We could also think of a way to produce the argument reading code on the fly as a wrapper function around the optimizable original function, based on some clever naming or meta-level information. But there are other more important construction sites, I think...

**Comment by iconexperience** [comment]
I agreen, this should have very low priority right now. I just wrote hoping it would save some time in future if we decide to work on V8 optimizations.

**Comment by lehni** [comment]
Yeah that's where I stopped optimizing when I did the last V8 optimization pass through the library a few years back :)
