### ISSUE TITLE
strokeBounds when strokeScaling is false and view has zoom are wrong

### ISSUE THREAD

**Issue by georeith** [paperjs/paper.js#1080]
`bounds` and `strokeBounds` normally ignore the view zoom level and return bounds as if `view.zoom == 1`.

However when an element has stroke and strokeScaling is set to false `strokeBounds` seems to take into account the view zoom.

http://sketch.paperjs.org/#S/rVLBasMwDP0V4VNXQtrm6LHL9gNjPezQ5OA4WmLiSMH2Wmjpv8+JKSyll8GMMOhJ7+lZ+CJIDSik2PcYdCcyobmZ8qNy4FCHHbwA4QneVejyjwgoai2uLiVBPCN7EwyThKPBU66RAros1bw5o4TDbrvNIF7VDQ6Oe9xrZQ21Er6U9bgofZomdDJSFugbW3ZRbhJLUZV0fXou6ea0+E+ns3JJmsmzxdxyu5q3kSc3r/xNjc/ShvJ6zibGfX/xoL/41Z/4s6Mz8xBfUDxQWU6FzRpCZzzECB3C6Li2OMB6c+8H/m4ofoDaoepHNhS8kIfq+gM=

**Comment by lehni** [comment]
It has to, because the stroke does not zoom along with the view, so the stroke bounds change by definition based on the view. But the version online calculates this wrong. I think the `develop` branch has it right:

```js
{ x: 389.5, y: 336, width: 110, height: 110 }
{ x: 394.5, y: 341, width: 100, height: 100 }
{ x: 392, y: 338.5, width: 105, height: 105 }
{ x: 394.5, y: 341, width: 100, height: 100 }
```

**Comment by lehni** [comment]
Did my explanation make sense? Do you still think it's a bug?

**Comment by georeith** [comment]
It does, seems to work for this sketch: http://sketch.paperjs.org/#S/XZDPbsIwDIdfxcqlIEGFhrZDEBd4A3rYoeVgUreNmjooCVQC8e7L+mcSy+33OYk/+ykYOxJSZC0F1YiVULb8zXd0oLRThmAPTD1kDV4pPQ5o8SwY4lHEgZyEu6Y+HcNqrDgs9c1L+NxMwAdnWzpaY+P95GJQtclb6VuXoZHw8f4gU2g01xIqNJ4Kfi13BRc8NHxY20W57UiiryMVkOt/yqeZztZXqznIabp07HOwNy59aqgKsIavPwn9IAl5zJGdJ1hpY+ZBakfEyeAVd3dxhO3wvRcyP79+AA==

I was modifying the `strokeMatrix` in the draw function to snap to edges of stroke and found it only works with the non view modified value, I think I just didn't understand the maths involved there, assumed it would be incorrect elsewhere.

But yeah that seems like correct behaviour thanks for the explanation.
