### ISSUE TITLE
strokeWidth breaks equals

### ISSUE THREAD

**Issue by georeith** [paperjs/paper.js#1084]
So there is something funny about `Item#strokeWidth`. The issue is it appears to have a value of `1` but isn't treated like `1` by default. For example equals breaks unless explicitly defining `strokeWidth`:

http://sketch.paperjs.org/#S/tZHLCsIwEEV/ZcjGCqGQuov0HwQXLtouYh1saE1qEx8g/rtTY7FVXDqbJId53Lm5MaMOyCRb1+jLinFW2l3/PqsOWuUrASkYvNC9xS5eEYluuQEKh/sDGu8kZAH0kQkOouAjkHBIJmDBYTGA4XS+szVu9M5XEgTB+3yZm9wMKpK/q3gNLK1xtsG4sftoFvbH40k1LsiQMx5ciQONnnTe104qR/uAduArBEc+v8vHCWmahu5j2rf8guSC+Bz1LRIumlLx2ja61H7i7W/59PPbDlXdWk1uMpkV9wc=

On a slightly different but related note why is `1` the default value? I feel like `0` is a much better value in this case as you have to explicitly state a colour for a stroke, why not the size? Feels weird resetting this value to `0` so I can factor `strokeWidth` into my calculations elsewhere.

**Comment by lehni** [comment]
The default value is 1 since the default value for strokeColor is `null`, so by default there is no stroke displayed. The idea was that it would be nice to be able to set just the color and the stroke would appear. There is no way this is going to change now, as it would break almost every script ever written.

As for the main topic of this issue, I need to look into it.

**Comment by lehni** [comment]
It looks like `Syle#equals()` does not take defaults into account when comparing. That should be easy to fix!

**Comment by georeith** [comment]
Ah ok yeah understand that about `strokeWidth` just wondering if there was a deeper reason. It's not in the docs so can take you by surprise when you see it. I see `Style#hasStroke()` takes that into account.

**Comment by georeith** [comment]
@lehni It's not just defaults. It doesn't recognise equivalent colours either:

http://sketch.paperjs.org/#S/vVHLCsIwEPyVkFMLobQp9FDx5A+IHpseYlza0ripSVSw9N9NK+JFvOnuZWd2YPYxUpQnoCXd9+BVSxlV5jjjq7RkkL7NyJog3Mg21MkOlJfYaIhGgSTEYDr0Jal4yghPa/ZkXXeHQBaBLN6kt6aHjdHGhl7GQtYCp3glUODLjf/Q7ZNf/pftlEFnNCTaNNFy0wTOF6ndAng8i75K8iAJnzlYkP0yk6NlVU8P

**Comment by lehni** [comment]
Ooops!
