### ISSUE TITLE
Inconsistent calculation in Numerical.solveCubic and Numerical.solveQuadratic

### ISSUE THREAD

**Issue by sapics** [paperjs/paper.js#1085]
In [this sketch](http://sketch.paperjs.org/#S/hZBNC4JAEIb/yrInC1NX6CJ0ig5BWOFRPYzbUKLuxvhxif57a5J26INhYD6e4X2ZG1dQIQ94VGAjL9zmUp/6vgNiyFYsbCukXELpbA7RdrcPbUbCzOPUFP6zSNQE1brscN1mubQ8ZzlHmy3eksSMuS6TUKP4fmVYMSX5442fKKmVgdEp9dmiYZuoPnq/f40dWzgRNEbGmPFGTz84MXAvpY/y5mkZIRRXnaum5kGc3h8=), you can confirm that solutions of two equivalent equation are not same in Numerical.solveCubic and Numerical.solveQuadratic.
It is just a special case problem, thus, it would be enough to fix after 0.10 :)

## Numerical.solveCubic

The solution of `a x^3 + b x^2 + c x + d = 0` is calculated in Numerical.solveCubic.
https://github.com/paperjs/paper.js/blob/develop/src/util/Numerical.js#L302

When the case1 (`a = 0.5*EPSILON, b = c = d = - EPSILON`) then, (because of `abs(a) < EPSILON`)
it is converted to `b x^2 + c x + d = 0` in https://github.com/paperjs/paper.js/blob/develop/src/util/Numerical.js#L307.

On the other hand, the solution with case1 is equivalent to the solution with `a = 0.5, b = c = d = - 1` (case2) where Numerical.solveCubic return right solution.
In the case2, it is NOT converted to `b x^2 + c x + d = 0`, becase of `abs(a) > EPSILON`.

The conversion in case1 causes problem.
I guess that we need to fix the conditions of this conversion in (https://github.com/paperjs/paper.js/blob/develop/src/util/Numerical.js#L307 and https://github.com/paperjs/paper.js/blob/develop/src/util/Numerical.js#L312).

## Numerical.solveQuadratic

Similar problem is occured in Numerical.solveQuadratic.
`a x^2 + b x + c = 0` with `a = EPSILON, b = 0, c = -EPSILON` which solutions are `-1` and `1`, but Numerical.solveQuadratic return no solutions.
On the other hand, Numerical.solveQuadratic could return right solutions for equivalent equation `a = 1, b = 0, c = -1`.

## One of the solutions (but it might cause some other problem...)

I create a branch(https://github.com/sapics/paper.js/tree/simpler-calculation) for discussion.
It is just simplified one by removing most of EPSILON error.
I think that this branch would not have the problem which introduced above.
However, I guess that original calculation is better than my branch for consistent calculation for epsilon error and collecting more solutions.
It would be impossible to avoid some epsilon error which is created in the Kahan's iterative calculation in Numerical.solveCubic.
Thus, for collecting the more solutions (but it might also collect more impossible solutions, in some case), original calculation might use calculations which cover some epsilon error, I guess.

**Comment by lehni** [comment]
Interesting. Have you run into this problem in real world data, or is this hypothetical? Did you test your branch against the unit test suite? I think you want to be careful with the handling of `MACHINE_EPSILON`. 

Most of the code was written by @hkrish and is based on _(Kahan W. - "To Solve a Real Cubic Equation")[http://www.cs.berkeley.edu/~wkahan/Math128/Cubic.pdf]_ and _Blinn J. - "How to solve a Quadratic Equation"_, and I think that's where `MACHINE_EPSILON` comes from. There's a good reason for it to be there. The use of `EPSILON` was something I added based on real world data, and that's probably far more questionable :)

**Comment by lehni** [comment]
Oh wow. I just set `EPSILON` to zero for those functions and did not tinker with `MACHINE_EPSILON`, and the code didn't produce any errors in the unit tests! So it could well be that the reason why this imprecision was necessary has long been solved by @iconexperience and my work on the boolean code more recently. I will do some more tests, but this is great news!

**Comment by lehni** [comment]
Oh, I was too fast. There's one failing case, that we should look into and compare the solutions we get. We may even find that the current solutions are wrong, masking a problem in the boolean code... It wouldn't be the first time.

**Comment by lehni** [comment]
Alright, here's the cubic that produces the different results:
```js
a = -0.23544048722315924
b = 6.984858879768526
c = -13.149024935312404
d = 6.399606542767038
```
* With `EPSILON = 1e-12` I get two solutions: `1, 0.9817961835811548`, and the correct boolean result.
* With `EPSILON = 0` I get one solution: `0.9817961835811548`, and the boolean result doesn't seem correct.

**Comment by lehni** [comment]
If you're curious to investigate yourself, this is the boolean example that behaves differently when removing the `EPSILON` tolerances, and the current result seems right. The example zooms in onto the area in question: There is a tiny loop that's the only intersection of the two paths. The current code base finds this as a solution, if I remove the `EPSILON` tolerances, this solution is not found anymore.

```js
view.matrix = new Matrix([807.793566946316, 0, 0, 807.793566946316, -195987.57916409153, -219869.205324027]);
var path1 = new Path("M249.53400844979302,269.5706278725207c-5.202299838213264,1.3434437726778015 -6.529484298911967,2.9120315237744876 -6.504886128424744,2.882905020664282l-45.83988896091887,-38.71310605015606z");
var path2 = new Path("M243.02912232136822,272.453532893185c0.44566136595048533,-0.527704170852985 -0.5294319041516928,-0.18417469336759495 -0.35985190468429096,3.787313842921378l-45.480037056234465,-42.50041989307755z");

path1.strokeColor = 'red';
path2.strokeColor = 'blue';
path1.strokeScaling = false;
path2.strokeScaling = false;

var result = path1.intersect(path2);
result.fillColor = new Color(1, 1, 0, 0.25);
result.strokeColor = null;
```

<img width="406" alt="screen shot 2016-06-19 at 10 40 39" src="https://cloud.githubusercontent.com/assets/213275/16176268/8f6bda16-360a-11e6-829e-ec766af724d3.png">

**Comment by hkrish** [comment]
The EPSILON is checked against probably because of geometric precision issues. Some curves that are nearly linear may produce a quadratic due to roundoff etc. @lehni knows best where these isues probably are :).

For reference, this is a version of the implementation in c that I translated these functions from. The javascript version is a bit simpler (and imprecise, in c we use long doubles and split doubles to do intermediate calculations so that we will have enough correct bits when we convert the results back to double). Long double is not available in js but, if you need high precision you can try to copy and use the split double code.
https://gist.github.com/hkrish/9e0de1f121971ee0fbab281f5c986de9
Note that I check against 0, in my use case I didn't have any geometry issues.

reference: 
Dekker T. J. - "A Floating-Point Technique for Extending the Available Precision"

**Comment by iconexperience** [comment]
@lehni I think the loop should not be filled. According to this sketch it has a winding of zero, so it's not part of the intersect.

![image](https://cloud.githubusercontent.com/assets/2122773/16178556/f9ab797c-364b-11e6-90d2-30d6b2e8eb80.png)

But there is a tiny part at the crossing where the paths intersect:

![image](https://cloud.githubusercontent.com/assets/2122773/16178570/8d9e625c-364c-11e6-8b4c-4e9257b1a434.png)

**Comment by sapics** [comment]
@lehni
This is hypothetical problem.
Yes, when I tested with unit test, it caused some errors in my branch.
I will test more carefully.

Thank you for example!
It would be important example which checks calculations.

@hkrish
Thank you very much for c code!
It is very instructive code.
Can I investigate js code from your c code?

I think that one of the typical problem in current code in js would be `var gmC = pow(abs(a * b * c), 1 / 3);`.
`gmC` is 0 if a = 0 or b = or c = 0.
If `gmC` is zero, `a`, `b` and `c` are converted to zero in [Numerical.js#L237](https://github.com/paperjs/paper.js/blob/develop/src/util/Numerical.js#L237).
It looks strange for me, "a = 0 or b = or c = 0" => "`a`, `b` and `c` are zero".

On the other hand, in [your calculation](https://gist.github.com/hkrish/9e0de1f121971ee0fbab281f5c986de9#file-polysolve-c-L131), `sc`(similar with `gmC`) cannot be zero.
Thus, there are no unnatural conversions!

**Comment by hkrish** [comment]
@sapics The old code for normalising —[Numerical.js#L237](https://github.com/paperjs/paper.js/blob/develop/src/util/Numerical.js#L237), was a rather naive way of normalising coefficients. I think, we should replace it with the one in C code, which I took from the *experts* (Jenkins and Traub's polynomial root finder), the results are much better in terms of accuracy as well.

You can use the c code as you please. I have attached MIT license to the file https://gist.github.com/hkrish/9e0de1f121971ee0fbab281f5c986de9
Most of it should be directly translatable to js except for the parts where I use `long double`. As for the more accurate discriminant functions, you can translate the simd code to normal js fairly easily (see the commented  out function for details).

**Comment by sapics** [comment]
@hkrish
Thank you very much for your permission!

First of all, I will directly translate from your c code to js without `long double` calculation. (Sorry, i am not familiar with SIMD calculation)
In such a case, can we remove a condition in
https://gist.github.com/hkrish/9e0de1f121971ee0fbab281f5c986de9#file-polysolve-c-L141?

**Comment by hkrish** [comment]
@sapics No worries. I translated most of the code and ideas from W. Kahan, all credits to him.

Right after I wrote the last message, I was looking through the old commits for non-simd version. It's pretty straight forward. I wouldn't remove the condition though, the sensitivity of our algorithm to roundoff depends on the condition of the roots (not only the coefficients), see http://people.eecs.berkeley.edu/~wkahan/Qdrtcs.pdf#3 for a good explanation.

```
static void __attribute__((const))
_DD_split_double(double X, double *x, double *xx)
{
	double bigX = X * 134217729;  // = X*(2^27 + 1)
	double Y = (X - bigX);
	double Xh = Y + bigX;         // Don’t optimize  Y  away!
    *xx = X - Xh;
    *x = Xh;
}


double uru_poly_discriminant_double(double a, double b, double c)
{
	double ad0, ad1, bd0, bd1, cd0, cd1;

	_DD_split_double(a, &ad0, &ad1);
	_DD_split_double(b, &bd0, &bd1);
	_DD_split_double(c, &cd0, &cd1);

	double p = b*b;
    double dp = ((bd0*bd0 - p) + 2*bd0*bd1) + bd1*bd1;

    double q = a*c;
    double dq = ((ad0*cd0 - q) + (ad0*cd1 + ad1*cd0)) + ad1*cd1;

    double d = (p-q) + (dp-dq);  // Don’t omit parentheses!

    return d;
}
```
Good luck.

**Comment by sapics** [comment]
Thank you very much for you coding!
I can use your code right out of the box!! :)

**Comment by sapics** [comment]
Thanks of @hkrish, I have created a more precise calculation in [branch](https://github.com/sapics/paper.js/tree/fix-poly-solve).
In my local Windows PC (chrome), it passes all tests, however, travis-ci causes [error](https://travis-ci.org/sapics/paper.js/jobs/138845761).

There are a few elaborately differences from @hkrish c code.
1. @hkrish code includes long double calculation, but this js dose not include.
2. @hkrish code have one epsilon size (2.220446049250313e-16)
    but, this js have two epsilon size (1e-12, 1.12e-16).
3. In [@hkrish code](https://gist.github.com/hkrish/9e0de1f121971ee0fbab281f5c986de9#file-polysolve-c-L243), the condition is checked by `a` is zero or not. However, [js code's condition](https://github.com/sapics/paper.js/blob/645e2c2af3d0cc4c446c5537aebd9b8031482973/src/util/Numerical.js#L344) is checked by `a` is smaller than EPSILON  or not .

By applying difference 3., the test which is introduced by @lehni can pass.
I don't know the effect of difference 2., but, it is for keeping js code as similar as possible with original js code.

**Comment by sapics** [comment]
@lehni
Thanks thumbs up :)
Is it better to create a PR for checking the differences from original js?

**Comment by lehni** [comment]
No need for a PR yet. I haven't had the time to look into it all yet, but I can check out your branch locally to test.

**Comment by lehni** [comment]
Although... If you create a PR,  I can write code-comments. Maybe that's better!

**Comment by lehni** [comment]
@iconexperience I'm pretty sure the loop should be filled. See [this sketch](http://sketch.paperjs.org/#S/dZNNT9xADIb/yioXQEpGHn8b1FPPSJU4shzSJZQVYRct21K16n+vE9iqBSrlMGO/sv28nvxsNv390Jw2F3fDfnXbtM1qez3dv62Hp3Lf73fr74sPi83wtDifL8eXDlYsSFSDlaq2C5i/t/GuhoRbEYuqDFGFMog1XKMgCCED2tXJ2XLz/3aCCMiFxJjCvcah3zuJrqK6qiEVV9QKKFOQEdGAsJhidSF+btnvFg/9/ra+NPyU5+Nlc44cJTUAzhwJBNhizisGiuaGgmCrThIAMcLJsRIqt7UQEzOZoZo5VFl0WgSDnTE8ag21FktUBKqCKWR201kF7K4VU8kZTZU7BgggqDI6jh1L8YnTQ9NJd2s78mKVKmgKqyjoj2XzNxm+IaMCmP2RcmZ1TDLDwkK5Cg9Kb1ZQmHOFmZaYphKitoPEMAOuBp5AnmQwk1GNjErVQJ9k1VPDGkRqEhyzkPIRyCTUyQgIbamkkVRpuuck5jMeOwAZiGLaqNJ2jGlM1k/zCMxEXviWm3lv5XG/294NH7fjdpekR7vh+ujskLtZj+MhM3kwn4/r4fFAwZMXLb6u83n8Ohz9Sb5f6LlK/afQYaCLVT+uN19Sf9OPj8OrNm+z+dN93g393cN2vdk/NqeXV79+Aw==) where no boolean operations are performed, but the fill colors are made to mix where they overlap.

Was your assumption perhaps based on bugs in the old winding code that we since replaced?

**Comment by lehni** [comment]
And here the [zoomed version of above sketch](http://sketch.paperjs.org/#S/bVNNT9xADP0rUS5spWTkscceG9RTz0iVOLIcwjKU1YYsygaoWvW/18myEoVGOYz9nj/em+R3PXSPpT6vr3Zl2jzUTb3Z383xy7a8hsduGrc/q6/VUF6ryyVYXWtkEQrAmsw84KaC5f0P0EZTRIuEQZDZSDyH82Mm4lRTQqGbLxfr4aUbq6dueohv8777ebWuLzFZYEoAmpJlI8AGxVMZBLNmZIS8aTkgzF2VFH2cpCYGSpQS5YySs0LkqpXAaEkTmlqMJrnBYBGBIqMTU9IsCwuSqkR0ZvKss1TRgAFBJKFi3yYOSqaqJmBRNTctaciRIogT3QuQX+v6vTL8pMzdcncQyXcWd6rBjCExMaEaReUNhJTcVofZ5q2YqGnBZeQMKWZQF6SuDBZlFM2zHMVQZ1pU5yQxIslsyRYiues8E2U2AkwaCm4kRZpj3yTrIi8pAGVgQbdRuGkTujHe380jyJn5Td96WO4tHKZxvyvf9v1+dKVnY7k7uzhi+BG77Z/LCTwVXm26fjv8cPi+6w/lQ+ln9GjsWA7P/eTpY6vtMJXxUDbTaime1zsywv2270/z51tYzqvYVPH4AQfkd+x/9x2e+94x/z1ux9LtnvY+5lCfX9/8+Qs=)

**Comment by lehni** [comment]
@sapics could you provide an example where using `higherPrecisionDiscriminant()` is producing better results? I've deactivated the code and tested against your skethc in the first comment of this issue (https://github.com/paperjs/paper.js/issues/1085#issue-160804408) and there wasn't any difference in behavior, so I'm wondering if we even need this with the reduced precision of JS doubles...

**Comment by lehni** [comment]
@sapics don't bother, the sketch [mentioned here](https://github.com/paperjs/paper.js/pull/1087#issuecomment-231248097) is one of these cases.
