### ISSUE TITLE
Cannot get the correct item for click event anymore

### ISSUE THREAD

**Issue by SebastianStehle** [paperjs/paper.js#1086]
Hi,

I use the following configuration in package.json

```
"paper": "git+https://github.com/paperjs/paper.js.git#prebuilt/module",
```

When I reloaded the source code the last time (I guess it was one week ago), everything was fine for me:
I subscribe to the click event of the layer and event.target is the actual item that is clicked. I had to install all packages again and now the target seems to be the layer.

**Comment by lehni** [comment]
You could use this format to pin a specific commit hash on the `prebuilt/module` brnach:

    "paper": "git://github.com/paperjs/paper.js.git#1626c67a9ecbd3c840ed7bb22b564d4480729ca2",

This way, you could go through the versions and find out in which commit it exactly breaks. would that be OK?

**Comment by SebastianStehle** [comment]
Yes, I know. Is this by design?

**Comment by lehni** [comment]
I don't think so, but without a test case and the actual commit that caused the change, I can't tell.

**Comment by lehni** [comment]
If I wasn't clear: I was asking you to identify the breaking commit this way, so I can see what may cause your issue.

**Comment by SebastianStehle** [comment]
Yes, I got it ;)

I know that this commit works:
https://github.com/paperjs/paper.js/commit/8d1daa3a1bf7207c094272a9d8c072c0790b729b

I hope to find some time next week to find the last commit.

**Comment by lehni** [comment]
@SebastianStehle still hoping to get this last commit that still works for you...

**Comment by lehni** [comment]
@SebastianStehle still waiting for more information. I'll have to close this bug otherwise.

**Comment by sasensi** [comment]
I close this issue because no more information was given.
