### ISSUE TITLE
Path Boolean: Path.Unite() failed when one Path is opened and the other closed

### ISSUE THREAD

**Issue by ghenania** [paperjs/paper.js#1089]
[Here](http://sketch.paperjs.org/#S/ZVZLjxs3DP4rgi9JAY0iUqQeCXppew2wQHvr9uBMJt3tTu2F10mAFv3v/SjPzL7gw0gUX/r4kfK/u8P+72n3fvfr3XQeb3Z+Nx4/2/7+dPxrGs9hnKf96e0PH64P14crcj+6w/TdXe3PN2+vdx85NBYWT0qh1Bh5jn6gmANpKTJiwxqoaUuOYxCm0vwgGjIzV9cXj/ux61YmH5ejbiOxLNtVEUFqDZQSlgOxRRZB3BRYOdM41NCUW/JDC1y1qRvgqTbKtWvhsFY3JA5VsjyKxoEopKa1IoOBcRxLQdiAO+YMAwo5s2bfY3LhEQGoUmRfQ1WcOPNVNXKy3DNLdRfvMXuEEymcrncG5hW/gFJqUKGWvfS7ybhBZ8ksUHVActJN8ASSgWsLTUpMYwwRt/C4DWet2UlIQFE8rqRUY3IbaLgSF6Q7lxpEC1dfAUFWVXikUkIiYjWHEVH8WqEOKLJV2opySYk6YIvon8tVrw/v3rnfbib35TjPx++3hz/d8Xwzndx4/Ho/Q7y/nR/c99vzjTPuuePB/XTaH8Yb98v0bZqP9+bgFfUML0rKPo5DNoQ7bzraraqnoI1JeqKZIzgqVuSooxVWcuJm+AgJca+scAGgCYUsUbnbRZSh+QxAUqo0czSnwMGnlkEnGc0BkM5+denMPifwbPXoVnO/Ohy3+MNq77p2AkmG7qCyuC3+0D2Qpnm4ZMAKtSUDUD1KSQW+NNTUGBRkCbHiDt5WLZeaUJsYCirZHmVLcYDsSyZyoxA1I2XJ4EksuY3oaG4RgclYrAA2BxC+oXu4YMUKTsbAyShh0aokbbOtchHr+or7lBbLXEHCmjLUCO61gfNzAUPBJkExXw4Bo93wfBB00cq2bchstDTFJ1NmeG7Tu8WSbiVL9nEG9q1WdMeAdFqNuO0zUIVwN8MULS9PMDVIY4v0KBofeUjQj5pk4+EyDjYWvibhxoGNg68p2BmQBOB2DgoVLu4jxirGFtrRC4Dk1jB6hwS9jDmEhUjW5tAlsZaGUkA7lwxWYNCAa7kTEbVMGN+YdTakAWNBnUdG3SsVpE3NppkE7KR4wEeKeuDLGXs4IJSgXpLRVC65iGCo2i2qkXZZGFFiEvRRX+SLQBnVWBfjamNfbcVdLMgvX7caLF+EBa2sl6THLRU/c4JiU/dqC7MSzZe4tjBBNjCHZTGuqn41WVX9arKq+uWL0LkGPEUNg6+Cx5nYJnBN0SgXIYCCw9MBVHqkovDkkG7p0KMGqm2EJfbG9cBMubmKbhJB9oo7ggfOipTYiIp4iTFJBmNlJkV5YgZgVlGkhLle8BRWG38bEVsQkNsKJHi0sr2F/aWRWMEWBRv1ki9BhJJQtA4ha4LAxkKIMh6LZtMnpFq4jWg75YJnIVBM8E3W7fCChzgTWmQ1WPS398D+SYQvt/P883E+njB+3nyav05vPnT5w/l0vJten/Bzi9P0eRG/MFgOrg/f9id3Dwl8fj3cnqe3V2zh719G3o93b7r8VeTlxM7OeJEe5j28JI2Y5XG9yfUB/5k+nab93f3x9nB+2L3//Y///gc=) is a sample where a first path P1 is opened and the second is closed.

`P1.unite(P2)` returns `null'.

If you add `z` command at the end of `P1`, it works well.

**Comment by ghenania** [comment]
Another [sample](http://sketch.paperjs.org/#S/nVRNT9wwEP0r0xy6u6q9xF/5APVUqWoPrXahJ5oeguPdjcjaKMkWIcR/73OAChCqKiJFk/F4Zt57Y+c28fXeJcfJ2aUb7S5hiQ1N9I+O6IvrHdV4V/Se1ozG60BX9bgbyIeRRtfvW1+PrqGLG6qS8yohG/b72jeVR/b3MDoadzV27hxdHLbUBDf42UjB2kNP7Ya+Ut00VNP5YyJht4MJG1pVvvJU+d91j/4fybtrWqH5vEq+mUwwXRRWMJUTF5oZQVyXMJaXjMMRcIjLjAksyZJJTdxIJrFYpCzFWsF49EzGeMwuBON5abmOviKexToiw4fBR5FbxbiWpOI2QXk0qcVmQaVGExLopY0FsEyRSFMmVAGrmZRllSxO7omsXxDRpWFZBjjgINBVAqIkji4yB0YxLWoUiYg02FquQAawgCAakQKesQDDOBoDsgRcHVUxwChVpIqYFpMavEBEIyBU1CUHi5ymDEVGw5baZljNMhImRhVJtOdZbkETiwiagqRSTEhhUQAgSiZSQJEGOkDB2EZFZdNJKnRgEaaNBCA+kE2Simk+iBUa9PM4LgU5YTSqFiBaMI2p6YKVBUVPGGmhExCDgTAplRmTIrVZBCaZ0CSi3FaoeB5wHHIZtxTCAm5GmZnmlALuw0QqP/Y3dItjhieO51RgPqvlwbejm6/jlhg5FctN23WfQhd6xGe9a2YI3VXe1rgyNHd9v3gsY4MfQueWXdjOZ5/bfhhpKkebuu1wVY5n9IGQsNy7Yai3bnFfaboxpy7iqTe4WWS7MLR+ixMTb9zD6ZFov14i5N18Ee3gppM09oep0Es68ikd+ZePfM7noju42ckr8M8c3OYB/3Cw1jVg8G62+D/2z9LfSH810afrHbKhxTACOIUr5x1+Mqv/kEC9OlH1XIFt75x/VYIfu7Z/uwJPs/8lAP66F72rL69C68chOf756+4P) where the bug occurs.

**Comment by lehni** [comment]
Technically speaking, boolean operations are only defined for closed paths, and that's how we're currently handling it. If the involved paths are open, we defined what should happen as outlined here: https://github.com/paperjs/paper.js/issues/757#issuecomment-132998373

You can see an example of that in action here: https://github.com/paperjs/paper.js/issues/757#issuecomment-150849565

Some observations:

* Your paths have a fill color set, and open path still get filled if that's the case, with a straight line connecting the first and the last segment, ignoring their outward handles. Perhaps we should take styling into account when making decision wether to treat a path as closed or not?

* Your paths have the first and last segment in the same location. We could check for this when deciding, and if that's the case, close the path.

* #1072 proposes an `options` object that allows to control this behavior. We could say that in the absence of `options.closed`, its value is derived from the above information in case paths are open.

Thoughts?

**Comment by ghenania** [comment]
Sounds good. The 2 conditions (visually closed OR filled) seems to be adapted for this kind of cases.

But I have 2 additional questions:
1. If a path is visually closed (i.e first and last segment in the same location), why Path.closed() shouldn't return true ?
2. If I try to unite a closed path with a (true) opened one, is there a way to return something valid ?
For instance, if I take your example for bug #757, maybe it could give something like that (but a little bit cleaner):

![capture d ecran 2016-07-13 a 11 27 24](https://cloud.githubusercontent.com/assets/758717/16798538/d159edb0-48ec-11e6-8c00-9c10ddaf3b00.png)

 
 Am I crazy ?

**Comment by lehni** [comment]
To answer your questions:

1. `path.closed` indicates wether a path is actively closing the shape, by connecting the first and last segment with an additional curve. If it starts returning true as soon as the first and last segment are on top of each other, then it stops reflecting that additional piece of information and  we'd have to store that somewhere else... I don't think that's a good idea.

2. This situation is not really defined: Would this suggested resulting shape be one path or two? Would it be a compound path? What happens with the lines at the beginning and end of the blue path that doe not describe an area: Would they have two curves on top of each other? I so, then the boolean code would actually get rid of them because they don't contain an area. etc. 

Open paths in boolean operations are a gray area, most code I know doesn't even attempt to do anything meaningful with them. I think we can do better, but we have to be careful and consider all the implications.

**Comment by ghenania** [comment]
Ok. Thanks for these precisions.

**Comment by lehni** [comment]
@ghenania note that after `var Q2 = Q.clone().closePath(true);`, Q2 will be `undefined`, since Paper.js doesn't return `this` for chainability.

**Comment by lehni** [comment]
Here an obvious example of an [open path boolean operation](http://sketch.paperjs.org/#S/jZHBasMwDEB/xfiSDkJIMnaYx079gbEemx5UR2tNPDnITgsr/ffJ6aEZ9DAfDHqS5Wf5ogm+URu9GTDZoy61DX2OT8BqbNS7IjyrD0jH6hNtAjp4XF06UrLG4CgZtW3qulSy7cobj+4HBbcZtwucOAy4Dj6wUcXeT1j8yWwseEcHo77AR+zo+vTWUUezSLsUWTu2dwuLlJAfaDD0boomo4cGjP2/BMam4pAg4eq1zkRi60PEXpzmyrumEMlO5KR4bOfianGppOXdYIfi1rhKDBR9bv38Upcyq3xE/mDPCMM83qjNdnf9BQ==) that currently returns null.

After the changes, it should treat the path as closed if `options.closed` is passed.
