### ISSUE TITLE
Adding points using simple maths is broken

### ISSUE THREAD

**Issue by kumarharsh** [paperjs/paper.js#1090]
While using PaperJS (version 0.9.25), trying to add two points using:
```
new Point([10, 20]) + new Point([20, 30])
--or--
new Point([10, 20]) + 20
```
just concatenates the string representation of the point1 with point2 (or the number).
```
new Point([10, 20]) + new Point([20, 30])
{ x: 10, y: 20 }{ x: 20, y: 30 }
new Point([10, 20]) + 20
{ x: 10, y: 20 }20
```

See: http://codepen.io/khs/pen/JKbPOj?editors=0010

**Comment by kumarharsh** [comment]
Nevermind, I should have read the docs more carefully.

> So if we compare this (javascript) example to the one written in PaperScript, we see a row of differences. In addition to the code from the previous example, we need to:
  * ...
  * Use Math functions instead of operators on Point and Size.

**Comment by lehni** [comment]
Cool. Yeah it's a bit confusing : )
