### ISSUE TITLE
Update jsdom

### ISSUE THREAD

**Issue by georeith** [paperjs/paper.js#1093]
The version of jsdom used by paper is `8.0.1`  whereas the latest release is `9.2.1`.

We have found that the version of jsdom used by paper won't install on some of our systems due to errors in the postinstall scripts, and was wondering if we are able to upgrade to the newer version which seems to work on all of our systems?

**Comment by lehni** [comment]
This is the setting in package.json, not sure where `8.0.1` is from?

    "jsdom": "^8.3.0"

But yeah I'll adjust the range.
