### ISSUE TITLE
Call to new Curve(this, null, null) leaves handleIn of segment2 in invalid state

### ISSUE THREAD

**Issue by iconexperience** [paperjs/paper.js#1095]
Due to changes in Segment.initialize() in https://github.com/paperjs/paper.js/commit/f0edcd31b0bf59f31f5a24e39ae0d9f84ad5ae2f it now happens that if `new Curve(this, null, null)` is called (as it is done in <a href="https://github.com/paperjs/paper.js/blob/develop/src/path/Path.js#L453">Path.js line 453</a>), `segment2` of the curve has a `handleIn` with coordinates `[null, undefined]` and `[undefined, null]`.

This is the test case (problem does not occur on current Sketch version):
```
var crv = new Curve(new paper.Path(), null, null);
console.log(crv.segment2._handleIn);
```

Here is the call tree:
```
new Curve(this, null, null)
  -> new Segment(undefined, null, undefined)
      -> new SegmentPoint([null, undefined], this, '_handleIn')
```

The `SegmentPoint` finally has the coordinates `[null, undefined]` instead of the expected `[0, 0]`. Probably the easiest way to fix this issue is to change <a href="https://github.com/paperjs/paper.js/blob/develop/src/path/Segment.js#L141">`Segment.js lines 143-145`</a> from currently
```
point = arg0 !== undefined ? [ arg0, arg1 ] : null;
handleIn = arg2 !== undefined ? [ arg2, arg3 ] : null;
handleOut = arg4 !== undefined ? [ arg4, arg5 ] : null;
```
to
```
point = arg0 != null ? [ arg0, arg1 ] : null;
handleIn = arg2 != null ? [ arg2, arg3 ] : null;
handleOut = arg4 != null ? [ arg4, arg5 ] : null;
```

I just stumbled upon this while debugging some of my code. This may not even cause real problems, but it is certainly not the correct behavior.

**Comment by lehni** [comment]
@iconexperience thanks for pointing this out!
