### ISSUE TITLE
`set()` ignores `applyMatrix` unless it appears first in object

### ISSUE THREAD

**Issue by georeith** [paperjs/paper.js#1096]
Depending on object order is never a good thing. Object key iteration order is not required in the spec and is unpredictable in browsers. In practice most browsers will iterate an object in insertion order.

The issue comes when you are programatically creating objects. Such as through `Object.assign({})` where I have found the order to be varying. `Item#set()` should check for the existence of `applyMatrix` before using `matrix`.

Another place a similar issue occurs is in Raster with the `crossOrigin` property. We shouldn't be relying on order from an object ever. It's unusable in too many contexts.

**Comment by lehni** [comment]
I haven't yet encountered a browser or JS engine that doesn't preserve insertion on JS objects. Out of curiosity, could you provide a scenario where `Object.assign()` does lead to such variations?

I agree that depending no sequence is not ideal, but supporting this may have many consequences in terms of code complexity. I have to think about how this can be achieved a bit.

**Comment by georeith** [comment]
@lehni Hmmm I can't reproduce the issue with `Object.assign()` I guess that wasn't the actual problem. However I do have the following example:
```js
var obj = {
  '02': true,
  '10': true,
  '01': true,
  '2': true,
};
```

Which for me [_Chrome 51.0.2704 (Mac OS X 10.11.0)_] prints out: 
```js
Object {2: true, 10: true, 02: true, 01: true}
```

**Comment by lehni** [comment]
@georeith that Chrome example is interesting... I think it's happening because '2' and '10' are treated as integers and hence differently than the strings. This wouldn't be an issue in our situation.

I just tried this, and they keys get sorted even, but only those that aren't prefixed with 0:

```js
var obj = {
  '12': true,
  '10': true,
  '02': true,
  '01': true,
  '2': true,
};
// Object {2: true, 10: true, 12: true, 02: true, 01: true}
```

**Comment by lehni** [comment]
BTW: That behavior is consistent across the latest versions of Safari, Firefox, Chrome, Node. But on Internet Explorer as well as Edge, I get this:
```js
[object Object] {01: true, 2: true, 02: true, 10: true, 12: true}
```

**Comment by georeith** [comment]
Yeah it's just an example of not using insertion order.

I'm not sure what was causing the issue here anymore I possibly inserted them in wrong order earlier down the line. I guess its good to know can always use:

```js
Object.assign({ priorityKey: obj.priorityKey }, priorityKey);
```
To reorder even if it isn't the most efficient. Internally I guess this could be solved by supporting `Map` but it's really more of a nice to have I guess.

**Comment by lehni** [comment]
Didn't you mention yesterday that you're using a data model similar to the JSON export internally? Could it be that sequence gets changed when it's stored that way?
