### ISSUE TITLE
paperjs and canvg svg export in IE

### ISSUE THREAD

**Issue by v1r** [paperjs/paper.js#1098]
I have some problems with the exported svg when it is serialized with canvg library in IE.

I had to hack the library in order to support that by editing the following: 

```
    Project.inject({
            exportSVG: function(options) {
                options = setOptions(options);
                var layers = this.layers,
                    view = this.getView(),
                    size = view.getViewSize(),
                    node = createElement('svg', {
                        x: 0,
                        y: 0,
                        // To get more consistent scaling across browsers always ensure you specify a viewBox
                     --> //  viewBox: "0,0," + size.width + "," + size.height,
                        width: options.width || size.width,
                        height: options.height || size.height,
                        version: '1.1',
                        // Removed this as it's causing a serializing bug when the svg is passed to canvg library
                  -->    //'xmlns:xlink': 'http://www.w3.org/1999/xlink'
```

Can you please fix this in the future release?

**Comment by lehni** [comment]
This sounds like an incompatibility in canvg, not paper.js, and should be addressed there, not here. Both of these values are required to address existing issues in browsers. Removing them will break things. Also please note that we're not stating anywhere that canvg is supported.

**Comment by lehni** [comment]
This may be related: https://github.com/gabelerner/canvg/issues/189

**Comment by lehni** [comment]
But the real question is: Why do you use canvg to export SVG as a bitmap? Paper.js is already natively drawing into a canvas, as the canvas can be exported. You can also use `Item#rasterize()` to turn any part of the scene-graph into a `Raster` item, and from this you can call `Raster#toDataURL()` to get its file content as a data URL. It supports the same arguments as the native `HTMLCanvasElement#toDataURL()`: https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toDataURL
