### ISSUE TITLE
Setting the layer position gets reset

### ISSUE THREAD

**Issue by SebastianStehle** [paperjs/paper.js#1099]
Hi I try to solve aliasing (http://stackoverflow.com/questions/195262/can-i-turn-off-antialiasing-on-an-html-canvas-element) 

My idea is to translate the layers by half a pixel in x and y direction. I tried to set the position and the matrix but it doesnt work because the position gets overriden in some way.

What is the best approach?

**Comment by SebastianStehle** [comment]
Sorry, found it:

    paper.view.matrix = new paper.Matrix(1, 0, 0, 1, 0.5, 0.5);

**Comment by lehni** [comment]
See `Item#applyMatrix`: https://groups.google.com/forum/#!searchin/paperjs/applymatrix/paperjs/4EIRSGzcaUI/seKoNT-PSpwJ

And please note that this is a bug database, not a forum. Such requests are better posted on the above mailing list.

Thanks!
