### ISSUE TITLE
Zoom applying both zoom and opacity causes problems for certain paths

### ISSUE THREAD

**Issue by park9140** [paperjs/paper.js#1102]
@lehni I am attempting to upgrade from `v0.9.25` to `v0.10.2`.  I ran into this issue, where applying zoom to the view, and opacity to my imported group causes the path to draw incorrectly.

I put together this sketch to isolate the issue to a specific set of circumstances.

http://sketch.paperjs.org/#S/XY9BC4JAEIX/iuxFBVkWwYNFp/5A0FE9jOtUi7oT26JU9N8bFSpjTu+94c03T2GhR7ERxxa9vohEaGomPRgc5YOoD3aBzLalLe0ALjAsLY7BAfwlitk2EpomKlSiqpXM1Mpg+WPdvKMW99SR476whzNaD+GcnUzXfRJ3riHi7mlkFodfjpRjI3VHFheOVNIVtPF3DpTM82X1/4vZ0HwNp/4ZK2es0vLntUNor2Ssv4lNUb3e

It appears to happen on any non closed path, with a fill, when you have zoom and opacity applied. If I close the path it works fine.  
Modifying the center position of the view affects how the issues applies. 
In the example if you highlight the view causing a view update it collapses the triangle by half every time you click.

**Comment by lehni** [comment]
Oh wow, that's some glitchy stuff! Looks different on every browser also. i'll investigate.

**Comment by lehni** [comment]
Actually, the differences are due to canvas size. So I guess there's some consistency.

**Comment by lehni** [comment]
Wow, this is one obscure bug. But I'm slowly getting there. It looks like calling `path.getStrokeBounds(matrix)` actually modified the path's geometry / segments. More forensics required : )

**Comment by park9140** [comment]
@lehni, unfortunately I don't have much time to help right now or I would dump some hours on trying to figure this out myself.  Thanks alot for the prompt response.

**Comment by lehni** [comment]
@park9140 don't worry, I'm on it :)
