### ISSUE TITLE
F5, F12 keys does not work in chrome any more

### ISSUE THREAD

**Issue by Skalkaz** [paperjs/paper.js#1106]
I tried to change paperjs from 9.23 to 10.2. but it seems the function hotkeys like F5 for refresh, F12 for dev tool in Chrome latest on Ubuntu does not work any more. Is it possible that paperjs prevents it?

**Comment by lehni** [comment]
Are you saying that as soon as you load paper.js, these buttons stop working? That's bizarre!

**Comment by lehni** [comment]
I just tried to load http://sketch.paperjs.org/ on Chromium Version 51.0.2704.79 on Ubuntu 15.10 (64-bit), and I'm not seeing this problem. Could it be that you're returning `false` from a key handler event?

**Comment by Skalkaz** [comment]
Yes, if I change the version of Paper mutatis mutandis, they stop working. Thanks for the tip, now I am 90% sure, that will be the problem. I'll come back with the result.

**Comment by Skalkaz** [comment]
I call the event.preventDefault() in the onKeyDown(event) function, this causes the problem.

**Comment by lehni** [comment]
Yeah that makes sense :) So I close this, yes?
