### ISSUE TITLE
Chrome: Native setLineDash() appears to be slower than our emulation with PathIterator 

### ISSUE THREAD

**Issue by lehni** [paperjs/paper.js#1117]
This need proper investigation, but a first test with TadPoles.html and dashed lines sure looks this way. Just creating this issue now to not forget to investigate this further.

We probably should file a bug report and build in a switch that decides which one to use based on browser version numbers also.

**Comment by lehni** [comment]
More info. It's very slow on (less than half the non-native speed, I'd say): Version 51.0.2704.106 (64-bit)
Seems again OK on: Version 54.0.2803.0 canary (64-bit)

So perhaps we can sit this one out? But even on Version 54, our emulation appears to be the same speed, than the native algorithm, which is impressive. It may even turn out to be slightly faster there, more analysis needed.

**Comment by lehni** [comment]
[Here the version that uses native `setLineDash()`](http://sketch.paperjs.org/#S/7Vpbc9y2Ff4rsDqNdi0uTJAEL3KUjmM300ydmUzsJjO1/QCRkJYVl9whuVpvMv7v/QDeAO5KoybTp/ZJXODg4Fy+cwGg385KsZFnl2fv7mSbrs+cs7TK1O8XL8hWbGVNm912W9UtLUWb38s3olmTK3Ijika+/Fh+LO9FTb6t8gyD34pGUvm5lWW2+A1zbV7mbS6K/Fd5SW52ZdrmVbnYVk2uPhyyEZ/fbaXM9Nd3VZ3KJdHrPraKa9PWsrxt1XY/iHZNa1Fm1WaxJM+JS/nLjrBd5w0VaSoLWQvFFtSl3JMfq7xsF0uT6l6mbVVjXs+Z7DyyIswkHWQE8fBJ06Iqpc2xFlm+a0Dku+bwoBcmxs+LUZ0Zpda7o+w+T1OKTbUrW9CNVnlOmAtiZm2d9lT2YC1FK79v5abp5f/iKNd9bOtdaXjmGm5sRhfopYVo2rdVCo6WXWbGyG/I4tltXe2276tb2a5lPXLp+dwUVXrXb9Av+kIkMDSjA1huyxmdIc51VWeybmwv7LYZ1LPHUlGkuwLD70Ve2FOb6l7+TYpsZgprhWEUG5LydiPLthntoXA5DDqDJs0a8fJuRqoHfzTpXxp8e7gYOKWFiQFFtM1lKt8OIcEVUPSyF8Q3qRS45/7q54edP7if6EBnCWtO6L/9QiSD12uRl+S2kg1YS1IpL5O9OOCXKPWQMqziMsmi0PPzEHUrQ7me7Q0mFoowxzx7iT9fEwPtGLi4MJCkKMcgHnXJB5FXlshWQFxc9bZ6PsVLx28v7uWQYJq8XCzMVRDoOfGXysKuu7TWNUr1K0NDWletgmHiLmlZ1Rud9haK/bSwk/PCWjbRGv5dKudih3HlsbZXM21VDCr7+cthZAbEh5dabrIcZMZeh/VNBc/PQ2fKL6cCR69eI+L61PxujbpC/1oU+baRi9G7KYSU9SX54DrE/TQFk64eH5jvkHgavcmL4nVVVKA/vy5EenfeC6wls4UeKgI+p92QRqs7abNw7Mlf8qxdXxJvNvxabLECya7MphUZyuKruhYHiOo5JPhkijNHuvsA0i3ganOLLFsY1Wym3JhS/qCGwSMaPkEPHTsbxA5cZOi0PKHUlARPaTYCakjRj6LJLNKnkt1EqCPTIOwTrChvC2ntizT3iyToJnYbXQqI0Ha12gsp0jVp840k12h3MlKp5FdLSepdIRvFRde6B8tqV0a2orZE6kfkQPzcyum6KqogHshPlElFl1Zr2Rhch9825XHLpNLjJNKFsd/FyNMyVFdyT7kHJvyHnkQigR3y9nDcgV0MWhgyTIXmbb7J2z5dL7oVfyrU2F+WR6z6IjkkcAVCqwNzTlRUywwjhi4sbEzS/CQb2doIaCvidjBID2khn96HDtZrpDTx0YoaTZMN8Ll7OpC0UtY9udO14DZjUddo0f84a/SFM8594/VQXzRW5ePWu+tJHo1URTK20kZjbTZIqAKqOOVyT9W30XiOPeln5KJVt3LZS4SxK72W7lWqA5wtztbyw4nlh2H5Wua36/bR9Z/JN6e2skRZGQSrx0T55uS2llwrk+KY2bOeNG/+KesKGXbWaZvIt0D/hE53pHxSWZs2PtXHHG//xeg9jMz8imxwtKgy1XC2ZGzXGyRpjd68vB1w2FZ7UWdqpkN0z+G9uOvIZVqVGcHUTgnjENhLQR4fSDxFtW9IVu1LIho1ILbbukK0d8kdbFSvO/HVex+FnKP5KC6zIy2Ip6YBibXu+n69CB3sQ+GR5U0rSn1Q7FfZ5wOl3b4i1Vata4jyy8C9t8lG3OI0vsvkuGDByGo1VbFhC0cdh1fjyXU5QWpQiXz11STQ1+ioXcPHShIoQTKx2SqX4LOpNnKvnCbq67ytRX24nJlgyuP2Afo5WYwbvdAbPXB4fJyP3c1qJ0yGHKxuoVDTPFJd9FHdISbZIFot211ddlOztN/V+Edbg16od3I71ZHQfTmD0IOZdn7+hzcgKpH3sj4QtRvJu8NacwCjjUOA6/ROBUDenuNkV1UER/tGnur2HFLgjxZ5AJ8O+OLUOa07H/bkiHYruYzlws5Eq27VHP9HEXDqgNwhdCT6BiXaRumRYa28pA64Q0YZxNP5SUFYqLPeTV1tYHRkW9RCI6Fpd4xJzDjOMSB22H86AuKco1x0cXEy3XWJDs4St1IFYZbf5xk6zQNZV3uEZHmYorFzNRQdW+xOlhdXHQrMWtDh9EQpwHbfb7aFPrej1zmUVZGhyr8bEuoVeTNGyc9WQ3cUI6cibpBpdaq7ejjKzHGHWDE3uxV6MNiUHYcutv89BUIpkYkeiIcRBWpU9K4we1ndHD8awwNK3sD7UMvjvzt8/1sBaASTfa+HKvSmn1vYwbh8aqCZ2tu1fwiVjvEMC48Gxv9B/1TQv+6PawbmTSBDma6qLHIqKenuXJakusGZrzDjorvNBIcpIB7qsnQ/NjBWq4Yj438SJKjtZpTsNv+jMQLFxwgZ6yBR2SzLLCM/pZjYETPto3aZRYz2tY4Aw6/yaMceesaZEbyss+gRSnebDqMfy/5yThl3DaQdXV2d/8BZQMMk9BIn9AIauT7z01VEmeu53Fl5EXW9IEDbyiLq+ZHvrLhH/STgPln5Lg1cHoXOKgqxwOVJumI+ZZEfg87zwQ38QBfTkDM/clahS7nnBSFRK4Ig8ANnxRjY8NhlqdotYqHPnJUf0jDwOSerAELFLAIhT2ic6DHOKEtYnIBhQiOIF2BjsPaVLCyEyEmUQOSYMs497AtJoyDhUMPzaBxEDGNgzAIwTFfKAJEig/B+giGIR90ATKBFSJPI9ZgxFIAZ8+IkdTHNaeAFvkdiCq4MEgUhjTzOE6KntCVCnyauH7MUoiVBFMGusCaL4ogRP8KclhH0URjxmIQQMfJ5MA2l+GCJF0eOSwLIEcYxd2Ka+F7okZDT0GM8diBqlMR+kEKNJIy90MGHF4egwXrfDRl3fL9zFPED6jKfxQ6sGvgRTyPKecwTvWkcu35EYD7PjZMYOnEKN4ch8RlNODbTznATqJ4yfLhxhIWg9z1oRWCgBEaLNHyCmPtcCZmEQRxMQ6lCmwIUVIIGCYfbY7iQh0FvAeAPsvCER+lgLocp7XmiNYrCmEOjCD7jcO04ApDBDNo/nktDAC8CZOA9YNoJPOrGYaIADZuyCC4LAxoATFxjyI0913eAEt/3FHa9hPIghOWBOa50Byv42o0834kB19iLAFwIwUPA3oF3AuYxUIFr4gc8cuKQ+lALJ7zYw46+FzsMQIiZx3W4cBYp58EfQRITFTaxF3iQNKFekLiejrPEcxMngjXgouDX8ymqdR5FRH9QmVQNWG+C1rNxn9FUjtGrcCI8dZngu2bent0lHb3j2tdDXRHY7pq1vmlWj9TG4zNTzwzU5frquesxyqFc4Tj8XS02coF2sRwS9O+qMyoDP/Qwql/IhjZgscjJBdH79a9P6tFpSf5MCvX+VEC7MWfOTz7ms99EhP20gV61C/uAOlw2Yc54KxpqIO0uEft5O6WPNPXOulP+0ltQ35eODlK+1eIQ/QqzX8tStd96fJ/DaXt1OVBL5bDs0rL+T3rQMv+k2E3efqveJpqF9ve1/u4EmYga9C1y4dJ4dK/B/odq18g31b60dpiD1X7RPsHm7/JwxESZtvPinTyQqyty3mxFKs+t3qcQB73Dtq7+hV6KilT9a8VbNdobXFPQRhaY1jdEz+wR+65hDCvtiTPn7LqW4k57sDm7/PDpy78B)

[And here the version using the `PathIterator` emulation](http://sketch.paperjs.org/#S/7Vpbc9y2Ff4rsDqNdi0uTJAEL3KUjmM300ydmUzsJjO1/QCRkJYVl9whuVpvMv7v/QDeAO5KoybTp/ZJXODg4Fy+cwGg385KsZFnl2fv7mSbrs+cs7TK1O+t2MqaNrvttqpbWoo2v5dvRLMmV+RGFI18+bH8WN6Lmnxb5RkGvxWNpPJzK8ts8Rvm2rzM21wU+a/yktzsyrTNq3KxrZpcfThkIz6/20qZ6a/vqjqVS6LXfWwV16atZXnbqu1+EO2a1qLMqs1iSZ4Tl/KXHWG7zhsq0lQWshaKLahLuSc/VnnZLpYm1b1M26rGvJ4z2XlkRZhJOsgI4uGTpkVVSptjLbJ814DId83hQS9MjJ8XozozSq13R9l9nqYUm2pXtqAbrfKcMBfEzNo67answVqKVn7fyk3Ty//FUa772Na70vDMNdzYjC7QSwvRtG+rFBwtu8yMkd+QxbPbutpt31e3sl3LeuTS87kpqvSu36Bf9IVIYGhGB7DcljM6Q5zrqs5k3dhe2G0zqGePpaJIdwWG34u8sKc21b38mxTZzBTWCsMoNiTl7UaWbTPaQ+FyGHQGTZo14uXdjFQP/mjSvzT49nAxcEoLEwOKaJvLVL4dQoIroOhlL4hvUilwz/3Vzw87f3A/0YHOEtac0H/7hS9ekNdrkZfktpINWEtSKS+TvTjglyj1kDKs4jLJotDz8xB1K0O5nu0NJhaKMMc8e4k/XxMD7Ri4uDCQpCjHIB51yQeRV5bIVkBcXPW2ej7FS8dvL+7lkGCavFwszFUQ6Dnxl8rCrru01jVK9StDQ1pXrYJh4i5pWdUbnfYWiv20sJPzwlo20Rr+XSrnYodx5bG2VzNtVQwq+/nLYWQGxIeXWm6yHGTGXof1TQXPz0Nnyi+nAkevXiPi+tT8bo26Qv9aFPm2kYvRuymElPUl+eA6xP00BZOuHh+Y75B4Gr3Ji+J1VVSgP78uRHp33gusJbOFHioCPqfdkEarO2mzcOzJX/KsXV8Sbzb8WmyxAsmuzKYVGcriq7oWB4jqOST4ZIozR7r7ANIt4GpziyxbGNVsptyYUv6ghsEjGj5BDx07G8QOXGTotDyh1JQET2k2AmpI0Y+iySzSp5LdRKgj0yDsE6wobwtp7Ys094sk6CZ2G10KiNB2tdoLKdI1afONJNdodzJSqeRXS0nqXSEbxUXXugfLaldGtqK2ROpH5ED83MrpuiqqIB7IT5RJRZdWa9kYXIffNuVxy6TS4yTShbHfxcjTMlRXck+5Byb8h55EIoEd8vZw3IFdDFoYMkyF5m2+yds+XS+6FX8q1Nhflkes+iI5JHAFQqsDc05UVMsMI4YuLGxM0vwkG9naCGgr4nYwSA9pIZ/ehw7Wa6Q08dGKGk2TDfC5ezqQtFLWPbnTteA2Y1HXaNH/OGv0hTPOfeP1UF80VuXj1rvrSR6NVEUyttJGY202SKgCqjjlck/Vt9F4jj3pZ+SiVbdy2UuEsSu9lu5VqgOcLc7W8sOJ5Ydh+Vrmt+v20fWfyTentrJEWRkEq8dE+ebktpZcK5PimNmznjRv/inrChl21mmbyLdA/4ROd6R8UlmbNj7Vxxxv/8XoPYzM/IpscLSoMtVwtmRs1xskaY3evLwdcNhWe1FnaqZDdM/hvbjryGValRnB1E4J4xDYS0EeH0g8RbVvSFbtSyIaNSC227pCtHfJHWxUrzvx1XsfhZyj+SgusyMtiKemAYm17vp+vQgd7EPhkeVNK0p9UOxX2ecDpd2+ItVWrWuI8svAvbfJRtziNL7L5LhgwchqNVWxYQtHHYdX48l1OUFqUIl89dUk0NfoqF3Dx0oSKEEysdkql+CzqTZyr5wm6uu8rUV9uJyZYMrj9gH6OVmMG73QGz1weHycj93NaidMhhysbqFQ0zxSXfRR3SEm2SBaLdtdXXZTs7Tf1fhHW4NeqHdyO9WR0H05g9CDmXZ+/oc3ICqR97I+ELUbybvDWnMAo41DgOv0TgVA3p7jZFdVBEf7Rp7q9hxS4I8WeQCfDvji1DmtOx/25Ih2K7mM5cLORKtu1Rz/RxFw6oDcIXQk+gYl2kbpkWGtvKQOuENGGcTT+UlBWKiz3k1dbWB0ZFvUQiOhaXeMScw4zjEgdth/OgLinKNcdHFxMt11iQ7OErdSBWGW3+cZOs0DWVd7hGR5mKKxczUUHVvsTpYXVx0KzFrQ4fREKcB232+2hT63o9c5lFWRocq/GxLqFXkzRsnPVkN3FCOnIm6QaXWqu3o4ysxxh1gxN7sVejDYlB2HLrb/PQVCKZGJHoiHEQVqVPSuMHtZ3Rw/GsMDSt7A+1DL4787fP9bAWgEk32vhyr0pp9b2MG4fGqgmdrbtX8IlY7xDAuPBsb/Qf9U0L/uj2sG5k0gQ5muqixyKinp7lyWpLrBma8w46K7zQSHKSAe6rJ0PzYwVquGI+N/EiSo7WaU7Db/ozECxccIGesgUdksyywjP6WY2BEz7aN2mUWM9rWOAMOv8mjHHnrGmRG8rLPoEUp3mw6jH8v+ck4Zdw2kHV1dnf/AWUDDJPQSJ/QCGrk+89NVRJnrudxZeRF1vSBA28oi6vmR76y4R/0k4D5Z+S4NXB6FzioKscDlSbpiPmWRH4PO88EN/EAX05AzP3JWoUu55wUhUSuCIPADZ8UY2PDYZanaLWKhz5yVH9Iw8DknqwBCxSwCIU9onOgxzihLWJyAYUIjiBdgY7D2lSwshMhJlEDkmDLOPewLSaMg4VDD82gcRAxjYMwCMExXygCRIoPwfoIhiEfdAEygRUiTyPWYMRSAGfPiJHUxzWngBb5HYgquDBIFIY08zhOip7QlQp8mrh+zFKIlQRTBrrAmi+KIET/CnJYR9FEY8ZiEEDHyeTANpfhgiRdHjksCyBHGMXdimvhe6JGQ09BjPHYgapTEfpBCjSSMvdDBhxeHoMF63w0Zd3y/cxTxA+oyn8UOrBr4EU8jynnME71pHLt+RGA+z42TGDpxCjeHIfEZTTg2085wE6ieMny4cYSFoPc9aEVgoARGizR8gpj7XAmZhEEcTEOpQpsCFFSCBgmH22O4kIdBbwHgD7LwhEfpYC6HKe15ojWKwphDowg+43DtOAKQwQzaP55LQwAvAmTgPWDaCTzqxmGiAA2bsgguCwMaAExcY8iNPdd3gBLf9xR2vYTyIITlgTmudAcr+NqNPN+JAdfYiwBcCMFDwN6BdwLmMVCBa+IHPHLikPpQCye82MOOvhc7DECImcd1uHAWKefBH0ESExU2sRd4kDShXpC4no6zxHMTJ4I14KLg1/MpqnUeRUR/UJlUDVhvgtazcZ/RVI7Rq3AiPHWZ4Ltm3p7dJR2949rXQ10R2O6atb5pVo/UxuMzU88M1OX66rnrMcqhXOE4/F0tNnKBdrEcEvTvqjMqAz/0MKpfyIY2YLHIyQXR+/WvT+rRaUn+TAr1/lRAuzFnzk8+5rPfRIT9tIFetQv7gDpcNmHOeCsaaiDtLhH7eTuljzT1zrpT/tJbUN+Xjg5SvtXiEP0Ks1/LUrXfenyfw2l7dTlQS+Ww7NKy/k960DL/pNhN3n6r3iaahfb3tf7uBJmIGvQtcuHSeHSvwf6HatfIN9W+tHaYg9V+0T7B5u/ycMREmbbz4p08kKsrct5sRSrPrd6nEAe9w7au/oVeiopU/WvFWzXaG1xT0EYWmNY3RM/sEfuuYQwr7Ykz5+y6luJOe7A5u/zw6cu/AQ==)

**Comment by iconexperience** [comment]
Just to add my two cents: On my Windows 7 (64Bit) with Chrome 52 both versions are very fast. If there is a performance difference, I cannot see it.

**Comment by lehni** [comment]
Yes the anomaly has since disappeared on my Mac as well. It was probably a weirdness of that particular version. Impressive though that our PathIterator code performs the task as fast now as Skia's native code!
