### ISSUE TITLE
Union of paths without intersections sometimes ignores one of the paths

### ISSUE THREAD

**Issue by MartinBolot** [paperjs/paper.js#1122]
Hi,

I've noticed very strange results when using `unite` on two paths that don't intersect: sometimes, the resulting path contains only the segments of one of the original paths. See this [sketch](http://sketch.paperjs.org/#S/dZJLTsMwEIavYplFUslKHTdEVStWXADBMmThxkMbxbUrx6ULxN3xgwTSpiuPZ75/Hpr5woofAW/wWwe2OWCCGy38/5MbdOL2gJ6QgoszT2CyF+dIF9t35SNZb43u4FlLbRyVPFBKkyH20Uo5RgwIH1guhYZeJRZdtOkcqFtl82kB70rXlKBHShdBE+DeW/f5fOQDw2aYgpUE/SGrOaRc/0eKGSRnbCwVmruayI/OhUhjqyR2E59VfIqbqSaagsxJo2ZKDvmmgjnyqoFfQRwhkI3UPQg3rjVnCG6/fQON5Wov4eYEstchlFbM7YrRmqCqdFZJa5/Xyxt93LUqpA1Fzqq1kI5JPTYg02vZGwCVbN0p7gzwLnTb401Vf/8A)

Even stranger: 
- note that if you reorder the points of the shape that vanishes, you can manage to get it to appear in the resulting shape: in the linked sketch you can switch the order of points and see the difference.
- note that if you change slightly the coordinates of the shape that vanishes, you can manage to get it to appear in the resulting shape: you can switch the coordinates of the first point to `81, 500` and see the difference.

**Comment by iconexperience** [comment]
Thanks for reporting this. Not sure what caused this, but it seems we fixed it already on the `develop` branch. You can get the latest build from https://github.com/paperjs/paper.js/tree/prebuilt/module/dist if you want to try yourself.

<a href="http://sketch.paperjs.org/#S/ZVBBDoIwEPxK0wuYEIKNEoLx5AeMHiuHUlYglC0pVQ/Gv9uCcPE2uzM7M+2bouiB5vTagZUNjajUlZ+fwpBB2IYcCcLLwQFMfHaL8D1C3QPaMSecZ0lE9klSRITvWBqRGaXZD20Zm/nisznc0BvGozW6g5NW2jjzwEAVLJRUeoQpxKtv6EsYkFZgreCvSXxZqJAz14NNkalDaVJ4A38udV+2CJW7niIe2FoIV1MvWyTxvVVq7VUbAAwO7kdKA6IbdOueTHNefL4=">Here is a simplified Sketch</a> that we can use if further testing is necessary.

**Comment by lehni** [comment]
@iconexperience thanks for the test case. This works on `develop` even if a turn off my code for #1113, so I think this is fixed either way.
