### ISSUE TITLE
intersect() operations results in open path

### ISSUE THREAD

**Issue by iconexperience** [paperjs/paper.js#1123]
Here is a rather simple example that does not work with the current development version:

![image](https://cloud.githubusercontent.com/assets/2122773/17178328/50d7453c-5415-11e6-856c-d53de340998e.png)

```javascript
var p1 = new paper.Path({segments:[[29.562573408343212, 132.54192488999095, 0, 0, -1.417935581083043, 0.174100597711913], [2.5662795205536213, 124.83546947214427, 13.887634830511104, -1.705187144644185, 0, 0], [18.447017946814753, 122.88555997766193, 0, 0, 13.88763483051116, -1.7051871446442135], [45.443311834604344, 130.5920153955086, -1.417935581083043, 0.17410059771188457, 0, 0]], closed:true});
var p2 = new paper.Path({segments:[ [5.684341886080802e-14, 132.07000000000002, 12.910000000000025, 27.075000000000017, 21.125, -21.119999999999976], [44.59500000000003, 130.54000000000005, 0, 2.3300000000000125, 4.816669792192272, -4.501887430254385], [56.887403180177614, 116.74936916538223, -3.66267533741933, 4.517228939026069, 0.002528361414420033, 50]], closed:true});            
var res = p1.intersect(p2);
```

<a href="http://sketch.paperjs.org/#S/jZTNbtswDMdfxfCpAxJB/JSUYZftBQb0mPTgpWob1LUN21sxFH33UW6zZOs2THaASCR//JMU/FR3zUOuN/XlfZ73d/Wq3vfXZb8bd923ZqwGqD5UXX6shmbIo/vczHcXT1O+fcjdPG22W0xOFCUQ+0hMCLiqgNAJQ0KOMaXkk6wqv7xrcAwhkUgE8/dMduwgMHgvKQSABHS1qrYGUMWQBL0IKYI5ArKLJKyJAwIzhpLKxRiU2GACAJ6XJME2MZiPMkN8TV+4EB1z8KaBNQIHWbhoEBFJpkAVEh3l/k7XN3ATJoXLYlwiAGuCWlnMJdo7SehBKIn4qP9Tf4ws4VWvgfdtP+XrzTx+zc/v3v8cCv5zKNVWnEYTYTT10R7Ma+CXwfjgT6sMC12C8yPrFgZzk9MZmCIEB8W2Ln8gnVbQpQFstZ6F0Gv9fIZ+mQM6orPDBWqDBVVNIaFdGwyma21AbwUEJtPEFJc+i5aJsCeIpiroUhWoC5xIE6hQRLTca3J2f9TmS9bcRFRyCATEmCh5VK+ptL7Ui5GMUy6UyTZH+Uvnj90f82TtH8AdujmPU97PFwO+uJjJ3Rza9lPf9qM57ervuW37x119tB66KY/zx2yHFwOcwNXZKnvDT/PY3+cT6nbMudvVS8iAb8xjvj4aj7GX+6Y9dLdmvmnaKf8a+Sfj7z/7HnwZc3M/9FbrVG+2V88/AA==">And here is the Sketch</a>.

It seems that `propagateWinding()` gives the correct result, but tracing the paths cannot find the closed contour. Here is <a href="http://sketch.paperjs.org/#S/tVTBbtNAEP2VVTgUJHs7szOzsxOOcEVC6hE4GNdto6Z25AQVqeq/M2tCQfSABOHgOPs8q33z3pt9WI3d3bBary5uh0N/s2pW/XRZ1+fnYTdPu+66O2ymMfQ33Wbch+kqDF+7u912CFfzdBc2+/2XIbxATPRx/jj6pnm4XIf7zXi5Ga9DOoLX8zCMP2GscH3G4T7sut0wx/fd4eblw85/33aHbh3O3iHExCTcYOJobKVvU2SGkpoWIgkxhlYiYFGriH9SCa3GrJpyRRCZaIscSynoNRhLKsBnTdgf5ul2eDNtp9mPWtg9oRd9t3WS63DVbffD46vXfySqkYVZnShFAGXaQjRLIguJ5AR7TFEEMlYSwggpeC1BNmlyRDIuIWUHCqVGowDjyWkyRxUhapBcvmLa+wtNuXGSLFQCOEf0Plx4NKjr7NqWuoZEadv+aOvY1TOG7v0/8WMB1YWfIpWybZ+8O1rXu3zIeWHgdmtozRV3Tk2bI5gRhxattgXUeBTEEtJpaf4eS7V+iaUjTg4YXDhnLZpKBbIrrkFdUTCqgHGiEyv3PIA9kguneTlRQdBCkihaKHu8SgHJNW9mOZkDCpnz/3bT4wbmU1uHAhAVQzXR1ViArEK/AqjHLUKiS4V4Z7UCFHCpAMAFyEDftwic2OvnI+MAI/pxtT3NFkoUhApYpez580lHSuCc3YPMzq12AUmoEQgtUzT1meMUySSTX2G5WuV5kuj7MvVUj8p+X9U/pVjwAjL1jEvM2S0LTxn0iKPPJv7NXVEfv+4/z0N3u5s242G/Wn/49PgN">the result of `propagateWinding()`</a> (red curves have winding 2, green ones have winding 1).

![image](https://cloud.githubusercontent.com/assets/2122773/17178364/8032b514-5415-11e6-89e4-a8be711442cc.png)

**Comment by lehni** [comment]
Does it find all intersections?

**Comment by iconexperience** [comment]
It finds six intersections, all crossings. Here is their location:

![image](https://cloud.githubusercontent.com/assets/2122773/17180169/db3a3936-541b-11e6-990d-bedfb312e5bf.png)

Looks correct at first glance.

**Comment by lehni** [comment]
Why are there two at the top?

**Comment by iconexperience** [comment]
I think this is correct. The paths are crossing twice almost at the same point, so this is more a "touching" of the paths. The green path is outside before and after the two crossings.


![image](https://cloud.githubusercontent.com/assets/2122773/17181037/e632ee8e-541e-11e6-9cd8-1756569720c5.png)

**Comment by lehni** [comment]
I now understand why this happens. Fixing it will merge with my efforts for #1091

**Comment by lehni** [comment]
Ok, so this was easier to fix than I first realized, and fixing this has lead to some nice improvements and simplifications in `tracePaths()`. Quite a few less hacks in there that I don't fully understand, now :) There has been a whole lot of improvements on boolean code today, BTW.
