### ISSUE TITLE
Should #hasStroke() return false for groups?

### ISSUE THREAD

**Issue by georeith** [paperjs/paper.js#1124]
Seeing how groups never actually draw their own stroke. Setting stroke values just changes the strokes of children. Should `hasStroke()` return `false` for groups?

Not sure if this would break anything internally. I just caught this in a piece of code that was working out `strokeBounds` for items and was incorrectly expanding group bounds. Seeing as `hasStroke()` means it has a visible stroke should it not be `false` here?

**Comment by lehni** [comment]
The way Style works on Group currently is that it unifies the style of all children. So if all children have a stroke, then the group will say it has a stroke...

Note that this behavior will eventually change, probably vor v2.0.0, once version 1.0.0 is out. See here:

https://groups.google.com/d/msg/paperjs/pJzsEYv2W7M/h-jSWu3j-tQJ
