### ISSUE TITLE
view.on("resize") gets previous view.bounds values

### ISSUE THREAD

**Issue by marquizzo** [paperjs/paper.js#1127]
Whenever I use `view.on("resize")`, the `view.bounds` object still has the values from before the resize took place. This is very noticeable whenever I hit the browser's "fullscreen" button on both Windows and Mac platforms. 

I've made an example to demonstrate. This is the code sample:

``` 
view.on("resize", function (event){
	view._needsUpdate = true;
	view.update();
	$("#messaging").append(view.bounds.width + "<br>");
	circle.fitBounds(view.bounds, true);
});
```

**Step 1:**
On load, view.bounds.width is 640, as expected
![Step 1](http://i.imgur.com/UM0NWuV.jpg)

**Step2:**
When hitting the green full screen button, the browser 'pops' to it's new full size. `view.bounds.width` is still 640, and `circle.fitBounds(view.bounds)` still occupies previous bounds
![Step 2](http://i.imgur.com/VpMpxct.jpg)

**Step3:**
When exiting full screen, the browser returns to its previous size. `view.bounds.width` is now 1280, which is what it should've been when I was in full screen.
![Step3](http://i.imgur.com/JEcfnIm.jpg)

Here is a working example demonstrating the bug:
http://dyadstudios.com/code/paperjs/resize.html

*Note that this bug isn't very noticeable when resizing by dragging the browser corner, since the difference in values is only of a few pixels. It's very dramatic when you use the "fullscreen" button, because then the previous value is drastically different from the current one.*

**Comment by lehni** [comment]
For reference, [here the example as a sketch](http://sketch.paperjs.org/#S/jVHLSsQwFP2VS8ZFi6VTcTUddeH8gCDiwoikye00tHNTkrQFh/l3k1TUpbvc8+IccmYkTshq9tyjlx0rmDQq3rOwILWVA8I9EC7wJHxXHhKSnTlxb4XSk6vhtiri2ephOJjB2Bo427S7irOEj8Zprw3VMGtcSonk0SbGeWt6/PVUu/bbszKvWvmuhpuK0yXfB5zWQmWr/aOZSLksRTbpXYC3E666BBvKOLPo9CeGWGgnkrEHZDiHDnnakIQfhKjcy6iEj2NjzP6HnBKcpVy/3cJVCN2c0Dlx1HTkLC/FOCKpv1XKJTaH6zDqrrEPQZTc/2sfpoZfaCyKfjSavGP12/vlCw==)
