### ISSUE TITLE
how to access vector.length in direct JavaScript?

### ISSUE THREAD

**Issue by brenna** [paperjs/paper.js#1130]
I'm following through the "Moving an Item" tutorial [here](http://paperjs.org/tutorials/animation/creating-animations/) and can't access `vector.length` via direct JS.

Is there a way to access a vector's length with a non-reserved JS property?  

I'm computing like this for now:
```js
Math.sqrt(Math.pow(vector.width,2) + Math.pow(vector.height,2)) 
```

**Comment by lehni** [comment]
It looks like you're dealing with a `Size`, not a `Point` object. Only `Point` has `point.length` defined. You can do this:

```js
var length = new Point(vector).length;
```

**Comment by brenna** [comment]
perfect. thank you!
