### ISSUE TITLE
Error when exporting clipped groups to SVG

### ISSUE THREAD

**Issue by iconexperience** [paperjs/paper.js#1138]
In this simple example, I get a _"Uncaught TypeError: Cannot read property '_id' of undefined"_ error.

``` javascript
var p1 = new Path.Circle({center: [150, 150], radius: 50});
var p2 = new Path.Rectangle(100, 100, 100, 100);
p2.fillColor = "green";
var g = new Group({children: [p1, p2]});
g.clipped = true;

project.exportSVG();
```

<a href="http://sketch.paperjs.org/#S/TY8xC4MwEIX/SshUQUQFF0unDl1LhS7qkMarpqZJOGNbEP97T3FweXDHfe+9m7gRb+A5L3rwsuMhl7ZZ5o9A5hJ2Yga+7Cp8F50VSg2HSYLxgDkrkywOGUkdMhSNGoecZfEcHCuzwukevoH0wrTEJ/FC7WUhXBo9ldZnqy0SV/EWAUzFN7N287qgHR1V6JRuEAyVcElIUfUa20ZSK+egoWuPI9CKnNG+KDyCn7Poi/vlEKx7evWBIHpnlfEDz8t6/gM=">Here is the Sketch</a>

The problem is in <a href="https://github.com/paperjs/paper.js/blob/develop/src/svg/SvgExport.js#L324">SvgExport.js getDefinition()</a>. This function is called by `setDefinition()` without any arguments. `getDefinition()` accesses `item` to get the `id`, but only in the next line it checks if `item` is defined at all.

So my suggestion is to simply change <a href="https://github.com/paperjs/paper.js/blob/develop/src/svg/SvgExport.js#L329">line 329</a> to

```
var id = item && (item._id || item.__id || (item.__id = UID.get('svg')));
```

P.S.: This issue feels strangely familiar, as if I had reported this before. But I could not find anything in the issues database.

**Comment by yincrash** [comment]
You are probably remembering this comment: https://github.com/paperjs/paper.js/commit/2c2542fb2f245251c1c13d82372b9f7898abc236#comments

Just ran in to this.

**Comment by mheesakkers** [comment]
Also ran into this :(
