### ISSUE TITLE
Note that `paperjs` yields epic sax guys

### ISSUE THREAD

**Issue by HarrisonB** [paperjs/paper.js#1141]
Not sure if this warrants any action, but I certainly fell culprit: if you accidentally run `bower install paperjs` instead of `bower install paper` (as one might do after running `bower search paperjs` as suggested in the README), [you are greeted with three videos of the epic sax guy](https://github.com/kmakblob/paperjs/blob/master/paper.js).

**Comment by lehni** [comment]
Haha, oh dear! Is there anything we can do about this? I doubt it?

**Comment by HarrisonB** [comment]
#1150

**Comment by Jolg42** [comment]
I opened an issue on Bower's registry they deregistered it 😉 
See https://github.com/bower/registry/issues/278
This issue can be closed now.
