### ISSUE TITLE
Performance when animating a few paths is bad

### ISSUE THREAD

**Issue by PhilippSchreiber** [paperjs/paper.js#1145]
Hey there,

i'm trying to create a simple animation of n lines. Here is a [Sketch](http://sketch.paperjs.org/#S/pVRNT+MwEP0rViTUpC1uGwSHhJ4WsZeVFgluaQ/eZEK8be0qdhNY1P/O2PnAYSsQIofUmXl+88bz3BdPsB14kXe/AZ0W3tRLZWa+K1aSjCvNRApkScL5dCUIPqk8CP07/8UFKIxfhH18K8ufbI+xxcwFtfmaVXDHdPHD4BCUzKdkMSXz9bu8IU3W8UqsRI5A3+jgGJvH+HO9HNTH0GQSkJeGwSA7FtwgoCZm6QfxsAJVupQb6IQYnF37A4kJKhuKThYY4WTct/ofMcsy35aVXGgfG6w41NS87vk/oAXwx0KTMV1ckoll6g44+IRqyFPzTBez8DT9LPw+92nmMb36VLei+4Mq+pM06aMZpZmNhifdzcVUfsBvv53d3gSipmwKQkPZ2uLvQWme85RpLkVERk1y1GZzKbRRGJGLzp85327tuBBcF1zDCCUEcSfCKjPFbgCJhaVFUTZESyYyufMD7NAqUUjdOPEgUouU4rbE++JDhTp65/G8CVBrTnJGQrJEx9p8g+j8uZeKtyX7I0OnUQWPOyRQ6DFqzyJ+v7OCVFu/nuzgvGcebPziDXLrOTfpTSnvbqv7tNodoNvOQI8Db9qkT2SybHvD9QznGH8Ef3bgz6fgbxJ2UjqX3zzHZmkNiS/8r/tTAttYZuVFyfr4Cg==)

Originally I wanted to have 64 lines but the performance is already bad with 32 lines (even i I throttle the frame rate). Does anyone have a tip what's causing the bad performance?

All the best
Philipp

**Comment by TrekkerUK** [comment]
What the specs of your computer and browser name / version you're using? I've got a 5 year old i5-2500 CPU and a 7 year old Radeon 4890 running a 1080p screen and in Chrome I can run that sketch with *700* lines at 60 fps. 1,600 lines brings it down to 30 fps.

**Comment by PhilippSchreiber** [comment]
I got a MacBook Pro Mid 2015 wit 2,8 GHz Intel Core i7 and 16 GB RAM. Graphic Card is AMD Radeon R9 M370x with 2GB of RAM. Actual Google Chrome.

I can watch all demos of three.js with 60fps but this small paper.js thing does not run fluid.

**Comment by sapics** [comment]
@PhilippSchreiber
How do you judge good performance or bad one?

Just my feeling, it looks good performance in Windows Note PC.
It would be a bit faster but almost same: [sketch](http://sketch.paperjs.org/#S/pVTfT8IwEP5XmiUm44cFRvQB5EmjLyaa8CIZe6jbwRqkJWsZIuF/99qxsiGRGPuwddfvvvuud7edJ9gSvIE3XoCOU6/txTIx3znLSMKVZiIGMiJBtz0VBFcs10K/zJ65AIX2fuDsHzJ7Yiu09TpV0OF8w3J4ZTq9NzgEhd026bVJNzo5N6RhNJyKqZgh0Dc6ONq6Q3zdjWrx0dRqNciuYDDIkgUdBGyI2fqNYT0CVTqTCyiFGJzd+zWJISqriw57aOGk6VL9QcySxLdhJRfaxwRzDhtqHmP+BTQFPk81adLeDWlZpvKCGxeo6jwbnui0E5yn7wT/5z7P3KS3F3Urulqr1N2kOd6bUrramJAPoDQXTHMp8P6tiWZMJHLpN5DcxlYYF51naxFbnBSPGTaqDzkI7UrOZ4WB2q4gVyQgI2wVd162xUoqfgjnlGKBqYL5Et0VlpaujI5h3S+HWNsmOav92vGeuMUpE3N4Q7+CgH6SDumXE1SuAjU5orYWVeH64wBUJVQG4Zgxj04kmGXzrsB+vRTngCm1RmWiZwHbI2ByAjiGWkpZmVCz9sV2bxsHf0fvGbCFZVTeIIz23w==)

**Comment by jo-fe** [comment]
I have a late 2013 Macbook Pro Core i7 Iris Pro 5200.
Your initial sketch is very fluid for me on Google Chrome 52.0.2743.116.

**Comment by sapics** [comment]
It looks good performance in the other PC. I will close this issue.
But feel free to comment if you have any information, we will reopen again.
