### ISSUE TITLE
Rectangle inconsistent

### ISSUE THREAD

**Issue by georeith** [paperjs/paper.js#1147]
Depending on how you create the `Rectangle`. Modifying a side property may shift the entire `Rectangle` instead of just that property.

E.g.,

Shifts:

``` js
var rectangle = new Rectangle({
    point: [0,0],
    size: [100, 100],
});
rectangle.left = -10;
console.log(rectangle.right); // 90
```

Doesn't shift:

``` js
var rectangle = new Rectangle([0, 0], [100, 100]);
rectangle.left = -10;
console.log(rectangle.right); // 100
```

http://sketch.paperjs.org/#S/jVDBDoIwDP2VZidMJhkcMf6EHhmHOSsQZke2RRMJ/+6QGFAv9tCkr+17rx0YqSuygh07DLphnGl7nuqbcuBQB0W1wQz2QHiHwxtIBkkQo7cthQJKwUXFZ8i3D4xIJgSHmCZ43OwkSVroUoOXEDm3mYgdbclbg6mxdbKacW3dhHlT0oed/MfObGCl+qWY/6GYL4rxDSeHqnud51lRVuMT

**Comment by lehni** [comment]
This was long overdue, and involved quite a bit more than just the case you described. Check the [unit tests](https://github.com/paperjs/paper.js/commit/49fca5510ed767fae87bfea373d73a66e6b7696e#diff-a8505e11f77c9f8fa50a9187f76258c2R72) for details... Seems to work reliably now, finally!
