### ISSUE TITLE
IE 11 CPU power to high

### ISSUE THREAD

**Issue by ZergRushJoe** [paperjs/paper.js#1148]
When running the code attached I have seen the CPU usage,about 30%, in IE 11 and was wounding if any one had solved this before or there some things I can do to make it better.
[cirs.txt](https://github.com/paperjs/paper.js/files/433149/cirs.txt)

**Comment by iconexperience** [comment]
CPU usage is higher in many Javascript apps on IE, so there is often not much we can do. But in your case you can speed things up by using <a href="http://paperjs.org/reference/symbolitem/">SymbolItem</a> for the circles.

I have modified your skript to use SymbolItem. <a href="http://sketch.paperjs.org/#S/7VdLb+M2EP4rrIoCUiWrkpOgWLtZoNiiQA+LFvWhB9sHRaZsInoYFG3HDfTfO6RepEgrTrC7LYrVIbI4w/m+eZGTZyuPMmzNrMUjZvHO8qy42PDvY0RRTGiJ7lGOT+hnSqOzfRc48xVd5VxYsmKvSm9roRAsg3Uj+6MgObMDD4WBtDuLnoRAUToSfPL5nwX5G/snsmE7D6mLO0y2O9bbAYpxin/BSWNocc4eihS+SU4YKXJbWI/Yzv8gNO3nGOcM0xlaAqVg7SEabcihnAE9DyUkTT8UaUFn3P6KPdcvBM+W68HWRtLJaqnwGWwuV9a3MTxJsrJq80uB46Hp3V29EK7XnryV243SGWL0gNv1yuuBC0q2JO/49oINLhnJI+5lLQ2DdS2tKqeOUHLIYy4HkHxTZL9BjCHwHspI7nC58EGQwOxAc/SRBypJi4La4me9zXbQ94hvRBOxE7niJRAqBabEjMfa3hDa228xyhOBCkOdkK91BPgTRyVGwUxe6mI7rKfeoVbsPwGvOwiDsjANHA8ZlM8gg4KUtM/gHS/R2i+dQKgS6FEUG64ENg2aqr9kcmoyGdbEDWa8jslrgW5MQNMXgUDjrJt8oDh6nMuZ7ZIX/n+SNxEAk+kXSN8VUF8qgdOv3TeIqZScz91/BqhXJ/Dmawe+KYWfrAffkET+VfWXaUGRzUcbAnDBHF4/iUHMT3G+ZTtYcF318iYJskH5HmYM88V6aSL7sZ3IOgb8B06hjmqb36Fbbjd4hdlB+QRy+dyKNuHTBDHgtsODpA8Tj5QOHoUlaeH4PHcgTAx4+2iPqS92C3xHGk7eFtMGywdSh73t6KNOkf9KYXK2sT7oXI2mRbRFpYfcdvTSgNFQptBGYA9+q+zZjpQ+XwYC/DXXBH7JaPGIxbALSjC2BvC8e7eyLur+xedx0L1RNeoJHNa7Udzfp1GM7X5/Am6xBd5mMD/7e14mjmpDRBlMdK7ZanzkGCnRlTjW5qUgo/dIKaXQQbA6mTiyNSX8qtcUZ8URN7RtonZwJX+IPcDrFNENJwWT/FyTNwQXOMUxw1wv1JXiA6VCSegaHYSzS9+X8Fr8M2I8D73T/Difyj3e6TOS4d8PTNMOjdqQz/NFvwR0KSpdkx3BVVFftsG7uhLg2pDKCNZK8X+bg34YeNbdd11fqDWU4yf2ERKmlFG5zZi51czh5vpjbnD5W3gb+EKPj1S8IcSuq135/JTuMnRFXTdkj6QkD6JntZQOVVu/kHsvx0Lb0zFpy+F+EAZnuENrbHNVTUINS8Wr204zbwyCHjfD0cEHGTg7TE1rRBlF6hxqy9OAu3RdE9ja0fItP9UlAb+/Pw/PyWSE56jV/nD8Rk3by1ubwyeJwK2L2sZgGBcvReflWhke4O+luehqa51bnzTO/0ItjNbsqNX/Ri0oC8rHMGZXHqVmUpfOxeYCNp+KY74bT+xOaezY1D1Wb6bK8izxT4m430prtlxX/wA=">Click here</a> to see the modified version of your skript in action. On my computer CPU usage is about half compared to your version.
