### ISSUE TITLE
PaperScript compiler produces invalid JavaScript (ReferenceError: invalid assignment left-hand side)

### ISSUE THREAD

**Issue by nebaughman** [paperjs/paper.js#1151]
**Version:** Paper.js v0.10.2-develop

**Problem:** PaperScript compiler produces invalid JavaScript

This is valid JavaScript:

```
1 < a.count && (a.radius += 2.0);
```

PaperScript compiler [(probably around PaperScript.js Line#255)](https://github.com/paperjs/paper.js/blob/develop/src/core/PaperScript.js#L255) turns this into invalid JavaScript:

```
1 < a.count && a.radius = __$__(a.radius, "+", 2.0);
```

Browser console shows [this error](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Invalid_assignment_left-hand_side):

```
ReferenceError: invalid assignment left-hand side
```

**Workaround:** Don't code this way.

**Background:** I discovered this after compiling some PaperScript code with [ClosureCompiler](https://developers.google.com/closure/compiler/), which minified this if-statement: `if (a.count > 1) a.radius += 2.0;` into `1 < a.count && (a.radius += 2.0);`

Overall, supporting the offending syntax would make PaperScript code more compatible with ClosureCompiler, and avoid producing invalid JavaScript (in this otherwise rather esoteric case).

_(PS Thanks for this fantastic library!)_

**Comment by lehni** [comment]
Thanks for spotting this! It looks like the problem is that the parenthesis are being dropped, correct?

**Comment by lehni** [comment]
[Here a sketch](http://sketch.paperjs.org/#S/q1bKS8xNVbJSCs5OLUnOUNJRSs5PAfHLEosUEhVsFaoVkvNL80qsFAx0FIoSUzJLi4HMWuuYvJg8QwUbhUQ9sLSCmpqCRqIeRIGCtq2CkZ6BJlAR0LykotTE7IL8zLySYiWr6NhaAA==) to reproduce the issue.
