### ISSUE TITLE
Can't change hue of group

### ISSUE THREAD

**Issue by maxim-danilov** [paperjs/paper.js#1152]
It working:
[http://sketch.paperjs.org/#S/zVRtT9RAEP4rY78osd3uS3f7ImDkQCCpSgJijDWmd7deK2XbtHt3KOG/O1vuDBB+gB/a7sw8z8yzs9259Ux5rb3MO7/SdlZ5vjdr585elT2UsAdd3/7SM0vq667t7fnl8auXu29vrhtY6X6oW7NXeIzQwgNtkFmbBTrqoQ2SRKYBK7y3+7D7IgjgWBvdl7btM3g3b6caTptmOdjRBUwRSqgPmB6OblwhOGuWi+DUABmdl/fFMkAghYNl3cyB7kAQuOyHnyYXX8+OYFgt4OzzQX46gcILwvCLmITh4cXhmIERFoZHH1Fo4VXWdlkYrtdrshak7RfhcV92VT0bQoSGDoq0EPMxRuZ2XnhYxmV/uGfcG9RzXE7KrvzhLOyKGfaeS88ppS7dFpTdNLW5ehbK0jQNx7ADI4R2N7j6/W+1rue2QitiMWFcjr5K14vKPnGuar0+aMcUQGET2X4xPtjfjcaoNuW00cG0nF0t+nZp5pnRa3iG8+ZefjZ05cwRu14Pul/psT0LfLrSVuBa8kEIQTiPfZESGckmkBFJmfITQShzpiKxCu6tkw32D3zgCuGJ8lnEHO2ERTGJZdwoSlKa+FwwolSaP4EhkUlGEi58xmOSRrJiTBCVJGOhJIpdJSbzJyjHQ31UOA8nUjVOlhRbXUlEGFP5Y4wjpRJhiS/iGGVAEyhOqIwDLvDnFPKE5o8RSKGEpduyJ4wrwtM8ZkTI1I9cZ/KHAMSLSJIkwaAkVI3dSwR2j6MTN8ddUED+COXah8JVxLZ9yTnHb7yRoRqnSkYbnbi/DfxP4YV4duFic4j/wcJdlX14ufOmMG4MVUuNg4iiVZifSzOzeAWhNe97nFyv9EobuwO3GLQl+Vk3zaRtcKTswa0jZu7lw1DaJY6acYQwH6a9uy9GDwOacOe4rshrrEKkq2MLc4ezcNrr8qpra2MHL/v2/e4v](url)

But it not working:
[http://sketch.paperjs.org/#S/zZR9b9MwEMa/ypF/xkTi+CV2kkKZWDfWSRlM2gAhglDaek1Y5kSJ2w6mfXfOWYvYtA+Aqir23e+5e3x5ufNMcaO9kXdxre289Hxv3izcfl10UMAY2q75qeeWVDdt09mLzycv994c3N7UsNZdXzVmnHuM0NwDbVBZmSUGqr4JkkSmAcu9g7fw5kUQwIk2uits043g3aKZaTit61VvhxAwRSihPmB5OL51jeC8Xi2DUwNkCH5+aDYCBCkcrqp6AXQfgsBVP/o4ufx6fgz9egnnnw6z0wnkXhCGX8QkDI8uj4YKjLAwPP6ARnOvtLYdheFmsyEbQZpuGZ50RVtW8z5ENHQoykKsxxhZ2EXuYRtX/d8z49mgWuByUrTFD7fDqZh+/Fx5Til15XbQ6LauzPWzKEvTNBzSDkaEtre4+vV3takWtsRdxGLCuBxipa6WpX0SXFd6c9gMJYDCNrO7Yr63v2qNWW2KWa2DWTG/XnbNyixGRm/gGc3rB/ujvi3mTth2utfdWg/jWeK/LWwJbiRnQgjCeeyLlMhI1oGMSMqUnwhCmdsqEqvgYTfdsr/hjCvEE+WziDnZlEUxiWVcK0pSmvhcMKJUmj3BUMgkIwkXPuMxSSNZMiaISpKhURLFrhOT2RPK6dAfFS7CiVS1syXFzlcSEcZU9phxolQilvgijtEG1IHihMo44AIfTiGnNHtMoIQSlu7aThlXhKdZzIiQqR+5yWT/AsiLSJIkwaQkVA3TSwROj2MQD8ddUkD2iHLjQ+MqYru5ZJzjNd7aULVzJaOtTzzfFv+deyHeu3C5vYn/wcK9Km9hb/91btzvamXmFl87aMz7Dr9WL/VaG7sPd5i0Bbmq6nrS1E1HypWGV2OgRD4obW7u8Ys263Rx3TaVsb03+vb9/g8=](url)

**Comment by lehni** [comment]
Importing the 2nd SVG returns a group in which the children have different fill colors, hence `group.fillColor` returns undefined:

[Sketch](http://sketch.paperjs.org/#S/zZTbbpwwEIZfxeUmqQQ+YnPISc0mykYibaSkqapSVeziAl0HELCHpOq7d0x2qyTKA/QC2TPzzczvAfzbqbN77cTOzUIP89JxnXmTW3uVdShDR6jtml96PuDqvm264ebuYn/v8GRzb9BKd33V1EepwzBNHaRryKzqAhxV33hhKCOPpc7JMTp853noQte6y4ami9GHvJlpdGnMsh9GF2IKU0xdBOXR+cY2QtdmWXiXNcKj8+6pWYwApOh0WZkc0ffI82z1s0+T26/X56hfFej682lyOUGp4xHyRUwIObs9GyswzAg5/whCU6cchjYmZL1e47XATVeQiy5ry2reE0CJRSGNQD3GcD7kqQNtbPXnZ4azoSqH7SRrsx/WgqnU/dFb5Tml1JbbQfHGVPXiTZRFUUTGsIUBoe0Gdg//dusqH0qwfBZgxuXoK3VVlMMr56rS69NmLIEo2kZ2K8T74cFoiOo6mxntzbL5ouiaZZ3HtV6jN3IOnuTHfZvNbWLb6V53Kz2Op4CnzYYS2ZFcCSEw54ErIix9aTzp44gpNxSYMmsqHCjvyZpu2Ud0xRXgoXKZz2zalPkBDmRgFMURDV0uGFYqSl5hkMgkwyEXLuMBjnxZMiawCsOxUegHthOTySvK5oE+KqyHY6mMlSXFTlfoY8ZU8pKxSZEELHRFEIAMZDzFMZWBxwV8nEJOafKSgBSKWbRrO2VcYR4lAcNCRq5vJ5M8B4AXvsRhCEGJqRqnFwqYHgcnHI7boEDJC8qOD4Qrn+3mknAOa7CVoYxVJf2tTjjfFn9MHQLvjhTbl/gfbOyvcoz23h+kcKfUfWM0Nk2xn+GflTGTxjSdDcFdNet0tmibqh56J/72/c9f)

If you assign a color to the whole group first, then it it should work as expected:

[Sketch](http://sketch.paperjs.org/#S/zVR/b5RAEP0qI/+0jbDsD3aB09PYa22boDbxV4wYQ48VsNuFAHfXavzuztI70zb9AJIQdmbee/N2gP3t2eJKezPv/aUel7Xne8u2dPG66KGAOXR9+1MvR9JcdW0/vv90sr/3/OX1lYG17oemtfPcY4TmHmiLzMZWmGiGNkgSmQYs916+gOdPggBOtNV9Mbb9DF6V7YWGM2NWwzilgClCCfUB5eH42jWCc7OqgjMLZEp+um02AwRSOFw1pgR6AEHg1I/eLT58OT+GYV3B+cfD7GwBuReE4WexCMOjD0eTAiMsDI/fotHcq8exm4XhZrMhG0HavgpP+qKrm+UQIjR0UKSFqMcYKccy97CNU7+7Z9wbNCUuF0VXfHcRTsUO88fkOaXUye1As2vT2MtHoSxN03AqOzBCaHeNq5t/q01TjjVGEYsJ43LK1bqp6vFBct3ozWE7SQCFbWX3xPow3hiNVW2LC6ODi2J5WfXtypYzqzfwCOfZrf3Z0BVLR+x6Peh+rafxVHh3xViDG8kbIQThPPZFSmQkTSAjkjLlJ4JQ5kJFYhXcRqdb7C94wxXCE+WziDnaKYtiEsvYKEpSmvhcMKJUmj2AIZFJRhIufMZjkkayZkwQlSRToySKXScmswcox0N/VLgMJ1IZZ0uKna8kIoyp7D7GkVKJsMQXcYw2wASKEyrjgAv8OIU8pdl9BFIoYemu7SnjivA0ixkRMvUjN5nsLgDxIpIkSbAoCVXT9BKB0+OYxM1xVxSQ3UO58aFxFbHdXDLO8RlvbSjjXMlo6xP3t4X/yr0Q311YbV/if7Bwv8oL2Dt4ltuC/GiMWbQGT4k57PW63MNsbn+s7HLEXxFa+7rHE2xfr7UdD+B3bgGvZWuH1mhi2mr/joRTzMc7CVKvNDydAyX4dds/ePxd9Lq47NrGjoM3+/rtz18=)

But it still doesn't after the first call! I have to investigate why...

**Comment by s-light** [comment]
related: [animatePaper.js#11 Why is it not possible to animate Group fillColor?](https://github.com/Eartz/animatePaper.js/issues/11)
my fix to this was to generate a object with the color information in it and set this to the color.
so the internal 'parser' is triggered and i had not to write to the sub-parts.
more details at: https://github.com/s-light/animatePaper.js/blob/f95461f064f25f42ed198d3df356a72e835245e6/src/prophooks.js#L405
in this way i think its slow but works ;-)
