### ISSUE TITLE
Wrong SVG path data parsing

### ISSUE THREAD

**Issue by lyssdod** [paperjs/paper.js#1154]
Hi,

I have an issue with parsing path data from SVG. 
[example sketch](http://sketch.paperjs.org/#S/TVhNb902EPwrwrukBQKBpMgllSKn9hgDFXpz24OTGkjh1A4coz0U/e+dmV3K7xKM50nL5e7sh/Lv5fHur/vLu8svD/cvnz5f3l4+Pf3Bv/++e16+3r18/unu5W55v7y5qduaxpL72stx4r0stax7XfJYM/iy1kQ8xlLzarbkXXxecyLe8HxaU3V8bPs6SvAbLDufjs3WYY4X4G3QJs4lln3D842nwIc2DuCGd40WgPNwfGx17Tb5jd7i+QH721qNdip4+D/kJ/iyduHNyGdhg/2MU5YCZ/JaKsABN/innKn6k57Aq7TWwhObgcS7S24811/M8CfRGr3aGB+cMsAjbu0ID/UkbpEC83Z7mrzxFOCBaPQ1m941Rq/I5hjkmQXEJCmqikACP9YkjLsAm/DemQW+23VrZCQ5Pq4ws7xV4avs49ZXqrgJn3FHZcQxYogsWKVvPTMj7mdRRiywIp8mX6SWiuxE5HEXZsox/E+T74wMnq/FMe3YFb+7b3X6MxUy/by9qTwGuaTscBlcVZgXHsJJss6SI64RmBKcfGcBhPQR0EGeQW9MFWySh1uwXxmswYwD8hA8R7aiXJjFCs86YO4HIOWhSjL6q9RWpX+yNC8Lgo1RA8RxjTIDRKhNdo1xNfls9JlVwNOovbTmyuOaNIZ/4dBQ/Es53E9cq5TwGdctafKs7iXe9Upvs5oKT91Vuft+1B4YQa0jqm/A9aGzJk/97x8I1AqSHnCMaMBISjMnOPTM1WsOb2+aKxuKGUebKkdagV3BqR6tq7+oHoBz9Z51NNxTN4GvranvEB/NVev8Fj0CFQXcvDcl8ptUWAv5rH7EtJSowAa+zO4APqsq/PkUfY32U/Qd9KOKylTfQRRMfQchMLUeBzCVJylMvhfqjcnzlpojuFm4dMa0KfEolapmLXxcYSVDuLsbep7C3SkF2MlGnoWkIFzhyXc2d1wnmWNec9jkC/OHNG2VYdklOASqbdEocVngIZsIDlKQAzMd2xXfhId4ppvCJd8b7Zed/KhTBk3jBwMG5zYy8AfjBKnP1UcaZUD7gyQDNSiYYBwYe1PgRgUDp41HW+brXf2uymxXf0dvOrHze40+TgUOYjgGzLDkUGm/4udsoKr9eYS9aYaxb9pUu4fxtQpub3qRrDW6TwxzwMlidPesOEoBPYXEySflWyPa9uiDGAI265L867g+bDYA5Ma8MWh0A9cSo9tazG2rUZ+Ii81Og25t6nDBb0qY5raVqDfc2UrsFCgAyxKQ5jawdyYI2ihfVguAOvvR1JnAOPDpHVgDHNhXCQzw5gNQA9wt+AAHpnsaXzzaYoCHqxrUuE7UW+Xd5zBnTGwmHnFDefsAN19z1OXNh7yix9iOGODWY7VBEMzFoQGOXGwjBrWNWHMwwK/wgvxWiwF+agCButLGTfisAX5inIh7+cKCAQ7sfhaloAdmCrxWyWdpRgPcU+ADPLAGeGANajzfagxw2jl5T7EGePgzpTL9hLi9+Ut8fePPwrwYAlcGByQwsz4YbgSCHRRFXyn6IgxzgY39+MRJPKXDDVNFAvuVKQfG5QtbC/kRWAGtfB5OA7NtG8PXNQeA0WDop/zhKG4sQuGjW/hJnuNavomnfaO1Lm9hH0Hv6kA4t4gn3thQAxemBDhR8VxA3A5qA/IiVmGXQd7rinGzWHAYzyZxO9+C32G/qhh2voW7eMGjnv2+wTv25lLmrBO/uwgy45B9Uaq0g1+RVLfvzR5ROvF28oUZj3eJab+NybsQcaIxLyl592VTM98w1dSSMDLCpqZz2dS8EVTq5BWnVz6X+TxubeR9+GTZbzqLOknii+JcNCUyG0f34lF5dN8psvxp8s15x4Vb2YmbdJLlM/YIvNtUAIyzNsfMFkO+zC+OwCZ/HA+JjYCWT6Z1tddG0udzV7p34VY/9K4ewX5EaflxlITvGk1SGap5570fQUiDfPV5K77NFakPvau3gL19Y+j1Pdo6S0yY0rXgIWmW5OCvhZ8etIM5VNR3uvaa0lQyQ2XrJaxFFKU0atwxWsRr67i9GSOWeTS/wNpNh6oXDmGfHM23L1bUqBxovowOzt/JZ32BeF3tqjeFIDBr4Dgxn0+xhNBOUiCcL5qN2FHz4WflfRn+cbsfQ98EZBww4pPsdGC0yAF66mjzw09uey7RFoeXXGNDwXG+v/H5rOMk1sCcUZNXExz+vZOZA+K5qMA+Q5c4P4E5fxIXbw+d8DF8cXK+R3mgDE4MhY0e8xO5x712iz2W6fAPYPFbmnyTLuHbxnPNbSbdNzDv6x855Lco13zyahNj7pbN4+Yxkf2ukoN2I86VzLC5x2b6nxVbJBfYVxs+P6XFtL7K7PbND789zv9nWd4vj/f/LD8Dfjf/3+V7/P7bI/9av708Pz3c//j05emZ/xvz8cvdp4c3+vny9vLx+f7u4evTn48v3y7vfv39v/8B)

this is the same path in svg: https://jsfiddle.net/2uw8mmsx/

**Comment by SebastianStehle** [comment]
Just use a CompoundPath.

**Comment by iconexperience** [comment]
Or use a more generic approach with `PathItem.create()`.

<a href="http://sketch.paperjs.org/#S/TVhNb902EPwrwrukBQKBpMgllSKn9lIgBir05qaHF9dACid24Bi9FP3vnZldPr9LMh5Ly+Xu7If87+nx/PX+9O70+8P9y93n09vT3dNf/Pmf8/Py7fzy+Zfzy3l5v7y5qduaxpL72stxwXtZaln3uuSxZvBlrYl4jKXm1WzJu/i85kS84fm0pur42PZ1lOA3WHY+HZutwxwvwNugTZxLLPuG5xtPgQ9tHMAN7xotAOfh+Njq2m3yG73F8wP2t7Ua7VTw8H/IT/Bl7cKbkc/CBvsZpywFzuS1VIADbvBHOVP1Iz2BV2mthSc2A4l3l9x4rr+Y4U+iNXq1MT44ZYBH3NoRHupJ3CIF5u32NHnjKcAD0ehrNr1rjF6RzTHIMwuISVJUFYEEfqxJGHcBNuG9Mwt8t+vWyEhyfFxhZnmrwlfZx62vVHETPuOOyohjxBBZsErfemZG3M+ijFhgRT5NvkgtFdmJyOMuzJRj+J8m3xkZPF+LY9qxK3533+r0Zypk+nl7U3kMcknZ4TK4qjAvPISTZJ0lR1wjMCU4+c4CCOkjoIM8g96YKtgkD7dgvzJYgxkH5CF4jmxFuTCLFZ51wNwPQMpDlWT0V6mtSv9kaV4WBBujBojjGmUGiFCb7BrjavLZ6DOrgKdRe2nNlcc1aQz/wqGh+JdyuJ+4VinhM65b0uRZ3Uu865XeZjUVnrqrcvf9qD0wglpHVN+A60NnTZ763z8QqBUkPeAY0YCRlGZOcOglV685vL1prmwoZhxtqhxpBXYFp3q0rv6iegDO1XvW0XBP3QS+tqa+Q3w0V63zW/QIVBRw896UyG9SYS3ks/oR01KiAhv4MrsD+Kyq8OdT9DXaT9F30I8qKlN9B1Ew9R2EwNR6HMBUnqQw+V6oNybPW2qO4Gbh0hnTpsSjVKqatfBxhZUM4e5u6HkKd6cUYCcbeRaSgnCFJ9/Z3HGdZI55zWGTL8wf0rRVhmWX4BCotkWjxGWBh2wiOEhBDsx0bFd8Ex7imW4Kl3xvtF928qNOGTSNHwwYnNvIwB+ME6Q+Vx9plAHtD5IM1KBggnFg7E2BGxUMnDYebZmvd/W7KrNd/R296YKd32v0cSpwEMMxYIYlh0r7FT9nA1XtzyPsTTOMfdOm2j2Mr1Vwe9OLZK3RfcEwB5wsRnfPiqMU0FNInHxSvjWibY8+iCFgsy7Jv47rw2YDQG7MG4NGN3AtMbqtxdy2GvWJuNjsNOjWpg4X/KaEaW5biXrDna3EToECsCwBaW4De2eCoI3yZbUAqLMfTZ0JjAOf3oE1wIF9lcAAbz4ANcDdgg9wYLqn8cWjLQZ4uKpBjetEvVXefQ5zxsRm4hE3lLcPcPM1R13efMgreoztiAFuPVYbBMFcHBrgyMU2YlDbiDUHA/wKL8hvtRjgFw0gUFfauAmfNcAvGCfiXr6wYIADu59FKeiBmQKvVfJZmtEA9xT4AA+sAR5YgxrPtxoDnHYuvKdYAzz8mVKZfkLc3vwlvr7x18K8GAJXBgckMLM+GG4Egh0URV8p+iIMc4GN/fiCk3hKhxumigT2K1MOjMsXthbyI7ACWvk8nAZm2zaGr2sOAKPB0E/5w1HcWITCR7fwkzzHtXwTT/tGa13ewj6C3tWBcG4RT7yxoQYuTAlwouK5gLgd1AbkRazCLoO81xXjZrHgMJ5N4na+Bb/DflUx7HwLd/GCRz37fYN37M2lzFknfncRZMYh+6JUaQe/RVLdvjd7ROmCtwtfmPF4l5j225i8CxEnGvOSkndfNjXzDVNNLQkjI2xqOpdNzRtBpU5ecXrlc5nP49ZG3odPlv2ms6iTJL4ozkVTIrNxdC8elUf3nSLLnybfnHdcuJVdcJNOsnzGHoF3mwqAcdbmmNliyJf5xRHY5I/jIbER0PKFaV3ttZH0+dyV7l241Q+9q0ewH1Fafhwl4btGk1SGat5570cQ0iBffd6Kb3NF6kPv6i1gb98Yen2Pts4SE6Z0LXhImiU5+NvCTw/awRwq6jtde01pKpmhsvUS1iKKUho17hgt4rV13N6MEcs8ml9g7aZD1QuHsE+O5tsXK2pUDjRfRgfn7+SzvkC8rnbVm0IQmDVwXDCfT7GE0E5SIJwvmo3YUfPhZ+V9Gf5xux9D3wRkHDDik+x0YLTIAXrqaPPDT257LtEWh5dcY0PBcb6/8fms4yTWwJxRk1cTHP69k5kD4rmowD5Dlzg/gTl/EhdvD53wMXxxcr5HeaAMLhgKGz3mJ3KPe+0WeyzT4R/A4rc0+SZdwreN55rbTLpvYN7XP3LIb1Gu+cKrTYy5WzaPm8dE9rtKDtqNOFcyw+Yem+l/VmyRXGBfbfj8lBbT+iqz2zc/fXycf2dZ3i+/4b9fX+6/rnfP9+eX+x/mn19+xGMfH/nT+v3l+enh/uenL0/P/KPMpy/nu4c3+vXp7ekTXnv49vT348v307s//vzvfw==">Here is the sketch</a>

In any case, this is not a bug in Paper.js

**Comment by lyssdod** [comment]
Thank you guys!
