### ISSUE TITLE
How to split a curve into parts of equal length? 

### ISSUE THREAD

**Issue by SkidX** [paperjs/paper.js#1159]
Hi, 
I need to split a curve into several parts of almost equal length (more than 2). 
divideAtTime() method is not suitable for this (if you try to use it for straight lines or curves that are close to a straight line you get curve parts that are pretty far from the percentage of the length, for example if you have a line with a length of 100 and you call divideAtTime(0.25) you get a new curve with a length of 15.625, while I would need a curve with a length of approximately 25), so I'm wondering if there is another built-in method to achieve this or if you know an easy way to approximate this result. 

Thanks in advance

**Comment by lehni** [comment]
Look at [`curve.divideAt(offset)`](http://paperjs.org/reference/curve/#divideat-location), and [`curve.length`](http://paperjs.org/reference/curve/#length). Please note that this is a bug database, not a support forum. Support requests should be posted here: http://groups.google.com/group/paperjs
