### ISSUE TITLE
Canvas animation lag retina screen

### ISSUE THREAD

**Issue by maximeberthelot** [paperjs/paper.js#1162]
Hey,

Im working on animation on scroll with paper.js and in my retina screen is very laggy.

For example, when i just move an rectangle(or svg path it's same, and without scroll animation) in my canvas, is very laggy.

Very strange behavior, when i move my mouse during the animation, it's more smooth. Maybe is something with mouse event ? Can i just remove all the mouse events from papers.js ? Someone have an idea ?

Thanks for your time,

Maxime

**Comment by jingman** [comment]
Can you post an example so we can reproduce it?

**Comment by maximeberthelot** [comment]
I try something for this issue, but my main issue it's with multiple canvas, i try to animate multiple canvas in the same times but it's laggy, there is an bounce/jump on the different shape.

**Comment by sapics** [comment]
It looks similar to #1145 .
Is it also slow [the sketch](http://sketch.paperjs.org/#S/pVRRT8IwEP4rzRKTDWaBGX0AedLoi4kmvGgGD3U7WIO0ZC0DNPx3rx0rGxKJsQ9bd/fdd9/1rvvyBFuA1/dGc9BJ5oVeIlPzXbCcpFxpJhIgQxJ1w7EguBK5Evp5+sQFKLRfRc7+IfNHtkRbr1MH7f1rVsAL09mdwSEo7oakF5Lu5MhvSOPJYCzGYopA3+jgaOsO8HU7bORHU7sdkK+SwSArFgwQsCZm6weDZgaqdC7nUAkxOLv3GxJjVNYUHffQwknLlfqDmKWpb9NKLrSPBRYc1tQ8RvwTaAZ8lmnSor1r0rZM1QEHZ6iaPGue6qwTnabvRP/nPs3cojdndSu6XKnMnaRx70wrXW9MyntQmgumuRR4/tZEcyZSufADJLe5FebF4OlKJBYnxUOOg+pDAUK7lvNpaaB2KsgFicgQR8X5q7FYSsX36ZxSbDBVMFtguMLW0qXRMWjGFZBoOyQntV863qOwJGNiBq8YVxLQDemQq+oGVatEvR1QW4uqcf3xAtQl1C7CoWI+OZJglq27Bvv1UFwAorRf7jY4FPuKw71z60xvwVH0Ic1CytrtNGtXbnd2aPBX9J4Dm1tG5fXjye4b) in your retina pc?
In my Windows10 note book pc, it looks enough fast.

**Comment by maximeberthelot** [comment]
That's work fine, my problem it's because i want to animate multiple canvas and it's to laggy in each on their canvas. But when i animate only 1 o 2 canvas in same time, that's work fine.
