### ISSUE TITLE
raster.onLoad event is not firing on PhantomJS

### ISSUE THREAD

**Issue by kdekooter** [paperjs/paper.js#1163]
Not sure if this is the proper place to submit this issue. But kind of at a loss of where to start.

Could this be related to #924?

**Comment by lehni** [comment]
What version of the library is this happening with? Could you share a test-case for replication?

**Comment by kdekooter** [comment]
The version number is 0.10.2. The code looks like this:

```
<html>
<head>

  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/paper.js/0.10.2/paper-core.js"></script>
  <script>

    paper.install(window);

    var raster = new Raster({
        source: 'https://en.wikipedia.org/static/images/project-logos/enwiki.png',
        position: [400, 400]
    });

    raster.onLoad = function () {
      console.log('FINISHED');
    }
  </script>

</head>
<body style="margin: 10px">

  <canvas id="canvas" height="900" width="800"></canvas>

</body>
</html>
```

**Comment by sapics** [comment]
From [the sketch](http://sketch.paperjs.org/#S/NU+xbgIxDP0VK8sd0jVhYErVraAiVR3KCAxpzhzpgR3FoQzo/p2ktB6e9eTn5+ebIndGZdVmxOyPqlOe+8p/XILkJGOCFyC8wucvaW+7tCMoJXxJHi00x5yjWGOQ9DWMIWIfnOY0GMkuB2/C2Q0oJib+Rp+fTjywFHHV6khD0/07RpaQA5OF7WI+76DAvs6m2XNtjzSa6Z1dX0IdLuSrHNoZ/KXyTMIn1OVG26zWH+vN2/K1eaxPFcp/XwndGDlQFmW3++kO), it looks working.

**Comment by kdekooter** [comment]
Sure, it works in FF and Chrome. But not in PhantomJS. The word "FINISHED" never appears in the console.

**Comment by sapics** [comment]
Could you try this?
```html
<html>
<head>
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/paper.js/0.10.2/paper-core.js"></script>
  <script>
    paper.install(window);
    window.onload = function() {
      paper.setup('canvas');
      var raster = new Raster({
        source: 'https://en.wikipedia.org/static/images/project-logos/enwiki.png',
        position: [400, 400]
      });
      raster.onLoad = function () {
        console.log('FINISHED');
      }
    }
  </script>
</head>
<body style="margin: 10px">
  <canvas id="canvas" height="900" width="800"></canvas>
</body>
</html>
```

**Comment by kdekooter** [comment]
I am sorry, my snippet was incomplete. I wrapped the code in a jQuery document.ready statement (`$(function () {`.

With `window.onload` is is working!
