### ISSUE TITLE
TypeError: Cannot read property '_currentStyle ' of null

### ISSUE THREAD

**Issue by supernlogn** [paperjs/paper.js#1164]
First i will list out my file structure:
I have one file minBug.js which has only a class definition as in the link below:
[minBug2 class definition](https://drive.google.com/file/d/0BxzY0txWsh_MMEdubFViR0RvYm8/view?usp=sharing)

and i have anothern one with name test.js
with only one line:
`var min2 = new minBug2();`

the index.html file looks like [this](https://drive.google.com/file/d/0BxzY0txWsh_MVjJrNlVhSXlMNjQ/view?usp=sharing)

when I launch my index.html using chrome open file,
I get the error:
`TypeError: Cannot read property '_currentStyle ' of null`
but if afterwards I write 
`var min2 = new minBug2();`
in the chrome's console all are working perfectly 
and `min2.background` is created.

Why is that happening? 
What can I do in order to call minBug2 class construtor from test.js ?

**Comment by jo-fe** [comment]
Might it be because

` window.onload = function() {
            paper.setup('myCanvas');
        }`

fires after minBug.js was loaded?

**Comment by supernlogn** [comment]
Thanks! 
Just for reference here is what i did:
I created a function
with line:
`var min2 = new minBug2();`
in it and i called it from window.onload function.
and all were ok!
