### ISSUE TITLE
Intersection between touching curves not found

### ISSUE THREAD

**Issue by iconexperience** [paperjs/paper.js#1165]
For the following special case of curves the touching point is not found:
![image](https://cloud.githubusercontent.com/assets/2122773/18579840/5dcd54ba-7bf8-11e6-8ceb-dfc85969a263.png)

```
var c1 = new Curve([163.04000000000002, 335.67999999999995, 163.04000000000002, 357.68330000000003, 145.2033, 375.52, 123.2, 375.52]);
var c2 = new Curve([300, 335.67999999999995, 184.90805, 335.67999999999995, 171.89195, 335.67999999999995, 56.80000000000001, 335.67999999999995]);
```
<a href="http://sketch.paperjs.org/#S/fZHLbsMgEEV/BbGyJQvxMH5FWWXVXaUubS9cMnIiO2ABTRdR/r00jetUijsr7szVnQNcsO5OgCv8NoBXB5xgZfbf+txZpBjaIg2faPdhzxDVLBOEpnQpniAhJMnycimZoKc+mZOsEOK3J4IvlYRTEU4il0QGF+OC8Fm28abRNw7+lyOErCwuUlLSgsqVcc5IUbJyZSwzUjxAU/bMdoP6wZrm53nt/CG6OOhPoL2rUK0YuauQsQjeJsh5awbYmdHYCjXYwr7B1/miE19N5I+J/J/E3gLoe2ajldHOjEBG00cBpAf/oj1YB8ofwyhSPI434dffLXTDZI5hG67q9voF">Here is the Sketch</a>

Note that `c2` is a **quasi-straight** curve, which means that it is straight, but we do not treat it as a line, because the handles are not at the end points.

**Comment by iconexperience** [comment]
The reason why this fails is that in our Bezier clipping in `addCurveIntersections()` both curves are reduced to a single point. Our code does not handle this correctly at the moment, but it should be easy to fix this.

**Comment by iconexperience** [comment]
If a curve has been reduced to a point, two things happen:

1. `getSignedDistance()` calculates the distance to the line through the end poins as if the curve was a vertical line
2.  in in <a href="https://github.com/paperjs/paper.js/blob/develop/src/path/Curve.js#L1667">Curve.js line 1667</a> a break condition is triggered in this case, because the end points of the curve are identical and both points are on the line that runs through the other curve's end points. Therefore all distances are zero.

I tried removing the break condition in line 1667 and while this works for this special case, it slows down things considerable. 

A better solution may be to adjust the line that runs through curve 2 if curve 2 is a point. In this case we could simply adjust the line so it runs through curve 2's end points, but orthogonal to the line through curve 1's end points.

<a href="https://github.com/paperjs/paper.js/blob/develop/src/path/Curve.js#L1644">Curve.js lines 1644/1645</a> have to be replaced by this:
```
     var q0x = v2[0], q0y = v2[1], q3x = v2[6], q3y = v2[7];
     // if the base line is a point, make it orthogonal to the line through curve 1's end points 
     if (q0x == q3x && q0y == q3y) {
        q3x += v1[7] - v1[1];
        q3y += v1[0] - v1[6];
     }
     var getSignedDistance = Line.getSignedDistance,
```

That's all.

**Comment by lehni** [comment]
@iconexperience I don't need to make any change on my local `develop` branch and already find this solution:

    [ { point: { x: 163.04, y: 335.68 }, index: 0, time: 0 } ]

Have you tried the latest state of things at your end?

**Comment by lehni** [comment]
@iconexperience the commit where this starts working is 58991a569ec8c29fd97d169e7e3ff3e0cb588caa, which is work done by you. Are you not running your code with that change?

**Comment by iconexperience** [comment]
@lehni Sorry for that. I have some experimental code in my own version and did not expect that to make any difference for this example. Should have tested properly.

Anyway, maybe we can add this to the unit tests.

**Comment by lehni** [comment]
@iconexperience no worries. Yes we should. Do you think your proposed fix is still required, or does the current code handle this reliably across different scenarios?
