### ISSUE TITLE
Cannot read property 'isStraight' of null if path has only one segment

### ISSUE THREAD

**Issue by iconexperience** [paperjs/paper.js#1167]
The following example throws a *Cannot read property 'isStraight' of null* error in `resolveCrossings()` at <a href="https://github.com/paperjs/paper.js/blob/develop/src/path/PathItem.Boolean.js#L1024">PathItem.Boolean.js line 1024</a>.

```javascript
var p = new paper.CompoundPath({fullySelected:true});
p.addChild(new paper.Path({segments:[[228.26666666666668, 222.72, -3.055000000000007, 0, 0, 0], [283.73333333333335, 222.72, 0, 0, 3.05499999999995, 0], [289.28, 228.26666666666668, 0, -3.055000000000007, 0, 0], [289.28, 283.73333333333335, 0, 0, 0, 3.05499999999995], [283.73333333333335, 289.28, 3.05499999999995, 0, 0, 0], [228.26666666666668, 289.28, 0, 0, -3.055000000000007, 0], [222.72, 283.73333333333335, 0, 3.05499999999995, 0, 0], [222.72, 228.26666666666668, 0, 0, 0, -3.055000000000007]], closed:true}));
p.addChild(new paper.Path({segments:[[283.73333399705655, 289.2799999999998, 2.212409526691772e-7, 0, -2.212411231994338e-7, 1.1368683772161603e-13]], closed:true}));
p.resolveCrossings()
```
<a href="http://sketch.paperjs.org/#S/lZPRboIwFIZfpeFKE2jaU0spy658gSVeMi8YnKkRKaHoshjffWgdaEYvdsJN0379P07bc1DnBwzSYLXHrtgGYVCY8jo+5S1pyCup8Ys0eYMtXZpDY451+ZZ329n581hV3yussOiwTLv2iJf5y3vd0Lwsl9tdVc5G0hEWNwesO5tmGUBCIX6oJCQAQBWEJBKUScnGUiFh7luHJINEUCUeSo6oW3blF3ooOYCawi3nbzbzxz6hE9nMF+uVvW82ofmQONWgO8j8vg51zfDITsc+gdMN8sWue7aojB1uwT+uwaCotWIylr/tUaPg9ccpcFgwLXsrzZUCjNzhRG6GcxBc64UQyW2GUy7iJE5Ev5THPGYCIy48ni1aU51w2Rprd/XGzub9G/hoMd83ZtdrBmm2vvwA">Here is the Sketch</a>

**Comment by iconexperience** [comment]
The reason for the error is that the second child path has only one segment. Therefore in `resolveCrossings()` the variables `next` and `seg` are identical for this path. Since `seg` has been removed already from the path, `next` has no curve anymore when being inspected.

The issue can be solved easily be checking if `seg` and `next` are identical.  <a href="https://github.com/paperjs/paper.js/blob/develop/src/path/PathItem.Boolean.js#L1024">Lines 1022 to 1029 in PathItem.Boolean.js</a> have to be replaced by this:

```
if (seg !== next) {
    prev._handleOut._set(0, 0);
    next._handleIn._set(0, 0);
    var curve = prev.getCurve();
    if (curve.isStraight() && curve.getLength() === 0) {
        // Transfer handleIn when removing segment:
        next._handleIn.set(prev._handleIn);
        prev.remove();
    }
}
```

**Comment by lehni** [comment]
Thanks @iconexperience. Fix coming up in 5s.
