### ISSUE TITLE
divideLocations() distorts path

### ISSUE THREAD

**Issue by iconexperience** [paperjs/paper.js#1169]
In this example calling `resolveCrossings()` distorts the path, which consequently leads to a faulty boolean operation.

```
 var p1 = new paper.Path({segments:[[153.59999999999997, 305.44, 0, 0, 0, 0], [141.59999999999997, 317.44, 0, 0, 0, 0], [141.59999999999997, 286.72, 0, 0, 0, 0], [153.59999999999997, 298.72, 0, 0, 0, 0], [143.36, 298.72, 0, 0, -3.182597878074528, 7.732783925589109e-15], [134.87471862576143, 295.2052813742386, 2.2504365413764127, 2.250436541376419, -2.2504365413764127, -2.250436541376419],[131.36, 200, 0, 0, 0, 0],   [407.8452813742386, 387.3652813742386, 2.250436541376419, -2.2504365413764194, -2.250436541376419, 2.2504365413764194],  [92.15999999999998, 390.88, 0, 0, -3.1825978780745263, 3.96383092040348e-15],  [102.39999999999998, 315.68, -12.259416997969552, 0, 0, 0], [143.35999999999999, 315.68, 0, 0, 0, 0], [131.35999999999999, 327.68, 0, 0, 0, 0], [131.35999999999999, 317.44, 0, 0, -1.9487791521785632e-16, -3.182597878074526], [134.87471862576143, 308.9547186257614, -2.2504365413764167, 2.2504365413764114, 2.2504365413764167, -2.2504365413764114], [143.35999999999999, 305.44, -3.182597878074526, -8.439462614061388e-15, 0, 0]], closed:true})
 p1.fullySelected = true;
 p1.resolveCrossings();
```
<a href="http://sketch.paperjs.org/#S/jVTbbtswDP0VwU8t4AjiRRKZYk/7gQF99PKQJVpb1LUD2+0wFP33yW2wJbYz1DBgmDokDw8pvhbN9ikV6+L2MQ27+6Isdu1+/Dcv284cwHwxTfplDttD6uy37XB/9dqnu6fUDP26qsCT9XryxNKQ85a5NO7vuylNBQxzJMRPIlGCjThDLmRHlSUkk6UwPV2RBUGvUaK4yB6lNNFGwiik6L0oOE0r8O8hiK1EjiABfQw54hjOW3TZDygykowZLHrHFDxnW2DAOLdpTr2Emxl1U+a88EHduUlVxlTsohU+I0ASM/6/nJbyKy8ZF3x5zFwpWjiVPitH6qzIRW1D1ousBhJyio4dsRy1zeI6tKSTeOBtyN8VjByUIeQGa1Dvcd7bszH45zuZglHKKRLjZ5Fn07oCqywxKniEKD4Q5mrCUuGXpoecWPUntoUOhIXxGYFLuJkz8EV9jnd0TjbbxDIpB8yMXACS9zYdtckBd3Xbp/166J7T2/X3Ju8I+/O5rn/fpjrthrTPG2M8u/k46lLf1i/pa9f2/UNz119d3+Qd86NL28dD+5C3SLGuNm9/AA==">Here is the Sketch</a>

Intially the path looks like this (zoomed in on the interesting part):
![image](https://cloud.githubusercontent.com/assets/2122773/18704616/f4660b4c-7fea-11e6-95cd-564ad8c63ccf.png)

And this is the result after calling `resolveCrossing()`:
![image](https://cloud.githubusercontent.com/assets/2122773/18704648/10812cee-7feb-11e6-9e3b-b7cb9b2ef6f7.png)

**Comment by iconexperience** [comment]
I have no solution yet for this issue, but as I see it the problem occurs in `divideLocations()`. This seems to cause trouble with multiple locations on the same curve. Below I have marked the curve that have multiple intersections:

![image](https://cloud.githubusercontent.com/assets/2122773/18704855/fa1b97d6-7feb-11e6-8c58-8d50065ddb6d.png)

I think this is what happens: Whenever a curve is split, the curve itself becomes the first part and a new curve is created as the second part. If a location X has been processed and the curve has been assigned, it will keep a reference to the curve if the curve will be split again for another location Y, although the new created curve should be assigned to location Y. Things may be even a bit more complicated, but I think this is roughly what's happening.

**Comment by iconexperience** [comment]
If I disable the time adjustment (`time /= prevTime;`) in `divideLocations()` the result is correct. But this causes a bunch of new issues elswhere. Mysterious!

**Comment by iconexperience** [comment]
I noticed that the locations' `time` attribute get updated autmatically (for example if `loc.getCurve()` gets called). If this happen and we then adjust the `time` attribute maually through `time /= prevTime`, the resulting `time` is wrong.

The question is: When do the `time` attributes get updated automatically and when do we have to adjust them manually.

**Comment by lehni** [comment]
The cached `time` value only gets erased when `path.version` has changed in the meantime. `divideLocations()` is written in a way that should never trigger a version change, hence the the internal scaling. Strange...

**Comment by lehni** [comment]
Oh wait, that's not right... It used to be like this. Hmm.

**Comment by lehni** [comment]
What probably happens here is this: 

- Due to a `path.version` change, `loc.time` gets invalidated.
- The next time `loc.curve` is requested, it will be recalculated along with `loc.time`, based on `loc.point` (See `trySegment()` & co).

Now this works well as long as there is no self-intersection. If `loc.point` is on a self-intersecting curve, there are two possibly solutions for `loc.time`, and we're getting the wrong one here.

The trick will be to never trigger recalculation of time during `divideLocations()`...

**Comment by lehni** [comment]
When you look at `resolveCrossings()`, you see that `divideLocations()` can get called twice, once for overlaps and once for crossings. This is probably what triggers the path version change, among other things.

**Comment by iconexperience** [comment]
@lehni I just found that the version change must be triggered when `include(loc)` is called. The `_time` value after that call is different than before.

**Comment by lehni** [comment]
Yes it is, and I know why. I'm, on it... It's just not so simple. The problem really is that we're working with a changing path, and cached locations. So just preserving all loc values and assuming no changes is also producing issues.

**Comment by iconexperience** [comment]
:sunglasses: 
Such a simple fix, thanks a lot. I remember that not so long ago we thought that we would never finish on the boolean operations, but I can tell you that we are extremely close. In my application there is exactly **one** remaining case that fails, which is due do a wrong result in `isCrossing()`. And as you can see from my recent bug reports I am encountering quite some weird cases.

In my opinion these things are left to do:

- Improve `propagateWinding()` to eliminate ambigous cases (not so difficult to do)
- Improve `isCrossing()`. This is still quite unreliable, because on the one hand we do not want to compare angles too close to the intersection point (can casue wrong results in tangential crossings). On the other hand we cannot move too far away from the intersection point, because then we may be behind the next crossing of the curves.
- Fix remaining glitches with `tracePath()`

There may be some more minor optimizations that can be done, but that's about it. :fireworks:
