### ISSUE TITLE
resolveCrossings() on self intersecting path fails.

### ISSUE THREAD

**Issue by iconexperience** [paperjs/paper.js#1170]
In this example `resolveCrossings()` on a self intersecting path results in a wrong path:

``` javascript
var p = new paper.Path({segments:[
        [360, 300, 10, -10, -30, 30],
        [420, 300, 0, 40, 0, -40],
        [360, 300, -30, -30, 10, 10],
        [400, 300, 0, 10, 0, -10],
        ], closed:true});
var res = p.clone().resolveCrossings();
p.fullySelected = true;
res.fillColor = "yellow";
```

![image](https://cloud.githubusercontent.com/assets/2122773/18708016/0afa88ca-7ff9-11e6-9a59-91d45d2de164.png)

(<a href="http://sketch.paperjs.org/#S/lVHBCsIwDP2V0tOEWTY3PEw8+QOCx22HukUdi21pqyLiv5tVRd3N0LyQvpcHaW9cySPwgm968M2Bx7zR7dCfpWWGLZmCCzPSgBVr6Q/RzcH+CMq7oqxspdgrymyexCxLCFLKaYAsXNXxjzCfvYV08meZ5mPVxy64BEhDju2SL7v0ZTdW1TFrUDtoC29PcJ8sBnJY0IKjFY0gVkE0EdRrPMPKauc6tXfRU2rE7oR43QBC46GlkcEnUDQhdh3iSqO2RFT8Coj6UvFAj5N9xZ89fc3WguyN7uj5eVHW9wc=">Here is the sketch</a>, but note that this example this does not fail with the current sketch version.)

**Comment by iconexperience** [comment]
One possible fix for this issue is to not switch segments on crossings if we are at the first segment. This makes sense to me and does not break any of our unit tests.

All that needs to be done is to change <a href="https://github.com/paperjs/paper.js/blob/develop/src/path/PathItem.Boolean.js#L786">PathItem.Boolean.js line 786</a> to this:
```
cross = !first && !finished && other;
```

**Comment by lehni** [comment]
Hmm that may be a workaround for sure, but why does that inner, right segment pass as valid? It shouldn't? This looks bit like a problem of winding to me...

**Comment by iconexperience** [comment]
@lehni This happens in `resolveCrossings()`, so winding is not used here. So if in a boolean operation one of the paths is like the one above, `preparePaths()` will cripple the path and then of course the result will be wrong.

**Comment by lehni** [comment]
Interesting, this doesn't happen anymore with my latest code-base, without your proposed fix in place. That's good news?
