### ISSUE TITLE
getCrossings() returns wrong number of crossing

### ISSUE THREAD

**Issue by iconexperience** [paperjs/paper.js#1174]
In the following example two crossings are returned by `getCrossings()`, while only one should be returned.

![image](https://cloud.githubusercontent.com/assets/2122773/18793352/a32fbc2e-81ba-11e6-97f1-8e6f80ef2e4c.png)

```
var p1 = new paper.Path({segments:[
    [20, 60],
    [20, 100],
    [150, 100]
    ], strokeColor: "red", strokeScaling: false});
var p2 = new paper.Path({segments:[
    [20, 140],
    [20, 100.00000001],
    [150, 98]
    ], strokeColor: "green", strokeScaling: false});
console.log(p1.getCrossings(p2));
```
<a href="http://sketch.paperjs.org/#S/lZHPisIwEIdfZcipQilNcUUjnnyBhR7bHmIdozRmwiSsh+K7b11X6C7inx/MYT5m4BumF04fUShRdhjbvUhFS9tL/6UZvIQVODyB1x45+9Rxn/QBzRFdDKqquXYwpCryFGZ5k/4BMh8T+fGLbqRJIUSmDtdkiRXUgnFbixstW20PzijYaRvwPFle9n6cited5PSOVJZfI//bLeYP5Awjuid6LblAFjNLJvEyMxjXTCEMcyHxxeQ6NC4Y5c1+eNSGUXeeDsPdQlXN+Rs=">Here is the sketch</a>

**Comment by iconexperience** [comment]
Exaggerated the paths look like this:

![image](https://cloud.githubusercontent.com/assets/2122773/18793437/087c7d6a-81bb-11e6-9761-71f2a1b78288.png)

The distance between the corners is less than out `GEOMETRICAL_EPSILON`, so an intersection should be found, but it should not be classified as a crossing. For this intersection in `CurveLocation.isCrossing()` two points right to the actual crossing are used to check if the intersection is a crossing. Therefore it is falsely classified as a crossing.

**Comment by lehni** [comment]
I have a feeling it's wrong to compare the beginnings / end points with `GEOMETRICAL_EPSILON`... I'll do some tests.

**Comment by lehni** [comment]
@iconexperience oh wow! I just lowered the `epsilon` in [`_getIntersections()`](https://github.com/paperjs/paper.js/blob/develop/src/path/Curve.js#L1911) from `GEOMETRICAL_EPSILON` to `EPSILON`, and a whole bunch of magic stuff started happening:

- This issue here is resolved
- Your test case with the bouncing path offset line suddenly produces no glitches at all
- All unit tests still pass

: D

**Comment by lehni** [comment]
Haha, mispronounced "closes" in the commit message, manually closing :D
