### ISSUE TITLE
Unable to use scaling and rotation together without resetting them on every frame

### ISSUE THREAD

**Issue by YoruNoHikage** [paperjs/paper.js#1177]
I'm trying to set scale and rotation for every frame. I've set the `transformContent` (or `applyMatrix`, which one should I use?) to `false` like planned but a weird bug appeared when I set the two properties I needed to change together.

Here's a gif and the sketch showing it, click run and wait for 1 or 2 seconds to see it show:

![Bug](https://cloud.githubusercontent.com/assets/969003/18868797/cd203788-84a9-11e6-86de-9579ca9bbfa9.gif)
[Sketch](http://sketch.paperjs.org/#S/dVA7a8MwEP4rh5bYEBy31EtCp0K3QmnGpsNZucTC8klIqpM25L/3ZNIHgQoE0vc86aQYB1JLte4p6U7NlXbbfB8xgMfUwT0wHeBZjtUL6YS8t1R49BSq0dCh0sSJwnxSrc0nFU09h6Yuy9WGc0C1M9Y+OOuCRM1ai7qffVPovf14whTMUcgd2khCXUjHj0Fmy8Q762QcFzRKWQmnDYOs1JlYBZcwcyK7a7I5TXDUaA3vBb2dwLwXC5AgNwwSImaKBKKhCMlBJMoQ0NHLI2kLLXU4GhcuxuuuevWX+G27+Wm7djT1f9Od5dfbQNh7ZzhFtXx9O38B)

**I managed to circumvent the bug in resetting scale and rotation before reassigning them.** In the sketch, I set scaling and rotation twice to simulate the fact that I have a variable parameter in my drawing loop.

**Comment by lehni** [comment]
What you are seeing is a short-coming of the decision to not store these values separately from the transformation matrix, but extract them from it through matrix decomposition instead... I think we're dealing with tiny errors in floating point math here that are adding up. Previously, I managed to prevent these through caching of the decomposed values, but this was causing issues as well, see:

https://github.com/paperjs/paper.js/issues/1004#issuecomment-225866308

I need to think a bit more about that. There may be a way to bring the caching back and prevent the issue in #1004
