### ISSUE TITLE
Setting opacity to Group with Path.Line has unexpected results

### ISSUE THREAD

**Issue by nadirabid** [paperjs/paper.js#1180]
The following is the code I'm working with (in JavaScript).

Example code w/o opacity set: http://codepen.io/anon/pen/ALVpwO
Example code w/ opacity set: http://codepen.io/anon/pen/rrJWRL

Note: you can click out of the sign in prompt if it appears for you in the links above.

Adjust the zoom of the view does seem to have an effect. This also seems to be specific to Path.Line object. 

Any ideas what could be happening?

**Comment by twobyte** [comment]
var group = new Group();
var line = new Path.Line([20, 20], [400, 80]);
line.strokeColor = 'blue';
line.strokeWidth = 50;
line.opacity = 0.6; // this works!
group.addChild(line);

**Comment by nadirabid** [comment]
@twobyte  Correct. But the reason that I had for applying it on the Group was so that a certain set of Paths, that intersect, have uniform opacity instead of additive opacity.

**Comment by nadirabid** [comment]
Should also note that this problem doesn't seem to exist in version `0.9.18`: http://codepen.io/anon/pen/gwvjjb

**Comment by lehni** [comment]
[Sketch w/o opacity set](http://sketch.paperjs.org/#S/bZFPb8IwDMW/StQLRaqyDm3SBNqJwzQJpEkcdqAcQuu1HqlTJQYGiO++pOVPJ+1mv/ez85KcIlI1RONosQHOqyiJclOE3gEzUumkahp9mCu2+CNexZfSDiYZ3Wz0peV3htr17Ix2yorSmm3jVYK9eAt1fBKmUTnyYSwexXk46TiNBBfsQ3ElZ76Pl6M0EaN0lYjlU+rLl3QV+MBKx9ZsYGq0sX5usNZbGPz1PrHgynvPqdfbHFIVxbRCXcQBG7YhG2u+IWepcsYdzNQB7B1rp64Rdwj7kd93nQj97Z7WK4pKDT2gv3JttlS4Dg97ZA7EEKLfJi/S5Eocjam9Pw/PUSPFGYkuQ3vyAo8gK8CyYvHQW9JJyT/wvn2PPtsqGYUL+l9fW1CbxiCxi8bL1fkX)
[Sketch w/o opacity set](http://sketch.paperjs.org/#S/bZFPb8IwDMW/StQLRaqyCm3TBNqJwzQJpEkcdqAcQuu1HqlTJQYGiO++pOVPJ+1mv/ez85KcIlI1RONosQHOqyiJclOE3gEzUumkahp9mCu2+CNexZfSDiYZ3Wz0peV3htr17Ix2yorSmm3jVYK9eAt1fBKmUTnyYSxS+SzOw0lHaiS4gB+KKznzfbwcpYkYpatELB9TX76kq8AHVjq2ZgNTo431c4O13sLgr/eJBVfee0q93iaRqiimFeoiDtiwjdlY8w05S5Uz7mCmDmDvWDt1jbhD2I/8vutE6G83tV5RVGroAf2Va7OlwnV42CNzIIYQ/TZ5kSZX4mhM7f15eI4aKc5IdBnakxd4BFkBlhWLh96STkr+gffte/TZVskoXND/+9qC2jQGiV00Xq7Ovw==)

**Comment by lehni** [comment]
Actually, this is fixed on the develop branch. I really need to get a new version out soon!

http://paperjs.org/download/#development-builds

**Comment by nadirabid** [comment]
Awesome!
