### ISSUE TITLE
importSVG fails when <switch> element present

### ISSUE THREAD

**Issue by jchaffer** [paperjs/paper.js#1181]
The importSVG routine appears to silently fail when the SVG data contains a <switch> element. Obviously, correct behavior would be to properly support <switch> semantics, but at least rendering one of the child elements would be a simple improvement on the current situation.

The following should print "English" or "Spanish" depending on the browser language, but instead renders neither string:
http://sketch.paperjs.org/#S/fZAxT8MwEIX/iuWlRUJxWrbU9YZYukViIQwmnBy3jW35jjgV4r9zHlgQYrp3uvc+Pd2nDHYG2cn+AjRO8l6O8b3ui80CFyeOYqPrXOdrwOMgJ6LUKVVKacpDE7NT+7ZtFVsGKRbI6GNg267ZDdJoLJ6pRjuBNySYTza4D+uAHRCqgWAlsdZAy/kbiz0L8xjc1eOkVb0brdzfCPwH0ScbfiHUT51a12wOQ0g5nmGkxs8pZuqfn7Z8uTvwG94y2EuKPhDK7uX16xs=

Problem first observed when attempting to render various SVG files from The Noun Project which contain this element.

**Comment by iconexperience** [comment]
I am not sure if this will can be fixed soon (everybody seems to be very busy with other projects at the moment), but if you need a fix urgently, here is roughly what you need to do:
- Add an entry for `<switch>` to the `importers` in <a href="https://github.com/paperjs/paper.js/blob/develop/src/svg/SvgImport.js#L190">`SvgImport.js`</a>
- Implement the `importSwitch()` function in `SvgImport.js`. For inspiration the code of `importGroup()` can be used.

I hope that helps.

**Comment by jchaffer** [comment]
Thanks! It looks like for my needs, I can work around the issue by simply setting the <switch> importer to use importGroup() directly. It's not correct behavior, but it is close enough for my specific case.

**Comment by lehni** [comment]
We will never be able to support all SVG features, and don't intend to. The purpose of `importSVG()` / `exportSVG()` is to provide a general purpose interchange format with other graphics editors and environments. `<switch>` is quite far away from such scenarios (it's the first time that I hear about its existence!)... `<foreignObject>` is another element that we'll have a hard time supporting.

**Comment by sasensi** [comment]
Also reported here #1389
