### ISSUE TITLE
Stroke drawing inconsistently

### ISSUE THREAD

**Issue by davidrhoderick** [paperjs/paper.js#1187]
I am having trouble not only fixing this issue but also reproducing it.  I have a web app with a lot going on but the problem I'm having with paper.js is that sometimes the stroke will draw way too large.  Here is how it should look:

![screenshot 2016-10-24 15 03 45](https://cloud.githubusercontent.com/assets/2300366/19646800/6f5dbaaa-99fb-11e6-8076-0c49053ccada.png)

But it draws like this:

![screenshot 2016-10-24 15 03 29](https://cloud.githubusercontent.com/assets/2300366/19646808/76f5e8d2-99fb-11e6-820a-39e84e0dd32c.png)

Anyone have any clues how this could be happening?  It only shows up intermittently.  Thanks!

**Comment by lehni** [comment]
Without any code to reproduce this issue there is not much anyone can do for you… I have never seen this behavior. Does it happen on all browsers, or only particular versions? It could be a browser bug...

**Comment by davidrhoderick** [comment]
@lehni thanks for responding; I forgot to update that I solved the problem:  Basically, I was resizing the canvas element dynamically on load and window resize so I needed to re-order the rendering of my PaperScript to happen afterwards, otherwise the canvas would set the height and width attributes to 150 and 300 respectively.  I was able to order the executing of the PaperScript using `paper.PaperScript.load()`.  See the answer [here](http://stackoverflow.com/a/40224193/1288913)
