### ISSUE TITLE
Boolean operation `exclude` with shape containing bezier and point segments

### ISSUE THREAD

**Issue by Mirovsky** [paperjs/paper.js#1189]
Hello,

 I have come across issue, when boolean operation `exclude` is failing with exception 

`Line 9830: Uncaught TypeError: Cannot read property '_visited' of null`,

when trying to exclude two shapes, both with bezier and point segments combined. I have managed to somewhat hack around with creating bezier segment with both handles on \[0.0001, 0.0001\] (It did not work with handles with zeros).

This is the first, not working [sketch](http://sketch.paperjs.org/#S/rVfBbhpBDP2VFRdAgtWMPeMZR+qpp55aKcckhw1Mk4jNEi2QtIry7/UshBaYsJtV4cSsx89+fraX10FVPIbBxeByEdaz+8FkMFvO4+/nos6e6vCcfcmq8JL9KNb3o/F1FY9nm7oO1froyXUVzfNiPr8Md4/yfDW6uq4y+USr3dno9Wn5UK0vsivrdY5KETsEIlIwyQCMzplZgwHvreWbSXZfVPMyfKvkBubakEFv2ROC12AnmdqbfN9EryoevY0n2TlkxxHFG2c0aMUmhdzqo7EXU2W0Vcj/ywfG2DyjAfJstWl1QjYnC+Cs8tYYhqSTAx7VKW1TlXsgbbxQ6zUZReJnCjkCI1rQ4JSzmm1rNLahlgGdImWNa6KxeZOlAZBiEx5GAzlpjRo8USwGukRVp2mj1mBMjoZFK0CoPVIHaoQGA0pu6T1OioYeojOuKbZzDEw+Ou5R7JSTz6oOt+oXW8vKJ9uu1YXPnRJ+rDTxe5XPtm5KcrGdPXojDQjoYz93oREhwYDLSTRHrKwU+wS5QXLyteBQclbcp34pYDY5CJOg5YBkoLQmLUdNMIqJEFmLqLEX27xVDpERlVumQ+QPuO2RdWpIn8dOZJ0e3K3QdDodWwk/ZbdP0gnkFo0lyE3I7k3W5M14tyhn5XIV5rJE1/UmxPW5W6vdN2hy2J6db1Oda4XWonOaHZClvsJosEkhOFGa1LbXOOuRgMqV0mysYRuvbDvxJIO0UesqjfesI7kL3mndNRyP+uNQOpP5KR4SkoullYxFo866rk1G21cQlv0o70NEXSZ5IyJjPVjjtRGNpxZiYwPKkBDDKELp9+5gcMsCRRztj2ZNMuWjNZNWfGss20WL7Hyj8C68JFI+HQoJ7t6nwnv/nwyGZlys66JalcU6jJqX7hjoaGpV9AlKqfE/DjqY7pyu1vVyEb4uy2UteMM6zIe7Jz8fynJ/flsWs8Uw3voLcnT1dyjL5cvw7/MDB4/FnZwVwz1w+DUrN/Mw2lmP5X/HbR2KRVOA1eDi6ubtDw==).
There is second [one](http://sketch.paperjs.org/#S/zVfBbtswDP0VI5ckQGJIpEhJHXbaaacN6LHtwU20tajrFI7Tbij676OcNF0TNfaCrVhySWSKj3x6pOjHQVXchsHJ4PQmNLOrwWQwW8zj//uizu7qcJ99zKrwkH0tmqvR+LyKy7NVXYeq2XlyXkXzvJjPT8P3W3m+HJ2dV5l8otVmbfR4t7iumpPsjJzOUSn2FoGZFUwyAKNz770GA84R+YtJdlVU8zJ8rmQH5tqwQUfeMYLTQJNMbU2+rKJXFZeexpPsELL1EcUZazRo5U0nssqVfLT4Xv/YBd193BlACyY4ymhS6P+LADCy4jwaYOdJm38bAVPOBGBJOTLGQ48I9k97qnIHrI0TRTjNRrH4mUKO4BEJNFhlSXvqjIZaRXhAq1iRsW00lLcUGQDRKOPraCBnrVGDY44aQpsQ4zRt1BmMydF4kTgwaofc53Cc6EbJLr3FSdFwRK0Y2yrFWg+eXXT83kpJRfCuxYLrdiFA5JXr7lN/Hd/lVsmxkrTMZ3EeDiAhxdg8HToj7Q7Qxe7Z5/QREtzbnKVU2CsSje4ht0hWvgQWhTDlj5FdCtibHOQYQMsCS/vuTFqW2mCUZ0b0WmoRj2LbrwXPbKQ4yfNr5De4PSLr1JV4GDuRdfqa7ITm/Ruhk/B9do9JOoHcobEEuQnZPclQcjHejCWzcrEMcxlZmnoV4rCyGWL6zyvJO+JgJ5zqXCskQmu1t8DExwqjxWaFYEVpcrbv34WPyD661t6Q8RS3rMt4L/20Uef4EPeRZdkLzmrdNxyH+u1Qep/EH/GQ0GvUhWQsArdk+1Yor2c2LzOBjK7Mfa6BVoGGHJBx2kiBpIaA1gaUYSHGo6jsuHnJ4JoFjjja7TSqZMo7d1S6XDpjWc8H6K1ry6MPL4mU9ztKgrvnlvLcPPa6SttrmrqolmXRhFH7fhQDHU1JRZ8gxTb+zUEP043TZVMvbsKnRbmoBW9Yh/lw8+TbdVlu1y/LYnYzjLteQHa2/gxluXgYfngxeOXh4eq6CcMtbvgxK1fzMNrYjuUN8bIOxU3L/3Jwcnbx9As=), fixed with [0.0001, 0.0001] as handles.

Is this correct behaviour and boolean operations are not possible with these combined shapes?

Thanks.

**Comment by lehni** [comment]
I believe this is the same as #1091, and already fixed. Works for me on the `develop` branch.

**Comment by Mirovsky** [comment]
Thank you, any idea when this will go into release?

**Comment by sapics** [comment]
Hello, @Mirovsky 

You can get pre-built version in https://github.com/paperjs/paper.js/tree/prebuilt/dist, if you need immediately.

**Comment by Mirovsky** [comment]
Thanks, we are using the `npm` right now, but I think we will have to switch to prebuilt anyway. Thanks for reply!
