### ISSUE TITLE
SVG Path Rendering Issue

### ISSUE THREAD

**Issue by mikechambers** [paperjs/paper.js#1190]
PaperJS v0.10.2
Mac 10.11.5
Google Chrome  54.0.2840.71 (64-bit)

Loading the attached SVG leads to some errors in the rendering in PaperJS (notice the A). Note, these are SVG paths, not text.

I have attached an example project, the SVG, and images of the SVG rendered directly in Google Chrome (on Mac), and via PaperJS.

![output](https://cloud.githubusercontent.com/assets/37918/19713201/efc0fa60-9af8-11e6-9e49-e4ff9cd8a3da.png)
![original](https://cloud.githubusercontent.com/assets/37918/19713202/efc30be8-9af8-11e6-93e7-259d48d1e533.png)

[svg_bug.zip](https://github.com/paperjs/paper.js/files/552335/svg_bug.zip)

**Comment by lehni** [comment]
The same example [as a sketch](http://sketch.paperjs.org/#S/zVZNb9s4EP0rgvbQFiBpfohfTppDL5tD9xSghzQ9uIpiqpEtQxbkLor97/uGTNLmUqAo0PZgczgcjt68eSPoS73f7Lp6XV/dd3Obala34y3tl81UHZdt9bp6cU7r592wP76+qdM8H9ar1el0Eicjxmm70lLKFUJu6urU384JQY1RImg4Utdv0wyPN4L2S9+d3oyf4ZCVrEpYVc4uzud+HrqLduo2c3e+KrvzbdXfIrx4KeqwmVNFrn+U8kJaZpQWoZVMRWGYFZbpAEM50RQrishwakTgTig6sBx/IXlhBy6FZ9oIl3DoWtpyLRRXQnPAgm3LyiQCLGtEQ5d9MYIgP6pwXNHNbBmXvUjqmcJtxwxlxEoAMxLDDEApApsNQIVfRHos05QoIcnwgE0nDqgtsDT0GAMgGYThyOCydfXAhY6U61tirsH6PG32x7tx2oG1bA/g8iWPQQRbce2R7xXCjvO/Q4eQu34Y1tV+3Hdnx3ka77t19Zc26k7Lhz3f9XM3DT2WdaXkTb161pbokRdPtyIsgB8G4kuK8M40IXGNfiwoyMEdOLw6oICBP+58SNq2qhEBnCAYXQRf2UCluZXEMnELotACS363gJhWUah6jAQ5xQAdeqH2StDdZJU0zDyt6Bb+PfUZbbU8gnoLwJ7k0JB+cJRTOWJcFSsQQA6citOlbOSSURvkSGrJHYvIHJACa0Kkud5J7pMC2ohUqEbn/LEYqC0eee4zHqapx5LECfeiIcZf304ji7J8gB4D00BCetRtng3gtblUqDpSN1y2Ege1BDheah9bmhzJ6FATkZKKiinrI+bRaznlwYEhaStqLAmdLKo964guKBKGJ9aIUkhDkfwjRlnRKAMeYi61bagLDRSmnylMPyrMmt9ApLNCYy7opYQxAAMDyg0k54Y5UtPTiBiCbwFfAfBbY6F/D1UlCMIN6IBlDm3AJff1klFlruzg87XrXWlHvodKBmKEa5vA02+ovrEhvxUkukn6UQ/6IdnYMjplurK1WINCIo3mU31ofKkv5vpyV6FCCEXRIEJrLGfME2pJVlDpoOhFjIbHX1+y1V6Y55NzabX67uBcNtHnuUmY/Z+am5LpB8YGM2v/mLFZbfHDR8XFi7ObPX2LIGSHj5HDNH7q2ln0u8M4zVfv/n6JoFdn+G75iC+E+8PY7+djvX7/4b//AQ==)

**Comment by lehni** [comment]
Actually, this appears to already be fixed in the `develop` branch. Time to roll a new version out soon!
