### ISSUE TITLE
Regression: resolveCrossing() moves intersections

### ISSUE THREAD

**Issue by iconexperience** [paperjs/paper.js#1191]
In the following example the intersections are moved during `resolveCrossing()` and produces a wrong result.

``` javascript
var path = new paper.Path({segments:[
        [100, 200],
        [300, 200],
        [300, 250],
        [150, 150],
        [150, 200],
        [350, 200],
        [350, 300],
        [100, 300]
    ], closed:true});
var res = path.resolveCrossings();
res.fullySelected = true;
```

Expected result:
![image](https://cloud.githubusercontent.com/assets/2122773/19759297/a10822ce-9c2c-11e6-8d07-31a78d40f13c.png)

Acutal result:
![image](https://cloud.githubusercontent.com/assets/2122773/19759270/7999ca3a-9c2c-11e6-8e15-934196b19a71.png)

This behavior was introducded in https://github.com/paperjs/paper.js/commit/fbb0c59598c9ec265b44a7fcf56c189ec75e8300 , which was introduced to fix a similar issue.

This certainly has something to do with the overlaps, but I do not fully understand what is going on.

**Comment by iconexperience** [comment]
I do not think that fbb0c59 caused this issue, it merely brought it to light.

Some testing showed that after the first call to `divideLocations()` the `_time` values of the crossings in the middle are not correct:

Before first call to `divideLocations()` (crossings in the middle are at index 1 and 6):
```
0: 0.32635182233306964
1: 0.5841272008905138
2: 0
3: 0.5
4: 0.5
5: 0
6: 0.4158727991094863
7: 0.6736481776669302
```

After first call to `divideLocations()`:
```
0: 0
1: 0.5841272008905138
2: 0
3: 0.5
4: 0.5
5: 0
6: 0.4158727991094863
7: 0
```
The correct values at index 1 and 6 would be `0.5`.

A simple fix would be to run through all intersections after the first call to `divideLocations()` and simply call `getTime()` or `getCurve()` on each intersection. This will update the `_time` property to the correct value.

**Comment by iconexperience** [comment]
Created pull request #1204 as a fix for this issue.

**Comment by lehni** [comment]
I think there should be a better solution to this... I want to think about it a bit.

**Comment by lehni** [comment]
@iconexperience this was a tough one to crack! But with this new code, no recalculation of curve-time should ever be required, and rescaling is correctly handled if dividing happens before and after a given location. I hope it was worth the effort for performance...

**Comment by iconexperience** [comment]
@lehni 
There are some problems with the new code. Here is an example (which is quite and awful path):

```
var p = new paper.Path({segments:[
        [256.22272245372784, 322.2911416479855, 1.3846994306732086e-7, -1.0032863428932615e-10, -0.07145907403264573, 0.000051770563516129187],
        [256.28274925468855, 322.29109816063755, 33.69934566220388, -0.024413795440409558, -0.020001069211389222, 0.000014489955333374382],
        [256.222722318658, 322.29114164808345, 0.020004442897743502, -0.000014492788977804594, -1.3846999991073972e-7, 1.0032863428932615e-10]
    ], closed:true});
p.resolveCrossings();
```

The variable `rescaleLocs` in `divideLocations()` is not initialized. This may be easy to fix.

**Comment by lehni** [comment]
Did you try the latest state of the develop branch? I already fixed this, I think.

**Comment by iconexperience** [comment]
@lehni Sorry, your are correct. I tested agains an old version. This has already been fixed.
