### ISSUE TITLE
Checking if a path intersects itself results in an error (TypeError: locations is undefined)

### ISSUE THREAD

**Issue by 0-zM** [paperjs/paper.js#1194]
I first noticed this bug [here](http://sketch.paperjs.org/#S/lVPPT8IwFP5Xlp02NQMkGjOiFzwZSUg4eBAPpXtsL3Svpu1GIuF/t92GFAQNvXTve7+/ftuExEoI03C2AsOL8CbkMnN2zVSQKwAKHgOCdTBlpoji0Zycg6Py4GSMiguI5hTYs+FABlQ6lUgmUYwyWUbxVY2wTjR+wU0bpliGlU4fOnOJQoylkCrdFBWkwcTV/Uke3ve7OHc0M5ViBiWlAw9eKMwLQ6B1Oti2cHe5sZtdEm2UXEHTyC6w2Se782/jP5r/GuCo5RtmprAth0f4i2XJwvNQyYqyedgRrImt4BUob5Ju+32LGylFImkiKw0TWYN1LCvibpQIakt6vFuoiSyRnlEbRtxF3o1aV9ubZVmbkny6V4o757pAAUHUxoi2+5M/S+xT1oYpKO0sM8hLWy7q70ptuxuXu3roVKGBGx1Z+cSxV8nf9tqtO9r7er1TL2crJNx9e5EOq1HjQjTUMKHh0HtWshfI9oR0L5XvJSo6dHnmMc9nuW6AA7aZAGWioV9ha//7hQK2auSgw/T9Y/sN). The bug appears every time the function is called (in case of the above example whenever the mouse is moved), whether or not the path actually intersects itself. I am pretty sure I didn't make a mistake in the code, and removing the if statement which the check is the condition of makes the error disappear.

**Comment by lehni** [comment]
A very simple fix. Apologies it took so long. You will be able to download the latest prebuilt versions shortly here:

http://paperjs.org/download/#development-builds
