### ISSUE TITLE
tolerance of hitTest affected by item's scaling

### ISSUE THREAD

**Issue by Skalkaz** [paperjs/paper.js#1195]
If there is a circle with radius 100 and I hit a test with tolerance 10, then I expect true results between 90 and 110 in radius. This is how paperjs works.

Let's scale up the circle by 2 meanwhile keep the tolerance at 10. Now I expect true results between 190 and 210 in radius, however paperjs gives true result between 180 and 220. It seems the tolerance also scaling up.

Demo (with rectangle):
http://sketch.paperjs.org/#S/vVTRTsIwFP2VupdtCVk2ElRGeBBfNTFq4oPzoXQXVlfbpi0IIfy7d2UoiIboA2+959x77tnp0lUg6RsEefBQg2NV0AmYKptaqCkZEqakVQISrJIxl2W0A8SDQmqqwSQWnONyahOqtVjeUmf4AocnVFgopKBLMFhqo16BuYQyx+dw06At+fNcIefUEE1dhZiEd3KHx2iz1VUJE8pCiZQzM2gx64yq4YmXfiZt0QkX4loJ1ZgIx4KyOmwZWpaRV1ZcuqifdgjJ0jT+3LHPZxk2HOO7v/Nef8tvHTMqIMriQlbc+TY0uVrk5BKblznJeum6kEo7rmTDOAzfUMkgb5Y1X5b7ANZe4B7sTLidrBF7BOuirXhno4Tr8AKj8CqLCSw0dkK50RkQ4zXysEO+BM+GeAMzIQ5tXvRPYbO7a9P/Hkd97uXbPTR+fop8R9nfjX/z2TtFwKN/BIxPxdgArXWjZ4P8+WX9AQ==

**Comment by lehni** [comment]
If you set `applyMatrix` to `true` in the beginning, the expected behavior occurs, so this is linked to the item's matrix not being taken into account...

**Comment by lehni** [comment]
The same occurs with `Shape.Rectangle`:

[Sketch](http://sketch.paperjs.org/#S/vZMxb8IwEIX/ipslQYqiBIm2GDGUrh0q6IYZjDmIi3uOHEOhKP+9Z1DVUIaqHfDm56fv3j3JhwjlG0Q8mqzBqzJKI2UX4W7sig2ZslhbAxndsrnGRdISOgOBRu7Bka9y9hWUz6TyegtPQRUocCsdq6QvyYHwzialrCAbk1HiykByEMjoVFaj52zaz1NW5PksPcm1/gBSu+fqUhvzaI11nMVzI9U6FtiEKALDpKxWkshFR2Cp/XMg0/DDjrN74uw5K3p5I9BWXlsML562cRIV8IIMgc6ZdxtojoAx1BvjWwuS9gK1T77g6YlE46iRJH4oOgx2FTlhceIMmDsyeJyyb+DNkBrZGHMZ865/jZjddsylNPXvOc/67V4Gv71Gv6Pi78F/5Oxdo+DRPwqmvzd3INfH71BHfDprPgE=)
