### ISSUE TITLE
Generate shapes from CompoundPath final result

### ISSUE THREAD

**Issue by dragondgold** [paperjs/paper.js#1196]
I have a complex shape that was generated using a `CompoundPath` with multiple `Paths` children that overlay in some cases to generate the more complex shape. This is an example:

![alt text](https://i.stack.imgur.com/W9kbW.jpg "Example")

This image was generated with a `CompoundPath` and this `Paths` that overlays each other:

![alt text](http://i.imgur.com/9BFZElg.jpg "Example")

I want to know if there is some method on `paper.js` or some algorithm that allows me to take the final result of the `CompoundPath` (first image) and generate the more simpler shapes to rebuild that final result but only with `Paths` (for example there would be a `Path` for each eye, a `Path` for the mouse and another `Path` for the tongue) . I need this because I want to be able to fill for example the eyes each one with a different color using `fillColor`, which is not possible because the color is taken from the `CompoundPath` and not from the `Path`. The same goes for coloring the pants which I can do because it's the `CompoundPath` color but without coloring the entire border of the image.

Is there any way to do this? Any built-in method in `paper.js` or any algorithm that could help me to achieve this? 

Thank you very much for your time and help!

**Comment by iconexperience** [comment]
I think what you need to do is to call `setClockwise(true)` on your `CompoundPath` and then call `reorient()`. This will set the orientation (clockwise/counter-clockwise) of each child path so that if several paths are stacked above each other, their orientation will be alternating. starting with clockwise for the bottom path. After that, if the orientation of a child in the CompoundPath is clockwise it represents a 'hole' or white area in your image. a clockwise orientation means that the path is filled.

If you then clone the children of the `CompoundPath` and fill the ones with clockwise orientation in brown color and the other ones in white color, you should have a result that will look like the original.

`reorient()` will only work if there are no intersections between the paths. Also, please note that `reorient()` is only available in the development version of Paper.js.

**Comment by dragondgold** [comment]
@iconexperience Sorry for the delayed answer, thank you very much! It worked perfectly with the described method :)

**Comment by fraank** [comment]
I had almost the same question, which took me some hard time (and this conversation) to solve.

Maybe this code / sketch helps somebody else, to get more insights on this:
[PaperJS Sketch for Subtraction of a an evenodd Compound Path](http://sketch.paperjs.org/#V/0.12.17/S/rVTBbtswDP0VwpfYq+skBgoUHnZZTj0MG7oBXZHmIFuMLUSRMplOgRb599GV7WRd2qVYdTDkJ/KJ7xHUY2DEGoMs+L5CKqogDgor2/+tcFCTcPQTPsF0Mvl4Zwbo9k9IPWDNyBzSySSG6SV/0gtYdMcbIaUyJQekFwx5MBfFqnS2MZLxb4Kq5BoLEqbUGD7eGeC1scpQBvOuiPOeKO5rGJBFDOMx/LCbc41L8olgl0AVQv2rEQ49Y1soE/qC55MFnEEKHw54j+KwiH36Umk9s9q6DEYO5YjhXTQo2ggidIblGLyHmV1vWnWttF5QUSktHRouwQPteq69VfK1YSYm+qzZpX3o36b0VpxqQL+eG3Eg3VPdKEkVCO5OhaqsXiTbRfHrUr4oKTWylptKER7XAmHX4jPe9XWMIY24wx0w9UAUd7G3J8TC/7kyHVyZvrsrV8b8q8EnmJK+wZT0fUxJB1PSt5vi98emKW99GHUHNWp2C2UG5Bo8iL5uNJcywi0aK3n82tsL22gJOUKHgnVgrHlAZ4fp7CYzqZFm2hare1Vj2HJH+zOH1ik0FEb9PBcN2Ya4SfunKqmbnJwoKOzSPH9hTW01JtqWoc9KSqQrwnUdRk98BxQO13aLYZu5v7uD+PHNHYrVU1PqIJsvdr8B)

```
var startX = 100;
var startY = 100;
var sizes = [ 200, 180, 25 ];
var padding = 25;

var background = Path.Rectangle({
    point: [startX - padding, startY - padding], // Top-left point of the square
    size: [ sizes[0] + 2 * padding, sizes[0] + 2 * padding ],
    fillColor: 'red',
});

var pattern = new CompoundPath({
    children: [
        Path.Rectangle({ // Outer = Black
            point: [startX, startY], // Top-left point of the square
            size: [ sizes[0], sizes[0] ], // Width and height of the square
        }),
        Path.Rectangle({ // Middle = White
            point: [ (startX + (sizes[0] / 2) - (sizes[1] / 2)), (startY + (sizes[0] / 2) - (sizes[1] / 2)) ], // Top-left point of the square
            size: [ sizes[1], sizes[1] ], // Width and height of the square
        }),
        Path.Rectangle({ // Inner = Black
            point: [ (startX + (sizes[0] / 2) - (sizes[2] / 2)), (startY + (sizes[0] / 2) - (sizes[2] / 2)) ], // Top-left point of the square
            size: [ sizes[2], sizes[2] ], // Width and height of the square
        })
    ],
    fillColor: 'black',
    selected: true,
    fillRule: 'evenodd', // could be evenodd or nonzero
});

pattern.setClockwise(true)
pattern.reorient()

var cutout = background.subtract(pattern);

background.remove();
pattern.remove();
```

Cheers!
