### ISSUE TITLE
_getIntersections() bounds check error

### ISSUE THREAD

**Issue by gerfarfel** [paperjs/paper.js#1197]
The _getIntersections function in Curve.js does quick bounds checking by scaling segment handles by a factor of 0.75. That test seems to be yielding an incorrect result in the following example. For reference, the code I'm referring to is preceded by the following comment:

```
// Avoid checking curves if completely out of control bounds. As
// a little optimization, we can scale the handles with 0.75
// before calculating the control bounds and still be sure that
// the curve is fully contained.

```

Here's an example where that test fails to yield the correct result:

```
var seg0 = Path.Line(new Point(99, 106), new Point(99, 200));

var seg1 = new Path({segments:[
        [100, 193, 0, 0, 0, -28],
        [140, 106, -52, -12, 0, 0]
        ], closed:false});
 
console.log(seg1.bounds)
// prints { x: 98.80332, y: 104.64679, width: 41.19668, height: 88.35321 }

var sects = seg0.getIntersections(seg1)
console.log(sects.length)
// prints 0, so no intersections were found

```

[Here is the sketch.](http://sketch.paperjs.org/#S/lVJPa8IwFP8qj1600MWk1a7N2MnTYAfZDjtYD7V9NsWaSJLNDfG7L7GKOsZgIQTy3svvH9kHstxgwIPXNdpKBFFQqdrfP0oNBhsKjzArrSDPrcShxB3MVCvtMM8jYDQNI7itxZSG4UMhC3kCYA7gOOJAhntX2KC0hs8LCac1Z5Q6sDyJgJ73XZwtouuRMT3yuc4kdgeL+8nFZWYRQdUpgzVflZ3BQ6+iUtKoDkmnmqFXQ5bqXdYmLORoBFvtZBvYwyeHPCMZTRKH+8Ud05ik4/TeGdq1tRUcxoywPE2zCAS2jbAcsowkkyRmcLi4razxfn1upEH7JC1qX22diiN9+FORf0E6lI0VN5qcOaNAKmivMWCHGmHlLXhSK1rzguaU8FRttr7TJ90HU4m2qzVKDnMv6pypsVqtcao6pTkMll1ZrQc3rbfeNSvkKUcrSvsfKvY7lcb6TyL3/5Yay/XWfygT8Pni8A0=)

If you zoom in, you can see that the curves do intersect (twice), yet no intersections are returned, because the bounds check yields the wrong result. The minimum x-value of seg1 is 98.80332 (as returned by seg1.bounds), but the bounds check uses the value 100, because scaling the handles by 0.75 trims too much off.

**Comment by iconexperience** [comment]
Thanks for reporting this issue. 

I thought that this 0.75 factor was reliable, and I do not remember any case where this failed before. But in your example this abviously fails, and by quite a margin.

I must admit that I am a bit shocked. Removing the 0.75 factor should be no problem and the performance impact should be really small, but wow, why hasn't this popped up before?

BTW, here is a <a href="http://sketch.paperjs.org/#S/fVLBboMwDP0VKyeQWJoAZZCqp50m7VCpx8KBgQeoNKmSbN1U9d+X0FZbV2lRYin288uznSOR9Q6JIOst2qYnEWlU6+8ftQaDHYMlrGrb05dBYiDxACs1SBsURQScZWEEt76YsTBclLqU/lxIuCOZYI4oODrHDqU1YuMhcFkbzpijLJII2HU/xHkV3YJSNr3rYvPYGR6fsdVvVBVBMyqDrXirR4Onsx7wxldEjdVqi09qVNoJK0mnEWVJFn8A66YeB9k5yERzDfO7fI3tTzb/J3uS0Chp1Ih0VF0w4V/Vu2xN6GOzGey1a6WBI3wKKHKasyRxNX4JV3VKszR7dE0+DK3tBaSc8iLL8gh6HLreCshzmsyTmMPpdgKNY1xO46Qd2mdpUXvn4KRMGsJ7YS6Fjig724fuU7xqrLd7P2VDxKY6fQM=">simpler sketch</a> that also disables stroke scaling.

**Comment by iconexperience** [comment]
The 0.75 factor comes from <a href="http://nishitalab.org/user/nis/cdrom/cad/CAGD90Curve.pdf">this paper</a> (12) to (15). So either the paper is wrong (which I doubt very much and which would be a real problem for our fat line clipping), or the factor only applies to the distance from the line through the curve's end points (which I suspect).

**Comment by iconexperience** [comment]
<a href="http://sketch.paperjs.org/#S/lVZLb9pAEP4rIw7BbhwHDAQVK5cmlx6iVknUC3DY2IOxYnaRvSZYEf+9+zJe7JAoCDA788037xXvPUo22Jv1nl6RR+ue14tYLM87ksOW8DXcAsU38XOLuf9XCJz3ApMNUl7MYD4fTocejCY/PRio93giviaDpQfz8c1EnG+mHsjPVOsHy+XBDRdUUvurMsuqJ8ww4hgLRzwvUegWVDp/YSWNi0ehC7UgZ2Wy/mVLtbzcxoSjVgiSVUkjnjLquPC+oCBe19cQlfkODaUWpitwGheu5c7PccN26MgwJbLRmFrIKvjyTGiSoaNS0aCuiV/wnL3iHctYLsz7SY5I++dgTxHJUprILEhWYHiMX+Xeib9VEbddonYmslo7Qa4iTpDfyaoUjjsfLOXxH8lKefQ0Wr6i4Xa4Fxa7uWypPFXqNFwK0IIvuBAFGnCjAYEGTBtAoRicEfwQ8mAJl5rVhWsYW6CqAY1qUNUCBRbT2ICCNlNgMU1q0AmTZHmQNdik1FHByNAL8wj2nuE18KoNrzRcP4LK5F3D39JYrY02IfvPPMAV7I3ZGtNkzdt2Z1wJuyrUdq3VMDPajKfwJcxUUB5oJ/U8tMbl4/G2QGfs2jOeY9z/FNkd84NcZnuR1czq/eaMZSa0Z/FTaaR8TWicoTmYO0kZSQOf0QdWFnjP3qh9KeBOoI43g6aQ5OImMiEbplOhWMF7BgTWKQeOBQdG9e24YnUgxaxZMgF7xKLMeL1sQvAszLR7f8tSyr06CDgSqAvwuH2cZZgTGuEMxlp2qBsgl//ow22ITuQ+r7YiN9EQzX+V0j5cXDTB+cdUTZSrNC/0pVCrAovcKleHwteq3zSs0QdA0dovImIl/3ZIw++F9KfkTUymjFYRjblutsX8zQ4ex6bdxI/aaDXyfCvtQezk9kFGh+7o5yQ5P/pN9m57EP09XN6CTjTGjBN/H7YQVRtRhZ3amlgt+rozqnqfeTkFfuWsc28cQvE/5iVH8qoIit5svjz8Bw==">Here is an interactive sketch</a> that shows the bounds and the rough bounds (using 0.75 of the handles' length). It's not really difficult to find cases where the bounds are larger than the rough bounds.

I still cannot believe it.

**Comment by gerfarfel** [comment]
Unless I missed something, the paper you referenced doesn't show a derivation for the 0.75 factor. But assuming it is correct, it does appear that they only apply that factor to the distance from a handle to the line between the end points. So, as you noted, that's undoubtedly the problem. Scaling the control points back towards their respective end points isn't the same as scaling the width of the fat line.

It truly is surprising you haven't encountered this previously. Thanks for your great work on this!

**Comment by iconexperience** [comment]
When playing a bit with my interactive sketch I was able to find cases where a factor of more than 0.9 would be necessary, so I would assume that there are extreme cases where the factor is even closer to 1.

@lehni We have to remove the `0.75` factor from `Curve._getIntersections()`, this was a wrong assumption. As I mentioned above, the performance impact should be small.

**Comment by lehni** [comment]
@iconexperience wow, thanks for looking into this! I will take care of it now. Also, let me know when you have a moment to discuss the many pending things. I've been a bit out of the loop, but have a bit more time for paper.js again finally.

**Comment by iconexperience** [comment]
I can always make a little time for discussion. Next week I may be able to do some more real work on Paper.js if we decide what needs to be done.
One more urgent thing that needs to be done and can easily be fixed is the two bugs in `PathItem.compare()`. I have a Pull Request for that at https://github.com/paperjs/paper.js/pull/1193
