### ISSUE TITLE
Is there a way to get non-increased image on retina display?

### ISSUE THREAD

**Issue by katriyna** [paperjs/paper.js#1198]
Steps to reproduce:
1. take a monitor with devicePixelRatio = 2
2. render input image on canvas using paper.Raster
3. render canvas to output image via `canvas.toDataURL()`

Expected result: input and output images have same sizes
Actual result: the output image is twice larger than the input image

Additional information: if I render image on canvas via `ctx.drawImage`, input and output images have same sizes.

Here is an example:
http://codepen.io/katriyna/pen/aBdxYQ

Is it possible to workaround it somehow?

**Comment by lehni** [comment]
You could turn hi-dpi rendering off, by adding this attribute to your canvas tag:

`hidpi="off"`
