### ISSUE TITLE
Modifying opacity hides PointText

### ISSUE THREAD

**Issue by ubershmekel** [paperjs/paper.js#120]
When I add this to line 5 of http://paperjs.org/examples/path-simplification/

```
textItem.opacity = 0.5;
```

The text for 'Click and drag to draw a line.' does not appear at all.

Chrome Version 22.0.1229.79 m
Windows7 x64

I found a workaround for now, though I don't really understand the problem.

```
textItem.fillColor.alpha = 0.5
```

**Comment by hishin** [comment]
I think this problem is still there. What do you mean nightly version?

**Comment by ubershmekel** [comment]
I currently can't reproduce the issue. Seems fixed to me.
