### ISSUE TITLE
Laggy animation performance introduced with version 0.9.10 and above

### ISSUE THREAD

**Issue by markmanx** [paperjs/paper.js#1206]
Hi,

First of all, paperjs is awesome.

Although there's a problem.  When doing even the most basic animation (just rotating a rectangle), I noticed that when I use version 0.9.9 and below, animation is smooth, and I can easily hit around 60fps even on mobile.  As soon as I bump up the library to version 0.9.10 or above, animation slows down to around 6 or 7 fps.  It seems like there's a lot more processing on each view.draw() call in 0.9.10+.

I think making a Sketch will be pointless as I can't change the library version, although it's very easy to set up a demo.  I can get one up on Codepen if it will help.

**Comment by markmanx** [comment]
After a bit more investigation I found it's down to the canvas size.  Larger canvas sizes means slower performance (seems obvious now), which prevents me from acheiving an acceptable framerate when the canvas is 100% of the viewport size on mobile with just one small spinning rectangle on-screen.  Quite surprised that even on a pretty powerful phone (Samsung S6) I'm only getting around 10 fps when the canvas is 1200px x 1200px.

Totally understand that the strength of paperjs is to keep the original vector data, but this means there's a big difference between paperjs performance and native raster rendering.  Any optimizations you can suggest I make?

**Comment by lehni** [comment]
In v0.9.12 we introduced hidpi support, which is on by default. Could it be linked to that? 

[See here](http://paperjs.org/tutorials/getting-started/working-with-paper-js/) for instructions how to turn that off...

I am surprised that the performance would be that bad though on a Samsung S6. Is there any way to profile the script and figure out where most time is spent? I don't have an Android myself, so I can't do the testing.

We do have some plans to implement caching for better performance, by keeping separate layers in separate canvases, as well as allowing items to cache themselves as bitmap data for faster rendering. This isn't implemented yet, but should certainly help with performance.

**Comment by lehni** [comment]
I am not sure I can do much about this issue though... I will close it, but feel free to comment if you have more info (e.g. profiling), and I can reopen again.
