### ISSUE TITLE
hitTest is broken for rectangles with radius and stroke

### ISSUE THREAD

**Issue by georeith** [paperjs/paper.js#1207]
Hit testing rectangles with radius and stroke is incorrect. The easiest way to see this is in the diagram below with the attached sketch used to generate it.

Here is the key:

![image](https://cloud.githubusercontent.com/assets/3090066/20720258/61a11b56-b656-11e6-934a-aa6dd17da6d9.png) : no match - correct ✅ 

![image](https://cloud.githubusercontent.com/assets/3090066/20720274/7528c14c-b656-11e6-8d59-ec1ea615fa7e.png) : no match - incorrect ❌ 

![image](https://cloud.githubusercontent.com/assets/3090066/20720307/92539288-b656-11e6-90cd-d24e273646ff.png) : matched fill - correct ✅ 

![image](https://cloud.githubusercontent.com/assets/3090066/20720363/b9b2ff58-b656-11e6-8492-1fd63793f05d.png) : matched fill - incorrect (should be stroke although fill does exist here) ❌ 

![image](https://cloud.githubusercontent.com/assets/3090066/20720340/a90a1ac4-b656-11e6-9b9d-e024430c99ff.png) : matched stroke (mostly correct in image but some weird pixels in middle match) ❔ 

## Rectangle with radius and stroke
[Sketch](http://sketch.paperjs.org/#S/fVPBbuIwEP0VK3tIokZWCAtqw6Jqt8utK63KSnsADiY2xCW1I3sCZCv+vbYT3HQP5UBm3jzPjF9eXgNBXliQB8sDg6IMkqCQ1OZHopDm/xiaI8FOaGnCaJVN0wSNbtNNPFsLy1CsACL2laeVpGb46YpGr2uBXJvc/ScuBSUPbFmQiot9jnak0sPCX06hzNE4HWAPspIqR+GX26932fdp6Eqkrqv2FwHFz8MuO15Vnr9IF9PFz46vCOWNztFd17mWXECOjpydcMEEMIV1swVFCojsrpjyI6csyuLY8bnQTEE/aS0uVoK18ALgk93byGA0mg3xkvF9CaYwzrJete5SP2QjqDaFd+6w4LlE2dPDEgZZP7Id9BQm6P+ErQSQL092ck+iEuys1cbkO6lQZMHWnTMDcDszybe57eXim5sYuZfnuWfPPc9M0nNt7LkIWaITtvfDbxtH5wS1Vq4rQzHdVPDh5iWHP0xD5A4PuWbvz7xlf52/ViNjzU1yBWVNCg5tjlI88eDAG/0O932Aoa2NiedzFHZChqYUFi0RITJGUvstidJkNBknmXnE72A2mSRp4jA/5oORUw/3jnOPDrtcb2rfDq4bXUYm6sCL8dha1Eo+mxtj40p+ZI+kNTYllD6UvKKRl8+e+IypmLCN9ZDnjN/UlACL4pn58LeKkYNbTgf5anN5Aw==)
![image](https://cloud.githubusercontent.com/assets/3090066/20719801/eeb695c2-b654-11e6-9d87-68f3357aac54.png)

**Comment by lehni** [comment]
Great test-case, thanks! And you're of course right, that's a bug. Will investigate, may be a simple fix!

**Comment by lehni** [comment]
If you reduce the radius to 89, it looks quite a bit better : )
