### ISSUE TITLE
Color convert error in color.js at line 819

### ISSUE THREAD

**Issue by lichenhao** [paperjs/paper.js#1214]
https://github.com/paperjs/paper.js/blob/develop/src/style/Color.js#L819
When the color is `rgb` run the toCSS method with convert method, it's always be white.
because the color is always lager than 1. 

SO SAD

**Comment by iconexperience** [comment]
@lichenhao No need for sadness here. Do you happen to have a test case that shows the erratic behavior?

**Comment by lichenhao** [comment]
When I run code like this `new Color(r = 200, g = 100, b = 10, a = 1)`  it will output white color. But it is excepted to output color value `rgba(200, 100, 10, 1)`

**Comment by bmacnaughton** [comment]
The problem is that paper expects values in the range 0 to 1 (corresponding to 0 to 255).

**Comment by lichenhao** [comment]
@bmacnaughton  I think use the RGBA values with CSS value is more better. How about use the [tinycolor](https://www.npmjs.com/package/tinycolor2) as color utils for paper? No metter what type the color is ,`HSB` `HSL` `HEX` `RGB`   etc. It's always enabled.

**Comment by lehni** [comment]
Like @bmacnaughton says: The color component values are floating values between `0` and `1`, so you need to scale accordingly (e.g. `red / 255`).
