### ISSUE TITLE
Raster.toDataURL() behavior discrepancy on iOS

### ISSUE THREAD

**Issue by elwin-jacellc** [paperjs/paper.js#1216]
I'm getting a discrepancy between the toDataURL output in iOS that I'm not seeing on Chrome desktop. Looks like the url is truncated so the image never shows up.

I should add that it only happens after I perform a getSubRaster or getSubCanvas operation before the toDataURL method is called.

**Comment by lehni** [comment]
Could you provide a simple test-case for easy reproduction of the problem? A JSFiddle, CodePen or Cloud9 project would suffice.

**Comment by lehni** [comment]
I will have to close this bug if no material is provided for reproduction, as there is nothing I can do without being able to actually seeing the bug in action...

**Comment by lehni** [comment]
Ok, closing in lack of further information.
