### ISSUE TITLE
API change responsible for differing mouseDrag scale behaviour?

### ISSUE THREAD

**Issue by techninja** [paperjs/paper.js#1224]
Found [this old bounding box scale sketch](http://sketch.paperjs.org/#S/pVhLc9s2EP4rsA4RadGM7MSdiRT1kPjSmbrN2O30UPVAkZCEmgI0JCjbdfTfu3gSJEFanuigB7CPD4vdb5d6GdFkh0ez0f0D5ul2FI1Slonfh6RAhySvcIkW6GVJl3yf8G05Q9eR+LEj9BsjlNcLyZNZuLQid0lGKlj5MDUyZuXTdEmPc1ikwtGW8N/3nDBqnZV4s8PSGi8qLLVLXrAH7CysSZ47PznLcZHQFESuXeMlznEqjN/BR0I3OQYntMrzed/+fZrkePG6yG+s2CU5+Q9nw8J3jCdiwUilBU44/ibiGYQS57qiUgU1tlQohM1Chu0G5zwB8OpeYhtOdGGXTMznRnMvL6WrqS6roamWpOaaFSgQ6gSUpnP4+GwEZRrAymSi8bkIHRcGCZqgW1CJ4WoytoNDnbunmdcWFNKGBQ1SW1jnjBVB25hzwNC1BmJgS8XzS85WwYHgx7iE2wIladhaiTSiSBtz7eRks+UUlwJYy/cFmsbXAsI0/ggY4d3R21YizdpgP/w01TJ7eSLI4K8sh2BD2guVmXiLUJnwqpApA9UU1RhmDpyja0jVhjE1XuVJ+jCWAkLs6EkxGZIUSgwXEbKZZCNQp54OJMWPSKSlSljlNc1ZiTPYFDXYmzfKYjdjMp2T0rKQCfTmkueYbvh2hoI6xc9VsCftSzhHbZnIWJG1B0Yg6Oi9Pdg5IkrgGLoRTLJMhwN8ZHU2He1pyx1j9vwFhhuiMjgmwKr2JW1FciPy8YYS0FSxYwdZ6xCFdZKXuMkFhBJ+37EQCNMykAheZB10nZxJogmVhHh1ReICC+fyNEJCljAuMQco8rSF4azFFL17p9ZKID1CN/HTYnHZWXyGRcfYilU0K+cWpTSuIb3UyFLgfODtOGebYCxlxgaSeCkrBlPDpnjJ1f0vECeS5F/6ZY/qA0OIhxFQhl4D0XTXdNCwpdRmaAwJpb4boyuwpVZECVG4hRg/7SGjg8tpdDk1Yurd3750NcZ1WqyMmuey9+TAxM36tlhJxEq/MqElLnhwFTmVuopVrcRPEVrFnO3DAe8nGbi4uv5hG9YA5NtZT8INhKCZOtr4fLiKdJW0q2ZYS5eMUdI/61TqjYKi+b9IJinjsj9cnX5Q4XG/tBgBQWw5sntQBXpzORrwIpfcDtAXYd1ENF0OSQ3mqthSdGtJktFbVpX4hj3SAB/gysLGAKmd1hOf7s6E3+GyyuV+wf4FFzGs/YFLrqzEsl1EzmSqeJ+sUXBmtUPVQFQzkOStJJSJHcvImuCijMstWXPb/ISENRHz5z0EHy5JIx5buSWvpfSmS9uyh83bCGTDoi0nYR/h1RJOL4SY1I4Jxzu991b0A73Jdg+Ver25FxpbDn4vcXcdNSjcvABSN6aEZvgJ/bxAVwJW3/7nBfoYdi16gHXAGVbwQvIXw11NLFOP0rG7VDe3t8IT/OMPlx+bfPYBYE6hxGW14kWScs+NN/k0jNVw9745UfjPqO6+dVj/Qet671ygqRWpifryVzLm2CTm2aJ7ECe15ZMBS80V1fbMoimZFg+ZPmbEdG5NxJTvhDO06t3JU4+ksrw80V6o+vr+vZdhzxZqgoST+spTbioPreQZmkddaPJN3VLDxmmzqj/nmsQnPTjDs+c+xaPV2FK2kdUHM5QPCUsO+NfkGYYIeAD4uiV5FjS5L+w8P+mOcyvguB3HZ9TpkHbAdzqEdKCjJHDVq57eagvBG8fhab9rzXummyLZNM4koPYQgL24xh3Lp9Yf5oYel+5UZUeoeh6UviMFwWWzwQmsOXz1iO9dsvIqdQgVtmH0n/QZc/G1mjfXNOUJl+kK/th7e87JIOqGc+rdyXEsjNUzyQR9mp4SRMfPacPysEI7diphJeVaujZ9XJ4ITcwBM+f/Jx/Nvkp3TkOxz+RLripULXm7iBHS6MRXNfiaxxAvwr6gDigJlaP5Yvi45fmNJvuVXj2CRXPsIZ8/9w71+N2YyUPP8n4hZ3TScsdRNFoVOHlQ/wGNZn//c/wf) that I know used to work, but now scaling and rotating fly off the rails exponentially. Was there a change in the API that might have been responsible? Or is this bad code? The fact that it used to work on some version of Paper over a year ago makes me think some recent improvements in paper require changing how such a rectangle scale controller might need to work.

**Comment by lehni** [comment]
I believe this is due to the same problem as outlined in my analysis here:

https://github.com/paperjs/paper.js/issues/1004#issuecomment-225866308

This would mean the new behavior is actually correct, and the code in the old example was working with a caching quirk. You can easily verify this by quickly reverting this small change in paper-full.js: f6b77b744211986ad5115c00ed371986413297bb

But in order to get this example to work again, you either need to set `item.applyMatrix` to false on all items, or handle the transformations incrementally.

I hope this helps.

**Comment by lehni** [comment]
PS: Looks like I was right here... https://github.com/paperjs/paper.js/issues/1004#issuecomment-225866882

**Comment by lehni** [comment]
Here the beginning of a conversion to working with `applyMatrix = false`. It's not perfect, but should point the way:

[Updated Sketch](http://sketch.paperjs.org/#S/pVhbb9s2FP4rjB9qKVZUJ20GzK4HrM3LgGUrkg17mPcgW7TNRSYFiXKSpf7vO7yKkig5Qf3gy+G5fDx3+WVEkz0ezUb3D5ivd6NotGap+H1ICnRIsgqXaIFelnTJ84Tvyhm6jsSPPaFfGaG8JiRPhnBpWe6SlFRA+TA1PIby43RJj3MgUmFoR/jvOSeMWmMl3u6x1MaLCkvpkhfsATuEDcky5ydnGS4SugaWa1d5iTO8Fsrv4COh2wyDEVpl2bzv/H6dZHhxmuU3VuyTjPyH02HmO8YTQTBc6wInHH8V/gxCiXNTUSmCGkfKFUJnId12gzOeAHgVl9i6E11YkvH53EjmMihdSRWshqQiSckNK1AgxAkITefw8ckwyjQAymSi8bkIHRMGCZqgWxCJITQp28Olzt3bzGsNCmlDgwapNWwyxoqgrcy5YOhqAzbQpfz5OWOr4EDwY1xCtEBIKrZaIo0o0spcPRnZ7jjFpQDWsn2BpvG1gDCNPwJGeHfkdpVIszbYDz9MNU8ubwQZ/IVl4GxIeyEyE28RKhNeFTJloJqiGsPMgXN0FanaMKrGqyxZP4wlg2A7elJMumQNJYaLCNlMsh6oU087kuJHJNJSJayyus5YiVM4FDVYk5M8z57h5gV5grNNkpW4N6mUuW46pTphpVnBE+jDJc8w3fLdDAV1/p+rSEzaETpHbZ7IaJGFCUogIui9vfU5IorhGLruTdJU+wpspHWqHe2dyz1j1jkFhvBR6TnjfdUYZE+L5EHkayqKQfeRPTvIRuD6sI4ioYTfdzQEQrV0JIIX2QRdI2eyC4WKQ7y6LHGBhXF5G8Eh6xuXmAMUedvCNLTFFL17p2gldERCt/HTYnHZIT4D0VG2YhVNy7lFKZVrSC81sjUMBGjqcca2wVjyjA0k8VJaDKaGTvGS1PwX8BNJss/9vEf1gcHFwwgoQ6dANM01DTR0KbEZGkNCqe9G6Qp0KYqoLwpRiPFTDhkdXE6jy6lhU+/+2aZLNa7TYmXEPMH2l2sPs2o09yqsp9lzcmAia3xHrCSC0i9MaIkLHlxFThdYxaoO46cIrWLO8nDgZq9ScHF1/d06rALI5bOeZB5wQTMttfL5cIXqCmxX5LBUaePmVmedpifC/hdJZTu6PJUfziCq8LifW+yewLYc2TOoMH24HA1YkSR39PR5WE8v3YqHuAZzVRypVm4bMKO3rCrxDXukAT5AyMLG5qqN1qumXgsIv8Nllcnzgv0LJmKg/YFLrrTEchRFzkqsZgrZoODMSodqOKlBIweD4lAq9iwlG4KLMi53ZMPtYBUcVkXMn3NwPgRJIx5bviWvufShOxLkfJy3EchhSFtGwr5mWnM4cxZ8UhsmHO/12VvRD8w9O5lU6vXmXmh0Ofi9Q6FrqDEezAsgdX1KaIqf0E8LdCVg9Z1/WqCPYVejB1gHnOkKXkj+YrirG8vUI3TskurB+VZ4ov/43eXHJh+6AJhTKHFZrXiRrLkn4s1+GsZqcXzf3Fb8d1Sxb13Wf9G63jsBNLUiJVFf/sqOOTaJebboXsRJbflIwtYmRLU+QzQl0+pDZo4ZNp1bE/F44bgztOLdrVavu7K8PN5eqPr69q23w54t1HYKN/WVpzxUFlrJM7TrutDkm4pSQ8fr9mB/zjUbn7TgLOaeeIpnurFt2YZXX8y0fEhYcsC/Js+wRMDDxZcdydKg2fvCzoObnji3Ao47cXxKnQlZP4DVE0Ia0F4SuGqqZ7baQvD6cfhJoqvNe6ebItk27iSg9jQAG7hGjOXj8nf3hh6T7lZlV6h6H5S2IwXB7WaDG1hz+ephz91m5RXqNFQ4hseKSZ8yF19reHPdpjzuMlPB73vvzHk1iHrguLHbYn5DCpk7P8tq79/b9BZ9wvN5Y08Ga69bmYcF2h5UaSsbr23aZprLe6GJuWbq/P3la7Ynm54zVuxT/5KrOlUk7ywxTBqd+Npwox9hn1MHhITI0XwxXbll+Y0q+4VOXsGiOfa0oD9zpwH5zZj9Q2/0fiZngdJ8x1E0WhU4eVD/Mo1mf/9z/B8=)
