### ISSUE TITLE
Group#clone matrix when applyMatrix = false

### ISSUE THREAD

**Issue by georeith** [paperjs/paper.js#1225]
When you have a `Group` with `#applyMatrix` set to `false` and call `clone()` it doesn't clone the `matrix` across.

I would expect the `matrix` to be cloned also.

[Here is a sketch to reproduce the issue](http://sketch.paperjs.org/#S/bVCxTgMxDP0VK0tb6VQVsQUxMTCx0LF3g5szveiCEzkp0Fb9d5xejwkPlv2e9N6zL4bxk4w125GKG0xjXOzr/oUCQq4gHwLBMzB9w3bAROv3GV1eWgat7M9kYfew2TSgrWsmOEXP5R88F4kjvcQQxcJCqF8ocV09tVw9DxKP6e73WufZBVMKpzcs4n8sfGDIdNdzgw+9EKvVX+Bulmz5JrgugpwDFlo+1jjaKjtxLkTWY8BzJtHERY7UQE+UphlUSR+zF8LxdlQ2dtddfwE=)

**Comment by lehni** [comment]
I completely agree. I'll look into it, shouldn't be hard to fix.

**Comment by georeith** [comment]
👍 Thanks for sorting that!
