### ISSUE TITLE
can't get one of the image tutorials work in direct javascript

### ISSUE THREAD

**Issue by mmobini** [paperjs/paper.js#1226]
Hi guys, thanks for your awesome library.

I've problem with [one of the tutorials](http://paperjs.org/tutorials/images/using-pixel-colors/) provided in paperjs website. It doesnt work when i use paperjs using direct javascript mode.

This is my code in jsfiddle website: [https://jsfiddle.net/3g1Lyd76/38/](https://jsfiddle.net/3g1Lyd76/38/)

Would you please help me overcome this issue?

(I've also tried calling view.update or view.draw but doesn't work too.)

**Comment by lehni** [comment]
You're dealing with two issues:

1. CORS
2. PaperScript's use of operator overloading.

I've fixed both here:

https://jsfiddle.net/azmcw1kw/1/

But please note that https://github.com/paperjs/paper.js/issues is a bug database, not a forum. Please ask for support on the mailing list: http://groups.google.com/group/paperjs
