### ISSUE TITLE
Canvas content disappears in Chrome when canvas is too high

### ISSUE THREAD

**Issue by bildlich** [paperjs/paper.js#1231]
Paper.js 0.10.2
Chrome 55.0.2883.95 (also, 57.0.2968.0 canary)

I have a canvas element with `resize="true"` that fills the entire window. When the window is resized in such a way that the canvas height is larger than ~640px (the limit seems to depend on the canvas width as well, it's not always 640px), the canvas content disappears. The canvas element itself remains visible.

### [Live demo](https://jsfiddle.net/ja8nwmap/1/)

HTML:

    <canvas id="paper-canvas" resize="true"></canvas>

CSS:

    #paper-canvas {
      width: 100%;
      height: 100%;
      background: #ccc;
      position: absolute;
    }

JS:

    paper.install(window);
    paper.setup(document.getElementById('paper-canvas'));
    var path = new Path();
    path.add(new Point(0,0), new Point(100,100));
    path.strokeColor = "green";
    path.strokeWidth = 2;

![canvas](https://cloud.githubusercontent.com/assets/501617/21580036/9665a5b8-cfd4-11e6-89b8-2b252b8e6dfd.gif)

**Comment by lehni** [comment]
Very strange, I cannot reproduce this, with the exact same browser versions, on macOS Sierra 10.12.2...

**Comment by bildlich** [comment]
After restarting the computer, the problem is gone. Very strange. Maybe an issue with some other graphic process. For the record, I'm running OS X 10.11.6
