### ISSUE TITLE
"Cannot read property '_path' of null" on path.unite()

### ISSUE THREAD

**Issue by iconexperience** [paperjs/paper.js#1233]
The following example throws the error "Uncaught TypeError: Cannot read property '_path' of null":

```javascript
var p = new Path({segments:[
                [274, 253],
                [274.39360933873525, 252.93741452470064, 0, 0, -0.6159287834059803, 0.8638915013756937],
                [271.7973629022481, 254.56035493761536, 1.0464052751698083, -0.17525065612978258, 0, 0],
                [275.08184882141563, 249.9554467894288, 0, 0, 0.17503510398097794, 1.0465180359346082],
                [274.39259699481335, 252.93883376712415, 0.6163491637478691, -0.8636845462953266, 0, 0],
                [273.5560469948133, 254.11108376712414]
            ], closed:true})
p.unite();
```

This occurs in <a href="https://github.com/paperjs/paper.js/blob/develop/src/path/PathItem.Boolean.js#L733">PathItem.Boolean.getIntersections()</a> if the property `_segment` of an intersection is `null`. Not sure why this happens.

I simply check for `inter._segment`, which works well so far, but of course does not explain why `_segment` can be null at all.

@lehni I will work on Paper.js during the next days and hope to contribute my remaining boolean changes/improvements. Let's finish the boolean stuff finally.

**Comment by lehni** [comment]
Interesting. There are a few things going wrong with this one...

If you log `console.log(p.getIntersections().length);` you will see different results based on scale, e.g. try:

`p.scale(10);` (3 intersections)
`p.scale(100);` (2 intersections)

Also, try `p.unite()` at those scales. It's not working...

**Comment by lehni** [comment]
I believe 2 is the correct amount of intersections, yes?

**Comment by iconexperience** [comment]
If the intersections are crossings, I think 3 is the correct number of intersections.

**Comment by lehni** [comment]
Why 3?

**Comment by lehni** [comment]
Here the important detail:

<img width="423" alt="screen shot 2017-01-02 at 14 10 07" src="https://cloud.githubusercontent.com/assets/213275/21589739/31f7736e-d0f5-11e6-8b89-da905214ee6a.png">

And if I pull it apart:

<img width="467" alt="screen shot 2017-01-02 at 14 10 52" src="https://cloud.githubusercontent.com/assets/213275/21589748/49289fb8-d0f5-11e6-8a65-384850584f5e.png">

It looks like 2 intersections to me. Of which only one should actually be a crossing!

But the curve that I pulled away may be crossing the straight line that goes down ever so lightly, twice, and only one of these is found? Oh dear...

<img width="804" alt="screen shot 2017-01-02 at 14 13 39" src="https://cloud.githubusercontent.com/assets/213275/21589777/af7662e6-d0f5-11e6-8d0b-f80dcaa12348.png">

**Comment by iconexperience** [comment]
Yes, but there is the other obvious crossing:

![image](https://cloud.githubusercontent.com/assets/2122773/21589793/d03481e8-d0f5-11e6-8ebc-3d781e466a12.png)

**Comment by lehni** [comment]
So the question is, does the curve cross that line twice? Then 3 crossings would be the right number. Otherwise one crossing, one touch.

**Comment by iconexperience** [comment]
Yes, that's what I think, too.

**Comment by lehni** [comment]
OK I was wrong about it not working. I was looking at the selection of the original path :)

Investigating...

**Comment by lehni** [comment]
This is the change that cause less intersections to be found... 7dd0b852c8560eb13c37c602e8c50e8f4f8de81d

**Comment by lehni** [comment]
So separate of the `_path` being null issue which needs fixing, I think we should look more into these imprecisions, don't you think?

**Comment by iconexperience** [comment]
I agree with the location merging that is making the difference between the different scaling ratios.

Since we are comparing curve time and distance in `CurveLocation.equals()` I am not surprised that the number of intersections is different for different scaling ratios. IMHO we should simply focus on why there is one intersection that should not be there.

**Comment by iconexperience** [comment]
The difference between the original example and the scaled example is that there is an overlap found at the original example, which is not found after scaling with a factor 100.

**Comment by iconexperience** [comment]
Hmm, for detecting overlaps we are using the old epsilon of `1e-7`, but for comparing segments in `_getIntersections()` we are using an epsilon of `1e-12`.

@lehni Do you agree that these epsilon values should be the same?

**Comment by iconexperience** [comment]
What i leaned today is that you cannot trust the browser's rendering when when using a high zoom factor. This looks like a clear crossing, so I tried to find out for quite a while why it isn't found by our algorithm:

![image](https://cloud.githubusercontent.com/assets/2122773/21595612/1b5a7e7c-d130-11e6-9756-0065079bebe3.png)

After dividing the magenta curve at the "crossing", it looks like this:

![image](https://cloud.githubusercontent.com/assets/2122773/21595632/547d6b60-d130-11e6-9bd5-38aab15ac9de.png)

As it turns out, there simply is no crossing, so the algorithm is right by not finding one. Oh dear!

**Comment by lehni** [comment]
Yeah I've seen these imprecisions with zoom levels and "long" lines. Sometimes, it helps to switch browsers. Firefox may be the most robust, perhaps using the least amount of GPU optimizations?\

Regarding the overlap tolerances, I think a lot of this has to do with what we observe in edge cases. If I use lower tolerances for overlaps, then I get more problems in edge cases. Very tricky stuff...

**Comment by iconexperience** [comment]
I remembered that you recommended using Firefox before, but in this case the result was exactly the same. I was really surprised that the rendering was so much off the real curve.

Regarding the missing crossing: After spending far too much time on this today, I think that `addCurveIntersections()` fails to find the intersection, but I am not sure if there is much we can do about this.

Anyway, we should be able to fix or at least the "Uncaught TypeError" from my original post.

**Comment by iconexperience** [comment]
More precisely, I think the missing crossing must be here:



![image](https://cloud.githubusercontent.com/assets/2122773/21596378/a497778a-d13a-11e6-89c1-8f3c60e93956.png)

**Comment by iconexperience** [comment]
You will not believe what I just found. If I set the factor in <a href="https://github.com/paperjs/paper.js/blob/b37b8cc495cae195101da22de5bf9ab96f39adca/src/path/Curve.js#L1665">Curve.addCurveIntersections()</a> that tightens the fat line from `3/4` to `3.01/4`. the missing intersection is found!

I have to stop now for today, but I wanted the share this discovery first.

**Comment by lehni** [comment]
b743f456b3bcb615188922a1a837c29330436706 was all it took to make that go away. But I keep the issue open for these other discussions around the intersections.

**Comment by iconexperience** [comment]
Unfortunately it turned out that my euphoria was a bit premature. I tested the path with a scale factor of 100. The missing crossing is found in some cases, but the fat line clipping algorithm turned out to be very fragile again. Here are the settings for the narrowing factor and the result ("yes" means third crossing found).

```
0.75      no
0.75001   yes
0.75002   no
0.75003   no
0.75004   no
0.75005   yes
0.75006   no
0.7525    yes
0.76      no
0.8       yes
```

Simply increasing the narrowing factor may do more harm than good. I suggest that we close this issue and either open a new one for the intersection or (what I prefer) wait and see if real life cases occur that need improvement of the fat line clipping.

**Comment by lehni** [comment]
I tend to agree... I think we'll always see such edge cases, and I am fine with some. Even Illustrator struggles with stuff like this.

**Comment by iconexperience** [comment]
Alright, let's close this as the original problem has been solved. I will continue to keep an eye on the fat line clipping. Unfortunately I had a scedule change and cannot work on Paper.js today (may a little bit), but the next days will be fully dedicated to the remaining boolean issues.

**Comment by lehni** [comment]
One more thing: I can't decide if ede9ef26235640d4f14a7a7c54a450d5a1dcf3af was right, or not. With it back, I get 4 intersections in most cases now, so that's probably also wrong?

**Comment by iconexperience** [comment]
I do not think this is "wrong". With the change the curve endpoints count as intersections, because the tolerance is higher. Their distance to the other curve is obviously between 1e-7 and 1e-12. If their distance was smaller than 1e-12, they would be found without the reversion.

In the fork of Paper.js that I am using I reverted this some time ago, but unfortunately I do not remember why.

**Comment by lehni** [comment]
@iconexperience would it be easy for you to deactivate those lines in your code and find out what situations they addressed? Would be great to identify cases where this makes a difference...

**Comment by iconexperience** [comment]
While looking at the code of `getTimeOf()` and had an idea. In some special cases (curves with loops, curves shaped like a narrow 'V') it can happen that two (or even three) points on the curve are close to the specified point. In these cases we should use the point on the curve that has the smallest distance. 
Here is my proposal:

```javascript
    getTimeOf: function(v, point) {
        // Before solving cubics, compare the beginning and end of the curve
        // with zero epsilon:
        var p1 = new Point(v[0], v[1]),
            p2 = new Point(v[6], v[7]),
            epsilon = /*#=*/Numerical.EPSILON,
            geomEpsilon = /*#=*/Numerical.GEOMETRIC_EPSILON,
            t = point.isClose(p1, epsilon) ? 0
              : point.isClose(p2, epsilon) ? 1
              : null;
        if (t === null) {
            // Solve the cubic for both x- and y-coordinates and consider all
            // solutions, testing with the larger / looser geometric epsilon.
            var coords = [point.x, point.y],
                roots = [],
                distMin = geomEpsilon;
            for (var c = 0; c < 2; c++) {
                var count = Curve.solveCubic(v, c, coords[c], roots, 0, 1);
                for (var i = 0; i < count; i++) {
                    var u = roots[i];
                    var dist = point.getDistance(Curve.getPoint(v, u));
                    if (dist <= distMin) {
                        // in case there are more than one location on the curve close to the specified point,
                        // we are selecting the one with the shortest distance to the point.
                        t = u;
                        distMin = dist;
                    }
                }
            }
            if (t !== null)
                return t;
        }
        // Since we're comparing with geometric epsilon for any other t along
        // the curve, do so as well now for the beginning and end of the curve.
        return point.isClose(p1, geomEpsilon) ? 0
             : point.isClose(p2, geomEpsilon) ? 1
             : null;
    },
```

**Comment by lehni** [comment]
That's a good point! There is also the case where a path could actually have two solutions, with self-intersection, but we don't really need to know both solutions elsewhere in the code, so I didn't take that into account...

Does using this improve things in your code, or is it just a general idea?

**Comment by lehni** [comment]
@iconexperience I meant that we really should have a `getTimesOf()` method that returns multiple solutions if they exist to be correct... I wrote the code, but then we never had any use for it, so I didn't use it.

**Comment by iconexperience** [comment]
That's just a general idea, but I am sure there can be cases where the original code will cause problems. Another advantage is that the new code will give more precise results in many cases. Here is why:

![image](https://cloud.githubusercontent.com/assets/2122773/22021173/086ca6b8-dcbc-11e6-887b-f940f2e3e119.png)

The grey circle has the radius of `GEOMETRICAL_EPSILON`, therefore we will find two solutions, where the solution when testing in y-direction is more precise. In the new code we will always find the better of the two solutions, in the current code we find the solution which comes first.

On the other hand there will be a performance impact, but I do not this `getTimeOf()` gets called very often, so this should not be noticable.

**Comment by iconexperience** [comment]
Regarding you idea about returning multiple solutions: In my illustration above there are already two solutions. How would you distinguish between that case and two "really different" solutions?

**Comment by lehni** [comment]
@iconexperience I am not sure this is really necessary though? I mean technically, neither of the two found solution is the closest one, the projection from the blue point onto the curve would be the closest solution (= getNearestPoint()). But probably we're fine with just using the first that's close enough?

**Comment by lehni** [comment]
@iconexperience as long as implementing what you describe in https://github.com/paperjs/paper.js/issues/1233#issuecomment-273142058 has no measurable benefit, I think I prefer keeping things the way they are. What do you think?
