### ISSUE TITLE
right way of resizing a raster

### ISSUE THREAD

**Issue by celevra** [paperjs/paper.js#1234]
Hi,

i'm loading an image and scale it down.
Later, if the window gets resized, i will scale it up or down to keep the relationship.
If i scale it up the image gets blurred, i think i have to call a "redraw" or something. But i can't find anything in the docu or via google. 
Here is a sketch of the Problem
http://sketch.paperjs.org/#S/dVHBasMwDP0V4UsTCHEp7JKxn9iOyw6uo8UmrhxsJWYt/ffZ25oxygwySE967wldBKkTik68TMjaiEZoP5R8VQGW4OAJemGY59hJmVJqnfU0IVJLyJIxchvXsRePfeiphJSzUxpBEdiTGrHUCtf5w1kaMGRCwgTPKjKGKis0q8XUaqSc1xvNrb31VO2cV8OugfeFNGf5qoZL6YH8pIz2jGD5VtgGDdrRcJZ72N9hyQ5s/kC/fE5lI8U+rtkTODshpDzmEwT8EvNa+yXEBqKHqJVDYIPf28Iy/yt22N8b2Uz+gNe6/PkKx4Bqmr0ljqJ7fbt+Ag==

thank you for guiding me in the right direction

regards

**Comment by lehni** [comment]
This is a bug database. Please send requests for support to the mailing list instead: http://groups.google.com/group/paperjs

I can't offer a full answer here right now, but when you load images with Raster, then they get rasterized. To use SVG data as vector graphics, use `project.importSVG()` instead.
