### ISSUE TITLE
Negative scaling is applied inversely in some cases

### ISSUE THREAD

**Issue by nicholaswmin** [paperjs/paper.js#1236]
When `scaling` *negatively* a Predefined Shape, sometimes the scaling is applied inversely thus the Shape is mirrored but facing the opposite direction.

![Animation showing the bug described above](https://cloud.githubusercontent.com/assets/3926463/21727084/31a24c08-d448-11e6-96e8-6f3c1ddf0bd9.gif)

Here's a chopped down version of the code that illustrates this bug

```javascript
var toolShape = new paper.Tool();

var path;

toolShape.onMouseDown = function (event) {
    path = new Path.RegularPolygon(event.point, 3, 2);
    path.strokeColor = "#000";
}

toolShape.onMouseDrag = function (event) {
    var vector = event.point.subtract(event.downPoint);

    var relW = event.point.x - path.bounds.center.x;
    var relH = event.point.y - path.bounds.center.y;
    var factorW = relW / (path.bounds.width / 2);
    var factorH = relH / (path.bounds.height / 2);
    
    path.scale(factorW, factorH);
}
```

And here's a [Sketch][1] for it.

[1]:http://sketch.paperjs.org/#S/fZIxb4MwEIX/iuUuIFEHtVuiTu2QpRJqKnUoHRxzARR6h4wJiaL8954hNDSKahYb33fv3ZOPEvU3yLlcbcGZQkbSUObPO22FI6pWha5BPAmETtS8teqd/wbhIsUUfVGtXdEffqsV4Su1DbxQh0xuWjSuJBQB7ABdKI4pCl4ePDdOeKveIG8rbROqDjnhUKxqKtFF4jESD15y5FTjLG3hmSqy3COVd3Ecp5IrTretWJ3/Y8XPsQPj+mYTYdW0a2e1cWc3GU+U+Ith/BG1UH1cgXtxPxhdU4tZowxfcXb7xR9qeUUdblOHCbXR3qaX61VnIpgCXZlxqLNLWBdkOSDLa6SAMi/clJnGbHQFwVkzGjuFY87+4yeztqC3/QSNnH9+nX4A

**Comment by lehni** [comment]
I don't think that's a bug. Since your relH is signed, and bounds.height will always be a positive value, you'll end up with a negative factorH when you flip your shape. Applying a negative vertical scale factor means the shape will flip vertically every time you scale it.

**Comment by lehni** [comment]
1. you can simplify the onMouseDrag event a lot by using vectors instead of separate values:

```js
toolShape.onMouseDrag = function (event) {
    var rel = event.point - path.position;
    var factor = rel / (path.bounds.size / 2);
    path.scale(factor);
}
```

**Comment by nicholaswmin** [comment]
@lehni Flipping the shape is intended behavior - What's the reason for the flickering though?

**Comment by lehni** [comment]
Each time you scale with a negative value, you flip. So on each frame that you scale with a negative value, you flip in this direction. That's how it works:

100 * -1 = -100
-100 * -1 = 100

etc.

**Comment by nicholaswmin** [comment]
Yikes, the first reply completely flew past me - Silly mistake, thanks
