### ISSUE TITLE
Gradients within PointText

### ISSUE THREAD

**Issue by hapticdata** [paperjs/paper.js#1238]
I've been working a lot with Gradients in all sorts of Items and I had a lot of trouble getting them to display correctly with `PointText`. It appears that with `PointText` exclusively the position of the element must be subtracted from the provided bounds, here is the snippet I now have in my code that seems to be solving the issue:

```js
    //property is always 'fillColor' or 'strokeColor'
    if(path._class === 'PointText'){
      path[property].setOrigin(path[property].origin.subtract(path.position));
      path[property].setDestination(path[property].destination.subtract(path.position));
    }
```

here is a standalone test that I ran on [the Gradient reference page](http://paperjs.org/reference/gradient/). Notice that if you don't include the subtraction it will be wrong and as you move the position of the `PointText` around it will map to different areas of the Gradient:
```js
// Create a rectangle shaped path between
// the topLeft and bottomRight points:
var path = new paper.PointText({
    content: "abcdefghijklmnop",
    justification: 'left',
    position: new paper.Point(50, 40),
    fontSize: 48
});
var fillColor = {
    gradient: {
        stops: ['yellow', 'red', 'blue']
    },
    origin: path.bounds.topCenter.subtract(path.position),
    destination: path.bounds.bottomCenter.subtract(path.position)
}

path.fillColor = fillColor;
```

If I am doing something wrong please let me know. Thanks for all of your hard work, Paper.js is really great!

**Comment by dexterial** [comment]
it may be cause by the same factor as in #1250 
"i narrowed down the issue to text.applyMatrix = True not having any effect compared to text.applyMatrix = False, so the original matrix created is never updated."

**Comment by dexterial** [comment]
ok, i see that it is intentionaly disabled or not implemented in https://github.com/paperjs/paper.js/blob/6e7fe67a8ddc93d41b620ef8f02a503d2920769b/src/text/TextItem.js#L26
Is there a particular reason on why this is the case ?

**Comment by lehni** [comment]
@dexterial as explained in the other issue: `applyMatrix = true` only makes sense on items where transformations can be baked into content, so `Path`, `CompoundPath`, `Group` and `Layer`. All other items need to store the transformations in the matrix and cannot pass them on to the content.

**Comment by lehni** [comment]
But the observation is correct: The problem occurs with all these items, e.g.:

[Sketch with Shape](http://sketch.paperjs.org/#S/XVHBboMwDP0VKxc2jbU9Vpl66rWn9ggcAnEhauqg4BVNFf++ZNAV+i6xnefnF+cuSF1RSHG6IFeNSEXldMxvygO79oBnhh3cDParConRwydk200K203xlVOklY7ZXY+mbl6pH3NqTus17D0qRlDgsWJFtUXoGtWihlZxAyVyjzhSucF/B4r0YkzrDHEnx/l/nTsg7OEUtVbHh/bbPScImGTkI0jH8kxRzpPp+mys3TvrvIRJJ6L2SpvwvEUxogvinYQs+UFrXZ+kkHjU8SjtNybFkz2kz9h5Uxt6dRahsWNDio2jhbuRMeQ0vIethh8rw04v40aEzIrhFw==)

**Comment by lehni** [comment]
The reason is that these shapes / text items are always drawn at 0, 0, but the matrix moves them to the given position.
