### ISSUE TITLE
New Boolean Operations Edge Case

### ISSUE THREAD

**Issue by lehni** [paperjs/paper.js#1239]
As reported by @iconexperience here: https://github.com/paperjs/paper.js/issues/1073#issuecomment-270866689

This works in v0.10.2 but doesn't with the current `develop` branch:

[Sketch](http://sketch.paperjs.org/#S/jVRdb5swFP0rFi8QiVq2wXxV0x6iPUzaw6Q+hjw45IawUDuySaup6n+fbUgL66rFQsTce+7XOVd5CaR4hKAKHk4wNMcgDhq1d99PQqMzRV+QhGf0UwzH6KWWyB4D7SPIwVRosylKgksaoxxzFiPin4LjlJTvJ49RmWLCtjHaUMLSGCWc4rzw4DvKckySGTzzdmem6cxcuHBXLitjlJUZZoUvxecgbhO6Wh/zER+eJji19TOe+PCx35xjRmbHJSkYzrJ5EhdeZmTRO6X2yqcx7D1LrkUya+UEczofwFci+bKSKzTvtpy63cYj2U2vDOwrNOgLTCYzaHWCteqVrlC46y8QLjwPjeg72VboIHoDtXxd3dfSq8n+o+Y0oFXyjmDCZ12lPE3GgbN8yfeV26uyb2vwSQond/6Zlk6+BJfFjCN2g3zLRZnko7Mk9HY+lRayvYXRWp61+gXNgEUzdE/wQ/wGjY2FQkQw4571Dp5xY+kFban/F/6sTDd0SvqETqTOgY1DU9zC8N1/2iiLMdGZuayNvaoecK/aaITjHmQ7HGMULvChQ0+Ig9LfRHOMDhfpnWPkCk1rcF0LvO50YyeYzJ4y3381dmYbtr/xu1eLfXex25PMbAtGx7DOrLUyxrIYrdBXFGrYh8jS3WoAGX6I/Ztx5/GsT9Q7pjRMNF1kN8DEjTXiQ9f3vrh114FudyJi3O6Wf7mlwcmqDu7tX91Ogzj5iUxQbbavfwA=)

If the scale is changed, it works expected. The difference is in the amount of found intersections.

Here at scale 0.3 where it works. 7 Intersections are found, of which 2 are not crossing:

<img width="142" alt="screen shot 2017-01-15 at 10 54 28" src="https://cloud.githubusercontent.com/assets/213275/21961687/2d2c0c7a-db11-11e6-9367-0b1f76c84ade.png">

Here at scale 0.25 where it does not work.Only 6 intersections are found, of which 2 are not crossing:

<img width="126" alt="screen shot 2017-01-15 at 10 55 39" src="https://cloud.githubusercontent.com/assets/213275/21961688/3088d826-db11-11e6-90ed-4fb6dceca1d4.png">

The intersection at the top left of the orange shape is clearly missing. The question is, why?

**Comment by lehni** [comment]
I tracked down the change in behavior to this commit: 09785a504b575cc6a053d56ba8d5a9bbb5eb9f52

So we're in epsilon edge case land again...

I had a really interesting conversation with @hkrish about a new project he is working on, for which he developed a better approach to boolean operations that can deal with such edge cases much better. We may never be able to solve all these edge cases, so maybe it is time to start thinking about another complete overhaul, based on Hari's findings... I'm not keen on spending even more time on Boolean though :/

**Comment by lehni** [comment]
Ok, so this isn't actually a bug in the boolean code, but in fat-line clipping. If I increase the `CLIPPING_EPSILON` to `1e-9`, then it works again. @hkrish also told me that he's not using fat-line clipping in his code, but approximates cubic bezier curves with one to multiple quadratic ones, staying within an allowed maximum error, of which he then finds the intersections with a numerically precise solver for quintic polynomial that he developed. 

I thin we've tweaked the fat-line clipping approach enough to have good reliability and performance, and should be able to deal with additional edge cases by further tweaking the values for epsilon and maximum recursion...

**Comment by iconexperience** [comment]
@lehni Although the fat line clipping has become really good, it still seems to be a weak spot, especially when handling edge cases for curve pairs that have an almost identical section. Ideally this section would be found as an overlap, but we just do not have an algorithm to find these kinds of overlaps.

Here is another curve pair that causes trouble. No intersections are found, but if you zoom in, there clearly must be an intersection somewhere.

```
var p = new paper.Path({segments:[
    [105.90335300308652, 982.4742993619318, 0, 0, -5.719405684117135, -2.0655137032616153],
    [83.96029586535639, 968.7694724373825, 8.925021866665332, 8.925021866665304],
    ], closed:false})
var p2 = new paper.Path({segments:[
    [105.94620455298124, 982.4898815570057, 0, 0, -0.020948612124328747, -0.0076072969939673385],
    [105.88277039383794, 982.46684512612, 0.021270323368810296, 0.007725020850102737, 0, 0],
    ], closed:false})

p.strokeColor = "green";
p.strokeScaling = false;
p2.strokeColor = "red";
p2.strokeScaling = false;

console.log(p.getIntersections(p2));
```
<a href="http://sketch.paperjs.org/#S/jVKxbuMwDP0Vw1MC+ASKFCUqh5s6dSvQMc7gOqobxJUN27gbiv576TTtDUUPR2jRe+Sj3oNeytw8p3JX3p/T0j6VVdkOx/X+u5mKsfhV5PSnGJsxTeauWZ42L3PqnlNe5t2+zoXW3gKbCERMAATiGasiChoXHMZI3kayUhVwOT/YBBsdsBdnbbDEiqEBz2wpAKG33jIdqqu4kIkeMLLqEnuKqu3FBB9dQEeBBFVBTEQGtOK1mAi/QOA+JA9V0fbDnI67x6af0+u2zher+N9enUdwzBjFort6lShimQMAh0+vYAAhOvEWtZNQggvvMAQPAaPXfKIPRMKfjtcVIhg0jEhCIX6s8BoZWw1I3a3KFte8iLxu1oT8BYUQVtsgDAoGuj7mH+brPJp5mYZzuhn6YdIU6rKbUsp1+fMvd982/Sl3yl4GVwa/jE3p+D6E307VuR3yPPTJ9EO3GU2Xltu8pGlO7XJSZjPidqt9+g8fptScx+Gk+Ze7/eH1DQ==">Here is the Sketch</a>

Interestingly the intersection is found if the fat line widened very slightly by `Numerical.MACHINE_EPSILON` (`= 1.12e-16`). I will  have to dig further to find out what is happening.

Regarding the new boolean algorithm: I think we are fine with the current one. The new edge cases that keep popping up are really rare and we even manage to solve some of them. And for my new edge case mentioned above I am not sure how any algorithm would be able to handle this. But having said that, if the new algorithm really is more robust, it will be very welcome.

Finally, there still is the possibility to add a fallback in the `tracePaths()` function, that will close paths even if there is no other way to find a result. This may be better than having no result at all (although I am not sure about this).

**Comment by lehni** [comment]
@iconexperience I think we should live with the current implementation for now and try to make it as good as we can. We've come a long way, and implementing the new one from scratch may be a huge undertaking, for which neither of us really has the time currently.

If you still have known edge cases that fail, please create issues for them. I'm interested to see them.

Also, there are a bunch of pending issues where I am waiting on feedback from you, you're probably aware. It would be good to wrap these up, if you have a moment:

https://github.com/paperjs/paper.js/issues/1073#issuecomment-270902663
https://github.com/paperjs/paper.js/issues/1113#issuecomment-271152491
https://github.com/paperjs/paper.js/issues/1233#issuecomment-271153706

**Comment by lehni** [comment]
@iconexperience could you explain how exactly you widen the fat-line by `Numerical.MACHINE_EPSILON`?

**Comment by iconexperience** [comment]
The values `dMin` and `dMax` are the distances from the line that runs through the curve`s end points. I simply changed their calculations to this:

```javascript
  dMin = Math.min(0, factor * Math.min(d1, d2) - Numerical.EPSILON),
  dMax = Math.max(0, factor * Math.max(d1, d2) + Numerical.EPSILON),
```

But I think this is the wrong way. I may have found something better.

**Comment by iconexperience** [comment]
Here is my new approach: If two curves are almost identical, the current fat line clipping will only give minimal progress with each recursion, because the fat lines for the remaining curve fragments become more or less identical. Here is a case where the clipping will give no progress at all, because both curves have the same fat line (the yellow area is the fat line):

![image](https://cloud.githubusercontent.com/assets/2122773/22301023/be3488d0-e329-11e6-9184-b49ba49ecca9.png)

In the Pdf <a href="http://nishitalab.org/user/nis/cdrom/cad/CAGD90Curve.pdf">Curve intersection using Bézier clipping by Sederberg/Nishita</a> there is one remarkable sentence, which is:

> However, it is clear that any pair of parallel lines which bound the curve can serve as a fat line.

If you look at the example above, you can find several fat lines that will actually yields in some progress. Here is one of them:

![image](https://cloud.githubusercontent.com/assets/2122773/22301291/d14d0f36-e32a-11e6-97c3-4b46bc6c0ffb.png)

Although the line is much "fatter", part of the blue curve is not inside the green curve's fat line, so the green curve can be clipped.

The great thing is that this fat line is incredibly easy to construct. We have the end point and the control point and only need the distance of the other end point and control point.

I have implemented this and it results only in one failing test case. It's <a href="http://sketch.paperjs.org/#S/lVNNb9QwEP0rVi4FyR55xh5/tOLEGQmpR5ZDcE1b7ZJU2RVIIP474ybZjUCqSg7JfLx5M/Ps/OqG/lvtrrvbfT2Vh053Zbxr/vd+Uk/96QHVOzXUH+qj2G+uPjifIafgvbbFYCZxbCRtlblkkCNYS8zb4Gw5isVqx2AppKgogcsOnQ4OPKnn92yXFSPUc9is4NWfcVYbJAfWI3qF1gJaEkJDEkQv/dRstRkuwf+hP097hixJZbbQn1dvb3bTbliFoxeE23RfOM7dzVaE10nFGYhzYGFDTBByYyYCjuIq5CSNvZdKCy5y8oUY2DMnLXLkyFl2ZggxRm5lISVWKYPMilF0geQjh9KwIXOWSCsnrxo2Y0giwFKuVrQ2K0FpCxHaiNrIoLJBuxfIsle27Uyyh0hyelLrGWJCuwmuoip51u/FWOznawrH0zTu6/vxME6i/K6b6t2uu/k7f1v6w+NwL4iv/eFYz3n6p/5+qnXYMNALDMsw8vd8mWq/fxofh9Oxu/70+fcf">this one</a>, where the new code finds four intersections instead of two. But I am not even sure which result is correct.

**Comment by lehni** [comment]
Very interesting! How close are the 4 intersections to each other? Are they pairs of almost identical ones?

**Comment by iconexperience** [comment]
I would have to check, because the tests do not revela that information. But I found that the whole fat line clipping is really fragile. If I raise one paramter a little bit, one or more tests fail. If I raise it more, it can happen that the same tests pass again. Raising the parameter further suddenly results in another failing test. 

For example with my new approach, if I change the split threshold (the minimum progress to not split) from 0.8 to 0.9, no tests fail anymore. But if I do the same for the current algorithm I get several failed tests. It all seems to be a matter of sheer luck whether we pass all test cases.

**Comment by iconexperience** [comment]
But on the bright side I have a bunch of ideas that actually work.

One type of problematic curve pairs curves that  share one end point and have the same slope at the connecting point. This happens quite often for adjacent curves on paths. If the intersection algorithm processes these kind of curves it takes a lot of time in closing in on the common end point, and if everything runs well, it will report this point as an intersection. But we could have found the intersection simply by comparing the end points. Additionally shared end points are already detected in `_getIntersections()`. So all the effort is in vain.

Therefore I suggest this simple procedure at the first recursion in `addCurveIntersections()`:

```javascript
    if (recursion == 1) {
      // special shortcut for adjacent curves. These curves can be the most time consuming
      // for fat line clipping, so we try to filter them.
      if (v1[0] == v2[6] && v1[1] == v2[7]) {
        tMin = Numerical.CURVETIME_EPSILON;
        v1 = Curve.subdivide(v1, tMin)[1];
      } else if (v1[6] == v2[0] && v1[7] == v2[1]) {
        tMax = 1 - Numerical.CURVETIME_EPSILON;
        v1 = Curve.subdivide(v1, tMax)[0];
      }
    }
```

This does not cause any tests to fail, but improves performance dramatically for adjacent curves in paths.

**Comment by lehni** [comment]
If you provide the code, I could look into these failing tests for you to figure out if it's the test that is wrong, or the algorithm : )

**Comment by iconexperience** [comment]
Here we go, the changes are actually minimal:

```javascript
      function addCurveIntersections(v1, v2, c1, c2, locations, param, tMin, tMax,
            uMin, uMax, flip, recursion, calls) {
        // Avoid deeper recursion, by counting the total amount of recursions,
        // as well as the total amount of calls, to avoid massive call-trees as
        // suggested by @iconexperience in #904#issuecomment-225283430.
        // See also: #565 #899 #1074
        if (++recursion >= 48 || ++calls > 4096)
            return calls;
        
        // Fatline types:
        // 0 - parallel to line through end points
        // 1 - parallel to handle 1
        // 2 - parallel to handle 2
        // Start with the standard fat line for the first few recursions. Then switch to the alternate handle fat lines.
        // Parameters for determining the fatline type were picked manually after intensive testing with path offsetting the bear icon (M-Collection).
        var fatLineType = recursion < 8 ? 0 : 1 + (recursion % 2);
        var q0x = fatLineType == 2 ? v2[4] : v2[0],
            q0y = fatLineType == 2 ? v2[5] : v2[1],
            q3x = fatLineType == 1 ? v2[2] : v2[6],
            q3y = fatLineType == 1 ? v2[3] : v2[7];
        if (q0x == q3x && q0y == q3y) {
            q3x += q3y - q0y;
            q3y += q0x - q3x;
        }

        // Use an epsilon smaller than CURVETIME_EPSILON to compare curve-time
        // parameters in fat-line clipping code.
        var fatLineEpsilon = 1e-9,
            // Let P be the first curve and Q be the second
            //q0x = v2[0], q0y = v2[1], q3x = v2[6], q3y = v2[7],
            getSignedDistance = Line.getSignedDistance,
            // Calculate the fat-line L for Q is the baseline l and two
            // offsets which completely encloses the curve P.
            d1 = getSignedDistance(q0x, q0y, q3x, q3y, fatLineType == 1 ? v2[6] : v2[2], fatLineType == 1 ? v2[7] : v2[3]),
            d2 = getSignedDistance(q0x, q0y, q3x, q3y, fatLineType == 2 ? v2[0] : v2[4], fatLineType == 2 ? v2[1] : v2[5]),
            factor = fatLineType ? 1 :  d1 * d2 > 0 ? 3 / 4 : 4 / 9,
            dMin = factor * Math.min(0, d1, d2),
            dMax = factor * Math.max(0, d1, d2),
            // Calculate non-parametric bezier curve D(ti, di(t)):
            // - di(t) is the distance of P from baseline l of the fat-line
            // - ti is equally spaced in [0, 1]
            dp0 = getSignedDistance(q0x, q0y, q3x, q3y, v1[0], v1[1]),
            dp1 = getSignedDistance(q0x, q0y, q3x, q3y, v1[2], v1[3]),
            dp2 = getSignedDistance(q0x, q0y, q3x, q3y, v1[4], v1[5]),
            dp3 = getSignedDistance(q0x, q0y, q3x, q3y, v1[6], v1[7]),
            // Get the top and bottom parts of the convex-hull
            hull = getConvexHull(dp0, dp1, dp2, dp3),
            top = hull[0],
            bottom = hull[1],
            tMinClip,
            tMaxClip;
        // Stop iteration if all points and control points are collinear.
        if (/*d1 === 0 && d2 === 0
                && dp0 === 0 && dp1 === 0 && dp2 === 0 && dp3 === 0
            // Clip convex-hull with dMin and dMax, taking into account that
            // there will be no intersections if one of the results is null.
            ||*/ (tMinClip = clipConvexHull(top, bottom, dMin, dMax)) == null
            || (tMaxClip = clipConvexHull(top.reverse(), bottom.reverse(),
                dMin, dMax)) == null)
            return calls;
        tMinClip = Math.max(0, tMinClip);
        tMaxClip = Math.min(1, tMaxClip);
        // tMin and tMax are within the range (0, 1). Project it back to the
        // original parameter range for v2.
        var tMinNew = tMin + (tMax - tMin) * tMinClip,
            tMaxNew = tMin + (tMax - tMin) * tMaxClip;
        if (Math.max(uMax - uMin, tMaxNew - tMinNew) < fatLineEpsilon) {
            // We have isolated the intersection with sufficient precision
            var t = (tMinNew + tMaxNew) / 2,
                u = (uMin + uMax) / 2;
            // As v1 and v2 were clipped, reset them again to the original
            // curve values to match the parameter space of t1 and t2:
            v1 = c1.getValues();
            v2 = c2.getValues();
            addLocation(locations, param,
                    flip ? v2 : v1, flip ? c2 : c1, flip ? u : t, null,
                    flip ? v1 : v2, flip ? c1 : c2, flip ? t : u, null);
        } else {
            // Apply the result of the clipping to curve 1:
            v1 = Curve.getPart(v1, tMinClip, tMaxClip);
            if (tMaxClip - tMinClip > 0.9) {
                // Subdivide the curve which has converged the least.
                if (tMaxNew - tMinNew > uMax - uMin) {
                    var parts = Curve.subdivide(v1, 0.5),
                        t = (tMinNew + tMaxNew) / 2;
                    calls = addCurveIntersections(
                            v2, parts[0], c2, c1, locations, param,
                            uMin, uMax, tMinNew, t, !flip, recursion, calls);
                    calls = addCurveIntersections(
                            v2, parts[1], c2, c1, locations, param,
                            uMin, uMax, t, tMaxNew, !flip, recursion, calls);
                } else {
                    var parts = Curve.subdivide(v2, 0.5),
                        u = (uMin + uMax) / 2;
                    calls = addCurveIntersections(
                            parts[0], v1, c2, c1, locations, param,
                            uMin, u, tMinNew, tMaxNew, !flip, recursion, calls);
                    calls = addCurveIntersections(
                            parts[1], v1, c2, c1, locations, param,
                            u, uMax, tMinNew, tMaxNew, !flip, recursion, calls);
                }
            } else { // Iterate
                if (uMax - uMin >= fatLineEpsilon) {
                    calls = addCurveIntersections(
                        v2, v1, c2, c1, locations, param,
                        uMin, uMax, tMinNew, tMaxNew, !flip, recursion, calls);
                } else {
                    // The interval on the other curve is already tight enough,
                    // therefore we keep iterating on the same curve.
                    calls = addCurveIntersections(
                        v1, v2, c1, c2, locations, param,
                        tMinNew, tMaxNew, uMin, uMax, flip, recursion, calls);
                }
            }
        }
        return calls;
    }
```

**Comment by iconexperience** [comment]
I just noticed that this part of the code does not make any sense at all:

```javascript
        if (q0x == q3x && q0y == q3y) {
            q3x += q3y - q0y;
            q3y += q0x - q3x;
        }
```

It is supposed to give the line a meaningful direction if the start and the end point of the line are identical.

**Comment by lehni** [comment]
Ok, so the main cause of these failing tests is the overlapping circles test:

```js
var path1 = new Path.Circle(new Point(50, 50), 50);
var path2 = new Path.Circle(new Point(100, 100), 50);
path1.strokeColor = 'red'
path2.strokeColor = 'green'
path1.getIntersections(path2).forEach(function(inter) {
    console.log(inter);
});
```
For some reason, it finds one intersection 9 times now, and somehow doesn't merge it:
```
{ point: { x: 100, y: 50 }, index: 2, time: 0 }
{ point: { x: 100, y: 50 }, index: 2, time: 0 }
{ point: { x: 100, y: 50 }, index: 2, time: 0 }
{ point: { x: 100, y: 50 }, index: 2, time: 0 }
{ point: { x: 100, y: 50 }, index: 2, time: 0 }
{ point: { x: 100, y: 50 }, index: 2, time: 0 }
{ point: { x: 100, y: 50 }, index: 2, time: 0 }
{ point: { x: 100, y: 50 }, index: 2, time: 0 }
{ point: { x: 100, y: 50 }, index: 2, time: 0 }
{ point: { x: 50, y: 100 }, index: 3, time: 0 }
{ point: { x: 100, y: 50 }, index: 2, time: 0 }
{ point: { x: 100, y: 50 }, index: 2, time: 0 }
{ point: { x: 100, y: 50 }, index: 2, time: 0 }
{ point: { x: 100, y: 50 }, index: 2, time: 0 }
{ point: { x: 100, y: 50 }, index: 2, time: 0 }
{ point: { x: 100, y: 50 }, index: 2, time: 0 }
{ point: { x: 100, y: 50 }, index: 2, time: 0 }
{ point: { x: 100, y: 50 }, index: 2, time: 0 }
{ point: { x: 100, y: 50 }, index: 2, time: 0 }
{ point: { x: 50, y: 100 }, index: 3, time: 0 }
```

I will investigate.

**Comment by lehni** [comment]
So the times aren't exactly 0, that's `toString()` rounding them to 5 fractional digits:

```js
var inters = path1.getIntersections(path2);
inters.forEach(function(inter) {
    console.log(inter);
});
console.log(inters[0].time - inters[1].time);
console.log(inters[0].time - inters[2].time);
```
Output:
```js
-1.4519108203386723e-9
-3.3877919141235685e-9
```
And:
```js
fatLineEpsilon = 1e-9
```

So we get multiple solutions that are slightly separate from each other. Why?

**Comment by lehni** [comment]
@iconexperience do you have any suggestion as to why with your change, so many near identical solutions are found now? Is it simply a question of adjusting fatLineEpsilon accordingly?

**Comment by lehni** [comment]
@iconexperience I've been testing your suggestion in https://github.com/paperjs/paper.js/issues/1239#issuecomment-275223892, and while it does sound like it's making sense, it unfortunately causes issues with edge cases, e.g. #904 where only of the two expected intersections is found within the valid range after the change...

**Comment by lehni** [comment]
@iconexperience I just landed a bunch of commits that has again largely improved boolean operations in many edge cases with my local offsetting code. Right now I am unable to produce any issues with it. This commit here has also lead to some nice performance improvements: d204175d3968d2672651d98c21b163c990cbd689

Curious to hear your thoughts!

**Comment by iconexperience** [comment]
@lehni I just took a look at https://github.com/paperjs/paper.js/commit/d204175d3968d2672651d98c21b163c990cbd689 . 

The change to `addCurveIntersections()` is quite a thing. I tried to implement something similar previously and failed at least twice. So far I do not see any new failing cases in our application (and that means quite a lot). 

I will investigate a bit further. It obviously works, but also I want to see if the performance changed.

**Comment by lehni** [comment]
Doing things this way does solve a few issues for me, so I do think it works better, with better performance.

While I have your attention: I am still waiting on feedback from you regarding the changes I made to the windings code, outline here onwards:

https://github.com/paperjs/paper.js/issues/1073#issuecomment-270888992

More importantly here onwards:

https://github.com/paperjs/paper.js/issues/1073#issuecomment-270897288

Could you tell me if those changes work for you so I can close that issue? Thanks!

**Comment by iconexperience** [comment]
I have to look further into this, but performance may have become worse in some cases.Here is an example that is surprisingly slow:

```
var p1 = new paper.Path({segments:[[483.2, 512, 0, 0, 19.052999999999997, 0], [512, 540.8, 0, -14.399999999999977, 0, 14.400000000000091], [483.2, 569.5999999999999, 19.052999999999997, 0, 0, 0], [483.2, 713.5999999999999, 0, 0, 19.052999999999997, 0], [512, 742.4000000000001, 0, -14.400000000000091, 0, 14.399999999999864], [483.2, 771.2, 19.052999999999997, 0, 0, 0], [483.2, 915.2, 0, 0, 19.052999999999997, 0], [512, 944, 0, -14.400000000000091, 0, 14.400000000000091], [483.2, 972.8, 19.052999999999997, 0, 0, 0], [137.6, 512, -18.927000000000007, 0, 0, 0]], closed:true})
var p2 = new paper.Path({segments:[[886.4000000000001, 512, 0, 0, 19.052999999999884, 0], [540.8, 972.8, 0, 0, -18.926999999999907, 0], [512, 944, 0, 14.400000000000091, 0, -14.400000000000091], [540.8, 915.2, -18.926999999999907, 0, 0, 0], [540.8, 771.2, 0, 0, -18.926999999999907, 0], [512, 742.4000000000001, 0, 14.399999999999864, 0, -14.400000000000091], [540.8, 713.5999999999999, -18.926999999999907, 0, 0, 0], [540.8, 569.5999999999999, 0, 0, -18.926999999999907, 0], [512, 540.8, 0, 14.400000000000091, 0, -14.399999999999977], [540.8, 512, -18.926999999999907, 0, 0, 0]], closed:true})
var res = p1.unite(p2);
p1.strokeColor = "green"
p2.strokeColor = "red"
```

**Comment by lehni** [comment]
It probably got worse because the epsilon in fat-line clipping was reduced fro `1e-9` to `1e-12`. But this needed for me to filter out many false positives. When you say slower, it would be good to know what state you're comparing it to.

**Comment by lehni** [comment]
I just measure, it seems a wee bit slower compared to `v0.10.2`, but not much. 750ms vs 790ms to perform the operation 1000 times.

**Comment by iconexperience** [comment]
Whoa, I just found a slight problem with your code, but it can be fixed easily.

In the following line something unexpected can happen:
```
var abort = ++recursion >= 48 || ++calls > 1024,
```
Imagine `++recursion >= 48` is `true`, then the variable `calls` is not incremented. But if in the next lines `straight1` and `straight2` are both `false`, we will iterate indefinetly. This will not happen, but we can get much more calls than the 256.

If you have a lot of time, remove in <a href="https://github.com/paperjs/paper.js/blob/develop/src/path/Curve.js#L1802">Curve.js line 1802</a> the part `d1 === 0 && d2 === 0 && dp0 === 0 && dp1 === 0 && dp2 === 0 && dp3 === 0 ||` and run my example. It will take forever (at least I did not wait until it finished).

So you should probably move the increment of `recursion` and `calls` before the declaration of `abort` to make sure these edge cases cannot occur.

**Comment by lehni** [comment]
On which version of develop are you seeing this? I think I've addressed this a while ago already, with  these statements right after:

```js
            // If we need to abort, consider both curves as straight and see if
            // their lines intersect.
            straight1 = abort || Curve.isStraight(v1),
            straight2 = abort || Curve.isStraight(v2);
```

If `abort` is `true`, `straight1` and `straight2` both end up being `true` also, and the case you're describing cannot actually occur, if I am reading this right?

**Comment by lehni** [comment]
But there is still a problem currently, it's the fact that when straight curves are handled, the result of `addLineIntersection()` or `addCurveLineIntersections()` is returned (`undefined`) instead of `calls`, and this is then used as the new value for `calls`, which is incremented and ends up being `NaN`, resulting in the `calls` check being ineffective. This is the reason why I was able to reduce it to `256` without seeing side effects: As soon as one of the involved sub-curves is flat enough to be considered straight, we basically end up without limitation of the number of calls. Will fix shortly (and reintroduce `4096` as the maximum for `calls`).

**Comment by iconexperience** [comment]
You are correct. I knew there was a bug but drew the wrong conclusion. Looking forward to experimenting with the new code.

**Comment by lehni** [comment]
@iconexperience I am going to close this issue, since the issue itself is resolved and unit tests are implemented. We can keep the discussion going in the other related issues, or better yet, start new ones and stay on topic : )
