### ISSUE TITLE
Gradients drawing and export is wrong for multiple offsets at 0

### ISSUE THREAD

**Issue by iconexperience** [paperjs/paper.js#1241]
If a gradient has more than one stop at offset zero, Paper.js sets the offsets wrong on the canvas and in SVG export. Here is a very simple example:

```javascript
var topLeft = view.center - [80, 80];
var bottomRight = view.center + [80, 80];

var path = new Path.Rectangle({
    topLeft: topLeft,
    bottomRight: bottomRight,
    fillColor: {
        gradient: {
            stops: [['yellow', 0], ['blue', 0]]
        },
        origin: topLeft,
        destination: bottomRight
    }
});
```
<a href="http://sketch.paperjs.org/#S/XZBBb4MwDIX/ipULnZZVHKtUO+26w9QdA4cALkRNHRTcoqnivy8ZTKV9p2fni/3kmyBzRqHE9wm57oQUtW9SfTUB2PefeGR4h6vFcVsjMQZ4A73LJezycl9QwirP7M8H23bP6OsaneHecBcpwhG+ot0esGZDrcPNrSCIWpaqfyPn9mqJWhfL89E69+GdDwqWOUltMI2NUR6aSUMcPijQOvtB5/yYSchLCTqr3AX/ivL+YZJ374NtLT2HS2pwYEuGraeHgDMxFTS97ON5q4Dm1HtLPAily+kX">Here is the sketch</a>

![image](https://cloud.githubusercontent.com/assets/2122773/22097696/ca85e342-de22-11e6-8afa-7f4bed926c27.png)

The gradient is a valid gradient according to the <a href="https://html.spec.whatwg.org/multipage/scripting.html#fill-and-stroke-styles">canvas spec</a>.  The rectangle should be completely blue, because the spec says:

> If multiple stops are added at the same offset on a gradient, then they must be placed in the order added, with the first one closest to the start of the gradient, and each subsequent one infinitesimally further along towards the end point (in effect causing all but the first and last stop added at each point to be ignored).

The problem is caused by <a href="https://github.com/paperjs/paper.js/blob/6e7fe67a8ddc93d41b620ef8f02a503d2920769b/src/style/Color.js#L871">`Color.js line 871`</a>:

```
canvasGradient.addColorStop(stop._offset || i / (l - 1),
                        stop._color.toCanvasStyle());
```

For cases of `stop._offset == 0` and `i != 0` it calculates a wrong offset. The correct code would be something like this:

```
canvasGradient.addColorStop(stop._offset == null ? i / (l - 1) : stop._offset,
                        stop._color.toCanvasStyle());
```

The same bug occurs in SVG export. In <a href="https://github.com/paperjs/paper.js/blob/develop/src/svg/SvgExport.js#L237">`SvgExport.js line 237`</a> you can find:

```
offset: stop._offset || i / (l - 1)
```

The correct code would be something like this:

```
offset: stop._offset == null ? i / (l - 1) : stop._offset
```

**Comment by lehni** [comment]
You're right! I'll fix that right now.
