### ISSUE TITLE
ImportSVG: Cannot read property 'width' of undefined

### ISSUE THREAD

**Issue by zenatti** [paperjs/paper.js#1242]
Trying to import an SVG passing directly the root node to importSVG will raise an "Uncaught Error: TypeError: Cannot read property 'width' of undefined" error if there's a width specified in %.

Test SVG (Chartist output SVG):

`<svg xmlns:ct="http://gionkunz.github.com/chartist-js/ct" width="100%" height="400px" class="ct-chart-line ct-chart--manydata" style="width: 100%; height: 400px;"> .... </svg>`

When the root node is passed to importNode it try to get the size calling the getSize without the 5th parameter allowPercent:

`rootSize = getSize(node, null, null, true) || paper.getView().getSize();`

But, into getSize, if width is in % and allowPercent false or undefined (like that call) it try to access to rootSize that isn't initialized yet.

`return /%\s*$/.test(value) ? (res / 100) * (allowPercent ? 1 : rootSize[/x|^width/.test(name) ? 'width' : 'height']) : res;`

As soon as possible i'll provide a test case and maybe a fix

**Comment by lehni** [comment]
[Demo sketch](http://sketch.paperjs.org/#S/PY/NasMwEIRfRSyUpFBbLvQkJ7nmAQK9xD0oa2Eptn6QNml+6Lt3bUpPy+zMfOw+IWhvQMFhNIQW3gBjP+urzqJcB7EVq808b34KRSFtO7BESUk5uBjGS3jUgyN7OdUYvUSrM7lC1blIpA7Et+vJcue9aV5YWuMGOzM+mibdeIGTLoU1UrV0q8kFI/5V5XW495o0RwvdJ8PRBanETGz/gEosvLaD3UbytbtV24WU49kg1c6nmOnwuV+z88oGP3nKRo8pukAF1PHr5xc=)

**Comment by lehni** [comment]
The question is: what dimension do you expect that outmost 100% be related to? the canvas size?

**Comment by lehni** [comment]
Let me know if this fix works for you.
