### ISSUE TITLE
Mathematical Operations is not work

### ISSUE THREAD

**Issue by zhipenglin** [paperjs/paper.js#1243]
[youer document](http://paperjs.org/tutorials/geometry/mathematical-operations/):
// Define a point to start with
var point1 = new Point(10, 20);

// Create a second point that is 4 times the first one.
// This is the same as creating a new point with x and y
// of point1 multiplied by 4:
var point2 = point1 * 4;
console.log(point2); // { x: 40, y: 80 }

// Now we calculate the difference between the two.
var point3 = point2 - point1;
console.log(point3); // { x: 30, y: 60 }

// Create yet another point, with a numeric value added to point3:
var point4 = point3 + 30;
console.log(point4); // { x: 60, y: 90 }

// How about a third of that?
var point5 = point4 / 3;
console.log(point5); // { x: 20, y: 30 }

// Multiplying two points with each other multiplies each 
// coordinate seperately
var point6 = point5 * new Point(3, 2);
console.log(point6); // { x: 60, y: 60 }

test in my computer:
VM5436:23 NaN
VM5436:27 NaN
VM5436:31 NaN
VM5436:36 NaN

**Comment by bmacnaughton** [comment]
Your code in [sketch](http://sketch.paperjs.org/#S/bZNBT+MwEIX/ylNOFEpbmrSCIMSBPexlEdLuDTi4zoRYpHZlO4QI8d8Z1wnbiB4ixY793jdvJh+JFltK8uTvK3lZJdNEmiKs53P8olJpgsDOKO3hDZwX1qNVvnqyT/pN2PjpAjfQ1OIhLE4uFlMsF5PrcCQ8rHRnSfig5EgaXQyClfBQDhm82pLjNaFU1nkYTbP+6r+KT6j40TEqhIMMckq/sGCwjWqBCu8QLN/1d0058G2b2qtdrajApkOWj/CXjN+fO0W252ZKZ2qa1eblJJ6ZXIMVP/CeI+MCuxyXC3we1HhvWrQEKWrZ1KHaQFyosiRLWhI25Fsivd/2rZmNENIBYYnznuU4R3rAkUaO9Zijz7ojz1kYdustpjEhjqzZklUSb6JuOM6i4FC4t1F+nEw2YKU4Y7vjSNkB0joiXY2RfnM0YmMaJuLylS1CZ0L3b0duq8EtwxzpcbPVgdkymqVjsz+x1V2YD845KrpYPAlZIWbyPRFuv9tflsbYQukQoKMdWX6puxHkeoBc8bD8H/qUZ35yHHn9M5/QMv7VNtyq18iX5I/Pn18=).

Maybe you aren't using paper-full?

**Comment by lehni** [comment]
You need to use paperscript for this to work, not normal javascript. See the examples in the distribution, or here: http://paperjs.org/tutorials/getting-started/working-with-paper-js/#what-is-paperscript
