### ISSUE TITLE
Broken Page on Chrome 55 on MacBook Pro (2007)

### ISSUE THREAD

**Issue by jwiener88** [paperjs/paper.js#1244]
If I am posting this in the wrong place, then I apologize. 

One of my clients has told me that our page was broken. He sent us an image that was completely pixelated and he said it was "flickering". I linked him to these pages:
http://paperjs.org/examples/tadpoles/
http://paperjs.org/examples/spiral-raster/
http://paperjs.org/examples/hit-testing/
http://paperjs.org/examples/q-bertify/
http://paperjs.org/examples/chain/

Each one responded in the same way. Here is what my client has sent me:
http://imgur.com/a/uGml8

I thought it was a graphics card issue, but he claims that he was able to run this page:
http://www.kevs3d.co.uk/dev/canvasmark/ and that it looked fine. 

My colleagues and I were unable to reproduce the issue and we do not have access to the computer.

**Comment by lehni** [comment]
Wow, that sure looks like a GPU issue... Never once heard of this problem before. How does it look on Safari? It may be linked to the size of the canvas elements and the use of a hi-res canvas on these examples. This example here does not run in hi-res mode. Could they test that?

http://paperjs.org/examples/nyan-rainbow/

Either way, this is clearly a browser / OS / hardware bug and not something we can fix in paper.js

**Comment by jwiener88** [comment]
Thanks for the help. I have not heard back from the client, so I suspect that they conceded that it is time to replace their hardware.

**Comment by lehni** [comment]
I guess we can close the issue then?
