### ISSUE TITLE
hit detection position/pivot selection versus center selection

### ISSUE THREAD

**Issue by dexterial** [paperjs/paper.js#1249]
as per issue #980 this should be resolved, however the position.selected = true actually triggers a call to getCenter, that attaches itself to bounds.getCenter. All is nice and fine unless you have an uneven shape, in that case, after rotation the 2 points do not coincide anymore, ergo the hit test does not give you the actual position/pivot, but the bounds center.

**Comment by dexterial** [comment]
i also have a short of quick fix if one can integrate it in bold/italic https://github.com/paperjs/paper.js/blob/da52f1f6850fbd820cc3c70b4609f4cb639861f2/src/item/Item.js
starting with line 1941, I tested this in manual edited file and it works, you just add the options.pivot = true to the hitTest call


if (checkSelf && (**_options.pivot_** || options.center || options.bounds) && this._parent) {
			bounds = this.getInternalBounds();
			if (options.center) {
				res = checkBounds('center', 'Center');
			}
			**_if (!res && options.pivot) {
				var pt = this.getPivot();
				if (point.subtract(pt).divide(tolerancePadding).length <= 1) {
					res = new HitResult('pivot', that,
							{ name: 'pivot', point: pt });
				}
			}_**

**Comment by dexterial** [comment]
or if one inverts the return order pivot on top of center

if (checkSelf && (**_options.pivot_** || options.center || options.bounds) && this._parent) {
			**_if (options.pivot) {
				var pt = this.getPivot();
				if (point.subtract(pt).divide(tolerancePadding).length <= 1) {
					res = new HitResult('pivot', that,
							{ name: 'pivot', point: pt });
				}
			}_**
                        bounds = this.getInternalBounds();
			if (!res && options.center) {
				res = checkBounds('center', 'Center');
			}

**Comment by dexterial** [comment]
or a better option to check for position instead of pivot , there is also the HitResult definitiof file that needs to be updated with a default value if one wants to be complete 

**_// Hit test the pivot/position of the bounds
                position: false,_**

if (checkSelf && (**_options.position_** || options.center || options.bounds) && this._parent) {
            // Don't get the transformed bounds, check against transformed
            // points instead
            **_if (options.position) {
                var pt = this.getPosition();
                if (point.subtract(pt).divide(tolerancePadding).length <= 1) {
                    res = new HitResult('position', that,
                        { name: 'position', point: pt });
                }
            }_**
            if (!res)bounds = this.getInternalBounds();
            if (!res && options.center) {
                res = checkBounds('center', 'Center');
            }

**Comment by lehni** [comment]
Could you provide a simple demo script that demonstrates the problem, e.g. on http://sketch.paperjs.org/? Thanks!

**Comment by dexterial** [comment]
http://sketch.paperjs.org/#S/dVdNb9w2FPwrD744BSxH/JSYoqf00kOBAjk2PSiyEi+8XhmSnDQp+t87M9TGi6I97HIpku9j3ryh9q+r0/A4Xb25evcwbeP91c3VON9x/nlY7GnY7n8etsF+sutfc28+l2RjE7I1weGTrEnZMHMdFjHrogWPaZvNdxi5wzntcsEa71qLmPrcWajbE7e10Zzr8SPDGkZ8epgpGFoax1acLsHkuXXW4VR00QpsJQtY7J0lDA5TjzMxWsRQnOEXHCTjQDcwgIHncdDJF116xJJhLsAxDtK9l8uGezn6ngvOZR2FMcw65oZTGdYjcUCWTNAhYWaGM64vjNU8R18sErDsjcG0wZKzY+wZJYMLNiIpQmIuEyjgybQQIzMPyI0JFPPKgPlH84wYnpJ1SqwCgjrgWRML3BBaOFIoPnol3GUrfI69jqe8R81gHN5ViSQTFfy4l9G5tOdJVLsgnJmcqACrgaE7r+LCWKopCCofrO8QqGs7ppoQXlbGiVHjOSNFFX1hrTAhPsxMzECQgtcS65it5xCs80LDZaYNCsJ2U0EAvEGBWgwygjjpHOcAJd0DVFdJEdo6JGwUCzpt6OzoxCmLMAjsRuLmWFOS2xcUkQmHvvKqZA0OifMUl2rMQolgMmpkhmKQM+SUj5U0gCfVNmIkTV9rqD763lCIvRUdPIHOTJ6uipHQYDg2uqQIzccdgqI8Y8W8BV/QHxhZdE8DYL3LhMdrFMeFG/YyAO4FOkBDiKPUzjMeUKdjIoC6MGcwpOd+ftXaNyqbV11q0uzLpOYgeYi5bO6MbsBL7euE7a4KskmmNDhNrmpk76gVsMRUoBOAHIH2JA4Qd44tgs7oraBBHEuNsIpEIZJM8JxaEY6ESbVV26JUvWjcir50JcaD1HDAPlZdA0MFHxJLVlQtMLyLUkai/kLDnWTFGB8RYPwsv/PqXzr30k1El1u1m+AJTkVByqx0K5lRLFCXIrp0GtlW1MFcOU50YY/wMwl2ad9XXVbteJJSJxKzvdlFbC9KSr//pP+iwJr4IgBCJNfaqnlKrIXzZAFiOzbMPdBW4FUB8KM6yIN77FC1ZeiVOwWAClrhc1XewVwOWDvTZZdj4HhUINychetI2Y/io5PeBkhdDDVeGGF0qoKrAOnmYlpSEXKtCLpOyic5ZqK+jnWtNhRJAwvf7FFsQEMfecRXWSF/R2GlB7tIUmPq9bZHsV8mZHNVMc7ANQopBnYCJcp0l2ItSNspnJIqVwmFGDqnqo+KOnEHyaeEnNAX53i5VeHV413sau1Sfc6DJCX5F5RkypppsUj4MCQv7mbpMq5kzOFOkgxdkqAhKpCn1AtyVMOq2g0J6uutIKhYBvS9GjCq5dDRYHrQN9wHgiwdcza6eu1hJnlJutKFIFGlFgYNmdqIlkIGiI+vKh0jEr0c2HMkHULtK28jm6O+RXjeSo2vSkMlKTSJnAvNIYFe3OiElIJ3ez/oCglVr/gh1mS17n+MkJfWdLGxfmp35enUAfBOejEQv8shL7G9jcQlslcVDvXtJZtorIKRyKXW0FfRqtxu9yBTvfJKK8HA0EnZPTPEAbrtSC5Wt6s8PVcIR3l1txR2am6SpLEP8KzL1bZnc3DOJ7DT8a1G+uYkaCF9u/7x/fL+dH6NxCvkafpiv+Hnq/Nr5Q/awdnt0+HzvGFPnczrYTvMp5fldRyO06v21t3gc3FsW4bTehy26RWvl/ZG3xfry7xxMaSLZ+u2zA/T2/k4L3yvXaa765fFj8/H49d303Eat+kOy9vyPL2sfpifT3fr7fp/6+fA/3PHGQ0ZeTudtmm5AOX27WEZkeOln1GbbnA91fAvTv47i0/LNJ2uv/t5/dp+WdfnyQ6rbffDhq/J7g+b3U0bAkOIdpznh9U+4jjXqiubP2omR4fTJ/z4czf35X5apmG93FyTpC14WSaU4fB5sm3WnvV+eJrsaT6ctvXGhtOdfTmABbu103xaD4/TthxQ2H2XfZ2fbcLG56e6d7DHw7o+DvhbYnCiWsLbOUf8VfmAkB7q6as3v//x9z8=

**Comment by dexterial** [comment]
Hi Lehni,I provided a script for this issue in Github.Best regards, Dan.

**Comment by lehni** [comment]
Great, thanks! Trip: If you use `PathItem.create(pathData);` instead of `new Path(pathData);`, then it will always produce the right type of path, in this case a `CompoundPath` for you.

**Comment by lehni** [comment]
Ok, I understand the issue now. I agree that adding the `options.position` option is the best way to go.
