### ISSUE TITLE
group.bounds.selection bug in path and text mixed scenario

### ISSUE THREAD

**Issue by dexterial** [paperjs/paper.js#1250]
when having a mixed group of paths and text the selection misbehaves, see bellow code that reproduces the issue. the computed value shows ok, but the represented value in selection is offsetted topLeft of the view.

var path = new Path([100, 100], [100, 200],[50, 150],[100, 100]);

var text = new PointText(new Point(200, 150));
path.bounds.selected = true;
text.bounds.selected = true;

text.justification = 'left';
text.fillColor = 'black';
text.content = 'The contents of the point text';

// Create a group from the two paths:
var group = new Group([path,text]);

// Set the stroke color of all items in the group:
group.strokeColor = 'black';

// Move the group to the center of the view:
group.position = view.center;

group.bounds.selected = true;
console.log(group.bounds);
var pathz = new Path.Rectangle(group.bounds);
pathz.fillColor = 'rgba(0,0,0,0.2)';

**Comment by dexterial** [comment]
i narrowed down the issue to text.applyMatrix = True not haveing any efect compared to  text.applyMatrix = False, so the original matrix created is never updated.

**Comment by lehni** [comment]
`text.applyMatrix = true` makes no sense, because by definition, `applyMatrix` bakes the transformations applied to the item into its content, which is not possible for text. This is why the property cannot be set to true o text items. Something else is going wrong...

**Comment by lehni** [comment]
The same problem occurs with `Raster` items, or any item that does not have `applyMatrix` set:

[Sketch with Raster](http://sketch.paperjs.org/#S/dZJNb8IwDIb/itVLi1SlDIkLiBOHnSZNcAQOoZg2NI2jxIC2af99ScoYmoQqtbbz+vFH85UZ2WM2y9Ydct1mZVbTIfoX6cBKbmEBBq/wHsxi8zIelxBeuxIGexLtzTRGp9G6C0bzrYnpYk9nc/DCo8aa8RBw7M4YTmMBxdjfCqykZ3RF3jLbWVVJ75G9sNKiO3lBrqlULxv0VS+d0h9GnGyTxyqRIXwtNRZjMZneQ08Lb01VwdKhZAQJjaOzhaOjHrhF4Culsf1s6HA4Hlp8jXaxicdlaj1NmXBr5JTu2VGHUJMmB3QEqXVSelAmCRIvsNNXDPJlUi8g32tZd/kv840u+JcDTMmp0YQ9RXb0Lgqvd5olr1iRCagYF4M04QbB05XUZDxpFJqa4lE6uv2nOPLnw00QqwCQpgk7/y9PUnFUWt/Hcs1eFuMyPWIyyufhlu3D/jtLyrDPZpvd9w8=)

[Sketch with Shape](http://sketch.paperjs.org/#S/dVJLa4NAEP4rgxcNyMYKuRh6yqGnQmmOmsOqk7i42ZHdTQIJ+e/dR2tDaRR0Ht9887wlih8xqZLtiLYbkjzpqPf6mWuYuB3gFRRe4MOJWf1SFDm4zy6HKJderlfeuvLSDFisG+XDWUsn1RtmUGJnsXd0Vp/QeX0CYfHoLNuBT8g+HYCrg8Ts1ihwz0RC2Qrqcs4U7UZc8R/zXki5IUm6glRjnzbq7qvwOZjpuOMtWLmaTU8La9RyCRuN3CJwOGg6TbDXdAQ7INgLhbGYKnYQ3XFGb17Oau/OQ2thCoFuizaEG6tpROh8mUB74FIGpAGhAiDwOe7wZxEemnI50lbybkx/ON/pjL8xYCkoHSqLgdtrZ4GXmW0iI6wg5ai8nUVooIuApyPpSBmSyCQdskfo4nuPvuXrw6U87PIvPEDZvCvflj60PCvy8LJyka7dFbZu/mM4AJNU9e7+BQ==)

**Comment by lehni** [comment]
The problem is in `group.internalBounds`, which returns the bounds in the item's own coordinate system. This doesn't seem to work for nesting items with transformations stored in their matrices:

[Demo Sketch](http://sketch.paperjs.org/#S/bU/BDoIwDP2VZRcwIQsx8TLjRQ/e5Qgc5qiwOFqyDU0k/LsbXu2haV9f3ntdOKoRuOTVE4IeeME1dWl/KcdMgJGdWDWoCcQNdFDYW8iXBlmsiQwGyep9WRYstrb44d584A/8MNZeyJKTLHPQZQ2uu2ODyUN4raJuKQ4JSc69o3mK1ghvdk1zXidim+6a0JMFYanPN56IOcChsmeasfOJE/+4O1DPLaPnsm7XLw==)

The fix should be rather simple, but I am surprised nobody ever caught this!
