### ISSUE TITLE
path items inside array

### ISSUE THREAD

**Issue by George35mk** [paperjs/paper.js#1256]
First i am new gide me pls.

i want to make an array that hold all the paths , circle or rectangles 

like this

var myScene =[];

`// blue circle
  var blue_circle = new paper.Path.Circle({
    center: [_x, 50],
    radius: 5
  });

  blue_circle.fillColor = '#0080ff';

myScene .push(blue_circle );

`

i have animation frame for redrawing the canvas 

`animate_canvas();

function animate_canvas() {

  requestAnimationFrame(animate_canvas);

  paper.project.activeLayer.removeChildren();

 myScene[0];
 myScene[1];
}`

WHY is nor working like that i want to have array that holt all the shapes and i want to draw on the canvas  if this array have objects inside

**Comment by lehni** [comment]
This is a bug database, not a support forum. Can you please send this question to the mailing list instead?

http://groups.google.com/group/paperjs
