### ISSUE TITLE
Boolean Path Operations: Subtract between 2 triangles (Path.RegularPolygon) doesn't always work as expected

### ISSUE THREAD

**Issue by alexburner** [paperjs/paper.js#1257]
I'm trying to recreate an [old illustrator project](https://www.flickr.com/photos/alexburner/7028879121/) in Paper.js and have run into an odd issue.  

If I have 2 triangles, and one has been rotated 180 degrees, the result of their subtraction is incorrect:

Screenshot | Sketch link
---|---
![screen shot 2017-02-14 at 11 07 59 pm](https://cloud.githubusercontent.com/assets/409114/22963926/af9bdc1a-f30a-11e6-831d-1cbdb91c62e6.png) | http://sketch.paperjs.org/#S/zZFBTsMwEEWvYnmTVIqshEoIuWLFBap2waJhMbEniRVjo8mkVVX17rgEQrkBs/vz/3ie7YsM8I5Sy/2AbHpZSBPtTR+BBJOD0HmsxLMIeBJb4F7tsJs80Db6cxdDfqmDSGUwMJIWR4cnNYtidkZncdRi/S0JrJuSrsryJ8AUB3yJPqb5rPFghuyP9eos91o8puZ1talDHe7hHv4b3AKmKDIw5tVTWdzv/r2DdW2b8Jd3VuPUMIHhfDlkDt+CqnXef5GkkYzQZpv0XQ0hDB/RBR6lPrxdPwE=

If the rotation is anything else (disclaimer: not fully tested), such as 179 degrees, the subtraction works as expected:

Screenshot | Sketch link
---|---
![screen shot 2017-02-14 at 11 08 17 pm](https://cloud.githubusercontent.com/assets/409114/22963929/b48051fc-f30a-11e6-8077-072b24e0dfe6.png) | http://sketch.paperjs.org/#S/zZFBTsMwEEWvYnmTIEVWAxIIV131AlVZsCAsJvYkseLa1WTSClW9O25TQrkBs/vz/3ie7ZMMsEOp5VuPbDpZSBPtRR+ABJOD0HosxUoEPIoNcKe22I4eaBP9VxtDfqqCSGUwMJIWB4dHNYlicgZncdDi6SYJrBuTLheLnwBT7HEdfUzzWe3B9Nkf691Z7rR4Ts3zw7IKVbiHe/xvcDOYosjAmJcvr8X97t87WNc0CX9+ZzWMNRMYzudDpvAlqBrn/ZUkjWSENlum76oJod9HF3iQ+uPz/A0=

Am I doing something wrong, or is this an issue with the subtract operation?

**Edit:**
Issue not specific to 180 degrees, seems to be any multiple of 60

**Edit 2:**
Issue *is* specific to triangles, made a new sketch that supports arbitrary number of sides, and other regular polygons appear to be fine:

Screenshot | Sketch link
---|---
![screen shot 2017-02-14 at 11 39 09 pm](https://cloud.githubusercontent.com/assets/409114/22964714/d5f38530-f30e-11e6-9524-bd49963e2d8f.png) | http://sketch.paperjs.org/#S/zZHBbsIwDIZfJcqlRapCAYlDECfYYTe0HnZYd3ATl0bNEpS6IIR496Ut08YbzDd//vXrt33jDr6QS160SKrhGVdeD/0ZAite9y8F27LVpnSlG8jJ2+siEocXdgBqxBseewvhEPnRu/RWOhZLoSMMkp0NXsTUZNOkMxo7OTk/UABt+sgWef4jouBb3Hnro0dSWVBt8jR6N5oaydYR3mdP4Zb/MdwYTARPQJiu1jmbP047Z8vsb47fXbSp67jKeG/R9RUFUJSORpNoEIjaWDsmidIkoE428YFVQGhP3jjquPz4vH8D
![screen shot 2017-02-14 at 11 36 24 pm](https://cloud.githubusercontent.com/assets/409114/22964632/7af64000-f30e-11e6-934f-737375c15509.png) | http://sketch.paperjs.org/#S/zZHBbsIwDIZfJcqlRapCYROHIE7bDtwQPeyw7pAmLo2aJSh1QQjx7nNbpo03mG/+/OvXb/vKvfoCLnnRAuqGZ1wHM/QnFVmxfX0r2IY9r0tf+oEcg7ssiHg4s53CRuzh0DsVd8QPwafX0jMqDR4hSnaycBZTk02Tzhro5OR8R1EZ2xNb5PmPCGNo4SW4QB5J5ZRuk4fRuzXYSLYieJs9hFv+x3BjMBEDKoT0aZWz+f20c7bM/ub43cXYuqZVxnuLrq8wKo3paDSJBoGorXNjEpImEUyypgdWEVR7DNZjx+XH5+0b
![screen shot 2017-02-14 at 11 37 22 pm](https://cloud.githubusercontent.com/assets/409114/22964658/992feb3e-f30e-11e6-9b91-8796c4895ed6.png) | http://sketch.paperjs.org/#S/zZHBbsIwDIZfJcqlRapCYRqHIE7bDtwQPeyw7pAmLo2aJSh1QQjx7nNbpo03mG/+/OvXb/vKvfoCLnnRAuqGZ1wHM/QnFVmxfX0r2IY9r0tf+oEcg7ssiHg4s53CRuzh0DsVd8QPwafX0jMqDR4hSnaycBZTk02Tzhro5OR8R1EZ2xNb5PmPCGNo4SW4QB5J5ZRuk4fRuzXYSLYieJs9hFv+x3BjMBEDKoT0aZWz+f20c7bM/ub43cXYuqZVxnuLrq8wKo3paDSJBoGorXNjEpImEUyypgdWEVR7DNZjx+XH5+0b
![screen shot 2017-02-14 at 11 37 31 pm](https://cloud.githubusercontent.com/assets/409114/22964672/ac259298-f30e-11e6-923c-9ac84d2a53e2.png) | http://sketch.paperjs.org/#S/zZHBbsIwDIZfJcqlRapCYVIPQTttO+yG6IHDukOauDRqlqDUBSHEu89tmTbeYL75869fv+0r9+oLuORlB6hbnnEdzNifVGTl++tbyZ5Zsal85UdyDO6yIuLhzLYKW7GDw+BU3BI/BJ9eK8+oNHiEKNnJwlnMTTZPemugl7PzHUVl7EBslec/Ioyhg5fgAnkktVO6Sx5Ge2uwlawgeFs8hFv/x3BTMBEDKoT0qcjZ8n7aJVtnf3P87mJs09Aq071FP9QYlcZ0MppFo0A01rkpCUmTCCbZ0APrCKo7Buux5/Lj8/YN

**Comment by lehni** [comment]
Have you tried this with the `develop` branch? I quickly checked, and it seems to be fixed there already:

http://paperjs.org/download/#development-builds

**Comment by alexburner** [comment]
Just downloaded develop branch and checked, it worked! Thank you :)

![screen shot 2017-02-15 at 7 36 12 pm](https://cloud.githubusercontent.com/assets/409114/23006354/1a85bd88-f3b6-11e6-9ec4-cabb1d141475.png)

**Comment by alexburner** [comment]
Paper.js continues to be an excellent library for 2D path geometry, many thanks @lehni & co!
![screen shot 2017-02-15 at 8 30 06 pm](https://cloud.githubusercontent.com/assets/409114/23007452/a1cdf6e6-f3bd-11e6-807a-5491b746e29e.png)

**Comment by lehni** [comment]
@alexburner glad to hear it works, and thanks for the kind words! This example looks great. Could you consider "donating" it to the examples / reference? : )

**Comment by alexburner** [comment]
I'd be honored to donate to the site! I'll need to tidy up the code a little ;) How should I submit it to you?

**Comment by alexburner** [comment]
@lehni here's a more reasonable/readable version
https://patterns.website/experiments/paperjs/other/holonstar-6.html
https://github.com/alexburner/experiments/blob/master/paperjs/other/holonstar-6.html
![screen shot 2017-02-17 at 12 01 39 am](https://cloud.githubusercontent.com/assets/409114/23057573/a1dee83c-f4a5-11e6-96cd-05127ce9f581.png)

**Comment by lehni** [comment]
@alexburner that's great! It's a really nice example. I will loo into perhaps animating it somehow.

BTW: instead of `triangle.remove()`, you can pass `insert: false` when creating it, should be faster!

**Comment by lehni** [comment]
I have simplified the code a bit [in this sketch](http://sketch.paperjs.org/#S/pVbbbts4EP2VqYs2cmPITlW0WHvz4KRBG3Q3DmwHfUiDBS3RFh2ZFEgq2qDwv+9QV4p2sA/Rgy1xrjxnhsPfPU52tDfuLR6pDuPeoBeKyHw/EQmXs7ubJZzDp8kvbr7n06/Xdwtc+PhpVC0tlvPZj6t/fl5/XX43gu7y5eyv2RyXT94GQXBSy6bLu/l0eT27QUkwrJ1fzK+/fV/eXC1MgD+GZybCcAhPjOZ+SLmmEtc5zeFWMK69fmXWiCxFFK0zHmomOESS5AtNpNeH37844INOQ0mJpqAlI3yTUFUKjLtmCT3eP0xKwVpI8IyU4epogn9/ltjg6+lp49j1gcq3RMf+nG6yhMhbkTxvBPcsbfOUKY+r/0FXqFhE1RgCZ1mSiGW4XhLi2mgpHumlSAR6tYk4qveTRToed3h09BhXVOoxrEmiaCva9yftR71lXwqNyHoMPkAwGlSbOqap/DRTsVd/1ip7l6NUsh2Rz6CylaIFpRZbpZC9iq06wHmb2j17sDJu/G1Lf9vW39bxV8C1Btz+m/Nz2B7IzNPGq9583JqWJNRem8D2wcbMAsZ5bQAo0aw8vggmIih49CKctfh1gNa7mL4Mqa120VFD6E7hrA/vygiuUbuB1mjqM1NkZjsNghf91xG4LQhk8P49lK9OXkeZtZNr3l/DrsVHyW/j9ZBh+m8RZQBKSPwlPMIGf8ZDKIxZEknKS027Y1IpQqrUZaXgNbIBjOoA3ZJwLSzpAILPIxjiaKhNMSlJdSY5CE5hxTawkSJLQaybHiiybFDrZlrZmhP/m7Fr0/PRICTajt43QffWse9mGopdKjIemQMZc40zuojZWjc8FqOkUrZrv2PnYyVdkTD2mjAdvwNgnbqwZX7t/JgPIxocOS4MrajaOIIUPQFTBaB1OZ0oyJHy2OB60NWWp1WmIaeQE66BJIlRF5m0TfCkBwJS5OBxyjbxSkgFK6HjA19PTGXooyQwZzpGSx1TIFKS5z6WoImUJiSkZnkHmWJ8AzuyYaEz/CpU7k17bXFolF2PDBQSq0uacdO8/D+iDh1m0bemHkaxx97kuGoxSFvVYpIeqK5ZktSKDolYauOiNz6YQ2QIZx/7uNe6AN2ZTLDoidnE2LonOUorieRojuU9tm5NltLeharqpRqxqleOHOtfukd6ceTi5QkV2nvUxJKFpLjm/G0qPBW59yUI8OY2GhnsJ6ZSLM6NI7+w8Ipf93ZQyimPluKChI9e1dJ4JV3h9HpMzbVP9cb3D/v/AA==)

Note that the colors don't work correctly in `v0.10.2` but fine in `develop`, I am not sure why that is.

**Comment by alexburner** [comment]
@lehni thank you! That `insert: false` is a nice trick, and looks like you pared down the project hierarchy manipulation in those for loops (much nicer without all the `.clone()` and `.replaceWith()` calls). And animations sound like a great idea! I might noodle on that too.

FWIW the colors issue in `v0.10.2` might be related to the 180° triangle subtract issue? I'd developed the `secondaries` before the `primaries` and noticed—while they did all show up—they showed up out of order. Most of the shapes extracted from the triangles showed up in clockwise order [1, 2, 3], but the second set had children in clockwise [1, 3, 2] order and the third in [2, 3, 1] order. This threw off the whole `children[i + j * COUNT]` trick. Here's [a sketch](http://sketch.paperjs.org/#S/nVVNb+IwEP0rFtKqyTYKXxUrheXQ0mrby27VUvUAHEwwxBBsZDtdVVX++47jODiBslJ9IM7M8/jN5M3w0WJ4R1pR63lLVJy0glbMl/r9DQv0+nA7uUcj9KPTGc6YttzfPfy6n9RMT9e3Dy/PYOpdWdP4z8tvDbqCd2OJCVNEgImRv+iRU6Y8E7yNeoGNCnu/jKAExWydEglHpvMizIoL5GkfBVtnCI+f5iLYXl766GPGECz3NAAfsUrCJ7LOUiweefq+5swrkXoZXlH5DA4OSZdERqjvmARe0gxsJmEXqwTfkjFPOUS6WKQ43l4cuV/pUiURGpSOXGeqN5ZrKLjCingUfUf9TlAyaqJkuM9k4tlX7c5tjSWJOVtiQQ9V+0LNrgFZ3Tal8+Ex5KYGAcaXqOujbyaye8AyencOXIdUJwYuVaVxY9Os+G4M382B78bhqxddIQ9QoxGiPoJrFGUZGZ7yNwieRLvpjWvpbeZNGNntAVHlFspsoQR20hn7zhEND1c0TQt9wEEnB72SjESo2+nAZwei7ZJjUAdJrDKBFeUsQr12v+FdCLpOFCMSxNl1fLlD40BXkD0oFPSoQEdAzj+F0iUAX+nKzcMRmJFhBa/pUCWUrSsJuofg897hOPFWGYt1MugQIdCfsSyNCQDaszHqCcQJTZeCsBPh9tDtNZVUoQzhYvoApgCGkqx30GXStyWomvJrlxVBBdnxN+KdCekgCm85IXnGVKH6GTOsT1xpFVarlh0gJ+A6ToA2NZbH/uJqvylMSdSE7gjPlHPiCFUVOYxTLklRXFdRdYwzCiHVwX9wtmPKkfop+kx32VV0WX9QdFkxDzawK8dBG3V7zYarinC28ez6rAHtyhvU80B3vCZjSu+4c7/2VWDouUKCH/iHXgiCt3v9Jypb0XSe/wM=) with some debugging code. In `develop` they all show up in clockwise [1, 2, 3] order.
