### ISSUE TITLE
Shape Item (Rectangle) wont accept children (when calling shapeItem.importSVG).

### ISSUE THREAD

**Issue by MmariDeusdedit** [paperjs/paper.js#1259]
I've been trying to import SVG and insert it into a shape item i had already created. The documentation states that the returned item (*child*) will be added to the item (*parent*) on which the importSVG was called on but the returned item is not added to the *parent*. I tried adding the returned item manually through the onload function using item.addChild on the *parent* item but the *parent* children list remains undefined. The following is a sample of the code I'm working on:
```javascript
var rect = new paper.Shape.Rectangle({
	center: new paper.Point(this.hand.point),
	fillColor: "rgb(244, 67, 54)",
	radius: 3,
	size: new paper.Size(this.cardSize),
	shadowColor: new paper.Color(0,0,0,0.4),
	shadowBlur: 12,
	shadowOffset: new paper.Point(0, 0)
});
rect.importSVG("./assets/cards/card.svg", { 
	expandShapes: true, 
	onLoad: function(item) { 
		rect.addChild(item)
	}
}) 
```

**Comment by lehni** [comment]
Shape items cannot hold children. Only `Group`, and `Layer`, and `CompoundPath`, if they are of type `Path`.
