### ISSUE TITLE
Curve.hasLength() should only check handles that belong to curve

### ISSUE THREAD

**Issue by iconexperience** [paperjs/paper.js#1260]
In <a href="https://github.com/paperjs/paper.js/blob/develop/src/path/Curve.js#L1031">`Curve.hasLength()`</a> we check if the start and end point of the curve are identical have no handles, because in this case the length of the curve is always zero and we can skip an expensive call to `getLength()`. But it checks both handles for both segments, while only the handles that belong to the curve should be checked (`handleOut` for `seg1` and `handleIn` for `seg2`). As a result we often make calls to `getLength()` although it should not be necessary.

This is merely a performance problem, but I think the code does not have the intended behaviour, therfore we should fix it. I suggest to change the code to this:

```js
        hasLength: function(epsilon) {
		var seg1 = this._segment1,
			seg2 = this._segment2;
		return !(seg1._point.equals(seg2._point)
					&& seg1._handleOut.isZero() && seg2._handleIn.isZero())
				&& this.getLength() > (epsilon || 0);
	},
```

**Comment by lehni** [comment]
You're right! Thanks for pointing this out.
