### ISSUE TITLE
Unite operation results in empty path

### ISSUE THREAD

**Issue by iconexperience** [paperjs/paper.js#1261]
Here is an example of a unite operation that results in an empty path:

```
var p1 = paper.PathItem.create("M933.13,1023.97l-516.19,-171.71l607.1,-101.57z");
var p2 = paper.PathItem.create("M933.13,1023.97l-516.19,-171.71l67.33,-11.27l337.49,112.27c16.7,-50.22 71.03,-77.36 121.34,-60.63l45.23,-135.96l35.71,-5.98z");
var res = p1.unite(p3);
```

<a href="http://sketch.paperjs.org/#S/pVHBSsQwFPyVktMupI+8lybZrnjy5EEQPBoP2W7cLc22Ja0eFP/dl8WD4FESHpnMMMwkn2IMlyj24mmIa3cWUnTTseD3kKsZq9tqDnPM8BjW8/0aL9DlGNa48eKh1RpQS1SkoXWpNmgBW1mjQ3CYrHKAjBSCcR9ebG/8eDWl/5g60JoRArmktYOmlYjEqGOhk7VRQFSxWLHMsdpWSAi6kbVVYHVqDFBx0AZam3g6Dsnn3U/EGWFZ8zTEuylNmaN6kePRi0LRH+qUYxyvZKmW41K6IbyNPdeZqRjyJbz2Kf3yOx3ChoyR1XUo3kBbL/xYFn/BgZ9jmKd+XBexf375+gY=">Here is the sketch</a>, but note that in the sketch everything works as expected.

![image](https://cloud.githubusercontent.com/assets/2122773/23228978/e46c92f6-f93e-11e6-82e3-f40d43944b91.png)

**Comment by lehni** [comment]
Ok, thanks. 

[Here the sketch with the view zoomed onto the shapes](http://sketch.paperjs.org/#S/pVE9T8MwEP0rkadWck4+O/Y1rZiYGJCQGOsOITVtVDeJ3FAQiP/OueoAgg3LOvnde3q+jw/RN8cgluLxEKZ2L6Roh23G5y68wrGZUvdW3BRrBPXzkCzU5f7FlEZbQOUMVmrhaiRlOWktAaGihXWcU2g2K9/7/tykYkT+ZGzGkOChmfZ3UzhCm0IzhZkX97UxgEai0gZqiqVFB1jLEgnZMDpFgIwUgqV3L+arq6n+jymBMYwQNEVjCKpaImpGLQtJllaB1gWLFcuI1a5AjWAqWToFzsTKgs4OxkLtIkfiIvm9uJY4IpymNBzC7RCHxKV6kcLWi0zpX9QuhdBfyNxaCqfcG8JL33E7o86GnITnLsZvfrunZqYtD/8S8sJAz73IY/c9L/uJx3EYh66fTmK53nx+AQ==)

**Comment by iconexperience** [comment]
What I find irritating here is that the intersections at the bottom corner actually results in splitting the curves there, although the distance of the points there is tiny (`p1 = [1024.04, 750.69]` and `p2 = [1024.04, 750.6899999999999]`). Since the curves are lines, `t` is smaller than `tmax` (`t=0.9999994022573444`) and as a result curves that are far shorter than our geometrical epsilon are created. Not sure if this is the reason why the unite operation fails, but I find it very strange.

**Comment by lehni** [comment]
Interesting indeed!

[Here the sketch with intersections marked](http://sketch.paperjs.org/#S/nVJNa+MwEP0rQpfYYA8aKbJil2UPYQ89LCz0WPfgOopjoshBdtplS/77jj+yDfS2wkia994Mo+f54L46WV7wp6Md6gNPeN3txvitte9wqobQ/mbf2DMmTEwfXVIlNaDIFK7FJsvRCE2g1gYMCrPRGWEC1ctD6Uv/VgV2RirxqxoOj4M9QR1sNdio5D9zpQBVgkIqyI1LNWaAeZKiQSrlMmEAKRII2vwpefywlJP/V86AUhQhSOOUMrDOE0RJUU1Ck6RagJSMxIJkhtQZQ4mg1kmaCciUW2uQYwWlIc8c7Ybao/tmae6M0A+hO9pt57pATZY82F3JR0p+oZpgrZ/JW95TXbnWN0T/039C+8r1drGg9YMN/ahDaOzwOIW2HtrO99FZjs3UdO2cBdc10SwHZ30zHEZyAfZd+FHVh2h/8VPuLIzZR+kZLW/fJ59h24ba2WiBx1XbUVnMjcC5ozP5ZEO1ay99wdQddvf8W1rbb0PX9/S8KGbf2YrMWrGCrSZnVl9yFyuK2YmZvcas9NfbZAS7eHLxLc3EbASBsG+du/spzWsVSU1TO23jYIOMS156mv9Xmqfj9KCeF88v178=)

More analysis soon.

**Comment by lehni** [comment]
[And here the updated sketch keeping the circle size independent of the zoom level](http://sketch.paperjs.org/#S/nVNNi9swEP0rwpc44Ez1EVuxQ+khtLCHQiHH9R68jmKbKJKRnd2yS/57R/7IBnKrMLJm5s1j5mn0GZjirIIs2J9UX9ZBFJT24O23Rr3Duehd85d8J88sInT48LASPAZGE8HWdJOkTNIYnXEsQTIqN3GCPsrEyzY3uXkrHGkZUvwp+vqpV2conSp6FebB71QIYCJilAtIpV7FLAGWRismGVLphEpgaFEGsfzIg+V2ouP/RydBCLQYcKmFkLBOI8Y4WiUCZbSKKXBOEEwRJhGdEMYZiHW0SigkQq9j4J5BxJAmGneJ5eF5MxXXMuh6Z09qZ7V1WGQeOHXIAx/iD6HKKWXG4Jy3LwvdmArDN/yX61joTk0SNKZXrvM4BpXqnwZTlX1jTRe23BdT4tFqBdpW4QgHrUzV17OMZeNKrTzJs7+qCXO07mdR1uHxYga6MXdJPnNDcE1J0F66OjTqnezrolWwG9zhBBqAyudlY6XQWvxHX1FXHJpLlxFx57vTZ05rup2zXYf9h0vygyxQzQXJyGKQbvGQO2mVjVKN0evS93udm3ZqUu1iGpyaUSp0wrHR+u7aqtci5DHO9bD50Qe+zAM/0Ujk34Y1vxw+HX8xs1QPKj2KiRN7Q/nlHdDd7piRb2Rg/7D2vJ078A3kBt/mK876adCyC7Lnl+s/)

With this you can see what the problem is:

On the right hand side, the green path appears to cross the red one, but when you zoom in, you can see that it doesn't seem to. The left part of the right "beam" is not crossing at all, and the right part appears to barely touch. So why is this not an overlap? It may just be another case of not finding an overlap. I would guess that this is the reason why it's not doing the right thing.

<img width="378" alt="screen shot 2017-02-23 at 19 42 30" src="https://cloud.githubusercontent.com/assets/213275/23273819/c9f1faac-fa00-11e6-886f-55fabb6d8159.png"><img width="340" alt="screen shot 2017-02-23 at 19 42 54" src="https://cloud.githubusercontent.com/assets/213275/23273822/cd1b087c-fa00-11e6-84ba-a19b7e83ece1.png">

**Comment by lehni** [comment]
I found a way to adjust this and make the code not see it as a crossing, but the unite operation still fails. Could it be that this is a problem of the new winding code?

**Comment by iconexperience** [comment]
<a href="http://sketch.paperjs.org/#S/vZNNb4JAEIb/CtmTJjjZD/aLpqf+gSY9ggfUrRJxIQtqE+N/74DWYtuDp242BN558s7szHIivtg5kpK3reuWGxKTZb3qvw+lO8Ku6EL5ET1HGYsjOmx8mQkugVElWEKNskxTiaKUGjSj2kiFGmVi/pT73B+KEDUMLbw7Rk3RuACvRbeZnFq33jnftWmW+whXZoUAJjAD5QKs/krY73kcXaGEKbDCfq8kjozkwNU9f8XRKwGKjJYUlL1jLghaL6u6dau0C3t3nl4r5v9e8Y03CcZGPOIJBWv/xg1noNHKSjGyxJyajlYyTIgC5yNR3NpkEzwI5rEclLiQgo1I9J31lmKkMfOzFGsMCNH3WoHSD8zD3J3ygdHkvmHQdqHeupe6qgMOKSfBrXKCd63hv0Lr4Jwfgv1Qg2tRRYe9Lzs3afgUAyjCe1lVI7/1ophwiR0bHn1BwKc5yT3+HYvgim1Tl3gNSJrNz58=">Here is the sketch using the "segment" form</a>. I find this more useful for fiddling around.

Regarding the "not found overlap": I do not think this is the problem. If I move the green corner down a bit as in <a href="http://sketch.paperjs.org/#S/xVPLasMwEPwVo1MCzqKnLTn01B8o9Gj54CZqYuLIRnaSQsi/d+2mrdMGeuwihDQ7zK520Jn4cu9IRp53rl9tSUxWzXq4Hyt3gn3Zh+oteohyFkd0XHhYCK6A0UQwSXViWEoVgkqlkDKaapUgRpkoltZbfyxD1DKU8O4UtWXrAjyV/XZ27txm73zfZbn1EUZuhAAmsALlAkz6WXBYRXzlSJaAEeY7ZBxpxYEnd+koJYEiJ1UUEnPDsb6Io1XddG6d9eHgLvPltVv+T91KLTE1oSNbUjDmLltzBikKGSUmglgxpZOQozUUOJ+A4kvESHwFljEcEvHBFGzCRN3FICkmGNM/OjFagxDDkA0k9ydxa4S+eeNfnljfMuj60OzcY1M3Ad2xJLi1JZhs+a/UJjjnx+TgZnAdoqhw8FXvZi0fJBGE16quJ3qbl3LGFU5r3IZugM8tsR6/xEtw5a5tKvSfZHlxeQc=">this sketch</a> the problem persists.

**Comment by iconexperience** [comment]
Maybe we are doing it still wrong when collecting the intersections. First we should look if end points of curves are close, using geometrical epsilon. If so, these intersections should get `t=0` or `t=1`. Then we can look for more intersections using the curve/curve, curve/line and line/line algorithms. Doing it this way would at least prevent the creation of those super tiny curve fragments.

**Comment by iconexperience** [comment]
If I put the following code snipplet into `getCurveIntersections()` (just before `addCurveIntersections()`) this test case works:

```javascript
      var c1p0 = c1.point1,
          c1p3 = c1.point2,
          c2p0 = c2.point1,
          c2p3 = c2.point2;
        if (c1p0.isClose(c2p0, epsilon))
          addLocation(locations, include, c1, 0, c1p0, c2, 0, c2p0);
        if (c1p0.isClose(c2p3, epsilon))
          addLocation(locations, include, c1, 0, c1p0, c2, 1, c2p3);
        if (c1p3.isClose(c2p0, epsilon))
          addLocation(locations, include, c1, 1, c1p3, c2, 0, c2p0);
        if (c1p3.isClose(c2p3, epsilon))
          addLocation(locations, include, c1, 1, c1p3, c2, 1, c2p3);
```

**Comment by lehni** [comment]
There is a reason why we don't look at these points first: Remember when we had a case where a line-line case would produce 2 intersections instead of only one, because one pair of start-/ end-points where closer to each other than `GEOMETRIC_EPSILON`? I think this case would be back now if we did it i the way proposed above.

BTW, in the code you're proposing, which values is `epsilon`?

And finally the question: Is there a reason for you to still use your own version of the winding code? Does the one in the library not work as well? And if not, could you provide cases where it fails?

**Comment by lehni** [comment]
@iconexperience I just tried your suggestion of adding the code snippet, but it doesn't change the behavior at my end (and the same code is already performed after `addCurveIntersections()`, just in different form).

Did you also change the `epsilon`?

**Comment by lehni** [comment]
Oh, and  #1174 is the issue that breaks if I add this code and increase the epsilon... But the sketch above still fails for me on `develop`. Not sure how you managed to get it work.

**Comment by lehni** [comment]
@iconexperience the strange corner is not at the bottom, btw, it is at the top right. The distance between the found intersection and the actual corner is `6.597945674741107e-10`, the curve-time of the found intersection is `0.9999994022573444`. I just compared with the code that works, and there too this intersection was found. It had the same amount of intersections, the same curve-times, and the same winding contributions. The only difference is that it started in a different segment, and was lucky to not fail. I think this bug would occur in other similar constellations on the old code though, it's just that another case has "unlocked" this particular case on the new code. More investigation needed...

**Comment by lehni** [comment]
Oh, btw: The problem is that the `tracePath()` algorithm now starts exactly in this corner, and somehow doesn't manage to close the path because of the proximity...

**Comment by lehni** [comment]
I now found out that my `tracePath()` branching code isn't actually correctly trying all possible intersections, as well as not crossing, in all intersections. This is sort of huge, it may well mean that many of the other issues that I am seeing could be resolved as well. The fix is fairly trivial!

**Comment by iconexperience** [comment]
Sorry for again another useless proposal. I am currently working on so many things, so I tried to find a quick solution, but doing fundamental things in a hurry is just a bad idea. And I noticed later that the strange corner is at the top right, too.

Anyway, your observation is really interesting. It sounds like this could really be the breakthrough.

**Comment by lehni** [comment]
@iconexperience I have just pushed all the changes that fix this issue here. But it also introduced some new failures with unit tests. After analyzing the first problem, it turned out that this error was caused by the reintroduction of the following snippet (see https://github.com/paperjs/paper.js/issues/1073#issuecomment-270897288):


```js
if (onPath && !windingL && !windingR) {
    // If the point is on the path and the windings canceled
    // each other, we treat the point as if it was inside the
    // path. A point inside a path has a winding of [+1,-1]
    // for clockwise and [-1,+1] for counter-clockwise paths.
    // If the ray is cast in y direction (dir == 1), the
    // windings always have opposite sign.
    var add = path.isClockwise(closed) ^ dir ? 1 : -1;
    windingL += add;
    windingR += add;
}
```

I have then removed it, but now another test case is failing, and I am not sure why yet. I am fairly certain that the snipped above is wrong though, as it leads to wrong winding numbers. I am tapping a bit in the dark with all this though, perhaps you can help me out? Also, I am still waiting for feedback on the winding changes outlined in #1073...

**Comment by lehni** [comment]
[Here the newly failing sketch](http://sketch.paperjs.org/#S/ZVPbattAEP2VRS+WQN7u/eJQ+mBa6EOhkMcoD4qylkWUXSPJDST43zu7kh0TC6HLnDMzZ+ZIH5mvX122ye5f3NTsszJrwnN8/1cP6EDRd+TdG/pbT/u8yv5Ia7AURllpOVHEqFIQgyklTHJLiCGWin4tGGaGcEEFt1pIpkppMSWKMk4k1Vpo3a85NtxSzrQQXCjOrC7XzGJrDNOSc6OVlOq9yoq7yict7KsWqTBThkuhKFdK8lIojRlVXCsrQEjqorHmkkvQowio4+XaaAxigSSoBcWa9VxhIjUx2kBEGilLBhzFjGRCKkmgOl+UHCgepyG8uG3owwCKqmxwz1UWIXYDtYNzfgbPefdN3Xe+BfjC/wzt6n50wIaJO/eGG+cnFytB9iGM3dQFP6Owj8GNM3L03eTyA4vyIIh3Xd9fqWuf6pzBSChdCJyYF0lTrNLFDkuh1k2/06trYqdxqdnAY+gd7kObz3TcO99O++KipemGpk96Hh4huLB2YfhZN/t8d/Sp4JxdoI/KIziWJHw4jvs8Gnu/rw8Ob1M4X0iJmNawmbXCIuBefqJD/dwdxw3iV7ErH85p3bgdwjjCnvMC/UArcG2FNmiVLFrd5C6ebGZLZvRUxIlPxadBwf8a4O+Jzp1nvBnvdguTe72w4hEDeLx8BBR9Q6n6ewivd+fWsXPl4fd8Glz9kpYwZpuHx9N/).

Note that it works alright on `v0,10,2`.

**Comment by lehni** [comment]
When zooming in on the bottom part o Firefox, you can see the situation there:

<img width="496" alt="screen shot 2017-02-26 at 00 36 16" src="https://cloud.githubusercontent.com/assets/213275/23335728/a9264bea-fbbb-11e6-9e99-55cb6f621f8b.png">

What's interesting is that if I scale the active layer up by factor 10, everything works. Looks like winding imprecisions to me, but it's really hard to debug.

**Comment by lehni** [comment]
I just found that it appears to be OK to reduce `windingEpsilon` to `1e-9`, and it solves this new issue here (see 4d3ca746aba7f965257e0eede2b5a93e9fca0616). All tests pass again, but I am not super comfortable with this solution. I really would appreciate to hear your opinion on these open winding questions, @iconexperience... And it would be good to reach a state where we're working with the same code base again, as otherwise we're just tapping more and more in the dark.

**Comment by iconexperience** [comment]
I started looking at our winding code and already found one, albeit unrelated part that can be improved.

In <a href="https://github.com/paperjs/paper.js/blob/develop/src/path/PathItem.Boolean.js#L518">`addWinding()`</a> if the curve is completely left or right of the abscissa's tolerance range, we simply use `t=0.5` to calculate the abscissa's value, because it does not matter which point on the curve we use. This is not wrong, but we should select `t=0`, because this makes the calculation of `a`much easier and faster.

**Comment by iconexperience** [comment]
One part of the code that I find suspicious is this line in `addWinding()`:

<a href="https://github.com/paperjs/paper.js/blob/develop/src/path/PathItem.Boolean.js#L552">`} else if (a3Prev < paL && a > paL || a3Prev > paR && a < paR) {`</a>

I have my doubts that this only handles thoses cases that it is supposed to handle. It may handle other cases, too, which could cause trouble. I will have to think this though again.

**Comment by iconexperience** [comment]
Yes, I am pretty sure that part of `addWinding()` is not fully correct. It should probably be

```javascript
                } else if (a0 != a3Prev) {
                    // A horizontal curve is between current and previous
                    // non-horizontal curve
                    if (a3Prev < paR && a > paR) {
                        // Right winding was not added before, so add it now
                        windingR += winding;
                        onPath = true;
                    } else if (a3Prev > paL && a < paL) {
                        // Left winding was not added before, so add it now
                        windingL += winding;
                        onPath = true;
                    }
                    // TODO: Determine how to handle quality when curve is crossed
                    // at starting point. Do we always need to set to 0?
                }
```
I have not tested if this fixes any of the remaining issues, but at least it passes all unit tests.

**Comment by iconexperience** [comment]
Here is an explanation of the code above. It is supposed to handle cases in which the winding of the path does not change (from upwards to downwards or vice versa) and there is a horizontal curve between two non-horizontal curves. The blue area is the range between `paL` and `paR`.

![image](https://cloud.githubusercontent.com/assets/2122773/23363742/651801fe-fcfc-11e6-87ec-07cab34962a1.png)

In case 1 the winding of the previous curve was not added, so we should add the winding of the current curve.

In case 2 the winding of the previous curve was added, but it is on the opposite side of the blue range, therefore we should add the winding of the new curve.

In case 3 the winding of the previous curve was added. The start point of the new curve is in the blue range, therefore the winding of the new curve will not be added.

In cases 4 and 5 the winding of the previous curve was added. In order to not add the same winding twice, the winding of the new curve will not be added.

**Comment by lehni** [comment]
@iconexperience great, thanks! That's very useful. I will look into it shortly and get back.

**Comment by lehni** [comment]
@iconexperience this looks reasonable. But we still need to figure out what to do with `quality` in these cases? At the moment, it is set to `0`

**Comment by iconexperience** [comment]
@lehni The correct approach for the quality factor would be like this: In all these special cases we have two abscissa values, `a3Prev` (the end point of the previous curve, and `a0`, the start point of the current curve. We should find which of these is closer to `pa` and then adjust the quality factor as if we only had this one point. I will try to figure out how this looks in detail tomorrow.

**Comment by lehni** [comment]
@iconexperience thanks for the PR! This doesn't address the proposed way to handle quality yet, correct?

**Comment by iconexperience** [comment]
Unfortunately not. This only addresses the simple stuff. And the addressed cases are quite rare, therefore we should not see any changes at all, but it had to be done. Sorry for being late on the quality handling, I still have some other things to do first.

**Comment by lehni** [comment]
Another question: Should we use `1` for `t` here also?

```js
Curve.solveCubic(v, io, po, roots, 0, 1) === 1
        ? roots[0]
        : 0.5,
```

**Comment by iconexperience** [comment]
If I see it correctly, if we arrive there something has gone wrong in `solveCubic()` and do not think this happens anymore. The `0.5` is just a fallback, and I think it is alright to take the average here.

**Comment by iconexperience** [comment]
Or maybe we should use 

```javascript
    Curve.solveCubic(v, io, po, roots, 0, 1) > 0
        ? roots[0]
        : 0.5,
```
