### ISSUE TITLE
Boolean edge case involving curve overlaps.

### ISSUE THREAD

**Issue by lehni** [paperjs/paper.js#1263]
I managed to isolate one of the issues I am still encountering in my work on path offsetting:

[Sketch](http://sketch.paperjs.org/#S/jVTLbtswEPwVwRfbgMIul8uXg6KHoAV6K5Cj7YMi07YQmTIkuQFa5N+7lGw3TnooAT043J2dHZH6PYnFIUwWk8fn0Jf7ST4pm02a/yza7Fj0++xzFsNL9oNfZ79XMePRhd0hxL5bZMsRSGO5JOsFaCINGgC80jl5LaS0aB0DCJLW+RJy4PudBKE4kgxoqw1ZSzkJB4qn4J3UGpRar/MbfrKC0FvU1llvlWR+KRwiGqMVgDVM7IVUaNErY6zXiC43wikko50B1oZa61teCZBz9g1m/4EtyThWaAw4iVzdAUv2VjiLxnkCIO8cK5DEYUoZVFwUPQLmd1IJVqiQwzQbo60fPFACASRyt1o5g2RzmRCQki0k5w0RvTdBWWG84Q49G8Uumzz5bshIkp6d9jLZoAWBBUMSSErJhuYShQSpkYiFOWdBJQmIwoNVmqMcayNN+Z1mEcbxVBpvDWkmfKfhvz60UsICao9suSTWwjZoFmqNwlRNO2lwvR6JLwXKuunCZpH17Smcoa5vm+fw0NRNu8imT/UpTG9WHsuiruJukW2Lugur+Dq/X8VVTPu3DR1v37SLxSlWfZilJQbFtqrrgZGXp+3uqZixyDxdvD2Fnk+vFFXsQ3tl2YX++wCEsq+a2A2EJb80dRB1s5uN4aIOcdfv/wopq7asBzHLNYPnqG3Tfi3K/Wx7igPdmD3PzsfsnCSOp24/S2fwcV8cg3gY4MtZHAJDyluMWsWx4eeb79UWm+rEZ1W9wW48HdOq7qFtuo6dnM2zL+xK2EwzNnzXhhCnH3Lfu55WXuep44v/VXgRTfzW8u+F+772+KG9jy704XCNSiMBohsLMpXMPmUD+6+mOdxfSqfKq8j/r6c2FM+DCd1ksVy//gE=)

Note that this works in `v0.10.2` but fails in `develop`. That doesn't mean the last release is better, the issues also occur there, just with slightly different values.

**Comment by lehni** [comment]
One of these intersections sure looks wrong!

<img width="696" alt="screen shot 2017-02-26 at 13 16 42" src="https://cloud.githubusercontent.com/assets/213275/23339567/ddd1e056-fc25-11e6-9df4-78bfd9cdbfb2.png">

**Comment by lehni** [comment]
It's the last segment connecting back to the first at the same location, creating a curve of length 0. This is a bug in itself, but filtering it out doesn't resolve the issue.

**Comment by lehni** [comment]
Here an updated version with that crossing gone:

[Updated Sketch](http://sketch.paperjs.org/#S/jVRNb9swDP0rRi5JAFejKOorxbBDsQG7DegxycFxlcSoIwe20wIr+t9H2WnWtDtMQGLriXx8fJL8MonFIUwWk/vH0Jf7ST4pm4c0fyra7Fj0++xrFsNz9otfZy+rmPHowu4QYt8tsuUIpLFckvUCNJEGDQBe6Zy8FlJatI4BBEnrfAk58P+NBKE4kgxoqw1ZSzkJB4qn4J3UGpRar/MrfrKC0FvU1llvlWR+KRwiGqMVgDVM7IVUaNErY6zXiC43wikko50B1oZa62teCZBz9hVm/4EtyThWaAw4iVzdAUv2VjiLxnkCIO8cK5DEYUoZVFwUPQLmN1IJVqiQwzQbo60fPFACASRyt1o5g2RzmRCQki0k5w0RfTRBWWG84Q49G8Uumzz5bshIkp6d9jLZoAWBBUMSSErJhuYShQSpkYiFOWdBJQmIwoNVmqMcayNN+Y1mEcbxVBpvDWkm/KDhvzZaKWEBtUe2XBJrYRs0C7VGYaqmnTS4Xo/EbwW6vm0ew11TN+0im27qU5herdyXRV3F3SLbFnUXVvF1fruKq5gOqijrpgvDOR3BdILb0PEBHpZPserDsMSg2FZ1PZTh5Wm72xQzlpmnHx9QoefTC0UV+9BeWHah/zkAoeyrJnYDYckvTR1E3exmY7ioQ9z1+79Cyqot60HMcs3gOWrbtN+Lcj/bnuJAN2bPs/NFOyeJ46nbz9ItvN8XxyDuBvjtNg6BIeUtRq3i2PDz3Y61xUN14tuq3mFXRo9pVXfXNl3H9s7m2Td2JTxMM96FXRtCnH7K/bgVaeV1njo+b8pTFZ5FE3+0/IHhvi89fmrvswt9OFyi0kiA6MaCTCWzL9nA/rtpDrdvpVPlVeQv2KYNxeNgQjdZLNevfwA=)

**Comment by lehni** [comment]
Ha, I spoke too quick! That crossing gone does indeed seem to solve the issue. Hmm! 🤔

**Comment by lehni** [comment]
Ok, as so often, it's way more complicated than that... The problem is that `resolveCrossings()` doesn't resolve this correctly in some cases, because it doesn't perform any checks, it just crosses at each encountered crossing. And getting rid of this one wrong intersection through `path.closePath()` as opposed to `path.reduce()` causes the difference: While both remove the intersection, they result in a different sequence in the segments that causes the different behavior: Calling `reduce()` has the effect of moving the first segment to the end of the path, which doesn't change the geometry of the closed path, but does break `resolveCrossings()` in this case. I believe it has to do with the even amount of intersections found in the overlapping area (which is not detected as overlapping, see #1262). If an even amount of intersections are encountered in sequence, and `resolveCrossings()` crosses at each of them, we end up back on the old trail, and do not separate the two shapes.

@iconexperience do you have an idea how we could solve this? I can't think of a way right now, but I have a feeling that resolving this will once again improve things a lot in those remaining edge cases...

**Comment by lehni** [comment]
So after giving this quite a bit more thought, I have an idea for a solution that may better handle all these issues with overlaps and other edge-cases, while at the same time improve speed, and I got to it thanks to this issue her and my analysis above:

So the problem here is that `resolveCrossings()` doesn't correctly resolve the sub-paths that lie on top of each other, because it doesn't have the intelligence to decide when to cross in a found intersection, and when to stay on the current path. `tracePaths()` has this intelligence when performing the actual boolean operation, thanks to the internal branching mechanism and calls to `isValid()` which tell it if any given encountered segment is valid (was a valid winding contribution) or not. If `tracePaths()` ends up in a place where there is no way forward, it goes back to the last crossing and tries other possible directions. 

The problem is that defining `isValid()` for `resolveCrossings()` isn't trivial.

 So my though was, can we get rid of the need for `resolveCrossings()` all together? What if we just subdivide all involved paths at all the encountered intersections, regardless of wether they are crossings, touching points or overlaps, and let the branching mechanism of `tracePaths()` handle the rest?

The problem here is that the way `getWinding()` is currently implemented, it assumes that there are no overlapping sub-paths. In order for this to work as it should, we need to teach it how to handle those cases.

And this where I could useyour help, @iconexperience. Here is what I have thought of so far:

- Instead of a global `windingL` & `windingR`, we have to count these values on a per path basis, based on the path owners of the curves in the `curves` array. We can do so by using the path id to group these values in an id based lookup table (for paths that are part of a compound-path, we need to use their compound-path parent)
- These grouped values then need to be flattened on a per path id basis, taking each path's winding-rule into account.
- The flattened values then are combined again

Once we have distributed corrected winding contributions to each segment in this way, we can simply perform `tracePaths()` and it should always produce the right result. No more need for `resolveCrossings()` (but we do need to check for self-intersection as well as intersection with the other path when searching for all intersections), and no more need  to distinguish crossing points (another unstable part of the code, as you know), we simply split in every found intersection and let the branching code handle the rest.

Since this reduces the amounts of required passes to one, I believe the result should perform faster than our current implementation, while at the same time handle edge cases much better. I'm excited to implement and test this soon, but am hoping to get feedback on the winding part above from @iconexperience before I start.

**Comment by iconexperience** [comment]
@lehni I would love to assist, but I am stuck at trying to understand your idea. What do you mean by "The problem here is that the way getWinding() is currently implemented, it assumes that there are no overlapping sub-paths."?

**Comment by lehni** [comment]
With sub-paths I mean areas within the same path that are covering each other. We are currently getting rid of them in `resolveCrossings()`, no?

**Comment by lehni** [comment]
I mean, `getWinding()` is currently not taking winding rules into account, `resolveCrossings()` is, but we will have to respect those if we are to remove the `resolveCrossings()` step, and I am just wondering how will do this correctly, imagining for example two compound paths, of which one even has self intersections in one of the child-paths.

**Comment by lehni** [comment]
Actually, that wasn't precise enough. `resolveCrossings()` only resolves the crossings, the flattening happens in `preparePath()` which then calls `path.reorient()` right after. But if we don't resolve the crossings, we can't call that, so we need to teach `getWinding()` how to handle winding rules properly on a per path basis.

**Comment by iconexperience** [comment]
I think I get the basic idea. Have to go to bed now, but my guts tell me that it's not really difficult to implement. More tomorrow.

**Comment by lehni** [comment]
Going back to the original issue here, here a reduced sketch that shows the problem:

[Reduced Sketch](http://sketch.paperjs.org/#S/jZRNa9tAEIb/yuJLHFC3M7uzXwqlB9NCb4UcbR9UZWOJ2JKR5CQQ8t87Kympk7TQxSDvzLw78z4S+7RoikNc5IvruziU1SJblO1N2t/X8UEeiqGrH8UXsUaUltBohV7ZoMljJmD8/S3zibwB6Qk0AgTrKMWM1iDBkNMUyKhgtptm09wXnShP3X1EbtPEB7FKm+WaXEjFZMAAn6FNRsFIRKec54ACpG22/oQgNdeQBeOMJecoI+lB8xaCR2NAa64LErVyKmhrXTBK+cxKrxVZ4y1wE2WM4TIiJ0kFp4zzLjiN3BSlV0pZazSAs9vLq7OZ1buZrefe1oJHxWIPPExw0jtlfSAACt6PQ2upAFDxeEZ7q8hlmCKAyG7JB0uU3BlJ4IDpAiEi28lQSQQ0ikgxae8gmSPtpGXKKgQ2zaxsluhZskgYmFfAae5Nc3tqyqFuG9FX7cM09WgkE2W7b7tL8bRpBK/k8FgM1ezvJ/9dzqm0+rg7xGboc7Ee5XIO8Gt+s1fb7Ew0dO1dXKU++dTuQ/K6LPZ1s8vFbbHv45R9TpM/p+HfzczNLrp4c5Hy71KKU7suxuZisp3s1M0Qu54NTWK5i8OPMRRHIv2sTIKSt+0+yn27W04yuY/Nbqj+nFbWXbmP6bj1loNz1W3bfSvKavmCeVK/Up1F8njqq2Xiel0VxyhXY/icbxmTLp9mlseWn2esuuKmPjF7/S+4k6zuV13b98xzeSm+TqxE/gLmP9mP8Gfb6UZom+8dXxjs+9XjB3sfKQzx8FqVVgrIfmrIR6H4LM7um5eMfLx6+wnw7fSri8XdCKRf5Ovt828=)

The two curves are almost overlapping, but no overlaps are found. From the tests today I found that when 3 intersections are found in this situation, the example above works as it should. When the one in the middle is not found, as it happens regularly currently, then things go wrong. I just realized also that if I go back to the state of mid February 2017 before I did all the adjustments, it works reliably too! I'm just putting it here for further investigation.

**Comment by lehni** [comment]
@iconexperience I ended up reverting this optimization again, see ecc1edb6ea3cbec4aaef560a332ce62eb5cf4b63, due to the observation described above. I don't think it impacts performance substantially... Still investigating all these things further.

Shall we dedicate this issue to the winding code changes described above?

**Comment by lehni** [comment]
@iconexperience I've moved the discussion above regarding the changes to `getWinding()` to a new issue #1285.

**Comment by lehni** [comment]
This was fixed by 3ff5560c0c16a1ecd581ab558d6682becd6ddd75
