### ISSUE TITLE
Incompatible with node v7

### ISSUE THREAD

**Issue by Chaoste** [paperjs/paper.js#1266]
Hey,

I already saw, that there is a commit regarding this issue and the package.json states, that paper.js supports node <8.0.0. But if I call "yarn add paper" (the faster solution for "npm install paper"), I get the following error:

> $ yarn add paper
> yarn add v0.21.3
> [1/5] 🔍  Resolving packages...
> [2/5] 🚚  Fetching packages...
> error paper@0.10.2: The engine "node" is incompatible with this module. Expected version ">=4.0.0 <7.0.0".
> error Found incompatible module
> info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
> 
> $ node -v
> v7.0.0

As you can see, it pulls the newest version (0.10.2), which should support node v7.

If I try to install it using npm, it throws another error due to some dependencies problem:

> $ npm install paper
> nexboard@2.0.0 /Users/Thomas/work/repos/nexboard2.0
> ├── paper@0.10.2 
> ├── UNMET PEER DEPENDENCY react-addons-css-transition-group@^0.14 || ^15.0.0
> ├── UNMET PEER DEPENDENCY react-dom@^0.14.0 || ^15.2.0
> ├── UNMET PEER DEPENDENCY react-redux@^3.0.0 || ^4.0.0 || ^5.0.0
> └── UNMET PEER DEPENDENCY redux@^3.0.0

Thanks in advance,
Thomas

**Comment by sapics** [comment]
Hello @Chaoste

As you said, current develop branch support v7. However, v0.10.2 have not support v7, yet.

**Comment by lehni** [comment]
I really need to wrap the current constructions site up for a new release very soon :/

**Comment by Chaoste** [comment]
I will try later, if I can do a hotfix by installing from this repo.

**Comment by lehni** [comment]
v0.10.3 is out with support for Node.js v7

**Comment by Chaoste** [comment]
May I ask if it is necessary to not allow v8 ? I just wanted to udpated all my dependencies and failed using node v8 because paper.js requires <8.0.0 .

**Comment by sapics** [comment]
Current version fixed it :)
