### ISSUE TITLE
wrong selection on raster with SVG

### ISSUE THREAD

**Issue by Skalkaz** [paperjs/paper.js#1267]
Sketch:
http://sketch.paperjs.org/#S/LY+7bsMwDEV/RdCSBAikJcigoluBLsnSjnFhqDJrE7ZJQQ97MPzvlZpyO8C5vOQmyc4gjfwcIblBnqXjrnJDiw0ih0m8isOQko9G6+wntp1accQZOrSKQ68r+Ura8TwzRX3Rl6t+CxzZDzjZ9h0I2hvSaHto79aruPSHl2dDsDFBKCUEq/j4g+MWOQcHptafheeICZmMWBBW5YCKs59KvqFnWjHdyl1lyU8mV93jSWwNiTL/RoQJXILqpJChob3ky7ffAezoGSlFaR5f+y8=

**Comment by lehni** [comment]
Hmm strange. On Safari, this produces the expected result. And on Firefox, the resulting raster has width and height of 0...

**Comment by lehni** [comment]
This looks like a Chrome issues… Look at [this sketch](http://sketch.paperjs.org/#S/JY+xagMxEER/RajxGYzUmBQX0gWCIalSxuFQdBtpudOukHS+wvjfsyLbzcwyj7lrcgn0qD8XaD7qk/Y8d31zRW1lVS/qEFvLdbR2yyu72ey4YIIZneESbFe5K+s5JaZqz/b8ZF8LV84RVze9AcH0jrS4ANOHy6bewuH5Sp2AKQiBYFeXJPFwFF88w9RREv1u5BsyDUd1v5KS88LgFczKYeivO84tnnqTiYAhtt7x+K+pxUuHzBBLpv0UcEtmpFb1+PX9+AM=), in which I create a normal `HTMLImageElement`: It also reports these wrong dimensions in Chrome.

**Comment by Skalkaz** [comment]
On Firefox 52.0 + Ubuntu 16.4 MY sketch does show the image, still the onLoad triggered and a zero sized object is selected in the center.

On Firefox 52.0 + Ubuntu 16.4 YOUR sketch gives 0,0 as dimensions.

Other svg files seems ok in both chrome, ff.

(Maybe not just the fruit fly is the mutant in the image, but the svg format, too.)

Feel free to close the issue. Thank you for your response.

**Comment by lehni** [comment]
Haha, mutant SVGs indeed! One could argue, the whole SVG standard itself is a bit of a mutant, though. : )
