### ISSUE TITLE
Curve type

### ISSUE THREAD

**Issue by seriouslyfluffy** [paperjs/paper.js#1274]
Hello. Can i draw curve like [this]( https://youtu.be/5GI3dfmDtAk)?
And how?

**Comment by lehni** [comment]
Yes, those look like bezier curves, the core component of paper.js `Path` and `CompoundPath` items, through their `item.segments` list. You need to read up on this a little in the [tutorials](http://paperjs.org/tutorials/paths/working-with-path-items/) and [reference](http://paperjs.org/reference/path/).

Also, this is a bug database, not a support forum. Please direct future question at the mailing list:

http://groups.google.com/group/paperjs

**Comment by seriouslyfluffy** [comment]
Thank you!
