### ISSUE TITLE
Node.js canvas is not loading

### ISSUE THREAD

**Issue by kareljan** [paperjs/paper.js#1276]
I'm building an electron app and I'm trying to generate an image trough node.js.
But for some reason canvas does not get loaded with version 0.10.3. I get the following error.

Unable to load Canvas module. Running in a headless context.

What am I doing wrong? A fragment of the code I use.
```
    var paper = require('paper'),
    fs = require('fs');
    paper.setup([640, 480]);

    // Create a Paper.js Path to draw a line into it:
    var path = new paper.Path();
    // Give the stroke a color
    path.strokeColor = 'black';
    var start = new paper.Point(100, 100);
    // Move to start and draw a line from there
    path.moveTo(start);
    // Note that the plus operator on Point objects does not work
    // in JavaScript. Instead, we need to call the add() function:
    path.lineTo(start.add([ 200, -50 ]));
    // Draw the view now:
    paper.view.draw();

    // var fullpath = __dirname + '/test.png';

    // Saving the canvas to a file.
    out = fs.createWriteStream(filename);
    stream = paper.view.element.pngStream();

    stream.on('data', function(chunk) {
        out.write(chunk);
    });

    stream.on('end', function() {
        console.log('saved png '+filename);
    });
```

What am I missing?

**Comment by lehni** [comment]
node-canvas is a native dependency. Are you following the steps to compile it correctly for use in Electron?

https://electron.atom.io/docs/tutorial/using-native-node-modules/

**Comment by kareljan** [comment]
Thanks

that was it! that was the missing piece. Everything is working now.

**Comment by lehni** [comment]
Great to hear it! I am reopening this issue to remind myself to add a line about this in the README.md
