### ISSUE TITLE
Raster is not able to retain the irregular shape of source image

### ISSUE THREAD

**Issue by petrgazarov** [paperjs/paper.js#1279]
Hey! Thanks a lot for the work, great library.

I'm new to Paperjs, and I recently have tried to create a Raster from an image that originally has an irregular shape (non-rectangular). Then, I placed some `onMouseEnter` and `onMouseClick` event handlers on it.

What I found was that, even though the original image is irregularly shaped, by the time it makes it into the canvas, it has a rectangular shape, which causes my events to work on the full rectangular, instead of having the boundaries of the original image.

This is understandable, since `<img />` tag itself only works with rectangle shapes and Raster gets the image from the `<img />` tag. It would be great if Paperjs was able to retain the shape of the original image. Is there already a solution to this problem? Thanks!

**Comment by lehni** [comment]
Rastered images are always rectangular. I guess what you mean is that your raster image has an alpha channel and some transparent pixels?

At the moment, Paper.js does not take transparent pixels into account during hit-tests. We could add this for Rasters of course, hidden behind a `hitTest()` options property. The question then is, when is a pixel considered transparent? In paper.js, alpha values can be anywhere from 0 (fully transparent) to 1 (fully opaque). Value in between means the pixel is to some degree transparent (often used for shadows, antialiased edges, etc).

My suggestion would be to add `options.alphaThreshold`, and if it is set to a a value, then only actual pixels with their value above the threhsold would be considered opaque. If it's not set, then it would behave asbefore.

**Comment by petrgazarov** [comment]
@lehni Ah, gotcha. Thanks for the suggestion.
