### ISSUE TITLE
divide mathod return closed path in paper.js v 0.10.3

### ISSUE THREAD

**Issue by niravdhanorkar** [paperjs/paper.js#1282]
I am using divide method.  in newer version it gives me trace path of divided object.

bit same as 
https://github.com/paperjs/paper.js/issues/1221

(see below image for split and trace path example.)
want split path: 
https://cloud.githubusercontent.com/assets/10217168/21606970/5e909cde-d1b3-11e6-8f46-1536ea362274.png

anybody has any solution please suggest me.

**Comment by lehni** [comment]
I was hoping you would provide more info in #1221 as a comment. We don't need two issues for the same problem : )
