### ISSUE TITLE
Sketch editor http://sketch.paperjs.org/ fails with long sketches

### ISSUE THREAD

**Issue by glmnet** [paperjs/paper.js#1287]
It looks to me that the thing is failing when trying to put on the url the /S# with a very long encode(JSON.stringify(script)); so it fails with a message saying Line 131: Access is denied. May be it should be ok to resign to this feature for long scripts

**Comment by lehni** [comment]
Yes that's a known limitations of a hack that allows us to not have to store data by ourselves... Eventually it would be nice to allow gists for this purpose, but I haven't gotten there yet.

**Comment by lehni** [comment]
I guess I can close this as a won't-fix for now. There are plans to generally improve sketch though.
