### ISSUE TITLE
paper.project.getItem cannot find groups

### ISSUE THREAD

**Issue by lucapretti** [paperjs/paper.js#1288]
Hello.
I am trying to interact with Paper.js items from a javascript function. (from outside the paper.project).
If I try to get a pointer to a group by its name using  paper.project.getItem() I always get a null pointer.
I can obtain a pointer to any item inside or outside a group by its name but not the group itself.
Thank you for your help...

**Comment by lehni** [comment]
Could you provide a simple test case on http://sketch.paperjs.org/ ? thanks.

**Comment by lucapretti** [comment]
Done.... 
In the sketch I included also the piece of javascript from witch I try to access the group....

**Comment by lucapretti** [comment]
[Example.txt](https://github.com/paperjs/paper.js/files/858838/Example.txt)

**Comment by lehni** [comment]
But it doesn't demonstrate the query? How can I reproduce the problem?

**Comment by lucapretti** [comment]
To reproduce the problem you can :
1) create a canvas with one group in it named 'groupname'
2) create a javascript function like this:
function testgroup () { 
var item = paper.project.getItem({
                        name: 'groupname'
                    });
             if (item != null) {
                    doSomethingWithItem(item);
                    }
}
3) Create a button that calls the testgroup() function
You will see that the doSomethingWithItem() function is never called because item is always null.
If you try to get another item (even inside the group) all is working as expected.

**Comment by lehni** [comment]
Hmmm…. 

It like this is working fine:

[Sketch 2](http://sketch.paperjs.org/#S/dY07DsIwEAWvstomiYRyAEfUETUlTmHMyuS3a9kLFFHunvgAvGqmGL0N2a2EBu8zqX/jBb28in9dgpDkE+EKTD/oC9ebZThXGgOVUtbK8t50li174SwLtYuEOiaZyGsbSG9Ka/4XNt35+Ezk5igja0bzGPYD)

Please note that variable names are not group names. You have to set `group.name` to the string that you're matching against. There is no way for JavaScript to know what the name of variable is that is referring to a group. There may be multiple variables referring to the same group, also, e.g.:
```js
var group1, group2;
group1 = group2 = new Group();
```

**Comment by lucapretti** [comment]
You are right, I forgot to set the "name" property of the group.
Thanks a lot for your help.
