### ISSUE TITLE
Hit test doesn't work with circle properly

### ISSUE THREAD

**Issue by Yorkst** [paperjs/paper.js#1291]
I'm using the code from mouseenter example, but instead of view.center place the circle at (50;50)

When the cursor is above the circle, the circle should become red. But it works only with upper left part of it.

Tested in Firefox, Chrome, Windows 8

The snippet is here:

http://stackoverflow.com/questions/42945437/paper-js-event-example-incorrectly-tests-for-mouseenter

```
$(document).ready(() =>
{
    var canvas = document.getElementById("mainCanvas")
    paper.setup(canvas)
    console.log("creating circle")
    var path = new paper.Path.Circle({
        center: new paper.Point(50,50),
        radius: 25,
        fillColor: 'black'
    });
    console.log("created circle")
    // When the mouse enters the item, set its fill color to red:
    path.on('mouseenter', function () {
        this.fillColor = 'red';
    });
    // When the mouse leaves the item, set its fill color to black:
    path.on('mouseleave', function () {
        this.fillColor = 'black';
    });
})
```

**Comment by Yorkst** [comment]
Removing `resize` from canvas fixes it. Still interested, if paper.js can work with resized canvas

**Comment by lehni** [comment]
Are you using the CSS to correctly resize the canvas? If the pixels in a HiDPI paper.js canvas don't align then the hit-test will be off:

http://stackoverflow.com/a/29103200/1163708

**Comment by Yorkst** [comment]
It worked. Thanks!
