### ISSUE TITLE
importSVG is not a function

### ISSUE THREAD

**Issue by SimoneMSR** [paperjs/paper.js#1293]
When running the following code I get this error "**paper.project.importSvg is not a function**"

html 

`<script type="text/javascript" src="../node_modules/paper/dist/paper-full.min.js"></script>`
`<script type="text/javascript" src="code.js"></script>`
`<canvas id="canvas" width="1000" height="500"></canvas>`

js

`function SVGSymbol(_paper,elem){`
	`var a = new Symbol(paper.project.importSvg("circle.svg"));`
	`elem.parentNode.removeChild(elem);`
	`return a;`

`}`

`window.onload = function() {`
	`	// Get a reference to the canvas object`
		`var canvas = document.getElementById('canvas');`
		`// Create an empty project and a view for the canvas:`
		`var p = paper.setup(canvas);`
		`p.project.clear();`
		`var a = SVGSymbol(p,document.getElementById('svg'));`
`}`

version "paper": "0.10.2"

**Comment by lehni** [comment]
`importSVG()` isnt' `importSvg()`. JS is case-sensitive.
