### ISSUE TITLE
Trouble with tool function of paperjs

### ISSUE THREAD

**Issue by namth2** [paperjs/paper.js#1295]
Hi Every body

When I study about [Using event.delta](http://paperjs.org/tutorials/interaction/working-with-mouse-vectors/#using-event.delta), I have moved example source code to separate file javascript and import its to html file,  however the result is not my expected. Tool is only draw lines(-------)  instead of fish bone (-|-|-|-).
Is there a problem with the way I did it? 
Please help me!!!

This is my created source code: 
[StudyPaperjs.zip](https://github.com/paperjs/paper.js/files/881189/StudyPaperjs.zip)

- index.html & tool.js: separated file -> result Not OK
- index2.html: single file -> result OK

Thanks & Rgds,

**Comment by lehni** [comment]
As you're defining your tool in JavaScript and not PaperScript, operator overloading does not work in your code. This means that this statement:
```js
    var top = event.middlePoint + step;
    var bottom = event.middlePoint - step;
```

isn't producing the desired result anymore. In JavaScript, you need to write mathematical operations involving Point objects like this instead:

```js
    var top = event.middlePoint.add(step);
    var bottom = event.middlePoint.subtract(step);
```

**Comment by lehni** [comment]
Read more here: 

http://paperjs.org/tutorials/getting-started/using-javascript-directly/#setting-up-a-scope

**Comment by namth2** [comment]
@lehni : Thanks you for your support!!!
