### ISSUE TITLE
bounds.width = 0 in IE.

### ISSUE THREAD

**Issue by ValeriyDyachenko** [paperjs/paper.js#1299]
Property bounds.with is 0. This problem exists in IE when refresh page or open this page in new tab.

**Comment by lehni** [comment]
The bounds property of what exactly? Could you provide a test-case for replication, and a better description? Thanks.

**Comment by ValeriyDyachenko** [comment]
Hi! 
http://sklad.rent/catalog/6851/
You will see an error in the console. The error occurs if you open multiple tabs in sequence with this link. This error depends on the power of the computer. On weak computers, it arises immediately, on computers more powerful on the 4 tab and on.

**Comment by lehni** [comment]
It's really difficult to chase down a bug in a full website, and I don't have the time to do so. Could you please provide an isolated test case and explain what exactly is happening? Please also provide the version of your browser, and the exact error message you are seeing. Thanks.

**Comment by iconexperience** [comment]
@ValeriyDyachenko Sorry, but this is not a useful bug report at all. There is no way anyone would ever starting to look into this without much more detail or if possible a proper test case. From the bug description it is not even clear if this has anything to do with Paper.js.

**Comment by sapics** [comment]
The test case looks very difficult to detect the bug in the paperjs.
I will close this issue. But feel free to comment if you have any information, we will reopen again.
