### ISSUE TITLE
Errors with browser autofill

### ISSUE THREAD

**Issue by kumarharsh** [paperjs/paper.js#1302]
When I open a website using paperjs using a browser with autofill enabled, paperjs-full keeps throwing error that `key.length is undefined`. [This line](https://github.com/paperjs/paper.js/blob/6e7fe67a8ddc93d41b620ef8f02a503d2920769b/src/event/Key.js#L88) causes the problem - when the browser autofills, the event is a `keyDown` event, but there is no `event.key` causing this to fail.

**Comment by DominicSachs** [comment]
Any plans to fix this issue?

**Comment by cs-NET** [comment]
This is what I came up with as a fix. If key is undefined return '', one of the calling function checks length > 1 so had to return something.

```
return keyLookup[key] || (key ? key.length > 1 ? Base.hyphenate(key) : key.toLowerCase() : '');
```

**Comment by petrbrzek** [comment]
We have a problem with this in Avocode. I've seen there is MR for this #1375 (dunno if the fix is correct). cc @lehni

**Comment by petrbrzek** [comment]
Btw: we don't need paperjs events. Is it possible to disable them?

**Comment by petrbrzek** [comment]
@lehni This is good to close https://github.com/paperjs/paper.js/releases/tag/v0.11.5
