### ISSUE TITLE
Attaching event listeners to DOM node when paper is not used

### ISSUE THREAD

**Issue by kumarharsh** [paperjs/paper.js#1303]
Hi, while investigating #1302, I discovered that paperjs has attached a lot of events listeners to my DOM even in pages where I'm not using paperjs - such as login page, etc. Also, I actually don't need any of the event listeners as I'm using paperjs just for non-interactive drawing.

Is there an 'explicit' way of attaching event listeners too, so that I can attach listeners only when I need them, rather than paperjs attaching them automatically?

**Comment by sapics** [comment]
@kumarharsh Sorry for late response.
Now, we are tackling this issue in #1491, thus I will close this.
If you have any information about this issue, it helps us to comment to #1491.
