### ISSUE TITLE
[Question] Animate shape

### ISSUE THREAD

**Issue by KuneStudio** [paperjs/paper.js#1306]
Hi !
Sorry if it's not the place to ask that question but I need some guidance. 
I'd like to animate a shape with paper.js .
The shapes are created from SVG.
I've succesfuly imported the svg and so I have the paths, but now I can't figure out how to start to animate them.
The idea is to just give them an little waving effect, like you can see here : http://codepen.io/hirasso/pen/mJeRXG
But with all the code on the codepen, I can't figure out what is necessary and whats not. 
(I don't need the mouse effect :) ).

If you have some clue that would be awesome !
Thanks a lot !

**Comment by lehni** [comment]
Please use the [Mailing List](http://groups.google.com/group/paperjs) for questions. Github issues are for tracking bugs. Thanks!
