### ISSUE TITLE
Scaling layer does not scale strokeWidth of children

### ISSUE THREAD

**Issue by jonathanazulay** [paperjs/paper.js#1307]
I'm trying to scale (stretch) a layer containing some paths. But the strokeWidth does not change. 

Take a look at this sketch
http://sketch.paperjs.org/#S/bVBNq8IwEPwrS04NlNpXEUTx1KsHwcM7GA8xWWloTCTNeyLifzdbi194Cbs7k5nZvTAnD8hmbN1iVA3LmfKa+n8ZwMozBliAwxMsqc64cA+g+kTu2FHGZkBWqSxqE5TFrO+9cTGryjKH9PAcxiWfC0c/ii4G32LtrSdHwXb2DwV7A3+N7qWnr1aUouco6x1SjK9yATWpCddHL6TWdWOszojMh2n1Pq74k98pmXb4KSYcRiNYUwexQdib0MXhTieT0lFsuJsLl665CyjbI+3dsdlme70B

Is this the expected behaviour? I thought that's what strokeScaling was for.

I'm on version 0.10.3

**Comment by lehni** [comment]
Use `applyMatrix`, [see here](https://groups.google.com/forum/#!searchin/paperjs/applymatrix%7Csort:relevance/paperjs/4EIRSGzcaUI/seKoNT-PSpwJ):
http://sketch.paperjs.org/#S/bVDBSsQwEP2VIacGSrdWBKnsqVcFYQ8ejIfZZpaGxqQk0XVZ9t/NdIta8BLmzXt582bOwuE7iVbsRkr9IErRe834EwNYPFGALTg6wiPXxRlwmuzpCVMwXy0c0EaCi1TuR96s9Jm5chOmYWGec1l1JvSWihl741LR1HUJ+ZEl3NbyQTn+UcUU/Eidt55zKLG3H6TEinwxera+/zuKU8ya3npHHONfu0Ca3ZSbo1eodTcYqwsWy6XbrNuN/NXHHvMON9WdhM0GdowgDQQHE2Jarnc0OR3Hhutw5fKN94FwnHjvKNrXt8s3
