### ISSUE TITLE
All I want is `paper-core.js` and I want to install it via NPM without installing all those dependencies without warning.

### ISSUE THREAD

**Issue by tom10271** [paperjs/paper.js#1308]
Is it possible? I don't want to use bower. My manager is not happy with installing so much dependencies that we are not going to use at all.

If it is impossible then we can't go with paper.js

Thanks

**Comment by tom10271** [comment]
Ok everyone if you are in the same situation that you want to install paper.js only via npm, then you need to mark it as `no-optional`

```
{
  "dependencies": {
    "paper": {
      "version": "^0.10.3",
      "no-optional": "true"
    },
```

**Comment by tom10271** [comment]
Maybe this should be documented near `Installing Paper.js with bower` or something like that

**Comment by simonemazzoni** [comment]
@tom10271 does it works for you? I just tried, but it doesn't work. It simply ignores the paper package. 🤕

**Comment by tom10271** [comment]
I am sorry I checked it again it is actually not working... The only way to install Paper.js with optional dependencies is run `npm install --no-optional` which the flag can't be stored in package.json

**Comment by tom10271** [comment]
@simonemazzoni I have a new solution.

First install it with command:
`npm install paper --no-optional`

Then run `npm shrinkwrap` to lock dependencies versions.

Once locked other developers can simply run `npm install` to install all packages required.
Installing/uninstalling packages will also update `npm-shrinkwrap.json` automactically.

However I do experience npm warning when I tried to install a package which npm unexpectedly attempt to install `node-canvas` but it shouldn't be a problem. If you serious care about the warning then always run `npm install` with flag `--no-optional`
