### ISSUE TITLE
Will you plan to support blend mode in the future?

### ISSUE THREAD

**Issue by tom10271** [paperjs/paper.js#1310]
The blend mode in Photoshop.

CSS have some degree of supporting it.

https://css-tricks.com/basics-css-blend-modes/

Actually, I am not going to use this feature in the near future but think Paper.js is working insanely and seriously well and love to see it goes ever further.

**Comment by sapics** [comment]
Paper.js has blend mode as http://paperjs.org/reference/item/#blendmode
