### ISSUE TITLE
Multiplying Math.random() is causing an unexpected token error

### ISSUE THREAD

**Issue by notclickable** [paperjs/paper.js#1314]
In sketch.paperjs.org, across chrome,safari, on OSX & Windows:
var i = Math.random(); 
// works as expected
var i2 = Math.random()*2;  
//SyntaxError: Unexpected token ','

**Comment by lehni** [comment]
Interestingly enough, if I write it with spaces around the multiply sign, it works:
```js
var i2 = Math.random() * 2;
```

Looks to me like a case of wrong string indices used. Thanks for spotting! Will fix ASAP.
