### ISSUE TITLE
Point and Pivot can not link to a Point object

### ISSUE THREAD

**Issue by tripdragon** [paperjs/paper.js#1319]
Paper.version => "0.10.3"
I am trying to assign a pivot to a point so i can update one point and have multiple points positions etc update to it. I read through the source a bit and see that its returning a point every time, it did have a linked bit in there but I don't understand exactly how its working and its not in the docs I think. Checking again.
Can I force this somehow without having to make a manager function?

```
var rectangle = new Paper.Rectangle(new Paper.Point(50, 50), new Paper.Point(150, 100));
var path = new Paper.Path.Rectangle(rectangle);
path.fillColor = '#e9e9ff';
path.selected = true;

g = new Paper.Point(20,20)

path.pivot = g

g.x = 100

path.pivot => {_x: 20, _y: 20}
```

same goes for this, it will only update once since its being set internally it seems
```
path._segments[0].point = g
```

location in source
https://github.com/paperjs/paper.js/blob/develop/src/item/Item.js#L791

Oh, interesting I can access the private _pivot and link that, but it does not seem to move the path around after setting it. 
Should I keep trying to solve this this way, will this break some caching routine internally to the engine? Or do you have a known way I could do this internally?

**Comment by lehni** [comment]
Yes those are accessors, and the values are stored internally.

This works:

```js
path.pivot = new Point(20,20)
var g = path.pivot;
g.x = 100
```

I don't consider this a bug. It's how things are designed in paper.js, allowing changes to be tracked and caches invalidated. We won't change this.
