### ISSUE TITLE
Splitting paper.js into two libraries

### ISSUE THREAD

**Issue by photopea** [paperjs/paper.js#1325]
Hi, I am looking for a library to perform some operations on closed bézier paths.  I need boolean operations, hit-test, nearest point and [dilation](https://en.wikipedia.org/wiki/Dilation_(morphology)) (arrays of numbers should be the input and the output).  I don't need any rendering, DOM / SVG, mouse events etc.

Is it possible to do Dilation (offset-curve) with paper.js ? I need to draw strokes "outside" the shape, so for the stroke width 8px I would do a dilation 4px.

Would you consider splitting paper.js into a "core" with all computational geometry (something like Math in JS, only static functions, no constructors), and the standard paper.js, which will call the core for mathematical functions (the current API will remain the same)?  I expect you don't do hit-test by rendering and checking the transparency of a specific pixel.

**Comment by lehni** [comment]
I don't have the time nor the resources to do this. Boolean operations heavily rely on Paper.js classes internally, and rewriting that in pure JS would result in a huge effort, as well as remove all the fun of working on these things for me. The parts that render things to the canvas aren't all that heavy, it should be fine to have that lying around without using it. You can already use paper.js without a canvas, e.g. in a web-worker context. The same can be done outside web-workers.

As for dilation, there is a separate issue for it, progress is being made in the little time I am currently finding to work on paper.js: #371 

What I would like to redesign once version 1.0.0 is released is the current approach to projects, scopes and views, and how created items automatically are added to projects. I think that needs a lot of simplifying. But that's unrelated.
