### ISSUE TITLE
handleSize not taking into account when insert new segment to closed path

### ISSUE THREAD

**Issue by GlebkaF** [paperjs/paper.js#1327]
I've set `paper.settings.handleSize = 0` and it's working fine while path is open, but when I'm trying to insert additional segment to closed path with path.insert() a little handle square appears. 
Take a look at the screenshot. 
Left path - segments added after it has been closed
Right path - segments added while it was open
![image](https://cloud.githubusercontent.com/assets/8992139/26087692/69713c90-3a1c-11e7-9e92-0cbe5e3b8987.png)
p.s. Thanks for a great tool btw :)

**Comment by lehni** [comment]
Could you provide a simple way to reproduce this on http://sketch.paperjs.org/? thanks!

**Comment by iconexperience** [comment]
He may have found the effect that you can see in <a href="http://sketch.paperjs.org/#S/fZBBS8NAEIX/yrKnFEpIYvXQ4sk/IObY9LAmz2TpdrJMphUt/e9OxBUR7WEGZob33secLbkD7NrWe0g72KVtx26eo4vgfIKIp37KB0ddQO3fYe5N0XBDc50cm1jqhvBqHp0M+RNacdQHZGVRLM1nq77aYjNrYpm/+BAexjCyKhvL6BqbTp4msGQqmC1r9AeQZOWtLm7UYZEcjiG81Qiahk5dhI/YJKpvsuoK2eoPsuoXWc8AJbbq/1C9XeG+S9w/Sx/9zHD7OHqSya63u8sH">this sketch</a>.
If you add a segment after setting `fullySelected=true` the new segment will appear as a white dot. If you addit before, it will not be visible.

**Comment by GlebkaF** [comment]
Yep, that's it. [This sketch](http://sketch.paperjs.org/#S/fZHNTsQgEMdfheClTZouLTHRbTz5ABrrbbsH7M62uBQaoGvU+O4OlW3jQcNHmD8zv5mBT6rFAHRL6xP4tqcZbc0h2KMYweYOvJe6c3kv9EFBLT+A3BHW2EaHdRaWjAUqGt7Io/B9/gStF7pTkLCM4LxmP1taBf+xyI9SqXujjMWohl7x2zAaWl2QC5ajw8JNYjzPB3OGZ5PsSuQWjO3TqCupZ52zPy5CAA96RTYb8mDJ6+T8mmABZmRl4HkNi7xWGQcHLM7bCaL2u6nOAujYEl5K7cD6pMjmZDV0A2g0OYJvWHop8zgp9V6Dwvdb6P8TyrnKMiLCwt97sSBOo5HaO7rd7b++AQ==) is a bit more intuitive, p1 here is just for contrast background

**Comment by iconexperience** [comment]
But it seems that this happens for closed and open paths, as you can see in <a href="http://sketch.paperjs.org/#S/fZHNToQwEIBfpakXSAgUGhNd4skH0Ii3ZQ8VZqFuaUlb1qjx3Z0iC/Ggaafp/H0z035SLQagO1qdwDc9TWhj2qCPYgSbOvBe6s6lvdCtgkp+ALkjrLa1DnIWlow5WjS8kUfh+/QJGi90pyBiCcF9zX6OuAzxY54epVL3RhmLWTW94rdh1bS8IFcsx4CVGy35PB3MGZ5NtC+QmzN2iBe7knq2c/aHIyTwYC9JlpEHS14n57cCKzAhGwPvW1rgZRkSG2UctNietxMsVX6P1VkAvQyFTqkdWB/lyVyugm4AjSpH9A2LL40eJ6XeK1D4giv9f0Ix91ksiCD4fy8WxGk0UntHd/vD1zc=">this slightly modified sketch</a>.

**Comment by GlebkaF** [comment]
@iconexperience Yes, I initially thought that this behavior depends on `closed` property, but it seems it depends on `fullySelected` property

**Comment by sasensi** [comment]
#1327 should fix this.
