### ISSUE TITLE
wrong position with svg imported embedded Raster with transform="matrix()"

### ISSUE THREAD

**Issue by s-light** [paperjs/paper.js#1328]
i found a bug that has to do with if an svg element has an `transform="matrix(0.21 0 0 0.21 43.54 43.531)"` in it.

[example at sketch.paperjs.org](http://sketch.paperjs.org/#S/bVPBjpswEP0Vi1NWSuxNGrEpq/TUai/tKVIvpYqMGcAN2JZnErZa7b/Xhm0XkloIg9+bN8/j8UtiZAdJlhxOQKpJlomyZfwXglGjkYXHSQceldeOcpObgCAQk861v79J8vp5X8kWga1Wn8aYDqQJ7wFjShpWAPMgS1ZIdeKc52aQ5EGGtKmRT7TYng1qjzHVRXqGl/qIjSxtT4AUYAM9e/L27BZ3A2lO4Lpz1tPh+9MiNyyOPGmIHGZCqNJwL/taE1e2E7hqdd2QGM38wmOMR5FWaQqyUMXHNK2gLD4U6+0GdpsdrB82D7syha1a3ysQIbF4T3wkH3ZdWd+NG+cBzpPlaEKIPJnTZ/DLm9Uw4NlJUx6a4AkzRv4My3dQGwRPN8vWfLWyzFh1Noq0NWyhCbq7qexogn22DG0H4ZRMzXpNDYvMOU1Zg7YF3tp6MbhmbVCHMrgd2LHqU35c47GLwtkM/Mlp5Mn/yKhkC4vttdBN4pnQ8qoTptGvs2J88d76aTU6QJQ13BTkb0KIAf9YU93xM0xx9arRnEU96O/HG8IvGnpe2LMpkSswBH7oz16bEMKxic071wh4uHFFuBsnZ7UhTLIfP1//AA==)

if i import this file [shadowtest_transformmatrix.svg](https://github.com/s-light/paper.js_tests/blob/6f66eabcb966fedb3b142e828e17278d6e4c10ce/svg/shadowtest_transformmatrix.svg)
i get 
![image](https://cloud.githubusercontent.com/assets/1340319/26149947/a39cbb8e-3afc-11e7-8b6e-d39133a92331.png)

but i would expect
![image](https://cloud.githubusercontent.com/assets/1340319/26149887/6021ab3a-3afc-11e7-8f71-566c23ef16eb.png)

this transform arrangement can happen with illustrator exports (there i originally found it)
if i open such a file in inkscape and move the 'shadow image' one step left and one step back inkscape converts the transform matrix into x and y values. if i save this and try with it all is fine again.

i have not tested if this happens with not-Raster items too.

**Comment by blayzen-w** [comment]
This has been reported in the past and it looks like its from the transformation on the embedded image is applied twice or is done incorrectly if a transformation is applied in the onLoad function. @lilltiger found a fix for it by wrapping the content in the onLoad in a timeout.

See: https://github.com/paperjs/paper.js/issues/1192

**Comment by blayzen-w** [comment]
This has been reported in the past and it looks like its from the transformation on the embedded image is applied twice or is done incorrectly if a transformation is applied in the onLoad function. @lilltiger found a fix for it by wrapping the content in the onLoad in a timeout.

See: #1192

+1 would like to see this fixed

**Comment by sapics** [comment]
This is fixed in #1452. You can check it in [prebuilt version of sketch](https://rawgit.com/sapics/sketch.paperjs.org/with-node/prebuilt.html#S/bVPBjpswEP0Vi1NWSuxNGrEpq/TUai/tKVIvpYqMGcAN2JZnErZa7b/Xhm0XkloIg9+bN8/j8UtiZAdJlhxOQKpJlomyZfwXglGjkYXHSQceldeOcpObgCAQk861v79J8vp5X8kWga1Wn8aYDqQJ7wFjShpWAPMgS1ZIdeKc52aQ5EGGtKmRT7TYng1qjzHVRXqGl/qIjSxtT4AUYAM9e/L27BZ3A2lO4Lpz1tPh+9MiNyyOPGmIHGZCqNJwL/taE1e2E7hqdd2QGM38wmOMR5FWaQqyUMXHNK2gLD4U6+0GdpsdrB82D7syha1a3ysQIbF4T3wkH3ZdWd+NG+cBzpPlaEKIPJnTZ/DLm9Uw4NlJUx6a4AkzRv4My3dQGwRPN8vWfLWyzFh1Noq0NWyhCbq7qexogn22DG0H4ZRMzXpNDYvMOU1Zg7YF3tp6MbhmbVCHMrgd2LHqU35c47GLwtkM/Mlp5Mn/yKhkC4vttdBN4pnQ8qoTptGvs2J88d76aTU6QJQ13BTkb0KIAf9YU93xM0xx9arRnEU96O/HG8IvGnpe2LMpkSswBH7oz16bEMKxic071wh4uHFFuBsnZ7UhTLIfP1//AA==).

**Comment by sapics** [comment]
I totally agree with you! It is the one!

**Comment by s-light** [comment]
thanks for fixing this :+1:

**Comment by sapics** [comment]
@lehni I would like to create a code for `We should maybe have a pulldown on sketch itself where versions can be selected, prebuilt being one of them`. Is it OK?

**Comment by sapics** [comment]
I create a PR in paperjs/sketch.paperjs.org#4 to execute paparscript in multi-version of paperjs .
You can preview the result in https://rawgit.com/sapics/sketch.paperjs.org/feature/multi-version2/index.html.
