### ISSUE TITLE
how to get through point after using arcto() function of path

### ISSUE THREAD

**Issue by code945** [paperjs/paper.js#1334]
sorry to have question here,since i don't know where can i get the answer.
my question is  how to get through point of a arc in path,after i use arcto() to draw an arc. path only have segments property, which have no data of through point.

**Comment by lehni** [comment]
You can post questions on the mailing list: http://groups.google.com/group/paperjs

`arcTo()` is a function that constructs the bezier segments for you that describe the arc. The `Path` item isn't keeping the points for you by which you described the arc, you'll have to do this yourself.

For more information about the anatomy of `Path` items, see http://paperjs.org/tutorials/paths/working-with-path-items/
