### ISSUE TITLE
Paths do not appear to work in IE11 or Edge

### ISSUE THREAD

**Issue by sephiroth838** [paperjs/paper.js#1340]
I've done some searching on this and haven't come up with anything.  My scenario:

I have multiple canvas in the same page and I'm using javascript instead of paperscript.  In my mouse down event I check to see which canvas I'm attempting to do things on and I activate it and create a new path.  Then on mouse drag I add points to the path.

This works perfectly fine in Chrome and Firefox, but in IE 11 and Edge the path never appears on the canvas.   I can click and drag, the breakpoints I set in the tools onmousedown and onmousedrag are hit and I never get any console errors or anything, but the path never appears on the canvas.

My original thought was maybe something weird was happening with z-index, as in the path was being rendered below the canvas, but in my basic tests this doesn't seem to be the case and I always thought canvas were transparent.

Here is a sketch of a minimized version of my problem:
http://sketch.paperjs.org/#S/pZJNSwMxEIb/SsylXZDgxUvLXtSLB0FQ9NAWySbTNu6aLNnZLVL6353ZbpdUUA8OBDJvnvnIJHvp9QfImXwqAc1WXkoTLPudjsL58lHjdr6MS89r0J5DqEQuPOxErWuIioVpNmIDooJ/CG0Dd2HnCV+33qALXkwhE3vmBJlbk6+gA4+qaBHpPM/FVUKwcWGjqX5DiU446rgBVM6OhVO8c9RePjT4Qo56Y6m5+by3i2Ou1TwN4k4uGMlSlS0CttGfwV2fsI7hHQwqTRfrNEIygzHrcYRn42JhQL9hqsEYSnh1tg+5/oW5DVWIxEyKSptyMpIH3hx+fIuoN/98i1Mb2lqi6+A8Zn9VTwZEP6yIoMs+sJGzxerwBQ==

This sketch will show the path in Chrome and Firefox, but not in IE11 or Edge.  I'm at a loss for ideas, so I have to assume this is some kind of bug, but I haven't been able to track it down.

Thanks for any help!

**Comment by sephiroth838** [comment]
Further notes, the main reason I use javascript instead of paperscript is because I dynamically add and remove canvas tags to and from the page as things happen and I use setup to add them to the PaperScope.  The onmousedown activates the different views as the user bounces between canvas tags.

Thanks again.

**Comment by iconexperience** [comment]
A little debugging shows that the code never enters this if-block:
```
    if (e.event.button == 0) {
        inkPath.add(e.point);
    }
```
And if you print `e.event.button` to the console you will find that it is `-1` on Internet Explorer. That's why it doesn't work.

**Comment by sephiroth838** [comment]
When I debugged on my browser it does enter the if statement and e.event.button is 0.  I put break points all over my code and all of them were hit, all succeeded as expected, but the path never showed up on canvas.

I'll take another look at it, maybe my debugger was doing something weird.  Thanks!

**Comment by sephiroth838** [comment]
So upon further investigation based on your input it turns out the e.event.button is -1, but only for the drag event.  The onmousedown and onmouseup event its properly set.  I could have swore the code was entering the if statement during my debugging but I must have messed something up.

Sorry for wasting time on something so simple.  Thanks for help though.

**Comment by iconexperience** [comment]
No problem, those things happen. Thanks for closing the bug quickly and glad I could help.
