### ISSUE TITLE
project.hitTest doesn't work when adding a new path

### ISSUE THREAD

**Issue by fsih** [paperjs/paper.js#1346]
I'm making a line drawing tool: [sketch](http://sketch.paperjs.org/#S/7VhLc9s2EP4rax0iKZVpx5npQbIy02kOzSHTTJNODrYPNLmSEEEAS4BWXIf/vQviwYco23Lc6XQmPsjkYrG72P32A8C7gYg3OJgOPq5RJ6vBZJDI1LzfxDloKTnMQeAWPtHjaDy7FEYuM82kUDR0VzpRFusVPdqXFdMfJBPazC04n9VS0qqFQfx7bY+kGkWqpqDzAifmdVmwFKewiLmyAi055rFISPjzKZyQ7wzz6IbhNvpbys2lKCvjJvpIiveyUPhWbgWZXxQiMa5GeINCj607trCvkf29LsiBgDdwOoYcdZGLGcDJCUjBb2HBcqVhY0yCVTSeLjWNv1vArSwg4SxZU8poZTFkJgsTSKTQTBQIehVr4EwgMKE0xinIBWziNRNL0jZ5NoPG4G6ytEvWH6gKblJrl53l8gsmOqKRT6i0W4pzXOd2PLNLhVFt4sWL2l7ENG6M5KgtihIuFaYuVc242nqV+dImw3kxemGeCT73kVeVWTCR/haLlKNXnkAjeBuwNWYnBltNYaRwuTGTyBp+hfl8buoWFEPAUVW5j05ZIT1yShumI4Mz76w5IadgcoWjeqwEJAjCvc79bDeiIo5iSfk6hle9YfH4MVGV9gHoj7CkCP8Rl8vRMAALvzKlDYpMHw7riVmo1QfXoEEcxWnaWcd4ZoD+S5qCQjKdevxuVyxZAVP0QPjdMs6pBW6QXlG4ZkjzeLnE1DooG2CwnSGktj0h9QotW0xA6TjXDvdG4rFzlDWR01qwneInhIW6ZRq5Wefors6X0rlc46+Sy3wKw2seJ+vhpDv8maV6NYXXLvym2b1VCTnsAW3/2HMkt+xjt/dGfw+7ufxXfCTq7A8VEM26ECRR/YoicAPXuGTCUxdnGfUrMG1+VUFxKO3sfiEVwtyJoQiDPTJemVCRZ7D2JtDHaq7kVQGJfbKdVq3iiJao3xLCDem3Ga6qCJw3mC4K2wO87BW3uMxFuOPX8plt+AaFfSf/PoqBO5KjuQ3vEeT8AD0HHukj6JqS9tPQk0l8D40fRORPoPLnJOxDKfv+rSSUooPDdphd/ve8Wu4cb4gg/rXjjf6f0ki3om/g9RMoZh+5/Hcs8oNHfvDI8/CIbW3fOCFMX1YL/xB71g06c868rhV4iLRQf8/sRpln7fDsQafNdH9mB/McfPsG7kh54H3uHRhC4mgvdZhOIJViqOmXSPCW8i2WzQTu1P4czozz3jGDmbPH8lF/8h6kpsyCxhwnR92jsufSS+2SEjARsN7vNcK/CrqKt1d80bvGYzi7cqH2xeTM9ufO9M2eAJsFItumJRLtbhbV5Rr96VpNqt3F7EwVxTVvpy10h+U2CxH6utMI7SuYsdt37TpwkW6SZWJDi8QCe1qp5b9aX8d9vamC3kq7mX5/aMZkoPv2RtC3Sdf3P9o/sI9pzP1r54pVfebZD9ae7yIOE41rUb2bNMnCXjqzRjEXhIuR2YwY6Z1OgPs9vJOMGSmcA6d/P8358avWRw3lsdKeecGuZrVS6hqZtEaW9479RNcf3lMNxzDngSb3/dHcZJztqXcS+L/DsGGuS2Y5G0wG1znGa9s+g+nFVfkP)
(Hit tolerance is set very large to show the problem)

Click and drag to create a line. When you create a new line near one of the ends of the line, the new line snaps to the old line (hitTest works correctly):
![connect out](https://user-images.githubusercontent.com/2855464/27292629-028ec3c2-54e2-11e7-8782-0421c2023bcc.png)

However, when you create a new line and try to connect it to the end of an existing line, it very rarely works (hitTest failing):
![connect in](https://user-images.githubusercontent.com/2855464/27292725-451ebabc-54e2-11e7-8317-f22a1116ecce.png)

(Compare onMouseDrag hitResult to onMouseMove hitResult, which both use the same line of code: `var hitResult = paper.project.hitTest(event.point, hitOptions);`)

**Comment by lehni** [comment]
Could you reduce this to a script that does not need proper interactive use to reproduce the bug? A sketch in which you create a path item and run a hit-test on it with a point that is supposed to produce a result, but doesn't? That would be more helpful. Thanks

**Comment by fsih** [comment]
I think I found the issue; it was my bug. hitTest returns the first result it hits, which in the drag case is always the line you are already dragging. I needed to use hitTestAll.
