### ISSUE TITLE
Access SVG id attributes after import

### ISSUE THREAD

**Issue by kontur** [paperjs/paper.js#1348]
I would like to identify some groups in an imported SVG based on their `id` attributes (generated by Illustrator's export based on layer names). I can't find a way to retrieve those in the imported object - do they get dropped completely, or are they somewhere there under the hood still?

#745 was the same question / request, but closed without resolution.

**Comment by lehni** [comment]
It ends up in `item.name`

**Comment by nicopowa** [comment]
Here's my experiment, SVG file imported with elements IDs.
I'm able to get Paper items based on child SVG ID, pretty useful to change fill or stroke.
https://github.com/nicopowa/PaperSVGLoader
