### ISSUE TITLE
SVG Export example on paperjs.org is broken, as are things based on it.

### ISSUE THREAD

**Issue by Robbbb** [paperjs/paper.js#1350]
Hi there!
I do not know javascript well, but  there is a problem with this example:
http://paperjs.org/features/#svg-import-and-export
When you click [Export SVG]
you get an error:
"Support for Python 2.5 has turned off. Please refer to https://goo.gl/aESk5L for more information"

The same is found on my applet, Vector Ruler
http://robbbb.github.io/VectorRuler/

Best,

**Comment by iconexperience** [comment]
I am not sure what is happening in your browser, but I do not get the error message. Also, I do not see where Python should get used in the example.

Do you have any extensions activated in your browser?

**Comment by Robbbb** [comment]
Well, It seems to have fixed itself. I just tried and it is working great.
It was not my browser, as the issue was brought to my attn by someone trying to use my script and we had the same error. 
My flawed, vague understanding is that there was a call to an external function that Google hosted that built data into a file and allowed it to be downloaded. 

Cheers!
