### ISSUE TITLE
Seems like generator functions are not supported in paperscript

### ISSUE THREAD

**Issue by bluewhale8202** [paperjs/paper.js#1357]
Generator functions are one of my favorite syntax in JS and make a room for performance improvements through lazy evaluations. But it seems like it's not supported in paperscript, yet. For example, 

```javascript
function* idMaker() {
  var index = 0;
  while (index < 3)
    yield index++;
}
```
this simple code cannot be interpreted in paperscript.

About [function generators](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/function*)

**Comment by lehni** [comment]
The included version of acorn.js only supports ES5 to keep size small for now. You can always load your own version, to get full ES7 / 8 support. See sketch.paperjs.org:

http://sketch.paperjs.org/#S/jY9BDoIwEEWvMumKigHUHegRXLm0Lmo7YkOdGiiIIdzdNiSuWc777/9kJkbyhaxklwa9erItU07H+9GT8sbRBow+ywbbhMMkCGCQLRjSOMIJiiqSz9NYhGSBRzjwCAG+Bq1e1DQN4ixIUGzXSKH7n60iV446ZzGzrk5CnhGOPuHZIG2PvII8h2KNtFsj7QWFP+8tyubtDPmOldfb/AM=

**Comment by lehni** [comment]
Related: #1183

**Comment by lehni** [comment]
Why not use v5 then?  `https://cdnjs.cloudflare.com/ajax/libs/acorn/5.1.1/acorn.js`
