### ISSUE TITLE
keydown / keyup throws exception

### ISSUE THREAD

**Issue by Skalkaz** [paperjs/paper.js#1365]
TypeError: Cannot read property 'length' of undefined.

Paper.js v0.11.4
Key.js > getkey() method > in the last line, where key.length > 1 is called the key variable is undefined.

I can't reproduce the bug, but my log file says the user agent was:
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.101 Safari/537.36
or
Mozilla/5.0 (X11; CrOS x86_64 9460.73.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.134 Safari/537.36
or
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.101 Safari/537.36'

**Comment by justmao945** [comment]
Same error produced

**Comment by justmao945** [comment]
I can reproduced this. This error will be triggered if you use auto fill form. The browser fires a custom event which has keydown type without any key...
![Uploading image.png…]()

**Comment by Skalkaz** [comment]
Thanks Mao! When exactly the event triggered? When the page loaded with an autofill form? Or when you click into the form? Or when you start typing in the form? Or when you start typing in the form and the auto filler recognize something?

**Comment by justmao945** [comment]
e.g. your browser remember the username and password, this error will be fired when you open the login page with username and password filled. The autofill action fired by the browser triggers this error.

**Comment by lehni** [comment]
Related: #1358

**Comment by lehni** [comment]
Please let me know if 6a96a115493d4f1ff89d08466437085ec1cb5d13 really addressed this!

**Comment by malero** [comment]
@lehni it fixed it for me! This console error has been driving me nuts! Thanks @cjds.
