### ISSUE TITLE
Count intersections between a shape and a path

### ISSUE THREAD

**Issue by mikeInkerz** [paperjs/paper.js#1366]
Let's say I have 2 square shapes side by side and a lot of paths on top of them.

I want to know which square is more "filled" by the paths.

I was thinking about using intesect bool operation to detect which square has more intersections with the paths. But I would need to count how many intersections there are.

Or maybe use a hit test? But hit tests are only on one specific point and I need to know which square is more filled, checking all the point on a path would be a resource intensive task. 

There might be a better approach. What would be the best way to do that?

**Comment by iconexperience** [comment]
Change the shapes to paths (via `toPath()`) and then use the `intersect()` method to get an intersection between the quared and the paths. Finally compare the area of both results.

**Comment by MikeBailleul** [comment]
toPath() would give me the path of the rectangle perimeter, thus the result area would only be between the paths and the rectangle perimeter. What I need is the result area to be the intersection between the surface area of the shapes and the paths.

**Comment by lehni** [comment]
`toPath()` should give you the actual shape. If it doesn't then that's a bug. Could you provide an example where this is the case?

And welcome back @iconexperience! Good to see you again around here!

**Comment by mikeInkerz** [comment]
Correct, that works, thanks!
