### ISSUE TITLE
Incorrect path construction when created with SVG data

### ISSUE THREAD

**Issue by ccgus** [paperjs/paper.js#1367]
I have SVG data which is a single path, which looks like so:

```
<svg width="800px" height="800px" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
<g >
    <path d="M223,367 L362,367 L293,436 L223,367 Z M400,352 L194,354 L293,463 L400,352 Z " stroke-linejoin="round" style="fill: rgba(0, 255, 255, 1); stroke-width: 1.000000px; stroke: rgba(0, 0, 0, 1); " />
</g></svg>
```
And the output looks like this:
<img width="311" alt="screen shot 2017-08-25 at 2 52 57 pm" src="https://user-images.githubusercontent.com/60178/29734095-3033e8a0-89a5-11e7-9708-9c39358cb5fb.png">

If I try and create a path in paper.js using the same SVG data:
```
var p2 = new paper.Path('M223,367 L362,367 L293,436 L223,367 Z M400,352 L194,354 L293,463 L400,352 Z')

p2.fillColor = 'blue'
```
I get this:

<img width="266" alt="screen shot 2017-08-25 at 2 54 23 pm" src="https://user-images.githubusercontent.com/60178/29734116-4b6cb93a-89a5-11e7-8d68-ccd97fb5d39b.png">

It looks like the close path operations (Z) are closing the wrong path when paper.js is loading it up. Is this a known issue?

**Comment by ccgus** [comment]
OK, it's no the SVG data, rather it's something to do with closePath() not going to the right location maybe? The following code has the same wrong output:

```
var path = new Path({
    strokeColor: 'black'
});

path.moveTo(new Point(223, 367));
path.lineTo(new Point(362,367));
path.lineTo(new Point(293,436));
path.closePath();

path.moveTo(new Point(400,352))
path.lineTo(new Point(194,354))
path.lineTo(new Point(293,463))
path.lineTo(new Point(400,352))
path.closePath();

path.fillColor = 'red'
```

**Comment by lehni** [comment]
You need a `CompoundPath` item with two `Path` item as its children to describe this shape in paper.js. You can use `PathItem.create(svg)` to handle those cases easily.

**Comment by ccgus** [comment]
Awesome, thanks so much for the response. It's all working good now.
