### ISSUE TITLE
Mouse handlers aren't working

### ISSUE THREAD

**Issue by joshreback** [paperjs/paper.js#1376]
I'm just getting started with this library and have lifted some code pretty much directly from the tutorial. The code is small enough that I'll just copy it in full:

index.html: 
```
<!DOCTYPE html>
<html>
<head>
<!-- Load the Paper.js library -->
<script type="text/javascript" src="js/paper-full.js"></script>
<!-- Load external PaperScript and associate it with myCanvas -->
<script type="text/paperscript" canvas="myCanvas" src="js/myScript.js"></script>
</head>
<body>
  <canvas id="myCanvas" resize></canvas>
</body>
</html>
```

js/myScript.js
```
var myPath = new Path();
var tool  = new paper.Tool();
tool.activate();

myPath.strokeColor = 'black';

myPath.add(new Point(200, 200));
myPath.add(new Point(100, 100));

function onMouseDown(event) {
  console.log('You pressed the mouse!');
}

function onMouseDrag(event) {
  console.log('You dragged the mouse!');
}

function onMouseUp(event) {
  console.log('You released the mouse!');
}
```

When I open index.html in my browser (tried chrome and safari), and I see the path show up but clicking around doesn't log anything to the console. I'm using v0.11.4 of the paper library.

Please let me know what, if anything, I'm doing wrong. Many thanks!

**Comment by lehni** [comment]
https://github.com/paperjs/paper.js/issues/636#issuecomment-76537954
