### ISSUE TITLE
Possible copy/paste bug in Curve#isSelected()?

### ISSUE THREAD

**Issue by alexjlockwood** [paperjs/paper.js#1378]
I was browsing the source code and noticed the following code:

https://github.com/paperjs/paper.js/blob/b6f9d73af0c44d9f75c880730465e05f85fb690e/src/path/Curve.js#L342-L347

The code checks if `handle2` is selected twice. Should it be checking if `handle1` is selected as well?

**Comment by iconexperience** [comment]
Well spotted, this looks very much like a bug. <a href="https://github.com/paperjs/paper.js/blob/develop/src/path/Curve.js#L342">Here</a> is a direct link to the code.
