### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by MegaUITeam** [paperjs/paper.js#1383]
I just load paper.js with CND and get error

`<script src='https://cdnjs.cloudflare.com/ajax/libs/paper.js/0.11.4/paper-core.js'>`

![image](https://user-images.githubusercontent.com/30184325/30680444-4c98601c-9ea8-11e7-9900-d7c570fd44f5.png)

**Comment by lehni** [comment]
Same as #1365. Please search through issues before posting.
