### ISSUE TITLE
Crash when doing boolean operation with some path

### ISSUE THREAD

**Issue by bbqaaq** [paperjs/paper.js#1385]
Hi! Im currently encounter problem when I try to unite with a path.

Currently I have test with a lots of path, which most of them don't have this problem.

But when I try to do operation with some path, I will encounter a crash mentioning a segment with the "_path" property as null.

As attached, I have include a path that I see this error. Please just place it in an empty sketch and you will see the related issue.

Could someone tell me why it will have this bug and how to fix it?

[paper_sketch.txt](https://github.com/paperjs/paper.js/files/1343468/paper_sketch.txt)

**Comment by lehni** [comment]
Wow, that's a hell of a path :) Luckily the solution is quite easy. Fix coming up!
