### ISSUE TITLE
Feature request: convert stroked path to filled path

### ISSUE THREAD

**Issue by alexjlockwood** [paperjs/paper.js#1388]
Let me know if this is outside the scope of the project, but recently I stumbled across the need to convert a stroked path into a filled path (i.e. or in other words, to compute the outline of the stroked path that would be identical in appearance if it were filled).

Is this something that can currently be done using the library?

**Comment by lehni** [comment]
It’s a planned feature and I’ve been putting some work in earlier this year, but it’s unfinished unfortunately and I have had very little time lately to work on it recently:

https://github.com/paperjs/paper.js/issues/371#issuecomment-285041094

I can’t give an ETA right now, as there are quite a few edge cases that need sorting out still…. : /

I should however start a branch and bring this code into the core, so we can test and evolve it more easily.

Let's close this issue and keep discussion to #371

**Comment by lehni** [comment]
PS: Here a demo of current state: http://bl.ocks.org/lehni/raw/9aa7d593235f04a3915ac4cef92def02/

**Comment by alexjlockwood** [comment]
Awesome to hear! :)

BTW, I have one other feature request too but I doubt you have put any thought to it. That is the ability to convert nonZero to evenOdd filltypes: https://www.google.com/patents/US6111587

The reason I need it is because I want to be able to reverse the order of a path's points with the guarantee that the path's appearance will not change. Reversing the order of a nonZero path can result in the path's appearance changing, but if you convert the path to evenOdd first you won't run into that issue.

Not sure if this belongs in the library or not... maybe it is something that could be relatively easy to implement using paper.js? I experimented with the algorithm a while ago before I even knew about paper.js and gave up pretty quickly because of all of the math involved.

**Comment by lehni** [comment]
This sounds like something that @iconexperience knows more about than me... I do feel that we've solved this, but I'm not certain anymore. Let's see what he thinks?

**Comment by alexjlockwood** [comment]
@iconexperience Any thoughts?

I just noticed a method called PathItem#reorient() that might be related? Still looking into it...

http://paperjs.org/reference/pathitem/#reorient
