### ISSUE TITLE
SVG switch tag is not supported when importing

### ISSUE THREAD

**Issue by jackytwh** [paperjs/paper.js#1389]
I am using importSVG heavily with high variety of svg paths. I've found that there are some cases of paths that paper.js may not be able to import correctly so as to obtain valid bounds. Kindly found the sketch link below for some example cases. 

Wondering if anyone out there encountering the same issue. Thank you.

[sketch link](http://sketch.paperjs.org/#S/lVpdbxxHdv0rDebBNlA9qu8Pw+sXPyQPZgBigzwkCrL0iJYUU6JIcR1bQf57zjm3etikKO/GsGZuTVdX3e97qw7/5+z95burs2/P/vzL1f3xzZk7O9684vjFi+Wfb+6X4+WHy5+ur5b7m+XN5ftX11cv319f3S8/Xb76z5+urpY/LX/57uOvr7//7tXVzx+//+7D5f2b5dWfXp6dj0NYsz+0crumQ1/D2g91CQdf1nKIZYmHpF/aIRRMGEvBVBEhHcril0Mth1KWisn2HfCsHUY59CUfuEAoSz80rbmkQ1gif19B+PUQuVE+9ILHtawViy9pJXkYazhk/KsXa6has60x4iuDVazPx3y7HeISwGwXZwGirOCZa2LG0C8Jy2EYKR8nZSyO/yMYXrVvohTYN/EXzDjUleziK1IJXhNWPU2YR4KL8nvRB/TQyXsgG4PfGZLrB2oGXwljqVHfFVJQt4VqzCunVEnMV8jXPRmDsikrdooLpkA9WbxAFrICQTMZxNS+Ui8YDCMyzTWoioansWwf4A67dUoTtVSkVvhi09tacECmLJmgCROhbSJEfpMNCAwbYhtYIU+Z54uJI6kjQoL5lseu8AQsCDYe5AYDGIGkVHAMORfdAfPLr1DVLV5OdB1IgLcrl49cPtgay1yWZqLfQUmDsoK3oqWTfTV9es4K9AvsFUh1o6In56QaZ3h6Dm1/DfHC7YHuT3vJrFx0KQv2qaYkehe9Oa1BYUIJ9VkhTDNjyQC2avoV3JVbv8p/qS2YSu7U6Joa4Z8vF2GQq0H9yWP6bZD+IDA8PlxEeXJbYmMA3CLW+DM57WtfGDAKC0Qw+QtkiM9XWK1jK/k0gyZIS/majB8aXK6v0QKeETDK+RCnHuagO690Y+ioGFXkDw17NPk6LFRlnqxlB6dyF2aNiAwgNdDzsKXNmIF2KIrJg/kvNSp/ZYher9JfvV2VSpL4YyKRZhlTCuXF9E3XtMimg0oGKGrMRbmlp7ynLITvC0iyKiKZubA6d6ImyzozlxJK1KvcHP9f6An0yHQXGKqBrItn2vtfwCYywW0wOys9epo3viObhZtkWzxJlfTrcbFq0ya+FfS38DKv9NqkpUXqCVK9kobCth7KxUpbYF28xbjDZjD9WjaiYy2JA6rxKyjtdeblTfn021zkAY3K8Xob/37lx62xFOWVWCUp/vgmE7Sy+Ls1DcZp5mYMwqxPhUiwZCirNSPo1ySWYFVBHj4/vWIIM95hzwDtdSrZW1ArZzEYaZhFSVG5msvIv5RgVqVnKWnMDDjMLZSy0jt4dVsY0rdyGxqjKY4XaUYWUy2jAJRa2V3qN1/38hLmLuUvEcNm612Wrip5Kz2SZYpV7NrCHz9Z5cWuygJR9bcYCxEyyEPCakmQBqY8RZlbSV7+OLiwnGiYvc/XKIcK8ZoRhxzGTwVR3BmVClcGUVo4hDe08enZakXQZFamVnKXMSEM5cYvig18BYWPF9NBRY5hyqydyVM1osmtkBLqKt1S1rQRsLCEg14tXIMCWcVySMx3lekvMvJv7WFSiVrpwr3I6SkNDXYtO6vDUBa+VUaokoWqeLcWLNCUiVU9GTdZfYNqql4LygutKDk3VR9LPsZRkCam2FZXstXCTH/FJ4uK35TgleSWg/nBOwlJ1m+lq6oCqr6FIVmk4iSP5KhN7rOSqt7QXskaB2+Jg2YrlgQj25Xy6eXZ8pbN3uXLsxfff/fCWsC/frxafrt++/6Xb9/cXf2Mp/+Ax8v93eX7jz/f3L3DD+8u7+/e/vY18sXIAyL4ZZIF4vhvbDE2lX+xXvPtuw83d/dXaDhPTeeHyw9Xd4cPdzf/dXW8P9iEP//rP349Z3zz8v3Tlw4/v72+/uHm+uYOr391d/Xqq2fmiMvry/urr9fPnv1089f3rz4efnPLF5/9jn2PN+8/3lxfHa5vXn/91Xz+7VfuMyHmO3jjoaH+8Pb1Q0P98b/foh///rvX+64aGXBUpFXEbgwqq0xptbbjas2u72wj8cmfU2I8Z/YWoapPbcjPfqirVbrJkb1xYoNVe7uGuVnMWz4eSmJuSfQcn+kIo3U6W1V/q76tBWbZyD4qt0AG6JRtsBuugYWXLpYaQgeTUIGCQi0mFu5Yx/WhVbpdbfGIlRuLTfHkpdfKsp46K0gbGnTW6hQ5yY/2SV6yO25AJERLRMkcCcoIGemlBTaqkfyMrg60MbvlwF9CpCMH1qOovKSuJXq0DgxuL+fHsmnQ26Ed8FnZ3LRKxbeK18Gt9kLweQZPksCDSTcwxQfmAekFaaHRMnFQXSFFpt/GI0tsbJ5So61yZuWsXekXKkX5CLHNAVqc5nVoQOT3yjaol8o5o6CzQJ/U0LTlnmkPuEFVh1sLW/eUNxoSqvymCNpT8JRFUKhAKXyGk0VwXwa4G+A5jiO6jKH+z6vtKo2JsA41kKkyF/cMZQ/Ps0gJUlTN5LEGJThvgwGvhUmUXUp+w8qbr6ED7JvCERaC8qhCHvxyUAcZeDhL4BLvB6qn0LmHpyytwq98U09W2bfHRi/xTWW0YH0odlt/xCO5WplXG9bsOsT1zl6jJ/gEwkStWapwgsjanHkU6E3cdFFwxIxawiIEF4FcSUeS6fN8efAo1u2Mi0WgzDZYPsArdmCYQcdqEqD1NzR3BYcVHCK4jgxSBmgI3KtE8ZgtQlNjIOTIgEbE8bkPFro0ileTMYYU4StW9R0+EhvUgBjDJnT50tuRLo54DYnNVUQ/iJdrnIMEEUNUucx0ko40wrI6VjproId61Equ1YPit3dVDLV7PSha0HIkmsmjovbBqjIiU1WncorIlCQr653vTE0MhpDkjDTf0AZ8R91LUF/XWZBTL5/OI/MAeiBUuhjeMLhHO+K1ytNJrip5I7FxqfTVGJOySFVLQjMl/OqzwpqJzcMXK8M12EEnBoYoVDSUgaDCFGnAMcand5ldN2oX960eCg2JVbMgzENkvEaddAZ9qkgRhZIV9jOsddym80gQ2DG0mC6zkqR9qiSa8phdwvFQs46P8EI0X0NK8fQOOH+xCoBlA8+piUdeO8P2Ck4RNHz3DU9k9cielxrMJYjzzDuQmHQ0rGkbwNHZLkFU8FDp2nnghOCZPGNmYmBIe1kxdrYcBS+ApxGVZIOijz1lCmwBPfQ6uNukMbPTwahfStg61FsCnTOjf4XG4AT4kfEDH2Q+9yx5mbLlRMPlyLPGyIEmiW1QPp/KkblQJ33uVcEnHjMKGswJVcQyeOJTm1+4AZOWT51ZvLN/hTk6rc6SAQdkPxjJHaoIGYNFoceQEaZMsTBlZyLR2VC3B7kzeGP6gapkPKIg+ci6FJBzIi9BkEgqwwD0kaeMyNN+6iIoDFxujpDxa2WTRyEGu1hUgyXC4+XYCcGDGCoVVk6MgrWwrtLKieuwgIfGI2xQ/LDtRq5UHoECeWCTvxd2pSgLrKx5JnKEAyt8ho6q1x0TChRtQUdW4AWGEJI4KcTT6GziqACo1o4xXgGsPmNkK9jHt3fH66vl+BtqNpLOGGgNj79jUMgMBnegGfHDusDX7ARnI/TFltDapj9qCTHjaUuIn/5mS8g5X2oJ+eyhJQzef/Hxs10hnn/WFT68o67wxYvln3Tj+mo53tzdQarr30361zc3T25fXz/XYFtb3UfOfgTkMLipW7z+f+5J8Q7d9/Ly7IvLnd7m52nqdgSY7RiVyq7f6z+Y9OP93c0vV/jp/c37K4w5fTlHWg2L3RAvF7rOW7OdNnAM40m/LTongcahdkGwY3rSwRAxvayRhyBRgUfVSXZODTrYMfI5A162MIBF8m2duHmJiU/e4XLtbGdNBpVuTMuiS9Gux8hNJ4r9xmkL1lxulHRWDHqQ1R6R4AZDLMxr5mW7ZybBPapejzqWeR6GWYi5Nw9o/D2K6WyTuKj0FJXgOReLoxngD5yfKWks2qjoWbdFq+SOQzLEaj/qLgWjhfdvQa9gqRRsbRtEe8MGVQuSvaT7UllDg3Si42YlrZT0KRuaeMlPtro4ECkudKvLm4XJYTaJi2TrEjxIQi9zicXM9YMJY6hAtiU2u0Q6zpBSml2OGKk2qWzk9IEoA9nv8jXT45DazSqQK28+lpIx7k0T2dbg8ZyDIQvbA5MhiY7Gd3kY2K5N0umWEyFhzr2Rkn9S3kLDHAjOkabe5OOpyTmMruJho8WbqDSZ1sDbwBs/1EWoeiQzBjOgnKNKFYPKMt/BtmbjKGBhiM5qO4JoNaFJ7sGfu+2iQdReP56G1XIAh+yaFTOmH9M4zrjZQpcuX7aBrjE2WvE0jRJ4w5jS9iDrQRIduCRtGeSXu8GkPQ9NTVdiuvHJdl0mM0+6PdCSE0YYpLooLrokFWasqbsmegfJzG6AQMOwR4nc68kwKssWSZfzJ5oLaAfd1IO3SnGMTHMbw7dkALMxrJYfyPRAxm1G1PGQ+pWXREFpurxkepkIxmc4wRKaJS5M267PFks8XngB46arRdnCxuzJdpT7Tx8rk466hrKUr2v8Ig9N3aCTpqJARrJ+lH9tE2Qii54u7EWxMcq+srDMeEs8FS5m+TPpRnnI00nGshGKw6SMa0nAAnFGZuBdcbQYKhNrwmcjH3YpJ8BDN5hyKaaQDRRKYleNUZ8Ufc2oVf7FgsVt+MuPOisuq5zwYoonkawgMLvozrjY7X43qHRRnAklIX5Jhpuu4Xn/Qtn4eFJ5mUGpO/ZxoroowxQfIRdLmbCE3UcXu00soib6GJYNuli8hROhEWUwu09NFm5BN5kEI3TDKzhjsewes9nwZLZzq6LE2tQptLJVpjhLmIqKXKuZzmb53ihtauycFCylS2vKoAaCBImeJ+C0gR7LCfVYhHjpunWSKgbDUo0U1q1cJ3rm2Gp6XVbT8Cy+zRhX8rddZ2WdgyFKxI8n0jyBFyuz6FqxVc0Ms74KH3hQ17ne61s1vpBGkw3bwyCa4HOUpLmuRawrmv6vPHYaxK1splnYy6nh2EbjyejEyPli11aydrbkbx2MValwUuEsXhYZaarnNMr7QZ2V1kZ9LvFoNB4GZdbA2TKVB46Kpu3ZO1/sjxYEHpsNrPtjU0nbD4FOWTCb/jqB32q3uv1Fg8VtEnY5ZpoI1TJBVy4ti5xXVGReO1FWfiyPh1kJRrHrv8VyGcM1ESglh7N+tZnorSrkmaxnLTRkxSvoLMGlMskJNlj213WYFQbGi+mglEf6OF9OkBB1oyRqWY+0LzN5ReM6KFhnsmxbhrVy/DDo1tOJtsavmb5/1KBO7V/YiIM6W6tyGujPBZgtN7egBXRcYFeYLaG3h7RrVrKTgmhwEE+0MktQ2k9h5ppSpi1m374N1NTOQZKDJOvEDNSbKdYG5vIGwg0FizcvOSWFsGtWoeLzxbrNpK7+YrEmir3TYk47uwOqOBHUTUrzSaH5I51jcJA4L8iBOldJ5jjx0ernW7UOwzbbhsqKwf40RR2fdUjWMvKSYJlntLhVaaYGvhdPmSb0XdqZrbPRlmdop1ltebm9zPwU4wyGIg5Ovwf7WwpVeOPS2u69AOfzqGDdzIVGdlU2exGpvshJ4pTSGuRA9klHxWA5STzmUa0Ua6R0OttIiyg/k0zlbPP+YNbeMfNvPEC/4Al6Xnts/5679dhdAHzp2mObsr/32H57fPHBk/pXz816uPp4dL1xev4cIvb04WeXH9uER7cfT946gWL6/REq9gwa5vZomJtoGDOT28FhbgeHOcFhR8PDnH9AxNwOEXM7RAxzassL/jv6EzDmdsCY2wFjRwPGPJExZ8gYmcluB40dmUqTEziGxT1m7uAxN+ExT3zMCR/T3juMzO0xMrfDyH58pJNPO6d6ipW5DSvzAsu80DL/PFx2nHiZ3wFm/gExgwgJHm36OSFn/HXDzqTBJ+iZN/iM23MuETRPCM0ZhEaGuhOGdjQQze1ANLcD0ZxANG3/dyFpxwmluQ1Kc4+gNGdQGjnLPbsTmOZ2YJrRtqXn3SnW8sLUvEA1T1TN72E1T1wNJgXrQtZAxpEg9wldc0LXnKFrTuiaM3TN6VJ222346nYYm9tjbG7D2GhI+vMDyOaFgvnHMJvbw2xuD7NNa9bC0CHYxvere0Db3ETbPOE2t4fbTjs9AtzcDnBzjwA37iTQjR4TuxPs5qj9Jv660UdBb847g94Yt1zohL0dhb05YW9O2JsT9uaEvbkNe/O8Snc78I37k+dKnp9AcG4Pwbk9BHcUBOcEwVmucAbBOUFwbkJwnugD+H9A4bxgOE8cbuo4KV10yLxH49wejTtuaJx/Ho5jXtKqPShjbIic2yFy226JFvVRXI3hhMw5InNOyNxRyBwfSnXDd9E0C9E5OfUPg7moOV6PIdkMRGlAWkWNxOxH6eUTd10mWOe+CNa5HVjndmDdUWCdMklygusskzgBdmSsBm7wA/sziF6JCSXHfhHJoyGe8fVo80/LeeX1Zd8xQwTPnyA8xuSzIB71Z0AerUdDn5A894DkUcUlys3oxHVUpbhgSjeagUVRnBA9zApDJvB8A4aUSJWnekQo9Aiv4ogiJSWsRyJApO6Zn08iGdbn/x6wb8sqGXWEOWwMKuCE+lEZPh4N+CNzG/TndtCfE/R3NOzP7bA/t8P+jLbtBAC6DQD0OwTQGwTIMksVtq4EE5UCooqVT/TcExbodlige4QFTn8/AYJuDwiy7O8gQS+9sCrbhrlpp67y1GXNP0QG/QM0ONMZiwZ9oDvDB73S0mcAoTOA0BlASFcdzgBCtwMI4SkGCToDCLfRBAjpLR0lAXm4dOXmjiCW/zfI/cg54Cz8k448nK7hy1H6lc9PvJBOe0IMGe6nysPs57+MHELZXYpjaBp46IkeOkMPzYLUFL3cK/UkxUgqpBXno5s4A0UIOZBnJdh1MAmKY+Rn94j/fYvz/0EX8ZJN/1tt9h+ji9uUz9rsz/DFZ9vsxwjj5232H6CMT58/32k/xRmfvPXNmTv76e7q8pcPN2/f3388+/bf/+N//w8=)

**Comment by lehni** [comment]
This is not a problem with the paths. It's linked to the use of `<defs>` and `<switch>` as containers around them.  How do these display as pure SVG?

**Comment by lehni** [comment]
Ok no worries, here they are:

[bad-svgs.zip](https://github.com/paperjs/paper.js/files/1368487/bad-svgs.zip)

**Comment by jackytwh** [comment]
Or here are the original bad svgs for your reference. 

[bad_svgs.zip](https://github.com/paperjs/paper.js/files/1370325/bad_svgs.zip)
