### ISSUE TITLE
How to track when the view changes?

### ISSUE THREAD

**Issue by poonwu** [paperjs/paper.js#1390]
I plan to implement an infinite grid on paperjs. The trick is to redraw (or remove/add path) when view changes. I wonder if there is a way to listen to when the view changes? For example, `onViewChange(callback)`? 

Otherwise, I'll have to track whenever my application make changes to the view (happens in more than one place), which is quite cumbersome.

**Comment by lehni** [comment]
Please follow the instructions in the text field when submitting issues. This is not a forum, it's a bug database. There are better places to ask support questions.
