### ISSUE TITLE
chrome autocomplete in forms triggers 'keydown' but the event.key or event.keyIdentifier is undefined

### ISSUE THREAD

**Issue by darkmeton** [paperjs/paper.js#1398]
We have a login form in our web-app and chrome stores the usernames/passwords for that form. The script `paper-full.js` is loaded and when the app is loaded, chrome auto-completes the username/pass. 
`keydown` is fired and `getKey()` raises an exception since the key pressed is undefined.
 Thus we get an `Uncaught TypeError: Cannot read property 'length' of undefined' exception`. 

additional info
---- 
- project is built with angular-cli
- project is Angular 4
- paper version 0.11.4

**Comment by lehni** [comment]
Already fixed in `0.11.5`, see #1358, #1365

**Comment by filipw01** [comment]
For anyone looking for the actual chrome issue [issuetracker.google.com/issues/41425904](https://issuetracker.google.com/issues/41425904)
