### ISSUE TITLE
Missing Minified Packages on Repo?

### ISSUE THREAD

**Issue by samypr100** [paperjs/paper.js#1402]
From `v0.11.1` onwards, minified version of the library (due to .gitignore's dist/*min.js) files are ignored from the repo. This means they're no longer available via bower package manager or even yarn's bower-away migration feature. Is this intentional? Is there an expectation that users would known how to minify/package this library "appropriately"?

**Comment by lehni** [comment]
Yes, this is intentional. You can get minified packages from NPM, or you can minify them yourself. Having to commit prebuilt things has been an ongoing pain, removing it has simplified things a lot.
