### ISSUE TITLE
Multiple subtractions create incorrect results

### ISSUE THREAD

**Issue by RandomClown0** [paperjs/paper.js#1403]
# Description/Steps to reproduce

**Subtracting from a path's subtraction creates incorrect results.**

1. Create a large shape
2. Create a few overlapping small shapes
3. Subtract one small shape and save the result
`large.subtract(small[i])`
4. Subtract the next small shapes from the result

# Link to reproduction test-case

[Example Code @ sketch.paperjs.org](http://sketch.paperjs.org/#S/nVRNj5swEP0rI7QH0yJKskl2m6in7bXVSu0Now0BZ4NC7AiGbKso/70eMMb52D2USDCO35uZNzP20ZPpTnhz79dWYLbxAi9TOa0zJWuEPMX0RTWIooJvEMfjKApgPJ4kAcQPY8cMJ48BfJ3RosU4JmGSxYJLx2Uhpahqcsklxzge3c8CGM0iIumPtu9bB6PReLB7TBIYUgt8nAxAY1850//fJLmRPiS9591Nr8cQKdFyuVw3MsNCyU+Qqxqb9Zr5cOQS9HNIK0DxB19yUWe6DlK8wbMqJP7WfzK7Yg/TAGaR7y86mqWE66Isn1SpqC/cW5VptuXeFUqXHIXEFvNUFtkWUEGNYg9KZgJY9GXiW1r3LgWC7XibSIobZtKmp8ZKbUUbez6EDgaATY22q9dVyqKAfhCFFM0gT72mLliY5jkLw9CZOP8qr2FsErO31gVgtEU8UGt3vGyxORJir3X8jySOHG9LGk+nF6I4WlkcKaAra9jp8gv3Tb1hhOp3Tu3YXCgrtGxwFFE+fwtR5ovO7t+9GFsoLbajxUWyuETdmpHlrRG5O/5sditRscKHzzA66YlZGm90oFUpwre0kmxJoZXam9gkaw53x+K07NXR01NK9cq4Z+aMsLqEZhICOxGVSP3zSB1tiECsdmU+Lqd7UzV0y5+75hvPdbPCKs2QtST/rJDnoXqkPsU2oHFnjeugJkwlduogWO/fPVXEe6d/nRCH204GlyeajLa51Ct7o2hAgaGka8M/u3V0/36ophbf1Ztk4qBbbA+ES9Bu9a2/0hK2e7pyam8eJ6d/)

# Expected result

4 triangles are cut from a larger square, 1 step at a time.

The result should be a square with a smaller square cut from the middle  .
Got "not a square".

Changing the order of subtracting smaller shapes create inconsistent results.

# Additional information

Tested on Paper.js **0.11.3**, **0.11.4**

Chrome 63.0.3239.18 (Official Build) beta (64-bit)

Windows 10 64bit

**Comment by lehni** [comment]
This was fixed by 192437dbe26159a9b7412e258003c781ad469d5a 🎉
