### ISSUE TITLE
http://paperjs.org/reference/path/#path

### ISSUE THREAD

**Issue by sevaTechoPark** [paperjs/paper.js#1405]
I am trying scaling 
```
path: new Path({
                segments: [x, y],
                strokeColor: '#ff0000',
                strokeWidth: 5,
            }),
...
path.scale(magicNumber);
```
but even I try path.scale(1); the path disappears.
How can I scale this?

**Comment by sevaTechoPark** [comment]
Wow I did stupid mistake.
I did
`path.add([x, y]);`
instead
`path.add(new Point(x, y));`
This was the cause why I can not scale. Although `path.translate()` works right...
Close this issues please

**Comment by Jolg42** [comment]
@lehni this issue can be closed ;-)

**Comment by lehni** [comment]
@Jolg42 would you like to become a maintainer?

**Comment by Jolg42** [comment]
@lehni I could help with simple tasks indeed.
For more advanced stuff I don't know.

Maybe putting labels would help too like "help wanted" on issues or https://www.codetriage.com/?

**Comment by lehni** [comment]
Yes, in the past I've used labels, but even that I haven't managed to keep up with lately...
