### ISSUE TITLE
getCrossings() returns touching paths which do not cross each other

### ISSUE THREAD

**Issue by richnicholls404** [paperjs/paper.js#1409]
In the documentation, Path.getCrossings() says

> Crossings are intersections where the paths actually are crossing each other, as opposed to simply touching.

However, with the following code, these non-intersecting but touching paths are reported as crossing:

```
var path = new Path({
    segments: [[20, 20], [20, 80], [80, 80], [80, 20]],
    fillColor: 'blue',
    closed: true
});

var secondPath = new Path({
    segments: [[80, 20], [80, 80], [140, 80], [140, 20]],
    fillColor: 'green',
    closed: true
});

var crossings = path.getCrossings(secondPath);
console.log('crossings', crossings);
for (var i = 0; i < crossings.length; i++) {
	new Path.Circle({
		center: crossings[i].point,
		radius: 4,
		fillColor: 'red'
	});
}
```

Loving paper.js! It's absolutely amazing and I am very thankful for such a great library! Thank you!!

**Comment by lehni** [comment]
Yes there are a ton of edge cases where this doesn't work as it should. Unfortunately I have very little time available to further improve anything on paper.js : /

**Comment by richnicholls404** [comment]
I can completely understand. It's a very complex area of the library too. In case it helps you or anyone else who has this issue, I'll detail my fix.

In order to find out if a path overlapped another path (but without returning as an overlap if it happened to be touching), I ended up using something like this:

const intersectingPath = PathItem.intersect(secondPath);
If (intersectingPath.segments.length === 0) console.log('does not overlap');

Thanks for your speedy feedback!

**Comment by renschler** [comment]
I'm not sure if this should be logged as a separate issue.

But if you take two identical simple paths, and run getCrossings, should this return empty? Today it does not.

For example, see [this sketch](http://sketch.paperjs.org/#S/jZHNToQwFIVfpelmICEEGFdMXPEAGmfhQlyUzhUq11vTVo1O5t3tz5iBRBNL0oRzuOd+Jxw5iRfgLd/P4OTECy71Iby/C8Os+0S4GZ5BOnbNjj0xf6wzeoZ7dXBTy+piKXYatWnZZkAh583ZelKIZ4PeEHs69RSesMD45Jr5bIIPdivcVN55RdCIkEVJK3JZXVUF81dexO/26gsuWr67RDU+KUaWEjVBFryekhK7eH/RaZe85g+vJ6nJaoQS9ZillBFcZ7S1ikYbpSZPSwKCVEbWyzKdF1ZNtp56G4tcVT/gYSqAx+kVeFJ+h4tT/wJPKSvwOOzB/d8eDIj5NcBZ3j48nr4B)

**Comment by lehni** [comment]
Theoretically it should return an infinite amount of points :)

**Comment by lehni** [comment]
@renschler yeah this is a a bit of a workaround that was included for the boolean operations to work correctly, but it shouldn't affect the public API like this. See the TODO here:

https://github.com/paperjs/paper.js/blob/b51a4bed57be5827a730be8c6eb3d5e03fc13666/src/path/PathItem.js#L354-L360

You can work around this for now by doing this instead:

```js
const crossings = rect1.getIntersections(rect, inter => inter.isCrossing())
```

[Updated Sketch](http://sketch.paperjs.org/#V/0.12.3/S/lVI9T8MwEP0rpyx1JCtKUqZUZenEBKIDA2FI3CMxMXZlGxBU/e+c7VakEgxkcJJ39z7u5EOmu1fMmmw7oRdjxjNhduH/vbPg/KfC2/4FhYc1HFoN9DhvzYQPcufHBio+BzdGGdvAoledmBan0rNU6lTQb0q1+tjqVgujnYcB/cYa56QeHDmwfefHikN41Tmsr5NCRAvqvdEeraM0ktixueYgA0i96aOQ7qzI8nwVrMIklkgVkIXGD7gjYnFPSKcHhSxChtisKksOdOQ89m3lF/5gQewsVZNSlCyEMhpZMkpIXBrVZ8tbpVr9Ry1twygslBnYfCcsSvLkORtHSCuq+TQbAi5GWVLsZZzkqjwnD6yQPLIvkifk93SR9f/kUZInz5icrlZvsZv2IZ/Lmsen4zc=)
