### ISSUE TITLE
PaperScope#setup(element|string) documentation doesn't mention how to use the library inside a web-worker

### ISSUE THREAD

**Issue by alexjlockwood** [paperjs/paper.js#1412]
Commit [8fb7c41](https://github.com/paperjs/paper.js/commit/8fb7c415379f6d0711cb8ec9842cd8529a42c51b) introduced a change that made it possible to create a paper.js project w/o a HTMLCanvasElement (i.e. so the library can be used with web-workers, etc.). This is discussed further in #634.

However, the documentation has not been updated to indicate that this is possible. I think the [PaperScope#setup(element)](http://paperjs.org/reference/paperscope/#setup-element) documentation should be updated (i.e. now it is possible to pass in a `Size` object instead of a canvas element/string).

**Comment by lehni** [comment]
Yes, I agree. Could you create a PR for it?
