### ISSUE TITLE
Wrong area fill

### ISSUE THREAD

**Issue by Skippidar** [paperjs/paper.js#1414]
I have an object and i need to mark as red area 3 meters deep inside this object. For this i build area 3 meters around it's borders (`item.area.full`) and then to get area which is inside the object i use `item.area.full.intersect(item.area.item);` as a result I get `item.area.inner`. It should be like a big "border" inside the object. But when i fill it red - it fills not this area, but area inside this area. And if i set `onMouseDrag` for this area - it works as it should. You can drag the resulted area, clicking 3 meters outside red zone, not inside. And `contains()` for point inside red zone returns false....

As an example - [You can watch it here](https://granatland.ru/canvas)

**Comment by Skippidar** [comment]
Got this working. I calculate this 'wrong fill' area and then subtract it from `item.area.full`
```
        item.area.item = item.path;
        item.area.temp = item.area.full.subtract(item.area.item);
        item.area.inner = item.area.full.subtract(item.area.temp);
        item.area.inner.insertAbove(item.area.item);
        item.area.outer = item.area.full.subtract(item.area.inner);
        item.area.outer.insertAbove(item.area.item);
```

**Comment by sasensi** [comment]
I close this issue because there was no bug to fix and @Skippidar self answered his question.
