### ISSUE TITLE
importSVG not applying attributes

### ISSUE THREAD

**Issue by okitu** [paperjs/paper.js#1416]
When using importSVG attributes of nodes are not applied.
The basic attributes are applied directly by the importer-functions
but anything beyond that will just be ignored.

Have a look at this fiddle:
https://jsfiddle.net/4awsphbn/

As you can see, the small circle should be inside the pin,m
but because the "transform" attribute is not applied, it stays 
at the original cx/cy position.

This svg is certainly not optimized, but we have to work with imported
icons, and cannot optimize every icon by hand.

https://github.com/paperjs/paper.js/blob/develop/src/svg/SvgImport.js#L523
```javascript
function applyAttributes(item, node, isRoot) {
    if (node.style) {
    ...
```
This conditional never let's anything through.

I could apply the attributes by removing the conditional, and adding
it in the getAttribute function.

https://github.com/paperjs/paper.js/blob/develop/src/svg/SvgImport.js#L496

```javascript
function getAttribute(node, name, styles) {
    // First see if the given attribute is defined.
    var attr = node.attributes[name],
        value = attr && attr.value;
    if (!value &&  node.style) {
```

Now paper imports the svg with all attributes applied.

**Comment by sapics** [comment]
Thanks @okitu for reporting bug and teaching us how to fix!
And sorry for late response.

This looks serious bug in SvgImport.
Thus, I have created PR in #1532.
If you have any further updates on this, please write down here!
