### ISSUE TITLE
Boolean exclude operations fail for equal shapes overlapping at a 45 degree offset

### ISSUE THREAD

**Issue by edwinvanrijkom** [paperjs/paper.js#1419]
# Description/Steps to reproduce

When drawing 2 equally big circles, overlapping, offset from each other at a 45 degree angle:

![image](https://user-images.githubusercontent.com/2211269/33562653-0e8aa4b2-d916-11e7-8b41-904eaf482699.png)

then the result of running `exclude` between the two circles is incorrect:

![image](https://user-images.githubusercontent.com/2211269/33562636-03f4f296-d916-11e7-842c-1813c0bef5ac.png)

# Link to reproduction test-case

[Sketch](http://sketch.paperjs.org/#S/jZHBa8MgFMb/FfGUQiYmozsIu6yHXQc91h2svq0S9wzGdB0l//tM6hbSweg7CN/z4/t96Jmi+gAq6LaBqA+0pNqbUR9VINoG7aAij+RFxQPbTLI4SyRpNGCEIMjRwie7iPJyE5SxfSfImufFm3Vu451PbkkDGEklDiuJEmdK/T8lV2Gt72y0Hpkyprir1yVJx+omsA8K32HJhpN2vYEnZRL+h5GXRS6WzLONxZTSORVTw5Mg1T0vyZcgfFi6fsEpVtLWYjNyJebIqxTO+DTVnLWo9+z9Tf1G31V0/fC34GRbNty7Pr1M+v19ANW03mLsqNi9Dt8=)

# Expected result

A correct exclusion between the two circles:

![image](https://user-images.githubusercontent.com/2211269/33562724-493a15d4-d916-11e7-8fe5-330d016b638a.png)

# Additional information

Please note that a correct exclusion result is returned when (a) the two shapes aren't exactly alike (changing one radius to 51, for example) or (b) when the shapes aren't at an exact 45 degree angle (as outlined in the test-case)

**Comment by lehni** [comment]
This bug was fixed by 3ff5560c0c16a1ecd581ab558d6682becd6ddd75!
