### ISSUE TITLE
fontWeight is not working 

### ISSUE THREAD

**Issue by developersatish** [paperjs/paper.js#1421]
# In rectangle PointText is not appearing as 'Bold'. Here PointText used with symbol and placed.

```
 addressText = new paper.PointText({
        point: new paper.Point(0, 0),
        fillColor: 'black',
        fontSize: 9,
        fontWeight:'bold',
        content: '2.\n1.\n45.\n355',
        CustomType: "AddressText",
        strokeWidth: 2
    });
```

![image](https://user-images.githubusercontent.com/2935852/33699546-d481ee30-db39-11e7-9524-80167f339d6c.png)

**Comment by sapics** [comment]
It looks work well in latest version as http://sketch.paperjs.org/#S/vZHPCsIwDMZfpfRShSHbdB7qSXwBwcEO1sO2RldW29FW/Ifv7iKo4FHBQBP6y5fQj16pKfdAOV21EOqGRrS2Eu8GjqQrO3CjpVUm5HAKg6twwpA+OkScfGgGSRxHJIuH0VO3VVovrLaOE1bpsm7Zu2VNWKkLcJJMX7DuIeBmlo6EMAmmSYZ5nGXv2cXBB7vPz10/LehcSgfe4wsFfWl8cLaFQsnQcJIivQ1nWPB8Yy791RzCAtSuCZxVVkv2N9v9r1YOyvbhzFO+3tzu

**Comment by Jolg42** [comment]
@lehni working in sketch as @sapics posted, this issue can be closed ;-)
