### ISSUE TITLE
Shifting on hover effectes

### ISSUE THREAD

**Issue by ghost** [paperjs/paper.js#1422]
When the text or application size of the computer changes and refreshes the web site the hover effects on the canvas shifting.
  Windows 10 Pro 10586.962, Chrome 62.0.3202.94
-->

**Comment by lehni** [comment]
I don't understand what any of this means.

**Comment by BarkinB** [comment]
I have some rectangles in the canvas
If the computer's text size has changed 
the hover effects on the rectangles are shifting

**Comment by lehni** [comment]
That's neither a test-case, nor a screencast... I can't do anything with such a bug report. I don't know what "shifting hover effects" mean. What kind of hover effects? Shifting how?

You may want to read this text to better understand how to report bugs:
https://sifterapp.com/blog/2012/08/tips-for-effectively-reporting-bugs-and-issues/

**Comment by Jolg42** [comment]
@lehni this issue can be closed I think.
Btw I'll bookmark this link for the future, I'll probably need it too!

**Comment by lehni** [comment]
Agreed!
