### ISSUE TITLE
Not expected point coordinates for HitTestAll (and HitTest ?)

### ISSUE THREAD

**Issue by doom-fr** [paperjs/paper.js#1430]
In [Layer.hitTestAll](http://paperjs.org/reference/layer/#hittestall-point) documentation, it is written : 

> hitTestAll(point[, options])
> Performs a hit-test on the item and its children (if it is a Group or Layer) at the location of the specified point, returning all found hits.
> 
> The options object allows you to control the specifics of the hit- test. See hitTest(point[, options]) for a list of all options.
> 
> Parameters:
> point: Point — the point where the hit-test should be performed
> options: Object — optional, default: { fill: true, stroke: true, segments: true, tolerance: settings.hitTolerance }
> Returns:
> Array of HitResult objects — hit result objects for all hits, describing what exactly was hit or null if nothing was hit
> See also:
> hitTest(point[, options]);

As it is on Layer, I thought that the point was in Layer coordinates.
But it is not like that.
In fact it seems to be in Canvas coordinates.

Can you just precise this in the documentation please ?

Thx.

Doom !

**Comment by lehni** [comment]
Does the layer specify `applyMatrix = false`? If not, then the two coordinate systems would be the same. It's hard to say what's the expected behavior without a way to see what's going wrong.

**Comment by doom-fr** [comment]
Yes, I have set `applyMatrix` to `false`.

**Comment by doom-fr** [comment]
In fact, I process events with my own touch & mouse event library which give me client coordinates.
So I have to translate it in Canvas coordinates before giving it to hitTest.
I use different layers with different scale, angle and position.

**Comment by lehni** [comment]
The point stands: I can't help you without a way to replicate the problem.

**Comment by doom-fr** [comment]
No need for me. I have found the problem.
I just want you to update the documentation for others.

If applyMatrix==true : it is canvas coords or layer coords as it is the same
if applyMatrix==false : it is canvas coords and not layer coords

So Just write in documentation that point is in canvas coords.
It works in both cases.
You can also write that canvas and layer coords are the same if applyMatrix==true (default value).

**Comment by sasensi** [comment]
I think @doom-fr wanted simply to point out that the point passed to `item.hitTest()` and `item.hittestAll()` has to be in global coordinates system and that this should be added to the doc.
The mistake he did was to provide the point in local coordinates system instead, as in this [sketch](http://sketch.paperjs.org/#S/jVNNa8JAEP0rQy6JEGKK7SXSQ/FQChaECj2ohzUZk61rNmzGL8T/3tkktk2NtIeF3dk37719w56cXGzQiZy3NVKcOb4T68Se+32IDQpCEDlIwg0Igrsw9HnNzTzfCVOXHyHHPUwEZcFImlihd4IYc0IT1Tda5uTZTtve88GIRG7LCB64spJKjbTSjHW1EXmKLpx7QytgF5sgrpbK+lDiiAb0CgZhCIU8oCpB5nCARBqMSeqqpTD6g0+B4MoOx7YnEEWhjq+CjDyw3ZVQJQ5vYb/0vIG1HLbMpEigdCwUh5JAqvSSt1UKhS6ltVBesqlgL3w1aW5Y2SKDC3IITPgr0Jqxs0sYzjSoWKf6ucJ5Vxq9ivT+m7TxnWjIJAFhScCcS03ZRZLrUy6/S8rGlu6HcFc8DfxJdap3kNZW/896HUFrAnpLxZbsIeawtUKOJPXcr9ftWbIZ0SXoyPVvvrIOrCaF2eIP3mbgN4jbL20z2xlW7PzBlvyt1oX9FaUTzRbnTw==).

```javascript
// create an item at 100,100
var item = new Path.Circle({ center: new Point(100, 100), radius: 50, fillColor: 'orange' });

// translate layer of 300 pixels in x direction
project.activeLayer.applyMatrix = false;
project.activeLayer.translate(300, 0);

// get local and global item positions
var localItemPosition = item.position; // 100,100
var globalItemPosition = item.parent.localToGlobal(localItemPosition); // 400,100

// do hit test on both
var hitTestWithLocalPosition = project.activeLayer.hitTestAll(localItemPosition);
var hitTestWithGlobalPosition = project.activeLayer.hitTestAll(globalItemPosition);

// output
console.log('hit test with local position:', hitTestWithLocalPosition); // output []
console.log('hit test with global position:', hitTestWithGlobalPosition); // output [item]
```

I added that to documentation in PR #1559.
