### ISSUE TITLE
Is active thie project?

### ISSUE THREAD

**Issue by qianlizhe** [paperjs/paper.js#1431]
## Thank you.

**Comment by lehni** [comment]
Paper.js went through phases of inactivity before. As maintaining it is not making any money currently, I need to work on other projects, and the current one is a massive project that is absorbing me to the point where I am finding very little time and capacity to still work on Paper.js. 

There are plans for new features in the pipeline. I am open for other maintainers to join and help the effort. But right now, the project is resting.
