### ISSUE TITLE
'Unable to load canvas module.' Error in node version 8.9.4

### ISSUE THREAD

**Issue by lightbringer2994** [paperjs/paper.js#1435]
# Description/Steps to reproduce
I was using paperjs without any problems for the past few months with node version 6.9.5. But when I try to switch to node version 8, it throws the error, " Unable to load canvas module".

# Link to reproduction test-case

# Expected result

# Additional information

**Comment by sapics** [comment]
@lightbringer2994
Sorry for late response. Have you fixed?
It might be necessary to execute a command `npm install` after node version update.

If the problem is not fixed yet, please write your environment (OS and node version and so on).

**Comment by sasensi** [comment]
I close this issue for lack of feedback.
It will be reopened if more information is provided.
