### ISSUE TITLE
Shadow on raster items not drawn

### ISSUE THREAD

**Issue by s-light** [paperjs/paper.js#1437]
# Description/Steps to reproduce
original question at
https://groups.google.com/forum/#!topic/paperjs/tWceBtl2rgw

If i add a shadow to an raster Item like this:
```javascript
var raster = new Raster({
    source: 'http://assets.paperjs.org/images/marilyn.jpg',
    position: view.center,
});
raster.style = {
    strokeColor: 'black',
    strokeWidth: 0,
    fillColor: 'white',
    shadowColor: 'black',
    shadowBlur: 15,
    shadowOffset: [3, 4],
}

raster.scale(0.5);
raster.rotate(5);
```
i would think this should be the same result as this code produces:
```javascript
var raster = new Raster({
    source: 'http://assets.paperjs.org/images/marilyn.jpg',
    position: view.center,
});

var path = new Path.Rectangle({
    position: view.center,
    size: raster.size,
});
var group = new Group([path, raster]);
group.style = {
    strokeColor: 'black',
    strokeWidth: 0,
    fillColor: 'white',
    shadowColor: 'black',
    shadowBlur: 15,
    shadowOffset: new Point(3, 4),
}

group.scale(0.5);
group.rotate(5);
```

# Link to reproduction test-case
http://sketch.paperjs.org/#S/bVC7bsMwDPwVQUtcwJBTtFlUZGk/oEA7dIgzMDJtKZYlQWJiBEH+vUpc9wGUG+/IuyPP3MGAXPL3HklpXnLlm2t/hMgiJMLI1szhyN5uTXGuHcuV/CEqlGyhiYKsKkgJKYkAAeM+CR+7ygzQYaoGiMaenNiHblFOy8EnQ8Y7yY4GR6HQZeXMXe6eajeZikQni9l69qPoe3zx1sdsurOg+lltoj5MQ1qy5RfYGmvn6VEbwu9pDY0f/xe6Uc/2kJn71R/wtW3zfZJtHkr2uL1Grd1PVAUWi6VY/YofPQFhkaH80l1E6IM3jhKXm+3lEw==

# Expected result
http://sketch.paperjs.org/#S/dVE9b8IwEP0rVhaCFDlULYurLu3QsRUdOgDDYY7ExNiWfRBRxH+vnY9WlYqn+3j37r3zJTNwwExkHw2SrLMik3ab8hN45iEQevbEDLZs0SX5ZWVYfMEevUTBJjWRE2UJISAF7sCh3wdufVWqA1QYygN4pc+G7101KfphZ4MiZY1gJ4Utl2gic+xdp48rszJptQOqh8XvMeQLlASm0jgKuMXRiVNfUVqvnqdk5E7MlbdHN1C/pjhfpmXFgF8nXIfhgc4aI3K0TN42+GK19dH3RoNsRkN961NtqRZsNhR3SusR3daK8Addw9a2/xN1rWd9jJ27+Z/i224XTyz6k1hlKL8v2MM0WUtHGyRLiCea8fmvC28JCPNYiZ+78QiNS9MhE8v19Rs=

# Additional information
tested on Kubuntu 17.10; Firefox 58.0 (64-bit)

I think paper.js does not recognize the raster image as `fillColor` and so can't draw a shadow.

**Comment by blayzen-w** [comment]
This has been reported in the past and it looks like its from the transformation on the embedded image is applied twice or is done incorrectly if a transformation is applied in the onLoad function. @lilltiger found a fix for it by wrapping the content in the onLoad in a timeout.

See: #1192
