### ISSUE TITLE
Imported SVG, how to save as Path?

### ISSUE THREAD

**Issue by paulcanning** [paperjs/paper.js#1444]
I am importing SVGs to the canvas and its working well using:

```
    view.project.importSVG(image, function(e) {
      var svg = new paper.SymbolDefinition(e);
      var point = new paper.Point([x, y]);
      svg.place(point);
    });
```

I am storing the SVG image source and the X & Y coords in a database to reload them onto the canvas, however I'm storing them in a different table to hand-drawn paths. This is causing layer sorting issues, as paths are being rendered before any SVGs.

SO, my proposed solution is to convert the SVGs to a Path object. Below is an example of a hand-drawn path I'm storing:

> ["Path",{"applyMatrix":true,"segments":[[473,417],[474,417],[474,417],[475,417],[477,417],[488,411],[491,409],[492,409],[493,408],[493,408]],"strokeColor":[0,0,0],"strokeCap":"round","strokeJoin":"round"}]

How can I convert an SVG into something similar? (Basically a JSON object?)

That way I won't need a second database table.

**Comment by lehni** [comment]
As pointed out in the other issue. This is a bug database, not a support forum. Please post support questions on the mailing list instead. Thanks!
