### ISSUE TITLE
Although the item.removeOnDrag() method is called, the second tool.onMouseDrag event produces 2 items

### ISSUE THREAD

**Issue by DSnopov** [paperjs/paper.js#1447]
### Description/Steps to reproduce
Hope the title is pretty self-explanatory. This happens on retina displays, not sure about the regular ones. I also noticed that first and second mouse drag events trigger with the same `event.point` and `tool.minDistance = 1` fixes the issue.

### Link to reproduction test-case
In the test-case I simply log the total number of items in the onMouseDrag callback. You can open the console and make sure that there are 2 items at some point.
[https://jsfiddle.net/kan4hwsp/9/](https://jsfiddle.net/kan4hwsp/9/)

**Comment by lehni** [comment]
You're removing on mouse drag, but not on mouse up, so it makes sense to me that once the mouse is released, the last line stays...

http://sketch.paperjs.org/#S/bZCxbsMwDER/hdASBwg0dBSQqR1bNECGDkkGRWZt1zJpSLSDwvC/V4qHuGhvIcQnHnicFNkOlVHHFsXVaqccl/n9OZCThgmY3niI+BJsVeCIJFuY4EyQ5JiigG8IYQ+ENzhYqYtpgVkRqy5NRAOnRzPrbqRLvtGBG5Ldf7TP5AEuq09RArf40ZRSG3j6A57ZczCwuXrr2s1C5+1S87Y6YMcjvtN61zIFNCBhwJXf0C+t3x45N3vUnquiD/yFTrRN1xrx1X5j0K5ufBmQtEeqpE5TczrsNaBt76GiMqfL/AM=

**Comment by DSnopov** [comment]
Sure, the last line should always stay in this case. If a mouse cursor is dragged for more than one pixel, there always will be one line. The problem is that when user drags a mouse cursor for only one pixel, the drag event fires twice and there are two lines instead of one, which is inconsistent.
Sorry for the vague description.

**Comment by lehni** [comment]
Ah you're right, I can see it happening now. This is a bug indeed...
