### ISSUE TITLE
Item#localToGlobal() returns same results before and after its parent transforms when applyMatrix = false

### ISSUE THREAD

**Issue by kota65535** [paperjs/paper.js#1448]
# Description/Steps to reproduce
1. create rectangle path and add it to group
2. get global point at the bottom-right of the rectangle
3. change the position of the group
4. get global point at the bottom-right of the rectangle. It return the same position as (2).

# Expected result
I think it should return different position because its parent changed the position.
Here is my test code.

```
    // 1. Create path and add it to group
    let path = Path.Rectangle({
      position: new Point(200,200),
      size: new Size(100,100),
      fillColor: 'black'
    })
    let group = new Group({
      children: [path]
    })

    // 2. Get global point at the bottom-right of the rectangle
    let point1 = path.localToGlobal(path.getPointAt(0))
    console.log(point1)

    // 3. Move the group
    group.position = new Point(300,200)

    // 4. Get global point at the bottom-right of the rectangle again,
    //    But it returns the same result as (2).
    let point2 = group.children[0].localToGlobal(path.getPointAt(0))
    console.log(point2)

```

**Comment by kota65535** [comment]
Oh, I forgot the important thing. This happens only if `applyMatrix = false`.

**Comment by lehni** [comment]
You mean like this?

http://sketch.paperjs.org/#S/nVJNb8IwDP0rVi8UiZVSdqq0w8aBExIauzEOaRvaiBBXidkX4r/PSfmodpqIVNW1X1+en32MjNjLKI9WO0llE42iEiv/DTAewySBmZWCJLSCGhCmAlFVoAgIobZ4aN8N8NGSOsQTLPmVvMqShKm1jI8dAKBFp0ihycHIT1iiMhRnaTriZzi6gJz6kR1gxVE84fqkX98qrWeo0eYwKLQod4NrSbSt/l4Isuorh63QTnaV0/AmMShmjf6CuY9v8spG6cpKlrf2jWz+xdtF7FOWwNzzayyE5la5ORBsUiOhQCLcP1hVNwS4DTl7safnnv9nwtr87YnGUug3nAe+OKRqScG0Z4rT4bmnEo1DLRlexx1BX9Q0gQV+yHBjb1YhTC7jOLvRzWN6nkeP5PHOzkDUQpnRlYfPy4H85lhJB2tcgDvePU64g2ZWB3E2TP5YkrHATvFlQut0c7c/GRd4xQve6V1IuChfb06/

**Comment by kota65535** [comment]
Yes, exactly that's it.

**Comment by lehni** [comment]
None that I know of. I'll need to analyse the problem to understand what's going on.

**Comment by kota65535** [comment]
With a little survey, I found that it's because of old cache of the global matrix is used.
The cache is updated when the item is drawn at every frame, but this case Item#localToGlobal() is called before it. 
The most simple resolution is not to use the cache, but it may be some performance degradation. 
For a workaround, I will update a global matrix of an Item before calling Item#localToGlobal() like this.

```
    path._globalMatrix = path._matrix.clone()
    let point2 = path.localToGlobal(path.getPointAt(0))
```

**Comment by kota65535** [comment]
I noticed the workaround above does not work if the path is a grandchild of groups, because they also calls localToGlobal(). This a bit dirty code works instead. 

```
    path._project._updateVersion += 1
    let point2 = path.localToGlobal(path.getPointAt(0))
```
