### ISSUE TITLE
Post-Fix decrement on splice() index does not work as expected

### ISSUE THREAD

**Issue by mi-ja** [paperjs/paper.js#1450]
# Description / Steps to reproduce
1. Loop through an array
2. In the loop delete an item at the current index
3. To not miss an element decrement the index
4. Do that inline with postfix unary operator: splice(i--,1) where i is the index

For index = 0 splice behaves like being called with index = -1, meaning it deletes the arrays last item.
Debugging showed a jump into __$__ from paper.js before splice was called, which decremented i and called splice with index -1.

# Link to reproduction test-case
Tapping keys creates circles which shrink and, when below area 1, are removed from canvas and the array holding them. The issue happens when splice() gets called in line 17.
http://sketch.paperjs.org/#S/XVI9b8IwEP0rVpaaEqx06FBoJ6ouXSp1BAZjLviEYyPHJG1R/nvPCQ60Sy6+9+GXp5wzKyvI5tnnAYLSWZ4pt4vnRnqm0CsDNXthq81ibde2PFkV0Fnm7Dt8v7rWcmjAhgk7ExyippJfHw5tIJGFlvXvvEFoRY0/IFrcBZ2z60ID7nWYLJLeS7tzVbLopxh2/Eo6XuDxsvtb3UijAMv+E1IYGbQYNry3yNljUUwifaSKEo1ZOuM8ie62RqrDXW94KUMcT7XmIz1m6v5V8+ap0ksx1AtjpfM85kGyLBY0nlO1woDdB0276XTgsgStcCNqJSlqIZ7iNRHDkt/A0oMkr4ek/KP1ULkGeFKOmKiPBhVwnM1ykg5oFwc9OvoBtuR66Oups/lq0/0C

# Expected result
should behave like this:
http://sketch.paperjs.org/#S/XVI9b8IwEP0rVpaaEqx06FBoJ6ouXSp1BAZjLviEYyPHJG1R/nvPCQ60S8659+GXp5wzKyvI5tnnAYLSWZ4pt4vvjfRMoVcGavbCVpvF2q5tebIqoLPM2Xf4fnWt5dCADRN2JjhETSW/PhzaQCILLevPvEFoRY0/IFrcBZ2z60ID7nWYLJLeS7tzVbLopxh2/Eo6XuDxsvtb3UijAMv+E1IYGbQYNry3yNljUUwifaSKEo1ZOuM8ie62RqrDXW94KUMcT7XmIz1m6v5V8+ap0ksx1AtjpfM85kGyLBY0nlO1woDdB0276XTgsgStcCNqJSlqIZ7iNRHDkt/A0oMkr4ek/KP1ULkGeFKOmKiPBhVwzEk4gjibDccuDnp09Ctsyf/QF1Vn89Wm+wU=

# Additional information
this is why I think it should work:
https://stackoverflow.com/a/49017841/8166576

**Comment by sasensi** [comment]
Hi, thanks for the report.

This is a bug in `Paperscript` handling of postfix increment / decrement operator.
Reproduction case can be reduced to this:
```javascript
var code = 'var x = 1; console.log(x++);';
console.log(paper.PaperScript.compile(code, paper));
eval(code); // outputs 1
paper.PaperScript.execute(code, paper); // outputs 2
```

Here is the [fiddle](https://jsfiddle.net/xidi2xidi/9aw84jLb/1/).

About solving this, the actual failing compiled code is:
```javascript
var x = 1; console.log(x = __$__(x, "+", 1));
```
One solution could be to produce this instead:
```javascript
var x = 1; console.log(x); x = __$__(x, "+", 1);
```

Parsing is done here:
https://github.com/paperjs/paper.js/blob/fd1a517e84fb17d96b30536cded823651a32caf5/src/core/PaperScript.js#L254-L272

@lehni, what do you think ?
