### ISSUE TITLE
Changing scale of a layer actually changes scale of lowest children instead

### ISSUE THREAD

**Issue by amakely-moxie** [paperjs/paper.js#1454]
If I want to organize an animation by groups or layers, I would expect properties of those layers to persist after being set.

If I set the scale of a layer, the layer scale remains 1. The lowest level CHILDREN of that layer have their scale values modified to my new value.  I do not understand this.

So if I remove all children from the layer, and add new ones, I would assume that the new ones would be drawn at the desired new layer scale.  They do not, because the children that were removed actually held the scale value, which was lost when they were removed. New children are drawn at scale=1. 

I would expect that each item would retain their own transforms, and account for parent transforms when drawn to the canvas.

Example:

http://sketch.paperjs.org/#S/7VM9b8IwEP0rJy8xamQFsVGVhaFLh0qMCYOxr4mFsSMnQFHV/96zG0pVPiT2Dh587957vg9/MCc3yKZsscZeNSxnyut438kACp7A4R4WjWxRzE1QFnkMvHrjej4uipzOKIdxMXqsnBJvxtq5tz4QsWIrK9W6YoRULsrVoR0En4PftrxUy0iLkD2EAXqRBwy8pNwEEiA6Jcn324NcvOu8RWF9zbPZDGwkgOmgwx56DymbXpTDTtotUrzxe9i2YByoxlgd0GUXpJLOFDJ4gKOpcbV4p3uW/40eUr2/6XUs6UQ/OpXF8orUpYxz2WPWZeX7XK46njdVo8We8J+OgXQapNYxJtOgEiKEGHpZORqZCLjxO5wPJJ7Kub1EE1qiyY0lCqjTCkV18k/SXP3P7+RIf3YVUK7b2M+OTcvl5xc=

**Comment by lehni** [comment]
That's not a bug. Look into the `applyMatrix` setting: https://groups.google.com/forum/#!msg/paperjs/4EIRSGzcaUI/seKoNT-PSpwJ
