### ISSUE TITLE
resize  wrong !!

### ISSUE THREAD

**Issue by fanyongfeng** [paperjs/paper.js#1464]
The initial drawable area （1000， 700） is the same size as the view area. I scale up my view a bit, but the drawable area is not the same as the view area.

paper.view.scale(val, paper.view.bounds.topLeft);

paper.view.viewSize = new paper.Size(1000 * val ,700 * val);

I'm wrong?？？

**Comment by lehni** [comment]
Are you using css to resize the canvas? See here:

https://github.com/paperjs/paper.js/blob/develop/CHANGELOG.md#removed-1

**Comment by fanyongfeng** [comment]
thanks!
