### ISSUE TITLE
Mouse drag event problem.

### ISSUE THREAD

**Issue by EvangelosPetr** [paperjs/paper.js#1465]
This mouse drag event bug started from the release of paper.js v0.11.3:
    https://github.com/paperjs/paper.js/releases/tag/v0.11.3
The commit that caused this problem is:
   https://github.com/paperjs/paper.js/commit/fbd5eeb7ef12fe5f30565dd2b9fcdac3631c1e54
   Mouse Events: Fix item-based doubleclick events.
   Closes #1316

The bug is:
I have a canvas that I add svg graphics in it, canvas and svg graphics objects have the same event (mouse drag).
When the mousedrag event is on the canvas it moves the svg graphics, for the svg graphics objects is moving the svg graphic in the canvas.
At the svg graphics objects I have a point at the bottom right corner that when I click down and then mousedrag it resize the svg graphic object.
The problem starts when I do mouse down at the point of svg graphic obejct and then mouse drag if the mouse cursor leaves this point (because I move a little fast the mouse cursor) starts the mousedrag event of the canvas so for result i have two events runnin: the resize of the object and the canvas mousedrag that moves the objects in the canvas.

This bug started when updated the paper.js to the latest version. From v.0.11.3 and upper the bug started, below this version the mouse drag event does not have this problem.

**Comment by lehni** [comment]
Please provide a way to reproduce this, e.g. on http://sketch.paperjs.org/ or as a repo. Without it, nothing will get fixed.
