### ISSUE TITLE
Angular 5 Example

### ISSUE THREAD

**Issue by michaelb-01** [paperjs/paper.js#1466]
Does anyone have an example of using paperJs with Angular 5? I've tried but it doesn't seem to recognise any of the functions (e.g. paper.setup()). I have a stackblitz here:

https://stackblitz.com/edit/mlb-anuglar-paperjs

**Comment by alexjlockwood** [comment]
https://github.com/alexjlockwood/ShapeShifter/tree/next (in the 'next' branch)

**Comment by sapics** [comment]
Now, https://github.com/alexjlockwood/ShapeShifter/tree/next is removed.
But, https://github.com/alexjlockwood/ShapeShifter looks good example with new version of Angular and very interesting application!
