### ISSUE TITLE
What happened to scroll event

### ISSUE THREAD

**Issue by m5x** [paperjs/paper.js#1470]
We are migrating a simple vector editor from paper 0.9.21 to the latest version and we got stuck on scrolling. In the old paper version there was a scroll event on the view that we used in many places to recalculate and redraw items that are affected by scrolling. From the diff between the old and new version it seems that the scroll event has been completely removed. Does it have any replacement? How does one listen for scroll changes in current paper version?

**Comment by lehni** [comment]
Paper.js never implemented scrolling by itself, just the mechanisms to do so through changing the view's internal matrix, so I highly doubt there ever was a 'scroll' event. You must have been emitting the event by yourself?

**Comment by lehni** [comment]
I just looked through the source-code of v0.9.21, and it confirms what thought to be the case: There isn't any trace of a 'scroll' event being emitted anywhere.

**Comment by m5x** [comment]
You are right and I sincerely apologize for taking your time. I presumed previous developer of our vector editor used paper without modifications but as I just verified he modified it quite a lot adding not only scroll event but zoom event etc.

**Comment by lehni** [comment]
Interesting... Maybe these changes could be considered for the core?

**Comment by Doerge** [comment]
```javascript
const strokeWidth = 2.0;
// Experiment with this to see what works best for you.
const zoomMultiplier = 0.001;

let zoomFactor = 1.0;

scrollHandler(event) {
  event.preventDefault();
  // Incrementally change zoomFactor
  // Clamp between 0.1 and 1.5. Otherwise you might end up in +-infinity.
  zoomFactor = Math.min(Math.max(0.1, (zoomFactor -= event.deltaY * zoomMultiplier)), 1.5);

  const oldCenter = paper.project.view.center;
  paper.project.view.matrix = new paper.Matrix(factor, 0, 0, factor, 0, 0);
  // TODO: Bake the `...view.center = ...` operation into the new view matrix values.
  paper.project.view.center = oldCenter;
  paper.project.view.update();

  // We adjust the strokeWidth globally which makes sense for us, but might not in general.
  // [...paper.project.layers].forEach(layer =>
  //   setStrokeWidth(layer, strokeWidth / zoomFactor)
  // );
}

el.addEventListener('wheel', scrollHandler, false);
```
We do something along these lines if it can help anyone.
