### ISSUE TITLE
Clipping mask cant have fillColor or strokeColor?

### ISSUE THREAD

**Issue by liajoy** [paperjs/paper.js#1476]
If a Path to be a clipping mask which is the first child of clipped Group, it's fillColor or strokeColor would be transparent.
see the sketch http://sketch.paperjs.org/#S/PU+9CoMwEH6VkMUIIip0ETo5dC10VIcYr1VMk3DGdih9954/6XBwd9/f3Ycb+QRe8tsEXg084cr26/ySyJz0Q87OzMCbXalPqxGVBlHnWZZQtQk7ZXFjNl56H7WurLZIiqjTC0QBmT3aCf4YQk9QY0JEQcudqLQ1IA7HIvUozaylB3EExkH2QLu4cNplHcTmQIQdIqvROeiJ4nGBVUe/dQhycnY0fuZl3X5/

**Comment by sapics** [comment]
Yes. From the reference http://paperjs.org/reference/group/#clipped, *the first child in the group is automatically defined as the clipping mask*.
