### ISSUE TITLE
Extra Rasted added on the layer.

### ISSUE THREAD

**Issue by athiselvam** [paperjs/paper.js#1484]
Hi,
I tried to import the exported JSON from browser's session storage. It added a raster image of the final layer of the project in the project. 

Saved the JSON as follows:
_**sessionStorage.setItem('project_json',paper.project.exportJSON());**_

Importing the JSON as follows:

_**var data = project.importJSON(JSON.parse(sessionStorage.getItem('project_json')));**_

Please help me to resolve.

**Comment by sasensi** [comment]
I close this issue for lack of feedback.
It will be reopened if more information is provided.
