### ISSUE TITLE
Subtraction of two points return NaN

### ISSUE THREAD

**Issue by DayTimeDreamer** [paperjs/paper.js#1486]
var p1 = new paper.Point(10,10);
var p2 = new paper.Point(1,1);
var p3 = p1 - p2;

Test result: p3=NaN;

Expected result: p3=Point(9,9);

**Comment by sapics** [comment]
p3 is the result what you expected.
http://sketch.paperjs.org/#S/q1bKS8xNVbJSCs5OLUnOUNJRSs5PAfHLEosUCgwVbBXyUssVChILUov0AvIz80o0DA10DA00rWOKYvLAaoywqdExRFJhDFQBNEoXqBYsmJyfV5yfk6qXk5+uUWCsCbQzqSg1MbsApLVYySo6thYA

**Comment by DayTimeDreamer** [comment]
I don't know what's wrong with my program. It always return NaN. I use the Paper.js v0.11.5. If I use p1.subtract(p2), it will be correct.

**Comment by DayTimeDreamer** [comment]
Oh, I know. It's the difference between javascript and paperscript.

**Comment by lehni** [comment]
Yes, operator overloading as your example relies on it only works in PaperScript.
