### ISSUE TITLE
How to destroy an item?

### ISSUE THREAD

**Issue by DayTimeDreamer** [paperjs/paper.js#1489]
The API Path.remove() will
Removes the item and all its children from the project. The item is not destroyed and can be inserted again after removal. 

So how to destroy it entirely?

Because my graph'shape will be changed at run time while dragging and I need to redraw it every frame. So it will produce an item by path each frame. Will it produce many items in the memory?

	var draw = function() {
		var path = new paper.Path();
		path.strokeColor = "black";
		
		for (var i=0; i<polygonPoints.length; i++) {
			var pixel = pg.core.utils.toPixelPoint(polygonPoints[i]);
			path.add(pixel);
		}
		
		path.closed = true;
	}

**Comment by lehni** [comment]
This is a bug database, not a forum. But to answer your question:

Anything in JS not referenced anymore will get garbage collected eventually. There is no "destroying".
