### ISSUE TITLE
resize

### ISSUE THREAD

**Issue by supun19** [paperjs/paper.js#1492]
how to drawing resize when window resize. i use drawing tool its implemented by using paper js. so now i want to know how to drawing resize when window resize. i can access pepper.project object it has all layers. i want know how to change all point in onResize function.
can you   give me suggestion

**Comment by sapics** [comment]
This is a bug database, not a support forum.
Please post support questions on the mailing list instead.
Thanks!

**Comment by supun19** [comment]
@sapics thank you
