### ISSUE TITLE
RegularPolygon path cannot be converted to a shape?

### ISSUE THREAD

**Issue by ValentinZhao** [paperjs/paper.js#1494]
# Description
I just want to produce a triangle when I am dragging my mouse on the canvas. And I saw there is `RectPolygon` method could do this, however, I have to set the radius of polygon manually to the constructor. I am just wondering that I shall convert this path to`Shape` to implement this, nevertheless, `toShape()` returns `null`  in this case.

And this is how my code looks like:
```
const downPoint = new paper.Point(event.downPoint.x, event.downPoint.y);
const triangle_path = new paper.Path.RegularPolygon(downPoint, 3, 0);
this.triangle = triangle_path.toShape(); // null
```

**Comment by sapics** [comment]
From [the reference](http://paperjs.org/reference/path/#toshape), you cannot convert triangle to shape.
Shape type is Rectangle, Circle and Ellipse. (http://paperjs.org/reference/shape/)

**Comment by ValentinZhao** [comment]
Okay thanks for your time! But is there any way to implement the feature I mentioned in my issue description?

**Comment by sapics** [comment]
Yes, adding static method RegularPolygon in src/item/Shape.js and fixing some methods like _hitTestSelf, your issue would work!

**Comment by ValentinZhao** [comment]
Okay sounds like there is a long way to go...
