### ISSUE TITLE
Possible bug with subtracting paths

### ISSUE THREAD

**Issue by SBD580** [paperjs/paper.js#1496]
# Description/Steps to reproduce

I'm trying to implement grid cell selections. Every time the user click on a cell the path of the cell is combined with the current selection (unite) and when clicking on the cell again I'm removing the cell from the selection (substract).

I have some strange behavior when uniting cells and then subtracting them , here is a Sketch to illustrate:

http://sketch.paperjs.org/#S/fZPPbqMwEMZfxeJikyLUJTlUoellX2DFHoGD40wTJ47N2qbtbsS77xDCn9DuWkKy5xu+md9YvgSanyFYBz9P4MUhiAJhdu1ZGO08yciGrB7TQhdagScV9weHobzE0KuxrA3KzWMqn5epfHgIL4UmuHrpiNIRpeMoteuN26sVOml4Jz9wG2cgPNd7BWySWPjKSO3XJJeLLDousjKaik7+AdSyaB731pzgu1HGrgndKi5O9C7hVSo1yjXQUWzCdDxceeOqdgfWbnupKXTTj0SY81Zq2H1DmC7dwq4WwJiNPsLNy42mTTWYYuNaSw/sI+ziFtPP5g1Y723B11YTg8cm6qfDLmPHdG8BNI2mkBRr0iZsPYZ+Ym+5dopjsTxbrCL8yrDt+tplvirjwXNDf4NS5p0OF+1+1dzCwNRmC2V01+ZN/LJAOp9Lgh5jT67e4l/Cs5tHGDvwd3RVbSsFM7zuCpspX/IPvr65fqwjcXJH3E5shpsMuMln3Fm9J6z39AXucoKbzHGTz7gGTfdz3O42J7DL/8ImAyw+360Ffrq+Ghes87L5Cw==

First you can see the whole grid, next is the combined paths of all the cells (combined1) then the yellow cell subtracted from the combined path (combined2) and then the red cell subtracted from the previous one (combined3).
You can see that the last path doesn't have a "hole" at the middle like the one before him.

I'm not sure if that is a bug or rather misunderstanding I have regarding how paths are uniting and subtracting...

**Comment by sasensi** [comment]
No, you are right, this is a bugwhich is resolved by this change #1515.
You can try with latest library version:
https://github.com/paperjs/paper.js/tree/prebuilt/module/dist
https://github.com/paperjs/paper.js/tree/prebuilt/dist

**Comment by lehni** [comment]
Thanks for checking @sasensi! Let's roll out a new release soon!

**Comment by mpkelly** [comment]
Hello, 

Any idea when this bug fix build will be available in npm? I presume it will also fix the issue illustrated by this sketch, where the subtract return value is an empty path and the original path remains the same, too?


http://sketch.paperjs.org/#S/7VXBTsMwDP2VqJd1IonSrmQdiBNcJyE4Ug5ZFmi1LpnaMKQh/p04TVjHFQ5IoKpW7Wc/O6+R/JZosVXJRXK/UVbWCU6kWYO/Fx3aCVvfCCvQFZosM045zs4pr8mCckkY5TyfF5ghktEcM3o+m+d8cNwrGQ4ZKEAQRQGtgeLIAFESGbwzMMQmKIIeGHqAOSznuKRFPfsRtprMvn2wQ9CJ0fJX6ZQtMKtJVtBCusCiLPMcJprBrJRn2bwcHPfu3QlKRxrSUMABQiGl9kRHHgiTyOMd4CGBKDZEMcXDQz8wh2XO3KDOFCM1yFiOqFY8whdRyYmqYI7Nv6pLorz+l3u6U4HH+o7+6P/N/7/5f+zmTyod14BbAVq9omuz3ZkXvb51oTSuh+llpeGbPjVte21a08HCWLVCbiYR6qVoVZqxz9yd6RvbGO1S9416pVJpqzqHDj07Ja2DoA+9c99CP7v6USb289w3B5XmjGHkzHRaaag7maNK/CBVErDPvmdXiDPfTxrdW9S/rGwnZJhpGDqEUqiEyUc5p4ft1HriuXyPTm3NXqVQAdymVbQ1z+moegq5w+NW7qpTYrMzjbZ9cvHw+P4B

**Comment by sasensi** [comment]
@mpkelly, I confirm your example will be fixed too (I tested with latest version).
