### ISSUE TITLE
Memory leak on Gradient

### ISSUE THREAD

**Issue by rkdrnf** [paperjs/paper.js#1499]
# Description/Steps to reproduce
1. Create shape having gradient colors.
2. After removing shape by calling .remove(); gradient still remains in memory.
3. Memory continously increase after gradient creation.

# Link to reproduction test-case

# Expected result
memory used by Gradient must be freed.

# Additional information
Gradient remains in rendering context, as shown in chrome memory snapshot
![image](https://user-images.githubusercontent.com/1143159/44656535-32acb200-aa34-11e8-95cf-bfd84d992d64.png)

**Comment by sapics** [comment]
Thanks for the bug report!
I have tried to fix by releasing memory in #1511
Could you check the pr, whether memory is released or not?

**Comment by lehni** [comment]
#1511 has been merged. Can we close this?

**Comment by lehni** [comment]
I am closing this. @rkdrnf please reopen if the leak persists.
