### ISSUE TITLE
Scaling on symbol does not scale stroke width

### ISSUE THREAD

**Issue by rkdrnf** [paperjs/paper.js#1500]
# Description/Steps to reproduce
Make Shape as symbol, scale it before calling .place();

* scaling shape after  symbol.place() works normally.

# Expected result

Stroke width must be scaled properly

**Comment by lehni** [comment]
Pretty sure this has to do with `applyMatrix` and isn't actually a bug. https://groups.google.com/forum/#!topic/paperjs/4EIRSGzcaUI

**Comment by sasensi** [comment]
From what you are describing, I cannot reproduce any bug, but as @lehni said, I think this is related to `Shape` having `applyMatrix` property set to `false`.
The consequence of that is that when you scale the shape up, you also scale the stroke width up.
If the behaviour you are expecting is to have a constant stroke width when you scale your symbol definition item, you have 2 solutions:
- set `strokeScaling` to `false` on the shape
- use a `Path` with `applyMatrix` set to `true` (default value) as symbol definition source

Here is a [Sketch](http://sketch.paperjs.org/#S/jZTBbtswDIZfhfDFNua5KYZePOyUXQcUyG5tD4pML1oUyZDopkWRdx9F26lTBOgM2LAo8udHivZb5tQBsybb7JH0Lqsy7du0vrmBNqgjKIg71SMcDe2gxU4NlqBXgaMIQ3wMj+5ZhXlnI74/wOER5L1em6AtFs8Gj7VGxzHwBR5WFXy9vVs9VXC7Kr8nkaVAHSn4Pa699YHF8q1Vep+LW7qvofmBYIyCqJU17s9MpodI/jCDXaTR1jssypqCctEqwoK5GGskWgROQJtRmWU6ZSNeAeoVd+mTVonPBxLy92z9iPJtNaEsk8TXw9ZbUUvrjSyLpVoF+Zx9bFBxgd9QGNhH9b19/aUomJdGyinz6STeVRctYNFxdV1TFP5PNNW/QJR2fEqYLLNWurvBaTLewULYEB4qIEMWS3hLXsAX900H5I5OnUuNN85IcBdSPZwUW0jRIBMByrXQ88whG0HRuNX7KEGzbjrKSXGad1n8PKsLz3nGJEtxV5a1KI+bs+Z7XROxnLRUMhtThntvHP3GFyrO1aWrT+Zmgqm3fnBt5Inq15efG39ty6i/fJqmM1olgIZPV7zzCx/t2Za0L1BOI+4pPfiHseXu7oUhZs3D0+kf) comparing the solutions.

**Comment by sasensi** [comment]
I close this issue for lack of feedback.
It will be reopened if more information is provided.
