### ISSUE TITLE
Translating item caches incorrect position in certain specific circumstances

### ISSUE THREAD

**Issue by brandondahler** [paperjs/paper.js#1503]
# Description/Steps to reproduce
When translating an item with a pivot defined that is not the center of the bounds of the item, the cached position is incorrectly updated to the center of the bounds if the bounds have already been calculated.

# Link to reproduction test-case

http://sketch.paperjs.org/#S/jZJRS8MwFIX/yiUva6FsRehLxScRX4fzbdlDl16TsJhb03Sbjv13k66iFrdJQ0lyz8n5bsiB2eoVWckWG/RCsYwJquN6WzkQ2gmDcAfzyqvpEwpfWWkwsbiDOWnrkzyDPM0gbiz0ByZF2LjJ0/SW25N52ugt+XDEyPMteNHG3JMhF0QT6RDtJBTjFxGko64Z7I9xnixPvlXaq2YzeFa6hTAcvnXaYQ2ewDstJTrwCkFUQmGII9tSyDMkE84e9k1oBw6wLyEAvff/na69KiE2oVBL5cvQDBw563F/+Huq6Zo6W7fjGmecOx7YWDr0cTX5r4iv66NWe032WspI/uvCiwyKQXWWpOhJin+SXGI5XwmPa+2w2jSRqmXlcnX8BA==

# Expected result

```
Expect { x: 0, y: 0, width: 50, height: 20 }
{ x: 0, y: 0, width: 50, height: 20 }

Expect { x: 0, y: 0 }
{ x: 0, y: 0 }

Expect { x: 5, y: 5 }
{ x: 5, y: 5 }
```

# Actual Results
```
Expect { x: 0, y: 0, width: 50, height: 20 }
{ x: 0, y: 0, width: 50, height: 20 }

Expect { x: 0, y: 0 }
{ x: 0, y: 0 }

Expect { x: 5, y: 5 }
{ x: 30, y: 15 }
```

# Additional information
Apply the following diff fixes for me:
``` diff
diff --git a/src/item/Item.js b/src/item/Item.js
index 6b8183f2..68e26eb5 100644
--- a/src/item/Item.js
+++ b/src/item/Item.js
@@ -3507,12 +3507,16 @@ new function() { // Injection scope for hit-test functions shared with project
                 }
             }
             this._bounds = bounds;
-            // If we have cached bounds, try to determine _position as its
-            // center. Use _boundsOptions do get the cached default bounds.
-            var cached = bounds[this._getBoundsCacheKey(
-                    this._boundsOptions || {})];
-            if (cached) {
-                this._position = cached.rect.getCenter(true);
+            // If we have no pivot defined and cached bounds, try to determine
+            // _position as its center. Use _boundsOptions do get the cached
+            // default bounds.
+            if (!this._pivot)
+            {
+                var cached = bounds[this._getBoundsCacheKey(
+                        this._boundsOptions || {})];
+                if (cached) {
+                    this._position = cached.rect.getCenter(true);
+                }
             }
         } else if (transform && position && this._pivot) {
             // If the item has a pivot defined, it means that the default
```

**Comment by sasensi** [comment]
The code change you are proposing indeed fixes the issue but prevent from using cached bounds for items that have a defined pivot point.
I made a PR #1531 that should fix it but still use caching.
