### ISSUE TITLE
Multiple subtractions where paths are touching, result is an open path. 

### ISSUE THREAD

**Issue by HHogg** [paperjs/paper.js#1506]
Possible bug with the subtraction of paths where the point of intersection is at the edge of the shape, which the result is an open path.

# Description/Steps to reproduce

Create 3 overlapping circles, where the middle circle subtracts the other 2 circles that are touching. 

<img width="236" alt="screen shot 2018-09-09 at 17 44 31" src="https://user-images.githubusercontent.com/7130591/45266767-2f63ee00-b458-11e8-95ec-b25f774d1b4a.png">

[Example Code @ sketch.paperjs.org](http://sketch.paperjs.org/#S/pZRBD4IgFID/CuNSbs6hZqWtU3+grWN2IHxNp0FDqkPrv4fGJVuLCZx4sPe99w14YE7PgDO8q0GxEvuYiaJb57ybNyoRqyRrIERrxOGOtlSVwaYPTR85R3ow4ApkhvZhmvooJOTgvzckLaprm6GEmECrpKhhIxqhj08kFJOcP73VJymyIEU6pTsptiDFJBxNMv0E7fWoJGVqalR6w0jsBaeqafokuqY+y6DWmY0Voq1EUeJmJbH170yaW/kfTzL9DG3PvvzP//tfWPnXdyVOHG/l0ta/Mym1IXVveiTJ9DO0vfjyn/7yr/+jowRaX0TFVYuz/eH5Ag==)

# Expected result

<img width="227" alt="screen shot 2018-09-09 at 17 48 15" src="https://user-images.githubusercontent.com/7130591/45266789-92ee1b80-b458-11e8-9d1d-48a5a7746edd.png">

The result of the subtraction is a closed path (similar to that above).

**Comment by sasensi** [comment]
I think it is the same problem as this one #1513
