### ISSUE TITLE
boolean subtract fails for semi-circle inscribed in rectangle

### ISSUE THREAD

**Issue by renschler** [paperjs/paper.js#1513]
# Description/Steps to reproduce
I've reproduced the behavior in the sketch linked below.

I have a rectangle, and then I have a semi-circle that is inscribed within the rectangle.

I am trying to boolean subtract the semi-circle from the rectangle. Example 1: When I do so with {trace: true} the operation returns an empty path (this is wrong - ie not the expected behavior). Example 2: When I do so with {trace: false}, the operation returns a single line, the edge of the rectangle that is shared with the bottom of the semi-circle (I'm not sure if this is wrong, the trace setting is confusing to me but I think it's wrong).

Example 1: Subtract with {trace: true} is supposed to leave me with a path containing the green sections, but it's not doing that.
![screen shot 2018-09-23 at 12 24 34 pm](https://user-images.githubusercontent.com/3973468/45930919-b7072d80-bf2b-11e8-9c17-e8811ac511a2.png)

Note: In my sketch example, I take a few steps to get to the Rectangle and Semi-Circle. That is how this issue surfaced in my code.

[paper.js sketch](http://sketch.paperjs.org/#S/rZTBbtswDIZfhfDJBQwn0W4OdllfYFgL9DDvINuMLUSWAklp5xV995Fy7MZJWmDALglMip/+/6eT18TIHpMiedhjqLskS2rb8LPGALVWhw18BYMv8F2GLv+BdZCm1ZjGklUmpJv1OgP6uMviuQf1B1NBNS7dbUtTGkY52aijZ9iX9Xo71mrl6gX+ngpX7BF9mmdgHMt3Sut7q60jQJm0DtGUydz1wdk9PqkmdNTfXNTf5yot632cm4WSRWpF63mtrcGUL+UyTQ8auXli0dNMdnggFl0ZupQPR6UR4rC3zyPl5JvK4n/GyrDNIlbxaazMEWexiilWcRHrtzmesXs7VvFprCypk3rHKk7ZiZxUoPNkO41hZPCqjEcXCthJ7TGD4CjMgr6O+MbqJsJiB2KxA7HYwTQw7UFc7wF/y/6gkV/Bcb3Hiq8N8+yZLBZyoao0q9WEyD1qQmBDLO5uYbUCY0OnTAvBQqM8SRtAmuFFDp4kWeOtxlzbNi2TWYnHtkcTfFEmGZzBxypLJ+5jpzxMYpU1pN4fdfCgDN05M/I8v3Aq/tlp3MbCqrhp1Ro9QOgQKhuC7UErg8AqT2c/MCxuGhbvhtkA4TvVcJDegiKbKL1Cx7F6xHjrLGki8FR0+qy8quILE63EAOd36bpJ/3+VQ7k/8O/EJ8XPX29/AQ==)

**Comment by sasensi** [comment]
Hi,

I will try to investigate the problem.
As a workaround for this case, you can use [Item.exclude()](http://paperjs.org/reference/path/#exclude-path) instead.
See it working in this [Sketch](http://sketch.paperjs.org/#S/VZCxDsIgEEB/5cIiNU1TO9o4mLq4GRsndUB6WlIEQ6kajf8utLWNA5C7472DexPFrkjmJK/Q8pKEhOvCx3dmYLtcrXc5LCCJ4/RgDsovXzDILVMXieCKCh+wYbaMtr8sbVNaKEtncRyC24KwvZeLF9JeO4Uk7FsEQfpTc2G498KfOmuzdOgbnXSjitod1uprhsqiGWSDq2Ty3JHONbLC365dSLtmwd/f8MllUwutAPpXjGRbK5CO4o4dmOgspMy01MZxE20chpPUTfVkkFU3P5KazPfHzxc=).

**Comment by renschler** [comment]
thanks @sasensi 

that workaround is for when the trace option is set to true.

When it's set to false, I think this is the workaround needed:
[sketch](http://sketch.paperjs.org/#S/jZE9b4MwEIb/yokluEKEZgRlqOjSrQrq1HQw5ggoxo5s01aN8t975jPdOtjWfT2vX901ULzDIA2KMzrRBFEgdOXjT27g8PT88lbAHnZJkh3NUfnjCwaF4+okEaio8AteuWviw5wNh5RulQsfkyQCulg09BXtD4YT9gF20STBWDajRWuE58IfdD5kw0U3LnWvKkuPc7rLUTk0C2xhNVzW4ySx1tnWd1sKw1GMLd62W2q7SC6wIyTU+s5qbPvSGU5TKzaCq09hCjWXFm9sVsZvIXvbagUwWVk5Q63COwz7F3v55QKPLUrCYkV8Z3rMRg9rvW6lzLUkG3vYaEP6uMlox6VBfr74Bdkgff+4/QI=)

**Comment by sasensi** [comment]
If somewone else wants tries to solve this, the problem can be reduced to [this case](http://sketch.paperjs.org/#S/rVNda8IwFP0rl7y0Qol1ri8dDqb+gMEeqw81vdpiTCSJcyD+96Wpse3QfcACgeacc2/OyaUnIvIdkpS8bdGwkkSEyaI+D4dQicrAPjelXqiFeM+VO7zABAQe4dV+h6eaAbs0bnYojE4h81C9MhjFcQTjOIZldIMY3SCSbwnXyuOtQiNHZrBIwagDXmHGpcYCoIFr9Dx46qaZ/jFNcifN+J7px+T/TNfbzsXyApvBwFoqwA/GD7qSohtsZoO5cVEnDwfUqFxonhsMraOHJO4/xPyin/6g9zX6sNJWwYy99xLWX2gpx4SuX1PWldN1xflMcmt9AoHCInASJoWWHCmXmzDotT9KtdVB1LuT+hlRjmJjSniGLw6vz9KzN6MOL9C5mzclV+lvrLV9va+2/K4p+2OtFObbvawsTdJsef4E).

I wasn't able to solve it, but I found that it is linked to this call to `_getWinding()` which seems to return a wrong winding value of `0` at the triangle top point.
https://github.com/paperjs/paper.js/blob/6cbf5292da1551cd870a3ef78e087199d2344738/src/path/PathItem.Boolean.js#L748-L757

Moving any of the points or changing the first offset value here, solve the problem.
https://github.com/paperjs/paper.js/blob/6cbf5292da1551cd870a3ef78e087199d2344738/src/path/PathItem.Boolean.js#L727

**Comment by sasensi** [comment]
@lehni or @iconexperience, can one of you look at this PR #1515 to see if it is a reasonable solution ?

**Comment by lehni** [comment]
@sasensi I've just merged #1515, thank you for your contribution! Are you interested in working on more paper.js features?

**Comment by lehni** [comment]
@sasensi oh wow, that's super nice! The code looks rather complex!

From working on this, is there any method that you feel should be added to the `Path` / `Curve` interface that would simplify the code for this effect? Maybe this is something you could start working on implementing?

**Comment by lehni** [comment]
As for helping out otherwise, there are a ton of things that need work. Looking after issues, fixing bugs, wrapping up the path to 1.0.0 (not sure what's holding us back actually : )

**Comment by sasensi** [comment]
About this extrusion effect, if you think this is something that could interest other people, sure, I could integrate.  
For example as a path instance method `extrude(point)` that would return a `Group` made of: background (`Path`), sides (`Group` of `Path`) and edges (`Group` of `Path`).  
An example of usage would look something like

    var path       = new Path('M4.477,1.992C4.931,1.311,5.702,0,6.648,0c1.336,0,0.655,1.76,0.366,2.424z');
    var extrusion  = path.extrude(new Point(50, 50));
    var background = extrusion.children[ 0 ];
    var sides      = extrusion.children[ 1 ];
    var edges      = extrusion.children[ 2 ];
    
    background.strokeColor = 'black';
    edges.strokeColor      = 'black';
    sides.fillColor        = 'yellow';

What do you think about that ?


About other tasks, I will look at still opened issues and try to resolve them.  
I've also seen the discussion about path offsetting which seems to be a difference making feature unfortunately on a pending state. Could I help you finishing its implementation ?

**Comment by lehni** [comment]
I was more thinking of the more lower-level tools / helper functions needed to make the effect work. Perhaps we could add some out of this that would help making such an effect, and others, simpler?

I'm super interested in wrapping the offsetting up!  The main issue at the moment is my availability, as I got swallowed by a massive project that pays my bills and consumes all my time currently. I'm happy to help where I can and time allows, and things should again get better around March 2019, time-wise.

Progress has stopped around here, when @sapics started looking into some of the edge-cases:
https://github.com/paperjs/paper.js/issues/371#issuecomment-297585655

This would be the right place to pick up work, maybe also together with @sapics who has started helping out more with paper.js stuff, and has become a contributor.

**Comment by lehni** [comment]
PS: I meant helpers like `getCurveTimesAtVectorTangents()` and such.

**Comment by sasensi** [comment]
Sorry, I misunderstood your question.  
Actually, I think a curve method to get times at tangent to a given vector could help in some other cases.  
For my example, I adapted the method mentioned in this [comment](https://github.com/paperjs/paper.js/issues/371#issuecomment-277541824).

I could integrate it as `curve.getTimesAtVectorTangents(point)` and `path.getTimesAtVectorTangents(point)` which would return `float[]`.

For path offsetting, I will look the code in more detail and see with @sapics how I can help to get this done.

**Comment by lehni** [comment]
Very cool! Yes we could than share this method with the offsetting code, indeed!

**Comment by sasensi** [comment]
@lehni, here is the PR #1530 for Path/Curve#getTimesAtVectorTangent methods.

**Comment by lehni** [comment]
Let's close this issue here and discuss the PR over there. @renschler feel free to reopen should you still see problems

**Comment by renschler** [comment]
wonderful thanks. I will give it a test.

This is a beginner question but now that this is merged in, is it included in the latest version on npm? Or are there more steps involved before it becomes available on npm?

**Comment by lehni** [comment]
@renschler no it's not automatically released, but you can use the prebuilt versions for testing, see here: https://github.com/paperjs/paper.js/issues/1513#issuecomment-425644738

**Comment by renschler** [comment]
ok gotcha, yes I tested and this resolves my issue. Thanks!

Another beginner question but how often do these changes get incorporated into a release?
