### ISSUE TITLE
Disable image smoothing on Raster?

### ISSUE THREAD

**Issue by akeshavan** [paperjs/paper.js#1521]
I'm trying to disable image smoothing when zooming on a Raster, but I'm not able to. It looks like someone also [asked this on stackoverflow](https://stackoverflow.com/questions/49166140/how-scale-raster-without-image-smoothing) but there are no replies. Does anyone have suggestions?

# Description/Steps to reproduce

I'm trying to to set the `imageSmoothingEnabled` property of the canvas context to `false` so that the image looks pixelated, like in this example: https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/imageSmoothingEnabled which works on my browser (Google Chrome | 69.0.3497.100 (Official Build) (64-bit))

# Link to reproduction test-case

Here is my codepen: https://codepen.io/akeshavan/pen/GYRZZm?editors=1010 with my attempt to do this with a paper.js Raster, but it doesn't work. 

Any tips would be greatly appreciated. Thanks!

**Comment by sapics** [comment]
It would be necessary to get context from view.
Is it what you want? https://codepen.io/anon/pen/gBOMdJ?editors=1010

**Comment by akeshavan** [comment]
Perfect! Thank you so much!

**Comment by lehni** [comment]
Let's keep this open as we should probably add an API for that?

**Comment by sasensi** [comment]
@lehni, I implemented `Raster.smoothing` in #1529.

So, @akeshavan, once this change will be merged, you'll just have to do:

    raster.smoothing = false;

**Comment by lehni** [comment]
@sasensi thanks for taking time to do this! I will make time to review it properly soon. There will some minor changes, mostly to align things with internal architecture and also change tracking to take note of the need for redraws, but nothing major.

**Comment by akeshavan** [comment]
awesome, thanks @sasensi and @lehni !

**Comment by lehni** [comment]
This will be part of the next release!

Speaking of which: @sapics and @sasensi, could you help me with updating the CHANGELOG? You can look at its content to see how it should relate to the changes we've added since the last release.
