### ISSUE TITLE
Travis error in node v6.13 and v6.14

### ISSUE THREAD

**Issue by sapics** [paperjs/paper.js#1523]
I could not find out why node v6.13 and v6.14 cause error in SymbolDefinition.initialize.
https://travis-ci.org/paperjs/paper.js/jobs/434854796
If someone could fix error, please teach me or make a PR!

Keeping travis state to green, I specify version to v6.12 from v6 as temporary solution in .travis.yml in #1522.
It is important to check source code quality at first glance by travis state.

**Comment by lehni** [comment]
Closing this because it has already been merged

**Comment by lehni** [comment]
PS: We can probably remove Node 6 soon, as we're already at 10 now.
