### ISSUE TITLE
Adding Blend modes

### ISSUE THREAD

**Issue by sapics** [paperjs/paper.js#1524]
Copy from #1505 created by @SkepticaLee.

### Description
Provides execution for missing blendMode:
pin-light

Adds new blendModes:
minus
divide
divide-source
hard-mix
pegtop-light
linear-light
vivid-light
grain-extract
grain-merge
darken-intensity
lighten-intensity
divide-intensity
multiply-intensity

Provides newer, simpler code for:
color-burn
color-dodge
darken
lighten
difference

#### Related issues

none
### Checklist

- [x ] New tests added or existing tests modified to cover all changes
- [x ] Code conforms with the ESLint and Prettier rules (`yarn eslint` passes
      and `yarn prettier` has been applied)

[paper.zip](https://github.com/paperjs/paper.js/files/2349840/paper.zip)

**Comment by lehni** [comment]
@sapics instead of the ZIP, could you turn this into a proper PR so I can review the code?

**Comment by sapics** [comment]
OK, I have created PR in #1527. It is not my work, but @SkepticaLee's work.
