### ISSUE TITLE
Export Only Clipped Portion of View

### ISSUE THREAD

**Issue by MannikJ** [paperjs/paper.js#1550]
# Description/Steps to reproduce
![screenshot](https://user-images.githubusercontent.com/1841856/46605863-30da1200-cafb-11e8-9865-62d228760919.jpg)

I have a quite simple use case in which I want to load an image paint something on it and then export it as png.

I am exporting by calling rasterize on the active layer, but that creates a raster object of the complete layer with also the whitespace of the canvas included, which is not what I want. How can I only export the image with the painting except the whitespace?

**Comment by sasensi** [comment]
Hi, can you provide a working example showing the problem you encounter ?

Here is a demonstration of what you are describing in [Sketch](http://sketch.paperjs.org/#S/dVOxbuMwDP0VwkscNJCDAF186NS1w6Ed2w6sxFhKFUmQ5Bi9Iv9+lN2mTnKnSSIf+R757M/K4Z6qtnp6pyx1taqkV+XdNKAiDoAOzB47eokv7oARIqZMEe7A0QCP46P+LEngk3wfJbWw0DmHtmkwJcpJBAwUd0n42DVjs9TsMRr74cQudIvVdzlzDpqYMINJYD0qUt857x743cK2dzIb7+olnGi/apNES6VY+cGxcAXBohwjmOFgWLAkx4LndVmbJMbKei02t8tfV8ngkymMPHPpIaYeI+5CwLQwkCZKFsIV2QfwWxYwB5YtfkGmLf7GrMX9GKnPZipnYmvn1KtLTERl+tTC5vYqtTXW3nvrucPCR3QdLeaQ4/Jfc0wemz8EFj/O1/XzCXBa8QAh+h3JLJBdOdBDwYsToD5fZ/FI+2HeYCSAN987lebQH4hIZJlgJMuxp8uOk8dXLdnxrDluOp2LB55vxqEdTTKu+w/ZyeybO3ie4mJSJwajsoYb2KxXsH49yTiWC++Rf523SPgevHE5Ve3z6/Ev).
You can see that no extra space is added in my case.

**Comment by MannikJ** [comment]
Thank you very much for preparing the sketch! I actually realized that my question (especially the screenshot) in now way described the actual problem.
Please take another look at the [sketch](http://sketch.paperjs.org/#S/fVOxbuMwDP0VwkscNCcHBXKDi0xdOxTt2HZQLMZWqoiGJMfXK/LvR1lp6jjoeZLIR76nR/ozs3KPWZk9v2OommyRVaTivShAOdmDtKD3ssZX92oP0oGTPqCDNVjs4Wm45J8xCfx56lyFJcyaENqyKKT3GLxoZYtu5wW5uhia+WIvnTYfVuzaerb4KmfOvkEmDKA9GJIK1VeO7APfS9h2tgqabD6HM+2p1lfSYCxW1FsWrqA1shoiMsBBs+AKLQse14VGezFU5ktxu5rfXSVb8joy8ptjD5F6XOAMBqDN7pH8f0AJIP7ArzX8Xt1NxCezodKu4kcwW6AWaMvix8A4gRMkTeBRhkbcD5H8wo/4JRHliXkxTTupdOdLuF1dpbbamHsyxMUzctLWOBtDjsmmyRPSaui/CEZ+XLr8vTmcVqy9dbTDKgjJwzzgQ8SLMyCfT93xDfXjBgMBbKizyo+h3xDh0TDBQBZch9OOaTWuWvKihIbjum5CtJ/4pK00w3y0rX8gO+/IzRpeUlwkdaLXKjRwA6vlApZvZxnHeGAf+Y/bOJTvLWkbfFa+vB3/AQ==). I would like to clip off the parts of the drawing that do not lay on top of the image.

**Comment by sasensi** [comment]
For that, you have to create a [clipping group](http://paperjs.org/reference/group/#clipped).
Here is the updated [Sketch](http://sketch.paperjs.org/#S/dVRLb+MgEP4rI1/iqF4cVcoeXOXUw156WHWPaQ4EiE1KAAGO1a3y33ewXdePrE/AzHyPYfBnoulFJEXy510EViVZwgyP+zwH7mgDVIO80FK8uTd9pQ4c9UE42IEWDby2m/QzBgE/b2rHRAGrKgRb5Dn1XgRPLLXCnT0xrsxbMJ9fqJPqQ5OzLVfZVzlyNpVAwgDSgzKUC/4VM/oF9wWcas2CNDpdw0Db13pGlYjF3DQahXOwirL2hAa4ShTMhEbB47pQSU/aynRDHrfrp0XQGi8jI3qOGKTDeJqRd80CJh1DEZgdjAVzQvJxYuxgn9J18DcNFXluT9KJn/h1TMVMBvyA/c9ttjlk83xHuax9AY/bRegklXo2yiDayjiqS7Eap9w63zNPzAkaRHSlpLVSl+AEC1iM8o/UCx599gNxNLXmfuG1L3wd6ka2h8O0wyAdxnre2qWM0pnaQiNDdV8c9WjY+QCskorPRXXVnZBfcZ0uZGa9ray/rammFoC0RdiDHQRXi3v96zDkXwGKfkzH7vspYThiWGfOyE4oTvdVvMR8MiSki574yjRjgJbgziV8pxAvFBJMBY8Qu7eygMSXEyo8l2UV4jwbXElNVTvw2LL/kA3T+rCD/eR6SSM53tsDbDcZbA6DjFtc9HOIv6EjXvq7NVIHnxT7w+0f).

**Comment by MannikJ** [comment]
Thank you very much! It is not more or less working ;) How can I get all drawn paths directly from the project object? At the moment I am pushing all paths to an manually managed array, but they objects are already stored somewhere in paperjs, so how could I access them?

**Comment by sasensi** [comment]
I close this issue since there was nothing to resolve.
