### ISSUE TITLE
Subtract fails with any shapes, when they fully overlap each other.

### ISSUE THREAD

**Issue by eXponenta** [paperjs/paper.js#1557]
Test: http://bit.ly/2pGCxqS

Draw from red shape to red shape with full overlapping a blue shape.

**Comment by sasensi** [comment]
Hi, there is a problem in your logic, you only do the subtraction if `shape.intersects(aim)` and this method return `true` only when there is at least one intersection between both paths.
That's not the case when one fully contain the other.

Here is the updated [Sketch](http://sketch.paperjs.org/#S/lVZNb9swDP0rgi+1G8NNV3SHdLm0vexQYFi30zIMis0kRmQpkOR0QJH/PkqKZcmOh82AY8skH8nHD+Q94bSBZJG87kGXuyRPSlGZ86blpa4FJ6UEquGRiXVaAtcgc9LQ319pVbcqJwdRc60y8r6SK07wOlJJDlTvyJJweCNf8DXNHjqpkRQlEwoqVNCyBS/aCElSY12jZP6Aj09ndHyfzQIXnZsKmKadH6OZRirmYsC3ercgqQ+ZXJN5cZ+RGUlfTDCS8ko0aYbfhzr5EI3yLQMEu/s4Jzc+9WtSh4qnPlufMa2qM3no14bdK50iblQjRMSYBN1KboX2m1U3t2FA7egBkIGgRj0Zd/N5TvAny8mte3Wo1qhQWoo9PAmGtC/JKpFQrZJAvqkZm5YqYFDquIhdULRupkK6nwgJTUYBrVkLZ59GHMczEP4tnEa0CsJu9E0SeFyQqzWj5f7KUpxFAIwq/csW26C0jHmpnxHBX4yXZ/HGUzhioYNujcytsLAnX2EboG2RQJrFxR55knQ78mRnAp30Host6OdaacpLGKMbm3pD0gon7XY+GDDXd+Mu/Y90etWe0M6n06rNSCgsnXIfskEQTktCI47wCtsGvak0nq+pOA0ZHKB6YkBNz2woU/2ysXtGfe7co3wUkG30mKjA4sI6cvvAQyH1XhsrNwLsQJ1Z4TYVWS7JhwF2hy9BtcyE6kaw5bWGM20PQ32n4ohLJ8SI5CAnrC8N1SUtXn0Tjzg7F/yEBRhhnKKadYebG6LatZYUq2Lay3CkdyCBULy5IHVIalhPz4/dCGeMIetGNqLFbawBGVN7pZcNEg87xSf+7w0dqpWYmmBQMLFNV4mrFqZPF6skP/NujjHhsZHJyZuYeGMDz/nkivl+GC0YF31p8kqDBYV/GtYIvnednCx+/Dz9AQ==).

**Comment by sasensi** [comment]
I close this issue because there seems to be no bug to fix.
