### ISSUE TITLE
drawing path with large strokeWidth causes unexpected sharp angles.

### ISSUE THREAD

**Issue by crono009** [paperjs/paper.js#1560]
As the title states, I'm getting weird angles while drawing a path with a large strokeWidth of 30. Below is an example of me drawing the number 3 multiple times.

![image](https://user-images.githubusercontent.com/28131759/46726072-659cb500-cc32-11e8-9948-d60c429da52b.png)

I'm surprised i can't find any post or documentation on this issue. I can even replicate it on the paper.js example here: http://paperjs.org/examples/path-simplification/

Simply change the strokeWidth to 30 and it's almost impossible to draw anything the way you want to. 
Has paper.js addressed this issue or is there some workaround for it? Thanks in advanced!

**Comment by sasensi** [comment]
Hi, the issue you are seing is a common stroke drawing problem that you will encounter in every drawing library / software. `Paper.js` relying on [canvas API](https://developer.mozilla.org/fr/docs/Web/HTML/Canvas), this is related to how this API handles stroke drawing.
In `Paper.js`, you can control how stroke joins and cap are drawn with respective [item.strokeJoin](http://paperjs.org/reference/style/#strokejoin) and [item.strokeCap](http://paperjs.org/reference/style/#strokecap) properties.
By default, `strokeJoin` value is set to `miter`, which means that at a sharp angle, stroke will be interpolated under a certain limit. You can control that limit with [item.miterLimit](http://paperjs.org/reference/style/#miterlimit) property.
Here is a [sketch](http://sketch.paperjs.org/#S/tZTBbptAEIZfZcUFaNFqAWMHolySW5VDpVTqgfiwXsbNxnjXWsZ22yjv3tm1cd1crEjNAQGz//wz34zgJTJyDVETPawA1VOURcp2/n0nHdtIfGI3zMCefaXH5IUN8GMNBoeGtW1e81k5zVg5rfhsUswz1lYVF0WdsbwSY2g242VR/KMqqppf5SXJaopVPjTJpzwXOcmqgouyns/Za3r96B6N74EP6OwK7mxvHfUTL3qpVvHb4++6C+0W4uwEelAIHYXRbSEcBByrDX6Dn0hMyhokpobFHSzltkeWrDWCS+OMbbyuCYPgC7s13UA3RLu+owxw7DNrBXEIQRBL8nnQv6FhJcWetwPqpVYStTXkrUJCPGL5y4/YedPQX6ihemsgSTk6aYZeIiTnpfeB8BPLeZUxcTA6Ghxn8IX69RMK0fgC7kF0ghydPoSz136m7+QsT5THdB4Wc+9fyKm6wBfE1HpI/ss5en0I5wJ20L+PcnK2zZD+ZpchdmmXB9GJ8eDz3wk3zj7T98SlQr2De/kLHF9qvA11kp2G/VhzULKHRPCrNL2mn8rCgVyF3oaoaeevfwA=) demonstrating the different `strokeJoin` possibilities.

**Comment by lehni** [comment]
@sasensi has summed this up really well. There's nothing we can do about this in paper.js. Some of these artefacts may be side-effects from the way canvas optimizes bezier drawing in the GPU, some may be in the handling of the geometry itself. But all we can do is work around it with either stroke styles or better path geometries... Closing this as we can't fix it in paper.js
