### ISSUE TITLE
How to change default unit to millimeters?

### ISSUE THREAD

**Issue by ceremcem** [paperjs/paper.js#1566]
I'm using Paper.js for engineering purposes, so I need all dimensions to be expressed in millimeters. Currently I'm using a conversion function: 

    function mm2px(mm){ return mm / 25.4 * 96 }

...but it would be nice to write everything in millimeters by default. Is there anyway to achieve this?

# Edit 

Asked also in SO: https://stackoverflow.com/questions/52829984/how-to-change-default-unit-in-paper-js

**Comment by sapics** [comment]
There are no unit system in paparjs. If you would like to use only mm unit, [view.scaling](http://paperjs.org/reference/view/#scaling) might help you.

BTW, howto questions should be posted to the mailing list: http://groups.google.com/group/paperjs.
This is a bug database, thus, please help to keep free from support questions. Thank you for your undestanding.

**Comment by ceremcem** [comment]
> Add: I just read your edit now. I will answer in SO.

Thanks, I just read it. 

> This is a bug database, thus, please help to keep free from support questions.

Many projects follow different approaches, so, it's absolutely okay.
