### ISSUE TITLE
How do I use the events in plain JS?

### ISSUE THREAD

**Issue by netpoetica** [paperjs/paper.js#157]
I was able to get most of my code out of the awful PaperScript sandbox, and into real-world JavaScript, but it seems that all of those global events are being ignored now. How can I tell Paper about an onMouseDown function that I declared outside of document ready?

Could I assign it by reference like paper.onMouseDown = function(){ ... }? I tried this but no luck.

Thanks a bunch!

**Comment by manuelro** [comment]
You (and that gist) saved my day. :)
