### ISSUE TITLE
Error Report: exportSvg error with singular matrix

### ISSUE THREAD

**Issue by sapics** [paperjs/paper.js#1580]
There is `Uncaught TypeError` in function `exportSvg` when `item.matrix` is singular. [sketch](http://sketch.paperjs.org/#S/TY/BisJADIZfJczFGShqPVY8iXgSZLu7lx0PY01ttU2GdFZdxHffjoKaQCD5/p8kV0WuRZWp/IihqFSiCt7F/uQEBIsAMyA8Q145j8OPfuBo36C+WoI+SuE2uwvWXFPQ6XicQF9M8uCB3+kk0smLlnXTzLlhyWAguBtYupmppbh2GMRRV7K0OvpXLkh90WnyTGMsWfLCh6jGi2cJ+fdSGxiN4IsK97uvAnz+eVyIsFjqX9sKuqOPp3Qq+9nc/gE=)

**Comment by sasensi** [comment]
Resolved by https://github.com/paperjs/paper.js/commit/c30767ed2e2637c3954e046043c710d12e2417ca.
