### ISSUE TITLE
Cannot get the correct bound params.

### ISSUE THREAD

**Issue by joy-yu** [paperjs/paper.js#1583]
```
  var path = new Path({
    segments: [
      divide1.bounds.topLeft,
      divide4.bounds.bottomRight
    ],
    selected: true
  });
```
![image](https://user-images.githubusercontent.com/9348314/47286373-058a1380-d621-11e8-83e5-7675d508140e.png)

The divide4's bottomRight shouldn't be here.
I've created a simple case on [CodePen](https://codepen.io/anon/pen/zmLRBj?editors=1000). Just check it out.

**Comment by joy-yu** [comment]
@lehni No. I post one more issue because of the network. So I close this.

**Comment by lehni** [comment]
I see! When I asked, the other one wasn't showing, also because of Github's issues yesterday :)
