### ISSUE TITLE
shear and skew give same result

### ISSUE THREAD

**Issue by maen007** [paperjs/paper.js#1606]
Testing the methods shear and skew at  [sketch](http://sketch.paperjs.org/#V/0.11.8/S/fZDBjsIwDER/xcoeaKuIphI9AOLEDyA4AocQXFo1dVAa4ID4d5xl2a447M3jmXmWfBekOxQzsWkxmFpIYdwx6qv24NEETSeLsADCG6zfOolq5RoKSakklCqVMKyKuCuUStP5jiLnrEP9g1jxOB44vxdiNMbGVWPt0lnnuTD6wilOq2r0Nnu0XMAje8FfkNc7yrMMLmRc1yEFaIivNb6HLMvZy1+1GrVPCqnktzQcRJ8Odou3ZFJ+2C/4X4CSxT8AJRnxAeB3Hjzq9hz/0ovZdv94Ag==) shows that except the parameters of one is in degree and the other parameters are in totals the result is the same!?

Do I miss anything?

**Comment by sasensi** [comment]
No, you guessed right.
That can be confirmed by looking at the `matrix.skew()` code which is internally calling `matrix.shear()`.

https://github.com/paperjs/paper.js/blob/8202f78453411c54bd197fc3f0dc15f0f897230b/src/basic/Matrix.js#L364-L371

**Comment by maen007** [comment]
So this is not a bug?

**Comment by sasensi** [comment]
No, I don't think so.
Were you expecting a different result ?

**Comment by maen007** [comment]
Coming from photoshop and gimp and inkscape, yes, I did! One is creating a kind of a parallelogram like here, the other one is kind of a free transform tool.

**Comment by maen007** [comment]
Why are there 2 methods which does the same?

**Comment by sasensi** [comment]
Oh ok, I see.
Unfortunately, `Paper.js` distortion capabilities are far less advanced than in `Photoshop`.
AFAIK, you can't for example do perspective transformations and things like that...

About why there are 2 different methods, maybe @lehni could answer ?

**Comment by waruyama** [comment]
"Shear" and "Skew" are both used frequently for the same transform. Paper.js decided to use `skew` with point values and `shear` with angles. Maybe the documentation should explain the difference.

**Comment by lehni** [comment]
If I remember correctly, we initially only had `shear()` working with shear factors. Then came the SVG import, and we needed to support SVG's own `skewX` and `skewY` transforms which provide angles. To do this smoothly, `skew()` was then added tot support those.
