### ISSUE TITLE
drawing is different from the point of touch

### ISSUE THREAD

**Issue by yasithph** [paperjs/paper.js#1607]
I have been testing paper js on safari (ipad) and I noticed that when you move your finger down the y-axis the line drawn falls shorter than my finger. The longer the line that I draw the longer the distance between my finger and the last point of line. This happens only in y-axis and there is no problem with the x-axis. On my laptop this works without any problem. Problem only occurs in iPad or tablets. The problem is common to shapes as well.

**Comment by sasensi** [comment]
Hi, can you provide a test case (ideally a [sketch](http://sketch.paperjs.org)) allowing us to reproduce the issue ?

**Comment by yasithph** [comment]
Hi @sasensi 
Thanks for your response. I managed to resolve the situation myself. I called event.preventDefault(); on both onMouseDrag and onMouseDown functions. The problem was due to scroll when touching. The displacement due to scroll made the difference between touch point and end of line.
