### ISSUE TITLE
[Question] Is there paperjs server-side

### ISSUE THREAD

**Issue by CreatorVilius** [paperjs/paper.js#1608]
Is there a way to use paper js in Node js, server-side? I don't want to embed it on my website **right now** or anything, but use it in my Node js project. Is there any chance there is server-side paper js?

**Comment by sasensi** [comment]
Sure, look at the [installation instructions](https://github.com/paperjs/paper.js#installing-paperjs-for-nodejs) in project README.

**Comment by CreatorVilius** [comment]
Hey, sasensi!
Tutorial only tells how to do in Node JS Web Server, but not in plain Node js.

**Comment by CreatorVilius** [comment]
I don't use any HTML.

**Comment by lehni** [comment]
I don't understand this question... You can use it in plain Node JS, and some of the examples show how. One of them serves the result in a web-server, but that's just one illustration of a use case.
