### ISSUE TITLE
PaperScript does not handle postfix Increment/decrement operators correctly

### ISSUE THREAD

**Issue by lehni** [paperjs/paper.js#1610]
Example:

http://sketch.paperjs.org/#V/0.11.8/S/q1bKS8xNVbJSCs5OLUnOUNJRSs5PAfFzUksUShRsFQxj8pLz84rzc1L1cvLTNUp0dTUV9PUVgjPyS3NSFAqKMvNKQGqAGpOKUhOzC/KBAsVKVtGxtQA=

**Comment by sasensi** [comment]
Duplicates of #1450 :)

**Comment by lehni** [comment]
Silly me :)
