### ISSUE TITLE
PaperScript chokes on condensed expression

### ISSUE THREAD

**Issue by lehni** [paperjs/paper.js#1611]
Code:
```js
function easeInOutQuint(t) {
  return t < 0.5 ? 16 * t * t * t * t * t : 1 + 16 * --t * t * t * t * t
}
```
Error:
```
Line 2: Uncaught ReferenceError: Invalid left-hand side in assignment
```
Sketch:
http://sketch.paperjs.org/#V/0.11.8/S/q1bKS8xNVbJSCs5OLUnOUNJRSs5PAfHTSvOSSzLz8xRSE4tTPfP8S0sCSzPzSjRKNBWqY/IUFIpSS0qL8hRKFGwUDPRMFewVDM0UtIBcdGylYKigDZHU1cWQjsmrjckDWppUlJqYXZAPtKBYySo6thYA

**Comment by sasensi** [comment]
This issue can be reduced to [this](http://sketch.paperjs.org/#V/0.11.8/S/q1bKS8xNVbJSCs5OLUnOUNJRSs5PAfHLEosUKhRsFQytY4pi8pLz84rzc1L1cvLTNQwVtBR0dSs0rYGKk4pSE7ML8jPzSoqVrKJjawE=):
```javascript
var x = 1;
console.log(1 * --x);
```

Here is the explanation of what happen during compilation:
```javascript
var code = 'var x = 1; console.log(1 * --x);';
var compiled = paper.PaperScript.compile(code, paper);

console.log('compiled', compiled.code);
// output: var x = 1; console.log(1 * x = __$__(x, "-", 1));

eval(code);
// output: 0

paper.PaperScript.execute(compiled, paper);
// output: Uncaught ReferenceError: Invalid left-hand side in assignment
```

Code should be compiled as:
```javascript
var x = 1; x = __$__(x, "-", 1); console.log(1 * x);
```
instead of:
```javascript
var x = 1; console.log(1 * x = __$__(x, "-", 1));
```

This issue seems highly related (as the opposite problem) to #1450.

**Comment by sasensi** [comment]
I had another idea which should work in all cases and be easier to implement: using [IIFE](https://developer.mozilla.org/fr/docs/Glossaire/IIFE) syntax.
Compiled code would be:
```javascript
var x = 1; console.log(1 * (function(){x = __$__(x, '-', 1); return x;})());
```
I'll try to implement it.

**Comment by lehni** [comment]
@sasensi super cool, thank you!

**Comment by sasensi** [comment]
I made a PR with this idea, unfortunately, it can't solve the opposite case (postfix operator #1450) which seems to be harder.
