### ISSUE TITLE
Impossible to import some SVGs - inside arcTo() function

### ISSUE THREAD

**Issue by barnabeus** [paperjs/paper.js#1613]
While working with SVGs, I noticed that arcTo() function is unable to import some of the points in the path, here is screenshot of the error: https://i.imgur.com/4qj6c50.png

The problematic piece of code: https://i.imgur.com/voXKbLz.png
inverseTransform returns null;

Here is Sketch with the same problem: 
http://sketch.paperjs.org/#V/0.11.8/S/VVbLbhtHEPwVghfbwGxr3g/FNqDkkEtyMpBDosDYrBlRkUQSJCM5MPzvrurZlWJI7H3N9PRUVdful/VufNisL9cf7jbnabs262n/ideP43F1erz5eN6czqt3q1dvcbH6/HC/O727Xm/P58PlxcXT05M8Bdkfby68tfYCQ67Xq8fbzdOP+88YZld2VezKWXu9fr96e7O6/YS7D+Pp7uPhfvxvc9Tbh/G8XfHBr9mJd6Y6Sek0iE/GDhL8IM5Ng5cQhiAJJ3WoEsMQxdbBObFtDFKy0WD5NzhxBSHypq099CdIIL4+2olj3CC1IWHKuAoN6T3zlzxG8dFoeE4YEVLZ2glDo67AoxefkdFxbhmdlVxNj5zoWMSQJDrjUV4PcyG+YAceO8NTpMlSAkamhCm5DkWKY5XYdmJuj8GoMEtODIOzP4VmAmoJJhSJxlfBdZYWjM+oksVJTARCSgOGyOvz6BQl9x1WDetjxiAW4FgCkgtRYaiVoYyhScVKGvu8II5g5coiCUjOqJEgujxUPWztFfZv+FM0jGsScR2xlquD1gZcJVWSAjLC1o6VqNcX6LFZ0J4wJQfC4bmUx73aFQBcylUxM64GrPAHBgsZLM8MmjhJ8igmMDiW5XlWHPRRi2RwJL4hJN7J2RBxhJxOWBZaCYb8GLIxSor4n0kGsBK4p0hdOsNKJepaIwQKSnqcQZCaqK2AevAESWPBdSo4s9lkyHYMngX02NdIHMylzbJXqqZEEuKy1DjH/gSlV2o0U+eREFOqlASbqHntBFA04Fwy2QsExLE7ArlQfYN8cEP+MpARPBAUD9Jw4dmXiiQ6rR8w9graD8702LeLvYEw8kf2AUwuwAJXmQxkZLSZiscMXdC3E9UhqWE6Uk5Moys2spW4TK8MG6dcybFX7aYGuIH1LAWoEacTWcWqEchyX6VCXYlS8m6UCnX7hUYUAsTIuiN+hNOzOzkHHdObxBeaBrHFwsyH0SeSHouiRizCsyCpeRMb2KU5lGB67Jr0nAxi230vWF3JJu6GjuSxg5jZXaWrwtMTNcytYYlhugpoF1SosWdCGcWimVBrNhr6fWyL9bVJ6w4UfYMlOTb6y9k94U5R50e2UwzPioOTomJ/5ZBoWc0H04LERi+DQ2TyR3IruKZ6PJo6Evb4XB82jVSUS1JM0owJNG8gyTBC7DOAnmwRNL4CepiXhYkRnWDQNc/+DuuZ+msDLoZWYwPQM9RZfd2qqap1BTXVMqj80IV1oE70XQDX62bcDyPxgH1rXLhDN8E44GaQxBwXR6102wADHykGVcRSH2qBrlhh6z/YPiTYDTrCtzIF2WPff6ayYOT37NDQJpV6izqhtL6VouJQB1v6rre08eoQPS7Yk3mLRClhuxIyQaXxWbJWfH9bsh8DtSdpdIpyj0t2mAi0gixAJdMLHT3bUZ1OiVZ5Wr69NeYTcmpv4hyCKN5omIXJBBPyMQNFo5up7DvHcrtu9Rl2C0OhF+LUwYph3vXltUoh0rVLD0t6nV9OiTZSaD6ZpDRY0YQT0CKhG10/oAVovmgBoLF8PszQevV2jctLPjd910zdlWb9R90f1BDHJGybRf1JXxCo2ZnFq9jobFNskRhoXOQfqM7qrgAF4Zhn/O9j6ffr9QU+pC5uGPAR9v7VD9fH693huP9nM53l9uGwP54//Pbz6+WDzvz972463+53r998+frmu8Ej7j9ufuHXmRz2p1uOwvcfP+pk2uzOm6MOx4fiX8fNeHfY3+7Op/XlH39+/QY=

I thought its related to latest fixes in #1543 fixed by @sasensi , but the commit was related to code after the lines making problems.

**Comment by sasensi** [comment]
The error was due to an invalid arc in your SVG (equal from and to points).
Problem will be fixed with #1614.

**Comment by barnabeus** [comment]
Yes, indeed. Thanks for a quick response.
