### ISSUE TITLE
Fill Color Tool

### ISSUE THREAD

**Issue by ReyGab** [paperjs/paper.js#1617]
So I'm trying to do a tool that looks like fill color in windows paint. A selected part of image can be colored. 
![samp](https://user-images.githubusercontent.com/21187842/49055959-8cd83180-f234-11e8-80cc-97af82ae8e60.PNG)

Applied different approach by transforming the image to svg then selecting every path of that specific svg. But it's a very long doing, because you have to apply all the path of svg. I also tried hitTesting the specific part of an image and get the bounds of the item then fillcolor it but nothing happens. Is it possible to have just an image then color the specific part of it. Thank you for those who can help me!.

**Comment by lehni** [comment]
This is an issue tracker, not a support forum. I am going to close this issue, as you've already posted this to the mailing list as well.
