### ISSUE TITLE
Specific boolean intersection case fail since v0.10.4

### ISSUE THREAD

**Issue by sasensi** [paperjs/paper.js#1619]
# Description/Steps to reproduce

Do boolean intersection between 2 specific shapes.

# Link to reproduction test-case

The bug is reproduced in this [sketch](http://sketch.paperjs.org/#V/0.11.8/S/zVVNb9w2EP0rC128BgiCw+Gni1ziW5G0BXLowVoEXC1tq5alhaTYNQL/9w6pj3Uco0HRHnoQdt/jDGfe44j6WrThPhYXxae7OFa3BSuq7pDwQ+g3YfNu08bHzW9hvN2e8/r+2PXjz59+/WV7dlUWiS0L9rUswvHYPH0MY1//WRYXY/8lsrLojqGqxyciykJwpMiyGOLNfWzHgcirK2e5cMyA5ELv2AxRGG6FUZ4YYyV/i5lTdrRh1XRDPJyKXtdNc9k1XZ8qABNM7J53Z+c/lX3ZJkX7WdFlR1q+tIe3lb1c/YcKq9u6OfSxzQp/6NE3foCxHBgJlKtSeswMrGUKkduMwXBhmaYfSNYpL7meMS7YM5SSy4zRr1gv2J6sh+R9xgvQDBUVJ4jyBGHBhkkx49T1gnM6Ku6QgfM8HxkIqkXYGKIJU2veM0DSatdTB8q2KdojF8CM4wqXXKrtSP2ytWWTyu9O/5kifmj4IYyBEC0/1uPt59DeNDG5fx2aIT6/PhFF9Z00UjPQnhozWaFS1I8GUMQqjkIlm5QTJNOhZKCAU0gO1QK4p+E1DMh7tAtrSa2jfAAO5IzJJNVCYJ4KSWVxjnNCEOkM9yhzoWlLhZpZzY3xaimutECmDR20EbC26Z2nueEW87nnGtqSpSc5aAX3IJzJcdK5tCNSAEg0Lu/o1BQJlhtPp5BL64UEGlI0uUcwPs/MCy3CeVjDaH0SLUj2sqOzRk/+GCXX4hRqJy/RGlz6FBIg2y69M+rNK2AY++4urpcAXQEcvQRDV8G6+nt9SGNyIf/V0OSpez0zCJiEJDvpn51NluQtamDKESekn8QTh5bmSOtTJM3QKZLuPvd/FKkl0PxYT3NNrz/SO5LOLbNCCcXwBWvUN2yehsyd8on7D0TuXt//lMDgdP+nZ8/D4XCZ7uhtmNg9P3ZDPdZdS58Gcl8yZfxuTTj23R+xGnmoxvohfghPsf9ui+XjUtEOe163Y+wHylmWK752RQFnN32M7dm8Mn9CiCdt62YVH/vQDk0Y49YIwTbi/G8buq7H9+l7NWwf6vjI9/k/H6rQxC29NOdTNn3b930Md8eOWhzIn93zXw==).

# Expected result

![screenshot-sketch paperjs org-2018 11 29-10-00-55](https://user-images.githubusercontent.com/11247504/49213725-32baa600-f3c5-11e8-91d8-9c19ee9bbfe8.png)

# Actual result

![screenshot-sketch paperjs org-2018 11 29-10-54-37](https://user-images.githubusercontent.com/11247504/49213734-3bab7780-f3c5-11e8-8ac6-b724e1b557c6.png)

# Additional information

This bug only shows up in versions 0.10.4 and later.
It was originally reported [here](https://groups.google.com/forum/#!topic/paperjs/e3djsQeNWg8).

**Comment by lehni** [comment]
The way boolean operations are currently implemented, unfortunately there will likely always be some edge cases that fail. @hkrish has some good ideas about a better approach to boolean operations, but implementing it is far from trivial. I am very reluctant to spend more time on ironing out kinks in edge cases, but maybe @iconexperience could take a look? He helped a lot with the past iterations of improvements...

**Comment by lehni** [comment]
I've looked at InkScape in the past, but I think the code is rather massive... Size is a concern here too. Not sure what's best to do at this point, as we've progressed pretty far with the current approach. It just feels like edge cases don't stop to pop up!

**Comment by hkrish** [comment]
Is it such a crazy idea to depricate boolean ops altogether within the core library, and inherit from some thing like https://skia.org/user/modules/pathkit?

**Comment by lehni** [comment]
Oh wow, I wasn't aware of this! Not such a crazy idea, but the asm.js is almost twice the size of the whole paper.js library, and the wasm version is about the same size... I guess outsourcing would make sense though. @hkrish did you test it? Is it good? I remember Skia's boolean ops having some glitches and side-effects in the early days?

**Comment by hkrish** [comment]
It is quite a large library for sure (gzipped download size, for wasm seems to be comparable to paperjs, was it ~130K?). I haven't tried it yet, so no idea on glitches or accuracy. It seems they have been working on it though --https://skia.org/dev/present/pathops. 
Also they have a "canvaskit" pending release which is a canvas based implementation of whole skia?! It all depends on what will people use paperjs for, for building interactive editors and such, this might not be a bad idea.

**Comment by sasensi** [comment]
I've set up a little [fiddle](https://jsfiddle.net/xidi2xidi/k7a4nb2m/) running `Skia` and `Paper.js` in parallel to test boolean operations results.
It can be used as a first step to check if it performs better or not.

**Comment by sasensi** [comment]
Actually, for this specific case, `Skia` has the same intersection bug 😞 ([fiddle](https://jsfiddle.net/xidi2xidi/k7a4nb2m/3/)).
And by tweeking path data just a little, `Paper.js` result is better ([fiddle](https://jsfiddle.net/xidi2xidi/k7a4nb2m/5/)).
It seems that they have problems with edge cases too.

**Comment by lehni** [comment]
Wow... That's pretty crazy :)

**Comment by hkrish** [comment]
😆

**Comment by lehni** [comment]
I've reduced this case [to this sketch](http://sketch.paperjs.org/#V/0.12.3/S/lVNNb+MgEP0ryJckEkJgbPyx2sv2uofV7jHNAeNp4q0DESapqir/fQc3xNWql45kwZsvvRk/3jKrj5C12Z9nCOaQ0cy4PuKL9kST78TCC/mlw4H9BhO03Y+wfnv0j5agPXl3bMm2rhivKVEiZ7zc0RQNDmOqyhnGJFes4qpolrA7aTOE15ZwJu/Op2EcH9zofEtWHvpV9F833+IRv0iqu5F6cMeTO9s+klsofdrVHIax92CRT3JFS6Mt1ckm2B/BhgkLbhNIzlktdnSGVUULKVmlIhaK8YqWeAgcfls0OStvWCbcUJnnLJ+xbO64TLiiaXlbEbc54wRKKgukgFDmCxS7ZZXJzOgm6FsS/Bk+xq4b+vW5pZBMqqJWtMBbJVQdGeUFektBixp9PG/iCuZMWYmCluWSKesPmfj/6y8RTmj3qTS68Qz/ayPpw6A+OjbYAH5Cya71e4ph9waYsNp7ALu6FxsWvLbTqAOsFeeU8KXxybu/2IhpE4YL/NSv4LFX+BHFN60vA7ywbr6zyWh8Hpw1m/dqfE2dB/18ckhnytrt7voP) for further analysis.
