### ISSUE TITLE
Problem with Shape.Rectangle constructor & bounds.size

### ISSUE THREAD

**Issue by beeduul** [paperjs/paper.js#1625]
# Description/Steps to reproduce
When creating a `paper.Shape.Rectangle` object using the object-flavored constructor with `position` and `size` properties, the `paper.Size` returned by `bounds.size` is a degenerate (0) size object.

# Link to reproduction test-case

http://sketch.paperjs.org/#V/0.11.8/S/TY9LDsIwDESvYmUBrRSFz7KIOyC6JCxCazURxa6aoPIRd8cpG7KxZvScGb8VuRuqStVXTI1XWjXcZt1jggfsYaPhKWOrYcpqrcFnud5ZspShEZskDuEEgxtwNLWXYY5iO+p6LN6WQN7AMaTAVP2hBw6UiodElPpHxfDCf6IWXUwSWlr6lHPoagVTaJOHBXgMnU8QaN6DlmmZ4ObkELjwndpoqWGK3KPpuStyVZNJPbc2P2Z28tdy/GVEdx1yq6iq0/nzBQ==

# Expected result

`bounds.size` values match results from `size` property

# Additional information

other variations of the object-flavored constructor do not have this bug, see a comparison at: http://sketch.paperjs.org/#V/0.11.8/S/xVGxbsMgEP2VE+qAFUJSj66SrXsVj7alEIcEKw5YQGK3lv+9h0nVDl06leXdu/e4h7iRaHGVJCP5RfpaEUZqcwz8LixYWXsHGyiql1KXupUeBqTPDN4RUgZ9YGsGKtD1bJrv8O7mFNWyh0500vJcIfAdSkKfW0nHUgOezjTaZ/DtewsNOuD8hEWLaz7kT0eOnPaYmER9Qkz+nusa3xj9D9Ena64ZFAMsoV+l4SOXoFZp9cj0ZhYXX+JiFn/NOxn7KmpFLWy28JheG+1MK3lrznQf3/80Wh6qicHB3PTRxVasp32CS5sSXPvBSnGZF+JIVlTTJw==

reproducable on paper.js version 0.11.8 (latest at time of reporting)

**Comment by sasensi** [comment]
Hi, thanks for the report, but I don't think that currently, `new Shape.Rectangle({position, size})` is an accepted constructor.
Have you found it somewhere in the documentation ?
I would say that required constructor object properties are one of: `rectangle`, or `point & size`, or `from & to`.
You can also set position if you want, but you have to provide one of those.
![screenshot-paperjs org-2018 12 05-09-07-32](https://user-images.githubusercontent.com/11247504/49499342-004df480-f86e-11e8-964b-7313d5753cde.png)

So [this](http://sketch.paperjs.org/#V/0.11.8/S/RY/BCoMwDIZfpfSigoi7VnbaC4x5nDvUmmmxS6TtFCa++1rHtkCSP3w/JFk5ygdwwesRvBp4zhV1cZ6lZW6QE7AjQ1hYHXVxAeUl9gbStbENshATafRi95yjTMuclVn+xU6/4EProNJDGXAof8NETntNKNisYSkUoAf7o3dtzIkMWcESsmE1JBFtWRVbTEXoyEBhqE/3g4uWnti5rArPtBbkuF/ouLjetjc=) would be valid, even if it makes no sense to do it like that:
```javascript
var shape = new Shape.Rectangle({
    point: new Point(0, 0),
    size: new Size(100, 100),
    position: view.center,
    fillColor: 'orange'
});
```

**Comment by beeduul** [comment]
point taken! (har har)

the relationship between a Shape's `point` and `position` feels a little ambiguous to me, but you are correct that `position` doesn't exist as a valid parameter in the other flavors of the constructor.  Because using `position` somewhat worked, I assumed (incorrectly) that it was a valid property.

ok, i'll close out the issue.  thanks for looking at it!
