### ISSUE TITLE
CSS colors no longer work with spaces in parentheses

### ISSUE THREAD

**Issue by briman0094** [paperjs/paper.js#1629]
# Description/Steps to reproduce

After my most recent paper.js upgrade, a lot of the colors in my project have turned to Black. I discovered that this is because my color string constants are in the format `rgba( red, green, blue, alpha )` instead of `rgba(red, green, blue, alpha)` (notice the space after the opening and before the closing parentheses). In the previous version, this worked fine, but now it is parsing to pure black. The CSS standard supports spaces in the parentheses like this, so paper should ideally support them as well.

# Link to reproduction test-case

[Reproduction in paper sketch](http://sketch.paperjs.org/#V/0.11.8/S/lY9BCsIwEEWvMsyqhVCSYEDi0guILpsu0hrb0nQibVaW3t2o6EoEZ/Hhv8V/zIJkR4caT4OLTYcMm3B+9IONXXF0TbTUepcthiDdNfQUNZSCM8Er9oJzf3OJSc7kh1167/fBh0mDwamtbSaVYiA5ZyBUCl5sVW7Q0JrvDBn67dv874MvQngb05/15Ozw3J9Rl9V6Bw==)

All versions prior to 0.11.8 work fine, whereas 0.11.8 parses the second shape as black.

# Expected result

Both squares in the example should have the same color, but in the latest version, the latter shape is black.

**Comment by sapics** [comment]
Thanks @briman0094 for reporting bug and analyzing detail!
I create a PR #1633 to fix this issue.
