### ISSUE TITLE
It draws the canvas very slowly for me! Am I doing something wrong???

### ISSUE THREAD

**Issue by MUM9** [paperjs/paper.js#1640]
I've used paper.js on my website [here](https://umar.spectechle.com/) to draw a canvas on the very first section of my website, so it should be loaded before anything else. But it draws the canvas very very late after the whole page is loaded.
I'm not sure if I'm doing any mistake? 

I've also tried loading the paper-full.min.js with the defer and async in the script tag but none of them helped in drawing it fast.

I'm not sure whether I'm doing any mistake! How can I make it draw the canvas when the page loads?

**Comment by sasensi** [comment]
Hi,

I think that your best option is to use `Paper.js` in `JavaScript` context directly (instead of using `PaperScript`). Here is an [article](http://paperjs.org/tutorials/getting-started/using-javascript-directly/) explainning the difference between both.
Your code won't have to be parsed and it can run earlier.
You can still place the `<script>` tag in the top of your code if you want, but you have to make sure that the canvas was loaded by listening on the `DOMContentLoaded` event.

Here is a [fiddle](https://jsfiddle.net/erghpLyu/) demonstrating the solution.
Here is the code that you are using, translated for JavaScript context:

```javascript
document.addEventListener('DOMContentLoaded', function() {
    paper.setup('quad');

    var width, height, center;
    var points = 15;
    var smooth = true;
    var path = new paper.Path();
    var mousePos = paper.view.center.divide(2);
    var pathHeight = mousePos.y;
    path.fillColor = '#d94f5c';
    initializePath();

    function initializePath() {
        center = paper.view.center;
        width = paper.view.size.width;
        height = paper.view.size.height / 2;
        path.segments = [];
        path.add(paper.view.bounds.bottomLeft);
        for (var i = 1; i < points; i++) {
            var point = new paper.Point((width / points) * i, center.y);
            path.add(point);
        }
        path.add(paper.view.bounds.bottomRight);
    }

    paper.view.onFrame = function(event) {
        pathHeight += (center.y - mousePos.y - pathHeight) / 10;
        for (var i = 1; i < points; i++) {
            var sinSeed = event.count + (i + i % 10) * 100;
            var sinHeight = Math.sin(sinSeed / 200) * pathHeight;
            var yPos = Math.sin(sinSeed / 100) * sinHeight + height;
            path.segments[i].point.y = yPos;
        }
        if (smooth) {
            path.smooth({ type: 'continuous' });
        }
    };

    paper.view.onMouseMove = function(event) {
        mousePos = event.point;
    };

    // Reposition the path whenever the window is resized:
    paper.view.onResize = function(event) {
        initializePath();
    };
});
```

**Comment by MUM9** [comment]
That's perfect!
Thank you @sasensi

**Comment by MUM9** [comment]
Hi @sasensi 

I was struggling with a couple of things.

1- I'm unable to add a gradient BG color (from left to right) to this canvas. Although there is basic instruction on paper js site but I couldn't add a simple one from left to right.

2- As the `<canvas>` tag couldn't contain any HTML elements, so I had to pull up my text `div` (that contains the text "I'm UMAR your next web designer & developer") with a negative margin.
But this has caused an issue of responsiveness. 
On smaller desktop screens there appears a white space below the canvas.

See the attached pic!

![Image of Issue](https://umar.spectechle.com/images/screenshot-umar.spectechle.com-2019.02.24-23-55-18.png)

Can you please help with these 2 issues?
You can find the issues [here](https://umar.spectechle.com/)

Thanks for your time!
