### ISSUE TITLE
Importing paper.js in react-native

### ISSUE THREAD

**Issue by ksesong** [paperjs/paper.js#1641]
I am trying to use `paper.js` exclusively as a path processing tool, especially for the boolean operations (say I have two paths, and I want to get the path data corresponding to the intersection). There is no canvas support in `react-native`, and I am not trying to display anything with `paper.js`, but whenever I import with `import paper from 'paper/dist/paper-core';`, the following error appears:

```
undefined is not an object (evaluating 'self.navigator.userAgent')

PaperScope
    paper-core.js:767:29
<unknown>
    paper-core.js:15227:12
<unknown>
    paper-core.js:15250:7
loadModuleImplementation
    require.js:292:12
...
```

Is there any way to cherry-pick the modules that are related to the paths? (and avoid any incompatibility issues with the canvas requirement)

**Comment by noah-seltzer** [comment]
@ksesong did you ever figure it out?
