### ISSUE TITLE
The canvas appears blurry on Microsoft Edge!

### ISSUE THREAD

**Issue by MUM9** [paperjs/paper.js#1642]
I've used paper.js on my website to draw a canvas that appears perfect on Chrome and Firefox but it appears blurred on the Microsoft Edge!

You can have a look at this [here](http://umar.spectechle.com).

And how can I add a simple gradient BG from left to right on this?

Thanks for any help!

**Comment by sasensi** [comment]
Hi, can you try to isolate your issue, ideally in a [sketch](http://sketch.paperjs.org) ?

About applying a gradient, you can look at the documentation [here](http://paperjs.org/reference/gradient/).

**Comment by MUM9** [comment]
> Hi, can you try to isolate your issue, ideally in a [sketch](http://sketch.paperjs.org) ?
> 
> About applying a gradient, you can look at the documentation [here](http://paperjs.org/reference/gradient/).

Please see the following image! The outer boundary of path appears blurry on Microsoft Edge Browser.

![Image of Issue](https://umar.spectechle.com/images/MS-Edge-issue.jpg)

Almost a month ago I had an issue of speed with the paperscript and you @sasensi gave me the javascript replacement to use which loads quickly but have this blurring issue on Microsoft Edge Browser.

Here is the [paperscript version](https://umar.spectechle.com/paperscript-version.php) which loads too slow but don't have the Blurring issue on MS Edge browser.

Here is the [javascript version](https://umar.spectechle.com/javascript-version.php) which loads fast but it does have the Blurring issue on MS Edge browser.


Here is the [sketch](http://sketch.paperjs.org/#V/0.11.8/S/rVVNj9owEP0rVqoKU2iAVfdQKKdKVQ9FWrFHlkM2HjajBRslTiKK+O8d2wSS4EXsqjnkw37z9eZ5sg9ktIFgHDy+go6ToB/ESpjvJ8lqVxGlrEShkz5LAF8S3WcxSA3p5BK3VSh1xqZsdO/ZzTZK6YR2dZqDzzqyuxJKet1CGj7QAu96kBuVZ/CgTCSHLBDK0KUVCixQAL/zGZoQv20VZFp5CXctpEGFK1yvf6q1SgnZ+SS+f1vdx50WECVqjNb4F06pNgGrXMYalbxAsn0TaC6Xv6+mySXYtqSJzch7aNc9+KSqum1w3BiwO4+VZSKDlw24vi6Wb4EiIXjN9bPKpcjoobXa/IGVbnfDskPkctMWNJKZ0OPHUUL03ut5STLXSWpNtZgVzh0xg6OjLvvCsFJsuPNl0SzBWPlQhw/UPTfM+pw1Vw5t1bTVePKu5K+UziyVXQmLQ0GleZmqab03ZbyigH2tCZ8+zrAusTYa/uc+ZSgfAQQZ2kzDmAiihBhHuiH7TBFNj0ZDX+Cak9OpnVlJouSVZ1Lu0Po4V3LF1c6NDY+XkfNyjtU7HpprmqnOxgKXoaWEOJ3aILdpCFeMu7n4JosujsXwPdO7LYxZJ1ZSo8ypkR12uEGvh8k1id0sv5lRzkwVN0qwNqdd9y1Fk/ekNhiwOWxVhnaM6gTcb6JMQJLL1K6UKIUqGWYsBTPTxPhKCXMLuS1/z3xvZ06/zecUold3HoLxYnn4Bw==)

**Comment by MUM9** [comment]
One more thing, it appears to be sharp and crisp when I resize the window on MS EDGE browser but it again appears to be blurry when I reload the page.

Here is the [fiddle](https://jsfiddle.net/erghpLyu/) that you @sasensi sent me while fixing the loading speed with paperscript and replacing it with javascript, it also appears blurry on load but when the window is resized it appears crisp!

**Comment by sasensi** [comment]
I was able to reduce the bugs to [this](https://jsfiddle.net/nq5y4vau/).
```html
<!DOCTYPE html>
<html>
<head>
    <script src="https://umar.spectechle.com/js/paper-full.min.js"></script>

    <style>
        canvas {
            height : 500px;
            width  : 500px;
        }

        @keyframes link {
            from {
                transform : none;
            }

            to {
                transform : translateY(1%);
            }
        }

        .link {
            animation-name : link;
        }
    </style>
</head>
<body>

<canvas id="canvas" resize></canvas>
<a class="link">link</a>

<script>
    paper.setup('canvas');
    new paper.Path.Circle({
        center: paper.view.center,
        radius: 50,
        fillColor: 'orange'
    });

    window.requestAnimationFrame(function() {
        document.querySelector('.link').style['animationName'] = 'any';
    });
</script>

</body>
</html>
```

This seems to be a super specific, very strange bug due to the union of some circumstances.
I can't really tell what it producing this and I decided to not go further since an easy workaround is available for you by simply removing the `wobble` class on your email link and this seems to have no impact on the display.
This is the line to change.
```html
...
<a class=" black-text wow wobble" href="mailto:m_umarmurtaza@outlook.com?Subject=Hello%20again" target="_top">m_umarmurtaza@outlook.com</a>
...
```
See this [fiddle](https://jsfiddle.net/3mo4wdxp/) for a working demo.

**Comment by MUM9** [comment]
This is a strange solution but it's working!

Thanks for the help @sasensi
