### ISSUE TITLE
List available blendModes?

### ISSUE THREAD

**Issue by SkepticaLee** [paperjs/paper.js#1653]
Is there a way of listing the available blendModes via a script command?

**Comment by eeropic** [comment]
Not that I know of.. ['normal', 'multiply', 'screen', 'overlay', 'soft-light', 'hard- light', 'color-dodge', 'color-burn', 'darken', 'lighten', 'difference', 'exclusion', 'hue', 'saturation', 'luminosity', 'color', 'add', 'subtract', 'average', 'pin-light', 'negation', 'source-over', 'source-in', 'source-out', 'source-atop', 'destination-over', 'destination-in', 'destination-out', 'destination-atop', 'lighter', 'darker', 'copy', 'xor']

from http://paperjs.org/reference/item/#blendmode

**Comment by SkepticaLee** [comment]
Since I occasionally experiment with the blend modes, and one or two of them have not been implemented in the past, I was thinking more along the lines of a dynamic query. Surely the blend modes are methods of some object? But which one?

**Comment by eeropic** [comment]
Yeah, they are there but I don't think they are exposed at the moment 
https://github.com/paperjs/paper.js/blob/cc135eaba80943f78075f84ca430dc3152bd154e/src/canvas/BlendMode.js

BlendMode.modes and BlendMode.nativeModes

**Comment by sasensi** [comment]
I close this issue since it has been answered and there is nothing to fix.

**Comment by SkepticaLee** [comment]
It could be done by adding the following line after the definition of the modes (for 12.11 this would be at line 14524, otherwise look for "modes =" and find the closing bracket):

available_blendmodes = Object.keys (modes);

I would like to put in a pull request for this, but the whole procedure just fries my brains.
