### ISSUE TITLE
Tween not working with opacity only

### ISSUE THREAD

**Issue by octfx** [paperjs/paper.js#1654]
Tweening seems to be broken when trying to only tween the opacity of an item.  
I've created a JS Bin example which reproduces the problem:  
https://jsbin.com/nabodakoke/2/edit?html,js,output

**Comment by arnoson** [comment]
Your first path doesn't have any fillColor and therefore is invisible.
This works:
```
window.onload = function () {
      let canvas = document.getElementById('myCanvas');
      paper.setup(canvas);
      let path = new paper.Path.Circle({
          radius: 40,
          center: new paper.Point(50, 50),
          fillColor: 'red'
      });

      path.tween(
          {opacity: 0},
          {opacity: 1},
          3000
      );
  };
```

**Comment by octfx** [comment]
Oh, I see.  
So this also means that I can't tween the opacity of a group without a fillColor?

**Comment by arnoson** [comment]
You can tween a group's opacity:
```javascript
window.onload = function () {
  let canvas = document.getElementById('myCanvas');
  paper.setup(canvas);

  const circle = new paper.Path.Circle({
    fillColor: 'red',
    radius: 50,
    position: paper.view.center
  })

  const group = new paper.Group(circle)

  group.tween(
    { opacity: 0},
    { opacity: 1},
    1000
  )
};
```
The opacity tween of your first path did work. But because your first path doesn't have a fillColor or a strokeColor or anything visible you can't see it even if you set it's opacity to 1.
