### ISSUE TITLE
[typescript] event.modifiers has object type

### ISSUE THREAD

**Issue by dobesv** [paperjs/paper.js#1667]
# Description/Steps to reproduce

Try to inspect `ToolEvent.modifiers` within typescript code.

# Link to reproduction test-case

https://github.com/dobesv/paperjs-ts-repro/blob/master/toolevent-modifiers.ts

# Expected result

You should be able to check which modifiers were pressed at the time of a `ToolEvent` when writing TypeScript code, without casting to `any` or getting type errors.

# Additional information

Currently `ToolEvent.modifiers` is declared as the type `object`, which in typescript has no properties accessible.  It can only be used by casting to some other type, such as `any` or some custom interface created to workaround this issue.

The definitions in `@types/paper` have an interface in place for this purpose, perhaps you can follow that example.

Or, at the very least, declare it as `any` rather than object.  At least there won't be type errors (but there might be more runtime errors).

**Comment by lehni** [comment]
@dobesv before flooding the issues with typescript typings, maybe it's better to collect these information in one place? I'm not using typescript personally, so will not work on fixing these things. Maybe you'd be interested in helping out?

**Comment by dobesv** [comment]
I can try to fix them if you point me to some explanation of how the typings are generated.  I thought I would be able to fix them but they are generated in a somewhat complex way from the documentation, I wasn't sure how to implement more complicated types in those comments.

**Comment by lehni** [comment]
Perhaps @sasensi could help to get you up to speed with that? I didn't write the typescript generator, so I can't really be of much help without digging into it fully myself first.

**Comment by sasensi** [comment]
@dobesv, thank you for the feedback.
@lehni, I can handle those issues myself as I think I am the best placed to do it quickly but I was waiting that we decide how deep we want to go with typescript as asked in #1659.
The way to fix the issues will depend on the choice we make.

**Comment by lehni** [comment]
@sasensi I've answered #1659 now. Curious to hear your thoughts!

**Comment by sasensi** [comment]
@lehni, I answered back.
About getting all typescript definition related issues together rather than flooding new issues, what would you recommend ?

**Comment by dobesv** [comment]
I only created a few issues, I'm not sure it's a "flood".  However, all the issues I reported are using the same reproduction repo so they could be aggregated into one issue if that's helpful.  Personally I'd keep them separate so anyone having the same issue can find it but if they have a new issue they can file it with a new reproduction of their own.

**Comment by lehni** [comment]
@dobesv the current amount is totally fine. But I can imagine there will be many more. It just brought back memories of dozens of separate issues relating to boolean operations and curve intersection a few years back, and I'd like to avoid such a scenario again :) So maybe trying to keep things that are similar under abstracted umbrela topics would be good, when possible?

**Comment by dobesv** [comment]
Sure.  Actually these are the only issues I have for now, although as mentioned in that larger issue, there are probably many other issues that people *could* be having.

**Comment by jmariller** [comment]
Hi! I am facing exactly the same TypeScript issues as @dobesv with the latest version released. Some other things I have noticed in case it helps:
- Method `scrollBy()` of View object is not available anymore
- When cloning a raster with `.clone()` and assigning to a Raster variable, an assertion must be used (e.g. `let myRaster: paper.Raster = <paper.Raster>anotherRaster`)

I tend to agree with what @dobesv wrote [here](https://github.com/paperjs/paper.js/issues/1659#issuecomment-501906450). If you need any help with this please let me know, as mentioned once to @lehni in PM I am happy to contribute to support the library.
