### ISSUE TITLE
exported SVG symbol has wrong viewport size

### ISSUE THREAD

**Issue by sasensi** [paperjs/paper.js#1668]
# Description/Steps to reproduce
Originally reported [here](https://groups.google.com/forum/#!topic/paperjs/imn2C3AzT0w).

# Link to reproduction test-case
Reproduced in this [sketch](http://sketch.paperjs.org/#V/0.12.1/S/ZZBBa4QwEIX/yuBlXRDJFnpx6aHsodeC0B5cDzEOmjUmMhm3LbL/vaba7rYNJGHevPnyyBRZ2WOURXmHrNooiZSrQ32WBJqxhwew+AbPktv0oEkZjKcjHS3MS6FlpAwKkYAok2+ZZK1Hn8G9+JE8k+vw4Iyb7ZvKjLj503vVNbcZ7ESQL9t9uMI2yOA/+sqZNUn+VcQh2+JauulgpMK42Ik5zHyUV4Q/N48+Z9K2mRkDuRMqTvF9cMT5y1M8gVzbGTCNCOvzylnvDKbGNfEN43c2Qt0HENY37EUK7H9zV3/KJK03kjG+C6HFdj9/f0Uou8Fpyz7KivLyCQ==).

```javascript
var item = new Path.Circle({
    center: [0, 0],
    radius: 50,
    strokeColor: 'blue',
    strokeWidth: 10
});

let symbol = new Symbol(item);
symbol.place([100, 100]);

svgAsString = project.exportSVG({ asString: true });
console.log(svgAsString);

let reimported = project.importSVG(svgAsString);
reimported.translate(200, 0);
```

![screenshot-sketch paperjs org-2019 06 14-10-44-50](https://user-images.githubusercontent.com/11247504/59496392-9dc75800-8e91-11e9-87f0-49dc8288d5a1.png)

# Expected result
![screenshot-sketch paperjs org-2019 06 14-10-45-49](https://user-images.githubusercontent.com/11247504/59496397-a15adf00-8e91-11e9-84af-278292b608f0.png)

# Additional information
The problem seems to reside in the `<symbol>` `viewport` attribute which seems to use the bounds instead of the stroke bounds.

```html
<svg version="1.1" xmlns="http://www.w3.org/2000/svg"
     xmlns:xlink="http://www.w3.org/1999/xlink" width="867" height="937"
     viewBox="0,0,867,937">
    <defs>
        <symbol viewBox="-50,-50,100,100" id="symbol-1">
            <path
                d="M-50,0c0,-27.61424 22.38576,-50 50,-50c27.61424,0 50,22.38576 50,50c0,27.61424 -22.38576,50 -50,50c-27.61424,0 -50,-22.38576 -50,-50z"
                fill="none" fill-rule="nonzero" stroke="#0000ff"
                stroke-width="10" stroke-linecap="butt" stroke-linejoin="miter"
                stroke-miterlimit="10" stroke-dasharray="" stroke-dashoffset="0"
                font-family="none" font-weight="none" font-size="none"
                text-anchor="none" style="mix-blend-mode: normal"/>
        </symbol>
    </defs>
    <g fill="none" fill-rule="nonzero" stroke="none" stroke-width="1"
       stroke-linecap="butt" stroke-linejoin="miter" stroke-miterlimit="10"
       stroke-dasharray="" stroke-dashoffset="0" font-family="none"
       font-weight="none" font-size="none" text-anchor="none"
       style="mix-blend-mode: normal">
        <use x="50" y="50" xlink:href="#symbol-1" width="100" height="100"
             overflow="visible"/>
    </g>
</svg>
```

**Comment by macduy** [comment]
Fantastic, thank you for fixing this. I can go back to using symbols again
