### ISSUE TITLE
Group with applyMatrix = false does not used transformed coordinates to apply gradient origin/stop

### ISSUE THREAD

**Issue by nikkwong** [paperjs/paper.js#1671]
http://sketch.paperjs.org/#V/0.12.1/S/XVGxbsIwEP0Vy0tASp20FR1SYGiHLmUpUheCVCcxiYvjs+wjASH+vXZQitqTzj4/v/d8J5+p5q2gGV3vBZYNjWkJVTjnNtcdt6TjiizI19x1NTm2SrtFThtEkyVJ3/esf2Rg6+QhTdPEU3K6DELiY244NqTy9FUaz1I+CytJyX3sM03jv8jdAOU0GfTz4LX8CmXIErRDUls4GN+L4UZYZix8ixKZbA1YXH++TXyn08AeeIwbo04rjlYevWbHlRO3y53EFzjoyk2uZp0UPSsGhLmSKzFhT9Pp8/j+KFLqFRRY73cep6wtr6TQmN2gEA7BuIxsopNQCvooJpEVVdgKdRDRduRe4rECK2ups+uUYy/e5V3s8JdUCYdSc5Twn1kAIrQfsm4wkC/+Iwsr+N6A1OhottlefgA=

I would expect gradients applied to groups with `applyMatrix = false` to be able to use the matrix transformation on the group when calculating where to position `origin` and `destination` values for gradient stops. However, I am guessing what is happening is that it is not taking into consideration the matrix transformations, so the gradient's position is being applied to the pre-matrix transformation. 

```
var val = `<svg xmlns="http://www.w3.org/2000/svg">
    <path d="M0,50a50,50 0 1,0 100,0a50,50 0 1,0 -100,0"/>
</svg>`

const group = paper.project.importSVG(val)
group.applyMatrix = false
group.fitBounds(paper.view.bounds.scale(.6));

group.fillColor = {
    gradient: {
        stops: ['yellow', 'red', 'blue']
    },
    origin: group.bounds.topLeft,
    destination: group.bounds.bottomRight
}
```

This also introduces the complexity of `group.fillColor.destination` & `group.fillColor.origin` reporting the pre-matrix `point` unlike other group `point` based properties which correctly apply the group's matrix before returning the `point`. 

A temporary workaround would be to just reset the matrix and then apply, but I don't know how resilient this would be, and creates quite a bit of headaches for my app. Does anyone have a better solution? 

```
var val = `<svg xmlns="http://www.w3.org/2000/svg">
    <path d="M0,50a50,50 0 1,0 100,0a50,50 0 1,0 -100,0"/>
</svg>`

const group = paper.project.importSVG(val)
group.applyMatrix = false
group.fitBounds(paper.view.bounds.scale(.6));

var clone = group.clone();
clone.matrix.reset()

group.fillColor = {
    gradient: {
        stops: ['yellow', 'red', 'blue']
    },
    origin: clone.bounds.topLeft,
    destination: clone.bounds.bottomRight
}
```

**Comment by sasensi** [comment]
I think that gradient `origin` and `destination` are in fact using group matrix when it is not applied as you expect them to but I think that you are mistaken by the fact that `group.bounds.topLeft` and `group.bounds.bottomRight` are expressed in group parent coordinate system.  
I was also surprised by this behavior in the past but I guess that there is a good reason why it is like this.  
So you are not passing the good value for the effect that you want.

Here is a [sketch](http://sketch.paperjs.org/#V/0.12.1/S/rVRNa9tAEP0rgy62QSiOjS8qPvnQSwKl7c0xZC2trCWrHbE7smKM/3tn9eFIiUlLicFCO1/vzdsZnQMjChnEwa8XSUkehEGCqT/f3cHGSkESBBwsViUkaEgoo8yBTYmyiZZP9skchW0D7mENRtbw3R+m/u2HoDzaNJHT7Woewmq+84/Z7JvP9P8hTKLRSMAMKFeuA60V5VgRFIKsegVRllrJdIS7YNyWQNRUmLbVW1/kM06PbfYaMqGdvAnOmDYdgPaIBqlHhQwtCANCk7RGkDpKcKgrUmhGjJY9o8WIUQf5iJzXuN2V531EVhinmcuU9Rk28OZYzBsJB97lwLtcDbw91Eg1SISTMdSSr4lPhFBaPKqUNbfqoLgxk0IqHSnfHBpgUymsNNSVSxBt6p3c98mRLKJBA5nSeoOaJVrD2duBfwcrUsUFYjiDIyxdDNvJSWqN9SSEiZXpZAeXsA9vecT9de6xMqmLOO9BZnSNGlB8H7pHIix+qkPecL7cEGN4of8hiMZE6L/rsfhSPbZ8tbw6NwXYdnidArVKKQ9hbMylV2T375IINuXSQi1OfiFT9Fvv1zLkpyCOMrCXULl2K7pyBVrJohSllq9NIQ7nTWZdr2MKLSNWkq2Nlh9VbPavK/msvKztFP7GB58wnT1DVpnEtx8NVuHLB3D5Drczjqdy9slYfl5gMKuzt5vhL/Cev0kvJUtOLoi3u8sf) demonstrating the behavior for both matrix application cases.

```javascript
// Create a group containing a circle
var group1 = new Group(new Path.Circle([50, 50], 50));

// Create a clone of this group without matrix applied
var group2 = group1.clone();
group2.applyMatrix = false;

// Create a third group with matrix not applied for an alternative solution
var group3 = group2.clone();

// Move groups
group1.translate(50);
group2.translate(200, 50);
group3.translate(350, 50);

// Matrix applied case: we need to provide origin and destination in parent
// coordinate system.
group1.fillColor = {
    gradient: { stops: ['yellow', 'red'] },
    origin: group1.bounds.topLeft,
    destination: group1.bounds.bottomRight
};

// Matrix not applied case: we need to provide origin and destination in local
// coordinate system.
group2.fillColor = {
    gradient: { stops: ['yellow', 'red'] },
    origin: [0, 0],
    destination: [group2.bounds.width, group2.bounds.height]
};

// Matrix not applied case: another way of doing this, that can be used for
// more complex cases, is to translate bounds into local coordinate system with
// `item.parentToLocal()` function.
group3.fillColor = {
    gradient: { stops: ['yellow', 'red'] },
    origin: group3.parentToLocal(group3.bounds.topLeft),
    destination: group3.parentToLocal(group3.bounds.bottomRight)
};
```

**Comment by nikkwong** [comment]
Okay very helpful, thank you!
