### ISSUE TITLE
Color is no longer updated properly

### ISSUE THREAD

**Issue by sasensi** [paperjs/paper.js#1672]
# Link to reproduction test-case
Originally reported [here](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/paperjs/YPQNVofgiUY/hKdLGO2KBwAJ).
The bug can be reduced to [this](http://sketch.paperjs.org/#V/0.12.1/S/VVDJbsIwEP2VkS9JRBqZU6tUnPiBSuUGHIw9aVycMfICSCj/XjsREbVkeda3+MFIDMha9n3GIHtWM2lVzq/CwUWEHjZAeIOvFDZb7aTB8nFwB4J0JFJA18JV462Zk/rZc0Lp6Ft450up08ZsrbFpo3Coilwfq8/85Osx7PSANoayiySDtlRWC1fW0iwITR8RVhtYcz7tj3UOefXEmiRbTWGH9/Ai2CaNFBL/bAV8b6NRcEJpB4Qfh0gguuQDLKVuKpMqFgOXjPjPLqxgz2t4++DHZeo3+qA7LUV2kKjmyVe36ZdPDsV5wvOs3R/HPw==)

```javascript
var path = new Path.Circle({
    center: view.center,
    radius: 70,
    fillColor: 'red'
});

setTimeout(function(){
    path.fillColor.hue += 100;
}, 1000)

new PointText({
    content: 'Circle should become green after one second',
    point: view.center + [0, -80],
    justification: 'center'
});
```

# Additional information
By switching `Paper.js` version in sketch, we can see that this bug was introduced after `v12.1` because it only shows up with `prebuilt` version.
After investigating, I can tell that this was introduced in https://github.com/paperjs/paper.js/commit/aca305981466aba72d4e0bee307d20e2a3f3a84d.
@lehni, can you have a look at this since you better understand the changes involved in this commit than I do ?

**Comment by lehni** [comment]
@sasensi oops, that's not good! Pity that we don't have a test for this yet, I assumed we do... I am in jury at HEAD in Geneva today and tomorrow, but will be able to check on Friday hopefully.

**Comment by lehni** [comment]
@sasensi I've fixed this now, but maybe you have an idea for how to write a unit test for this?
