### ISSUE TITLE
[ts] No paper.Point.importJSON, exportJSON, etc

### ISSUE THREAD

**Issue by anion155** [paperjs/paper.js#1676]
I've made Base class in [@types/paper](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/2ceda6e7ea15eeaa8239832ecdbbb42ff87fbcf8/types/paper/index.d.ts#L21), which did define all those methods (like the actual code does), and all classes inherit Base class.

**Comment by sasensi** [comment]
Yes, good point and this apply to many cases as all classes inherit from `Base`, but further than a technical `TypeScript` definition question, for me, the question is more: is the user supposed to use these methods that are not documented ?
- if yes, they should also be documented  in the online documentation
- if no, I think that `TypeScript` definition shouldn't have those neither

@lehni ?

**Comment by northamerican** [comment]
I have an array of exported stringified item data. The most convenient way I'm able to convert them back to Items is:

`myArray.map(paper.Path.importJSON)` 

This works as expected but it seems paperjs doesn't have the TypeScript definitions for it. It appears to expect importJSON when used on an instance only.
