### ISSUE TITLE
Using replaceWith on item's own descendants causes incorrect segment coordinate calculations

### ISSUE THREAD

**Issue by nikkwong** [paperjs/paper.js#1681]
http://sketch.paperjs.org/#V/0.12.3/S/NU+xbsMgEP0VxBJHsoCm6mI5XjtlipQOIQPFJ+MGA4JTiRrl3wuxMtzT3Xvv7vTu1KkFaEePV0BtaEu1H+usvUtI0u9E9iSoAJGF6H9AI5uX4CMeT5/Npq/6bbEu7SU1iKHjPOfM8jvzceI7IQQvFkmHPig0ZCy2w4doBXkToi1FVvyTlA99tQ6brXQWkDjI6/OCTJvZjhHcWVykq0SEYJWGrxlNszrL2tqwpJWFZleImsFbYNZPzUuEaQGHqVxiwc8O2W1bQn9HUNfnnGh3vjz+AQ==

**Comment by nikkwong** [comment]
Actually looks like this is happening in general cases too, here a path is showing incorrect segment points when just scaling a child: 

http://sketch.paperjs.org/#V/0.12.3/S/LY/BbsMgDIZfBXFpKiHwVu0Spbnu1FOlXUoPjFhJVgIIrCZb1XcfyXaw5d/+ftl+cG8m5DU/35DswAW3oVu1DT4Ty/eeHVk0EZOMKXyhJTlOMSQ6f7xXu2adL5Pz+aj5QBRrpeZ5lvNBhtSrVwBQBdG8baKhgXUFO72BAPYCIEqwv/yjuWqbFW13e+0dErPD6Lqyu/TkVif0F7hqvwmZrXFYHQR7LDWI7xqexbfeHBxKF/rqH8N+Qk+5OGUMoye57MuPnwnNbdOZ15fr8xc=

**Comment by sasensi** [comment]
Hi, you are actually expecting the wrong value to output.
The fact is that items imported via SVG are imported with matrix not applied:
https://github.com/paperjs/paper.js/blob/cc15696750035ab00e00c64c7c95daa2c85efe01/src/svg/SvgImport.js#L608
so what you are seeing is the local coordinates without scaling being applied.

If you want to access global coordinates, you can either:
- set item `applyMatrix` property to `true` before scaling (see this [sketch](http://sketch.paperjs.org/#V/0.12.3/S/TZDBboMwDIZfxcqlTEJJtmoXRrnu1FOlXUoPWbCANiRR4ha6qu++ADvsYMv2/8m/7AezakBWsMMFSXcsZ9o1c6+djQTx1sIOfHBn1MT7wbtAh6/PbFPOyjQYG3c164h8IcQ4jnzcchda8SalFAmpWVV6RR00Cdu/y1zCq5R5CljzT81EVc5otXn5qENtDRLorjdNMk5jvtQB7VGeFn3pufLe3PeKQj8ljsIV/4lRK4PZNocHTEUygnvK8Fz3z4c5g9y4NvvDsR3QUkwO3LveEp9WNH3jO6C6LMPIiuPp+Qs=))
- convert coordinates using [item.localToGlobal(point)](http://paperjs.org/reference/item/#localtoglobal-point) (see this [sketch](http://sketch.paperjs.org/#V/0.12.3/S/LZDBboMwDIZfxcqlVEJJ1moXRrn2tFOnXkoPabCANsRREg22qu++ADvYsn9/+WP5yawakBXs9MCoO5YzTc3ca7IhQvhu4QDO0x115P3gyMfT+ZhtynkyDcaGQ826GF0hxDiOfNxz8q3YSSlFQmpWlU7FDpqEfb7LXMKblHkKWPNvzURVzmi12X7UvrYGI+iuN036OMl8qT3ai7wu86XnQSuD2T6HJ0xF8oKflOG1Wsy7k0FuqM1W3FDiv+ho6KbMvxawHdDGkIy5o97GLZ/W9+kKN4/qsaiBFZfr6w8=))

**Comment by nikkwong** [comment]
Ah totally. Thanks :)
