### ISSUE TITLE
how to create pattern for fillPattern in Paper.js

### ISSUE THREAD

**Issue by hichem147** [paperjs/paper.js#1696]
# Description
In canvas, which is the main used element in PaperJS, there is already the possibility to use Pattern to fill Rectangles.

In the app, I am developing I need, the use of the pattern as fillPattern or strokeStyle. I saw that with PaperJS I cannot use the patterns.
Could you please, consider the possibility to use it, even, with the remark, that there are problems, with SVG (export, import). 

At least, could you just give orientations, how to fork paper.js to add this feature.
I request here this feature, because, I found that paper.js is very intuitive and excellent graphics js library.

**Comment by sasensi** [comment]
Hi, this topic has already been discussed in different places:
- https://github.com/paperjs/paper.js/issues/829
- https://github.com/paperjs/paper.js/issues/628
- https://github.com/paperjs/paper.js/pull/307

Have a look at them and see if you can add your voice there or help to implement the feature.
