### ISSUE TITLE
Issue template: objection.js?

### ISSUE THREAD

**Issue by guettli** [paperjs/paper.js#1698]
If I open a new issue, I see this text:

```
This issues database is used to keep track of bugs and new features.
For questions and support, please visit the Gitter channel instead:
  https://gitter.im/Vincit/objection.js
 ...

```

If I follow this link I see: 

 > Vincit/objection.js An SQL-friendly ORM for Node.js

I guess the template for new issues contains a copy+paste error.

**Comment by sasensi** [comment]
Indeed, thanks for the report.
