### ISSUE TITLE
Rasterizing group returns empty raster

### ISSUE THREAD

**Issue by jrichterpowell** [paperjs/paper.js#1700]
# Description/Steps to reproduce
Unknown. The following sketch works as expected: [link](http://sketch.paperjs.org/#V/0.12.3/S/TVBBbsMgEPwK4hKsWNSuWlWK05MPvUbKMc6BGCKjYLAW7KiN8veyOHHLBZiZndndG7WiV3RD9xcV2o7mtHUS/5NWV94qGxSQT3Io8uJYNbaxkwCywFZdyc5pG1hWzZQPAr7AjcODTe/ENvbsgKFGR66oiN6SssB7vc5ukQ/P+p3zUZF8OQgrXc8y7sdTANEGVvD3jPejCXow3wyE1KN/ec24kJLNjaW0xe3ZpggdrzW0RrFHSB7zUUviQYiftTG1Mw5rVqDkKhktI2FE3WkjkwFW3uehQfgYu48gNv6nn3H9o9IC/uGqdxOCcd0nUOIy4Kyebg60fItY+UGP918=)

Yet performing the following inside my project returns an empty raster (from the univserse.js file in the repo):
``` 
                //translate from polar
		var center = new Point(radius*Math.cos(angle*Math.PI/180), radius*Math.sin(angle*Math.PI/180));
		var starGroup = new Group();

		for(var i = 0; i< this.starsPerChunk; i++){
			//randomized position
			var starPos = Point.random().subtract(0.5).multiply(radius/2).add(center);
			var star = new Path.Circle({position:starPos, radius:100, fillColor:'white'});
			starGroup.addChild(star);
		}
		var raster = starGroup.rasterize(300, true);
		raster.selected = true;
		starGroup.remove();
		this.starClusters.push(raster);
```

Any idea as to what the difference could be?

# Link to reproduction test-case
https://github.com/jrichterpowell/aphelion

# Expected result
The raster should 'contain' the items in the group. But the raster is empty.

# Additional information

MacOS 10.14.5,  Chrome 75.0.3770.142, no db

**Comment by lehni** [comment]
@jrichterpowell your test-case looks quite complex. Could you simplify this to a simple sketch on http://sketch.paperjs.org/ ?

Thanks!

**Comment by lehni** [comment]
Closing in lack of feedback.
