### ISSUE TITLE
Update PaperScript based on API GET request

### ISSUE THREAD

**Issue by warrenalphonso** [paperjs/paper.js#1702]
I want PaperJS to rerender every second and to do so by sending a GET request and rendering based on the response data. Is there any way I can implement this?

**Comment by sapics** [comment]
Yes it is.

**Comment by sapics** [comment]
Yes it is. This is simple example to animate in PaperScript.
http://sketch.paperjs.org/#V/0.12.3/S/TZBPa4QwEMW/yhAoKhXXPfRi6amU0ltpe1NhYxxNMDuxMe52Eb97o/bPzmVm4PfeY2ZixI/IMvbeoROSxUyYetlP3EIPD0B4hlfuZPKGwnFqNYbTWdVOZrBP0xgkqla6dZmjghZZo7R+NNrYwevzoNJcdEEMgcV6aZUecemtRaSg3DSKavzyeFrQgO6FHNoT12EzknDKUBhNBYGvPvlz9/R/Ur4alPcb9esWbsMt7CO4uaITjdQ6+UPvdnAxIwhO0KKDwyo6eJPG2CNf4qG6wPPTB1j8HHFwBc0x3KWpv9c/rLLIu94ocgPL8nL+Bg==

**Comment by warrenalphonso** [comment]
Thanks! Works great.

**Comment by warrenalphonso** [comment]
I'm now trying to access a socketIO client from a PaperScript file and want to rerender on some event. Is there a similar way to implement this?

**Comment by warrenalphonso** [comment]
Sorry, I just realized I was using an arrow function in paperscript.

**Comment by lehni** [comment]
@warrenalphonso if you include a more recent acorn.js along with paper.js, that should work!
