### ISSUE TITLE
typings file missing View.scrollBy

### ISSUE THREAD

**Issue by aaronhudon-ts** [paperjs/paper.js#1710]
v0.12.3 of the typings file.

I have noticed that `View` is missing the `scrollBy` method.

**Comment by sasensi** [comment]
Hi, this method is deprecated and is, for that reason, neither present in the [documentation](http://paperjs.org/reference/view/).
So I don't think that it should be added to the TypeScript definition.
@lehni, what do you think ?

**Comment by lehni** [comment]
Yes, I agree. Use `translate(delta)` instead (opposite direction)
