### ISSUE TITLE
Nested group matrix should not be reset.

### ISSUE THREAD

**Issue by sasensi** [paperjs/paper.js#1711]
# Description/Steps to reproduce

Originally reported [here](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/paperjs/oPnqgXIJBCU/f_8Vhd0nAgAJ).
When two groups are nested and the parent has matrix applied and the child has matrix not applied.
If we first do a transformation on the child, its matrix is updated as expected.
But if we then do a transformation on the parent, the child matrix is unexpectedly reset.

# Link to reproduction test-case

Here is a [sketch](http://sketch.paperjs.org/#V/0.11.4/S/jZExb8IwEIX/yslTkCpD1lSdOnSqGNoNGK7OJVgY2/LZEIT47zhJI9rSSh0s2ad3777nOwuLexKVeNtRVFvxIJSr+/d8Ds+BMBJY4kg1tMElz3Id1vaAAdRWm/qlr8FTlhxhuBdnQO/N6RVj0F0FDRomuMwepzaPgWy871vd/Dajuj8Z4j2g5caF/ThxmH/TSlZoqCgX33rG6aAZkq9zBAZkoM6TykHkp2iZok+RKygXg6ez7AxJ49rih7+2rez+gBrzDJ5fok1YsvyN65hpkp14zAkCMcV7Lii0zV+PNbgmU87+j5nX+JGXt/NO28iiWm0uVw==) reproducing the issue.

```javascript
// Create nested groups.
var childGroup = new Group({ applyMatrix: false });
var parentGroup = new Group([childGroup]);

// Transform child.
childGroup.scale(10);

// Matrix is updates as expected.
// Outputs: 10
console.log(childGroup.scaling.x);

// Transform parent.
parentGroup.scale(1.1);

// Matrix was unexpectedly reset.
// Outputs: 1 (instead of 10)
console.log(childGroup.scaling.x);

```

# Expected result

Child matrix should not be reset.

**Comment by lehni** [comment]
@sasensi merging this has actually broke the `examples/Paperjs.org/PathIntersections.html` example, see attached screenshot.

Could you look into what's going wrong here?

![image](https://user-images.githubusercontent.com/213275/70820434-f80d8b00-1dd8-11ea-90cb-31d5d28bbced.png)

**Comment by lehni** [comment]
This is blocking the release of a new version… We should also implement a unit test for whatever has broken here.

**Comment by Filprots** [comment]
Hello. I've made a sketch representing the broken example.
I've uncovered this bug, so i'll be happy if it'll help you to solve it.

[SKETCH](http://sketch.paperjs.org/#V/prebuilt/S/fVfLctvGEv2VKWYhqQIM5/2g7CyuF0mq4sqtOOWN5QUFggQkGGAAkLSc8r/f0wOSeti+sktEY3pOd59+sPXvrF1+KmeL2bv7ciyqWTYruhXJ8zn7/dO268dyxd69/5X92ne77cCq5b5kY1XWPVtut83D2+XY15/Zullu2LjrW2h36zW7fbhpgbAq18tdM3L2d1UPDP/78p9d3UNp3fUJtk426ha3O3bo+ntWdH1fFmPzgFsATDj1yLqWtd0hYwPUSrbq2ovx6EwHM8uGHeqxYm05kMNF1/Wrul2OJRu2y6Ic+E27X/Zs2G827DW7eIUH9vlT0w6vb2bVOG4X8/nhcOAHzbt+M1dCiDlUbmaT0uJzU7f331WVMcZ5OoYyaNlUI/ScEBAP9WqszlK9wuMEOowPTQlpVQ/bZvmwaLu2vJn98mozKT2UA0nbJQIi+a1Rnksrs2C5D7KCpLVsch24EyHzig73RnMVdJUrw6WS+3ySoRV5NPmkVKnAjQqN0jw6k1nBlfd/PIf/QrbnZPypC9ZqbpzPpHBcKVnlTnIRzB7WrFSVdVx4vVeCCxOq/CRG7uCvgzVh6dBb/ZtxgQf5/hhLMNxZ//4I+wPbUXEtYNtZboMugGNcZuG7yRRXUmcRv21muI4uk5IH5QrYjAGvPAKTggcDokCMy+CGxbskFBauyEyQhlUxF9xBQ4JBq3LghMLx4H2uuCEVLV2OF+4sSA2TqhC5JhzccIE0vJO55cLqHKGaWOBYewkUoR1eeanpgva5BE/KQ9cI0+QSZmKAmjeyIAn5I0manLhTBOocBAvj5oTtufcRJ1rBH3jgArnlKIBJQopiICfJae0zmBY2l4FHZYktIxOkd7bw3CEMhKhjBgUfIl1SNmZac0sOJ6mAb1oq8KYUAneAVMpkWlItIBnOywK1GXXmuDGAwrlVmQTblEZ455GHgBpxqFfNJdwD96hM2I6G2LFakv9EfiRbOZIShCQqg4X3PEIBNowFQyF6Op84hlAARruYCYIwFlHCvs5hX1m4iZpIOQEe6scKB/Y8npEMYY7PCNREU4iMuokAgteoGSUsCs8pSSWHLCFj6EDJtaXyQoyKR0uBau2o+LxvFFEWJgGsBB+hJEIkLas1DkIAN+hSZ7OAICIVXZCwY3RyRKvEYAhHAYxZj4SmqjU+N0QkIWjKK8pGZ8pRdxRgCJWMwIggykuKC/xpk5pgkgpiRkYPvtIkADVGIwlIl51SHgNBeeFT+VsqMIEaR/lqoU4SEqql/O3YrU9beb45z7a2ezHahECjwmHjuHShQiGq4BsD2yA5UBb2efqoUGvGu72URIydBp20TY6bQMgDakK4/fSB06T9/oj7/cHihEUdoXwtMmh0ipGscupCvNLEu0FVaU8z5SgVFDcaleiKXApKgImTjsnPOmg+Yh1jkgYFisOoXFFm/Uky1G4WjQlb0mAco6Et4QgMs6c6pqCh4eFepOqRU6+Toeyp1SL55agtyS8aiCbK7KnzBbllUuIdmTAu1QqAjsJk741TNNlCpkGysT5z5A6KTBuqwJC9YO4Lw5DGkE2DIjUWJiuNEk/fByDUyEBRC6+Oghb0DUFDCR1jaMJiNFDSog35o4pGUghJE5JPccpoqSYJHer+JAyELz1cRhsaOgpTuVOrEEakmQ9vgI5Jlk3eHIXkTeoolHKaCgHfMOBAKOrJs4qmsNC6U1g0/THvJhvZM4vvLL7fUHuJMIzp7AU9L7uDto1fLq5vWvpHmwpWodWAVWXbd3fYhvi0J2FjuqQd5gqaSYPv66G+bUpojv2uvGZYlmhrSksY1jRWrte4DpE9XTbO19d107zpGixjr1m7a5rzwTD23X15Orq4bZbFPflHvmE/SdsgDibloqqbVV+2HCfXpwja7gdKbXedlrq/yqH+kpbJY7TY5NbY9IZ2t2keWN0O9Wo63tflYfHo8vifbteuhkt6zW/T8yMhQ7FsykuQfZU8OfnKt91QjzW2yNcJjhdlO5Y9dI5+PlX4kEchMka/PyaU9a4t0lnXvu12Q/m225eX5R4QV+zfm5bh5zswSQEv6na8npRo670kcmoci2t8vDqz+UhQU7abscLpzz+f4Z/dvptu3+H2yew3l+9eXKafoeoOv1PYQ5nCGS5fXv9w9zH71qMP9cerR6Sv0yM+vj7j5lt0qm+ZMfpQZ2dS+E/VqMpJkW/K8dv76ur/cPcM54e8teWB/RdQ/E3dFyiOF6xMlbB4DoaQp8xlz5X75areDQtmX7w/N9KCXfwkRFyVxcUTyq54X35C0fzZptI5xUQc4k+u275c3idrw2zx4ePX/wE=)

**Comment by sasensi** [comment]
@lehni, sorry for the delay, I am overflowed by work currently.
Was your last commit (that closed this thread) able to fix the issue ?

**Comment by lehni** [comment]
@sasensi no worries, I know too well how that goes ;) Yes, my change fixes the new bug as well as the original issue here. Your test is still there and passes. Should be all good!

**Comment by lehni** [comment]
@sasensi …and I added a test for the new issue here:

https://github.com/paperjs/paper.js/commit/c82e5d41f7074533f3037553286ba35e442cb0f0#diff-d0910dfd0a27fc801d12c43b3c3e040fR202

**Comment by sasensi** [comment]
@lehni, ok, great, thank you !
