### ISSUE TITLE
Type Definition of Item.isEmpty() is misdefined

### ISSUE THREAD

**Issue by harrydrippin** [paperjs/paper.js#1712]
# Bug Description

In the auto-generated Typescript type definition file (`dist/paper.d.ts`, [Line 2326](https://github.com/paperjs/paper.js/blob/develop/dist/paper.d.ts#L2326)), the return type of the method `item.isEmpty` is misdefined to `void`, while JSDoc showing `boolean`.

```javascript
/** 
* Specifies whether the item has any content or not. The meaning of what
* content is differs from type to type. For example, a {@link Group} with
* no children, a {@link TextItem} with no text content and a {@link Path}
* with no segments all are considered empty.
* 
* @param recursively - whether an item with children should be
* considered empty if all its descendants are empty
* 
* @return Boolean
*/

isEmpty(recursively?: boolean): void // Should be `boolean`
```

**Comment by sasensi** [comment]
Hi, thank you for the report.

This issue has already been fixed and will be released in the next version.
You can check it from the "prebuilt" branch [here](https://github.com/paperjs/paper.js/blob/prebuilt/dist/paperjs.zip).
