### ISSUE TITLE
Dynamic (Variable) Stroke Width?

### ISSUE THREAD

**Issue by MelerEcckmanLawler** [paperjs/paper.js#1715]
Say I have the letter "a" as a non-closed path.  I can change it's `strokeWidth`, but that changes it for every part of every segment.   How to change it so it's for instance, fat at the beginning than trails off, like handwriting?  

After the `path.add(coordinate[i])` I tried adding `path.insert(0, coordinate[i + 1])` based on the demo but that was very ugly and choppy and did not look as smooth as in the demo.

I am open to non-paperjs ways to achieve this via JavaScript, even if it takes NodeJS or something.

**Comment by sasensi** [comment]
Hi, I think that you should have a look at this [thread](https://github.com/paperjs/paper.js/issues/371).

**Comment by sasensi** [comment]
I close this issue since there is already a thread covering it.
