### ISSUE TITLE
How to crop a path?

### ISSUE THREAD

**Issue by MelerEcckmanLawler** [paperjs/paper.js#1718]
I want to crop a path with a rectangle.  This may mean turning the cropped path into multiple paths.

I have been messing with `divide`, `intersect`, etc. but none do what I want.  Hopefully it is extremely clear what I'm asking and there is a simple solution.

Using `intersect` for instance on a hand-drawn star consisting of a single stroke produces flawed results: [sketch](http://sketch.paperjs.org/#V/prebuilt/S/jVJNb4MwDP0rVi4NEkJs2ompO7BdJ02bdlp3SMFtI0KCkkA1If77EugGtBVbDpbiZz8/f7REshJJQt4KtNmBhCRTuf/D6Qm0UDF7uN/ojRxdaQprkHiEF4dFr5hZJvcCae9SXFp6G8chOBOEMDrvvNOZIJjwpWlkrFYFPiqhtONdbQXLitVZyVLVBp/UUbqIHRMGJ7iSzxOUYoPSBrB+gHaMgRmD1fWUAPomJz3R4AL9U2V3KUiz/YIgvgP6KyqYY6eaLM+H7KjyE5yr6pZqv1f/HMX5MH+65WUl+O6L3sTzqn4ZGk0trEt2y8t5w3OkPimElkuD2ib9gENnWYbDp5uzDAyRQeGOB/NrK/GHsQD3KjWWqsHZtjp3xVuNrOgnZkjy8dl9Aw==)

**Comment by sasensi** [comment]
Hi, unfortunately, I don't understand your issue.
Here is a [sketch](http://sketch.paperjs.org/#V/prebuilt/S/hVZLbxs5DP4rgi9NAVuRqBfloqcW3etie3RzkB25CeLMGDNT5BDkvy+ph51ddLEGEnM4/MiPD4l+XQ3pOa+2q+9PeTk8rNarw3jPz7e34uuUXsSUD0safp6y/DH9GA7jMC9Xnfgshvwi/kzLg/yrK29e2VLQ5ziNz1uxA6XWgv7drfuLZSS1ZbV9r56XaXzKX8bTOG3Fh/0pHZ4+8Lu3j5/4i/86rXlJE7kR+ywO03g+5/t3/MrLK7UroTn/fM7DMlP0ruLPbgfeEMXo7tZiR6wUf4O03ljSb6JEZwLcsXYHIZKpR37YBKnQGrJpAitRogXrCdekijPKEc7qgkPpPcawFk2o8ZxG5HhNajgNhDNQcFpGbzw7ktE6W0goGaMLZERvbTQOO86SGRTXGyVRQQjFxivnSqJOarBMQitJAmXfgJ5rUXLZWAnKGsq4S6ylOOidJmAVGs7AFadl8EH5XkovdQBj+bHYWs0jEX2xpbcqeqgZBBODq0GMK1QUvVVQg1jjL7jqxChbiwDogYtO5oiqtgdAGu+5Xl4iguoZcleNLrmQiabmcmmcdAZtcbcxEmJAx9ER7KWH3GoDuvJDdB5KuxCo+TVvTZmi59p4LkHsxXFkScPAD0FG4LJvqtDi6WAUKZvQiTJKY41HjrnNTagJUvN1cEyiSm1GmblxpfYapdYRAg8RJeUre6q0NhGxTo13rmYIHMBArF489d2Y0IZMqZZtUBpdH38bylyTO6u1beEN8skuFKkgIcSC1FF60wayDA+1xocOcQxpsdBHMG0c0LpLRzTXw0vH9W44sFxXXw8QoubTsqHSA/h+ZMA6j+XIKO9ixxEDa1zFgfFc+yb01FwdqCZ1HBfIlniWJseHcvghWKgjx2fJObTMnvprQ2gToIPm0S3eaTYwFlJUHrp7Qmyn1IEvpVI0/Fq1k6wtc0PTLyfCqtp/VUzp7ELoQTjRqJo7Cg7VnTa+TW2MhTNHoGwbjPlSefsdE4sfZhFiP/LKINeWXMUQevUd9z5iuyqspSpQWatwuUvv+l37Xzf9lO9/c89/OY1DFvNDOueZr/q8F2lPO4fEw/h8TlOm2/84Tvk2HZc8ifGcp7Q8jsPvNlV19vndOjuw5uajXKY0zKe05BvDC0lVDtdF0pEs/w+ISP+RF7E8ZPE4EKWZghEfMR6L7ro203BfNGVRpVmksqvOvEavwdte+16X2T8zkRf/NxeOa/FKYec8LVuxTL/omVgecn0QbxeK3x5PJ/FIyY3EIS3ihVZoGmg3Ztbu80KeK40rAXkkUGkXUSn9+vRvi3ct5d3763QqJvSLYj/l9HQeifK82u7u3v4G) demonstrating what I understand that you are trying to do and it seems to work as expected.
Based on this, could you try to reproduce your issue by using shapes that we don't have to draw and explain what is the current behavior and what behavior you are expecting ?

**Comment by lehni** [comment]
Closing in lack of feedback
