### ISSUE TITLE
Path intersection bug

### ISSUE THREAD

**Issue by MuTsunTsai** [paperjs/paper.js#1722]
In my app I noticed that paper.js sometimes came up with bizarre path intersections even with fairly simple paths. An example I constructed can be seen in this [[Sketch](http://sketch.paperjs.org/#V/0.12.3/S/jZHBbsMgEER/BfliV3KJcZRKddRTf6Cqj3EOGK8TagzRgpNWUf69i1JZSQ9VEQd2mHkawTmxcoSkSuoBgtoneaJcF+fGHtB9gApcTYhgQx2+DHAf0A3w6oxD9sLS1kg1pOs/zbWSRtsd2XtpPNyYjxpOfJQB9Sf3ELKyyNl1P/4cV0XxQIHGHiUyFMSwcGJvMuz5OxGk3RnIzo1ltHp0Y8U2MbXNr1JwJAhSxCyh7PTkK7Zq7OUGXf4HvaROd+jnnD39Bi9n8GLBIlvH2ii4tgHQEzrDMhroWgvea2Pm50To0rmTjp2wvM2JmNPlfag1E6Rr+rkWQQ4HR36fVJvt5Rs=)]; the blue color is supposed to fill the entire intersection, but it does not. The weirdest part is, intersection `i1` turns out to be OK, as one may try by un-comment the two lines I commented. Clearly, the order of intersection is not supposed to make any difference to the result, but in this example, it does.

I just noticed that the problem is fixed if I choose the "prebuilt" version, so is this a known issue and is already been taken care of? Just in case, I report this to you guys anyway.

P.S. In version 0.10.2 the problem also doesn't exist.

**Comment by sasensi** [comment]
Hi, thank you for the report.

Indeed, @lehni, recently worked on several fixes for boolean operations which were not released yet.
So I would say that this issue is already fixed.

**Comment by sapics** [comment]
Thanks for the report! Current version v0.12.4 looks work. [sketch](http://sketch.paperjs.org/#V/0.12.4/S/jZHBbsMgEER/BfliV3KJcZRKddRTf6Cqj3EOGK8TagzRgpNWUf69i1JZSQ9VEQd2mHkawTmxcoSkSuoBgtoneaJcF+fGHtB9gApcTYhgQx2+DHAf0A3w6oxD9sLS1kg1pOs/zbWSRtsd2XtpPNyYjxpOfJQB9Sf3ELKyyNl1P/4cV0XxQIHGHiUyFMSwcGJvMuz5OxGk3RnIzo1ltHp0Y8U2MbXNr1JwJAhSxCyh7PTkK7Zq7OUGXf4HvaROd+jnnD39Bi9n8GLBIlvH2ii4tgHQEzrDMhroWgvea2Pm50To0rmTjp2wvM2JmNPlfag1E6Rr+rkWQQ4HR36fVJvt5Rs=)
Thus, I close the issue.

**Comment by lehni** [comment]
🎉
