### ISSUE TITLE
Please release 0.12.4 for better TypeScript support

### ISSUE THREAD

**Issue by wes-r** [paperjs/paper.js#1724]
I'm using paper.js in a new typescript project and I'm getting TONS of `is possibly null` warnings. I believe these have been fixed via https://github.com/paperjs/paper.js/pull/1677 but are not yet available in the current release.

**Comment by sasensi** [comment]
You are right, this issue has already been fixed.
Unfortunately, a new release is not yet planned as @lehni misses time to do it.
But if you really need this, you can still use the `prebuilt` version of the library before a new release: https://github.com/paperjs/paper.js/tree/prebuilt/dist

**Comment by vicapow** [comment]
would also love an update to get our types working!

**Comment by lehni** [comment]
Done
