### ISSUE TITLE
Why not export the matrix when it is identity? 

### ISSUE THREAD

**Issue by alsymiya** [paperjs/paper.js#1725]
So I am will load and export objects through JSON. And I do transformations through matrices. I set applyMatrix = false, so that for every frame the object is moving with respect o its initial position. 

Then I notice that when you export objects with applyMatrix set to false, if I do the transformation in this way: 

path.set({ matrix: new Matrix(1,0,0,1,0,0) })

and I export it as JSON, the matrix property will not appear in the variable. I mean, why not?

**Comment by sapics** [comment]
When the property (ex. matrix, strokeWidth, strokeColor,,,) is equal to the default value, paper.js does not export the property for saving file size.
