### ISSUE TITLE
How to draw pie chart?

### ISSUE THREAD

**Issue by whitesnow9291** [paperjs/paper.js#1727]
I used path.arc to draw piece of circle.
and set fillColor, but all I can draw is this.
![img](https://user-images.githubusercontent.com/25058760/67968670-c7b3c800-fc42-11e9-94f0-8376b5f71201.png)

Is there any option to fill whole piece of area?
And do circle path have another options such as startAngle, endAngle?

**Comment by lehni** [comment]
You need to add the center point to each arc path, e.g. with `path.movetTo(center)`before actually drawing the arc, and you should get actual pies.

**Comment by heaxo** [comment]
> You need to add the center point to each arc path, e.g. with `path.movetTo(center)`before actually drawing the arc, and you should get actual pies.

Hello, could you please explain in detail and provide the code? I am a beginner, thank you
