### ISSUE TITLE
Any way to compress exportJson string?

### ISSUE THREAD

**Issue by mrchrisjoy** [paperjs/paper.js#1730]
Hi, sorry for not using the template.

Is there a way to compress the string exported using the [exportJson](http://paperjs.org/reference/project/#exportjson) method?

The issue I'm having is that when layers get too large when I try to store it on the server, the HTTP request takes a while.

**Comment by sapics** [comment]
How about compress json by library like https://github.com/imaya/zlib.js ?

**Comment by lehni** [comment]
I think compression is outside of the scope of our library. The suggestion by @sapics is one possible strategy that can be applied to the data that comes out of paper.js (wether it's JSON or SVG)…
