### ISSUE TITLE
Is it possible to export objects as array? 

### ISSUE THREAD

**Issue by alsymiya** [paperjs/paper.js#1734]
I am using project.exportJSON() and project.importJSON() and project.clear() to modify states of objects, which slows down performance. 

I want to modify the objects in another place (say, a reducer, for example), then I will export the JSON first, then JSON.parse(projectJSON), then modify it in javascript. 

I just want the array with subtle information. Is there a method to do so? 

At best, I hope something like
project.exportArray()
and 
project.importArray()
can be used.

**Comment by lehni** [comment]
Pass` { asString: false }` to `exporTJSON()`, as mentioned in the reference:
http://paperjs.org/reference/project/#exportjson
also, this is a bug database, not a support forum. Questions should go to the mailing list.

**Comment by alsymiya** [comment]
What about importJSON?

**Comment by lehni** [comment]
That works with strings, objects and arrays
