### ISSUE TITLE
Path.removeSegments() results in script error in function addJoin (segment is undefined)

### ISSUE THREAD

**Issue by SkepticaLee** [paperjs/paper.js#1755]
# Description/Steps to reproduce
quad = new Path ({strokeWidth:2, strokeColor: "red", blendMode: "screen"});
quad.add ([100, 100]);
quad.add ([200, 100]);
quad.add ([200, 200]);
quad.add ([100, 200]);
quad.closed = true;
//quad.closed = false;
quad.removeSegments ();

This results in a script error when the blendMode is defined as anything other than "normal".

# Expected result
All segments should be removed from the Path, while it still retains its original properties.
Due to the error, however,  the script terminates execution.

Workarounds:
1) Set blendMode to "normal", or don't set it at all;

2) Before calling Path.removeSegments(), unclose the object by setting Path.close = false;

3) Wrapping the addJoin function in a conditional wrapper, e.g. if (typeof segment != "undefined")

# Additional information
Windows 10 Home, Firefox (72.0.1 64-bit), paperjs 11.3 - 12.4 + prebuilt,

**Comment by arnoson** [comment]
Please provide a paper.js [sketch](http://sketch.paperjs.org/#V/0.12.4/S/fdDBCoMwDADQXwk5KcimHpWddh4MPOxgPVSbTbG2rtaNIf77KmywTVgPgb6EhGRCxTvCBLOWbFVjgJUWy/86cgE7UHSHI7c1eBNT4N5gjW7p1AhbJ3HwaXsttUmAoSHB8JUqJSlxcC2XRDdK2/TywZCp2U+ZWoZsuBDg5VEYBuBC8ePxP4/XHq28knqgZRdrRnK43X7zmcuB3sWGOn2jjC4dKTuA56fuJKUh3va6cYJJXsxP) with your problem, this makes it really easy to test it.

I've tested the above sketch in Chrome 80 and Firefox 72.0.1 on Mac OS and didn't get any error. Can you test it in your Browser?

**Comment by SkepticaLee** [comment]
Not sure how to provide a sketch without further instructions, but the url I was working on was: http://sketch.paperjs.org/#V/0.12.4/S/fZCxDoIwEIZf5XITJo0CI8bJ2cSEwYEyFHoCobTaFh0I7y7IYIzE5ZL//3JfcjegFh1hgmlLvqyRYWnknO+9kHAATU84C19DMDhvTUuXRvo6iRks8WiUsQlwtCQ5MigUaXmaFHOnqRK+MZrjuNlzy/Us3QopIciiMGQwjfyHxP9JvEaiFVIq42i+wdue3vVu9w2uQjn6LFjqzINSqjrS3kGwuKaXFJZEezPN1GKS5eML

The file downloaded as Sketch_200114_155736.js.

One other thing, it did work with blendMode set to "screen", but setting it to "negation" did result in the known script error.
