### ISSUE TITLE
line fill option

### ISSUE THREAD

**Issue by focusedsoft** [paperjs/paper.js#1756]
Is it possible to line fill shapes in paper.js?
![image](https://user-images.githubusercontent.com/6641294/72276732-8d927980-3628-11ea-9fc9-837f4b38af75.png)

**Comment by lehni** [comment]
Yes you can use the `options.trace` option with boolean operations to operate on open paths (e.g. a bunch of lines): 

http://paperjs.org/reference/path/#intersect-path

But please don't ask questions in the issues. This is a bug database, not a support forum.

**Comment by focusedsoft** [comment]
thank you
