### ISSUE TITLE
CoumpoundPath.compare throw error

### ISSUE THREAD

**Issue by myagoo** [paperjs/paper.js#1769]
# Description/Steps to reproduce

`CoumpoundPath.compare` function throw `Uncaught TypeError: CollisionDetection.findBoundsOverlaps is not a function`

# Link to reproduction test-case

https://codesandbox.io/embed/paperjs-luovu?fontsize=14&hidenavigation=1&theme=dark

# Expected result

CoumpoundPath.compare should not throw

# Additional information

**Comment by lehni** [comment]
@waruyama looks like this is caused by your change in #1737, #1740

Could you take a look what's wrong here? It looks like we don't have any unit test for this method…

**Comment by dorpxam** [comment]
Hi, I've the same problem. In the master, the `CollisionDetection` utilities do not contains `findBoundsOverlaps` but it's called in the `PathItem` base class (`compare` function). Maybe that's just a typo error and `PathItem.compare` need to call : 

`findItemBoundsCollisions: function(items1, items2, tolerance)`

The `PathItem.compare` problem is line 725 : 

`var boundsOverlaps = CollisionDetection.findBoundsOverlaps(paths1, paths2, Numerical.GEOMETRIC_EPSILON);`

Thank's a lot for this great project !

**Comment by lehni** [comment]
Yes I am aware, but I'm not sure what the author's intent was, hence my question to @waruyama above

**Comment by waruyama** [comment]
Sorry for that, my bad. That is most probably a leftover that did not get refactored properly, so I guess @dorpxam is right and `findItemBoundsCollisions` needs to be called instead. I will take a closer look later today.

**Comment by lehni** [comment]
Thank you @waruyama for the fix!

**Comment by myagoo** [comment]
Thank you @waruyama and @dorpxam  for the quick fix and the amazing work :)
