### ISSUE TITLE
Potential side effect in PathItem.Boolean.js

### ISSUE THREAD

**Issue by dorpxam** [paperjs/paper.js#1773]
Hello,

I'm not sure about this one, but I see a potential bug in the `PathItem.Boolean.js` file. 

In the subfunction `function getCrossingSegments(segment, collectStarts)` of the private method `function tracePaths(segments, operator)`, the intersection collect use a potential (typo) invalid linked list member pointer : 

**line 942 in PathItem.Boolean.js**
```
if (inter) {
    collect(inter);
    // Find the beginning of the linked intersections and loop all
    // the way back to start, to collect all valid intersections.
    while (inter && inter._prev)
        inter = inter._prev;
    collect(inter, start);
}
return crossings;
```

You use `_prev ` where the property is initialized as `_previous` in the `CurveLocation` class and where the `function linkIntersections(from, to)` use the `_next` and `_previous` properties.

**Comment by lehni** [comment]
You're right! I wonder if this code is still needed though, because I've later improved the sturdiness of the approach by allowing it to try all possible paths of the intersection tree… But it can't hurt to fix this.
