### ISSUE TITLE
How to change the layer order in paper.js

### ISSUE THREAD

**Issue by KeJunMao** [paperjs/paper.js#1776]
# Description/Steps to reproduce

I'm sorry my bad english.
How to change the layer order in paper.js
I try to modify `paper.project.layers`(https://draw.kejun.me) ,But it didn't work
I want to make layers like PhotoShop.
Any ideas? Thanks!

# Expected result
like PhotoShop.
Allow changes to layer order

**Comment by sasensi** [comment]
Hi, you can organize your layer as you would do with any other items, so you just have to use one of the "Hierarchy Operations" listed in the [documentation](http://paperjs.org/reference/layer/#layer).

Here is a [sketch](http://sketch.paperjs.org/#V/0.12.4/S/rZLNCgIhFIVf5eKmiWL6GdpMtIjZtghaVgtzbo1kGldriOjd02SggqCgu9FzDsqnnCvT/IAsZ4s9OlGxLhOmDLrXg4KQO4QMFL8g2XRFKy2Mti4aA5iAxhpmQSTLkIKfYM25q9JCklCYXJsgjEDtkHI4S6zTKLrPOfFSnmwOo/6LvZVKFUYZf7J1QaVM3WriWzvs1u1xWN4Ih/8hhM47zxeYhrje4VeY2d8wB/2fOQnLz5C+BHPFBUZOGALfmHOjskch4kenUlskNw1xEh8Vb/GF2vga7Y9GamdZvlzf7g==) demonstrating a possible solution.

```javascript
// Create 3 layers.
const layer1 = new Layer([
    new Path.Circle({
        center: view.center,
        radius: 50,
        fillColor: 'yellow'
    })
]);

const layer2 = new Layer([
    new Path.Circle({
        center: view.center + 50,
        radius: 50,
        fillColor: 'orange'
    })
]);

const layer3 = new Layer([
    new Path.Circle({
        center: view.center + 100,
        radius: 50,
        fillColor: 'red'
    })
]);

// Place layer 2 above layer 3.
layer2.insertAbove(layer3);
```

**Comment by KeJunMao** [comment]
thx!
