### ISSUE TITLE
Extend documentation for Raster.drawImage

### ISSUE THREAD

**Issue by LBBO** [paperjs/paper.js#1781]
# Description
According to [its documentation](http://paperjs.org/reference/raster/#drawimage-image-point), `Raster.drawImage` is supposed to take an `image` of Type `HTMLImageElement | HTMLCanvasElement` and a point. Internally ([src/item/Raster.js:570](https://github.com/paperjs/paper.js/blob/develop/src/item/Raster.js#L570)), this calls `CanvasRenderingContext2D.drawImage` [which accepts an `image` of type `CanvasImageSource`](https://developer.mozilla.org/de/docs/Web/API/CanvasRenderingContext2D/drawImage) (`= HTMLOrSVGImageElement | HTMLVideoElement | HTMLCanvasElement | ImageBitmap | OffscreenCanvas`) as its first parameter. `Raster.drawImage` works perfectly fine when called with a `HTMLVideoElement`; I haven't tested the other types yet.

# Expected result
Unless this type definition is intended for some reason, I'd expect the first parameter's type documentation to be changed to `CanvasImageSource`.

# Additional information
I'd be happy to provide a PR with this change (unless the current type definition is intentional, of course).

**Comment by sasensi** [comment]
Hi, thank you for the report.
You point seems totally right to me so I took care of making the PR.
