### ISSUE TITLE
Runtime error: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined

### ISSUE THREAD

**Issue by whyld4900** [paperjs/paper.js#1792]
https://github.com/paperjs/paper.js/blob/c044b698c6b224c10a7747664b2a4cd00a416a25/src/node/self.js#L21

Can we make this line have a fallback to empty string if parent.filename is undefined?

![image](https://user-images.githubusercontent.com/6947701/78153805-15567b80-7401-11ea-9d09-bc502967a013.png)

I'm using wallabyJS (node mocha chai) for testing and this breaks during test startup.

**Comment by sapics** [comment]
Sorry for late response.
The solution in https://github.com/wallabyjs/public/issues/2383 looks good.
If it has not fixed yet, please reopen this issue and make a comment.
