### ISSUE TITLE
Some elements move if rotated by multiples of 200 degree

### ISSUE THREAD

**Issue by LennartH** [paperjs/paper.js#1793]
# Description/Steps to reproduce

Create a triangle with `RegularPolygon` and rotate it several times by 200/400/600/... degree. I couldn't determine any other values that produce this behaviour. Also effects polygons with 9 or 27 segments, but no other elements.

# Link to reproduction test-case

http://sketch.paperjs.org/#V/0.12.4/S/lVTLbtswEPyVhU4WQjh61HHlpJcG6DloiqJF1YNCbyTBCilQVNM08L+XFB+inRhBdBConZ3hzi6p54hVDxhtotsdStpEJKJ8q7/vR0Zlyxn0vHuqOVv0fPhB1Nfwk8CA9QMyOcTwXDJQD+VskCBFW7G6Q/gEDB/hppLN8ivWY1eJG6syxXnLZKAXz4IEVkl8aTSd2nKQgu/wmndcWOVpvSiju66iuzJyDIFyFMwTVXRfspJ5Kw4I93YOLPc1t3n8QkkglUbqsd3KhkCDbd3IiXGsbHrjGYfNcTIn+qLDt+2/o23i2bDlv7tHnvnCGm0FVQXRvwToEwFx5MPAoYlrQ5gdGGqsuXZTQ3p3kYbmKuxQnbBUEf0Y0yQhoF5JbNEsRLNjNA/RPEANThVsza8cOJ1HA+uS57GnBiPwUS+K9crL9IVKdMfIpukUK9Nn6wDPPZ6tXUIArzycXsx18pFJ1OUklweT4+yLUJd5gX/UVQrGNqWfndnetvewcBJXWtxn6uf8HD5XW/hedSMOG5h6+EG/LhJn1vQlVdBMk+lScFlJ1Rg3wymc+bDudIjkDimKIgTmVV8ckAMgW59ADnx8w0G2rAYuG2UVO5z+MHMKPSEi3hTvX8lQR3Sv/p53Aqtdr6/BEG1+/d7/Bw==

**Comment by sasensi** [comment]
Hi, I don't think that this is a bug but rather a maybe surprising default behavior of the `.rotate(angle)` method.  
When you only pass a single argument to this method, the item is rotated around the center of its bounding box.  
In the case of a triangle, this kind of rotation can have the effect of changing the bounding box itself and with it, the center of rotation of the next rotation, hence the displacement that you are seeing.

What you need to do is pass the original center, used to construct the polygon as the second argument of the `.rotate(angle, center)` method.  
Here is a [sketch](http://sketch.paperjs.org/#V/0.12.4/S/lZTNbtswEIRfZSGgiAwYjJCiFxU+xA5yTZC0p6YHmlpLhBlSJSmrReB375JS5D/ZSAzYkKXZ3W9naL8lmr9ikifPa/SiSqaJMEX4fn0Nd5a34K3kulQIt9BWUlTQSqVAcY8WlgjWeLosgFvT6AKkd2CsLKXmCgRqUrEX+6KF0c4PvW4feskiKh6N1B5msJHYsq7o+0gRKTS28Mh9xZ6wbBSnSvWvNDq91HgKX6fwLZvEloOQOW/NGhdGGUuNr5aqwasoCe+R5eOi0ujTrQJ2N2+fcCGtUJi+BR3QqyvLL3owfRdbXsjG5UT+fmdFrkfYvGcND7aT88Tzj8a1DFeu5+tbpQWueKM8lVR8I42djKQ4p3V3fgplNKaHLs+PXTaW7vc+05jnyhwQRxSpS7r4C86Ar7iHFkFwTSQ+7EACtM5zgm/DU+n6XhWva9RUzA4JuvWYQ4UibB6YG7zk2/mkh66fj3sA6R58MOner9OsHzQ0dUFRMhb5Vo0Wkdnoe0s/6BQ3NGcCA49cQXePCeLw8AVuMpjNZpDticKLmj/FQ0Ih+Grgd2xftIu9O1DpTZZNLx7tjn5vyI9KOkoP8E8jN1yREryhpJWiDPMj8c7FsXlH3h6OGis9gfkZvbxwCOCV2/WoBf1ZYLVxMhbMznENQ7cxz/BBf7dLi3xdB4tckv/6vf0P) that should clarify my point.

**Comment by LennartH** [comment]
Hi. Thanks for the clarification. Surprising indeed, but reasonable.
