### ISSUE TITLE
Syntax Error in paper-full.js

### ISSUE THREAD

**Issue by sandeep318kumar** [paperjs/paper.js#1799]
syntax error in it:paper-full.js:15726 Uncaught SyntaxError: Unexpected token (9:9)     at raise (paper-full.js:15726)     at unexpected (paper-full.js:16366)     at parseObj (paper-full.js:16844)     at parseExprAtom (paper-full.js:16799)     at parseExprSubscripts (paper-full.js:16730)     at parseMaybeUnary (paper-full.js:16716)     at parseExprOps (paper-full.js:16682)     at parseMaybeConditional (paper-full.js:16669)     at parseMaybeAssign (paper-full.js:16655)     at parseExpression (paper-full.js:16644)

**Comment by sapics** [comment]
Could you give us a test code in http://sketch.paperjs.org/ ?
Without test code, we could not identify bugs in paperjs.

**Comment by sapics** [comment]
Closing in lack of feedback, and there are no information about error.
