### ISSUE TITLE
Shadow Clipping on Candy Crush

### ISSUE THREAD

**Issue by hsab** [paperjs/paper.js#1806]
# Description/Steps to reproduce
I've been running into some issues with shadows and shadow blurring on the [Candy Crush](http://paperjs.org/examples/candy-crash/) example. Basically what happens is that the shadow is clipped outside the path boundary.

# Link to reproduction test-case
Replaced the path instantiation on line 12 with the following ([Link to sketch](http://sketch.paperjs.org/#V/0.12.4/S/nVfbbuM2EP0V1kU3UmzLdi6LXbtOAbfoUxddIED7kPhBFzrWWiYFinLiBv73Dq8iJTlNNy+RZ84Mh3NmyOHrgMR7PJgP7neYp9vBaJDSTPyeTNDuSLIoJxuKrqazm0fySDY1SXlOCVrFRRGwESpH6BCiV9Bxvs2riMVZXldoidjCykqaEw6ishEdcMopA9mhke3jl79wCrLZbSMk9f4eP+2xdPAl5ttoU1DKAoYm6BoN0VXYYBNak+zPzabCAvyw7tWs6s2mpa3yDH8VMVZGocKG1UBA8DP6Cp+B3OQj3+RF8SstKJsjLXnk2xrPVXQsJhndByG6RNcfpyMDqGJes1hkbo5mVpqw/GnLCa4qkCrhSSuTApPsCzAxRxeFQGF2oVVpQSuczRFnNdaiijO6wzoqEbD8DC5+xNebz59vLkIP93ee8e0cXRnhNs7oc9c4KeJ015hK1KqoAXQ19YQqscpW5jEYfxyh8a0yPUmG4GMDhAeHmKEcsjpdwL+fUYtjIRwOQ5PYNndRWVfbwKkzRX4/yW+DBblRnGVBE3ToAZqiUI4anGU9Jk8F8AM8QzG2q/US5ZZn4PJJZNxwrFc6PZKTSI3opahklFN+LDEkR66QA+UxB/+m5wI/L+kWp7sVZRlmVWBCzzcocBosUiujO+R0WGjC6gEuXaCXL9nDQ61XRq6+LjMI9n4bl1gHIysZ/rtx9m1GVESV/yP2fcjxcyS+27uRq0cvUDBjl1BvIwazlN6iZ1HkcEA4+HNe785anFth/J9ej++I9Whi3WLR4e8J9miC7TM5t0YnWkONQ9pZZlQ5V6YyZN8YoY7x/Y1tj0Pt4CFf29tBWjxhfm8aL8jNyeH2bLWnFA7j8H+v3ZzWNqfOiQGRGEt9hU3QjY23e8II/LKNXxi8CIjgF7GtABZHsxD91AnLBZcMHxT4Dk1D9AuEPEYzNO8cKyD1DKm57noCtEANgu51z0PwpRQhxK7v3Ba6myaxq7UpO1chdrAWnq48v9cLryhbZ7STxU5ulQ9tfnLLluE45U7BJl7FZnll86F6AIrqNxDGJMVBomTueSkNfO6HKDGfHz4ojz8sBTGvXu4PmBVx2aoDx3YsTT2+spzJGcdpaoCZqCJC2T4uoMED4/wSTaPp7Db086jnJ+BIOrTKxGjGjsY1TOMiXYlUV5A2x8yRC1xrOXVQaL1r1qvwyILkrxpq32BNjmV+VhaNXt61Im8CGKlf0FefpqKz4AbWUIZhziLdinImR2U7kdf2ZQepL8Jw7d9hNju9G/ieQ0jAefnGuWdRyR+YAC6J/FQGvPRxPBPeyrfKXZ99GcQnvDrhnO9PqKRAhgCM8Ex2uPV26ifcbsXJVk4y/GIXdHnSowVqjV0P0mLdw5HW9FxlHY6+g6Jz51X/WaWzZOc52W+TybjvD+3jnKBelbCSXMMoaF8h8hap9ystm30CWd8+DAZ+2RKTlwqtcvlYW6rJ1X2c+KOWQNsnWWfSdebcS/+VoydcM9+2X0CzafMAkGvY12EbCa6HSHexzEEzdKuXpjQc2S2NdLhykj55L1NKfmfwojXU9yVMraBHXnGjOolzLL6Bhby9F/DpW4HE62apE9OMvJsC9fPb2j8Ru+GMUCE623MsAiz8iKx3/SYImvcDvNcTWHMnm6gazB/Wp38B)):
```
this.path = new Path({
		fillColor: {
			hue: Math.random() * 360,
			saturation: 1,
			brightness: 1
		},
		blendMode: 'lighter',
		closed: true,
		strokeColor: new Color('#e3f994'),
		strokeWidth: 2,
		shadowColor: new Color('#edebee'),
		shadowBlur: 5,
		shadowOffset: new Point(-6, -5),
	});
```

# Expected result
This however seems to be example specific and does not [generally occur](http://sketch.paperjs.org/#V/0.12.4/S/dZFNDoIwEIWv0tQFNEFDavA3bvQAmrhwIS4KLYFQGVKKLox3l9ZAwMhu+r5p583rCxfsLvAGn3Oh4xR7OAZuzg+mUMl0inaoEE90akqXbMPCaLNKK8jFASSohjuRZHHutJBx7torkBXanfsemvuEbNEopsEoXrV4lC57NJZQCd440qoWndc7QN97kklpne9QiK3zEP9dy8yxtetM1pTTaOn8BHDJuA2IdnLKODz/PPBNiAz79rI2bdQfysckqYRuc7eLThceCkjzOZESLC+NVuHN9fb+AA==).

```
var path = new Path();
path.strokeColor = 'black';
path.add(new Point(30, 30)); 
path.add(new Point(30, 25)); 
path.add(new Point(80, 25));
path.add(new Point(80, 75));
path.closed = true;
path.smooth();
path.fillColor= "black"
path.strokeColor = new Color('#92d2b7');
path.strokeWidth = 2;
path.shadowColor = new Color('black');
path.shadowBlur = 20;
path.shadowOffset = new Point(-6, 5)
```

# Additional information
I'm assuming the issue arises from the specific implementation of Candy Crush. But from what I understand the boundary calculation is only used for the "simulation" and does not modify any internal attributes of the path. Would love to get some clarification on this.

**Comment by sapics** [comment]
@hsab Thanks for the report!
I guess that this bug would be fixed by #1631.
