### ISSUE TITLE
path.unite(path) operation gives wrong result

### ISSUE THREAD

**Issue by LanderN** [paperjs/paper.js#1812]
# Description/Steps to reproduce
I'm trying to use paper.js to perform some operations on icons. One of these operations is merging all paths into a single path (in inkscape: select all paths, then use Path->Union).
Paper.js does not produce the expected result.

# Link to reproduction test-case
[paper.js sketch](http://sketch.paperjs.org/#V/0.12.4/S/bVZNbxs3EP0rhC6xUXpNDr8NO4f2UPQQoECKXuoCUdYbS/VaEiRFNhLkv3c4H04MxDCw4iz5Zvj2zSO/LjbLx2lxtXj/MB3H1cIuxu1dH++Wu2k/7Pbb/6bxOKwfd9v98f3fv599uD6c7s1p2h/W283N7cIP/nZhbjcG/54f580BY6vjcXd1efn09DQ8hWG7v78E59wlLnw99ep5Xm8efrrAt9Yu6TUueVrfHVc4LTiHo9W0vl8dX4an9fT06/YZx844A/3/dvGWs1zvlseVucN378pQIRRvvRtq8TBeuMH5UL3Fpws5mx6A6gIFUgIKRAiggdVFHDzEmGmt8z5ZR5McQLP0A6McCTFqJM6E3KBIJHtOnkHnhEirAoTAkeAKpy9FVlXvO05IoaUeweyJC4FaE89pkYtOMTEy5Mz1lAg8J7ZcOw6Ar4QMqRUhQ1KBKwzDtcSUGCOkUilSwPOekq+UB0JNjUmRNFidElEyowZIryMhuXC6CEP0DWB0Vkj1Roi0Qi1IQKkJYaZALApcRmaRcX01/EmLpKmM0Ap/pAQlz53AWgkyQC25I3hXhTbUXl8SnOdAygSRUmLMkmKHgAqJcoIPjSDAyVf2KaS+JHaFEWaqtLNcpYyAcB0jJcdLYo2Ny/BZyGjBEGisQoaUVUHHK5Xkd0WqIFWPKkdVo4pRtahSVCWqEFWHKkNVoYpQNagSVAWqAFV/Kj9Vn4pPtSfSU+WR8FR3KjtVnYpONSeSU8WpvFRvP4xJbd/FRs0fAyvSZ6m28jhWyhhaDaTzXLpLQG4lsMqLo5xQpXGxNOI7CWL0zEdJQAgQs2w4lMRN6yrtEld66XTHSXNhKyqpMWcxwpd3Fd+URu4VC7TOhK9qBbW5ytREliOqLPbWQvFBoy2EBpnnutIDuGVud+SjUgRqZjG7FlKexYayulgm98OvQHOxycgWQw282EPpDPjsPXOGsJl2nBvMzmItLaYyaylSiRaidWgZWoUWITXMvQQPmPoLWvz1ZXf3nzl9b+lg41Cyq5X4bq6ywguQs/qCfNLeMlLPkZKp21FIgbzWqUNASECu6UtgB0CFNOIoQBdL/1FRJT0Ssbkogh89EfmxBWnxygH86JHOHV88oRCcFfxZ0azAi4JS1wehU3GVRRhby/Hkh4itW1jYDb8BSyiQ6nwm58UHD5gQnMTHV4/r7B/G+DhdIC7yEtWdW2xsxmJAqLzCfhMZAzsC+kdrMZLLJTw/48i2rSu4LVsVGyzs176Jnyfce9dBQdMlqkurDNGyYORCWdFG2J4D8khWkRsHkN7urTGgg9LHySgIMprEbuyxmcXopHAUKjmXa3oG+F4GNizvxKOCCCFIl6BLUFI8TeTwL5XsOoIeVbWR26XMEsGmZ7vEa0d6ddxBKXqBiFRG9JHcAGnpfBKNlnnlKiqbA9JqhEQrrBrmkAwVSe0VEIWWOQ2jMGiFUiMEWmaUtxB9skLoLPRZ5pP9GumzTKcR8qywaYQ7K2TOTJ0VKkdhzgqVRoizwqQR3qwQOQttbCWV1xc+vXpPG21hKz1ttIOttPQrp7jud1B8fji/3ZyWe/Nxv32YNubGyD2XveTHv+F+Ov5xnB4PZ1/N4xJvyFdmjUNz85af683huNyM0/aT4Rvzn92Hvp3/BGk/3X0ep7Oz5ThaM37e7887Co6GzxvEOusha74i4rQ/XplPy/kwfTtHpNsN1znstof1Ea/dw7P55Qbvue7lzaf1PP+2nbd73Mubj/NyfHjz8m55d/fX9kx2eI43/I/7afmw2643x8Pi6p9/v/0P)
You can see the original path on the left and the unionized (broken) path on the right.

# Expected result

Expected:
![image](https://user-images.githubusercontent.com/12765267/82427027-d9e33f80-9a88-11ea-85d1-67197fe339ee.png)

Actual:
![image](https://user-images.githubusercontent.com/12765267/82427078-e5cf0180-9a88-11ea-9857-30b30c3563ae.png)

# Additional information
I'm using this code to get the union of all the paths:
```javascript
var unionized = project
                .getItems({ match: item => item instanceof paper.Path })
                .reduce((acc, curr) => acc.unite(curr, {insert: false}))
```
Tested on latest Firefox and Chromium on Arch Linux.

**Comment by sasensi** [comment]
Hi, this is not a bug but a misunderstanding in the way you are uniting items.  
By calling `project.getItems`, you are getting all the 3 paths of the drawing: the hook shape, the outer rectangle and the inner rectangle. If you think about it, the result that you get is correct in the sense that you are uniting these 3 paths but Paper.js has no way to know that one of them has to be subtracted from the union of the others.
What you need to do instead is only uniting the hook shape with the existing compound path (outer rectangle - inner rectangle). You can simply get those by traversing the nodes tree.
Here is a [sketch](http://sketch.paperjs.org/#V/0.12.4/S/dVdNbxs3EP0rC51SgF6Tw2/H7qE95NIABVL0EhuIutpaqteSIK1lN0X/e4fzETuGa9iQOEu+GT6+eVz/s9gu78fFxeLT3TgP64VZDLtVG+8Pu7/GYe439/vdYf70+4d3Xy6Pp9vuNB6Om9326nrhene9uD5cbzv8ebqftkcMrud5f3F+/vj42D/6fne4PQdr7TmufDX34mnabO/eXOFqref0+HrRPW5W8xqneWtxtB43t+v52/C0GR9/2j3h2Ha2g/Z7vfhR81zul/O6W+HTj7kv4LMzzvYlOxjObG+dL87gp/UpdS0AxXoKxAgUCOBBA+uz0DsIIdFa61w0liZZgGroC0Y54kPQSJgIuUKWSHKcPIHO8YFWefCeI95mTp+zrCrONRwffY0tgtkjFwKlRJ5TAxcdQ2RkSInryQF4TqipNBwAVwgZYs1ChqQCmxmGawkxMoaPuVAkg+M9RVcoD/gSK5MiabA6JSInRvUQv4/4aP3pzPfBVYDBGiHVdUKkEWpBAkqN9xMFQlbgPDCLjOtKx0eaJU1hhJr5kCLkNDUCSyFIDyWnhuBsEdpQfW2Jt44DMRFEjJExcwwNAgpEygnOV4IAK6fsoo9tSWgKI8xYaGepSBke4RpGjJaXhBIql+GSkFF9R6ChCBlSVgEdr1WSz4pUQaoeVY6qRhWjalGlqEpUIaoOVYaqQhWhalAlqApUAar+VH6qPhWfak+kp8oj4anuVHaqOhWdak4kp4pTeaneXoxJbc9io+YPnhXpklRbeBwKZfS1eNJ5ys0lINXsWeXZUk4o0rhYGvEdBTE45iNHIAQISTbsc+SmtYV2iSuddLrlpCmzFeVYmbMQ4OvHgk9yJfcKGWpjwhW1glJtYWoCyxFVFlprofig0hZ8hcRzbW4B3DK3O/JRKAIlsZht9TFNYkNJXSyR++Ep0FxsMrJFXzwvdpAbAy45x5whbKIdpwqTNVhLDTFPWopUooVoHVqGVqFFSA1TK8EBpv6KJn953tz9ba9vTe1N6HOypRDj1RbWeAbyVpeRUdpdQvI5khP1O0rJk9ta9QjwEcg3XfbsAaiRSix5aHJpXwrqpEUCthdF8Ngj0R+qlyYvHMBjD3TzuOwIheCM4E+KZgReNBSbQgidiissw1BrCifXB2zezNKueAosIk+6c4m8Fz94wITgJL7AWlxnvxjjx+kMcZGXoP5cQ2U7FgtC7WV2nMAY2BPQjq2GQD4X8QYNAxu3ruDGrEWMMLNjuyqOHnHvTQkZbZeozrUwRE2CkTJlRSNhg/bII5lFqhxAepu7Bo8eSoeTUBBkNZH92GE7i9VJ4ShV8i5b9RZwrQxsWd6JQwURgpc+QZ+gpHifyPWfCxl2AL2sSiW/i4klgm3PhokvHvG7Cw9y1leIQGUEF8gPkJbGJ9FomFeuorA9IK2dkGiE1Y45JEtFUlsFRKFhTv0gDBqhtBMCDTPKWwguGiF0EvoM88mOjfQZprMT8oyw2Ql3RsicmDojVA7CnBEqOyHOCJOd8GaEyEloYzMpvD7z/dV6utMWNtLTnXawkZZ+5RWX7VWUvn354X37aH/DbnucO3zw4bB72HdXnb78Lod5cxp/Wf49Hvo/N4fj/PN6M63eP68Zdvh6/LBd/drc5+obRD+0eYdx+9ndvJi9/79ZcPOqloctvmO3QnBFj4N5fPcyFZdOk/r5sNwepyXOwDdt09mXz5ar1W+7d2/s5uWk4zjh03GF6ebDw0hP8P+APw7j8m6/22zn4+Li882//wE=) demonstrating the solution.

```javascript
project.importSVG(`<svg version="1.1"
    xmlns="http://www.w3.org/2000/svg"
    xmlns:xlink="http://www.w3.org/1999/xlink" width="300" height="300" viewBox="0 0 20 20">
    <path d="M7.82371,10.8712c-0.01381,0.00366 -0.02803,0.00552 -0.04232,0.00552h-4.12446c-0.00115,0 -0.00229,-0.00001 -0.00344,-0.00004l-0.02927,-0.00061c-0.01624,-0.00034 -0.03233,-0.00307 -0.04777,-0.00811l-0.35395,-0.11556c-0.02885,-0.00942 -0.05454,-0.02661 -0.07425,-0.04968l-0.22187,-0.25972c-0.0177,-0.02072 -0.03,-0.04551 -0.03578,-0.07214l-0.05184,-0.23859c-0.0025,-0.01151 -0.00376,-0.02325 -0.00376,-0.03503v-3.41922c0,-0.00111 0.00001,-0.00222 0.00003,-0.00333l0.00047,-0.02327c0.00036,-0.018 0.00367,-0.03582 0.00979,-0.05276l0.11883,-0.32876c0.01084,-0.02999 0.03014,-0.0562 0.05557,-0.07546l0.28256,-0.21396c0.02027,-0.01535 0.04381,-0.02581 0.06879,-0.03055l0.25507,-0.04849c0.01016,-0.00193 0.02048,-0.0029 0.03082,-0.0029h4.12446c0.00115,0 0.00229,0.00001 0.00344,0.00004l0.02927,0.00061c0.01624,0.00034 0.03233,0.00307 0.04777,0.00811l0.35395,0.11556c0.02885,0.00942 0.05454,0.02661 0.07425,0.04968l0.22187,0.25972c0.0177,0.02072 0.03,0.04551 0.03578,0.07214l0.05184,0.23859c0.0025,0.01151 0.00376,0.02325 0.00376,0.03503v3.41922c0,0.01343 -0.00164,0.0268 -0.00488,0.03983l-0.0671,0.26973c-0.00705,0.02834 -0.02149,0.0543 -0.04185,0.07523l-0.24687,0.25375c-0.02083,0.02141 -0.04708,0.03676 -0.07595,0.04442zM8.03791,10.47294l0.18395,-0.18908l0.05146,-0.20684v-3.38129l-0.03926,-0.1807l-0.16477,-0.19287l-0.28656,-0.09356l-0.00306,-0.00006h-4.1072l-0.20182,0.03837l-0.21279,0.16113l-0.09286,0.25692l0,3.39457l0.03926,0.1807l0.16477,0.19287l0.28656,0.09356l0.00306,0.00006l4.10122,0z"></path>
    <path d="M7.32873,4.76088c-0.09084,0.00727 -0.17037,-0.06047 -0.17764,-0.15131l-0.01883,-0.23528l-0.17357,-0.48896l-0.32488,-0.38671l-0.42928,-0.24659l-0.49307,-0.0859l-0.21441,0.01716l-0.48896,0.17357l-0.38671,0.32488l-0.24658,0.42928l-0.08705,0.49964v1.40347c0,0.09113 -0.07387,0.165 -0.165,0.165c-0.09113,0 -0.165,-0.07387 -0.165,-0.165v-1.41774c0,-0.00949 0.00082,-0.01897 0.00245,-0.02832l0.09449,-0.54234c0.0033,-0.01895 0.00989,-0.03718 0.01947,-0.05386l0.27562,-0.47984c0.00963,-0.01677 0.02214,-0.03171 0.03694,-0.04415l0.43193,-0.36287c0.0151,-0.01269 0.03235,-0.02256 0.05094,-0.02916l0.53749,-0.1908c0.01356,-0.00481 0.02769,-0.00783 0.04203,-0.00898l0.25688,-0.02056c0.01385,-0.00111 0.02779,-0.00046 0.04148,0.00192l0.54234,0.09448c0.01895,0.0033 0.03718,0.00989 0.05387,0.01948l0.47984,0.27563c0.01677,0.00963 0.03171,0.02213 0.04415,0.03694l0.36287,0.43192c0.01269,0.0151 0.02256,0.03235 0.02916,0.05094l0.1908,0.53749c0.00481,0.01356 0.00783,0.02769 0.00898,0.04203l0.02056,0.25689c0.00727,0.09084 -0.06047,0.17037 -0.15131,0.17764z"></path>
</svg>
`);

const svgGroup = project.activeLayer.firstChild;
const compoundPath = svgGroup.children[1];
const path = svgGroup.children[2];

const union = path.unite(compoundPath);
union.translate(200, 0);
union.addTo(project.activeLayer);
union.selected = true;
```

**Comment by LanderN** [comment]
That makes a ton of sense, I should have thought of that 😖 

The code should be quite general though, so manually getting the correct child index won't be an option, but I guess uniting all top-level children should be fine.

I will close this issue for now, will reopen if I find anything that is not caused by my own misunderstandings 🙂 

Thanks for your reply!
