### ISSUE TITLE
Animating scaling with Tween not working

### ISSUE THREAD

**Issue by l-portet** [paperjs/paper.js#1816]
# Description/Steps to reproduce
I want to animate the scaling property of a path but it doesn't seem to work with Tween.
But on other properties like fillColor or scaling it works perfectly.

# Link to reproduction test-case

[JSBin Demo](https://jsbin.com/mexafevabe/edit?html,js,output)

# Expected result

The red circle should be animated to scale from 0% to 100%.

# Additional information

Tested on Google Chrome 81

**Comment by lehni** [comment]
I noticed the same problem also recently. When you start with `0`, scaling can't grow somehow. Start with something very small, close to 0, and it should work. But when using `Path.Circle`, make sure to also turn of `applyMatrix`, or use `Shape.Circle` instead:

```
window.onload = function () {
      let canvas = document.getElementById('myCanvas');
      paper.setup(canvas);
      let path = new paper.Path.Circle({
          radius: 40,
          center: new paper.Point(50, 50),
          applyMatrix: false
      });

      path.fillColor = 'red';
      path.scaling = 1
      
      // Comment this part and it will show the red circle
      path.tween(
          { scaling: 0.1, fillColor: 'blue' },
          { scaling: 1, fillColor: 'purple' },
          { duration: 1500 }
      );
      // Uncomment this one to see it works on animating fillColor
      /*
        path.tween(
          { fillColor: 'blue' },
          { fillColor: 'purple' },
          { duration: 1500 }
      );
      */
  };
```

The fact that `scaling = 0` doesn't work is a bug.

**Comment by lehni** [comment]
[Sketch Version](http://sketch.paperjs.org/#V/0.12.7/S/XZBBa8MwDIX/ivAlKYTgwXIx7NTzoLDjvIPqqKupKxvZoRsh/312D2X0poc+6T1pVYxXUkZ9XKi4sxqUi3PTLnIukLCc4Q2YbnCo5bj34gL1q2UAwdkv2cCrHpp0xIXE3NmEiWQ8RM+ln/QAk97dGUwp/L5jEf9j4IQhk+VtZ9lyMxpPPoR9DFGqZSc0d49OuRFx31askB0Gz98G9Ki1fhngMWagO4aFOtiGJ/SJSouk8I+bF8HiI1dw0ho2yzVU/cVRCC+pnZGV+fza/gA=)

**Comment by l-portet** [comment]
I put scaling at 0 for the example, but my real mistake was to forget to set `applyMatrix` to `false`, thanks for your reactivity!

**Comment by lehni** [comment]
Reopening since `scaling = 0` is still a bug ;)

**Comment by lehni** [comment]
That bug isn't actually linked to the use of tweening. It can be  simplified to this scenario:

[Sketch](http://sketch.paperjs.org/#V/0.12.7/S/ZY6xCsIwFEV/5ZGlCqW0a8CpsyA4Godn+mpD40tIolVK/91U3dzuOcO9dxaMNxJSHEdKehCl0K5bWTuOCTymAXbANMEhx6o1QVvazIoBAnbmHiU0dV2urIkTBQkPQ1P1hY9H7+1rjymYp4QebSTFy1ax4rW96o21rbMu5J0iUFf8fNRoDV+zrf9Mozg/vQTC0TvDKQp5Oi9v)
