### ISSUE TITLE
Inverse skew

### ISSUE THREAD

**Issue by minthaka** [paperjs/paper.js#1823]
Hi!
This is maybe not a real issue, but rather a question:

If I drew an irregular, closed and filled path item, and after this I performed .skew( angleX,angleY, center), how could I make the inverse operation of this. So how could I get back the original item?

The problem is a bit more complex, since in reality I am applying skew on mouseDrag, so I have a sequence of skews, and I need to revert it onClick, all at once. I made a solution which works on regular shapes like rectangle only, but not for an irregular one.

This is basically an Undo operation. I don't know whether it is possible to make it by calculations, or it would be a better way, to save the item before skew's start, and on undo just restore the previous?

Thank you for your answer!

**Comment by sapics** [comment]
Hello, @minthaka !
Yes, it is possible! I think that using `matrix` would be easy way. [sketch](http://sketch.paperjs.org/#V/0.12.7/S/VZBPa8MwDMW/ivAlCYQ0DexS2GnnXtbjsoPqqKuJIwXbawdj3312/jT0YIMsPb/f069iHEgd1KmnoK+qVFq6VLd8QweOdIBXYLrD6YojVe/xAfnLUv5Sl5DOvp6vouU0XV2MtW9ixUVddrao+6zllnc78HgjCAIDBmd+ZoPR0XEq4/Qkn5uVtsKUF5NORnIYjLBfLHxP93w/2a6uXmNkakpoiuQ26S6RQcswojNeuAQD2hEGgqSnLkWZIbZ6pXjYb63nYI667KkbHLK38fe8SQupiwXimzvZEiy0wxr5Eb/luPpzxOtHMRy8Onx8/v0D)

**Comment by minthaka** [comment]
Hello, @sapics  and dōmo arigatō!
I've implemented your approach given in the sample. On mouseDown I am hitTesting the item, and storing its id and matrix in a varible. On mouseDrag I am skewing item, and when it is over, I am passing the stored variable to an undo stack array. So far, so good. But when I do apply the undo functionality:
-- i search for the item by stored item id and got foundItem

        foundItem.selected = true;
        foundItem.matrix = item.matrix;
        foundItem.selected = false;

where the item.matrix is the stored original.
It even detects, that the foundItem.matrix is not equal as item.matrix, but at the end the canvas is not updated, so the skewed version remains, and the original is not restored.

**Comment by sapics** [comment]
Hi, @minthaka dou itashimashite!
I am sorry about adding sample later.
I am grad that it worked well as you expected!
