### ISSUE TITLE
Creating a Path with pathData string results in changed SVG data

### ISSUE THREAD

**Issue by joeveiga** [paperjs/paper.js#1828]
# Description/Steps to reproduce

Creating a Path with pathData is changing the resulting SVG for some reason.

# Link to reproduction test-case

Here is a sketch creating a Path object with a pathData string representing the commands for drawing a letter 'A' shape. (`M 110 28 L 102 49 M 110 28 L 118 49 M 105 42 L 115 42`)

http://sketch.paperjs.org/#V/0.12.7/S/q1bKS8xNVbJSCs5OLUnOUNJRSs5PAfHLEosUChJLMlwSSxIVbBXUfRUMDQ0UjCwUfBQMDYwUTCwVkEUMLaAiBqYKJkZgERBD3TomD2YQ0JC81HKFACBTA2awJlA+Jg/E0ysuKcrPTnXOz8kvAlmXlJOYnK0Olga6KakoNTG7ID8zr6RYySo6thYA

# Expected result

Here is a Plunker rendering the same path data in plain HTML SVG object.

https://plnkr.co/edit/wsOlJ2ely1VcqRKm

**Comment by joeveiga** [comment]
Found the problem. Should've used `CompoundPath` instead. That worked.

**Comment by lehni** [comment]
You can use `PathItem.create()` and it'll figure out the correct constructor for you:

[Sketch](http://sketch.paperjs.org/#V/0.12.7/S/q1bKS8xNVbJSCs5OLUnOUNJRSs5PAfHLEosUChJLMlwSSxIVbBXUfRUMDQ0UjCwUfBQMDYwUTCwVkEUMLaAiBqYKJkZgERBD3TomD2YQ0JAAIOVZkpqrl1yUmliSqgEzXxOoLCYPxNMrLinKz051zs/JLwLZmpSTmJytDpYGOi0JqC27ID8zr6RYySo6thYA)

**Comment by joeveiga** [comment]
> You can use `PathItem.create()` and it'll figure out the correct constructor for you:
> 
> [Sketch](http://sketch.paperjs.org/#V/0.12.7/S/q1bKS8xNVbJSCs5OLUnOUNJRSs5PAfHLEosUChJLMlwSSxIVbBXUfRUMDQ0UjCwUfBQMDYwUTCwVkEUMLaAiBqYKJkZgERBD3TomD2YQ0JAAIOVZkpqrl1yUmliSqgEzXxOoLCYPxNMrLinKz051zs/JLwLZmpSTmJytDpYGOi0JqC27ID8zr6RYySo6thYA)

Oh thanks, even better!
