### ISSUE TITLE
Cannot set size to image - raster

### ISSUE THREAD

**Issue by egenge** [paperjs/paper.js#1835]
Hello,

I notice that it seems imposible to set height and width to a raster when source is specified.
Also, when i try to access the raster size is always zero.

```
const raster = new this.scope.Raster('http://assets.paperjs.org/images/marilyn.jpg');
raster.position.x += 50;
raster.position.y += 50;
```

first try - not working :
`raster.size.set(new this.scope.Size(40, 40));`

second try - not working :
```
raster.height = 40
raster.width = 40;
```

third try - not working :
```
raster.bounds.height += 40;
raster.bounds.width += 40;
```

another try - not working :
`raster.bounds.size = new this.scope.Size(40, 40);`

I tried many other ways but still not working cause the size (width and height) is still the original image one.

We also have this when i thy to see what's indide raster :

**console.log(raster)**
![image](https://user-images.githubusercontent.com/54799316/85605520-8600e300-b652-11ea-983e-5a7c02cfb9cd.png)

**console.log(raster.size)**
![image](https://user-images.githubusercontent.com/54799316/85605789-cbbdab80-b652-11ea-83b0-d709d1c7158d.png)

How can i resize images ?
scale is not useful for me because we have differents kind of images with differents sizes, i want them all to have the same size no matter their original size ...
I could use scale, but i do cannot access raster.size (it's always zero !)

Have a nice day !

**Comment by lehni** [comment]
You probably need to wait for the raster to load? This works for me:

http://sketch.paperjs.org/#V/0.12.7/S/hY/PDoIwDMZfZdkFSMiIngyJb+BJjuJhQoXxp13WGaOEd3cIB2/20PRrm9/XThL1CDKXRQ++amUqK6oXXRGyF06zByeOAuEpzl8RR633Ns8yzQyeldUWXMeKXJOZUTfA2aidGV6oOttESYkrRBGeSNeBdX9g5Q1hnIipRBFiMaMB1EBNvG2zeUOyTn862yVFKOPd/pCKkJJ/jDl8dXOge0sGPcv8cp0/

**Comment by egenge** [comment]
thanks a lot !
Have a beautiful day ^^
