### ISSUE TITLE
Animations appear to run faster in different browsers - onFrame firing more often? 

### ISSUE THREAD

**Issue by CarlyRaeJepsenStan** [paperjs/paper.js#1847]
#883 Description/Steps to reproduce

This is a recording of my animation running in Opera (version 69.0.3686.77)
![adsf ](https://user-images.githubusercontent.com/44917034/88699140-d1783800-d0bb-11ea-8d12-c48f1f3d0059.gif)

This is a recording of my animation running in Safari (version 13.1.2 (15609.3.5.1.3))
![asdf safari](https://user-images.githubusercontent.com/44917034/88699189-e228ae00-d0bb-11ea-9517-838501ab76a8.gif)

On Microsoft Edge it also runs rather quickly.

# Link to reproduction test-case
http://sketch.paperjs.org/#V/0.12.7/S/ZVPBjtowEP2VUU6hUAfS3UPDcmrVU5Eq7aGHDQfjDMQl8SDbgaJd/r1jJ6Ds9hA5fs/zPPNm/JoY2WJSJM8H9KpOZomiKuxP0oJstHSwgqOlP6i8kMrrE/6UF7RC1bqpLJplaUqTZeC8tB5qtFj0iJWV7lzO4dD/LrKFeITPsKXOVFjBFv0Z0UA+B0+wmIewXWf4DjKgLEqPzyyaHkkbP4siegaKGrITeC0NQMjxcOk6vsPgGX5JX4sYElkAhcajLaBX6DHnLR3wW1AperF3xG9d+bqAfABjpCvgYdgPlRRDNmMwH0DIIA/4dbIMS8hPuJbI12lArqHM0niiRrTafNdsnFHIJeSPg5e+RkBryYJ24KjFc7AVtAFfM7JtSB2KkVdkflhuYoonrnewZsfRafBHs/J8yctT307RoNn7mpHpdDgLPfOiN8KSZ9vTxbxPfsQ4JRtM5+Lrf8yRnA55iAtMuYqB1jtI70diy504B3PhaQVf4O0NPrI16n3tI31PbJwatnTC9HY9QJbduFUYqJ02WA3kNTaAzeZDaKresrvtZNbUOVyzHJtzs/GdfcE57ibT6zBUVpqK2nQCn+CBzcyyMG4BBNO1W7TAsfYCUQF22mIVREYz/BIpEcdJ/J3BeHvZxOGeQZkQa+6xTOKg8MfPccsih34Mk+Jlc/0H 

...sorry for the super long Sketch link.  
The star animation similarly runs overly quickly when used in Safari. 

# Expected result
I expected the animations to run at similar speeds.  

# Additional information
I am using macOS Catalina 10.15.6, and my version of paper is the latest (as provided by a bare unpkg link).  
I am also hosting on Glitch (folded-paperjs-test.glitch.me/home.html) , but since the problem appears on both my site and Glitch I don't think its an error with my hosting service.

Thanks in advance for helping!

**Comment by adasek** [comment]
Hi,
I think this behaviour should be expected with `onFrame` event. Different browsers/platforms may use different frame rates (according to display refresh rate and performance scaling).
See [documentation of the underlying requestAnimationFrame method](https://developer.mozilla.org/en-US/docs/Web/API/window/requestAnimationFrame).

You should take care of your animation timing yourself, for example
```
var lastFrameAt = new Date()
var rotatePerSecond = 10
function onFrame(event) {
   newFrameAt = new Date()
   elapsedTime = newFrameAt - lastFrameAt
   alias.rotate(rotatePerSecond * elapsedTime / 1000)
   lastFrameAt = newFrameAt
}
```

**Comment by CarlyRaeJepsenStan** [comment]
@adasek Thanks.  I did some timing tests with `new Date().getTime().toString().slice(9,13)` and it turns out that Safari fires onFrame twice as fast as Opera.  I rewrote the onframe function into a setInterval function so the behavior is the same across brrowsers.

**Comment by arnoson** [comment]
`onFrame` or `requestAnimationFrame` is still prefered over `setInterval` because it will result in smoother animations. Closing this issue because it is not related to paper.js.
