### ISSUE TITLE
Error with npm and paper jsdom

### ISSUE THREAD

**Issue by NoZ4** [paperjs/paper.js#1853]
using npm with visual studio on windows 10 machine
all versions above 0.12.8 give me this error

Microsoft Windows [Version 10.0.17134.829]
(c) 2018 Microsoft Corporation. All rights reserved.

C:\Users\Noz\source\repos\PPP\PPP>npm install paper-jsdom
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported

> paper@0.12.11 preinstall C:\Users\Noz\source\repos\PPP\PPP\node_modules\paper
> [[ $npm_config_heading == 'npm' ]] && npx npm-force-resolutions || true

'[[' is not recognized as an internal or external command,
operable program or batch file.
'true' is not recognized as an internal or external command,
operable program or batch file.
npm WARN ppp@0.0.0 No repository field.
npm WARN ppp@0.0.0 No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! paper@0.12.11 preinstall: `[[ $npm_config_heading == 'npm' ]] && npx npm-force-resolutions || true`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the paper@0.12.11 preinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Noz\AppData\Roaming\npm-cache\_logs\2020-08-24T13_59_32_372Z-debug.log

C:\Users\Noz\source\repos\PPP\PPP>

**Comment by Welchen** [comment]
@NoZ4 I'm seeing the same issue with 0.12.11 under the same conditions.

**Comment by sapics** [comment]
Duplicates #1833
