### ISSUE TITLE
Position of raster in loaded SVG changes after loading

### ISSUE THREAD

**Issue by RickMohr** [paperjs/paper.js#1859]
[This sketch](http://sketch.paperjs.org/#V/prebuilt/S/lZdpk6pIFob/ilH9pXuskn3zdk8E4oIKgoqKzu2IYV9kTRIQO/q/T2Ld2np6PowRj0mePOfNBDKJc/54yqzUexo/7a8edMKn5ycnd/t+Y4FB1QSGd4OD3wb//g6+Z7+ift8OBoNbmmTV2HV++/4UQliMMayoQTLKQYC5DuYlXuplsMKIEYF9f/oS43yKcYBnwajxnDxN86x6hGfVT3+JAK7/EdK27ailHp6EIAgYTmIk+YJcXqoug9bt5b/j0ar/Np7EcRzrb+mL+//hOr4lUXb932t7DP91MbkbFYiPqDfLqMpr4Hg+CvdGmQexqTF9H3zBRy50/6KF1CvHKryvK3izvj5N9HKrwnK8Cnuzv4u8aY/d3On9kEwVpUXijT7f6VvYuPFAFeUZ8iJG+OBnGqcYi/ZtWngekDiJv+DMC0788hHn9npNwDP4u+2zBPFhjbx2kt+QFR/gA5JACNz7aOhFQQjRIDKm6bu5jVwY9lYC763/fDX/+rY/f8yfWJ0HPmb6dDcByOsiRVv9zevvnBLL9hLkoPQOA+J9GjRRlFqB9x7xY7qHkaBJ6pMYeln9NhiHwOu3sWtBa/zww4os+GZblcfSz9Fxou1afL0IchH9NvtDODsE6GrWdyeiJKqolVxIy1VvEamNtD9ul5IY2/QB6z1FyZwsT6Yq9jOL4oLrA+t2xnKaHvXjC3M3P8k7wyYvuEvOu8t2QrmUU1snBjjkJnQWh9qmVlk6pPlFr5i6W2O+m/d6GPqJa4CJaHhugVKy5Fham97UskOpNBB6hNoAtQjDl9geM0AtQn8wXSM/1O/1PuxvPsYn38/tKyg2mFpmMC0RKGa2tsMZmntW2mGvN2P9cL5GWHE4LxFsFi0sRAmiBQsieY2wmkhmm3i5vsdLC1FS8ZKl4tUaUXLxeo1d1xZ27fXWJXZVlOlVseWrAhCckqg2AujJxjaSDUBwRqopZqrZCIDg7FRXELaf6gDB+dlWibNebwvibMeBfG83+R7c8z13zw1AFQeFKw42AnDFUcGKkyqXJwdRKeWJV0qT18FZNcDZQVQI3gS93qWyK0v1K8tBVH5lq3FlO4gqgzafQadqoMM30FUR1b12+XvtOVTt8VztqwgHUWGNz2NNrxe40yaA0yZ0ZYTShhAhKG200dFBQ0CEYLTxBuGatxgiBPN23di3q4uACMG/pZu46/VSN+tSiBBAl7nNPROae+7e7zlECNS92CAgh5cuhpcQw4E2xYE3JUAtE5WG8BSiqhUC1gbZ69WaSdYeYmiTzdCnWg1Rx1Q7zKibhvAy+lYD+jYEdKchvIbuasTwTt+1O3OvKQYfYgyhYWyvRzRTlsCmLKkjfJklGwQms5SucBSmc7RucLSPaBCYyTG+yTONzTOYzbM6wvd5Fj09rsmEXo/XM4H3gcA3CAwIgt4MBR/R3IcCdh+iJQ+HDQLjMCSPYT6iwR6/Tarzh7Y/rQx+uDLG6/lV19NJ5euzm3ZOd7kj79dxuW8h4MROMM+MB7qhng1tX52x/VkdTla72fxwUjV4JF17hs+2+nUbFOFs2uvl2ytY6rZXnAO3ZlfRdjfnJvxp3fje2rRFcz6DFTmp14tK4nUeuHW7u3u3mtFVl0+dK68yGvpsJJQbHYrH+V2ebCBfZEO+7Q9Zp7YkTYSHKjwca6VqN7vD1ssKi/C4+5k8tvnusAQKcbVkjwmYYLtPJvLmvMeYnePtsV5vPvEJE/OWp80yuh3OM4EW1NU0z1VjffY5eM3zek/SKZjjBH7g9kGSynC/jQ9mWIVpvpvhF8Dvz/GM2M8e+09zt2JnlfdoFlyXx010nvIzlhmqlJbNC69e80210roy8GnTo7YVaK5aqNNDcgrP1kZ2iXQdYzXZlReWe3zklSGnG4c77R/i+8KUh9V9q2CafxJzykTPm8qzVXkv81LBJuEyFa5CRWJnmaFwjB9q9514PbpznVzWuoCvez0dBjhXp1mw82NNO5wW0ULHhewqSswmkHURGLRl7zJ0DjX2ot8NeuN2uVRMU8JmD6SIhdRSXXUkTzuh3+uVOkUZZDrlq7NurMw560jN9lTYUksFjLg5tENd39gm3V0FMsxJfRMreoRLDAkvK/6CTW1mqcu6t0pNf9frGVM954i5OD37JH1ZrzBatK1JlO6X8LzkaP5krvNrowyBmG94WUEq6yrT+TO9bNF3dlMTtNNaxh0uk4zo9aZqaKZElWg3N1iyU3zfyrDYEWvhcpYI0ghnYLK1T6wpzzsxJePyZka6y0/IbEi31Vw9dflsD+1kGtXzRa+HLzUZQ7mp2xwKa48rl9MsqWYXKHf6vLwdcMrW1Ck7NVR+mLF4pKR7QtHoxcVqIL0+pDBfXf2z3J4Omm/2esx2iWlVsZ9cpAResUjs2gURa0PJDgxV3FFz7zrRFwkvSux86ojdLeKnO6xjF7UUHUrRdybqcGKxS4ue73u9W8JPLgZzXPod3J5qOsQmc2bJ3HQg6bwJ8WV43HA4j7fT+cVda+gLtpQpPDYCWVOzVuT1S7wV7pzTzuaP96sY9j0+YdmJui75FXeb+LvGoM6pddz49Aw/Oau63OcTnfKv4rHCW30770g3M2R0sLDLyWNSo5tZAY9NCrrXy0pisrhs0kxKHTtV+RtLqrxV7Xh47cq6K3jLj++ivj5JWMks5ByWNdsAq4y0Gbs2C8cnBWpr5SemaKVeb69UIrc5CUsJlw4qUYSyRxoZfzlOT61RNoJ9WQ9Fibud42R+xKMbCESSPwFFmwmKnx3xQLpQu87bNeTwsV+kiw2GMX+4k+yBgfKCu+SCuzVhZKSRqNkBS1HSxjNztEkOWHq6tYrANNuqWaw0vWmsJlzxx0pYzeXb9PjYL+Ex89TFvkrMe5Hu0kiqziRTmoqqm7qmmoa3MU1PM21HN31P1ePkQvNhiLmTBBOAKbWCTuOcc5Th8JFv6D7Kh0C+CpZcCCY698jJZsncuO7rbSo9nsmXHLAAXuWBxhOrwnPgDlU9OUoGszzzvri9J7sEzY04nuC/ZpJvSe/fj94eSfKI5WiGJb6MdGiEoUY8y+D096cB9pHGFhYM/5rF9jaUxHJfJPqBdMAyI47leIZ7Jjh+ROM0xw54YsTSJM9Qzy/EiCEI4UtcBbukz7H9PIMvqKaM+lvPXioPwigLqnGWg9RKvuWoRolgNya+oWoQ5uDF8310Me6f0Dc/SpKPq5cP3wqC/OqNf/J9VJ/hP7ovj6c0pt+6KPv2UDY/tmsIP9viPMrGaQQ98GZ9dJIINR/RrlWFFgBW97qAT9bc99FdjN+n/bysvHhx8iQH459w/MfSkOnd49M7+BULHle/9uXl4+pRavf8qMBR9V2APEZPY4SqsxzA/XHx84/K/HnwB6pW0M6C44FvJZU3+POXb32sg8rpHFVySR70viMnsapqg4q81+Fe+lGEIPHHcBglLvCyfxG/f1zjv397WwqS0fMq6l/dz68K6NaNKPXyGv78afB5gP/yHuTXmdMbB1+iB3+87Y7Pa3wsZlT88HrV+PNNCPvHwAi9AZqrqOG4t/wxuI0H+POgQ/+DP98tBE6NGJah+ccIQaJTwjAC++rxj0em8fT8ZAPPuhbo7cPqafyv3//8Dw==) shows the issue.

Here's what it does:
1) Load an SVG file containing one raster and one path. (The SVG was exported from Inkscape, and simplified.)
2) Log the raster's position.
3) Set a JS timeout which logs the raster's position again.

Expected: The positions are the same.
Actual: The positions are different.

The behavior is the same when loading the SVG from a URL with the onLoad option.

I'm using paper.js version 0.12.11

**Comment by RickMohr** [comment]
Here's [a simpler sketch](http://sketch.paperjs.org/#V/0.12.7/S/bZZps6JIFkD/ivE+1TQVxb697p4IZBEEBAUE7eqIYd8EZFcq+r9P4qvqqZkYIo4pN+89aWgm3m9vtV/Fb+9vVhkPYfb2+S1sovV+8rtNP6V2/Bg2v2/+9bX7Wv+Wbh7Vre5///qWDcP9HYbnef4y41+aLoUxBEFgUPD17Z9r7mbzW175abz5uAHXA5ShyNe3vwPP/w285O91j/7fBVCWZeHHLa/Ln0pA8nvWxQmoiPzBf3+tCd/r9NfA72OK+Lxm5uetcZoRdZc2HLgOlpOJTgreievtluM5HYx8NBByv0Y4/MBb56PCc0VAOPCayfHeVnE9nVt9HLej18JxFinaMPN1fuedJFc+2QF2RSJMel6PWzzCw9F3yS7EDlm4c8YA39cVRDC71VhFR1s6SasPBhendjAHpiW/a3lfLnjViwU/yPjWBpg5GFMwAuyEp1a8FIwA84Wggjxwv/r+E/+RY/+U+/P4AahNBd9LhRYAakQ1yESwttgG2eoTqSSTVIBfZFILoOp85wPaLt9RXS6rAH/KZWoqFHUpFB/Q4oVC4cVeBbR0oapwqfpwufrUFi41TSi1QC61DkBrNz0AdObtENi3Qweg7crQvMoIAB2ADipTAwRJZXYAOqmPWlGvvmNX1Ce6a6xgaqxuaSx6aewOvzsafXcCQEffzxp8d3W5dUNAr7Uuo7UeY3YX3e4uIaAHMF63+q590Pt60vshoE/6QC/6IAT09RAw9RD20xAy0xDpgH4ZI2YZ4xAfY4YeEx0QAnp4Shh4Wn1pJEzpIExZJAO0ORsArDbnB3POI8AAYO25OAAi71EMANZ7lIfgUUaAAcAmj+pQPFdfFdXPagCw3bOOpqVmp6WJlqUZACy+3A+AgUbaCEbaAUY6Q0C6WEC7UUZ7AxBraD9q6DDa2OobDQ8bYwAUYBOU4LMBGAt8hmr8YQDimniMHfGAOuJpAOKJeI4AaCEWYyGXEScRCCZRA6ZWHzoJFAoLFGYCEpnCJgAsU7ip0Ths0oRp00QCmACwR5OJx5BTwJBwwFAmIEkYCnx79FSzq48xa5ZJOpaZAHDHsuYEsQlgWiAWXiDwkSFoAsA0DPQwnAAm+HUdKpNx5vW0kohTkvbH+dVVYdsnpvgwLtWpCWVLLVprHjqae7LehYy7J2TWUJDoIrWeVWi7P4mS4+rGcMaiQETEo1ke03smCquvOZadYgbx/ZJGI7XPjyeJ3jKuOiWx6gWcJ4lDj21HddfzjMl00TiflvgxkqYeMVVYMjppgMfGDY9y5/46v4obdPJVtuWH5dRPfcYINHP6zDmPWj8fTs4xru8+GtPLBTvPzclROg0tfTkmUzI9WretfLhYMHkKYwtefdI2QT04VtyDkj+ci8gSrL4Xmka31UtCD2XTjBZGVJ2EoIhDW+mtkgfrWDhe1mdVcxKRa8dYl0JELfG1/4zoyD39dsnFtFTOh/wiMCJFQjpu1NI9HlVm6vfGs00TwovxY99NpZGZBIQJw8U/yBFaqQU8Ys/2StHx6tMg2rSdhUicYtl5MtQvRw02EpdrcA9833hT79ulbVoN3mZKxZZsj8EXmcQRmIGM5cSV50gyMWU0WURdfeaQIvRY1ekpKQzDcXf5zkTYuuR48pDKJtfZhB+canAODepqLjZxiJ4NfxcqNKAcjIMzXNH3T4whwixZfa2J4zZWCUx/Me29J1EhPx3de8DPeEpyB2eGTPMQeMSzZLGswcxDoZk5wpPYcN0zV1gISMWUzXhfeclp9dmC2dCoxAmXBCOu6h4muMDf5pWlDBeFJhjXU5ty0qCOaw6MrAGL2tcmcyGUGTxnDyNKhLNvL4Nyq9HVJ+iZV6H9zXhEqUIJiDXLw/2Equz1wqOYnYnd9hi4lCdLT67Civbh5WbEbLEaIuZe0t1nI1pDcBPyUdqtPkQxZBj880eTc/ctRLu64q0Xr4P8NKX24SB4YOgCJdg6A9UUkmuVhWoGsbv600CoTjU0+zK5yLPrGIm3+sijAhv93dpe+dtQwjn3nHdoYUB8kNo6d8KluNyauxvD8ZQkhNzzkTPCCX5Su5HPnZZLwq0ObX1K8QnJWn2PG7O92uRZSZ7D0R2JDN5KpEI+zI43GW9AlOx8oBEGmQXpGqkGeIIpMo4Udiobej1zjHktjuxCh7MovX5fzQ6WwoVrFy8VZk8/tslpsvFL5Z8PCSEibrgfW6vZmnhScucemc2j9MSi2pbBwYKvbkxW9lP0Uwbe3onVV7fodnc9VDVfhUGlMw8K0xm/PzFD+WzH553xk2LhTNXl4Zbcyc3QjtTU+W1uiJTq3cMEY/Gj37jkfeZXn6X1HH1wWYVHeEdH75kcY3bNXM+CO9vtxAZXFeJ4+nEpbtIZyR9dymGM22mGyGpJfUZS/oqfnvFpwqDXfuGvQQcVjLNglEMO8o6+Nmx09IbcrnLOCFIKx/lD7DVgkzhw5T5mjSWnYz/t9oY5Tf6U7Zlzz+4l+SGcX/slO9exvrP6m7fcq1OV8/0FI1tP003PNHTPjg+eFxteEJpeEutmcbsSTJbB0fYGs53Hz6xJIHR4lgfo1W+YCeiHumafKnTWbU361ZOJN8kurfFY8fxH/we/+szf4PQ1vhrUle99K+hZ711TxOHwJa/uTTdY592n7/3sP379kfjRov6+FnwJs/wWdXH9B/Lna/7WpGbT50Pe1J8+Kvp4sPMqbsbh00+TnzfIx/RKMtbhGtz8V/Xm24+GNWzqvrnFX8D0p9fiX+7fsz4cf/0Qwb9s7CzegLXu4/C+Rr5tHu8b5PPmCV43f/0dQT9C6PfYL68nPmjjgy72y3uT10P/9v7Hn3/9Gw==), where the simpler SVG has just a single image.

**Comment by RickMohr** [comment]
I believe the position is correct when first loaded, and incorrect when it changes.

**Comment by sasensi** [comment]
Hi, thank you for the clear test case.  
This is actually not a bug but a consequence of the fact that images are loaded asynchronously. Your first log is done while the image is not loaded yet (so the position cannot be known).  
This can easily be confirmed by checking the `loaded` property of the `Raster` ([sketch](http://sketch.paperjs.org/#V/0.12.7/S/bZZpr6NGFkD/ytP7ko5oNZidTjISZjGYrWzAxk5HGvbNgNltovz3KfySTM+CdFxU1b0HhKvg/v5e+1X8/vXdLuMhzN4/v4dNtPYnv3vrp9SJH8PbL2///NZ9q39O3x7Vre5/+faeDcP9K4rO8/xlJr40XYriGIahMOHb+z/W2Le3n/PKT+OPc3g8YNYG+/b+98Dzvwde7q91v/m//g3Hcejjltfldykw+GvWxQnMiPzB//q6JHqv058Cv49p8vMamZ+21nHGtF3a8PAwbTeT3BSeSWt3ywu8AVshGkilX0d4whTs00EV+CIgXXSN5AVvq549g199PL9j1sRxlmjGAvk6v/OO8lk5OgF+xSJcfl4PWyIiwtE/U12Im1m4c8eA2NcVQrK71VhFB0c+yqsPhQevdSgPp2W/awVfKQTNi0U/yITWgYActilsIU4i0CteClsIeCFqMA72V9+/x/+Kcb6L/b79AOamou+lYguBOZIWZBK8ttQG2eqT6CSTNYhfZHILoet850PaLt/RXa5oEH/KFXoqVG0pVB/SEoVKE8Veg7RMoWloqfloufq0Fi11XSz1QCn1DsLoNyOAdOBmBs7N7CCMU1m6V1kBpIMwQQV0SJBUoIMwSX3Qi3r1HbqiPjJdYwdTY3dLYzNL43TE3dWZuxtAOuZ+0tH72VDacwjp9fbM6q3Hgu5iON0lhPQQ1utW37UPet9Iej+E9EkfGEUfhJC+HgK2HsJ+GkJ2GiID0i9jxC5jHBJjzDJjYkBCSI9OCYtOqy+NxCkdxCmLFIg+ZwOE0+fcBHMeQQYI58yFCYm8RzFAOO9RmsGjjCADhEselVk8V18V1c9qgHDds46mpeampYmWpRkgHLHcTcjAYG2EYu2AYp0lYl0sbrpR2fQWJNY3/ahvhtHBV99oefgYQ5AAn5CEmC3IWBAzUhMPCxLX5GPsyAfSkU8LEk/kc4QgC7lYC7WMBIUhKLWxUHr1bSaR3qAijQNIotD4BEEVmgA6Q6CAIYHDkAlkgqAeQyUeS00BS6EBSwNIkrA0fHrMVHOrjwU1xyYdx04QtOM4MCFcApkWhEMXBN4ygkwQlEGhHkUTyIS+DrMCrDuvu5XC3JJyPvavoYnbPgHSw7pUxyZUbK1o7XnoGP7JeRcq7p4IqJEgMSR63avIdn+UZPdsWMMJjwIJkw6gPKT3TBJXX3MoOxUE8f2SRiO9zw9HmdmyZ21KYs0LeE+Whh7fjtquF1jAdtE4H5f4MVLAiNgqLFmDsuBr40ZEuXt/7V/1HHTKVXGUh+3WT2PGyU3m9pl7GvV+No/uIa7v/iZmlgt+mpujq3b6pvSVmEqp9GDftop5sVHqGMY2uvrkbbLx0Fg9m2r+cC8SR3LGXmwaw9EuCTOUTTPaOFl1MrbBXMZOb5Uy2IfC9bI+q5qjhF071r4U0saWXuvPig7802+XXEpL9WTmF5GVaAoxCKuW7/GosVO/t55tmpBeTBz6biqtDJAILg4X31SiTaUV6Ig/2yvNvD4POsIAx13IxC2Wnacg/XLQUSs58w3hwedNNPW+Xdqm1dFtplZcyfU4elEoAkNZxFqOfHmKZICrI+AwbfWBIcWYsarTY1JYlnve5TuAcXXJC5SZKoDvHNIPjjXchxZ9BYtDmtGzEe5itQloF+fRjFCN/RNnyTBLVl8LCMLBK5HtL8DZezIdCtPhfA+EmUgp3nRnBAAz8MhnyeFZgwOz0EGOCRQ+XPfsFRUDSgUKiPeVlxxXnyOChtnIvHhJcPKq7VGSD/xtXtnqcFEZkj17WlNOOtLxjckqOrRofQ3YC6nO8D1rjhsynH1nGdRbvVl9opF51aa/WY8oVWkRs2dluB83Gne9CBvcyaRuewjOtKfIT77Ci/bh5SBit3iNkHMvG+dnI9lDcBPzUd6tPky1FBR++KPJvfs2pl/P0q2XroPyBHL7cDEisAyRFh2DRWoay/XK3ugWubv600BqbjU0+zK5KPPZtRJv9VEHFbX6u729CrehRHP+Oe82hYUIQeoY/JGQ43ILdjeWF2hZDPnnI2fFI/qkd6OQuy2fhFsD2fq06pOyvfoeN3Z7daiTmjyHw3kkM3QrUyr1AJ0AWG/A1OxkMhiLzaJ8jTQLvsFUhcAKJ1Uso555FlyLA7cw4SzJr/9Xd4KlOKP1mShVds88tslxcohL5Z/MhJSwc7gfW7vZAiIp+VOPzeAgP/GodhS4sdDrOaYq5yn5KYtu7+Tqq9vNdnc1q1qowqAy2AeNG6zfH9mhfLbj8876SbHwQDsLaEvtlGZoR3rq/Da3JFrz7mGCc8TBb87UfRZWn633PGOeOVXABNfY3DMlxp2avZ7E8+y0ExdcNYQXmMeluMknLH90KY+z5063JE5P6hOWClfi+IyPE4681otwDTqkYN0Fp11qUHbMteGigzfkTpXzVpDSBCGYsdfAReKi1fkx6xw1Hfppt7fANPlTtmdPPbeXlYd4eq2X7FTHxs7ub95yr45VLvQXnGo93QAesAzPiU3Piy0vCIGXxAYobleSzTI02t5QrvOEmQMkxoQnZUBe9QZIYD3UNftUZbJuC5hXTSbdZKe0x0MlCB/1H/oqM39G01f7z5/W35U/61ZYs967pojD4Ute3ZtusE+7T3/Wsz/+9Ffgq16EoXDiS5jlt6iL61+x3/6W3ZoUNH0+5E396SOrjwcnr+JmHD59N/n5Dfvx76RkrMN18O0/st9+/6tqDZu6b27xFzj96Ydb40dx9MPnj1v58tH9cP1P7P1P2d/Rfw18xP+x/sACPuhiv7w3eT30719//e2PfwE=))

The way to go if you want to work with the `Raster` position, is to wait for the image to be loaded. You can use the `onLoad` property for that ([sketch](http://sketch.paperjs.org/#V/0.12.7/S/bZZpz5vGFoD/SvR+uamoAmYnXSTMYjDb2ICN3VQq+2bA7DZV//sd/CZp74L0eJiZcx4QnoHz51vtV/Hb5ze7jIcwe/vxLWyitT/53Yd+Sp34MXz45cMfX7ov9c/ph0d1q/tfvrxlw3D/jKLzPH+aiU9Nl6I4hmEoTPjy9usa++HDz3nlp/H7OTweMGuDfXn7PvD874GX+3Pdb/6vf8NxHPq45XX5jxQY/Dnr4gRmRP7gf35dEr3X6U+B38c0+eMamZ+21nHGtF3a8PAwbTeT3BSeSWt3ywu8AVshGkilX0d4whTs00EV+CIgXXSN5AVvq549g199PL9j1sRxlmjGAvk6v/OO8lk5OgF+xSJcfl4PWyIiwtE/U12Im1m4c8eA2NcVQrK71VhFB0c+yqsPhQevdSgPp2W/awVfKQTNi0U/yITWgYActilsIU4i0CteClsIeCFqMA72V9/f499inH/E/rN9B+amou+lYguBOZIWZBK8ttQG2eqT6CSTNYhfZHILoet850PaLt/RXa5oEH/KFXoqVG0pVB/SEoVKE8Veg7RMoWloqfloufq0Fi11XSz1QCn1DsLoNyOAdOBmBs7N7CCMU1m6V1kBpIMwQQV0SJBUoIMwSX3Qi3r1HbqiPjJdYwdTY3dLYzNL43TE3dWZuxtAOuZ+0tH72VDacwjp9fbM6q3Hgu5iON0lhPQQ1utW37UPet9Iej+E9EkfGEUfhJC+HgK2HsJ+GkJ2GiID0i9jxC5jHBJjzDJjYkBCSI9OCYtOqy+NxCkdxCmLFIg+ZwOE0+fcBHMeQQYI58yFCYm8RzFAOO9RmsGjjCADhEselVk8V18V1c9qgHDds46mpeampYmWpRkgHLHcTcjAYG2EYu2AYp0lYl0sbrpR2fQWJNY3/ahvhtHBV99oefgYQ5AAn5CEmC3IWBAzUhMPCxLX5GPsyAfSkU8LEk/kc4QgC7lYC7WMBIUhKLWxUHr1bSaR3qAijQNIotD4BEEVmgA6Q6CAIYHDkAlkgqAeQyUeS00BS6EBSwNIkrA0fHrMVHOrjwU1xyYdx04QtOM4MCFcApkWhEMXBN4ygkwQlEGhHkUTyIS+DrMCrDuvu5XC3JJy3vevoYnbPgHSw7pUxyZUbK1o7XnoGP7JeRcq7p4IqJEgMSR63avIdn+UZPdsWMMJjwIJkw6gPKT3TBJXX3MoOxUE8f2SRiO9zw9HmdmyZ21KYs0LeE+Whh7fjtquF1jAdtE4H5f4MVLAiNgqLFmDsuBr40ZEuXt/7V/1HHTKVXGUh+3WT2PGyU3m9pl7GvV+No/uIa7v/iZmlgt+mpujq3b6pvSVmEqp9GDftop5sVHqGMY2uvrkbbLx0Fg9m2r+cC8SR3LGXmwaw9EuCTOUTTPaOFl1MrbBXMZOb5Uy2IfC9bI+q5qjhF071r4U0saWXuvPig7802+XXEpL9WTmF5GVaAoxCKuW7/GosVO/t55tmpBeTBz6biqtDJAILg4X31SiTaUV6Ig/2yvNvD4POsIAx13IxC2Wnacg/XLQUSs58w3hwedNNPW+Xdqm1dFtplZcyfU4elEoAkNZxFqOfHmKZICrI+AwbfWBIcWYsarTY1JYlnve5TuAcXXJC5SZKoDvHNIPjjXchxZ9BYtDmtGzEe5itQloF+fRjFCN/RNnyTBLVl8LCMLBK5HtL8DZezIdCtPhfA+EmUgp3nRnBAAz8MhnyeFZgwOz0EGOCRQ+XPfsFRUDSgUKiPeVlxxXnyOChtnIvHhJcPKq7VGSD/xtXtnqcFEZkj17WlNOOtLxjckqOrRofQ3YC6nO8D1rjhsynH1nGdRbvVl9opF51aa/WY8oVWkRs2dluB83Gne9CBvcyaRuewjOtKfIT77Ci/bh5SBit3iNkHMvG+dnI9lDcBPzUd6tPky1FBR++KPJvfs2pl/P0q2XroPyBHL7cDEisAyRFh2DRWoay/XK3ugWubv600BqbjU0+zK5KPPZtRJv9VEHFbX6u729CrehRHP+Oe82hYUIQeoY/JGQ43ILdjeWF2hZDPnnI2fFI/qkd6OQuy2fhFsD2fq06pOyvfoeN3Z7daiTmjyHw3kkM3QrUyr1AJ0AWG/A1OxkMhiLzaJ8jTQLvsFUhcAKJ1Uso555FlyLA7cw4SzJr/9Xd4KlOKP1mShVds88tslxcohL5Z/MhJSwc7gfW7vZAiIp+VOPzeAgP/GodhS4sdDrOaYq5yn5KYtu7+Tqq9vNdnc1q1qowqAy2AeNG6zfH9mhfLbj8876SbHwQDsLaEvtlGZoR3rq/Da3JFrz7mGCc8TBb87UfRZWn633PGOeOVXABNfY3DMlxp2avZ7E8+y0ExdcNYQXmMeluMknLH90KY+z5063JE5P6hOWClfi+IyPE4681otwDTqkYN0Fp11qUHbMteGigzfkTpXzVpDSBCGYsdfAReKi1fkx6xw1Hfppt7fANPlTtmdPPbeXlYd4eq2X7FTHxs7ub95yr45VLvQXnGo93QAesAzPiU3Piy0vCIGXxAYobleSzTI02t5QrvOEmQMkxoQnZUBe9QZIYD3UNftUZbJuC5hXTSbdZKe0x0MlCO/1H/oqM39G01f7x0/r78rXuhXWrPeuKeJw+JRX96Yb7NPu49d69oefvgW+6kUYCic+hVl+i7q4/g37/bvsNf+pqfXGj2DYxx8+/PLrhz+/lZ+3JgVNnw95U398d/71PTMZ63Cd+M+gv3PDpu6bW/wJTn/81w3q4+hfP77fz6f37rvxf2LvX2Xfo78NfL2D9QdW8UEX++W9yeuhf/v82+9//Rs=)).

**Comment by RickMohr** [comment]
@sasensi thanks very much for your comment. In my actual code I'm loading the SVG from a URL, with the `onLoad` property. When the `onLoad` handler is called the position is X, but later after relinquishing the thread the position is Y. I tried to make a sketch of that but couldn't get the image to load. I saw somewhere that CORS restrictions could prevent loading a remote image in a sketch. Unfortunately I don't have rights on the server to permit cross-domain requests. I'll keep trying.

**Comment by sasensi** [comment]
@RickMohr, from what you say, I think that you are waiting for the SVG to be loaded (with the `onLoad` property of the `project.importSVG` method) but you should also wait for the images contained in this loaded SVG to be loaded themselves with the `onLoad` properties of the `Raster` instances (like I did in the above sketch).

**Comment by RickMohr** [comment]
@sasensi, thank you very much -- with this insight I was able to solve my problem. 

Because of a bug elsewhere my code worked correctly when the SVG's raster was not fully loaded (and so had position (0, 0)) but incorrectly when it was fully loaded (and so had a non-zero position). So I never suspected I was using a not-fully-loaded raster.

Closing this issue.
