### ISSUE TITLE
the selected point too small to click

### ISSUE THREAD

**Issue by Terness** [paperjs/paper.js#1877]
I have a path that it was selected, but it was too small, i cannot click it, so how can i make it become bigger?

![1606105361064](https://user-images.githubusercontent.com/9781661/99929033-46c5e380-2d11-11eb-8be2-c9510e7566ea.jpg)

**Comment by arnoson** [comment]
You can increase the handle size in ther paperscope's settings: [demo](http://paperjs.org/reference/paperscope/#settings)
See [here ](http://paperjs.org/reference/paperscope/#settings) for more information

**Comment by Terness** [comment]
Thanks @arnoson !! It's very useful
