### ISSUE TITLE
travis-ci.org will be closed by Dec 31st, 2020

### ISSUE THREAD

**Issue by sapics** [paperjs/paper.js#1887]
https://docs.travis-ci.com/user/migrate/open-source-repository-migration#q-when-will-the-migration-from-travis-ciorg-to-travis-cicom-be-completed

travis-ci.org will be closed by Dec 31st, 2020. It would be better to migrate to travis-ci.com before closed.

**Comment by lehni** [comment]
@sapics it seems to be still going! I don't really know if we need to do anything when they switch, or if this is automatic. I don't see any mention of the .org domain in our code…

**Comment by sapics** [comment]
As you noticed, they have not been shutting down yet. It might be enough to switch when they shutting down travis-ci.org ;)
Thus, I close issue.
