### ISSUE TITLE
Path, problem with getCurvatureAt 

### ISSUE THREAD

**Issue by pedefe** [paperjs/paper.js#1890]
Hello,
I have built a Path with 5 points, matching a road on a map.
I try to follow the Path with a "vehicle" which is not exactly on the path at the beginning, and move in parallel of Path.
So, I use `getNearestPoint` in order to find the point on path : result is good. (I display it on canvas);
I use `getWeightedTangentAt` and `getWeightedNormalAt` : result is good; (I display them on canvas);
I use `getOffsetOf`, then `getCurvatureAt` in order to tune the correction of the vehicle direction toward the Path.
But then, returned curvature is bad (a big number for a straight Path), and increase during vehicle moves in parallel of path.
What can be the mistake ?    
Best regards.

**Comment by sapics** [comment]
Please post question or discussion to the other place.

* Questions: https://stackoverflow.com/questions/tagged/paperjs
* Discussion forum: https://groups.google.com/group/paperjs

This is bug database, thus, please help to keep free from general questions. Thanks.
