### ISSUE TITLE
distance bwtween two  same point on different screen sizes

### ISSUE THREAD

**Issue by abasit007** [paperjs/paper.js#1896]
hi there hope everyone is doing fine ...
am new to paperjs and and i am having an issue with calculating the distance between two same points at different screen resolutions ... i will try to explain if something doesn't seems to be good then you can ask for more details ...
so this is what we do ...
1=>  we have a canvas with an image so at normal screen we measure distance between two points and then that is the standard distance so on same resolution we calculate distance so it give correct value
2 =>  but when we same scale on smaller screens or bigger screens with different resolution it relatively differs in the value for larger screens it increases the length between same two points and reduces for smaller screens... so any one with suggestions am open for it

**Comment by sapics** [comment]
Please post question or discussion to the other place.

* Questions: https://stackoverflow.com/questions/tagged/paperjs
* Discussion forum: https://groups.google.com/group/paperjs

This is bug database, thus, please help to keep free from general questions. Thanks.
