### ISSUE TITLE
To be able to set the font during the initialisation

### ISSUE THREAD

**Issue by kuzman** [paperjs/paper.js#1898]
Is there a way to set the `font` during the initialisation so that it is propagated to all the items that compose the view?
I have tried with the `view.context.font`, but the items still have `sans-serif` by default

**Comment by sapics** [comment]
project.currentStyle might help you (doc: http://paperjs.org/reference/project/#currentstyle).

Please post question or discussion to the other place.

* Questions: https://stackoverflow.com/questions/tagged/paperjs
* Discussion forum: https://groups.google.com/group/paperjs

This is bug database, thus, please help to keep free from general questions. Thanks.
