### ISSUE TITLE
Rasterize in 0.12.12 moves the rastered image

### ISSUE THREAD

**Issue by petbuc16** [paperjs/paper.js#1905]
Since paperjs version 0.12.12, which was released a few days ago, using rasterize is moving the item. Is there some hotFix? 

![image](https://user-images.githubusercontent.com/41146204/111295104-4d26f500-864b-11eb-9cfc-f37d5640d79b.png)

**Comment by lehni** [comment]
uh oh, that's a regression! Could you share the sketch? Thanks!

**Comment by petbuc16** [comment]
Sketch link:
http://sketch.paperjs.org/#V/0.12.12/S/VZFNb8IwDIb/ihVpotOq0mnqpYgT503TOBIOITU0Io2rJMA2xH+fQwvbcrP1vB9yzsKpDkUtlnuMuhW50NSk+ag8aOO1RZiDwxO8q9gWi+smO0sH/DS6iL6GVVXmUJXrfFh71ZhDqKEa562xdkGWmJx4bCbSXR5n0kk3ncLCo4oIikWBvcw3NnBEHww5oC3EFqHn4Fq6VGiAuNDQrLiLsrPHQPYQWVfDc1mWvxGvdEQwMW37CJGupt7s2siug0PRUzBJW3zC0zyRN/FSK77ArQYo1wzyocjmC17K8iGHQHBC0MqBpq5X/irp2H8sGpJNVqVOY+KfDVPkuD0WlnaZFB/3U0iRj1HFhg6uCQn/D7+R75RN4Bh1A/krN3zcfU/GxSDq1fryAw==

**Comment by lehni** [comment]
Thanks @petbuc16 for the sketch. It was an easy fix!

**Comment by lehni** [comment]
Works as expected now in the newly released v0.12.13:

http://sketch.paperjs.org/#V/0.12.13/S/VZFNb8IwDIb/ihVpotOq0mnqpYgT503TOBIOITU0Io2rJMA2xH+fQwvbcrP1vB9yzsKpDkUtlnuMuhW50NSk+ag8aOO1RZiDwxO8q9gWi+smO0sH/DS6iL6GVVXmUJXrfFh71ZhDqKEa562xdkGWmJx4bCbSXR5n0kk3ncLCo4oIikWBvcw3NnBEHww5oC3EFqHn4Fq6VGiAuNDQrLiLsrPHQPYQWVfDc1mWvxGvdEQwMW37CJGupt7s2siug0PRUzBJW3zC0zyRN/FSK77ArQYo1wzyocjmC17K8iGHQHBC0MqBpq5X/irp2H8sGpJNVqVOY+KfDVPkuD0WlnaZFB/3U0iRj1HFhg6uCQn/D7+R75RN4Bh1A/krN3zcfU/GxSDq1fryAw==
