### ISSUE TITLE
Installing paper 0.12.13 with npm doesn't work

### ISSUE THREAD

**Issue by petbuc16** [paperjs/paper.js#1906]
I tried to install the new version, after bug [#1905](https://github.com/paperjs/paper.js/issues/1905) was fixed, and now npm says husky not found. Do I need to install husky on cli or something like that:

![image](https://user-images.githubusercontent.com/41146204/111426740-66847b80-86f5-11eb-843a-6496a420d482.png)

Thanks in advance.

**Comment by lehni** [comment]
I've updated to husky 5 and followed their instructions. Turns out this doesn't work with Yarn 2 which I had to switch to to avoid another problem with NPM. The Node.js ecosystem is such a mess 🤦 

Hopefully fixing this one today.

**Comment by petbuc16** [comment]
Ok, I understand you, npm can be horrible sometimes.

Please leave a comment when released. Thanks a lot !

**Comment by lehni** [comment]
Sadly this didn't work for `v0.12.14`, so I gotta downgrade husky…

**Comment by lehni** [comment]
`v0.12.15` is out and works again. But now husky seems to no do a thing… 🤯

**Comment by petbuc16** [comment]
Thanks man and good luck
