### ISSUE TITLE
Index improvements

### ISSUE THREAD

**Issue by petbuc16** [paperjs/paper.js#1908]
Hi there, 
is there a way to improve the index behavior of the paper items. 
So basically I want a setter the '.index' property and not have to struggle with 'insertAbove' or functions like that.

Do you have any idea? Thanks

**Comment by sapics** [comment]
It looks reasonable feature, thus, I create a PR. Please review the PR.

**Comment by petbuc16** [comment]
thanks, looks good i think

**Comment by lehni** [comment]
I agree this is reasonable, thanks @sapics! I added one comment, happy to merge otherwise.

**Comment by sapics** [comment]
This issue is merged and released in newer version. Feel free to reopen this, if there are some related issues.
