### ISSUE TITLE
Path.intersects

### ISSUE THREAD

**Issue by manticore999** [paperjs/paper.js#1915]
Hi,
I am a newbie to paperjs. I am facing some issue while using path.intersects().
I have a bunch of circles going in different directions and I want them to turn red when they intersect. This only happens about 5% of the time, the other times they remain black. This is my code: 
```javascript

<html>
    <script type="text/javascript" src="paperjs-v0.12.15/dist/paper-full.min.js"></script>
    <canvas id="canvas" width=1400 height=750></canvas>
<script>
    paper.install(window);

    window.onload = () => {
		const canvas = document.getElementById('canvas');
		paper.setup(canvas);
        const circleNum = 20;
        const circles = [];

        class Circle{
            constructor(){
                this.size = 20;
                this.x = Math.random() * (canvas.width - this.size * 2) + this.size;
                this.y = Math.random() * (canvas.height - this.size * 2) + this.size;
                this.color = "black";
                let speed = 5;
                let angle = Math.random() * Math.PI * 2
                this.velX = Math.cos(angle) * speed;
                this.velY = Math.sin(angle) * speed;
                this.path = null;
                this.create();
            }

            move(){
                this.x += this.velX;
                this.y += this.velY;

                this.path.position.x = this.x;
                this.path.position.y = this.y;

                if(this.x + this.size >= canvas.width || this.x - this.size <= 0) this.velX *= -1;
                if(this.y + this.size >= canvas.height || this.y - this.size <= 0) this.velY *= -1;
            }

            create(){
                this.path = new Path.Circle(new Point(this.x, this.y), this.size);
                this.path.fillColor = this.color;
            }
        }

        for(let i = 0; i < circleNum; i++) circles.push(new Circle());

        function bounce(){
            for(const circle1 of circles){
                for(const circle2 of circles){
                    if(circle1 !== circle2){
                        if(circle1.path.intersects(circle2.path)){
                            // console.log('hit');
                            circle1.path.fillColor = 'red';
                            circle2.path.fillColor = 'red';
                        }
                        else{
                            circle1.path.fillColor = 'black'
                            circle2.path.fillColor = 'black'
                        }
                    }
                }
            }
        }

        function update(){
            for(const circle of circles) circle.move();
            bounce();
            window.requestAnimationFrame(update);
        }
        update()
    }
</script>
</html>
```

**Comment by sapics** [comment]
This is not a bug of the `path.intersects` ;)
I guess that this is what you want, isn't it?

http://sketch.paperjs.org/#V/0.12.15/S/lVVLbxoxEP4r1l7YhWQVkHoJoVUbtVIOrSL10ghy2HgH1sTYW9sLoQn/PX7ugyWJygU88/mbbx4eniOWbSC6jH4/gsJFdBZhnpsz5kwqhDO2zSSaoZzjagNMpStQ3ymYn9/2N3k8cIhBMl2IBSuzEkQqQVVl7BzO7smIwBR+VRvNN7noOUyY+b01WxfNpETX1vVsDEh/LF5UWHERJ7XVfFRBZCrJP2jIO64nbf+ZqSIVGcv5Jk7QEHmN6Y7kqkDnLY4hmiRo1Bj6fPt3+Aogq0L9JyHmlAtNuogeaIYfF1EHQkEhWQLkGvGp58nYisIJQfZ8e2Oi9+Jtgf4JVzCXseUwl2yYvj6Nvwt4SdiH+FIDNZ5VlJ5IVkCmIE5qzyG03Rw2fAun2vuERrNG/KmetPx3pyWlJZdEEc7sRDjaj5D7gNx3kGQZB1mtTn+eoc5YvbwE8e15uJqhi6TViOEMnY9Psu/fYPdDFuj379DfHdF3ih1a0S936CDs0K2ph3uLsT1zwpTP/swLSM4aAckbJV0SSq/9oDdT3xVWq1vqR26mm2jwxVR/XTUrRB9HoyRsjrSsZGGFeY2JE7DNhF4ZFVMgLIdlrRg2XUUP2oHbiftlVAmht5vGj0b+bq3P8FFg2hcC69NKFTXASDYgI3nsJGvEVFORboHbi2/c8M3JfadygW/tSrDWfMSwrbtsx4yTFuO6y+hHy0d2XSEmSQlYSW+fWHvSD2ID+atNYcOllsUV8fj6oW04dLoesm2ngfgypHFUPWvsj5S31zpmtRL0BQ0E5AN0iQZ2vw7eGrowHlWZd9/Fe+pCZLe5auowYrVhR/Ru3qUC/lYg1VdGNpkJ9kPoP+HYRXRgqydI0P/KD/qVPpbm1cnocn5/eAU=

**Comment by manticore999** [comment]
> This is not a bug of the `path.intersects` ;)
> I guess that this is what you want, isn't it?
> 
> http://sketch.paperjs.org/#V/0.12.15/S/lVVLbxoxEP4r1l7YhWQVkHoJoVUbtVIOrSL10ghy2HgH1sTYW9sLoQn/PX7ugyWJygU88/mbbx4eniOWbSC6jH4/gsJFdBZhnpsz5kwqhDO2zSSaoZzjagNMpStQ3ymYn9/2N3k8cIhBMl2IBSuzEkQqQVVl7BzO7smIwBR+VRvNN7noOUyY+b01WxfNpETX1vVsDEh/LF5UWHERJ7XVfFRBZCrJP2jIO64nbf+ZqSIVGcv5Jk7QEHmN6Y7kqkDnLY4hmiRo1Bj6fPt3+Aogq0L9JyHmlAtNuogeaIYfF1EHQkEhWQLkGvGp58nYisIJQfZ8e2Oi9+Jtgf4JVzCXseUwl2yYvj6Nvwt4SdiH+FIDNZ5VlJ5IVkCmIE5qzyG03Rw2fAun2vuERrNG/KmetPx3pyWlJZdEEc7sRDjaj5D7gNx3kGQZB1mtTn+eoc5YvbwE8e15uJqhi6TViOEMnY9Psu/fYPdDFuj379DfHdF3ih1a0S936CDs0K2ph3uLsT1zwpTP/swLSM4aAckbJV0SSq/9oDdT3xVWq1vqR26mm2jwxVR/XTUrRB9HoyRsjrSsZGGFeY2JE7DNhF4ZFVMgLIdlrRg2XUUP2oHbiftlVAmht5vGj0b+bq3P8FFg2hcC69NKFTXASDYgI3nsJGvEVFORboHbi2/c8M3JfadygW/tSrDWfMSwrbtsx4yTFuO6y+hHy0d2XSEmSQlYSW+fWHvSD2ID+atNYcOllsUV8fj6oW04dLoesm2ngfgypHFUPWvsj5S31zpmtRL0BQ0E5AN0iQZ2vw7eGrowHlWZd9/Fe+pCZLe5auowYrVhR/Ru3qUC/lYg1VdGNpkJ9kPoP+HYRXRgqydI0P/KD/qVPpbm1cnocn5/eAU=

Yes this is what i wanted, thanks a lot for that. I have 1 more question though. When i try to do this with 1000 circles, it seems to be extremely laggy. When i try it without paperjs on canvas it doesnt seem nearly as laggy. Is there something wrong with my code or is paperjs just a bit slower?

**Comment by sapics** [comment]
Since it is a circle, it is faster to calculate the distance than `path.intersects`. Anyway, it is faster to create your own dedicated calculation than to use library ;)

It is better to post question or discussion to the other place.

* Questions: https://stackoverflow.com/questions/tagged/paperjs
* Discussion forum: https://groups.google.com/group/paperjs

This is bug database, thus, please help to keep free from general questions. Thanks.
