### ISSUE TITLE
How to fill a figure with a color in a closed path paper.js

### ISSUE THREAD

**Issue by kandjiabdou** [paperjs/paper.js#1931]
# Description

I would like to draw and color full figures by doing animations with paper.js. I have examples here.

- In figure 1: the animation starts at point A then goes towards B, after C, D, E, F and ends with G. We notice that the figure GBCDEF is a closed path and I would like it in green as indicated, but it must do so as soon as the animation intersects the segment [AB] at point G.
- on fugure 2: the animation continues and again cuts the segment [BC] in H. So the triangle GHB is a closed path and it should also be colored in green.
- in figure 3: the animation ends at point J and again cuts the segment [CD] in I. But there you do not need to color anything since the triangle CIH is already colored.

# Example
![Figure 1](https://i.stack.imgur.com/dIjef.png) ![Figure 2](https://i.stack.imgur.com/bePri.png) ![Figure 3](https://i.stack.imgur.com/DxUfJ.png)

# Additional information
Windows 10 Pro

**Comment by sapics** [comment]
It is better to post question or discussion to the other place.

* Questions: https://stackoverflow.com/questions/tagged/paperjs
* Discussion forum: https://groups.google.com/group/paperjs

This is bug database, thus, please help to keep free from general questions. Thanks.
