### ISSUE TITLE
Incomprehensible results of view dragging

### ISSUE THREAD

**Issue by hiluxx** [paperjs/paper.js#1935]
i use the code for dragging the view:
```
view.onMouseDrag = function(event) {
      view.center = view.center + event.delta;
}
```
it works, but the distance the view moves is _**twice**_ the distance moved by the mouse.
And we need the view move in the opposite direction to conform to human habits, so i modify the code bellow:
```
view.onMouseDrag = function(event) {
      view.center = view.center - event.delta;
}
```
direction is ok, but the distance moved by the view is **_half_** of the distance moved by the mouse. 
And the view shakes severely during the dragging process, but it does not appear in the above code.

**Comment by eeropic** [comment]
Here's an [example Sketch](http://sketch.paperjs.org/#V/0.12.15/S/fZExT8MwEIX/iuWpkaqIgSkVC2VFqtSKBTO4zpWYmrvo7CRCVf47tpOUSgi83d333j3bF4n6E2Ql92cIppFraahOda9ZBPBBPAiEQewb3UK5tWwcrC4KRTysa9v5StzfradGS94GS1iJ3sJQGsAAPM9O1rktOeJKSYZaSYVjoVBhWuS0DzuyGDa5k8SEz9R5eKIBY4RThyY5r6CPpsUc4CqLRBa1TB9gwoFeYjWxZZuAIhqPv7xZv//pnWIlOAKhsX7z023njan9/8ZFkXIuguR5oN0kW11vsOCZ8YbJucevPC59dwysI3zrvvC3T5An8Z7xE48M+pxrL6vXt/Eb) of how to handle the View <-> Project coordinates while adjusting the view position

From sketch.paperjs.org implementation (Zoom tool + space to pan around the view)
https://github.com/paperjs/sketch.paperjs.org/blob/5c369014277727248e7414fbe4c841ec6732343d/assets/js/main.js#L828

**Comment by eeropic** [comment]
> In order to have coordinate changes not mess up the dragging, we need to convert coordinates to view space,
> and then back to project space after the view space has changed.
