### ISSUE TITLE
Export Canvas with Raster Image

### ISSUE THREAD

**Issue by r00sn** [paperjs/paper.js#1937]
Hi all, I am new to **Paper.js**, I am creating a simple drawing tool using paper.js and download the canvas with the background image.  I'm trying filesaver.js and blob however, I'm stuck downloading the canvas with a raster image as background. 
Any help or suggestions would be highly appreciated. 

       ```
          //button to download
       <button href="#" class="btn btn-primary" id="save-canvas" 
         onclick="exportPNG()">Save</button>

          //canvas
        <canvas class="canvas" resize id="canvas"></canvas>
         //image
        <img src="image/image.jpg" id="image">

    function exportPNG() {

        var canvas = document.getElementById('canvas');
        canvas.toBlob(function (blob) {
            saveAs(blob, 'paper.png');
        });
      
    }

        // Setup Paper
      
        paper.setup(document.querySelector('canvas'));

        //Image Layer

        var imageLayer = new Layer({insert: false});
        var image = new Raster('image');
        image.position = view.center;

        project.layers.push(imageLayer);
        imageLayer.addChild(image);
        imageLayer.activate();
```

**Comment by sapics** [comment]
It is better to post question or discussion to the other place.

* Questions: https://stackoverflow.com/questions/tagged/paperjs
* Discussion forum: https://groups.google.com/group/paperjs

This is bug database, thus, please help to keep free from general questions. Thanks.
