### ISSUE TITLE
linestyle dash_array

### ISSUE THREAD

**Issue by Zhang-fulin** [paperjs/paper.js#1941]
Sorry to disturb
I just want to ask that special line types can be supported by paper, like AutoCAD

![1628144820575](https://user-images.githubusercontent.com/49267133/128301899-3b489152-b30a-4e8d-a30d-770d27db5fad.jpg)
<img width="817" alt="WechatIMG2" src="https://user-images.githubusercontent.com/49267133/128301928-b5f79762-d363-43fb-880c-230d7573cf2c.png">

I did not find a similar demo

**Comment by sapics** [comment]
I have not understand well about `like AutoCAD`, but `dash array` is supported as http://paperjs.org/reference/path/#dasharray.

It is better to post question or discussion to the other place.

* Questions: https://stackoverflow.com/questions/tagged/paperjs
* Discussion forum: https://groups.google.com/group/paperjs

This is bug database, thus, please help to keep free from general questions. Thanks.
