### ISSUE TITLE
How to use expand method

### ISSUE THREAD

**Issue by mcnLeandro** [paperjs/paper.js#1942]
I wanted to use expand method but I couldn't see any changes.

```js
let rect = new Path.Rectangle({
    point: [100,100],
    size:[100,100],
    fillColor:'black'
})
rect.bounds.expand(500,500)
```

Am I missing something?
I prefer to see some examples of expand method usage.
I'm using javascript for text type.

**Comment by sapics** [comment]
It is better to post question or discussion to the other place.

* Questions: https://stackoverflow.com/questions/tagged/paperjs
* Discussion forum: https://groups.google.com/group/paperjs

This is bug database, thus, please help to keep free from general questions. Thanks.

**Comment by sapics** [comment]
Sorry, Is this a bug issue?
It would be better to use `rect.scale(500, 500)`.

**Comment by mcnLeandro** [comment]
Thanks
I think so. "expand" method doesn't work

Thank you for your advise too.
But, is there any way to expand with "px" unit? 
I don't wanna scale, because I'll expand many time.

**Comment by sapics** [comment]
How about `rect.bounds.width = 100`?

**Comment by mcnLeandro** [comment]
That's works! Thanks!
i'll use that instead of `expand`

**Comment by mcnLeandro** [comment]
Close this issue for now, but I always welcome to know various solutions.
