### ISSUE TITLE
Setting "pointText.fontWeight = 'bold bold'" result in scaling the item while the fontSize property still be what it was. 

### ISSUE THREAD

**Issue by wiskewu** [paperjs/paper.js#1951]
# Description/Steps to reproduce
The pointText item was scaled When setting 'bold bold' to it's fontWeight property

# Link to reproduction test-case
[click to see the test-case](http://sketch.paperjs.org/#V/0.12.15/S/dZJNb4MwDIb/isUlnVYhxseFqqdKO06TWmkH4BBCOiLSZIJ03Vb1v8+BAkWlSCiyn9fxa8PZUfTAndjZVtyw0lk6TBc2/qY1GP5jYA2Kn+BdC2V2GC/OqQJ8vmwihiTylhB52bLLMq0Mt3myK3kfNaD3YDBua9pbyVW/F1JutNQ1VuSSsmoAWPpKD0L+ItnoYy14DW/8dMs/uPgsba9cy+IWbMUfj8GPUnV5WqUqVf0wPk5jT5dJrfjCwh4Fj1H4GEX3qO3j5vqoisZlOD4af15Dgnt68bzsqgjmFf6oCOcVwaiI5hVhp+idjJtCr0QYKgWD7iCDmakIe9g+ZHAyxXbdkEtdkMHIVFDSEvAlK/yd8prTqv3wjRMn2eUf)

# Expected result
`item.fontWeight = 'italic italic'` is not ok;
`tem.fontWeight = '300 300'` is not ok;
`tem.fontWeight =  'bold bold'` is not ok ;
`tem.fontWeight =  'haha haha'` is not ok ;😂 

And this is somewhat not easy for us to figure out what's going on out there.

# Additional information
Actually I have no idea whether it is an problem or not... Maybe someone will tell me the difference between those case.

**Comment by aliraad79** [comment]
Hi. I'm not an admin or something but as i go through your issue it's like it fixed. Hope this help

**Comment by wiskewu** [comment]
@aliraad79  Yes, It seems to have been fixed already, thanks a lot
