### ISSUE TITLE
Add point (moveTo, lineTo) only get Point types

### ISSUE THREAD

**Issue by jglee96** [paperjs/paper.js#1954]
I use typescript and paper.js v0.12.15.
When I add point by using `moveTo` or `lineTo`, I always have to create Point.
I just want to give `x, y` values to `moveTo` or `lineTo`.

like this:
`path.moveTo(new paper.Point(x, y));` -> `path.moveTo(x, y);`

**Comment by sasensi** [comment]
Hi, there is an existing PR that should fix this issue: https://github.com/paperjs/paper.js/pull/1865/files
@lehni, would you have some time to look at it ?

**Comment by wrightwriter** [comment]
Yes, we really need this. The ts definitions are horrible like this. Unusable.

**Comment by lehni** [comment]
Merged.
