### ISSUE TITLE
"Download as SVG" button fails

### ISSUE THREAD

**Issue by RichardJECooke** [paperjs/paper.js#1955]
- Go to `http://paperjs.org/features/`
- Click the `Download as SVG` button
- Get redirected to the error page with message:
```
Error: Server Error
The server encountered an error and could not complete your request.
Please try again in 30 seconds.
```

**Comment by eeropic** [comment]
There's an issue open of this at the paperjs.org repo https://github.com/paperjs/paperjs.org/issues/41

**Comment by eeropic** [comment]
Look at 
https://github.com/paperjs/paper.js/issues/1945#issuecomment-915079853 
if you need the feature on your own code
