### ISSUE TITLE
Global Symbol class is overwritten

### ISSUE THREAD

**Issue by the-leonat** [paperjs/paper.js#1964]
# Description/Steps to reproduce

On Safari 15.0 paper.min.js (0.11.5) overwrites the global Symbol class. Other scripts relying on this class fail later.

**Comment by the-leonat** [comment]
is this due to a polyfill which is removed in later versions?

**Comment by sapics** [comment]
Now, we use SymbolDefinition and SymbolItem as below. Thus it will not be a problem in current version.
http://paperjs.org/reference/symboldefinition/
http://paperjs.org/reference/symbolitem/
