### ISSUE TITLE
Item.globalMatrix incorrect if parent's matrix changes when item.visible is false

### ISSUE THREAD

**Issue by RickMohr** [paperjs/paper.js#1966]
In [this simple sketch](http://sketch.paperjs.org/#V/0.12.15/S/hY+xCsJAEER/JVwVQY7EMmJlqyBYqsVmXZMz6124W6NB/HdPoyA2lsOb2dm5KQsnUoVaNyRYq7FCt3/qQCLGVkFD23K/BPHmmsySA3Cg6dZ24BOM2tIlWYHUem48MqWjN+PIWu+OhKIBxXS0gJ58pKzFgw0MQukkG0+yZwSdDY5Js6tS1BW7EnjoHL0iASEezwev7kwwJdPXOx+Hzn8d4s/0tyDOLj1B0zpjJahis7s/AA==). A circle `c`'s layer is scaled by 10 and then .1, which should leave `c.globalMatrix` unchanged. But if we set `c.visible = false` between the two scale operations, `c.globalMatrix` changes. If  that line is commented out, `c.globalMatrix` does not change.

**Comment by sapics** [comment]
Thanks for report!
It's a reasonable issue, but it's not a bug, I guess.

`.scale(10)` is scaled with center of item, and, the center of group is changed by children's `visible`.
So, it would be better to scale with setting center as `.scale(10, 10, new Point(0, 0))`.

http://paperjs.org/reference/item/#scale-scale

http://sketch.paperjs.org/#V/0.12.15/S/fZAxawMxDIX/ivGSOzDG1zGlU9YECh2bDjpHuThR7UNWrw2l/732pSGdsjx4SN/zk791hHfUS/1yQvEHbbRPu+ozioQ4ZAvjSOcNCIcv9aT2QBkft3ECVr74iJ/qGeRgV4E9YTP7FKI0nTOqc+0sfwAVYOR0RC8WvIQJ13BGLlNv94FolShx2Vkw7hbbSFYYYiYQbB5ciStSo8p6ijkRWkpD4+1AqQe6VKxzstlD6XJpYNStkzOubefnppBDT/jvoivlbGfULPc54Y+K3a9S/rNnhNNYY7Jevr79/AI=

Sorry, I am not good at English. Is it good as answer?

**Comment by RickMohr** [comment]
Good point, and thanks for your comment. This was a simplified version of my actual problem. In my more complex case, `globalMatrix` is incorrect, but is correct if I first set the internal `_globalMatrix` to `undefined`. That surely looks like a bug, but so far I'm not able to demonstrate it with a simple example. So I'll close this for now.
