### ISSUE TITLE
Multicolored paths

### ISSUE THREAD

**Issue by 6peterlu** [paperjs/paper.js#1967]
Is it possible to make multicolored paths, or color individual segments? Any workaround suggestions would be appreciated if there's no directly supported way to do this.

Thank you so much for this library!

**Comment by sasensi** [comment]
Hi, this is not possible but you can workaround it by dividing your path into as many path as you need.  
For example one path per segment and color each of them differently.  
This is not perfect though because you can have issues at corners depending on your use case.
Here's a simple [sketch](http://sketch.paperjs.org/#V/0.12.15/S/fVJNSwMxEP0rw152i0toBUEiXuxJ8CD04MF6yCbTbmyalHy0Sul/d7Jrtx+gCxnysm/evJlkX1ixxoIXsxVG2RZ1IZ3KeJGsjNpZkB5FxFlqXkVsqw2FGgIu12jjs1X4NbmEtzVIZ5wfwX7u5xbok86GCNI4i/AIWYF1oBo9DJSM2a9OOLKOmAWjJVb/VYUbmFzLUQyoSGwhTMDrWtG7FU6zVWJ0lgeGx5i87Ynd4SGHvPpWGhEwT4MSLe4gb9lUe2mwOjVN1tBz2GrcsR7Ug75QOgUOd+Ph6MwOh9J5YZdYXv190yq2HCZnWWhQRlQcok/YOe2H0Hm9uLij5xrGNdD0ysYkLHv2X0yi0XWWHlV5kt1490lFmaDnscUX8Y2eLXR8csmqUHXtNt2eBSloImN2P+qz6XE1VGm1cZouteDvH4cf) demonstrating the idea.

```javascript
function createSubPath(path, segmentIndex1, segmentIndex2, color) {
    const clone = path.clone();
    clone.segments = path.segments.slice(segmentIndex1, segmentIndex2 + 1);
    clone.closed = false;
    clone.strokeColor = color;
    return clone;
}

const basePath = new Path.Circle({
    center: view.center,
    radius: 50,
    strokeColor: 'orange',
    strokeWidth: 10,
    selected: true
});

createSubPath(basePath, 0, 1, 'blue');
createSubPath(basePath, 1, 2, 'red');

project.activeLayer.fitBounds(view.bounds.scale(0.8));
```

**Comment by 6peterlu** [comment]
@sasensi wow thank you, this is really great! one more follow-on question: is it possible to blend the colors from neighboring segments together?

Thank you so much for the timely help!

**Comment by sasensi** [comment]
Can you precise your idea, maybe by drawing it ?

**Comment by 6peterlu** [comment]
here's the idea I had in mind! basically just to blur the color changes in the path for a more natural transition. Let me know if it makes sense or not (:
![colored path gradient](https://user-images.githubusercontent.com/8334251/151393594-81de2191-03c2-4ee1-932c-3818a99af8fe.png)

**Comment by sasensi** [comment]
Here again, not a supported feature but you can find descent workaround.  
Have a look at this [sketch](http://sketch.paperjs.org/#V/0.12.15/S/hVNNa8MwDP0rIpekLJh+MBgeu6ynwQ6DHnZoe3BstfWa2sV22o3S/z45abKmsM0Qx7KfpKcn+5QYscOEJ7MtBrlJ8kRaFe1VZWTQ1oB0KALOquJNhE22pykHj+sdmvBiFH6O+uY4B2lL60aX/3gAp4VbGKAhrfEBZGkNwhPEUKw2ssFjB4k2uwT0Laq1mS+1xOyv9HAHo9twNHtUFGwlSo+3uYKzW5xGroTouMaxdkJpisz723H4YPeew7xf6/Iads6vLev0Wht+SbrSzodZw5vtrTahB1bogzYi6t96lOLGocWfu3ochsqZBl9vnuMUv0b4QniMTaQyDR4hLtlUO1li9tMiio+Ow0HjkTVGxyyqUVHR98Nu60o8Dql1wqwxvTl91ypsOEyuvLBEGVBxCK7CmmnTsppr7761nHMY5kA6dznSoqwwbdx+cyE8XccGmacO1T94Ak8IH4F5m+iH2N7ZD6LNBL2LA76KL3TUx/BsK6N8VgtW1GvmpSBNh+xh0HjTqyoo5bbum0/4fHn+Bg==).

```javascript
function createSubPath(path, segmentIndex1, segmentIndex2, color1, color2) {
    const clone = path.clone();
    clone.segments = path.segments.slice(segmentIndex1, segmentIndex2 + 1);
    clone.closed = false;
    clone.strokeColor = {
        gradient: {
            stops: [color1, color2]
        },
        origin: clone.firstSegment.point,
        destination: clone.lastSegment.point
    };
    return clone;
}

const basePath = new Path.Circle({
    center: view.center,
    radius: 50,
    strokeColor: 'orange',
    strokeWidth: 30,
    selected: true
});

createSubPath(basePath, 0, 1, 'orange','blue');
createSubPath(basePath, 1, 2, 'blue','red');
createSubPath(basePath, 2, 3, 'red','orange');

project.activeLayer.fitBounds(view.bounds.scale(0.8));
```

**Comment by 6peterlu** [comment]
Thank you so much! One last thing: I am trying to get it to work in this JS fiddle but it doesn't appear to draw the gradient color: https://jsfiddle.net/xcotLpv3/
i can get your non-gradient example working but not this one. Any ideas?

**Comment by 6peterlu** [comment]
I basically am unable to get any sort of gradient coloring to work in my jsfiddle, not sure why.

**Comment by 6peterlu** [comment]
I got it working! It was a package import error, basically the version of paperjs on jsfiddle doesn't work correctly, so i just imported it from CDN and it works (: 
Stackoverflow help reference: https://stackoverflow.com/questions/70885885/color-gradient-renders-as-black

Thank you!
