### ISSUE TITLE
draw a dot without scale 

### ISSUE THREAD

**Issue by Zhang-fulin** [paperjs/paper.js#1976]
guys, sorry for the issu , 
 i want to know how to draw a dot with paper, no matter how the (paper.view.zoom) is, it still is a dot, 
 sorry for this issue again ,
 it most like is a function problem.

**Comment by sapics** [comment]
As written in before issue #1941, it is better to post question or discussion to the other place.

Questions: https://stackoverflow.com/questions/tagged/paperjs
Discussion forum: https://groups.google.com/group/paperjs

This is bug database, thus, please help to keep free from general questions. Thanks.
