### ISSUE TITLE
Optimization needed for canvas getContext() to remove warning on startup

### ISSUE THREAD

**Issue by chris-patenaude** [paperjs/paper.js#1999]
# Description/Steps to reproduce
During initial render, in the console you will see the following message:

```console
paper-full.js?9800:14575 Canvas2D: Multiple readback operations using getImageData are faster with the willReadFrequently attribute set to true. See: https://html.spec.whatwg.org/multipage/canvas.html#concept-canvas-will-read-frequently
```

# Link to reproduction test-case
Any environment will have this message

# Expected result

Already explained in description.

# Additional information
Windows 10
Chrome/Brave

**Comment by lehni** [comment]
Released in `v0.12.16`
