### ISSUE TITLE
New warning in Chrome Console

### ISSUE THREAD

**Issue by shagarah** [paperjs/paper.js#2003]
# Description/Steps to reproduce

I now get this warning in chrome's console:

"Canvas2D: Multiple readback operations using getImageData are faster with the willReadFrequently attribute set to true. See: https://html.spec.whatwg.org/multipage/canvas.html#concept-canvas-will-read-frequently
(anonymous) @ paper-core.min.js:32
t.call.n @ paper-core.min.js:32
n @ paper-core.min.js:32
(anonymous) @ paper-core.min.js:32
(anonymous) @ paper-core.min.js:32
(anonymous) @ paper-core.min.js:32
"

# Link to reproduction test-case

# Expected result

# Additional information

**Comment by pearcetm** [comment]
I believe this is the same issue as https://github.com/paperjs/paper.js/issues/1999#issue-1393848477

**Comment by shagarah** [comment]
Yep.

**Comment by lehni** [comment]
Released in `v0.12.16`
