### ISSUE TITLE
how does generateBezier work

### ISSUE THREAD

**Issue by sickopickle** [paperjs/paper.js#2015]
Can anyone explain to me the logic of the generateBezier function?
This is inside PathFitter.js
Sorry for putting this in the Issues section, but no one responded on the Gitter.

Thanks.

**Comment by eeropic** [comment]
Please use the [Paper.js Google Group](https://groups.google.com/g/paperjs) for discussing how to use the library. Regarding the inner workings of the library, such as generateBezier function, you should find plenty of material online searching for "least squares bezier fitting" - for example [A Primer on Bézier Curves](https://pomax.github.io/bezierinfo/) by Mike "Pomax" Kamermans
