### ISSUE TITLE
Zones and intersection

### ISSUE THREAD

**Issue by svk-man** [paperjs/paper.js#2016]
![image](https://user-images.githubusercontent.com/17108861/208333272-1ad11216-4121-4711-9dbb-0da147efb72a.png)

Good afternoon!

I need to draw three polygons - outer and two inner ones. They can be edited.

All three polygons form zones. I marked them - 1, 2, 3.

I need to be able to switch between zones and look for the intersection of each of the zones with a moving point, for example, the mouse cursor.

Can you please tell me if your library will help me?

**Comment by pearcetm** [comment]
There are a number of ways this can be achieved. Check out http://paperjs.org/reference/mouseevent/ if you are specifically interested in detecting mouse enter/exit on the items, or http://paperjs.org/reference/hitresult/ for detecting intersections with any point that you want.

**Comment by sapics** [comment]
@pearcetm Thank you for the answer!
I believe that your question has been resolved, so I close it.
