### ISSUE TITLE
NuGet package?

### ISSUE THREAD

**Issue by tommck** [paperjs/paper.js#240]
It would be nice to have paper.js packaged up as a NuGet package.  

More and more devs are using NuGet for adding libraries to their projects.  

Is there any chance of this happening with paper.js?

**Comment by darcythomas** [comment]
@lehni 
@tommck 
I have created a nuget package for paper.js

https://www.nuget.org/packages/paperjs/

Github page for package: https://github.com/darcythomas/paper.js.nuget
