### ISSUE TITLE
Which paper JavaScript file do I use in the dist directory?

### ISSUE THREAD

**Issue by samueller** [paperjs/paper.js#296]
There are 3 different versions of paper.js that I can't find an explanation for the differences of. Which do I use?

from the dist directory:
- paper-core.js
- paper-full.js
- paper.js

There's also a 4th, `paper-node.js`, but I assume that's for Node.js which I'm not using at the moment.

**Comment by mthuurne** [comment]
This question is answered in the "Which Version to Use?" section of the top-level README, but that file is not included in the distribution package. I think it would be useful to either include README.md in the distribution .zip file or add a short README in the "dist" directory explaining what the different .js files contain.
