### ISSUE TITLE
Can't create PNG image from Canvas

### ISSUE THREAD

**Issue by samueller** [paperjs/paper.js#329]
I'm trying to use FileSaver.js to create a PNG download from a Canvas. Works great when working directly with the canvas from JavaScript. However, with paper.js, for some reason it works with the canvas differently and I get blank images.

Has anybody been able to create a PNG image from a paper.js canvas?

Seemingly related but not important to me, if I draw directly on a paper.js canvas with JavaScript, I don't see any of those graphics. However, if I then save them with FileSaver.js, I see only the directly drawn graphics.

**Comment by LokeshLalwani** [comment]
Hello Samueller, Could you show me your code for converting html canvas to a png image using FileSaver.js
