### ISSUE TITLE
v0.9.11: Error: "Http is not defined" when using external script file

### ISSUE THREAD

**Issue by FR6** [paperjs/paper.js#332]
When using the latest version (0.9.11) I have the error: "Http is not defined" (line 11938 of paper.js).

But only when using external script file:

``` html
<script src="js/myscript.js" type="text/paperscript" canvas="canvas" charset="utf-8"></script>
```

And it works properly in 0.9.10 and 0.9.9.

**Comment by Krispomoho** [comment]
I sitll have this problem.But only when using external script file.
`<script type="text/javascript" src="js/paper-full.min.js"></script>`
`<script type="text/paperscript" src="js/demo.js" canvas="myCanvas"></script>`

**Comment by lehni** [comment]
Which version are you using? `paper.version`?

**Comment by Krispomoho** [comment]
I'm sorry.I just found it works correctlly in V0.9.25.
