### ISSUE TITLE
Event Propagation issue

### ISSUE THREAD

**Issue by khurramraheel** [paperjs/paper.js#339]
I have written a following code

A global tool.onMouseDown function

```js
var rect = new Path.Rectangle(new Point(300,200), new Size(200,100));
rect.onMouseDown = function (event){
    event.stopPropagation();
    event.stopImmediatePropgation();
}

function onMouseDown(event){
    // do some work here
}
```

so what I expect is when I click on the rectangle. rectangle's onMouseDown handler would stop coming to global onMouseDown since I used event.stopPropagation(). but it does not seem to work, global onMouseDown function is still firing. Is that some kind of bugs in event lifecycle?

**Comment by lehni** [comment]
So here's the deal:

Tool events are handled separate from item events, and the propagation si handled separately. By convention, a item mouse handler cannot stop a tool mouse handler from firing.

But:

You can install mouse handlers on the view now, and these get fired last, after all the item related code is handled. And if an item stops propagation, the event will not reach the view.

I hope this helps.
