### ISSUE TITLE
onFrame event does nothing in Javascript direct mode

### ISSUE THREAD

**Issue by nardove** [paperjs/paper.js#35]
I am using the new Direct Javascript Mode with global scope, I believe I got the setup working correctly as I can view my drawings but the onFrame event is not working, it is not very clear how to set this up in the tutorial so I may be missing something, here is my js code:

``` javascript
paper.install( window );

$(function() {

    var canvas = $("#canvas").get(0);
    paper.setup( canvas );

    $("#image-list").addClass( "image-list-dynamic" );

    var thumb = new Thumb( new Point( 50, 100 ), new Size( 100, 200 ) );
    view.draw();
});


function onFrame( evt ) {
    console.log( "new frame" );
}


// ---------------------------------------
// THUMB OBJECT BEGINS

function Thumb( center, size ) {
    console.log( "thumb created: " + center + ", " + size );

    this.center     = center;
    this.size       = size;

    this.path       = new Path.Rectangle( this.center, this.size );
    this.path.fillColor = "black";


    this.update     = function() {

    };
}

// THUMB OBJECT ENDS
// ---------------------------------------



```

"Draw the view at the end, since that is now only automatically handled when a view.onFrame handler is installed" how do I do that I mean install a view.onFrame handler?

**Comment by manuelro** [comment]
I can't get paperjs to recognize my `onMouseDown` function and trigger it. I'm using coffescript and plain javascript (not paperscript). Any idea why?

```coffescript
onMouseDown = (event) ->
    console.log event.point
```

Which translates to
```javascript
onMouseDown = function (event) {
   return console.log(event.point);
};
```

I wonder if I have to attach the function to any object, I tried attaching it to `paper` object but no luck so far.

**Comment by lehni** [comment]
Yes in JavaScript mode you have to attach it to a tool. See *Working with Tools* here: 

http://paperjs.org/tutorials/getting-started/using-javascript-directly/
