### ISSUE TITLE
Cannot hitTest selected handles only

### ISSUE THREAD

**Issue by memononen** [paperjs/paper.js#361]
Currently it is not possible to hitTest selected segment handles only. This leads discrepancy between what is seen on screen and what hit results are returned.

The follow change in Path._hitTest() should make `{ selected: true, handles: true }` behave as expected:

```
		function checkPoint(seg, pt, name, check) {
			if (check && point.getDistance(pt) < tolerance)
				return new HitResult(name, that, { segment: seg, point: pt });
		}

		function checkSegmentPoints(seg, ends) {
			var pt = seg._point;
			var state = seg._selectionState;
			var testSegment = !options.selected || (options.selected && (state & 4));
			var testHandleIn = !options.selected || (options.selected && (state & 1));
			var testHandleOut = !options.selected || (options.selected && (state & 2));
			return (ends || options.segments) && checkPoint(seg, pt, 'segment', testSegment)
				|| (!ends && options.handles) && (
					checkPoint(seg, pt.add(seg._handleIn), 'handle-in', testHandleIn) ||
					checkPoint(seg, pt.add(seg._handleOut), 'handle-out', testHandleOut));
		}
```

I'm not sure if this is 100% correct behavior, though, as currently the selected means selected items. I'm trying to hit test the segments of select items, and handles of selected segments.

p.s. Sorry about not submitting pull request, for some reason I cannot install the tools required to build Paper.js (npm fails to install bower).

**Comment by lehni** [comment]
I am closing this, since it's a very old issue and there was no more activity on it. Feel free to reopen.
