### ISSUE TITLE
strokeColor and fillColor does not import data

### ISSUE THREAD

**Issue by khurramraheel** [paperjs/paper.js#392]
I used a gradient on a path and called path's fillColor.exportJSON(), now after some manipulation, I am trying to reload the new gradient string in the path's fillColor but It seems that fillColor and strokeColor only provide exportJSON but not importJSON, so setting gradient string to the fillColor property seems not  possible.

var gradientString = '[["dictionary",{"#12":["Gradient",[[[0.41569,1,0.27059],0.6],[[0.14118,0.54118,1],"0.7"]],false]}],["gradient",["#12"],[100,100],[300,200]]]';

I tried as follows

path.fillColor = gradientString; 

and

path.fillColor = JSON.parse(gradientString);

**Comment by lehni** [comment]
This is finally all supported now, e.g.:

```js
var json = [["dictionary",{"#5":["Gradient",[[[1,1,0],0],[[1,0,0],0.5],[[0,0,1],1]],false]}],["Color","gradient",["#5"],[339,196],[499,356]]];
var color = new Color();
console.log(color.importJSON(json) === color);
console.log(color);
```
