### ISSUE TITLE
Import SVG + Edit SVG + Export SVG = </g></g></g></g></g></g></g>

### ISSUE THREAD

**Issue by lilo003** [paperjs/paper.js#417]
Hi, 

I am performing tests importing SVG editing and exporting. 

When import again my svg can not make the selection of a single element because it is within multiple groups.

Example:

<svg x="0" y="0" width="1920" height="748" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"><g fill="none" stroke="#ff0000" stroke-width="5" stroke-linecap="butt" stroke-linejoin="miter" stroke-miterlimit="10" stroke-dasharray="" stroke-dashoffset="0" font-family="sans-serif" font-size="12" text-anchor="start" mix-blend-mode="normal"><g><g><g><g><g><g><g><g><g><circle cx="500" cy="500" r="50"></circle></g></g></g><polygon points="184.549,117.553 159.549,99.389 150,70 159.549,40.611 184.549,22.447 215.451,22.447 240.451,40.611 250,70 240.451,99.389 215.451,117.553" fill="#ff0000"></polygon></g></g></g></g></g></g></g></svg>

![import](https://f.cloud.github.com/assets/2714802/2364544/b0f06844-a67b-11e3-98e7-ad3ee2026616.PNG)

How best to handle this?

Thank you

**Comment by lehni** [comment]
Closing this since #483 has more information now.
