### ISSUE TITLE
Non-scaling stroke is needed

### ISSUE THREAD

**Issue by nicholaswmin** [paperjs/paper.js#418]
Many CAD apps have a feature that is called a ''hairline'' stoke, otherwise called a ''non-scaling stroke'' in SVG. It allows a consistent amount of stroking irregardless of zoom levels.

It is critical when designing very detailed drawings since the stroke never gets in the way of the designer irregardless of the zoom level. There should be more uses which i am not aware of.

Ideally this would be an attribute of an element just like stroke and fill.

**Comment by plong0** [comment]
3 years later and this saved my day!   thanks y'all!

**Comment by SteamWind** [comment]
Sorry but how do you apply a false strokeScaling on zoom? It doesn't seem to apply on layers.

**Comment by bentedder** [comment]
@lehni you're amazing!

**Comment by WesleyKapow** [comment]
> Question: Should the view.zoom be taken into account here or not? Does a non-scaling stroke always remain true to the pixels?

Arg! My use case is the opposite here where I want non-scaling strokes but I do want view zoom to scale the stroke. Think of a typical drawing application. Zoom should zoom everything you see, including stroke, while resizing a shape should not impact stroke scaling.

Any pointers on how to implement this would be great!

**Comment by RickMohr** [comment]
Wesley, when resizing your shape, use `Item.applyMatrix = false`. (You can set it back to `true` when you're done.)

**Comment by WesleyKapow** [comment]
I have `applyMatrix = false` set globally. How can I resize my shapes without impacting their scale?

**Comment by RickMohr** [comment]
Just like I said. Setting applyMatrix=true on the shape itself overrides your global setting. Then you scale, then you set it back to false.

**Comment by WesleyKapow** [comment]
Ah you had the opposite in your first reply (set to false and then back to true). But yes of course, set to true, resize, set back to false. That may work for me. Not sure yet as I don't want to apply rotations and skew. There's some trickery I can probably perform here like undo rotation, resize, re-apply rotation or keep track of applied rotation in `data`. I'll give it a shot, thank you, much appreciated!
