### ISSUE TITLE
Scoping problem w/ multiple canvas elements

### ISSUE THREAD

**Issue by Doik** [paperjs/paper.js#447]
Hey. 
I might have run into a scoping problem when working with multiple canvas elements. I've built a small testcase: 

https://gist.github.com/Doik/9974554
(it only needs paper.js lying around in the same directory)

What happens:
I have two visible and separate canvas elements:
The first canvas works with two layers:
1. a visible node-layer for all nodes in canvas1
2. a hidden prerender-layer, which I use to render every type of node once. It's used like a kind of blueprint for each type of node: When I draw a node, I take the blueprint for this nodetype, clone it, and add it to the node-layer.

The second canvas works with one single object-layer, to render a small bunch of different objects.

Now, if I add a timeout (or a server call to get the data for canvas1) before I render nodes in canvas1, the blueprints from the prerender-layer in canvas1 are visible in canvas2, where they shouldn't be. They don't just appear there, I also see them in the children-array of the object-layer in canvas2.

If I remove the timeout, the problem doesn't occur.

(After loading the testcase, mouseover the second canvas, to trigger a redraw, to see the misplaced items)
(I could replicate this in the current versions of Chrome, FF, Safari)

**Comment by ericMLindgren** [comment]
I know this is an old issue but I'm having a hard time finding any working examples of this anywhere. I have some pretty modular code with a controller that is trying to control two different paper scenes on different canvases. I'm having the same problem with scoping. Anyone have an working code example of this scope switching I could look at?
