### ISSUE TITLE
cursor property for item

### ISSUE THREAD

**Issue by khurramraheel** [paperjs/paper.js#457]
Item should have a cursor property available on item's style object

**Comment by lehni** [comment]
I think this is something people would probably implement on their own through CSS. It is easy enough to change the CSS class of the container that the canvas resides in based on the user's actions. I prefer not to have paper.js modify the CSS styles of things outside the canvas. Does this make sense? A simple coding example would of course be helpful to illustrate how to do this.

**Comment by errorx666** [comment]
I also think this would be useful functionality.  Consider a scene with many possible Items with click handlers.  It becomes cumbersome and error-prone trying to programmatically predict whether a click at a given point would trigger an onClick handler or not, and a "pointer" cursor for clickable UI elements is user experience 101.  It's a ubiquitous requirement for any project using mouse events.

>  I prefer not to have paper.js modify the CSS styles of things outside the canvas.

Modify the style of the canvas element only, then; or, just fire e.g. an onCursorChange event and let the API consumer decide how that gets applied (e.g., inline styles, className).
