### ISSUE TITLE
Path.unite() returns different result each time you run the script

### ISSUE THREAD

**Issue by ifabio** [paperjs/paper.js#473]
Drawing and merging two paths with Path.unite(Path), the CompoundPath returned is different each time.
Here's the Gist code:
https://gist.github.com/ifabio/e24408cb94420192e036

**Comment by lehni** [comment]
@signalwerk Nice script! And good news for you: I can't reproduce your error anymore with the latest changes on the master branch! The script runs forever and crashes sketch though : )

**Comment by signalwerk** [comment]
@lehni sorry for the late respond. I tested now the master branch and can confirm that it's working. I also modified the sketch so it will just test 20 runs before it gives up. Thank you for your work.
