### ISSUE TITLE
Is there some thing like unsmooth?

### ISSUE THREAD

**Issue by khurramraheel** [paperjs/paper.js#480]
A little wild issue, but I think once we smooth a path, We can not get it back to its previous state, like unsmooth() or something like this.

**Comment by Pamicel** [comment]
Actually you can by removing the handles on each segment of your path like so : 
```
		for (var i = 0, l = path.segments.length; i < l; i++) {
			var segment = path.segments[i];
			segment.handleIn = segment.handleOut = null;
		}
```

**Comment by lehni** [comment]
`path.clearHandles()` does this too now.
