### ISSUE TITLE
Boolean unite and subtract problem

### ISSUE THREAD

**Issue by doom-fr** [paperjs/paper.js#487]
Hello,
I have a problem with unite and subtract functions.
Below, you will find my test code tested in http://sketch.paperjs.org

It works as is, but if you uncomment the `.unite(p5)`, the p5 circle is not unionned with the others (the circle in the left quarter of moon).

If you uncomment also the `.unite(p6)`, the p5 is now subtracted instead of unionned. p6 is well unionned.

If you change p6 to Point(60,40), p5 is well unionned and p6 has the problem of unionning.

I have make a post on stackoverflow (http://stackoverflow.com/q/24026810/1619521) to take some help and someone answer me it is maybe a bug of paperjs, so I open this issue.

What goes wrong ?

Thx

The test code :
```
var postyle = { fillColor:'grey', strokeColor: 'black'}

var p1 = Path.Circle({
        center: new Point(80, 50),
        radius: 50
    })
var p2 = Path.Circle({
        center: new Point(200, 50),
        radius: 50
    })

var p3 = Path.Circle({
        center: new Point(120, 60),
        radius: 50
    })
var p4 = Path.Circle({
        center: new Point(190, 60),
        radius: 15
    })
var p5 = Path.Circle({
        center: new Point(50, 60),
        radius: 10
    })
var p6 = Path.Circle({
        center: new Point(80, 40),
        radius: 10
    })

var pos=p1.unite(p2)
var neg=p3.unite(p4)

var boolp=pos.subtract(neg)

var path = boolp//.unite(p5)//.unite(p6)

path.style=postyle
```

**Comment by lehni** [comment]
Yes there's indeed an issue here... I will try and come up with a simpler test-case for easier debugging.

**Comment by lehni** [comment]
It looks like all the recent work on the boolean code has solved this issue. Download the next nightly and see for yourself.
