### ISSUE TITLE
minor bug with empty view and scrollBy(NaN, NaN)

### ISSUE THREAD

**Issue by martinmeeser** [paperjs/paper.js#489]
By changing one thing in my program I created following error (I am using the nightly build Jun-11 - tonight).

paper.setup('canvasId');
var point = new paper.Point(NaN, NaN);
// point.x = NaN, point.Y = NaN
paper.view.scrollBy(point)

// now every time the mouse moves over the canvas an exception is thrown at view.getBounds() line 10491

**Comment by lehni** [comment]
Closing as I think we've come to a conclusion.
