### ISSUE TITLE
Named layer access via project

### ISSUE THREAD

**Issue by martinmeeser** [paperjs/paper.js#491]
From my point of you it might be useful to have a named access to the project's layers as one has with named items in a group.

var layer = new paper.Layer({name: 'test'});

// later in code

var theLayer = paper.project['test'];  // IMHO this would be nice

currently I am doing:

var theLayer = paper.project.getItem({name: 'test');

// this is ok of course ...

**Comment by lehni** [comment]
This took way too long, but will finally be in the next release.
