### ISSUE TITLE
Is it possible to set alignment of a stroke?

### ISSUE THREAD

**Issue by cosss** [paperjs/paper.js#494]
I'm talking about this issue
http://stackoverflow.com/questions/7241393/can-you-control-how-an-svgs-stroke-width-is-drawn

**Comment by georeith** [comment]
@lehni Apologies for grave digging but thought this may be useful... someone has implemented inside and outside strokes without having to compute the offsetted paths manually: http://jsbin.com/nanaguleye/edit?html,js,output

Not sure how viable this is whether it has additional ramifications but would be a neat feature.

**Comment by georeith** [comment]
@lehni http://jsbin.com/revoniwuyo/edit?html,js,output

I've worked out how to do outside stroke using an in memory canvas which preserves the current state of the canvas
