### ISSUE TITLE
Unite path possible bug?

### ISSUE THREAD

**Issue by ontic** [paperjs/paper.js#505]
I've been playing around with paper.js the past few weeks and have really come to like it, but I've encountered mixed results when trying to unite paths.

I am trying to create an outline of multiple paths by uniting them, so they'll form a cut contour. The paths I am trying to unite were derived from an SVG font, explaining the problems I've encountered is difficult, so I've uploaded a functional demo to my server.

Demo URL: http://goo.gl/1SPeo1

Test Case 1:
Firstname: Adam
Font: Lobster
Result: The glyphs "d" and "a" are not united

Test Case 2:
Firstname: adam
Font: Lobster
Result: This works perfectly!

Test Case 3:
Firstname: Adam
Font: Lucida
Result: This works perfectly!

Test Case 4:
Firstname: Kaitlin
Font: Lucida
Result: The glyphs "i", "t", "l", "i" and "n" are not united

I'm sure if you try typing other words, you'll discover more problems/inconsistencies. I'd appreciate your assistance in resolving this.

Regards,
Adam

**Comment by lehni** [comment]
@masix, your issue is the same as #450, not the one described here.

**Comment by lehni** [comment]
@ontic if you want this looked at, please put your test case up again. thanks.

**Comment by ontic** [comment]
@lehni Yes I do desperately! I've re-uploaded the test cases and bundled the files in a .zip

https://www.adamdyson.com.au/sandbox.zip

**Comment by lehni** [comment]
Thanks! Got it now and will turn it into simpler test-cases based on JSON export of the problematic data.

**Comment by ontic** [comment]
@lehni Ok great! Let me know if I can help in any way.

**Comment by lehni** [comment]
With all the recent fixes to boolean operations in place, I am happy to announce that all the problems mentioned above are now working as they should!

@hkrish & @iconexperience, that's pretty good news I think! : )
