### ISSUE TITLE
ViewToProject, updateFocus errors (AMD)

### ISSUE THREAD

**Issue by vitalniko** [paperjs/paper.js#517]
I'm trying to use paper.js as AMD module. In my app prototype i get the following errors 
![c200e8c0fc64140b556e10bb20ea02ad](https://cloud.githubusercontent.com/assets/8628907/4131499/7069fbba-3347-11e4-9d0d-55cd7f5e4dbd.png)
This happens during mouse move after the page loses focus and regain it, for example switch to different browser tab and back. And the errors stop firing when the canvas is clicked (focused).
I tried to use the same code on isolated page without require.js and there's no such problem. Probably it is a context issue?

**Comment by lehni** [comment]
I'm still hoping to get a test case in order to reproduce this.

**Comment by lehni** [comment]
Closing for the lack of a response. Feel free to reopen if you encounter this again.
