### ISSUE TITLE
Numerical integration accuracy issue

### ISSUE THREAD

**Issue by kirillkh** [paperjs/paper.js#518]
Hi! I am using paper.js's source code as a reference to optimize my own code that deals with arc length. In particular, I was lacking Newton-Raphson in my inverse parameterization algorithm, and the one you use proved to be just the thing I needed.

But one thing is not working well for me. In Numerical.integrate() you do something I haven't seen in other places, namely you integrate between two t parameters a and b (as opposed to always setting a=0). I don't know enough math to figure out whether it is correct or not analytically, but in practice it introduces accuracy issues, demonstrated by the following code:

``` js
// verbatim copy of a private function in Curve.js
    var getLengthIntegrand = function (v) {
        // Calculate the coefficients of a Bezier derivative.
        var p1x = v[0], p1y = v[1],
        c1x = v[2], c1y = v[3],
        c2x = v[4], c2y = v[5],
        p2x = v[6], p2y = v[7],
        ax = 9 * (c1x - c2x) + 3 * (p2x - p1x),
        bx = 6 * (p1x + c2x) - 12 * c1x,
        cx = 3 * (c1x - p1x),
        ay = 9 * (c1y - c2y) + 3 * (p2y - p1y),
        by = 6 * (p1y + c2y) - 12 * c1y,
        cy = 3 * (c1y - p1y);
        return function(t) {
            // Calculate quadratic equations of derivatives for x and y
            var dx = (ax * t + bx) * t + cx,
            dy = (ay * t + by) * t + cy;
            return Math.sqrt(dx * dx + dy * dy);
        };
    };

    var ds =    getLengthIntegrand([0.000000,0.000000,100.000000,100.000000,200.000000,200.000000,-17.444029,-41.252811]);

    // produces output: 0.38959626747556086. expected output: 0
    paper.Numerical.integrate(ds, 0.5, 0.75, 16) - (paper.Numerical.integrate(ds, 0, 0.75, 16) -    paper.Numerical.integrate(ds, 0, 0.5, 16));
```

I would be happy to hear any input you have on this.

**Comment by lehni** [comment]
@kirillkh very interesting. Would you be willing to share that code?

**Comment by kirillkh** [comment]
The code is proprietary at this time, but I'll let you know if I decide to release it as open source eventually.

**Comment by kirillkh** [comment]
I outlined the ideas for the algorithm here: http://pomax.github.io/bezierinfo/#bezierinfo-comment-172
Since that happened almost a year ago, I can't remember what additional tweaks I made to the code after I wrote that, that comment describes the gist of it.
