### ISSUE TITLE
Inconsistent behavour between Paper.js editor and paperscript html

### ISSUE THREAD

**Issue by justin-hackin** [paperjs/paper.js#521]
I made the following sketch in the web editor:
http://sketch.paperjs.org/#S/rVZdb9owFP0rFi9NICQhXacOtif20EqdxmilPQAPITHEItiZ43Srqv73Xju240ClTtp4QMT33HPP/XJ4HtD0iAfTwf0Bi6wYBIOM5fJ5TRepKMKKM8HEU4XDNM/vCMXoC9o1NBOEUa9ihIraf15TBB9RkDo8skf8wLRlFW/82ZquxY5x5D2mHBFwn8wQ+dwCwhLTvSjgYDSSNGuxFoqmhEgdDdE0L/KLY9FwqqLBoTyiRhCqWJnyhXTyeJqTpg4Q6E+lbYF5hqloo2gOin+jFv1N5loT6p3Ah8lQmRa3/tAwKoFPkIiyZKx+38k/U3pMD3hJ6B5SrIk8AaUKOjE/Eh8prapslGIOEZVgST0nPCuxp0smg2I+RZarPW55poZYVVAVUrOyRvwza9Jj1XVVxGHdbAGcCU+ptyWQkVtqE1p1IInjAMGXxEkIh+J81wIncTxDUURoVuD6gS3+eJPExf0kuSgAl5zBDIo2xxtW4hpA18YRZ0I5Sv5APd5gsi8EYK5UPrJHP5o0f0i3901VMS68VnjQqQs6AYEJEnTcLq/U0uv//+TWO2gqcqsHpqviuCOb9bGy9QC1E+nqUDyOJN/xTXmmXc0AecYcRcYa7khZzlnJpJoLjvOLPsNSTVFP6WgSOxjBqju8k03RQzNyt9wyBOgyunbVbZkQ7Pg3bh/8frilHoJ3HK+6eO23yVhflN5KF1JnsDFoi+MZXHGtzsAGPkXpm7DlOjVmJauxqrzgDe7Lkdn8ggmTPYVsbKu7vdQsfTendRzL29xtquU4MXXuXewa748g+iuW0T/F0bU7djC4kqfWwzNnx4o1NO8NUe+lEcuXhlkC+74wsQ0nAJW8JfxO6R7usrZu45Xdmihx9yZKNgFavblSG+RmJ5MHU1iRRybDqIet1FyHbQwHrIxQY1qXqYBBgOtl7Nl1GtlFjOCO3/injuptgr2xN4EJG15+jGEEu2JGCTySoVPdAPWHwxLVgrMDfmv5DET1QA7svCBl7smjt5I+6fZLNw+Ww11z2pSl0+wCWpbLuw5MZiC7IbQUht3C+1dH1fCqxBfqYj6Lfj6pNpBjAt3w/2bLcXpo/1gMpqvNyys=

Then I simply copy-pasted the code into the first example here: http://paperjs.org/tutorials/getting-started/working-with-paper-js/.  Now what I get is not the same, the leftmost hole is missing.  When I make var i =-1 it works properly.  Insights appreciated :)

**Comment by lehni** [comment]
Apologies for the very slow reply. It sounds like we were running different versions between the two places. This happened sometimes in the past for a while, and there was a lot of progress being made on the boolean operations, which would explain the different outcomes.

We just finally finished working on the boolean operations, they are not extremely sturdy, handling all kinds of edge cases such as self-intersecting and touching paths, tiny hooks and loops, etc.

All the relating closed issues tell the story quite well: https://github.com/paperjs/paper.js/issues?q=label%3A%22cat%3A+boolean-operations%22+is%3Aclosed
