### ISSUE TITLE
project hitTest should return all results

### ISSUE THREAD

**Issue by Skalkaz** [paperjs/paper.js#536]
HitResult contains information about one item of the all possibles. It would be great the all, for example hitResult.items array

**Comment by piotrwitek** [comment]
+1 for events propagating down and hitTest returning array refactor, I was also forced to use them ugly workarounds :/, these events are a highly limiting factor right now.
Thanks for sharing your plans on improvement.

**Comment by Finu** [comment]
Hi.
I have two paths. One represents terrain and other - road. Click on the road should select land which is below road, Road should have no interactions or event - just render.
I'm not sure if it's helps any one - or does it have any grave consequences for performace of paper.js, or there is other proper mechanic for this - but I override function isEmpty of road path to return false. For this i can invoke event on path below.
It's just for disabling hit test for certain Item.

Solving this issue would be nice improvement

**Comment by pmros** [comment]
:+1:

**Comment by kaelumania** [comment]
+1 Maybe another workaround is to use `getItems(match)` with `match.overlapping: Rectangle`

**Comment by lehni** [comment]
@piotrwitek I just realized that events propagating and `hitTest()` returning all items is no related. Events propagating has to do with them going up the chain of parents, until one of them stops the event (bubbling). For event handling, it is enough for `hitTest()` to only return the first, top-most item, and then bubble up the event from there. That's also how HTML is handling it.

But I will implement a way to get multiple hit-results in one call. It will not be through `hitResult.items` as a hit-result object by definition describes the result on only one item. I need to think of a good way to implement this, still.

**Comment by piotrwitek** [comment]
@lehni thanks for your time looking into this issue, this was some time ago, but I'm sure what I meant here was related to only one point, to get multiple hit-result in one call, and probably I didn't express myself clear enough describing it.
What you said in the last paragraph, to add another method returning multiple hit-result, is exactly the point of this issue.

**Comment by lehni** [comment]
So I've been thinking about how to implement this in `Item#hitTest()` and `Project#hitTest()`. Here a proposal:

- There will be a new `options.match`option that can be set to a callback function. For each hit, this callback is called with the `HitResult` object as the argument.
- If the callback returns true, the hit-test is chosen and returned from the hit-test call.
- If the callback returns false, or nothing, `hitTest()` keeps searching for a matching hit-result.

This means:

- `hitTest()` will keep returning only one `HitResult` object
- If you want to get multiple hits, then you have to collect them yourself in the callback, and keep returning `false`

If this is too complicated, we can consider a second version, for example

- `Item#hitTests()` and `Project#hitTests()`
- `options.match` is supported, and all results for which it returns `true` are collected in an array, and returned in the end. If no `options.match` is defined, all hits are returned.

The naming is perhaps a bit weird... It could also be named `#hitTestMultiple()`, or `#hitTestAll()`.

Thoughts?

**Comment by piotrwitek** [comment]
@lehni I think both of your proposal would be useful to add into paper.js, but in my opinion they serve different purposes, and first solution is kinda hackish when you'd like to solve the problem of returning all hitTest items.

First solution would be useful to bring the possibility to integrate custom or some intricate selection logic in hitTest calls, that would not fit into the standard `options.match` object.

Second proposal is a fitting solution for discussed problem, though I like `#hitTestMultiple()` name, as it gives a lot of meaning to what it actually do, second would be hitTestAll (NB: hitTests is really weird).

**Comment by lehni** [comment]
Thanks for the feedback! I think I prefer 'All', because it returns all hits in that location, not just multiples.

**Comment by piotrwitek** [comment]
Thinking again I agree with you, "hit test all" of them seems better.

Pozdrawiam,
Piotr Witek

2016-02-14 10:46 GMT+01:00 Jürg Lehni <notifications@github.com>:

**Comment by lehni** [comment]
Finally done :)

**Comment by StratusBase** [comment]
It appears that hitTestAll is not available as a function on any item that I have attempted to call it on... Is something broken?

**Comment by lehni** [comment]
You need a `develop` version for now:

http://paperjs.org/download/#development-builds

**Comment by StratusBase** [comment]
Thank you!

**Comment by StratusBase** [comment]
Ok, so I have pulled / replaced my master file with the current script located here:

https://raw.githubusercontent.com/paperjs/paper.js/prebuilt/module/dist/paper-core.js

Still, the only available "hit" method on the project is "hitTest", nothing more...

**Comment by lehni** [comment]
Are you sure? The docs may be outdated...

<img width="524" alt="screen shot 2017-02-06 at 18 33 52" src="https://cloud.githubusercontent.com/assets/213275/22658620/15f0c474-ec9b-11e6-9364-607bfd69f992.png">

**Comment by StratusBase** [comment]
I'd be happy to start a Google Hangout and shoot you an invite so that you can see what I am doing if you'd like?

**Comment by lehni** [comment]
Sounds like a caching issue then... Make sure the new file is actually loaded in your browser. I am on the road right now, not available for hangout.

**Comment by StratusBase** [comment]
I assumed that too, I did a "Empty Cache and Hard Reload" in Chrome just to be sure, with the same result. Honestly it's not a huge deal as I can work around it... Just wanted to bring it to your attention.

**Comment by lehni** [comment]
Well, it's present here, so I am pretty sure you must be somehow using the wrong version... What do you see when you log this:

```js
console.log(project.hitTestAll);
```

or

```js
console.log(paper.Project.prototype.hitTestAll);
```
