### ISSUE TITLE
Cursor Precision Problem

### ISSUE THREAD

**Issue by Abdillah** [paperjs/paper.js#550]
Cursor point position wrong in toolEvent callback (e.g. `onMouseDown(event)`) function in firefox. Fine on google chrome. Here the pics
![screenshot from 2014-11-04 14 05 43](https://cloud.githubusercontent.com/assets/3030950/4895847/1a91af0a-63f1-11e4-9293-fca8b4125073.png)

**Comment by ActionCommunity** [comment]
Abdillah, about which attribute you are speaking? The style attribute? I have same problem, I resize the canvas when window is resized by jquery, after that, it doesnt track the mouse points correctly.

my canvas:
`<canvas #canvasElement *ngIf="data.Underlying.DrawingType===2" style="position:absolute; left: 65px; top: 9px; z-index: 10; right: 0;"></canvas>`

My resize method:
`let $canvasEl = <any>$(<any>this.canvasElement);
        $canvasEl.width(this.pChart.plotWidth);
        $canvasEl.height(this.pChart.plotHeight);`

can you please be more specific how to solve the problem!?

**Comment by lehni** [comment]
Manually resizing the canvas is not supported in paper.js. You need to resize it through `view.setViewSize(size)`.

**Comment by ActionCommunity** [comment]
Hi, thank you for you answer. But that does not fix it. Same effect when using this:

`paper.view.setViewSize(new paper.Size(this.pChart.plotWidth, this.pChart.plotHeight));`

I already checked the plot size to ensure that the problem isnt on my implementation. They are all correct. Any other ideas?
