### ISSUE TITLE
Mild suggestion for a different implementation of Curve.getSignedDistance()

### ISSUE THREAD

**Issue by iconexperience** [paperjs/paper.js#554]
The current implementation of Curve.getSignedDistance() returns a negative sign if the specified point is on the same side of the line as the origin, otherwise it returns a positive value. I think it would be better to have an implementation that returns a negative sign if the point is on the left side of the line and a positive value if the point is on the right side (or vice versa). The reason for this suggestions is that I tried to implement a visualization of the Convex Hull algorithm and found it much easier with the proposed implementation of getSignedDistance(), because the sign of the result is independent of the line's rotation.

The new implementation may also be more stable, as the current implementation has a very large nominator if vy gets close to zero. But this is only a guts feeling.

Here is the proposed implementation. It is based on this wikipedia entry:
http://en.wikipedia.org/w/index.php?title=Distance_from_a_point_to_a_line&section=8#Line_defined_by_two_points

<pre>
getSignedDistance: function(px, py, vx, vy, x, y, asVector) {
            if (!asVector) {
                vx -= px;
                vy -= py;
            }
            if (Numerical.isZero(vx)) {
               return vy >= 0 ? py - x : x - px;
            } else if (Numerical.isZero(vy)) {
                return vx >= 0 ? y - py : py - y;
            } 
            return -(vy * x - vx * y - px * (vy + py) + py * (vx + px)) / Math.sqrt(vx * vx + vy * vy);
        }
</pre>

Click on the link below to play around with the suggested implementation in a Paper.js Sketch (click into the canvas for testing - a green dot means positive sign, a red dot means a negative sign):

http://sketch.paperjs.org/#S/lVVNc5swEP0rWy6BxCGOp7nApD0k13QyjaeH1j0QWNtMZIkKQWAy/u/dFYgCdTpTZ2yk/Xj79q1E3jyZHNCLvKcXNOneW3ipynhfJxqyvDRrbAzcgsRXeFS5tHt/2PnXywVcL4Mg3uiNdPHhNhfiTgmlKfPsWSTpy5kNYNAiMfsesEgK1OEjGfwOgH3hQdW4Vv4NId8sR3aRS7avllxy4tlWQrRPKDA1mBG20RVar6tplBJ9zTUt+2rsKXF3QGmGfaYma9vkuH1qmMuv+vLuywVCJR9UVeK9epWUsq1kanIlfaypQABvHAf06UsyKvGOnfnqCu4VJLDPDRgsDSjZabUlGfeJzASWkQtmehT4FctKMJKVgQxrSuwKhgXTXcCbq1dGVpcFiSFQJzLFCD7CMRgI5FvwB8wR3ynnISIcS8cxR0BR4jRvJOGIVTwOqYosMSSa8f9QOfLiGJ9UVye7f6nLXfTMTvfQUQgbuHCcMhQmCZv4/eB2Htz+bwtDyJj7jDaJFbBioUa+A/50NE7KWVd8ElJduzOwzXVp7ipdYzyP4puxQ/OU7yRm93RV+Qz4lNs1eR02Cxjt2tFuNfGt2OfosGdYtwHMpu/uDnO7y3UqcGiErncQz8Inb44MPt3CEj7DxttpRLnxIKK1xmzjTRPdeydV0nTHdOO5DjkFLiB7bzJ/STKeUEHdFdRtTc+anvSg36T8Rq8apWfz+3DCbsVv4JLGMz1gdWuN7ZSWg/pSHVDnaSLCvPyOWvl1E8xQNZpKS8bpVSoIERqSiMqNq/X38jRs+x5s42AZlaCjDn/Edxh1n3JJaHBuq1P2eZfIC7ZfUHpgf62h4SW3dAUPfDTKX9r4Nsu6LBBxi0ejMvQ3vkh0Pei/1bPG5MWeytKLfvw8/gY=

**Comment by lehni** [comment]
Alright, now I get it. I didn't read your initial description correctly. Your proposal makes perfect sense, and I will implement it this way. The current boolean operations code requires the current implementation, so I will move that there as a private function instead.

**Comment by hkrish** [comment]
@iconexperience Thank you. This actually makes a lot more sense than the current implementation.
In the getCuveIntersections method, we are using it to consruct the "non-parametric" bezier curve. This should not create a problem if we merge this. (Not at 100% here, logically yes, but we need to test the implementation with your proposal first.)

@lehni May be we can use this in the boolean implementation (actually getCurveIntersections). As long as the sign switches when we go from one side of the line to another, it should work fine. (this is my feeling though we need to test it. Perhaps we can wait until we clear the other question regarding the intersection code?)

**Comment by lehni** [comment]
@hkrish I did test, and it did not work, which is why I've used @iconexperience's version in Line, and an inlined one in the fat-line clipping code. Will test more to be certain.

**Comment by lehni** [comment]
So when I run the boolean-test suite with the new Line.getSignedDistance(), it runs extremely slow (at least by factor 10 slower...) and produced errors regularly, perhaps at a rate of about 50%. I guess we do need that strange behavior after all?

**Comment by hkrish** [comment]
Okay, if it is that slow, we can't use it in Boolean code, even if it worked right. Let's keep the old implementation then. Besides, at least in the boolean case, we are trying to solve a problem that doesn't really exist! :)

**Comment by lehni** [comment]
It's not that it's slow. I think it's returning values that lead to the fat-line clipping code to loop for a very long time, and then produce wrong results. The method itself should perform similarly. I have a feeling fat-line clipping code is expecting this weirdly signed result.

**Comment by hkrish** [comment]
That has the same effect.
The fatline code only cares that we flip the sign if the points are on either side of the line. This switching of signs based on the slope of the line is still transparent to the fatline code —it's not that it is expecting any weird result, it just does not see this change since we don't rotate any lines within the boolean code.

I need to look at the code in detail, so as to what the issue is. Well it seems as it stands, the code is not a good fit for our existing use cases. That said, I appreciate that this proposal produces results which are easier to explain.

**Comment by hkrish** [comment]
Whoops!

https://github.com/paperjs/paper.js/commit/3781aedb227393e1080201c69544729ee1763e70 <https://github.com/paperjs/paper.js/commit/3781aedb227393e1080201c69544729ee1763e70>

:D

**Comment by lehni** [comment]
Great!! That fixed the one failing test out of 40576 in intersections.json of boolean-test that I couldn't figure out why it was going wrong. There are two other tests failing, but in those cases I believe that it's actually Java2D producing the wrong data. It looks like we're performing really well right now : D

**Comment by lehni** [comment]
We still need to figure out why we can't use Line.getSignedDistance() in the boolean code though?

**Comment by lehni** [comment]
Alright, everything is going very smooth now, except: @hkrish's fix above now causes the ol' BooleanOperations.html file to have hick-ups. I'm pretty sure that the fix is correct, and the previous wrong behavior must have shielded some other issue... Here is how it's failing right now. @hkrish could you look into this? I can't tell why it's happening.

![screen shot 2015-01-04 at 01 14 27](https://cloud.githubusercontent.com/assets/213275/5604225/57bfd2e2-93af-11e4-97f3-c56ef4c8edec.png)

**Comment by lehni** [comment]
I've fixed the above issue in the meantime already, and merged the boolean-operations branch into master. @iconexperience has suggested an improvement to his new Line.getSignedDistance() in  #611, and it looks like the fat-line clipping code works reliably with that one, so this mystery is also solved.
