### ISSUE TITLE
License (MIT) 

### ISSUE THREAD

**Issue by raphaelbastide** [paperjs/paper.js#556]
Why the name of the MIT license is not clearly claimed as it seams to be the license of paper.js?

**Comment by louisremi** [comment]
The filename LICENSE.txt is a convention, no matter what license is actually used. It should be kept that way, but MIT could be quoted in the README: "Distributed under the MIT license. See LICENSE file for details".

**Comment by raphaelbastide** [comment]
> MIT could be quoted in the README: "Distributed under the MIT license. See LICENSE file for details".

That sounds like a good solution.

**Comment by lehni** [comment]
I agree. Will do it this way.

**Comment by lehni** [comment]
Finally got around to it : )
