### ISSUE TITLE
Rectangle with 0 width can't be given any other width

### ISSUE THREAD

**Issue by georeith** [paperjs/paper.js#558]
Example: http://sketch.paperjs.org/#S/bZFBb4MwDIX/ipVLQUKReqXaabtOmtZj20MAA1GDjSCsbBX/fUmgbFI5RIr9vWc/JXdBqkGRiuMVbV6LRORc+PpLdaAtNoczlQPlVjMB0zsPPb7xjSKM4X4mCBp4AcIbHGvVovzE3CqqDEaBA7SsyaaAsnC+D18kM+j1D6Zw2iewvyytUhvzyoa7FHaZUfl15/tT7FJM7mxk6VS1ZvGZudOVJpfo377DA4YogbVr/8Ga4Ap66e7RPCiZPfE6olHjn0yNWzL/JDLjgYpeGiz9QjdQjk/QWetA1bhBLbeL8/uJZWwtN4vV48n9XNahuoYcvUhPl+kX

(Updated with a better example, still suffers from issue but slightly more reliable).

The issue is when you try to set a rectangle's `right` or `bottom` bounds to a point before the previous `left` or `top` bounds and vice versa, even if the next command is to ensure that is still a proper rectangle.

In the example the issue is reproduced when the mouse is dragged behind the origin point and the `left` and `right` and `top` and `bottom` properties are swapped across the negative axis. Sometimes it works, most of the time it doesn't.

I'm pretty sure this is caused because no matter which side you want to send over the axis first it will overlap it's opposite side and create an invalid rectangle. Is there a way to change both these properties in one go before they get recalculated?

Compared to this example which always works because the sides are never swapped: http://sketch.paperjs.org/#S/bVFBboMwEPzKypcQCSHlCmov7bVS1ByTHAwsYMXsIjBNaMTfaztAIpWDDzszOzMr3wXJGkUsDhc0WSVCkXHu5h/ZgjJYJycqesqMYgKmL+47/OQrBbiF+4nAa+ANCK9wqGSD0TdmRlKpMfA8QMOKTAwY5XZv74bwQXTqF2M47kLYnSeoUFp/sOY2hk2qZXbZOHzc2hajfStdWlkuXVxnblWpyDZ6yUtm0lfxXLPg/ogCAo9EN3ifLKLb5Pq4MUq5p7yLNBbOYdYk/xWWqZxkMvSK0XV/zRmeOcNqTsrGcL3YDCtBhptnk2HOGe0fpi3Ki1/sRHw8j38=

# UPDATE

Ok, I've looked at this further and the issue seems to be that once a rectangle gets a width or height value of 0 it will always be 0... see these two examples:

Goes to 0 (drag cursor back over itself on an axis):  http://sketch.paperjs.org/#S/dZFBb4MwDIX/isWlILFIvVLttF0nTeux7SGAC1GDjSAMWMV/XxIoq9TuECn2957z5FwDkhUGSbC/oMnKIA4yzl39LRtQBqvdkc4dZUYxAdMHdy2+c08hRnA9EngNvAJhD/tS1ii+MDOSCo2h5wA1KzIJoMit79MV8Qxa9YMJHLYxbE9L66y0fmPNTQKbVMvssnH9KbIpJnueZGlksWZxmblRhSKb6O693Q36KJ7Va//GKu/yemHv4Twonj3ROqKSw59MDs9kbiUi5Y7yVjixnSaGBzIuZHwgvcpN6agcrP/lH3+JqijNIhsX2TwsY2pZo9BchHcWv0X7w2mD8uLztkFyOE2/

Never goest to 0: http://sketch.paperjs.org/#S/bZGxboMwEIZf5cQSkKilrESd2rVS1YxJBgMXsGLuIjAFmvDutQ0hkZIBCd/3/ccvcwlIVhgkwfaEJiuDOMg4d+dfWYMyWG32dGwpM4oJmL64bfCTOwoxgsuewDvwDoQdbEt5RvGDmZFUaAw9BzizIpMAitzmvt0hnkCj/jCB3TqG9WEeHZXWH6y5TmCVapmdVm4+RrbFaJ8XXWpZLF1cZ65Vocg2evje5gZ9Fc/Oy/zGKp/yvrDv4bQonjLRsqKS/V2T/SvNXYlIuaW8EU6220T/RIaZDE+kU7kpHZW9zb9NebheYf2klqiK0szuMLvD3c2YGtYoNBfhQ87fp/3XaY3y5Js3QbI7jP8=

**Comment by lehni** [comment]
Finally done! And the solution was rather elegant in the end...

**Comment by georeith** [comment]
@lehni Best Valentine's Day ever. Was just struggling with this, had to put a hack in to stop it going below epsilon.

**Comment by lehni** [comment]
:heart_eyes_cat:
