### ISSUE TITLE
Curve.getIntersections() finds intersections twice

### ISSUE THREAD

**Issue by iconexperience** [paperjs/paper.js#568]
This is sub issue 2 of 4 for #547.

In some cases, intersections points between two curves are found twice by <code>Curve.getIntersections()</code>.

In this example, three intersection points are found, while there should be only two:

<pre>
var crv1 = new Curve(new Point(509.05465863179415, 440.1211663847789), new Point(233.6728838738054, -245.8216403145343), new Point(-270.755685120821, 53.14275110140443), new Point(514.079892472364, 481.95262297522277));
var crv2 = new Curve(new Point(542.1666181180626, 451.06309361290187), new Point(179.91238399408758, 148.68241581134498), new Point(193.42650789767504, -47.97609066590667), new Point(423.66228222381324, 386.3876062911004));
var pth1 = new Path({segments: [crv1.segment1, crv1.segment2], strokeColor: 'green'});
var pth1 = new Path({segments: [crv2.segment1, crv2.segment2], strokeColor: 'blue'});
var ints = crv1.getIntersections(crv2);
for (var i = 0; i &lt; ints.length; i++) {
    var dot = new Path.Circle(ints[i].point, 3);
    dot.fillColor = 'red';
    console.log(ints[i]);
}
</pre>

Sketch:
http://sketch.paperjs.org/#S/jVNNb+IwEP0rVi4ENbU84/EX3T1x2lulPVIONLiASJPKcdkD4r/vGNpdWKnS5uBk7PfezHtWjlW/eo3VrPq5j7ndVk3VDutSH1ZJtOkA4rvo4y8xf0+HWJevx2HX59qoIJUha7zV4AKBaQSRkoAA1mpPzvkwbcRfBmotrUPvtXfaM7cR90hGegRLSgMZTfqGcY9OSWeM9QZQMa4RRksgdAZAASn6h2CApHLBBySH2nIH8iCDQYsYnEFE56bTh6f01H/Yw6/sEUr2YcEDeGXRspQBqaxWQVvAoMC7m94cggyA2usQSHlnfCOAvLQeORyW0UTB31KCloTWKI7KWWdUiYSc5EIFZa0py20XQg6R3Xj2oj1oZIr2VnKmlscMnIuiK4tveft5g4+rvK2PY9y8xj6PM7Eotys/ao72usRlI8achn2cD92QZmKySTH2k9N/K+OtMn6t/Ny9x2thtjmy8HmcTcw/+hzTGNu8G/qxLlIX6MuQRH3GM1g98OvbmSq72G/yljfu7qbiWKCCn4JcD/lqYjnfpbaLdSEtdkv5VgLmNC/yhcN4+bLruvOkzJykuJ78OW15nqGLshs2nxoX6qks/CM9p7jan1XHarZYnn4D

It seems that this behavious is caused by a too high value for <code>tolerance</code> in <code>addCurveIntersections()</code> that is currently set to 0.00001 (https://github.com/paperjs/paper.js/blob/master/src/path/Curve.js#L1062).

In line 1131 (https://github.com/paperjs/paper.js/blob/master/src/path/Curve.js#L1131) the algorithm checks if the t value has converged to a value less than <code>tolerance</code>. Sometimes this seems to give positive results, while it should be negative.

<b>:bulb: Proposed Solution </b>
Setting the <code>tolerance</code> to a smaller value seems to solve this problem. I was not able to find any curves pairs with intersections found twice twice after setting <code>tolerance</code> to 0.0000001. Performance was not affected noticeably by this change.

**Comment by lehni** [comment]
The wrong "freak curve pair" solution is most likely a product of the current imprecise version of the cubic solver that relies on trigonometric methods. @hkrish has implemented a much better solver that lives on the solve-cubic branch currently. When using this one, the wrong solution is not found anymore. Bounding box checks would have a penalty on performance, so I'd like to not go there ideally.

**Comment by lehni** [comment]
Ooops, I was wrong. It's still happening there too, will investigate.

**Comment by lehni** [comment]
Hmm, using hullEpsilon there causes a whole lot of new issues when running https://github.com/paperjs/boolean-test

**Comment by lehni** [comment]
@ontic if you want #505 closed please put your test case up again. thanks.
