### ISSUE TITLE
Curve.getIntersections() sometimes fails to find end point intersections

### ISSUE THREAD

**Issue by iconexperience** [paperjs/paper.js#570]
This is sub issue 3 of 4 for #547.

If two curves share an end point, <code>Curve.getIntersections()</code> often fails to find the end point intersections.

First an example of two curves where the end point is found, just as expected:

![intersec1](https://cloud.githubusercontent.com/assets/2122773/5121984/3c91e7ee-709b-11e4-9cf0-151b921ab1d3.png)
<pre>
var crv1 = new Curve(new Point(424, 404), new Point(-20.758506961373257, 34.44025018591475), new Point(4.821151642742507, 2.926157563833783), new Point(386.2868240711502, 444.63582484237725));
var crv2 = new Curve(new Point(386.2868240711502, 444.63582484237725), new Point(-15.616799186321998, -9.47848531807091), new Point(-93.22116080355067, -188.73464523341818), new Point(525, 488)); 
var pth1 = new Path({segments: [crv1.segment1, crv1.segment2], strokeColor: 'green'});
var pth1 = new Path({segments: [crv2.segment1, crv2.segment2], strokeColor: 'blue'});
var ints = crv1.getIntersections(crv2);
for (var i = 0; i &lt; ints.length; i++) {
    var dot = new Path.Circle(ints[i].point, 3);
    dot.fillColor = 'red';
}
</pre>
Sketch:
http://sketch.paperjs.org/#S/jZIxb9swEIX/CqHFMiIT5PFIHp128tQtQEfHgyMztmFFCijGHQz/956UBLGGoNUi3el9D/eOvBTt9iUWy+L3Keb6UFRF3e2G+rxNok5nLX6KNv4Rq7d0juXw9dAd21wiYCVQ4bwSX80FKOktWeWC08YbsL4SBiWiAqs02aDR2wmCkkBrqx2CRxYxADKA09ZbZ8gYT2YCGHISyBGg8gwq4DEQpTOWW4RgvAc7n98/psf2IwN8k+H/rCYBtZVOOx+CJmdAh0CVWASJnpCs0aS8CnqKBCOBIzpFylheDSdcaCLpDTq0YAxq0jRhLFgehYhjiM8cr/nweRYP23woL33cv8Q290uxHs5JftS6ErclbCrR59Sd4qprurQUs32KsZ1dvzb0D2eYOsP3zk/NW7w15ig9G4/j7GP+1eaY+ljnY9f25WD1Ln3ukihHPYvVPb9+jKhsYrvPB27c3c3FZZAKfgblrss3E8vVMdVNLAdofdzI12GJfPHe7QeG9fL52DTjpEzOUtzNxr9XvvFPKW5PI9QXy/Xm+hc=
<br>
Here is an example of two curves, where the end point intersection is not found:
![intersec2](https://cloud.githubusercontent.com/assets/2122773/5121982/357f11e8-709b-11e4-82a8-4a8722fa5890.png)
<pre>
var crv1 = new Curve(new Point(171, 359), new Point(65.26926656546078, 62.85188632229557), new Point(-37.43795644844329, 7.813022000754188), new Point(311.16034791674826, 406.2985255840872));
var crv2 = new Curve(new Point(311.16034791674826, 406.2985255840872), new Point(39.997020018940304, -8.347079462067768), new Point(-73.86292504547487, -77.47859270504358), new Point(465, 467)); var pth1 = new Path({segments: [crv1.segment1, crv1.segment2], strokeColor: 'green'});
var pth1 = new Path({segments: [crv2.segment1, crv2.segment2], strokeColor: 'blue'});
var ints = crv1.getIntersections(crv2);
for (var i = 0; i &lt; ints.length; i++) {
    var dot = new Path.Circle(ints[i].point, 3);
    dot.fillColor = 'red';
}
</pre>
Sktech:
http://sketch.paperjs.org/#S/jVJNT+swEPwrVi5NRWrZ64+1y3unnrghcSw9lNS0UUOCHNN3qPrfWQcQzQHxcnF2PTOe8fpcdNuXUCyLh2NI9aGoirrf5fq0jayOJ8n+si78Y6u3eApl/rvvmy6VEmXFlPHzin03reFgPVhrrNFWoKuYBe6MdM4qAPDG4ISwUMi1Qm+s1k5rBb5iyJ1UAkAIgUYTdcJQUnJphdLopUXtwFZMC8vBOwPGOC0cwnx++xgfu88I8EOE/5OaHO659yjImnReCyV0xRaOk4JAry0Ii2infheouLPgwQhtNJ2CREFKjc54QEFtZaYUbQ0ZsUgpWI7wmg5fU7jfpkN5HsL+JXRpWLJ1nhD/rGkg1yVsKjak2B/Dqm/7uGSzfQyhm12+L+cXZZgqw8/KT+1buBamGAMJj3b2Id11KcQh1Knpu6HMUh/Q5z6ycsQTWNzS8mek8jZ0+3Sgxs3NnJ0zlNGXkbs+XTnmqybWbSgzad1s+Gu+QHqXH/KZQ3j+3LTt6JSYsxh2s3H3Qm/9KYbtcSQNxXK9ubwD

<b>Proposed (Weak) Solution</b>
I found that changing the function <code>clipConvexHull()</code> at line 1250 in Curve.js (https://github.com/paperjs/paper.js/blob/master/src/path/Curve.js#L1250) to a more intuitive version solves the described problem in 95% of all cases. There may be a bug in the current implementation of <code>clipConvexHull()</code>, but to be honest, I do not really understand how it works. Also, I may be missing something in my implementation, but so far it seems to work.

Here is my proposed implementation:
<pre>
        function clipConvexHull(hullTop, hullBottom, dMin, dMax) {
            var qy;
            if (hullTop[0][1] &lt; dMin) {
                // left of hull is below dMin, walk through the hull until it
                // enters the region between dMin and dMax
                for (var i = 0, l = hullTop.length - 1; i &lt; l; i++) {
                    qy = hullTop[i + 1][1];
                    if (qy &gt;= dMin) {
                        var px = hullTop[i][0];
                        var py = hullTop[i][1];
                        var qx = hullTop[i + 1][0];
                        return px + (dMin - py) * (qx - px) / (qy - py);
                    }
                }
                // all points of hullTop are below dMin
                return null;
            } else if (hullBottom[0][1] &gt; dMax) {
                // left of hull is above dMax, walk through the hull until it
                // enters the region between dMin and dMax
                for (var i = 0, l = hullBottom.length - 1; i &lt; l; i++) {
                    qy = hullBottom[i + 1][1];
                    if (qy &lt;= dMax) {
                        var px = hullBottom[i][0];
                        var py = hullBottom[i][1];
                        var qx = hullBottom[i + 1][0];
                        return px + (dMax - py) * (qx - px) / (qy - py);
                    }
                }
                // all points of hullBottom are above dMax
                return null;
            } else {
                // left of hull is between dMin and dMax, no clipping possible
                return hullTop[0][0];
            }
        }
</pre>

**Comment by lehni** [comment]
@hkrish, would you have some time to look into these four fat line clipping related issues? #565, #568, #570, #571

**Comment by lehni** [comment]
This is fixed, but I am keeping it open since @hkrish wrote this in commit 5fb75593c2de5a59c927176ea7c0a92940a086e6:
> Remove enpoint fix from curve-line intersections, since it's already handled

It appears to not be handled consistently, and I wonder if it should be in the new fat-line clipping code? It's not a problem to have this code in getIntersections(), just wanting to make sure we're not ignoring a bug.
