### ISSUE TITLE
Curve.getIntersections() sometimes returns a wrong location for end point intersections

### ISSUE THREAD

**Issue by iconexperience** [paperjs/paper.js#571]
This is sub issue 4 of 4 for #547.

When two curves share an end point, <code>Curve.getIntersections()</code> sometimes returns a wrong location for the end point intersection:

Here is an example. As you can see, the intersection is not found where the two curves share the end point, but at a different location.
![intersec3](https://cloud.githubusercontent.com/assets/2122773/5121978/2a83b136-709b-11e4-9ef1-1b94a67c4284.png)
<pre>
var crv1 = new Curve(new Point(171, 359),  new Point(205.3908899553486, -14.994581100305595), new Point(5.767644819815757, 28.49094950835297), new Point(420.1235851920127, 275.8351912321666));
var crv2 = new Curve(new Point(420.1235851920127, 275.8351912321666), new Point(-10.77224553077383, -53.21262197949682), new Point(-259.2129470250785, -258.56165821345775), new Point(465, 467));
var pth1 = new Path({segments: [crv1.segment1, crv1.segment2], strokeColor: 'green'});
var pth1 = new Path({segments: [crv2.segment1, crv2.segment2], strokeColor: 'blue'});
var ints = crv1.getIntersections(crv2);
for (var i = 0; i &lt; ints.length; i++) {
    var dot = new Path.Circle(ints[i].point, 3);
    dot.fillColor = 'red';
}
</pre>
http://sketch.paperjs.org/#S/jZI/T8MwEMW/ipWlqQiWffb5T4GpExsSY+lQUtNGDQlyTBmqfnfOAUQ6IJElufP7vdyzfSq6zWsoFsXjIaR6X1RF3W9zfdxEVsejZHesCx9s+R6PocxfD33TpVJaWTGFfl4x9tsFgVx54Zz3iEo7U7Frqbn3Gp2UQiiB6JGYXwS5NdZo7aR3Ei3aioHj2guvPQqnELy9ADQILkGhQ+lBSMiARU5K6akP0hgzn988xafuOwP8keFfTtNfX0vBrQXQFE5Yq5yifKg4SDAgvaWRjYNLBNDnda+tABTWISGAjqORBh1IpdHayy3RhkTa2EmKt7T/OYmHTdqXpyHsXkOXhgVb5VPi3zUdyrSEdcWGFPtDWPZtHxdstoshdLPzv53h0hn+dn5u38PUmJIMZDyOswvpvkshDqFOTd8NZbb6kr70kZWjnsTihl63I8rb0O3SnhpXV3N2ylJGT1Zu+zSZmC+bWLehzNCqWfO3vId0N7/sM0N6/tK07TgpkbMYtrNx9Uz3/TmGzWGEhmKxWp8/AQ==

<b> :fireworks: Proposed Solution</b>
The behaviour is cause by lines 1084 to 1086 of Curve.js (https://github.com/paperjs/paper.js/blob/master/src/path/Curve.js#L1084-L1086). Most of the cases in which the fatline of Q converges to an end point are two curves with an end point intersection. In these cases the intersection is either at t=0 or t=1. Therefore I suggest to replace lines 1080 to 1086 in Curve.js with the following.
<pre>
                if (tMin == 0 && v1[0] == q0x && v1[1] == q0y) {
                    tMaxNew = tMinNew = 0;
                } else if (tMax == 1 && v1[6] == q0x && v1[7] == q0y) {
                    tMaxNew = tMinNew = 1;
                } else {
                    tMaxNew = tMinNew = (tMax + tMin) / 2;
                }
                tDiff = 0;
</pre>

This checks if the curves intersect at an end point. If this is the case, it sets t to 0 or 1. In all other cases it sets t to the average of tMax and tMin, just like before.

**Comment by lehni** [comment]
Great, thanks! I'm pretty sure this also solves solves the "freak curve pair" problem you outlined here: https://github.com/paperjs/paper.js/issues/568#issuecomment-63792068

**Comment by iconexperience** [comment]
A little note one my intersection issues: I think it is still important to clarify the definition of an intersection. Are two curves that touch at an end point intersecting? Are two curves that touch only tangentially intersecting? This is quite important, because some algorithms count the number of intersections (like the winding rule algorithms) and they will produce wrong results, if intersections are reported wrongly. I also posted a question at https://groups.google.com/forum/#!searchin/paperjs/intersection/paperjs/jz_ZpK2qjzM/xERJuXFpPhsJ some time ago.

**Comment by lehni** [comment]
@hrish is the right person to answer these questions... I hope he'll find some time to look into these issues soon.

**Comment by lehni** [comment]
Interesting... The wrong solution got already fixed by b75def3f3afe0eb252f5364fb41ffb47175343d2, which was addressing #565. And the missing solution was fixed by fbd026ea0d9d9222b7493234dca5632ef6a8fbc9, which has addressing #570

**Comment by lehni** [comment]
Actually, what fixed the wrong solution was increasing the recursion threshold to 4 here:
    if (q0x === q3x && uMax - uMin <= hullEpsilon && recursion > 4) {

**Comment by iconexperience** [comment]
@lehni Regarding the definition of intersections: I think you answered this in https://github.com/paperjs/paper.js/issues/449

**Comment by iconexperience** [comment]
I am not sure if this issue should be closed, as I found another curve pair that produces incorrect results:

<pre>
var crv1 = new Curve(new Point(171, 359), new Point(211.28283338363133, -68.87975154264905), new Point(16.871423083326363, 23.260675237969906), new Point(397.60301383915134, 208.01252435198336));
var crv2 = new Curve(new Point(397.60301383915134, 208.01252435198336), new Point(-26.72794017762584, -36.849881197399725), new Point(-243.98797126980725, -243.37493616611425), new Point(465, 467));
var pth1 = new Path({segments: [crv1.segment1, crv1.segment2], strokeColor: 'green'});
var pth1 = new Path({segments: [crv2.segment1, crv2.segment2], strokeColor: 'blue'});
var ints = crv1.getIntersections(crv2);
for (var i = 0; i &lt; ints.length; i++) {
    var dot = new Path.Circle(ints[i].point, 3);
    dot.fillColor = 'red';
}
</pre>

![image](https://cloud.githubusercontent.com/assets/2122773/5610286/d1b145d0-94b4-11e4-96ee-db5a3ae83876.png)

My initially proposed change fixes this issue, but I will dive deeper into the code to understand better what is going on. Maybe I can also shed some light on why the new <code>getSignedDistance()</code> implementation does not work yet with boolean.

**Comment by lehni** [comment]
When i tried your fix, it caused other issues so I rejected it then. Many things have changed since, so I will give it another go now.

**Comment by lehni** [comment]
And regarding the definitions, I leave that up to @hkrish to define. I think depending on the situation, we want different results returned, so getIntersections() should probably receive an options parameter for more fine-grained control. @hkrish is about to compile a document that describes it all in more detail.

**Comment by lehni** [comment]
Fixed for good by #611
