### ISSUE TITLE
Canvas drawing doesn't work in iOS 8 Safari/Chrome

### ISSUE THREAD

**Issue by alexpersian** [paperjs/paper.js#575]
I'm in the process of building a whiteboard drawing web-app using paper.js. It works perfectly on all of my testing devices so far, except any device running iOS 8 or greater. Desktop Chrome, Firefox, Safari, IE, Android Chrome, and iOS 7 or earlier Safari/Chrome work great. (Mobile drawing is laggy though).

Does paper.js handle touch events in a way that prevents it from reacting to the ones that iOS 8 sends? Touching the canvas fails to create any paths.

My drawing code is very simple.

    var myPath;

    function onMouseDown(event) {
        myPath = new Path();
        myPath.add(event.point);
        myPath.strokeColor = WBAPP.penColor; // WBAPP is from main javascript file
        myPath.strokeWidth = WBAPP.penStroke;
        myPath.strokeCap = 'round';
    }

    function onMouseDrag(event) {
        myPath.add(event.point);
    }

    function onMouseUp(event) {
        myPath.simplify();
    }

    // hack for a save feature to grab the full screen as white instead of transparent background
    var rectangle = new Rectangle(new Point(0, 0), new Point(WBAPP.width, WBAPP.height));
    var rectPath = new Path.Rectangle(rectangle);
    rectPath.fillColor = 'white';

My web-app in question: http://alexpersian.github.io/html/whiteboard.html

Closed because I'm an idiot. Adding...

    document.addEventListener('touchmove', function(event) {
        event.preventDefault();
    }, false);
fixed the issue.

**Comment by lehni** [comment]
Closing, see https://github.com/paperjs/paper.js/issues/633#issuecomment-172369502
