### ISSUE TITLE
Breaking change in 0.9.21 regarding DomEvent exposure

### ISSUE THREAD

**Issue by georeith** [paperjs/paper.js#579]
I'm not sure how paperjs handles it's versioning, but there is a breaking change in 0.9.21 as opposed to 0.9.20.

`paper.DomEvent` is no longer accessible. I am currently using this to simulate `event.point` for events that paperJS doesn't handle e.g., mousewheel like so `paper.DomEvent.getOffset(event, canvasEl)`.

I see that `DomEvent` is not part of the reference so perhaps was never meant to be exposed, but it is definitely a useful addition and think it should be.

# Edit:
I can see that `DomEvent` is meant to be private:
```js
/**
 * @name DomEvent
 * @namespace
 * @private
 */
```
I can understand that you don't want the user manually using `DomEvent.add` or `DomEvent.remove` and messing stuff up (although there are many more ways they could mess stuff up), I think `DomEvent` should be made public and just make the functions you don't want to be accessible private.

**Comment by georeith** [comment]
@lehni Yeah that is probably a neater solution. Although I still think a direct method for converting an arbitrary mouse event's point to an Item's local coordinate space would be useful in some cases.

I can share my mousewheel implementation but there are tons of issues with determining the delta across operating systems and browsers which all report it differently, and getting something stable that works across the majority requires constant attention. My implementation doesn't really attempt to do that as its scope is less than that of the PaperJS on a whole, so not sure if it is really suitable.

I suppose it is something we could implement and refine over time.

**Comment by lehni** [comment]
There is View#viewToProject() and #projectToView() to converts project coordinates to view coordinates, and back, taking into account the current zoom level and all. There is also Item#globalToLocal() and #localToGlobal(), that converts project coordinates to item coordinates and vice versa, taking into account the scene graph hierarchy and nested matrices. That should suffice?

**Comment by georeith** [comment]
@lehni That works perfectly, that removed my dependancy on `DomEvent` entirely.
