### ISSUE TITLE
v0.9.21 group opacity doesn't work after rasterize

### ISSUE THREAD

**Issue by madvas** [paperjs/paper.js#588]
As you can see in this [fiddle](http://jsfiddle.net/6cshpm3u/) . When we apply opacity on group and try to rasterize activeLayer after, the whole group disappears from rasterized image. When we apply opacity on path, it works ok.

Thank you

**Comment by lehni** [comment]
Yes that looks like a bug. Here the same example on sketch:

http://sketch.paperjs.org/#S/rZLBTsMwDIZfJcplnaiitmIINu00CS4cEHAbPbhJaENDXKVhaCDeHafdNJA49IAURXF++/stJ5/cwavmS/7Q6iAbnnKJKsY78AyrFy1Dz9bM6Xd24/GtS+arJxe1CmRb041TB/kOQiPuKR9cbXWyzVJGq8jGrYx1pxrxbKzdoEVP1TOv1YzkEewJ8TeyGFAsZed0WGSRGJN/sypLJpF2aF6AUpvGWJXE3PkEmwuiX/6HzVGqvHH1I157dGGY31HADqQJe+Jl4mpCZ3mcQD59BIP002RxMoE+6JjdeYzNCJDB7PQt7LUXo2g+9NDtGIkOexMMOna2ZvFxizwrV/RfKq+h7dC40PPltvz6Bg==

**Comment by lehni** [comment]
I'm not quite sure which recent change fixed this, but it's now working in the develop branch : ) Will roll out a new release shortly.
