### ISSUE TITLE
Part of canvas not visible at load not usable

### ISSUE THREAD

**Issue by alexkurtz** [paperjs/paper.js#598]
I have a problem when using paper.js whith areas of the canvas that are not visible at load-time. Depending on the user device, screen is not always the same size, and sometimes the canvas gets hidden on the scrolling down area. If that is the case when loading, nothing can be plotted there (tested both in chrome and firefox). If the page is reloaded with that area scrolled so it becames visible, the area can be used, no matter if it gets hidden again.

Is this some issue with the library?

**Comment by lehni** [comment]
It's merged in!
