### ISSUE TITLE
Nonbreaking Space in Nightly Build

### ISSUE THREAD

**Issue by iconexperience** [paperjs/paper.js#602]
There is a 0xA0 character in the nightly build (16. December 2014). Here it is in paper-core.js:

![image](https://cloud.githubusercontent.com/assets/2122773/5475347/6076bad0-8618-11e4-991b-dbabde2c00ff.png)

InternetExplorer debugger is not happy about this character.

**Comment by jeeyoungk** [comment]
this is still an issue - can we please cut the build? new users of paper.js encounters this right away.

**Comment by lehni** [comment]
Apologies for the delay. This got snowed under. Will take care of it now.
