### ISSUE TITLE
Function splitPath(intersections) in PathItem.Boolean.js distorts path

### ISSUE THREAD

**Issue by iconexperience** [paperjs/paper.js#609]
If there are linear curves in a path, the function <code>PathItem.Boolean.splitPath(intersections)</code> may distort the path by setting handles of non-linear curves to zero. Below is an example that illustrates the problem. Both parts should be identical, but the second path, which is split at the "corner", is distorted, because one handle of the quadratic curve is set to zero:

http://sketch.paperjs.org/#S/lVbfT9swEP5XTp2EElGStmgPo4Np2xMS0pDYW4uQca/E4NqZ7RRNE//7zk7qJmlgww9N4py/7+67H+mfkWIbHJ2Nbp7Q8WI0HnG98s95DkIJByVzBTC1Ai61QhBuqbbM1NvnoPAZruk2SedL5feyjd7iT52EF1ool0wnkzHQTxpNflVsZZgT/HtlesYzb/xxko5hv3fq92ZtACnUAMdp22RdSfn7BiVyhyty1JkK6d3e+RltBssQV/R/ljnDlJXMYdJghmMkBzdIu7BmTySDcmgsgQutgDlwBcKSpDMKzXIEel0LNKv5orUl0kVNw33sdjG9zR7QXWnOPNRX50m9r+ntPJDaUjZJIKzwEOTeI9buBdt1pWqHoh04clbBWhtY4UYr60zggbIypbYUjNEbSmCJJnu0EFJ56XCTfdNaIlO0GZCTwrnSnuX5g3BFdZ9xvclLf+rR1lcyzO+lvs83zJJnuTU8907nA4gfrqafTlOo1ArNnlsKjsriUh1GkbTVtin8WSqg5ZV1BEr54kjCTrIJrem4frtbvlaYucGHDSpng1h+O7IYtKR/MEoidLAg0ZKQPY89BkmXLlgmUT24Yk4Wn0HS5fi4g7Bz0tb2B+cXwie5bZ3nYg1JgBtighOYpju47K6gtpT4o3IZheALJ9TqEN4Fveqfu1SvHnsHw/+BvtS3L1H9trad7LYiHUPokTGUBrfUIV7nC0oFXU9OOkJ7JKl5H4v07RWDXyEPmmd3JTM0+si+5aiXq6GDo6Mdc3YXPIHz8+ZoeDyEbp+I6LX4vbJwkJ8P2LYlA5TUoL1z3r9uaaSHbnRKupevJpBWGPO3+oUsg1EmbOwRinJxe5jcXSJoKoe5PiB9Uyw9vXcHItdKbMUKE1dPwmYeHkhIY0nhlvSlscwLGvJCgUPrgDOLg0Vaf68CV3bX7E1f0Sca0nS+pjwJXdmOmMP52TM5auI4nQ6l8OtLE2/0xcfE5DP7bemDImxok1dC2q0zIrqAKfXLO8lmr+HxGDYz7ip0Y/gopRTQ0DtK03SgCAcDfJszujZcXHHUdD6+dSmTS5et3U6mQqnvEzNchG82VW8Yl5UtkgamTbQbHMGleRx5/6To9yudof9h91TXT6X/e2NHZ4vbl78=

This behaviour is caused by lines 204-205 in <code>PathItem.Boolean.js</code> (https://github.com/paperjs/paper.js/blob/master/src/path/PathItem.Boolean.js#L204-L205):

<pre>
                segment._handleOut.set(0, 0);
                segment._handleIn.set(0, 0);
</pre>

I am not sure if I understand the code correctly, but maybe the lines should be changed to the following. This at least fixes the problem for me:

<pre>
                if (i &lt; linearSegments.length - 1) segment._handleOut.set(0, 0);
                if (i &gt; 0) segment._handleIn.set(0, 0);
</pre>

In my opinion this issue is responsible for many artefacts that we see with the current boolean implementation.

**Comment by lehni** [comment]
@iconexperience do you have a boolean operation example where this problem is also occurring? Would be good to build a unit test for it...

**Comment by lehni** [comment]
I think @hkrish has already fixed this in 1c9d1de380fd8e01a78460b3e5bcc48eb7776ddb, but it's in the boolean-operations branch that has a couple of other issues that I still  need to resolve. I will merge this one into master after some testing.

**Comment by iconexperience** [comment]
@lehni 
I will send an example within the next hours.

**Comment by iconexperience** [comment]
Here is a simple example:

http://sketch.paperjs.org/#S/hZHPbsIwDMZfxcqpSBXQcAPtHSbBbeXgpWaNME6VP0wI7d0Xsk6DwbRL5NjfZ/9kn5XggdRSrfcUTa9qZVx3+c9mMGDsG0DpSqQBPUGPvANjvWEKNeAw8MnKGySxkSD0LnEHnkLiCFYAR2krrRzRjx2fQOgdnnNcTVatlOT04I60cVWpOCuxaubzGvIz+dGgN/cSfSMx7AL9ar1LzKc1MZlIXZ4efaLVNZJ+hKT/QLqepx8jNTeSeyT9P9IiJ7/oy2qrYvv2L6bRowTGXBiJijlf79UT7ocLSlDLl+3HJw==

**Comment by lehni** [comment]
Great, thanks! I've cherry-picked @hkrish's commit, and cleaned it up a bit. Works like a charm! Closing this.

**Comment by lehni** [comment]
The example actually doesn't result in a circle right now, due to #449. But the issue outlined here with spitPath() is now resolved.

**Comment by iconexperience** [comment]
Great, we are getting closer to a working boolean! How much is left in the Boolean branch that awaits merging into the Master branch? Or in other words: should I test against both branches during the next days?

**Comment by lehni** [comment]
It's down to this one commit by @hkrish that I don't fully understand and that seems to produce some errors in boolean-test: 6c6ad76c94190e6eca0ef87a83393f9ee005f769
I will look into this with him. But we still need to resolve #449 and #450 in order to get to fully functioning boolean operations, and that part will be rather tricky.

**Comment by iconexperience** [comment]
Thanks, I will ignore these two issues and focus on other glitches and potential improvements during the next days. 

If you come to the point that only issues 449 and 450 are missing for a complete implementation of the boolean functionality, you should be aware that you have done some superhuman work already.

**Comment by lehni** [comment]
I just managed to squash the nasty bugs from 6c6ad76c94190e6eca0ef87a83393f9ee005f769 here: 5f3df1f5a16c4ae0e4ee216b386fbd6ba78ffaf4, 72bd150a34e93fc823adaea75fccffd06715cada and already merged boolean-operations into master, closing #610 as well. Seems all pretty solid now!

**Comment by lehni** [comment]
Issue #541 also still needs fixing.
