### ISSUE TITLE
Subtracting a ring from a square produces strange results.

### ISSUE THREAD

**Issue by lehni** [paperjs/paper.js#610]
```js
var square = new Path.Rectangle({
    position: view.center + [140, 0],
    size: 300
});

// Make a ring using subtraction of two circles:
var inner = new Path.Circle({
    center: view.center,
    radius: 100
});

var outer = new Path.Circle({
    center: view.center,
    radius: 132
});

var ring = outer.subtract(inner);
var result = ring.subtract(square);
result.fillColor = 'red';
result.selected = true;
```
Should produce this:

![screen shot 2015-01-04 at 22 03 54](https://cloud.githubusercontent.com/assets/213275/5607470/a5e25ae0-945d-11e4-9770-05e06248789e.png)

Currently produces this:

![screen shot 2015-01-04 at 22 03 58](https://cloud.githubusercontent.com/assets/213275/5607471/ac4f43d4-945d-11e4-9d6e-d5ebf7516999.png)

**Comment by iconexperience** [comment]
Not sure if you noticed, but the result is correct in the Paper.js Editor:

http://sketch.paperjs.org/#S/rZHBbgIhEEB/ZcJFm27WtfZE48lzk6Y9qgdkRyVLwcLgJjX+e5klVpv2WBIgMI/hTeYknHpHIcVbh6T3ohLat3w+qgDxI6mAMAeHPbwo2tevqEm5ncXxaRVWDvI4+GjIeCfhaLCvNTrCAPewnD42FTTr6gJG84kSZk3DF+e7J954TibwrDoEBcG4HaTIa0wbCkpzYvBboN6DNkFbjJLfsJ1xLn90I7cYgKtZUfnh9S0TVGtSlDD9pcOpfaJ/SD17+CP1UOO8/FBfqhwPtRRwgDAmSxlj+kqVfhSsIPXWWLvw1rPtKGA7ug1GtLlf2OYYhYRDKHd4E1B1B28cRSGX6/MX

**Comment by lehni** [comment]
Yeah I did notice that, but that's with the old imprecise cubic solver. Everything is different now : )

**Comment by markmanx** [comment]
Hi all, this might be of use >> 
- The circle in this example should be split cleanly into two halves by subtracting a rectangle.
- Sometimes this happens, sometimes not (depending on the y-positioning of the rectangle)
- Setting a y-position of 10 seems to work, but a y-position of 0 does not.

http://sketch.paperjs.org/#S/dZDBqsIwEEV/JWRjhb4QBRcqrvwB0WXtIo3jMxiTMp1WRfx3J0WKIO7m3jtzZpKHDOYCciF3ZyB7krm08ZB0Z1BYh1asRICr2Bg6qTVrD1mhc6HLXMz0eLkPqUkdW+/vO/BgCQ48QtgCZ/uQMMjuG1ObGlD1sC27Jvx/8IrJnKupLhM2Df3C9lkdG0cuBnXj4G+qv/w7+3o4omkr1v2xXBIaS1nqH56AcIkdZMPuD80DA5YhnYOrshAI8B0enffr6CNyOqp8C6Ml/2SFYM51dIEauSjK5ws=

**Comment by lehni** [comment]
@markmanx since this issue is already closed, could you create a new one for it? it's not the same problem.
