### ISSUE TITLE
Improve new getSignedDistance() function

### ISSUE THREAD

**Issue by iconexperience** [paperjs/paper.js#611]
The new getSignedDistance() function can be simplified. In Line.js line 172 (https://github.com/paperjs/paper.js/blob/master/src/basic/Line.js#L172) the term

  -(vy * x - vx * y - px * (py + vy) + py * (px + vx))

can be changed to

  -(vy * x - vx * y ~~- px * py~~ - px * vy ~~+ py * px~~ + py * vx)) 

and finally to

  (vx * (y - py) - vy * (x - px))

The full line should look like this:

<code>return (vx * (y - py) - vy * (x - px)) / Math.sqrt(vx * vx + vy * vy);</code>

Note that this makes the code not only more readable and faster, but **also produces more precise results**. Maybe this will make the new <code>getSignedDistance()</code> function work with boolean code?

**Comment by lehni** [comment]
Sweet! For things like these, feel free to create pull requests so you get some credit in the commit history : ) I will try out the suggestion.

**Comment by iconexperience** [comment]
Just created my first pull request and signed your CLA.

**Comment by lehni** [comment]
Perfect. Will add you to the contributors also. What name would you like to appear under? : )

**Comment by iconexperience** [comment]
I actually do not care much, but my real name, Jan Bösenberg, would be fine.

**Comment by iconexperience** [comment]
One question: Did I accidentially commit my change directly to the master branch before creating the pull request? The commits list looks like I did that.

**Comment by lehni** [comment]
No that's the result of me merging it in : ) You don't have the access rights to do that.

**Comment by iconexperience** [comment]
Good :-)

**Comment by lehni** [comment]
Cool, that seems to have fixed the slow downs and errors! Will do some more testing but it looks very good.

**Comment by iconexperience** [comment]
Here it also fixed my newly found problem in https://github.com/paperjs/paper.js/issues/571

Can you confirm?

**Comment by lehni** [comment]
Yes that worked! I like it when that happens : )

**Comment by iconexperience** [comment]
:star: :star2: :sparkles: :+1: :fireworks: :clap: :dizzy: :laughing: 

I will stop for today, this was great!

**Comment by lehni** [comment]
Yeah great work! If you ever feel like a new challenge, this one's really bugging me as it appears to have gotten worse with all our improvements: #541

**Comment by iconexperience** [comment]
OK, I will give it a try.
