### ISSUE TITLE
Hit test on Path results in uncaught TypeError

### ISSUE THREAD

**Issue by dasboe** [paperjs/paper.js#617]
Setting a Paths horizontal and/or vertical scale factor to 0 and its applyMatrix property to false results in an uncaught TypeError in paper.js when performing a hit test on the Path:

see the console log in this sketch:
http://sketch.paperjs.org/#S/q1bKS8xNVbJSCs5OLUnOUNJRSs5PAfHLEosUkjOLknNSFWwV8lLLFQISSzL0nMEiGmB+fmZeiYahgYGOApDQhJAxeRA9eokFBTmVvoklRZkVQP1piTnFqXC54uREoBkgfSD1+XnF+UDBnPx0Dah8RmZJSGpxCTZbNDWBLkwqSk3MLgBJFCtZRcfWAgA=

**Comment by lehni** [comment]
This happens with non-revertible matrices, due to the call of ` matrix._inverseTransform(point);`:

https://github.com/paperjs/paper.js/blob/develop/src/item/Item.js#L1765
