### ISSUE TITLE
paper.project.clear() doesn't clear until paper detects mouse move

### ISSUE THREAD

**Issue by zdavis** [paperjs/paper.js#625]
It looks to me like calling paper.project.clear does not actually clear the project until a mouse move is detected. I've setup a sketch to illustrate this:

http://sketch.paperjs.org/#S/dVJLT8MwDP4rVi9LpVEeGhcmTsARCQETB7ZDlnltWWpXSboJTfvvON2rDFZVrePH5++zs05IV5jcJW8LDKZI+onhWTzzUlu4B8IV1LpGl70zW5WOaamdeEJxtLzkfU7GFEsypmduPD7yisQ9b8iEkknhEimksB4TyOODduGFSwqS04ayOp7GtBme4Didn8eJ3X+RfBFH9mRtWXtU0f2KJmjKLapjz363ZZoOj1iZD44X+MCW3Q63tdV1H67k/Sf3o5y1HAadkM/qxhcqmrHiVNOoPq9o+zVMni1mxqJ2KoVu7PISRmS4qqQM5sKzJJEmdptcUn5I246kdvwlQ9hjDU+w3rjCUFboIRQIM7T6G/Q8oAOjZY6Uw55E6UF7qBpTxP/g4hY8CtGZz3ZLxfAuQNwEdRB30NVVZTlXvSkKd9yCt616e2rbKZ6n/gdqR/cv0qYPN7dXadyAXOypQ71od+6Tu8/J5gc=

To reproduce, do the following:

1. Click + drag to draw some circles
2. Letup on the mouse button, without moving the mouse. You'll see that project.clear() was called in the console, yet the paths are still there.
3. Now move the mouse—as soon as you move it, the paths will actually be cleared.

**Comment by zdavis** [comment]
Perhaps this isn't a bug, and the expectation is that one just calls paper.view.update() after making any changes.. if so, don't hesitate to close. Thanks.

**Comment by lehni** [comment]
Yes that's the intended design. Non of the mutable functions update the view, as otherwise the view would constantly have to repaint itself. Instead, PaperScript handles these updates for you at the end of mouse and frame events, and you have to manually do so everywhere else (e.g. when using pure JavaScript, or native DOM / jQuery events, etc)

**Comment by zdavis** [comment]
Thanks, Lehni. I appreciate the feedback. Thanks, too, for your work on this terrific library.
