### ISSUE TITLE
Multiple Key.isDown issue

### ISSUE THREAD

**Issue by pric** [paperjs/paper.js#630]
When trying to make a multiple key command I get a weird error. The functionality works, but it seems that the sequence gets stuck to ctrl-z in my case. Here is my code:

    function onKeyDown(event) {
      if(paper.Key.isDown('command') || paper.Key.isDown('control')){
        if(paper.Key.isDown('z')){
          console.log("Undo");
        }
      }
    }

After executing the ctrl-z sequence, if I hit only the command key, the `console.log("Undo")` gets called.

**Comment by lehni** [comment]
What operating system and browser are you experiencing this on?

**Comment by pric** [comment]
The issue occurred on chrome v40.0.2214.94 and OS X v10.10.1

**Comment by lehni** [comment]
Could you create a test-case? I can't reproduce...

**Comment by lehni** [comment]
I can confirm this is happening at my end as well... Investigating.

**Comment by lehni** [comment]
It seems that because the browser is handling this short-cut, they up keyup event or the 'z' key is never received... That's pretty irritating.

**Comment by lehni** [comment]
So it seems this is a known issue on Mac:

http://stackoverflow.com/questions/16716523/command-v-not-working-with-keyup-event-in-jquery
http://stackoverflow.com/questions/4001565/missing-keyup-events-on-meaningful-key-combinations-e-g-select-till-beginning
