### ISSUE TITLE
feature request: integer bounds with floor, ceil

### ISSUE THREAD

**Issue by Skalkaz** [paperjs/paper.js#631]
Dealing with canvas.drawImage you need to use integers for pixels or your draw will be blurred. So it would be great a flag for (stroke)bounds which if it is on, then we get the bounds in rounded integers. Of course we round "outwards", the rounded bounds never can be smaller than the original.

**Comment by lehni** [comment]
I think this should be left to the code that is implemented on top of paper.js. This would not work correctly e.g. if the item that is to be rounded is contained in another item with a transformation matrix.
