### ISSUE TITLE
Multi-touch implementation is buggy.

### ISSUE THREAD

**Issue by alexpersian** [paperjs/paper.js#633]
We've been using paper.js pretty heavily for a couple projects, and have been trying to implement a multi-touch solution for drawings paths. 
So far we have been able to get multi-touch working for path creation, but it's been through some hacky solutions. PaperJS doesn't seem to like handling multiple paths at once by default, and paths will connect themselves at times when you release a finger, or even while drawing. 

Here's some code that allows for multiple paths being drawn at once, but there are some issues.
* Paths do not get created at the touch point. They seem to be created below.
* All paths have to be force stopped when a touch point leaves. Otherwise the paths will connect on touchend.
```
startup();

function startup() {
    document.body.addEventListener('touchstart', touchStart, false);
    document.body.addEventListener('touchmove', touchmove, false);
    document.body.addEventListener('touchend', touchEnd, false);
    //PaperJS Installation
    paper.install(window);
    paper.setup('myCanvas');
}

//Array to store new paths
var paths = [];

function touchStart(ev){
    var touches = ev.touches;

    //Create new path per touch
    var path = new Path();
    path.strokeColor = 'red';
    path.strokeWidth = 4;
    paths.push(path);
}

function touchmove(ev) {
    var touches = ev.touches;

    //Prevents touch bubbling
    if(touches.length == paths.length){
        for(var i = 0; i < touches.length; i++){
            var path = paths[i];
            var touch = touches[i];
            var x1, y1;
            x1 = touch.pageX;
            y1 = touch.pageY;
            path.add(new Point(x1, y1));
            paper.view.draw();
        }
    }
}

function touchEnd(ev){
    var touches = ev.touches

    //Empth paths array to start process over
    if(touches.length == 0){
        paths.splice(0, paths.length);
    }
}
```
Is there a way that we are failing to see for PaperJS to handle multiple touches and multiple paths out of the box? 
If not, would it be possible for the mouse tools to accept multiple touch events?

edit: There are also multi-touch libraries out there, (HammerJS, InteractJS, etc.), but they create the same issue with the paths connecting. This leads me to believe that it is an issue stemming from the way Paper handles paths or multiple paths. Here is a link utilizing HammerJS, but the path creation is off, and the paths sometimes connect themselves. http://www.nielsdavinci.fr/multi/

**Comment by lehni** [comment]
The offset simply happens because you do not transform into view coordinate space. There are internal helpers in Paper.js for that:
```js
var point = view.viewToProject(paper.DomEvent.getOffset(event, view.element));
```

I think it would make sense to expose this in a new method, e.g. `view.getEventPoint(event)`.

The other problem I can emulate in the iOS emulator! I will investigate... Is it possible that the indices changes when you have multiple touch points? That would be crazy, right?

**Comment by lehni** [comment]
Oh, I just realize that DomEvent is not exposed... I will create this method `getEventPoint()` method now.

**Comment by lehni** [comment]
This must be a bug in how Hammer.js is handling offsets. I don't get the same behavior with the native events above:

http://sketch.paperjs.org/#S/lVNNj4IwEP0rDRcgGvCwJ1kPG+NtDyYe9iAeCh2kUVvSFowx/vftFFjxI7trL0xn5s3H4/XsCXoAb+qtdmDy0ht7uWR4j+MPpeiJGEm0kQqIgCOpqCl1KhqqWpPMyHqTpCIVRS1yw6Ww+XVergxVJoAmJOdUEHsQ4SKAGGii7pK04TieK6Dm2oRU0AGueOefuZSlNYOwA6M/0kbJHczlXiqb4ytg/mP4izNX4m0Q0lFV6zJAEwteHpc5yAZe2mWpoAFhdJtFsjrL9lxs2zAvgi4/2oPY4jyzWTdJ6/hphKeQKsCG3LaaJPbzTm7h1jcahQPEHV2u8ppvkicZkgtjUxoOx2gLZoFTL9HZj2hx4R3Q0UkZCxz6PupKMUWPwTByac3LU3oXgiG7f5Dbc7s4VKgOJz56FaiVG6mUzEFrYn+X+o3ryZCtGxkPh2Qyrw+WjyiT7IQLO3Y+uTYgQAW+K+wa++OB6MekoHsNuP2/KqC4+gJov4oHwXq4JXKAti85s29q536T9qbrzeUb

Note that this example will only work once this new `view.getEventPoint(event)` method is available...

I have it running locally, and here is the result I am getting with the emulator.

![screen shot 2016-01-13 at 15 19 58](https://cloud.githubusercontent.com/assets/213275/12296742/d449d21e-ba09-11e5-9b4d-ad4121aa7802.png)

**Comment by lehni** [comment]
Please note that the above example only works on touch devices. But with these things in place, I can't see any bugs... Could you verify?

**Comment by alexpersian** [comment]
Awesome that this issue is getting some attention. I'm in class right now, but I will look over this later and see if there are any bugs.

**Comment by lehni** [comment]
Apologies for taking so long to look at this. 2015 has been a busy year...

**Comment by lehni** [comment]
Did you have a chance to test it? Would love to close this if possible!

**Comment by alexpersian** [comment]
Apologies, I haven't had much time to test this yet.
The sample you provided above doesn't seem to be working right now though.

**Comment by lehni** [comment]
Yes like I said, you need the latest code base for it to run. You can copy it to a local HTML file in the nightly release: http://paperjs.org/download/paperjs-nightly.zip

**Comment by alexpersian** [comment]
Alright, I'm testing the nightly build now.
To clarify: is this fix for the drawing offset, or for the multi-touch connecting the two paths?

**Comment by lehni** [comment]
The drawing offset. Like I said, I could not observe a problem with the lines connecting in multi-touch, when working with the native events directly (as in the example). I did see the problem with Hammer.js, which made me think it's a bug there, not here.

**Comment by alexpersian** [comment]
After switching to the nightly build I'm not able to reproduce the offset bug that was present before. I would have to say that this issue is fixed.

**Comment by lehni** [comment]
And the multiple lines work correctly too? No more of that line-switching that you observed before?

**Comment by alexpersian** [comment]
I only tested the drawing offset, since the project I am using Paper on isn't setup for multi-touch.
Let me create a test project for multi-touch and see. I'll get back to you.

**Comment by alexpersian** [comment]
This is probably because it's been awhile since I've worked with paper.js, but when I load up an example using that sample code and nightly source I get no drawing functionality on my iPhone.
Here is the test page I've built.
```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <script src="../scripts/min/paper-full.min.js"></script>

    <script type="application/javascript">
        window.onload = function() {
            //Array to store new paths
            var paths = [];

            function touchStart(ev) {
                console.log("boop");
                var touches = ev.touches;
                // Create new path per touch
                var path = new Path();
                path.strokeColor = 'red';
                path.strokeWidth = 4;
                paths.push(path);
            }

            function touchMove(ev) {
                console.log("beep");
                var touches = ev.touches;
                // Prevents touch bubbling
                if(touches.length === paths.length) {
                    for(var i = 0; i < touches.length; i++){
                        var path = paths[i];
                        var point = view.getEventPoint(touches[i]);
                        path.add(point);
                        view.draw();
                    }
                }
            }

            function touchEnd(ev){
                console.log("bopp");
                var touches = ev.touches;
                // Empty paths array to start process over
                if(touches.length === 0){
                    paths = [];
                }
            }

            document.body.addEventListener('touchstart', touchStart, false);
            document.body.addEventListener('touchmove', touchMove, false);
            document.body.addEventListener('touchend', touchEnd, false);
        }
    </script>
    <style>
        #myCanvas {
            width: 100%;
            height: 100%;
            background-color: grey;
        }
    </style>
</head>
<body>
    <canvas id="myCanvas" resize></canvas>
</body>
</html>
```
Let me know if I'm doing something silly and messing up the test.

**Comment by lehni** [comment]
You're using JavaScript, so you need to do the initializing yourself. The easiest is:

```js
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <script src="../dist/paper-full.js"></script>

    <script type="application/javascript">
        paper.install(window);
        window.onload = function() {
            // Get a reference to the canvas object
            var canvas = document.getElementById('myCanvas');
            // Create an empty project and a view for the canvas:
            paper.setup(canvas);
            var paths = [];

            function touchStart(ev) {
                console.log("boop");
                var touches = ev.touches;
                // Create new path per touch
                var path = new Path();
                path.strokeColor = 'red';
                path.strokeWidth = 4;
                paths.push(path);
            }

            function touchMove(ev) {
                console.log("beep");
                var touches = ev.touches;
                // Prevents touch bubbling
                if(touches.length === paths.length) {
                    for(var i = 0; i < touches.length; i++){
                        var path = paths[i];
                        var point = view.getEventPoint(touches[i]);
                        path.add(point);
                        view.draw();
                    }
                }
            }

            function touchEnd(ev){
                console.log("bopp");
                var touches = ev.touches;
                // Empty paths array to start process over
                if(touches.length === 0){
                    paths = [];
                }
            }

            document.body.addEventListener('touchstart', touchStart, false);
            document.body.addEventListener('touchmove', touchMove, false);
            document.body.addEventListener('touchend', touchEnd, false);
        }
    </script>
    <style>
        #myCanvas {
            width: 100%;
            height: 100%;
            background-color: white;
        }
    </style>
</head>
<body>
    <canvas id="myCanvas" resize></canvas>
</body>
</html>
```

**Comment by alexpersian** [comment]
Perfect. I had a feeling it was something simple I was missing.
With this the multi-touch multi-path drawing is working great. The only addition I needed to add was `event.preventDefault();` within `touchMove()` in order to prevent the default behavior of scrolling/dragging. Referenced in issue #575. I have a hard time calling that a "bug" in paper.js since it's the default interaction for iOS though.

**Comment by lehni** [comment]
Yes but some people actually want that behavior. I spent a lot of time recently handling `preventDefault()`properly on the internal handles, but since you use the touch handlers and we don't offer those yet, you're own your own there...

That's great then, sounds like I can close both issues : )

**Comment by ilteris** [comment]
Sorry to bug in the closed thread, I haven't been found the nightly build that's mentioned in the thread. Should I assume this is included in Release version now? 

I am having a hard time touch working on Android with paperj. 
However, when I do 
`console.log(paper)`  I get this back: `PaperScope {settings: Base, project: Project, projects: Array[1], tools: Array[0], _id: 0}`
