### ISSUE TITLE
Cannot load from external file because of CORS restriction

### ISSUE THREAD

**Issue by eljefedelrodeodeljefe** [paperjs/paper.js#636]
When I am trying to load an external script like in the examples, I am getting CORS related errors with 0.9.21 and 0.9.19.

```html
<!DOCTYPE html>
<html>
<head>
  <link rel="stylesheet" href="css/style.css">
  <script type="text/javascript" src="js/paper-full.js"></script>
  <!-- // <script type="text/javascript" src="js/paper-full-0.9.21.js"></script> -->
  <script type="text/paperscript" src="js/main.js" canvas="canvas"></script>
  </script>
</head>
<body>
  <canvas id="canvas" resize></canvas>

</body>
</html>
```

**Comment by iconexperience** [comment]
Are you sure this is a paper.js issue? Maybe you are trying to load a resource from the local file system, which Chrome does not permit.

Did you try the same with Firefox? It seems to be less restrictive.

**Comment by iconexperience** [comment]
Maybe you want to take a look at this:

https://www.npmjs.com/package/http-server

I use it when testing our software on my localhost to prevent cross origin errors.

**Comment by lehni** [comment]
Yeah there is no way we can circumvent CORBS when on the file system. You can serve the files from a local web server, or start the browser with a flag that allows it to load from the local file system:

http://stackoverflow.com/questions/4208530/xmlhttprequest-origin-null-is-not-allowed-access-control-allow-origin-for-file

**Comment by lehni** [comment]
On OSX you could also use http://anvilformac.com/ to serve a local folder through a local web-server very conveniently.

**Comment by wonkoRT** [comment]
You can still force a chrome instance to allow CORS by adding the cmd line argument --disable-web-security.
