### ISSUE TITLE
SVG export creates 'data-paper-data="null"' attribute if item._data is null

### ISSUE THREAD

**Issue by iconexperience** [paperjs/paper.js#638]
When exporting an item that has set its `_data`attribute to null, the SVG export creates a `data-paper-data="null"`attribute to the svg element.

This happens for two reasons:
1. When cloning an Item with `_data===undefined`, the clone will have `_data===null`. I do not think this is really a bug.
2. On SVG export, the data is passed to  `JSON.stringify()`, which returns `"null"` (as a String object) if the argument is null. A small check for `"null"`afterwards should fix this.

Here is a tiny testcase:

http://sketch.paperjs.org/#S/nZA9j8IwDIb/iuUpFW3VFp2EejoWBkaQKt1yuSGXGogoTpWGDwnx30muTEyIzX7t137sK7I6ENbY7MnrHaaobRtzySflQBunO4IvYDpDs1M95Yt/SURhbQ17MStS+CiSFKZF8il5NNKlt86XwTmOyEeh+V6Kqxoa7wxva/DuSLdo0pYHG7o6uxUSyxwWlr0yPECrvMr6sNhlMawlwgTEY3xuuKXLahM8T30SE5hDViYj0gMiVuIxx657Iq3eI61eJK1eIg3f/3Ok9n3864D1z+/tDg==

**Comment by iconexperience** [comment]
Created pull request #639 as a fix for this issue.

**Comment by lehni** [comment]
#639 was merged. Thanks!
