### ISSUE TITLE
Symbol's stroke clipped with exportSVG 

### ISSUE THREAD

**Issue by alexburner** [paperjs/paper.js#642]
I've noticed that a Path.Circle with a stroke exports to SVG fine, but when I place the Circle as a Symbol, the exported SVG clips the stroke to the shape's bounds:

![screen shot 2015-02-23 at 1 15 45 pm](https://cloud.githubusercontent.com/assets/409114/6337351/1fe340a8-bb5e-11e4-9f15-3e16aa16d5aa.png)

I made a JS Bin example illustrating the issue ~ http://jsbin.com/hasowu/5/edit?js,output

**Comment by alexburner** [comment]
(if you comment out the 2 symbol lines in the jsbin, you can see the exported SVG works fine)

**Comment by iconexperience** [comment]
Interesting. Here is the string representation of the svg (you can create it with `console.log(new XMLSerializer().serializeToString(svg));` ).

`<svg x="0" y="0" width="200" height="200" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"><defs><symbol viewBox="-50,-50,100,100" id="symbol-1"><circle cx="0" cy="0" r="50" fill="none" stroke="#000000" stroke-width="6" stroke-linecap="butt" stroke-linejoin="miter" stroke-miterlimit="10" stroke-dasharray="" stroke-dashoffset="0" font-family="sans-serif" font-weight="normal" font-size="12" text-anchor="start" mix-blend-mode="normal"/></symbol></defs><g fill="none" stroke="none" stroke-width="1" stroke-linecap="butt" stroke-linejoin="miter" stroke-miterlimit="10" stroke-dasharray="" stroke-dashoffset="0" font-family="sans-serif" font-weight="normal" font-size="12" text-anchor="start" mix-blend-mode="normal"><use x="50" y="50" xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#symbol-1" width="100" height="100"/></g></svg>`

I found a question on stackoverflow that addresses this issue:

http://stackoverflow.com/questions/19981499/avoiding-the-clipping-of-symbols-in-svg

I tried the suggested solution and it works for your case, too. Just adding  `overflow="visible"` to the `symbol`node makes the circle draw as desired.

The question now is, how to get that attribute to the `symbol` node. You can do this directly by manipulating your svg dome structure. Or you can use the onExport callback of paper.js to add this.

But in general maybe it would be a good idea to have this attribute added to any symbol when exporting symbols to svg.

**Comment by iconexperience** [comment]
Some more background on why the clipping occurs:
- The initial value for `overflow`of the svg element is `visible`
- However, for elements that establish new viewports (`use` for instancing a symbol is one of them), the value for `overflow` is overridden to `hidden`.

Here are the relevant parts of the SVG spec:
http://www.w3.org/TR/SVG/masking.html#OverflowProperty
http://www.w3.org/TR/SVG/coords.html#EstablishingANewViewport

**Comment by alexburner** [comment]
Interesting, thank you @iconexperience! I'm saving the SVGs for converting to PDF and printing, so I can do a simple find-and-replace to add the `overflow="visible"` attribute.

While your fix patches my use case, I'm going to leave this issue open, because (as you say) I think in general it would be a good idea to have this fix integrated with the exportSVG method.

**Comment by lehni** [comment]
Merged in, thanks!

**Comment by alexburner** [comment]
Great, thank you!
