### ISSUE TITLE
Add a way to display the version of paper.js used by Sketch

### ISSUE THREAD

**Issue by iconexperience** [paperjs/paper.js#647]
For testing it would be nice to have a way of knowing which version of paper.js is used by `sketch.paperjs.org`

Something like an 'About' button would be nice.

**Comment by lehni** [comment]
Is `console.log(paper.version);` not good enough? : )

**Comment by lehni** [comment]
Actually, I'd like to add a pulldown that lets you choose different versions eventually. But before that, many other things have to change first.

**Comment by iconexperience** [comment]
Sorry, did not think about the easiest way. Closing this issue as that is all I was looking for. Thanks.
