### ISSUE TITLE
Too many intersections found for identical and partially identical curves

### ISSUE THREAD

**Issue by iconexperience** [paperjs/paper.js#648]
If we try to find the intersections of identical or partially identical curves, too many intersections are found. In the following examplethe two curves are identical, therefore only the start and end point should be returned. But instead *764* intersections are found:

http://sketch.paperjs.org/#S/hZLNjtsgFIVf5ZZNHMVFgI0NmXYVddHdSLOq4iwyzo1jhYERJplFlHcvOBPFs6jqDb4/37kc4ELs9g3JkrwcMbQHkpPW7VJ83npo/ZnDT7D4AauTP2OW/p5db0PGa55DIfU8B3hkBZO00EwpraUsSlXl8J2XVOtSKs4ZK5iUWkbmgUhaV3VVloprxWUt6xyEoqVmutSSqUIKXX8BSsEoF4VUkmvBuEhALWns5DrmBa+qaj5/anxjPz2I6CFZoa1xFrNb7V5/D4e7x+dtOGSXAbs3tGFYwnqEPuNodxqKTQ5D8O6IK2ecX8Ks84h2dn1M/o+y+Kos/q38ak54F55uPZ7GcLfWYfhtA/oB29A7O2RJ8oa0MXQGqXFd1pA/v15y+EDYu5PdQUNgMepQg7YLhxjFVD9V+taQm87eecjGuXEoe4rLjykaE4vFHC6pFeKXOncuTE6ArnrfGswStO439D3dZ3xFN/nExH66740ZnUdy5nE3G6vX+DJfPW6PIzSQ5Xpz/Qs=

But we can get even more. Here we try to find intersections of a curve with a subcurve. A whopping 27004 intersections are found! (Please be patient, it may take a few seconds)

http://sketch.paperjs.org/#S/hZJBj5swEIX/ypRLQKGWbTDY2fYU9dDbSnuqQg5ZmBAUr70yTvYQ5b/XJhuFPVTlYt4w37Pf4Etidm+YrJKXI/r2kORJa7uozzsHrTsz+AkGP2B9cmdM49uzHYxPWc1yKITKcoBHlVNBCkWlVEqIopRVDt9ZSZQqhWSM0oIKoURgHoggdVVXZSmZkkzUos6BS1IqqkolqCwEV/UXoOSUMF4IKZjilPEI1IKETqZCnbOqqrLsqXGN+czAQ4YYhbTaGkwz0g3nocOUEpGDdye8dd+Jd3+4p37e+UN6GbF/Q+PHFWwmm08dBjCXfJvD6J094tpq61aw6B2iWVwfZ/mPM//qzP/t/KpPeDeeHz3MZ7yH7dH/Nh7diK0frBnTaHlD2iCtRqJtnzbJn18vOXwg7O3JdNAksJx8iEbT+0NQoTTMnb41yc1nbx2k075hU/oUlh9zNBSWywwusRXCEzs762cTIOvBtRrTCG2GLXmPfzjcq5t9ZEI/2Q9aT8kDuXDYLaav13BXXx3ujhM0JqvN9voX

Obviously we should check if curves are identical or if one curve is a subcurve of the other before finding intersections. I will try to investigate this further in the next few days.

**Comment by lehni** [comment]
Before you do: @hkrish was already talking about that and had some ideas, perhaps worth checking with him first.

**Comment by iconexperience** [comment]
OK, will do, thanks.

**Comment by lehni** [comment]
I think @hkrish said that after more than 9 intersections we can be sure that it's at least partially identical to the other curve.

**Comment by hkrish** [comment]
Thanks for the cases @iconexperience. You are right, we need to figure out a way to know if curves are overlapping --completely, partially etc.

Fortunately there is an efficient way to compute this, based on a geometrical insight of cubic bezier curves; it's explained here http://web.mit.edu/hyperbook/Patrikalakis-Maekawa-Cho/node111.html.

Also, there are only 9 intersections possible for a cubic bezier curve, so there is no reason for our intersection methods to continue if there are more than 9 --but this is just an optimisation issue.

The best approach would be to have a method --*that lets us check if two curves overlap, if yes how (completely or partially), if they partially overlap, where does the common part start and end.*

We can use this method to check if a curve is overlapping, if not, check for intersections. This is better in booleanops code because, we need to explicitly take care of cases where curves overlap. That is, returning two intersections is not enough, because there can also be cases where we only have two intersections on a curve that are not overlapping.

Perhaps, we may need something like, 

    static Curve.doesOverlap (c1::Curve, c2::Curve) => 

        | Undefined                       --- if curves doesn't overlap

        | { 
            t_start(c1),   // The starting and ending parameter of overlapping regions...
            t_end(c1),     //  ... on both curves
            t_start(c2),
            t_end(c2),
         }                               --- If the curves overlap

@lehni, @iconexperience Do you guys think this makes sense? Please feel free to modify this proposal.

@iconexperience, it would be a great if you can start the work on this. The paper I mentioned is quite clear. Please let me know if I can help in any way possible. Until this April, I am going to be a bit busy at work. So, sorry about my sporadic involvement.

/hari

**Comment by iconexperience** [comment]
@hkrish Having a function `Curve.doesOverlap(...)`makes a lot of sense to me. Although I can think of cases when this may not be sufficient, for example two curves that that are almost identical only near the intersection point, your proposed solution will cover the most common cases.

And besides, paper.js is not the only one finding too many intersections on almost identical curves. Here is what Corel Draw 6.0 produces when uniting two very similar curves (these are only 97 intersections):

![image](https://cloud.githubusercontent.com/assets/2122773/6479474/0d6bd81a-c246-11e4-8216-564cfea917cf.png)

Having all these intersections does not really break anything, it can just make working with the objects very slow.

Alright, I will get to work.

**Comment by iconexperience** [comment]
Here is my version of the `getOverlap()`function with a little testing playground:

http://sketch.paperjs.org/#S/pVhtb9s2EP4rrIG18qqoEpM0WNy0GJIOKNA2RVusH1wXYGU64iKLBkXJ9lL/991RpCLJshNjRmJT5L3x7rnjUXeDjM354Hzw5ZbrOBn4g1hO8fnFC3KZiviWyIzohJOYZSXLiZYkT+SSMJLxJYkLVXKyYEJ9V98z/J8VWawF8MjsgyxyfiWXmcdLnukhuTNEWvNcXyLjJ+DzhiOc3Tj+kilyw/V1yVXKFuSC1AK9WJWRT+CbWlEEPmDmV3klz8kVj8WUo7ULpmBLmiui1wueB+RrInISyyKdkp+c6KWs7M6JVGZrJUsLTnKuiZw1lp0KNIn9zMGWD0wnAQx9cEPKFctiDrMfizlXImZp8PX6/dvPf368fDtyvGJGvCdoOPn1izypbFdcFyojWZGmo6YOILrA7UUBOOBvtCm33qkpaEVBd1KI/L3IOAwuiHFx4Ca8MhqiDd1ZOmzZ6hYaHrZefjcD33IbcfBnauh840AJX8ouzYtco5vrdSkDco0ES5FzJF8jljIJ3q6CHHQ02R3YGAEtKE7XjhrNNEKYAmtk6vQsExEnZM5ZllfrzhCkQ0ikKU8Jy6YdbSxbk4UUmQl+tYWo5gU0VVO0yWWC2u/erWmK001m9wEYecA1DifkCEI/fjkZkt8JMIwjM0PHZzBzRJAmsjRnNU1oaYBrSF434LhbGVqEuPkibjI+vRK5RoZKmE+MXr8S6VfafWLMMz+4NmNpztvqOjDBTx+68bNxD5sWogGoY0zrkk78JvmcQTXimHTjyaiR7O8gr5lGHClZ3CQEwkp4Nq1CCLn+l1AQukWEkSYL2giqgWrWt1QHdwYFwTNmvZuuQHUIPJiU4aiaeUUoefrU2RakPLvRCc7a9ecXhv4COMgb+D83WlECfP0gUcddqEnTOlUhNp9c6bqeeeUYZf4wUTHDybgj/GX/UgRLgJRRF7Kg6smFCQzYYZwJsxX0IZ8d1LvxRCPNhsHOyi1WDaiEzdEJaBtrivucjLrMqLbjLWSPai8ikF85h8ID/PVgqgGIoMjyRMx0JXa4pXFDOKB0l+IQc7RWDN5oab5fjLqL0UNmLYo82WlTbx44/9ROjXqwhTY/kGQ2kEuohgmPb/kUc4NzmxHkZ6EB1wVAPpM2kCYP7stroxTvT9haUSUPT0prbnUM3Och5lZZJRqcWdAwuLMXqHJAeEC+8aqqJwwSEJoKY7ut7Q19CYhIwUws4o65OlOap9a20+j2ARYrjoXDHPa5SXW76YXIbvCEMCcAZ+CgrUQoER3tPNVeaYpjC0H3j5GB8qgtJOoTggluGou5yLwW5FrSAIGOjq3207XVwtYVNGAqr/cO28x5LCE49jSfQTMX8zxnat1FJ54cpU2PI7MFc1K9ahw5gNqaKqqpztpUPSC2/hhbob7js4MTNzh1A+oGx24QukE0mfSfNi74Dl4OUOCDdvh1UqEsF3ORQs3jGZ4vBqhV6ziVgGfb6RhpCCHrwCn0t0KvO0qBlLuMEeBtBimgsS+NlYAfwbrOrru33ae48TKtvUz3xOK4pjreotor/qRmPNkj/rSmOn0w1OCMbrJV3q48B71zD0e3r7dFD5v6bk/PqkD4MKiaeaYUW/umwYcqZVLuvYwZXiTyHcW0dv4bc7UxPA76Pildqu2YeekGZz0zQ3Le53D8PKiKusGxG5y4wWmfqgearm57thm5m5e7fVV18jPkiZwbyxqXMC8X/4KX0+4dAflWkbshKcPrYa+K9OS5+WndU9aHEK/oIZIPIY6N0V6b/IgEp8hELWObY30whzH/MB2HcGDh2ApIM9Q1wnD0Cc9nbwWt2zqCA+V+CnrdcP/ECpq8NW2cLrbX+h9KY5yLtyYpTtIHlPejt/VyoYnchnMWSv7DYx3EKV7R2hdoBXXa4meWSqm8LpSiMGxzmNv9xXbaeMdhCPQtft/If01Ot2VQd/mPU7hnd6zSdbrg4R8GYRhGflt0+x6Pan4DrPT0j+b9wVSUUFU908Krgu+PqTFrN0fL0Dr7sJsJgz/g8whDj3cZ6t53OO30sfY6b+5mbHSZlWnQjc7FyjStrmHafhEE9tIDAGK3SPcEIwqsNq/HuAb/Th89kv+0j9/EbL6w3hr1e5F259EDwNVW1/SSrF/f3b/La76/qzlNgoMDvbuc38yhF8jhNmk2ZZ8th3vE0zDXSt7yb2Kqk/MT93gpU6nOTdnBkalePl6/AzrcPKwvauuLtvVVCsizG7hbZc827RDb/Xac65QFl0JBrfHuYpDIQcjYvfkyt6UoWPmkM7MGvYpNRQH2HfvQPqZpZcAzxadN7QfooVt66OP13Ge54MugWEyh2Ll3t3UR7r7ZHfiDn1AWb6tL4eB8PNn8Bw==

The function checks for all end points of the two curves if the lie on the other curve. If two matches are found, the potentially overlapping part is created. If the handles of the potentially overlapping parts match, we have found the overlap.

**Comment by lehni** [comment]
@iconexperience the code looks great! But I am curious, would it help to handle the case outlined by @hkrish here, where a curve or multiple curves are only partly overlapping?

https://github.com/paperjs/paper.js/issues/450#issuecomment-40109984

**Comment by iconexperience** [comment]
@lehni 
Hm, I don't know. This is actually something that I could test today or tomorrow.

**Comment by lehni** [comment]
@iconexperience that'd be great! And don't worry with taking time to respond, great to hear you'll have more time again soon! :)

**Comment by lehni** [comment]
@hkrish, @iconexperience: Thanks to @iconexperience's code here, I'm finally on to a solution for all the boolean operation issues in commit 85d21c84b89b519be6cfd1a1c5b7fe616c24c0f3. It shouldn't be too far away! And it's surprisingly easy.

**Comment by lehni** [comment]
Note that the code isn't cleaned up at all and contains tons of debug logging and drawing. But it works with all known edge cases at my end and hasn't broken anything else that I've tested yet.

**Comment by iconexperience** [comment]
It's great to hear that the code was acutally useful (I was not so sure when I finished it).
I have not tested any of your changes yet, but please note that the for use of <code>tolerance</code> in my function I basically followed a "guts feeling", therefore with edge cases there will probably be many remaining issues.
Nevertheless, if using this function already solves the vast majority of boolean issues, this is a fantastic start (and I am sure it will become better).
Sorry that I cannot be of much help at the moment.

**Comment by iconexperience** [comment]
@lehni 
I found a little time to test the new code with my "Cubic Bezier Playground" and tried to combine the segment offsets simply with the <code>path.unite()</code> function. I can see huge progress and in many (most) cases the result is correct, but there are still a lot of cases where  <code>unite()</code> still does not work properly.

But as with curve intersections, there should be a lot of potential for improvement. I am confident that we will resolve most of the remaining boolean issues. This should be fun, but as I said I need a few days before I can start.

**Comment by lehni** [comment]
@iconexperience yeah I wasn't expecting it all to go smooth that easily :) Would be good to see a examples of failures, if it isn't too much hassle.

**Comment by lehni** [comment]
@iconexperience also, you tested against all the commits on the `boolean-fix` branch, right?

**Comment by iconexperience** [comment]
@lehni Yes, I did. In all cases where the the new algorithm failed I also recieved a "Boolean operation results in open path!" message. Maybe I can find a simple example and post it here.

**Comment by lehni** [comment]
Oh that's good news then : ) I am still working on those, a simple example would be great!

**Comment by iconexperience** [comment]
Here is an example, I hope it is typical :-)

<pre>
var path1 = new Path("M597.08402,324.32719c5.57767,15.61199 4.14763,31.49945 -0.45248,45.60147l-57.04185,-18.60719c1.70338,-5.22185 0.93059,-6.97988 0.99206,-6.80781z");
var path2 = new Path("M562.21669,286.78261c15.60305,7.98946 28.68136,20.22995 34.86733,37.54458l-56.50227,20.18647c0.18704,0.52352 -0.03483,-1.41861 -5.71125,-4.32519z")
path1.unite(path2);
</pre>

In my test case there are always collinear handles at the touching corners, which might be the reason for the problem here.

**Comment by lehni** [comment]
Will investigate, thanks!

**Comment by lehni** [comment]
It's happening because there are tiny self-intersections in one of the corners, and the code is not handling that yet...

<img width="382" alt="screen shot 2015-08-24 at 22 41 01" src="https://cloud.githubusercontent.com/assets/213275/9451828/3d33404e-4ab1-11e5-92e1-81989e2bcabd.png">

**Comment by iconexperience** [comment]
Thanks, I did not know this. Looks more like a bug in my code that causes these little hooks.

**Comment by lehni** [comment]
Yes but the boolean operations code should of course handle that...

I did some more tests, first with a suggestion that @hkrish made in another issue, to first resolve self-intersections on all paths (`path.unite()` without passing another path to it). This sort of worked, but only when the shape was scaled to a certain size. When I kept it small, the tiny little left-overs that result from the self-intersection caused issues... I imagine it's a question of tolerances in the winding contributions code at this scale. But it's really hard to debug.

Here is one thing I'd like you to try, to see wether without these little buggers, the code runs more reliably. The code resolves the self intersection on the paths and if it results in a CompoundPath, it removes all children except the biggest, which should be the shape you'd like to process. After that, it's a simple union between two normal paths, resulting in hopefully another normal path.

```js
function cleanUp(path) {
    var newPath = path.unite();
    path.remove();
    if (newPath instanceof CompoundPath) {
        var children = newPath.removeChildren();
        children.sort(function(a, b) {
            return b.area - a.area;
        });
        var child = children[0];
        child.insertAbove(newPath);
        newPath.remove();
        newPath = child;
    }
    return newPath;
}

path1 = cleanUp(path1);
path2 = cleanUp(path2);
```

**Comment by lehni** [comment]
@iconexperience: so I've been looking more into why the different behavior is occurring at different scale factors, and it turns out it is because of the overlap checking code. If we manage to get that to behave more reliably, we might still be able to get the current approach to perform well enough!

Did you take @hkrish's link [here](https://github.com/paperjs/paper.js/issues/648#issuecomment-134377509) into account when you developed your code?

http://web.mit.edu/hyperbook/Patrikalakis-Maekawa-Cho/node111.html

**Comment by lehni** [comment]
@iconexperience after some more tests I think your code is solid, and I fully understand what it's doing now. I've done some adjustments and experimentations with tolerances, and I don't think it's the culprit anymore. But I get different amounts of intersections back from the fat-line clipping code with the same geometries at different levels of scale, so this is now the next area of fine-tuning.

**Comment by lehni** [comment]
I finally found the issue here, in the code that sorted the CurveLocations to remove duplicates: d85b4f0c80a91b04200c2242cb3b0615c41764ac
Tiny variations at different scale levels caused different sorting and unexpected behavior. Now the code behaves the same way at all tested scales. We're approaching a solution : )

**Comment by iconexperience** [comment]
@lehni
Sorry for the silence from my side, but everything is a bit too much for me now. I am reading your comments but cannot find the time to answer. This is just the busiest time ever.

Regarding the paper mentioned by hari, I took a look at it but did not really understand how to transform this into a code, so I searched for my own solution. I would be surprised if it was flawless.

**Comment by lehni** [comment]
@iconexperience I have committed many more boolean improvements to https://github.com/paperjs/paper.js/tree/boolean-fix

Please try again with your code, and make sure you use this before (the above hack should not be necessary anymore):

    function cleanUp(path) {
        var newPath = path.unite();
        path.remove();
        return newPath;
    }

    path1 = cleanUp(path1);
    path2 = cleanUp(path2);

**Comment by lehni** [comment]
I've merged all the work back into `develop` and remove the debug logging and drawing code. It works really well in my tests here... Curious to hear what you find! All that's left is supporting self-intersecting source paths... I roughly know how, but performance has been suffering quite a bit as a result... Not sure how to handle it all yet.

**Comment by lehni** [comment]
@iconexperience no worries, take your time! if you find a moment in the next days to re-run the previous tests with the new code base that'd be great, as I'm just really curious how it's working now.

**Comment by iconexperience** [comment]
@lehni I finally found a moment to test the new code. When I ignore all cases with self-intersections things work pretty well (but my code creates many self intersections, far more than necessary). There seem to be two remaining issue:
- a glitch that seem to unnecessarily split a cuve, which results in a small, but well visible deformation of the path. I should be able to send an example soon.
- a failure of the boolean operation. This does not happen too often, but it happens. Hopefully I will be able to catch a path where this happens.

But in general: impressive work!

**Comment by iconexperience** [comment]
Alright, here is my first simple test case. In this case the boolean operation works, but the result is different from the expected result. This is not a major issue, but I suspec the fix should be easy.

<pre>
var p1 = new Path({segments:[[463.9780047854934, 242.45788478669098, 0, 0, 18.39490991498633, 18.763283770414063], [503.97992517441867, 317.201107498782, -7.581784931122968, -30.770871629359817, 0, 0], [445.72229285125354, 331.5554892722653, 0, 0, -5.274450958793182, -21.406496602422067], [421.13310212488653, 284.46162647720143, 10.14208864284501, 10.345192670683218, 0, 0]]});
var p2 =  new Path({segments:[[503.9799251744186, 317.2011074987819, 0, 0, 10.51261931443213, 42.66573931487159], [493.7273421855935, 475.64521896494347, 18.87625636417505, -62.72422687679028, 0, 0], [436.2726578144065, 458.35478103505653, 0, 0, 16.587797481872997, -55.11986871580717], [445.7222928512536, 331.5554892722654, 7.346578331020112, 29.81627951630253, 0, 0]]});
p1.closePath();
p2.closePath();
p1 = cleanUp(p1);
p2 = cleanUp(p2);
p = p1.unite(p2);
p.strokeColor = "red";
p1.strokeColor = "green";
p2.strokeColor = "green";
</pre>

As you can see in this image, there is a clear difference between the united path and the two single paths.
![image](https://cloud.githubusercontent.com/assets/2122773/9530507/8f653ba0-4d00-11e5-9d21-2ec926200ae2.png)

BTW, is there a shorter way to create a new Path? something like using <code>pathData</code>, but without the loss of precision?

**Comment by iconexperience** [comment]
@lehni I have good news: When I tested before I checked for self-intersections after calling <code>cleanUp()</code>, but the error already occured inside the <code>cleanUp()</code> function. This means that in my tests of the boolean code there are no problems anymore (beside the glitch described above) provided that the source paths have no self intersections :fireworks:

The problem in <code>cleanUp()</code> occured in a rather bizarre path (of course one with a tiny loop). If you are interested I can post the code to reproduce the problem.

**Comment by lehni** [comment]
@iconexperience thanks for testing! Sounds pretty good already. And yes please post the code for the tiny loop problem. you can use this code to export higher precision path data:

    var precision = 10; // amount of fractional digits
    path.getPathData(null, precision);

**Comment by iconexperience** [comment]
Here is a not too complex <code>CompoundPath</code> where <code>unite()</code> fails.

<pre>
var p =new CompoundPath("M286.7698144035,419.5897402912c96.593571447,-52.045851282 124.5003076508,-85.3858134517 128.6455046309,-98.541740989l57.2265725798,18.0310673775c-12.4274438193,39.4419254732 -63.5081928346,82.7347795334 -157.4117060176,133.3311930292z M415.7406918171,319.7533573727c-0.0108320278,0.0645152456 -0.0620202783,0.4588200175 -0.3253727827,1.2946419295c-0.0012475831,-0.0529641787 0.3291498636,-1.3171381145 0.3253727827,-1.2946419295z");<p>
p.unite();
</pre>

I am aware that this is an edge case and I will try to get rid of these, but maybe there is an easy way to handle these cases.

**Comment by lehni** [comment]
The edge case should be handled properly now on the `boolean-fix` branch. Thanks for spotting!

**Comment by lehni** [comment]
I am going to close this issue now, as the topic is actually solved. Please feel free to open new issues for new edge cases when they arise. Thanks for all the testing!
