### ISSUE TITLE
importSVG doesn't fill correctly using linearGradient

### ISSUE THREAD

**Issue by lehni** [paperjs/paper.js#650]
From the mailing list:

> I'm trying to load the following SVG image using the importSVG:

    <svg version="1.1" xmlns="http://www.w3.org/2000/svg"> <defs> <linearGradient id="gra-1" x1="0" y1="0" x2="0" y2="100%"> <stop offset="0%" stop-color="lightblue" /> <stop offset="50%" stop-color="lightblue" /> <stop offset="50%" stop-color="blue" /> <stop offset="100%" stop-color="blue" /> </linearGradient> </defs> <rect x="45" y="20" width="200" height="100" fill="url(#gra-1)" stroke="black" stoke-width="4px" /> </svg>

> If you will save the above line as a file image.svg, and open it in a brower you will see the correct svg image.
> When I'm loading the image using importSVG, the image doesn't painted correctly using the linearGradient.

> You can see the issue on sketch, using the following link: http://sketch.paperjs.org/#S/vVTLbsIwEPyVlauKhyBOKFzSwJVLb0i91D2YZCFugh05hgQh/r2OaahQpbaoqLedtWey3hnlQCTfIAnJIkMTp2RAYpU0eMc1bHgAUyi0esPYeDw2YodPfI/aE5tCabN4nnc7jDEZlbs17FCXQskpI4EXMAL1JpelRakxRUhpVVVe9eApvaYj3/eppTAya9gAECW4KmfwgSDKhUSu55onAqUBkVidteZDpxtY4Nti3xb1qO00ReD791b5LOYES6MKUKtViaa5ay9A0xrGKlfadnKxTs0y36I9oN9yJzcm/4p3etNPxIhe7u18EtGL/Uba+gm11Ri5rbVFJRKTOtCgFJtnnT5u4UrkuQVbnXfvnBU9N5BWGbpheJydJsxw2AqNi9pN6DLSOD7rDA6AdcFlskh5gWUIRm8Rjr1HJpmk/b9kqU3RTdJzbWKuTsk1ybgqDV9T0Nr/6ft48i++w8l0JvvU/lmWGnlWKCFNScKX1+M7

**Comment by iconexperience** [comment]
It looks like the import does not take the rectangle's y-offset into account. The change from light blue to blue should occur at 50%, which is 50px from the top of the rectangle. Instead the change occurs at 50px from the top of the page.

![image](https://cloud.githubusercontent.com/assets/2122773/6491335/d4f80320-c2ac-11e4-843e-8a6c69954476.png)

**Comment by iconexperience** [comment]
This example shows better that the y-offset of the rectangle is being ignored for the gradient:

http://sketch.paperjs.org/#S/7ZXfT8IwEMf/lUuNAQmsGz9ecPDKi28kvjgf6nawutEuXWEjxP/dtnMYY6ISiTHG7OW+1953194n24EItkEyJcsMdZySPollYvWOKdiwAGZQKPmIsfZYrPkOb9gelcc3hVR6ebvodqIoEmG5W8MOVcmlmEUk8IKIQL3JRWlUqnUxpbSqKq8aeVKt6dD3fWpKIjK31QAQJrgq5/CiIMy5QKYWiiUchQaeGJ+1YgPnGxjhm2DfBvWwzdgg8P1L43w0c4allgXI1apEbfeaDWBTg1jmUplMztepfsi3aBboh7WTMxd/qa4502eFIX17b8eVkL6531CZeUJtPIbu1tqg4olOnbAqRXus5uVGrnieG7FVeffCjeLKNaRkhq4ZFmdNhxkOWqNxUbsOHSN24vNO/wBYF0wky5QVWE5Bqy3C09V1JOzTYDf8x+5PYzfyW+7Gv4I72vsOTC1GZ8HnVGROxuQUNE7C4T0G7fxfBz+e/Mj3BpqhR6JHzR/tQSHLCsmFLsn07v7pGQ==

**Comment by iconexperience** [comment]
After the import the fill color's origin is [0, 0]:

http://sketch.paperjs.org/#S/rVJNTwIxEP0rkxoDRtgP1Mu6cPHAxRuJF+uh7A67dUu7aQu7hPDfbYsQSYx68DZvpu/1zceeSLZGkpFFg7aoyYgUqvR4yzSsWQpTaLV6x8JGrLB8i89shzri61Zpu3iZDweUUpmbbQVb1IYrOaUkjVJKoF8LaRyqrW2zOO66LuruIqWreJIkSewolMw8GwDyEldmBp8IcsElMj3XrOQoLfDS6VSajYNu6kDigt0p6CenjA/SJLl2ymexIGisakGtVgatf+segE+NCyWUdhnBq9ouxQZdIf6R+/DP5D/xjj39Rszjy7mdK3l8Md9cu31C7zQmYWqnoOOlrQPwqEbf1vFzB1dcCAc2WgyvwipugiGtGgxmWNEcHTY4Pgndt31wGG7Eb3w2GO0B+5bJclGzFk0GVm8QDjePVFJZKGmUwEioakiJ0rziMgMncetvMfIWnnz30bHkSZeUEo3lkll3h9/yvtQ92Z37UiNrWsWlNSR7fTt8AA==

**Comment by iconexperience** [comment]
I suspect that the problem is caused in <a href="https://github.com/paperjs/paper.js/blob/master/src/svg/SVGImport.js#L378">`SVGImport` line 358f</a>, where the item's position is used for the offset of the color. 

When changing y offset and height of the rectangle, the offset always has to be -50 to produce the correct result. This is half of the color's destination value. In the given example replacing the line with this helps:
<pre>
if (color && color.origin && color.destination)
    color.transform(new Matrix().translate(
    color.destination.subtract(color.origin).divide(2).negate()));
</pre>

But this is the only example that I have tested so far.

**Comment by lehni** [comment]
The problem is that paper.js always assumes the setting of `gradientUnits="userSpaceOnUse"`, which is also what is used when exporting.

**Comment by lehni** [comment]
So i've managed to fix this one in fce126959d0f86509b4ad7acd457cded0a4ed76f. But there are a few other issues with gradients and SVG, one is that canvas doesn't support applying a matrix to the gradient separate from the drawing matrix when filling a shape, so paper.js gradient colors don't hold matrices and hence radial gradients are always circles. We could work around this but it would involve inverse transforming the shape with the gradient matrix, not sure it's worth the pain.

**Comment by lehni** [comment]
Closing this as I have since implemented unit tests for it.
