### ISSUE TITLE
Maybe I did something wrong, but examples on this tutorial page not working

### ISSUE THREAD

**Issue by waveiron** [paperjs/paper.js#651]
http://paperjs.org/tutorials/paths/working-with-path-items/

**Comment by iconexperience** [comment]
I can confirm that the examples do not work, independent of the browser.

**Comment by lehni** [comment]
Indeed, I recently broke something there. Thanks for spotting it!

**Comment by lehni** [comment]
Fixed in https://github.com/paperjs/paperjs.org/commit/020458ceae668ba77a4111dfb3b073a3b3e98d7a
