### ISSUE TITLE
Path.unite(otherPath) will produce a CompoundPath with both pathes if they're just touching and not overlapping

### ISSUE THREAD

**Issue by aureole82** [paperjs/paper.js#653]
In most cases my pathes are just touching. If I unite 2 pathes I got a CompoundPath including both original paths.
See: http://jsfiddle.net/bdtb24zm/4/

I need one straight path as result like a boolean OR operation would provide. Did I get something wrong on `Path.unite(otherPath)`? If yes, could you provide a workaround. E.g. `CompoundPath.simplify()`?

**Comment by iconexperience** [comment]
This is a known issue, which has been described in #450 . There have been quite a few improvements on the boolean code recently, but still things are not perfect.

**Comment by lehni** [comment]
It's actually a duplicate of #449. Closing this one here.
