### ISSUE TITLE
CompoundPath.unite(otherPath) produces paths with holes

### ISSUE THREAD

**Issue by aureole82** [paperjs/paper.js#654]
I know it's a complex algorithm. Sorry to bring up a this painful subject: Uniting complex paths leads sometime to holes:
![654](https://cloud.githubusercontent.com/assets/4819891/6580945/1718ca54-c754-11e4-8d2b-5a4f2f04c551.png)

All recent bug reports lacks in reproducible scripts. Here is mine: http://jsfiddle.net/02f0o3kb/

**Comment by hkrish** [comment]
Thanks for reporting this @aureole82. The existing algorithm is too complex to fix I am afraid. I am working on (I would estimate about 30% of it is done) a better algorithm.

I will post about the progress in the mailing list.

/hari

**Comment by lehni** [comment]
Here the same in sketch:

http://sketch.paperjs.org/#S/nVXBbqMwEP2VEXsoKCgFQy5EPUV72dNqu7eSA3HcBoXakbHblar8+47BEHChyS6HSMyM38yb92I+PF68Mi/zHo9M0YMXelTszfv9PfzQtQIlND2U/AVOhTrUy5zn/K2QILQ6aQUPwNk7/BQlV7/ZH+U/pVEUAllF22Ddlcq4K0OE5S9GVcFfKub3J/0VnllFQXgB82MTI1EUGBwZL5/LqtqISkjEyr1v35sn99pkzdQjqxCY7X0lNTNnms7kWud4ojUZtSZftSaTrdvdLKnginEFiwfAc3kzKeIzWWN57UsSZBiHBXyKr6GdX5vNYVbzUrEmkXM9TRerJHsVb8y3Uw/ePs/TjdMD20l03KtWK3bC7nGYc8BHJiFoEso01Ind7k4rJfhww5tSUlzvR3uEMkMqA+uJKNp2WMW+1HWGNrGBfsMZ3O0qze5sXPBNVdJjBs+aU1UK7gdgwc1Tv5doWfDNqKMELWoGcXYJtAyumsHMiT9jN1hDN24Y433hDKdwSrFhyYxCemyM5CKTE3fgdpIVx7WzD+LsQ5s/h+49kARu+urUeuQ5h/JMZp5pP0dHktzCKnFVTm9SeULjeErj9FaN0//WmIy0TC/0nfgt20hdjY3nEcnuNnU1vu5MTWY1Tv9V48EcHcnEZdXcKXPALufz4C7AO2CxsDmMn5EqfsyaEycjcu1lT9vzXw==

**Comment by lehni** [comment]
Who would have thought! I managed to address these issues in the current code base, and the work in the `boolean-fix` branch has landed on `develop`! Time to test thoroughly, but I'm closing these bugs. Feel free to reopen if similar problems arise.
