### ISSUE TITLE
paperjs failed if applyMatrix = false

### ISSUE THREAD

**Issue by Skalkaz** [paperjs/paper.js#657]
Code:
project.activeLayer.applyMatrix = false

Sketch:
http://sketch.paperjs.org/#S/q1bKS8xNVbJSCs5OLUnOUNJRSs5PAfELivKzUpNL9BKTSzLLUn0SK1OL9BILCnIqfRNLijIrFGwV0hJzilNj8oBakopSE7ML8jPzSoqVrKJjawE=

Error:
TypeError: setting a property that has only a getter...................line 267 paper-full.js

Device:
win7 + safari 5.1.7

I am sure that it worked with earlier version of paperjs, but I am not sure which one. I guess version 20 was ok, but 21 is not. Safari on windows is a rare bird, tell me if I need to test something.

**Comment by lehni** [comment]
Safari 5.1.7 on Windows? That's ancient?

**Comment by Skalkaz** [comment]
Surprisingly, this is the latest version on win. I won't test on safari any more. Thank you.

**Comment by lehni** [comment]
Yeah Apple abandoned it there quite a while ago. I think it has to do with me recently dropping some legacy code: #592. There haven't been any complaints so far...
