### ISSUE TITLE
strokeScaling behaviour inconsistent on layers?

### ISSUE THREAD

**Issue by voneiden** [paperjs/paper.js#658]
Hi,

Paper.js v0.9.22 

experienced a brief moment of confusion when I encountered a case where setting strokeScaling to false on a layer causes different behaviour on the main layer and a new layer. 

A quick sketch to demonstrate the issue

http://sketch.paperjs.org/#S/1VRNb9swDP0rhC9xAcOxk60DOuywrb3lECQodmhzUGwm0uJIhqwkaIf991Ef/mjSADtuBwMmH/lE8on6FUm2x+guWu7QFDxKokKV1q7YC+ocvkCt1U8sTMoKI444s+5n/SwdPiFc4gmcN77p/NMr/tyzMIPe2X5Hgaf0Vak95WXpbecqUBrUgWyuhDTxpyyBrEuucGMIzjNrGKNqMqbOOInScGc5k6PYch+atcnjMXybPT6ApvaY3FYIQoKrE/KAN0arHS4LZsEGjD6gK45poMNm/vS+OFtOAraOm89tnGVfilcMgfY3dsUl4It6G9ryMcPTRVtYHA5LOjafZK3U1/hdVcpOarSuDjg6R3+EaXwcSNH3JuSWsA2rGhyqQv3fs4ZjCYuH+/emNIGTIFpP1ASijuZyfA4CJWGtKM1zMFkOqGNWGa4OW94SoDGWVBib5jMaxD1JoYCzI4JUgJsNEfS3bHJ2y8bj4L7a8b+sp8Zy1GEl6fFVa/ZCyFNOq5BPVr7FQeo7DV67CpdSzx8X85nfiV7o6YWeTpSBoi4ucQtizU7RkNi/DGfaBOd/qUx90HU13LU36nwgcW5XfzN8+9HDu9bIdrXtronunla//wA=

Briefly in words how to reproduce

1. Draw a rectangle in default layer. Set layer strokeScaling to false.
2. Change view zoom and/or center, rectangle changes position accordingly. strokeWidth remains fixed regardless of zoom (which is what I wanted to achieve).
3. Create a new layer and add a rectangle in the same position. Set new layer strokeScaling to false
4. New rectangle becomes absolutely positioned and is not affected by view zoom or center values.

Now I realize this might actually be correct behaviour but my understanding of paper.js internals is not good enough to determine that, so I'm posting this just in case.

**Comment by lehni** [comment]
This is not a bug. It happens due to the way that styles in groups and layers are passed down to their children currently, so the opposite of how CSS handles it. There is a plan to change this behavior, see:

https://groups.google.com/forum/#!topic/paperjs/pJzsEYv2W7M
