### ISSUE TITLE
calls to smooth() on Paths with many points causes major lagging In Firefox.

### ISSUE THREAD

**Issue by limabeans** [paperjs/paper.js#659]
This isn't so much a problem in Google Chrome, however.

I'm using this library for phasor animations, and the call to smooth() at line 234 causes lagging in Firefox.

https://github.com/limabeans/phasor/blob/gh-pages/code.js#L234

My path contains 100 points.

**Comment by lehni** [comment]
I guess that makes Firefox the slower browser between the two. We can't expect all JS engines to run as well as V8?

**Comment by limabeans** [comment]
Yeah, that's what I was thinking as well, V8 beasting it up..

smooth is being called here, right? 

https://github.com/paperjs/paper.js/blob/master/src/path/Path.js#L2204

**Comment by lehni** [comment]
Yes that's the one... I have no experience with profiling on Firefox, but surely there is something similar to the V8 profiler. Perhaps worth trying to see where most time is spent?

**Comment by lehni** [comment]
Since this is not really a bug, I am going to close the issue. Should something arise from profiling, please reopen again.
