### ISSUE TITLE
SVG import does not handle gradients in firefox

### ISSUE THREAD

**Issue by jardakotesovec** [paperjs/paper.js#666]
Hi,

example svg created in illustrator:
```
<?xml version="1.0" encoding="utf-8"?>
<!-- Generator: Adobe Illustrator 18.1.1, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->
<svg version="1.1" id="Vrstva_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 viewBox="65 0 350 360" style="enable-background:new 65 0 350 360;" xml:space="preserve">
<linearGradient id="SVGID_1_" gradientUnits="userSpaceOnUse" x1="341.8214" y1="32.5047" x2="36.2769" y2="338.0491" gradientTransform="matrix(1.6822 0 0 -1.6822 65.0467 605.6075)">
	<stop  offset="0.7" style="stop-color:#790000"/>
	<stop  offset="0.8" style="stop-color:#FF00CC"/>
</linearGradient>
<path style="fill:url(#SVGID_1_);" d="M163,0v163.795c-54,0-97.565,43.784-97.565,97.794s43.898,97.999,97.908,97.999
	S261.252,316,261.252,262H415V0H163z"/>
</svg>
```

It does not load gradient in firefox (latest, OS X) when using `layer.importSVG(..)`.

I investigated what happens.. and issue is that when it's getting attribute for path fill it gets `url("#SVGID_1_") none` in firefox instead of `SVGID_1_` in Chrome, where it works fine.  Not sure how to fix this nicely. if you give me clue I am happy to create PR.

Thanks!

**Comment by lehni** [comment]
You are right. [Here's a sketch](http://sketch.paperjs.org/#S/dVPfb9owEP5XovShICWO7cTOjzEqrVPbPUx7YOVlTCgEAxnBjmyT0E3933uGUlGpi5T4vrv7znefnX++LHfCL/zJVthq4wd+pZYOt1r9EZVF9a5V2k6m94Pr0c1h13id0KZW8vPMJwjPfE9IYNRyDY69XYXZzL8Zj0y3fpdIILFegjnVxnbl3GEoJg24Nta2RRT1fY/6GCm9jijGOIIS56Ti0NRy+2EqyfM8OoZdMqTg9gDW05vlnq4W/Rflopx52IsZvNz1buxTI8AtZLloRLgoq+1aq71cFlL03mXyp1MvhWnLyjFaLYzQnZj54xHsLkp9r8tlLaQ9zQmCffs6J3OgrV8Dj7K2bt49ECeuzA/5aISrS8AbJwRllCSu+SOmiOEkdWHqIEc05bmLHmGcIZzk5KL8T11Ks1J6B+FdaXV9GBDEM0phCOyFrzZnwOOpxzFDHKds6AYwVrWep1YrI6wTDqUX2rhgWKlG6eIqzeFkQLjoA072H87dHca3t0dO9F6p8agt7eaNtKqbptjrZnB1Fm/oVHdqfic8DnAHX5TmrApZEuAwTxHjLEjAlyVnBEuaJwacWZ45BPfjuOAz8iaUE0QZDWLCg7NNOX1ICJviB9jk76lbuIHj6yH8Egstym2rammNX/z6/fwC) to illustrate the issue.
