### ISSUE TITLE
HitTest doesn't take into account clipping mask

### ISSUE THREAD

**Issue by sagendejonge** [paperjs/paper.js#671]
HitTest should not hit portions of items in a group that are not visible due to the clipping mask.  Or at least there should be a way to control this behaviour in HitOptions.

**Comment by iconexperience** [comment]
I just browsed through the code and at first sight this may be quite easy to solve.

If we implement `_hitTestChildren()` to do hit testing on the children, this can be overridden by `CompoundPath` for setting the child options (getting rid of the not so beautiful `_getChildHitTestOptions()`) and by `Group`, which can check if there is a hit on the clip mask, and return `null` in that case.

This sounds too easy, so probably I am missing something.

**Comment by lehni** [comment]
Sure sounds good to me! But it'll have to way a few days, some other pressing matters here now...

**Comment by iconexperience** [comment]
No problem at all, I just stumbled upon this.

<a href="http://sketch.paperjs.org/#S/rdXBbqMwEAbgV7F8ItoowWP1UKo99dBTpdVubyEHClPwxrGRMbtSo757jYE0TShBqEJC2Br/ePCn5EBVskca0T87tGlBlzTVWTNer4nSJJWiLIXKYxWrf4khBlPLyE+i8D/5ldhi9dtNJCqXGBxKLZSNyOYmXJKbcLsklXhFN2ZhP/EipLzXUpuIxNRgFtO3xV0bnAqTSvwUfe+ngkOKyqLpg9zNJZkkE3UVEQjPUnODqE5yc6Prskt9aJ5dXiFkZlC5RN/Osn/51q9q1/lm2HE/zSjw778N++i2BC5LGPM16/WXrXTpH33wszaeZY1dF1djYFJMrFKtKi1xJXUexJSxpoD8IKXRf91nWBXCPmFlg25vi8UdcQaqQtcyc+dua6OIqyFadd/rIhFGE2FKYnO5mp4dqavm7g9x5ScdmhOKMIEim2kRrluEGRZhFCP0GKHF2C7pW3dLranxM1IYQMrOlMKAUpimFL5HKcxTCqNKYYZSGFUKw0pVLeVXOIXFvT+gx6TaneLkE3DCTJz8Ok4+Haff7bGHD2VHtHwULe/R8otfUD6AE85w8gGcfBpO/j04+TycfBQnn4GTj+Lk13C6f+9ng8nOV1c02mzf3gE=">Here is a little example</a> that can also be used for a test case. This includes three tests, one without clipping, one with clipping using `group.clipped` and one with clipping using`item.clipMask`.

In the image below you can see the clip masks in translucent red and the hit points. Currently all hit tests return a result.

![image](https://cloud.githubusercontent.com/assets/2122773/12403176/95ce12e8-be32-11e5-8621-f4a1ad4f9e0a.png)

**Comment by iconexperience** [comment]
Another observation: If an object is not visible, it will not be used as a clip mask. This is already consistent with hit testing. But, if the first child of a group has set `clipMask` to true and it is not visble, the second child will not be used as a clip mask, even if it has set `clipMask` to true. This behaviour must be copied for hit testing.

@lehni I found this `_locked` property in `Item`, but was not able to understand it's purpose. The code comment say that it *"Specifies whether the item is locked"*, but it seems that it is not accessed anywhere. Is it used at all?

**Comment by iconexperience** [comment]
Another point to consider is that item with no fill will not return a hit result, but is still works as a clip mask. This means that for clip masks with no fill either `_hitSelfTest()` must be changed or a temporary fill must be set before hit testing.

**Comment by lehni** [comment]
@iconexperience `Item#locked` at the moment just allows you to lock items so that they can't interact with the mouse. It's there in case somebody wants to implement the same behavior as in Adobe Illustrator & co... But without a UI, it does not make so much sense.

**Comment by lehni** [comment]
And regarding the test-case: If you look at (`Group#setClipped()`](https://github.com/paperjs/paper.js/blob/develop/src/item/Group.js#L164), you will see that the two cases are in fact the same.

**Comment by lehni** [comment]
Thanks @iconexperience for the great analysis! I followed exactly your lead : )

**Comment by iconexperience** [comment]
Thanks, I am a bit surprised that this was all that was needed.

**Comment by lehni** [comment]
Such are the signs of a decent code-base!

**Comment by lehni** [comment]
@iconexperience it just occurred to me that `hitTestChildren()` is a pretty horrible function name... I much prefer `hitTestSelf()`, but what we really want is `hitTestAnchestors()` 
(Just kidding!)
: )

**Comment by iconexperience** [comment]
Yeah, there are some potentially horrible function names if you use the term `children`. One of the worst I can come up with is `destroyChildren()`.
