### ISSUE TITLE
why the button download as svg in http://paperjs.org/features/ can't work

### ISSUE THREAD

**Issue by nanmenxue** [paperjs/paper.js#673]
i use chrome.when i press it ,it say http://download-data-uri.appspot.com/  can't be found

**Comment by nanmenxue** [comment]
where is the example of import svg and export svg?~

**Comment by nanmenxue** [comment]
when i use the button locally,(i download the whole web)it can work

**Comment by nanmenxue** [comment]
can i import local svg?

**Comment by lehni** [comment]
I don't know why  http://download-data-uri.appspot.com/  doesn't resolve at your end. It works here. Where are you based?

**Comment by lehni** [comment]
There's a way to do downloads directly, without such an external service, but it only works on modern browsers:

```js
function getBlobURL(content, type) {
    return URL.createObjectURL(new Blob([content], {
        type: type
    }));
}

$('#download').click(function() {
    var svg = project.exportSVG({ asString: true });
    this.href = getBlobURL(svg, 'image/svg+xml');
    this.download = 'Export_' + getTimeStamp() + '.svg';
});
```

**Comment by nanmenxue** [comment]
but how to import a local svg,it import a svg which is in the web code.i want to import a svg like importing a image which in a folde。path like ../svg/example.svg

**Comment by lehni** [comment]
This is an issue tracker, not a support forum. I tried to respond to your initial report. Non-related questions about functionality are better asked on the [mailing list](http://groups.google.com/group/paperjs)

**Comment by nanmenxue** [comment]
thank you ,i am a new guy.thank you again
