### ISSUE TITLE
Force redrawing canvas manually

### ISSUE THREAD

**Issue by aureole82** [paperjs/paper.js#675]
Hi

Since I've got no answer on my last problem with `<canvas resize="true" />` (see #668) I moved forward on writing my own resize handler. Something like that:

```javascript
    $(window)
        .resize(function() {
            var windowWidth = $(this).width();
            var $canvases = $("canvas");
            for (var i = 0; i < $canvases.length; i++) {
                var canvas = $canvases[i];
                if (canvas.width === windowWidth) continue;

                canvas.width = windowWidth;
            }
        });
```

That works fine except the canvas is not redrawn after resizing. Is there an alternative to:

```javascript
    paper.project._needsUpdate = true;
    paper.project.view.update();
```

Thanks alot

**Comment by lehni** [comment]
At the moment, not. I think the best would be an optional parameter to update that forces the update when set to true. I shall implement this, but will soon also look into #668.
