### ISSUE TITLE
bounds of grandparent are zero

### ISSUE THREAD

**Issue by Skalkaz** [paperjs/paper.js#676]
http://sketch.paperjs.org/#S/fZFPTwMhEMW/CuFSNhqwJh66xpOHxqQmRg8eXNOwy7iLZQcCrLVp+t2F/k80cuL93jC8gTVF2QMt6csCYtPRS9pYlbWxLbkjjcVgDfCkeK1RsTNQ3FbopAPPA8SosQ1cOmdWjzJ6/Z0Of0gToEIjV+CTdN5+QhO5bKL+glmme/PvcxXqPmdAWJJnGSJ4NupidKUQgzNWKr7UC92D0pJb34qsXFYCUEzE5Ea8Po3nV/OHlHkeemkMd9iOigpbbwe37zzNe5ZgGOrpf5xLpe47bRRLsQ5NTvBQlpz0Ni0bF9v83OIsRc1TDZgGt8iKdYUkrW3ZdSrb5FkP9g7r3p2VsYouO8CSVJRckOydrF2M2g6owhk+pv7l5FBHmK5OX157kAtnNcZAy7f3zQ8=

Result for me:
when: 1
{ x: 0, y: 0, width: 0, height: 0 }
{ x: 0, y: 0, width: 0, height: 0 }
{ x: 0, y: 0, width: 0, height: 0 }
when: 2
{ x: 0, y: 0, width: 0, height: 0 }
{ x: -31.5, y: -30, width: 63, height: 60 }
{ x: -31.5, y: -30, width: 63, height: 60 }

What I expect:
when: 1
{ x: 0, y: 0, width: 0, height: 0 }
{ x: 0, y: 0, width: 0, height: 0 }
{ x: 0, y: 0, width: 0, height: 0 }
when: 2
{ x: -31.5, y: -30, width: 63, height: 60 }
{ x: -31.5, y: -30, width: 63, height: 60 }
{ x: -31.5, y: -30, width: 63, height: 60 }

**Comment by lehni** [comment]
Uh oh, you're right... This is a nasty bug in bounds caching that needs some proper investigation.
