### ISSUE TITLE
Path.Line duplicated on zoom

### ISSUE THREAD

**Issue by jonataswalker** [paperjs/paper.js#680]
Hi,

Can you figure out why I have this Path.Line [duplicated on the map](http://plnkr.co/edit/2A5mGXsncyWrUNKfEzqw?p=preview)? This happens on zooming and/or panning the map. 

I know this a very mix scenario but perhaps you can help me to fix it.

Thanks.

**Comment by lehni** [comment]
I can't see the duplicated line. How does it look? Perhaps include a screenshot so I know what to look for?

**Comment by jonataswalker** [comment]
Oh sorry for the late, but I was trying an (improbable) integration (Openlayers + Paper.js). I gave up. 
Thanks. Closing it.
