### ISSUE TITLE
Path.split with multiple intersections

### ISSUE THREAD

**Issue by vizath** [paperjs/paper.js#682]
I've come across a problem where I need to get all the intersections on a path, and splitting the path based on these intersections.
So, I use the `getIntersections()` method to get the `CurveLocations` and then call `split` with all these `CurveLocations`
Since the `split` method changes the `firstSegment` of the path, the following calls to `split` cuts the path at the wrong offset.
I've also tried to call `getLocationOf()` with `CurveLocation.point` before the split, but this is not working either... (does `getLocationOf()` returns the right location)

http://sketch.paperjs.org/#S/lVTLboMwEPwVi0uIhJLwyCVV1UNPlSo1ao5JDg7ZAsKxke00aqv+e9c8YqhooAcj8O6MZ3cHfzmcnsBZOZscdJw6nhOLo/mOBVeCwSxmQKU7vdvJHTfrnUoiIdaUJwx8ck84XMhrs+Gar7XIuHb9xcIj+Jh6Zcom+wS7V/EZroLqtKFZ4/vMctljqvQydaa0FDk8CiYkwiYHRuN80o4DQxwcMajlGfqFB7eEL43I5RjhwYDwwAoPfguXcJx0xOHZIBVCM8FNR6pyEtBPrYByS7KKt5kRE4nbQdtx1T0pWKa7KdvFvtPVngx/b3nMms/JJdMpOVH+QWLKmCJaEBT4LGJqIC9v7rS33eGQT8JRPgkH2h3aisIBn4TjfBIN+SQc5ZNoQHhkhUf/8klQ+yTs90l02ydB97dm9Rj9Nmlrth0o+mdWmD7YSht8MArvd/DorQztlOJDnYtCKBwMmusAuAdE4R1lgjwhDzcLuqrybDXtY+rRl2a/JvwdqhuEt+JBAs1LIuWstvvvHw==

Is there a better way of doing this ?

Thanks !

**Comment by vizath** [comment]
I found a workaround by calculating `getIntersection()` between everytime I split the path.
This makes a lot of tests, but it will do for now.
Since `getIntersection()` will returns the segments each side of the splited point, I need to `uniq` the  curveLocations based on their point, and because the splitting was creating segments of length zero infinitly (which I cannot reproduce in sketch).

http://sketch.paperjs.org/#S/vZTBbhoxEIZfxdrLehVqaCAXKKeoh0o9ROWYRJHjHXYNxt7as6RpxLt3vA6BJSjtqUiwePzPP5/H9r5kVm4gm2aLNaCqs0GmXBnHytngDAhlQHpezO78nY1fvWQcnxtwS/bA5vM5y1tbwlJbKPOCvUQJo89WehaU1w2yOSudajdgUSgPEuGrgTjieRLkyTxmpYCI/pSWI/zC4Upu5avwVBe8irIasZkOh5HDB+U8rIJwvjoKfNpoK1bhYPBGVIMshWwasOV1rU3Jk3VC2u0XPRyyJ40120j7zJQ0JjB0rAL8ZpFKgEJN7eLFXh9X7ykqbWVgTIwWntiPfYDH0Y3T1ILPo9GAXY1GxaCTLPRvSDH6KRJE9Gok1nubG/ovDl6HMkneSUVA79Zw7YzzsUOPRqp1fjwPhvKgpEn0LczOgk8+Ar+M4Jd98HEEH5+CT/4CPjmAT07BPZ2qHpw+bjgp0nLe7URnlnxPMx5Ea/VP3gsP2FKaAPRobRfhqvVb+O6UjCM619QVbL1lvbhoYi8EugV6bSu6JWyXii4Jn3e8VHE0o8eXProwYCusaebi4uja7G+dcRXXg7Mpr1cRT7tBhXryW33/dtyPJ0TsjQiN0dhrQvGBWhkXIO4fP6/6t514l/WfNmNHb7VHevOsO0XIprf3uz8=

**Comment by lehni** [comment]
Use CurveLocation#split(), which handles this internally for you.

**Comment by lehni** [comment]
Reopening as I have a better idea to solve all these calls nicely.

**Comment by lehni** [comment]
With this change in place, your example works correctly unmodified here.

![screen shot 2015-06-16 at 19 37 19](https://cloud.githubusercontent.com/assets/213275/8189828/30647e10-145f-11e5-93fe-932f39476ed0.png)

**Comment by vizath** [comment]
Nice, I will try this in two weeks.

Thanks!
