### ISSUE TITLE
is paper.js not useful in mobile web app?

### ISSUE THREAD

**Issue by nanmenxue** [paperjs/paper.js#685]
i use my phone to draw a line in a web app which use paper.js.it apper a line after about 2 second after i draw a line.is it my problem?

**Comment by lehni** [comment]
It should run much faster than that. Are you using paper.js through PaperScript or directly from JavaScript? If directly from JavaScript, it could be that you forgot to call `view.update()` after the changes?

**Comment by lehni** [comment]
Closing due to lack of information. Feel free to open again, once details are available.

**Comment by TheSalarKhan** [comment]
Had the same problem. turns out if you put hidpi="off" on your canvas element it becomes really smooth for mobiles.
