### ISSUE TITLE
Using PaperJS in Javascript directly stops propagation of touch events (scrolling)

### ISSUE THREAD

**Issue by mitsos1os** [paperjs/paper.js#686]
Hi, PaperJS really helped me in implementing a drawing web app. I face one problem though, same as issues: https://github.com/paperjs/paper.js/issues/585 , https://github.com/paperjs/paper.js/issues/472
My difference is that I handle paper through javascript directly, and I **do not initiate a tool** to listen on mouse events at all. Even without any tool, the touch events (scroll on canvas element in smartphones), isn't working. Is there any way to disable handling of mouse events completely and keep the screen scrolling functionality?

Thanks!

**Comment by mitsos1os** [comment]
Hi, after a lot of inspecting through the code, I found the source of the issue.
In **paper-core.js in line 10451** (version 0.9.22), the canvas element is added some predefined css styles. 
One of them is **touchAction** which is set to none. So in case you do not need any interactive functionality on the canvas element, and still want to enable drag on mobile devices, you should set this property manually to **""**, which is the default...
In order to do that I simply call this function on my canvas element after setuping paper on javascript:

	function(el){
	    /*
	    	This function will accept the canvas html element and enable css drag that was originally disabled in paper.js for canvas that we do not need functionality and want mouse drag on
	     */
	    var name = 'touchAction';//the property that needs enabling for drag to work
	    if (name in el.style) {
	        el.style[name] = '';
	    }
	}

Hope I helped someone!

**Comment by lehni** [comment]
Opening again as this does sound like a bug to me, and the information you found is useful.

**Comment by ms705** [comment]
This is still an issue in the latest version; I encountered the same problem as originally reported with a setup that has a paper.js-rendered `<canvas>` spanning the background of the page. On mobile devices, touch-based scrolling stops working after paper.js has loaded (even though the canvas is on z-layer `-3`, i.e., below all other content).

I tried the solution proposed by @mitsos1os, but it did not fix the problem for me.

**Comment by lehni** [comment]
Related: https://github.com/hammerjs/hammer.js/issues/241
https://github.com/hammerjs/hammer.js/wiki/How-to-fix-Chrome-35--and-IE10--scrolling-(touch-action)

**Comment by lehni** [comment]
Please let me know if this works for you!

**Comment by lehni** [comment]
Ok, false alarm. I was testing against the wrong version, this isn't fixed...

**Comment by lehni** [comment]
I have committed a row of changes to the new mouse-event handling code today that should finally solve this. Here how it's now handled:

- Any native mouse event can trigger events on tools, items and views. If at any level such an event is handled, `event.preventDefault()` is called at the end, before returning from the handler on the view.
- `touchAction:none` is not being set anymore.
- If a paper.js view doesn't implement any such handlers, touch scrolling shouldn't be affected.

And what I am thinking of implementing further:

The current convention is that if any handler returns `false`, both `event.stopPropagation()` and `event.preventDefault()` is called. I am considering adding a new convention to this, for the situation where `true` is returned: This will tell the view that default shall not be prevented even though the mouse event was handled.

**Comment by lehni** [comment]
I have been putting a lot of work into this one over the past days, and I believe I finally have code that handles all these situations well. 

I don't like the convention I introduced above about returning `true`, as it only really makes sense for mousemove events, and is only required right now if I *don't* want the handling of a move to consume the scroll. I think it's the better approach to assume that mousemoves don't prevent defaults, and if I want it to, then I explicitly call `preventDefault()` or return `false`.

**Comment by lehni** [comment]
So all this is implemented now on the `develop` branch and ready for testing.

**Comment by lqez** [comment]
Thanks!

**Comment by Chaoste** [comment]
Is this feature already part of the newest version? I'm facing this problem right now and I don't have any clue what I am supposed to do. I have a Tool which uses onMouseUp and onMouseMove (for highlighting stuff so it looks like a hover event). Do I jsut have to return True in "onMouseMove" if want to enable scrolling events?

**Comment by RickMohr** [comment]
The solution here doesn't work for my use case, where my canvas is part of a longer scrolling page on a phone. I want to handle drag gestures on paper items, but if you drag the "background" I want the page to scroll. I'd like to return `true` from my `onMouseDrag` handler to allow the phone's default scrolling behavior, but paper calls `preventDefault` regardless of the return value.

(No luck with the hack of setting `event.preventDefault` to a no-op instead of returning `true`)

**Comment by alejandrozeppelinlabs** [comment]
Any news on this? its not working for me either
