### ISSUE TITLE
Color.highlight cannot be set back to null or undefined

### ISSUE THREAD

**Issue by iconexperience** [paperjs/paper.js#688]
Once the `highlight`property of a `Color` object has ben set to a non-null value, it cannot be set back to null.

In <a href="http://sketch.paperjs.org/#S/rVTBisIwFPyVRy6tbKm1sJeIJ9nrsuCx7SE2zzYYk5LGdUX8903c2oq6siwGesibec2bmZADUWyDhJLFGm1Zk4iUmvv9eAxvX2zTSJxQeNdQi6qW7rO5KoUpJcIMFO7gg9k6np8q4afAXVyismgimCTJaHomxysh5VxLbVzbIVfgVmUYF45MzwW/WqublkKWBXuUUu+CCJI4eS0iyIKlZOXaFSZFEQ0d/i9MUrBmiz/VY4dqIyqhKHQjNLoVVmjVoRxbKxTzlZ6y1FvF29h4nfOTjlwdnQatWu1gqaswJ9eK4t6aWU7gBX7HvR+5GpxNKSzQDtZGYGtUTskeWrRuumrAwGpQWymdKnBD4koo5Gd708dhxIzz8IRroWyYJolzdTS6yij9R0gG+fMSSv8QUXono47dW3XDdeNepnmtdgjI2+g8nt6P/G7LZeZ3Cd5gjhItPmI9/cgbOAt6PCic0P4SPf1o94gsDbJ1429bS2hWHL8B">this Sketch</a> you can see that it is just impossible to get rid of the `highlight`property. Setting to null, deleting, nothing works.

I am actually not sure why this is happening, but it must have something to do how Paper.js handles properties.

Currently the only way I know to get rid of the `highlight`property is to manually create a copy of the `Color`object without the `highlight`property.

**Comment by lehni** [comment]
Yes, those are not simple properties, they are accessors. It's a simple bug, fix coming up in 3..2..1..
