### ISSUE TITLE
PaperScript does not correctly compile increment operator

### ISSUE THREAD

**Issue by backseatviolist** [paperjs/paper.js#691]
The following highly artificial example shows a difference between PaperScript and vanilla JavaScript:

    eval('var x = 1; x = x++; console.log(x)'); // outputs 1
    paper.PaperScript.execute('var x = 1; x = x++; console.log(x)', paper, 'foo'); // outputs 2

**Comment by lehni** [comment]
You're right. Here a slightly improved script to see what's going wrong. Will investigate a fix.

```js
var code = 'var x = 1; x = x++; console.log(x)';
console.log(paper.PaperScript.compile(code, paper));
eval(code); // outputs 1
paper.PaperScript.execute(code, paper, 'foo'); // outputs 2
```
