### ISSUE TITLE
make CanvasProvider accessible via paper scope

### ISSUE THREAD

**Issue by jardakotesovec** [paperjs/paper.js#692]
CanvasProvider is very handy tool for some custom stuff and would be great if its possible to access it via paper.CanvasProvider or something like that. 

Currently I don't see any trick to access it or did I miss something?

**Comment by lehni** [comment]
I don't think I want to expose internal classes and loose the possibility to change / adjust functionality without breaking backward compatibility. The functionality of `CanvasProvider` can easily be replicated in an app, and I think it's better to keep it separate.
