### ISSUE TITLE
smooth() only a certain part of a path

### ISSUE THREAD

**Issue by hirasso** [paperjs/paper.js#695]
Hi there, would it be possible to introduce a new functionality to smooth() a path only for a certain range of segments?
I would imagine something like this: 
```javascript
path.smooth([index1, index2]);
```
That would be amazing!

**Comment by timuric** [comment]
@hirasso Looks like this feature is coming with the new smooth functions #338

**Comment by hirasso** [comment]
@timuric wow, a lot happening over there! Can you point me to the comment in #338 where they talk about my issue? I couldn't find it — tl;dr   :)

**Comment by lehni** [comment]
Closing this as the work is being discussed over in #338.
