### ISSUE TITLE
option to store URLs instead of embedding raster image data in both JSON and SVG exports

### ISSUE THREAD

**Issue by m5x** [paperjs/paper.js#696]
Please, add possibility to optionally store just URLs of raster images in JSON and SVG exports instead of embedding them. It will help prevent vast data redundancy in projects like ours where many drawings share the same raster images of thousands by thousands pixels, but I believe there are many other practical usages as well.

**Comment by lehni** [comment]
I think this already works in JSON, no?

```js
var raster = new Raster({
    crossOrigin: 'anonymous',
    source: 'http://assets.paperjs.org/images/marilyn.jpg',
    position: view.center
});

console.log(project.exportJSON());
```
```json
[["Layer",{"applyMatrix":true,"children":[["Raster",{"applyMatrix":false,"matrix":[1,0,0,1,396.5,377],"crossOrigin":"anonymous","source":"http://assets.paperjs.org/images/marilyn.jpg"}]]}]]
```

**Comment by lehni** [comment]
In order to not break backward compatibility, I am going to add a new option `options.embedImages` that controls this behavior, defaulting to `true`:
```js
console.log(project.exportSVG({ asString: true, embedImages: false }));
```
