### ISSUE TITLE
Two Paths sides overlapping

### ISSUE THREAD

**Issue by radames** [paperjs/paper.js#698]
In my design I have a hexagon compost by many triangles, those triangles very often share the same side, I'm not doing a compound path, what happen is when they are overlapped a white line, appears, they don't blend properly.

I manage to reproduce the error here

http://i.imgur.com/ifDBmIB.png

http://sketch.paperjs.org/#S/fZFdC4IwFIb/ytiNCiJrYYHSVX8g6DK7OLkTimuTueoi+u9tgiD5cXf2Pns3Hs6HKnggzei5QVtWNKalFv78AkNasBU5EIVvcnJjGOWF8llyr6U8aqmNo4FBEUxAArKtwGGW7PYDBSHC/jFdKxtuWUxSFkXzNGU9XuS+vRnXS6k7FO5Ha57owkINCnzOgS9K8HULvq7xjycec/0xnXq4pdwMQtP6+x3NLtfvDw==

Here are some shots of my application, when I export a PNG of the small size canvas the effect is amplified 

http://i.imgur.com/Z3N0a4j.png
http://i.imgur.com/8B92X85.png
http://i.imgur.com/p2zeBjj.png

Any workaround in how can avoid it? I trying to round the numbers, seems it get better but even thought it still not smoothed.

**Comment by cjmalloy** [comment]
Using .unite() works.

http://sketch.paperjs.org/#S/hZHRCoIwGIVfZezGCTJsYkHRVS8QdJldLPeH4tpkzrqI3r1pCVpqN2P/OYfz820PrPgV8BofCrBphgOcatHMN25QyW2GtkjBHe3dlfibRDUaveRS7rTUxrmeAeH9GJTLMuPODuly1blcCNKW6VxZEoU0DlDsTt8fT8ThJzKTebcshjWp1BUIt92aGpyYqA6HjfGwSSA2T8T+I31HRpnGe4aJaabIiS12rXILpI33ngK4If2abnZ/fTbAi7JZWeH18fR8AQ==

**Comment by radames** [comment]
yes, it makes sense if they have the same color and alpha.
I guess my problem is they differ very little in the alpha with the same color, so I can't unite then.

**Comment by cjmalloy** [comment]
Is the background always white? You can precompute the alpha blending and use a colour with no alpha. You will still get the white line, but since you are no longer using alpha you can just overlap the bottom triangle slightly to merge the colors.

**Comment by radames** [comment]
Not really, I'm exporting the image with no background at all. Do you think this is a bug? I'm not sure what to expect

**Comment by cjmalloy** [comment]
I don't think this is a bug, this is just how the canvas works.

Here's what I meant by my previous comment. I removed the alpha and
overlapped the bottom triangle.
http://sketch.paperjs.org/#S/hZHRDoIgFIZfhdGFujklktpsXfUCbV1mFyQ4nQQOrS5a796hzc3S6obB+c4P5xt3rPlZ4hTva9nlJQ5xboQ7X7lFDe9KtEFa3tAOtn6wzrSrRUWl1NYoY4F6s6JgCUs8gHH8jiOumpJDE4mWqz7MhfBfV5pKd/6ChIgEwTRkBCgs37gLz9kA58q0UsCDnb1IKGa696BTIvSPCf2tQifGGUzziUc2U/khHdvA/5ys5HXj+lucHo6PJw==

**Comment by lehni** [comment]
This is not a Paper.js issue. It's a slight imprecision in the antialiasing code of the canvas drawing routines. Adding a little border to your shapes, or merging shapes should help solving this.

**Comment by radames** [comment]
you're right! that was my conclusion after all.
thanks
