### ISSUE TITLE
Clipped Group border pixelated

### ISSUE THREAD

**Issue by chad-autry** [paperjs/paper.js#703]
My goal is to try and clip paths to a non-bordered arc/circle.
However, the clipping circle does not cleanly match the lines to the background circle/arc even though it has the same radius as the arc path item below.

Here is a contrived jsFiddle demonstrating, http://jsfiddle.net/kodfish/4Lrckw9k/1/ in that instance I'd expect it to at least visually appear as if there were no clipping.

I'm making globes using circles and paths, so what I'd really like is a way to cleanly map the path item onto the shape below.

**Comment by lehni** [comment]
This is most probably a browser issue, not a bug in paper.js. You're seeing this on Chrome, correct?

Some resources:

https://code.google.com/p/chromium/issues/detail?id=7508
https://code.google.com/p/chromium/issues/detail?id=424291
http://stackoverflow.com/questions/9536257/how-to-anti-alias-clip-edges-in-html5-canvas-under-chrome-windows

**Comment by chad-autry** [comment]
I do use chrome, but opening the jsFiddle in Firefox and IE I am seeing the same issue. Blurry grey lines connecting the 2 hemispheres instead of appearing to be totally disconnected.

It isn't a huge deal, I am fine with leaving the issue closed and monitoring behavior as chrome is updated.

**Comment by lehni** [comment]
Oh I think this is probably just because of imprecision of antialiasing then? That's also a known effect.

**Comment by chad-autry** [comment]
I tried editing the jsFiddle and adding the background circle and arc to the clipping group.

Chrome: The whole image became pixelated, but the background circle bleed did not show through (as epected)
Firefox: The image remained anti pixelated, the background circle bleed went away
IE: No change (this one was weird, nothing happened at all, though personally I don't care about it much)

**Comment by lehni** [comment]
Could you provide screenshots? It's all a bit abstract otherwise.

**Comment by chad-autry** [comment]
![image](https://cloud.githubusercontent.com/assets/10950439/8399691/c9cf364e-1dd8-11e5-8176-79f3bbbbb7b5.png)

Again, the JSFiddle for circle/arc not a part of the masked group can be found here: http://jsfiddle.net/kodfish/4Lrckw9k/1/

The JSFiddle of the circle/arc a part of the masked group can be found here: http://jsfiddle.net/4Lrckw9k/3/

I think its acceptable that the "artifact pixels" are there when the background shapes are not a part of the masked groups. The pixelation with Chrome should be fixed, as your resource links say. The weird thing about IE is they both look the same. Its as if the masking isn't applied to all the shapes. Firefox is interesting to me, since the anti-aliasing of the circle/arc looks better to me when masked, than not.

**Comment by lehni** [comment]
Good news! It looks like this is resolved in Chrome Canary (57.0.2926.0) Should land soon, I hope!
