### ISSUE TITLE
Paths created from SVG data have incorrectly closed segments

### ISSUE THREAD

**Issue by 74hc595** [paperjs/paper.js#705]
It seems that, when creating a `CompoundPath` with an SVG path data string, or when using `Project#importSVG`, any "moveto" (`M`/`m`) commands incorrectly force the closure of the previous segment.

For example, the following data
```
M10,10 L20,20 L10,30 M30,10 L30,30
```
should create a right-pointing angle to the left of a vertical line, like this: `> |`. It is rendered correctly in Safari, Chrome, Inkscape, and Illustrator. However, Paper.js closes the angle and turns it into a triangle, so the result looks like `▷ |`.

It looks like this has been explicitly coded on [lines 197-198 of PathItem.js](https://github.com/paperjs/paper.js/blob/master/src/path/PathItem.js#L197-198), but is a violation of the SVG specification.

**Comment by iconexperience** [comment]
I think you are correct. The relevant parts of the SVG spec can be found at http://www.w3.org/TR/SVG/paths.html#PathDataMovetoCommands
