### ISSUE TITLE
Many frame events, problem with Chrome and Opera

### ISSUE THREAD

**Issue by andreamattioli** [paperjs/paper.js#706]
Hi, I've found a problem with Chrome 43.0.2357.81 - Windows 7 - Paperjs v0.9.22:
- two calls to ```view.on('frame', func1)```, each call do the same animation, but on a different path
- the second animation is still going, then the first animation is completed, so its func1 calls ```view.off('frame', func1)```
- at this point the second animation break up with *Cannot read property 'apply' of undefined" on line 623*

Changed ```for (var i = 0, l = handlers.length; i < l; i++)```
with ```for (var i = 0, hand; hand = handlers[i]; i++)```
it seems that the problem is resolved.

On Firefox and others we don't have this issue. Safari not tested.

**Comment by lehni** [comment]
Yes I see what you mean. Tricky business, as in order to solve it properly we'd actually have to use a linked list instead of an array.

**Comment by andreamattioli** [comment]
Why can't you use the change I've posted above?

I use that way in all my for-loops, I've tested with jsperf.com that is faster than the classic one

**Comment by lehni** [comment]
Deleting an entry at a given index will shift the indices of entries above it. If you have three event handler, and the first one removes itself, then the second entry will probably get skipped and the handler won't get called.

**Comment by andreamattioli** [comment]
But I'm not deleting the entry. The difference between the old code and the new code is that the new control inside the for-loop isn't based on the existence of the entry (i < len), but on the value of the entry (hand = handlers[i]). In this case i found that the entry existed but its value was undefined, so in the loop the code breaks.
I hope I was good to explain.

**Comment by lehni** [comment]
`view.off('frame', func1)` deletes the entry, after which `len` is one too big, hence the undefined entry. Your code won't prevent the fact that when calling `off()` from within one event, one of the others will get skipped.

**Comment by andreamattioli** [comment]
Ok, I'm starting to understand something :)
Obviusly another question: inside ```view.off()``` you use ```delete``` which removes all the array of handlers-type, or you use ```handlers.splice(index, 1)``` which removes 1 array's entry, doesn't create an empty slot and reduces the ```len``` value. What can create an empty slot and make ```len``` so inconsistent?

**Comment by lehni** [comment]
It's the fact that in the loop, len is cached in a local variable and doesn't get updated after an element is removed.
