### ISSUE TITLE
Absolute rotation

### ISSUE THREAD

**Issue by not-only-code** [paperjs/paper.js#712]
Is there any option to assign a **total** rotation to an item?

    // now
    item.rotate(45); // 45º
    item.rotate(60); // 105º
    
    // i mean something like
    item.rotate = 45; // 45º
    item.rotate = 60; // 60º

**Comment by lehni** [comment]
Already there:

http://paperjs.org/reference/item/#rotation

But this only works when #applyMatrix is false. See more on the topic here:

https://groups.google.com/forum/#!msg/paperjs/R3O0peJPFc0/A3krjdY70-wJ

**Comment by not-only-code** [comment]
Thanks it works.
