### ISSUE TITLE
ImportSVG returns undefined

### ISSUE THREAD

**Issue by sansumbrella** [paperjs/paper.js#715]
When importing the [ghostscript tiger](https://commons.wikimedia.org/wiki/File:Ghostscript_Tiger.svg) in javascript, no value is returned from project.importSVG. The graphic is displayed correctly.

Expected behavior:
`importSVG` returns a reference to the `Item` containing the SVG.

Current behavior:
`importSVG` returns `undefined`.

```javascript
paper.setup(document.getElementById("paper_canvas"));
var svg = paper.project.importSVG("img/ghostscript_tiger.svg");
console.log(svg); // => undefined
```

**Comment by lehni** [comment]
You need to use an onload callback function to know when the file is loaded:

```js
paper.project.importSVG("img/ghostscript_tiger.svg", function(item) {
    console.log(item);
});
```

**Comment by sansumbrella** [comment]
Thanks!

The documentation doesn't mention callback functions (and I was a bit surprised that the docs suggested it would be a blocking call in js). Is there somewhere I can contribute to the documentation?

**Comment by lehni** [comment]
Yeah that feature was added later. Hard to keep it all in sync... :(
