### ISSUE TITLE
Path intersect function error

### ISSUE THREAD

**Issue by abcoskar** [paperjs/paper.js#716]
Hey

I'm trying to use paper js to make a calculator based on graphics, the problem is when I use the PathItem.intersect method with a path that is not clockwise. Here is the code and the result:
https://jsfiddle.net/abcoskar/ut7d5uc9/1/

![errorpaperjs](https://cloud.githubusercontent.com/assets/713277/8291369/b7c45a72-18ee-11e5-90ce-5d9b36e14512.png)

Original post in google groups: https://groups.google.com/forum/#!topic/paperjs/JI1tKfrmazc

**Comment by lehni** [comment]
The code is still too cryptic for a test case. Please isolate the one path where the problem occurs and describe the expected outcome.

**Comment by abcoskar** [comment]
Sorry about that.

https://jsfiddle.net/abcoskar/3cx4r2x1/

**Comment by lehni** [comment]
Yes, this is the same problem as #450

**Comment by lehni** [comment]
Here the sketch of the above example, for future tests:

http://sketch.paperjs.org/#S/jZIxb8IwEIX/yikLRIpCOrAEVR1Y2g2VsengJBcSxdxFtiFqEf+951AgwII3P737fPfOh4DUFoM0WLfoijqIgoJLf98rAwYLp2ijEV6BsIdOdWjiz7M6vWorbshN5wlEkITRyLxuflH0COZJGC4yOmNviCvl6hH28my4gIz8LbbOcItL1mykcpJrVbQTwZ2AvHO6IVyx/tkwPaCnh4xAzgiSesYOJxkdwwFzi4hVWT5Ml/jZvPs57zAwzGYfFbi6seBLYMt7tFByT9A46Nm09ineS3KN8M5eaLY4jFkpbTG8pNKJJlnc2YWGxkqmQ8zSobT4jgZBWnQ1Qmc417h9y8jXxxa12LAUkDM7XPzLVaP1ZRsbg0inbWQkPyg3qNrO922D9Ov7+Ac=
