### ISSUE TITLE
PointText strokeScaling looks strange

### ISSUE THREAD

**Issue by sapics** [paperjs/paper.js#721]
Please look at http://sketch.paperjs.org/#S/hY/BCsIwEER/ZcmlCjkkOUb8ByHe2h5i3Gpp3UiyqFj676biwZNeBmZneMtMgvwFhRVuQA5nIUWIx8U3qaGbT8D4YA1bILzDLvbE+3JYTSESI7GttNaVhOuS2ForJaFIK6ErBdc/0YJR83rzjTM/cMaYvzgJmVMc0AU/9nSy0Pkx4+dJWXBI6Ic3Igtbt/ML

I cannot draw PointText at correct position which strokeScaling=false.

**Comment by lehni** [comment]
Implementing strokeScaling on text is unfortunately not possible as long as we don't have access to the glyphs, since canvas doesn't natively support the feature. But of course it shouldn't fail rendering the item.
