### ISSUE TITLE
Make the node-canvas dependency optional

### ISSUE THREAD

**Issue by MattouFP** [paperjs/paper.js#722]
When you use paper's npm module with browserify you probably don't want to/can't install the node-canvas library which is useful but heavy.

A solution would be to use npm's optional dependencies (https://docs.npmjs.com/files/package.json#optionaldependencies). Another interesting option is to use the canvas-browserify module that wraps both the web and node canvas APIs (https://www.npmjs.com/package/canvas-browserify).

**Comment by lehni** [comment]
Same as #664

**Comment by MattouFP** [comment]
Sorry about that!
