### ISSUE TITLE
paper-full.min.js broken in 0.9.23

### ISSUE THREAD

**Issue by crazysheeep** [paperjs/paper.js#724]
Hi, this might be the wrong place to report this since it has more to do with the build/minification than the  actual code (sorry!)

But as per the title, `paper-full.min.js` has a syntax error. I've checked this from **Chromium Version 43.0.2357.81 Ubuntu 14.04 (64-bit)** as well as **Firefox 38.0**.

`paper-full.js` is fine and so is `paper-core.min.js`. Everything is also ok in 0.9.22.

**Comment by lehni** [comment]
There appears to have been a problem in uglifyjs 2.4.16 which has already been fixed in the meantime. I've updated the dist files accordingly, you can download them again now.
