### ISSUE TITLE
Basic installation fail ...

### ISSUE THREAD

**Issue by glomotion** [paperjs/paper.js#725]
Hi there. 

Forgive me - this is my first foray into this kind of lib in quite a long time - but i'm really struggling to get up and running with the simplest of the tutorials listed on http://paperjs.org/tutorials/getting-started/working-with-paper-js/.

See my codepen http://codepen.io/glomotion/pen/ZGoyvy

Any ideas what I'm doing wrong?

**Comment by lehni** [comment]
Your example seems to run. Did you manage to resolve the issue by yourself? For the future, this is a bug database, not a support forum. It's best to ask questions on the mailing list instead: http://groups.google.com/group/paperjs

**Comment by glomotion** [comment]
Apologies Jürg, yep a friend helped me get it working. For sure, I'll use the google group for support rolling forward. :)
