### ISSUE TITLE
Smoothing/simplifying a CompoundPath

### ISSUE THREAD

**Issue by mmase** [paperjs/paper.js#727]
I see that `simplify` isn't available on `CompoundPath` but `smooth` appears to be. However, it doesn't seem to do anything. Is this a bug?

**Comment by lehni** [comment]
Reopened because there are a couple of methods that would make sense if they were exposed on CompoundPath, similar to `smooth()`.

**Comment by lehni** [comment]
Adding more functions to this list:

`simplify()`
`getNearestLocation()`
`getNearestPoint()`

**Comment by masedesign** [comment]
It would be amazing if a polygon could be simplified using cubic bezier or quadratic curves. The only thing out there right now simply adds more paths to create the illusion of a smooth polygon which just complicates it further and degrades performance.

**Comment by lehni** [comment]
I'm sure there are other things out there : )

Is this what you're looking for: http://paperjs.org/examples/path-simplification/
