### ISSUE TITLE
PointText position renders differently depending on the order in which you define parameters in the constructor

### ISSUE THREAD

**Issue by eadlam** [paperjs/paper.js#733]
PointText position is effected by the **order** of properties in the object literal that you pass to the PointText constructor. For example, If you define fontSize first and position second, then it's position ends up being what you set. However, if you define position first and fontSize second, the position ends up being different from what you set. 

This is unexpected because object literals property order is supposed to be undefined.

Here is a demo: https://jsfiddle.net/eadlam/x214xwne/

**Comment by sapics** [comment]
@eadlam　It looks very important!

Sorry, i don't know about setting place by `position` property is valid or not.
By the way, from reference http://paperjs.org/reference/pointtext/, i guess that set position by `point` might be better for `PointText`.
When i use `point` property, it looks work well https://jsfiddle.net/sapics/sk3kdcwa/3/.

**Comment by eadlam** [comment]
@sapics 

Thank you! It looks like I was just using the API incorrectly. I'll use point instead.
