### ISSUE TITLE
Bounding box of PointText breaks on Firefox when setting fontSize using em units

### ISSUE THREAD

**Issue by eadlam** [paperjs/paper.js#734]
I've run into an issue in Firefox when I've set the fontSize of PointText using em units. The font size changes correctly but the bounding box breaks, which you can see if you setSelected(true). Here is a demo:

http://jsfiddle.net/eadlam/7o7uq3yp/

**Comment by lehni** [comment]
Here the same in Sketch, for testing:
http://sketch.paperjs.org/#S/xZLBCoJAEIZfZdiLCVJqeNno0hMEdnM9mE4l5uxiU0nSu7dWlzqEQdAcBmb+mZ+PYTpBWY1CirhCznfCE7ku+noygYU+UlHSFta6BV0pOmUNMLYcwBwIz2Ayg814qUvilW2POkVgI9fESCzBiXWN0EuO95A2VorLC0oI/WfL9Ovy3W+UBL7vgU2p+xw84B5zxkJyc0RFV3emSNEnzvAHnE7om9YZxBr9nTWIDA9iDb++K2l+4Z3+hHccYT0M+ONx7duuG8yqu8VByCS93gA=
