### ISSUE TITLE
Blend Modes are lost when rasterising

### ISSUE THREAD

**Issue by nicholaswmin** [paperjs/paper.js#735]
#### Test case ####

- Create an element (e.g a `Circle`)
- Create another element (e.g a `Rectangle`)
- Make sure the 2 items overlap
- Set `blendMode` of overlapping element(top-most) to e.g: *'destination-out'*

- Rasterise both elements
- Remove the original elements keeping only their raster copies

##### Expected Result ####
- The top-most element should appear to be erasing the bottom element (due to `destination-out` blend-mode). 

##### Actual Result ####
- Top-most element does not erase the bottom element
- **Rasters do not retain the blend-mode property.**

=====

#### Test Sketch ####

http://sketch.paperjs.org/#S/VVLBbqMwEP2VERfSKE2yUntJtYc05RCpTapAL116MDAJVuwxMt4i7Wr/fceGlgSkEfjNmzczz38jEhqjVZSe0ZV1NItKU/n/xXSaE0whfnxOdk/wsn9KUnjepxnsd3BYp1ly2L6vs+1+F0OW8PFmnSaBEcKWQBDg8WisA2dA6saaTwSLVKGVdIIGLYNaUImzntMxLFrH8B8EoRSgQo3kWuhqJKgMIVRWdJ7tatSBJKjiotrX5jNpwVh5kiQUlKaR2M7HnrIaYZumb8kKHhX3cat51BZaRO1bLBCUaV2fe/EY8pWH1oaqOU0XOeW0WAQIS+e77wSFYZFzMadPYXvoJxB28CpcPT/wv6CTwsmP++UMOADH5TKEm4ecPGF+lEptjDKWqXGhRHmOH0a52NfnJcSheq8TJO2l0kba8lrmjr/ug0iffS1jsYpHqPALeuH9eIi35HilThq6Nb/dVy+HwSzvR2FcPU7cI0wN03ybOvHaY7ffWYPmdV5Q8MYOdo/GNjweSIe6HdbV+z+5mOzixL98rQuL4twYydcpWv36+Pcf
 
=====

#### Notes ####

- As a performance optimisation, I `rasterise()` all elements on my board and retain only their `Raster` copies(I remove the original elements).
- I tried here to build an Eraser Tool, using the `blendMode: 'destination-out'` trick.
- When I `rasterize()` the eraser paths and removed the original `Path`, the `blendMode` property no longer applied thus the erasing was lost

Thanks

**Comment by lehni** [comment]
That's not a bug. It happens because the blend modes are used when rasterizing each item individually. The resulting rasters have their #blendMode set to normal. If you put them together into a group and raster the group, you'll get the correct appearance. Since that's not what you want, I'd suggest rasterizing them both with blendMode set to normal, then setting the eraser's blendMode afterwards on the resulting raster.

Would that work for you?

**Comment by nicholaswmin** [comment]
Perfectly. Thanks!
