### ISSUE TITLE
Subtracting rectangle path from circle produces unexpected results

### ISSUE THREAD

**Issue by markmanx** [paperjs/paper.js#736]
The circle in this example should be split cleanly into two halves by subtracting a rectangle.
Sometimes this happens, sometimes not (depending on the y-positioning of the rectangle)
Setting a y-position of 10 seems to work, but a y-position of 0 does not.  Any ideas?

http://sketch.paperjs.org/#S/dZDBqsIwEEV/JWRjhb4QBRcqrvwB0WXtIo3jMxiTMp1WRfx3J0WKIO7m3jtzZpKHDOYCciF3ZyB7krm08ZB0Z1BYh1asRICr2Bg6qTVrD1mhc6HLXMz0eLkPqUkdW+/vO/BgCQ48QtgCZ/uQMMjuG1ObGlD1sC27Jvx/8IrJnKupLhM2Df3C9lkdG0cuBnXj4G+qv/w7+3o4omkr1v2xXBIaS1nqH56AcIkdZMPuD80DA5YhnYOrshAI8B0enffr6CNyOqp8C6Ml/2SFYM51dIEauSjK5ws=

**Comment by lehni** [comment]
@hkrish this seems to be different from the other issues we're facing in boolean ops. Any thoughts on why this may occur?

**Comment by iconexperience** [comment]
@lehni

I agree, this seems to be different. My guess is that the negative corrdinates play a role here, because it seems that if you shift the objects to the middle of the view before the subtraction, everthing works as expected.

**Comment by lehni** [comment]
I have managed to identify the source of this, an error in the way how we prevent rays from being counted twice at the beginnings / ends of curves in the getWinding() code. Rather tricky stuff, I hope the fix is solid for all cases...
