### ISSUE TITLE
Angle of last segment in rectangle path

### ISSUE THREAD

**Issue by markmanx** [paperjs/paper.js#738]
Hi all,

When creating an instance of Path.Rectangle, the angle of the last segment varies depending on the rectangle's height / width ratio.   At anything other than 1:1 ratio, the angle of the last segment seems to be arbitrary.  The problem can be seen here >> 

http://sketch.paperjs.org/#S/VU47DsIwDL1KlIVWraJMCLUwcQEEY5shDe5HTR2UBBiq3h2nG17s9/GzV456AV7xxwzRjLzkxj0T/mjPPJjILgzhy246juJOWONgIWtkyaQqWXOUNJ2kVHndYvKLfrL26qzztHno7BsOpLTYE5Gl0Il4WVM77/kiwLAAxiAs4BBHUooiX1tkVMZhcBaEdUP2Z24mJV5uwij2f9LxjX7vPOh55wOvGrX9AA==

**Comment by arthur-test-account** [comment]
The [angle](http://paperjs.org/reference/point/#angle) property of a point has meaning if you consider the point as a vector. It corresponds to the "The vector's angle in degrees, measured from the x-axis to the vector."

You can see more detailed information on the [vector geometry tutorial](http://paperjs.org/tutorials/geometry/vector-geometry/). In the last example the red arrow is the point, you can see its corresponding angle.

So `segment.point.angle` is not linked with the angles of the geometry described by the segments. You can see that if you place your rectangle further from the origin.

**Comment by lehni** [comment]
@arthur-test-account is correct. This is not a bug.

**Comment by lehni** [comment]
You can get the angle between two subsequent curves by using curve.getTangentAt() and Point#getAngle(point): 

http://sketch.paperjs.org/#S/XZDBTsMwDIZfJcplrVZF5oLoOg4TL4CAW9tDFrw2WnCm1C2Hae+O03FA5JL4/7/fsnPVZL9Q7/T7GdmNutIufuZ6sUkldKyeFeG3erU8mjepLQ0BixYqBX2l2keQ1xNAXzYdZd6cfAgvMcQkyc0xzLgRp6OTCEVu6kWHRq792t+4OS04mYA08Cj6dluqa0dKTsZXWyJ/2Nb3zR1wkaYY0IQ4FKtnBuQPGRGJD1yAAXioFKcZy+wc1tnv4CXh4uM8/U/Udf2bKPNKN/mRY0J7vkRPPOld299+AA==

**Comment by markmanx** [comment]
Thanks for your help guys.
