### ISSUE TITLE
Error returned on default sketch.paperjs.org page  

### ISSUE THREAD

**Issue by bnjm** [paperjs/paper.js#740]
Not a large issue and sorry if this is intended behaviour. It just made me hesitant to start sketching as it seems like something is broken.

The error is cross browser on OSX and is only returned on the first time you visit the page.

![screen shot 2015-07-29 at 12 26 10 pm](https://cloud.githubusercontent.com/assets/1694288/8947290/27f26a58-35ed-11e5-8c83-35b1e2ad762b.png)

**Comment by lehni** [comment]
That's funny, I thought I fixed that already! Will look into it again.

**Comment by lehni** [comment]
it was fixed in 3fa88d4fa78160f0d877501304ba23a44046116c, just not deployed yet. Now it's up!
