### ISSUE TITLE
Uncaught TypeError

### ISSUE THREAD

**Issue by sabrineZhr** [paperjs/paper.js#742]
I'm trying to do a hitTest and it's done. But I have this error : 
Uncaught TypeError: Cannot read property 'x' of null
paper.js:3721 
<img width="454" alt="capture d ecran 2015-08-04 a 10 09 26" src="https://cloud.githubusercontent.com/assets/8748817/9057307/13e01210-3a91-11e5-96fc-7dcef9377e07.png">

does anyone know what does "x" stand for ? 
Thank you.

**Comment by sapics** [comment]
I guess that you need to use newer version of paper.js, because it would be fixed as #30.

**Comment by lehni** [comment]
What version of paper.js do you experience this on? Could you provide a test-case with the shape and the hit-test that causes this issue?

**Comment by sabrineZhr** [comment]
It was a version problem I changed it to the last version and it's ok. Thank you.
