### ISSUE TITLE
SVGImport id attribute of an element

### ISSUE THREAD

**Issue by kaelumania** [paperjs/paper.js#745]
It seems that the svg id attribute is not being parsed/used during import, e.g.:
`<path id="my_curve" d="M200,300 Q400,50 600,300 T1000,300" fill="none" stroke="green" stroke-width="5" />`

Shouldn't it become the name of the Item (see 
https://github.com/paperjs/paper.js/blob/develop/src/svg/SVGImport.js#L395)
the id might need quotation marks.

**Comment by kontur** [comment]
This was self-closed, but I am wondering about exactly this. Is it possible to access the original `id` attribute somehow to identify objects in the imported SVG?
