### ISSUE TITLE
Inconsistent raster positioning on multiple canvas 

### ISSUE THREAD

**Issue by bebensiganteng** [paperjs/paper.js#746]
## Edit
Seems related to this issue https://github.com/paperjs/paper.js/issues/528 , inspecting now

I have several canvases that hold different animations that mostly uses rasters, but when the page first loaded, sometimes the positions of the raster randomly shifted.

### Code
Each canvas has similar classes, such as below
**baseanimation.coffee**

        class BaseAnimation

          canvas: null

          constructor: (@config) ->

            @canvas = @config.canvas
            paper.setup @canvas[0]

            paper.view.onFrame = @render

            if @config.width
              @setCanvas @config.width, @config.height

            @init()

          init: =>

          onCompleted: =>

            @cb?()

          render: (e) =>

          setCanvas: (w, h) =>

            @canvas.attr('width', w)
            @canvas.attr('height', h)

          start: =>

            @tl?.play()

**characteranimation.coffee**

      BaseAnimation = require './baseanimation.coffee'

      module.exports =

        class CharacterAnimation extends BaseAnimation

          time00: 0.4 #0.8
          time01: 1 #2
          time02: 0.5 #1

          constructor: (@config) ->
            super

          init: (obj) =>

            @hash = new paper.Raster @config.hash
            @hash.pivot = @hash.bounds.topLeft

            @mask = new paper.Path()
            @mask.fillColor = "black"
            @mask.add new paper.Point(37,0)
            @mask.add new paper.Point(548,0)
            @mask.add new paper.Point(585,37)
            @mask.add new paper.Point(585,272)
            @mask.add new paper.Point(548,309)
            @mask.add new paper.Point(37,309)
            @mask.add new paper.Point(0,272)
            @mask.add new paper.Point(0,37)
            @mask.closed = true

            group = new paper.Group(@mask, @hash)
            group.clipped = true

            @frame = new paper.Raster @config.frame

            @char = new paper.Raster @config.char
            @char.pivot = @char.bounds.topLeft

            @logo = new paper.Raster @config.logo
            @logo.pivot = @logo.bounds.topLeft

**mainanimation.coffee**
      
      CharacterAnimation    = require './characteranimation.coffee'

      module.exports =

        class MainAnimation extends CharacterAnimation

          constructor: (@config) ->
            super

          init: =>

            super

            @hash.position.x = -370
            @hash.position.y = 0

            @mask.position.x = 300
            @mask.position.y = 200

            @frame.position.x = @config.width * 0.5
            @frame.position.y = @config.height * 0.5

            @char.position.x = 350
            @char.position.y = 9

            @logo.position.x = 360
            @logo.position.y = 40

**Comment by lehni** [comment]
Why was this closed again?

**Comment by bebensiganteng** [comment]
Anyway this is my solution, I've used Modernizr to detect whether canvas is supported or not

	if(Modernizr.canvas) {
		document.write("<script src='/js/eva2/vendor/paper-full.js'><\/script>");
	}

**Comment by lehni** [comment]
I don't think that solution is about this issue?
