### ISSUE TITLE
function naming conflict: extend

### ISSUE THREAD

**Issue by henryj** [paperjs/paper.js#748]
Hi, there's a js lib mootools(http://mootools.net) which I use quite often. But when I put paperjs(core) with it together, it stops paperjs from working. I did some simple debugging and found if I replace all the word 'extend' in paperjs with something else like 'extendobj', it works. 

I know it might be too much to ask you guys changing that word as other people might extend your lib and depend on that function a lot. And it's kinda mootools' fault to make their extend function global but that's what they do and why people use them, so... Interesting thing is other libs I used which also has a similar 'extend' functions works fine with Mootools, i.e. https://github.com/iron-meteor/iron-router

So probably just take this as a notice and see what you can do. I'm pretty happy to change that word as a workaround for myself at the moment. I believe everyone else having the same issue would be happy to do so as well.

Anyway, thanks for the great lib you're making.

**Comment by lehni** [comment]
That's very strange, as everything in paper.js is scoped. Can you put up a simple test case where I can see this failing?

**Comment by henryj** [comment]
Here's the broken one:
http://codepen.io/henryj/pen/BNbZLN

(I've picked the piece of code from Mootools which shows how they break paperjs's scope. lol. You can find it on the top bit marked as 'Function overloading'. And next to it is the paperjs-core and last the standard hello world example from paperjs.)

Also here's the working copy with changing paperjs func name 'extend' to 'extendobj':
http://codepen.io/henryj/pen/waOezK
(everything else is the same.)

**Comment by lehni** [comment]
Oh dear, they appear to do some rather dodgy things there. I shall look into it shortly.
