### ISSUE TITLE
match.overlapping: Rectangle not working as expected

### ISSUE THREAD

**Issue by kaelumania** [paperjs/paper.js#751]
When the target Rectangle completly lies within a Shape, e.g. a Circle, then the Circle is not being returned as match.

```js
new Path.Circle({center: [60, 60], radius: 50, fillColor: 'yellow'});
new Path.Circle({center: [80, 100], radius: 50, fillColor: 'green'});
new Path.Circle({center: [120, 140], radius: 50, fillColor: 'red'});
new Path.Circle({center: [180, 180], radius: 50, fillColor: 'blue'});


var selector = null
function onMouseDrag(event) {
    if(selector)
        selector.remove()
        
    from = Point.min(event.downPoint, event.point)
    to = Point.max(event.downPoint, event.point)

    selector = Path.Rectangle(new Rectangle(from, to))
    selector.bounds.selected = true
    selector.fillColor = '#e9e9ff';
    //selector.strokeColor = 'blue'
    selector.opacity = 0.6;
}

function onMouseUp() {
    project.activeLayer.selected = false;
    if(selector) {
        items = project.getItems({overlapping: selector.bounds})
        for(var i = 0; i < items.length; i++) {
            if(items[i] instanceof PathItem)
                items[i].selected = true
        }
        selector.remove()
        selector = null
    }
}
```

I am missing an intersection match.

**Comment by kaelumania** [comment]
It would also be useful to provide a custom function, e.g.
`project.getItems(function(item) { return whatever(item) })`

**Comment by lehni** [comment]
Note that you can perform the filtering in this way:

        items = project.getItems({
            overlapping: selector.bounds,
            class: Path
        });

**Comment by kaelumania** [comment]
Awesome :+1:

**Comment by kaelumania** [comment]
@lehni the version with `getItems(function() {})` is not working, due to https://github.com/paperjs/paper.js/blob/2366e032653e62f3d1f34fea06af2af36aa1eb86/src/item/Item.js#L1982 which results in `items` not being set and therefore cant be push into https://github.com/paperjs/paper.js/blob/2366e032653e62f3d1f34fea06af2af36aa1eb86/src/item/Item.js#L2026

**Comment by lehni** [comment]
Hmm it seems I am still facing the original issue here, or again. Need to investigate, and will also finally look into the other points raised by you @kaelumania.

**Comment by lehni** [comment]
Reopening again, to fix issue with `getItems(function() {})` described in https://github.com/paperjs/paper.js/issues/751#issuecomment-164696795

**Comment by kaelumania** [comment]
awesome work @lehni
