### ISSUE TITLE
make path.exportSVG export <path> by default, with <polygon> as option override

### ISSUE THREAD

**Issue by Pomax** [paperjs/paper.js#753]
right now path.exportSVG on a line-segment only path will generate a `<polygon>`, but a `<path>` in all other cases. For stable behaviour purposes, it would be better to generate a `<path>` in all instances, with an option `asPolygon` similar to the current `asString`, to force-generate a polygon if possible

**Comment by lehni** [comment]
I propose calling the option `matchPolygons`, similar to `matchShapes`, as it will only export polygons when the geometries match.

**Comment by lehni** [comment]
Actually, it makes sense if `matchShapes` just controls both behaviors. Implementing it right now.
