### ISSUE TITLE
Define boolean operation behavior with open paths

### ISSUE THREAD

**Issue by Pomax** [paperjs/paper.js#757]
The following code has some interesting, and wrong, union behaviour:
```
var c1 = new Path("M 300 60 C 430 60 430 140 300 240 C 165 140 165 60 300 60");
var c2 = new Path("M 300 180 C 430 345 430 480 300 480 C 170 480 170 345 300 180");
var c3 = c1.unite(c2);
c1.strokeColor = 'black';
c2.strokeColor = 'black';
c3.fillColor = 'red';
```
[result](http://jsbin.com/kebusivenu/edit?html,js,output):

![screenshot 81](https://cloud.githubusercontent.com/assets/177243/9345870/542b4a3a-45ca-11e5-860c-8fb3fe9463e1.png)

**Comment by Pomax** [comment]
and right after filing that I notice there are no `z` statements in the sub paths... so that might be a problem.

**Comment by Pomax** [comment]
totally the issue. Closing.

**Comment by lehni** [comment]
Oh, so it was happening because the paths were open? That should be handled differently in the library still, i think?

**Comment by Pomax** [comment]
I guess that depends on whether it should treat paths as closed when it performs the boolean operation. I might make sense to force-close paths if unite/intersection etc. are called

**Comment by lehni** [comment]
Yeah... Or we could define what is supposed to happen, e.g. subtracting a closed path from an open path could split the open path along the intersections and erase the bits that lie outside the closed path. This would actually be very useful for hatching and such, and not hard to implement at all...  intersect would do the opposite of that (keep the bits that are inside the closed path). All other operations, wouldn't be defined and should probably throw an error. The same is true for all operations when performing them with a closed path on the left and an open path on the right hand side.

**Comment by Pomax** [comment]
that would be pretty cool, now that you describe it.

**Comment by lehni** [comment]
Here an example that then should work as described above:

http://sketch.paperjs.org/#S/bZHPbsIwDMZfxcoF0KqKteJSxIkXmMax5RCKV6qmNnLCdkC8+xwy9k/NIZJ/+exPn3M1ZEc0ldkNGNqTyUzLx1i/WwHBNsAGCD/gxYZT/qq1pc7h/NoQ6HkTHiuon5fLDPTaZwkHVliuFBY/0AfhAbfsWCqYCR5nDd0W64Yail6uJ/zl9XDw2I1IwevABOJJhqvv0Ynd/f7BYkJYTAnLCWH5ECY2HeTgLvg3iaDXIDFP3lNA8bq1eVxllOhjfmbfh54JnjZQfy3p3t0yeXaYO+60wS/W+h0HQTucWSd5U9X72yc=

**Comment by Pomax** [comment]
hm, given the result in that sketch, I'm not sure I could explain why it'd look that way.

**Comment by lehni** [comment]
Don't worry that's the old code. Things have improved hugely in the Boolean ops since then. I've just put it here for reference as I'm going to implement the behavior for open paths outlined above.

**Comment by lehni** [comment]
A new release is imminent now. Finally!

**Comment by lehni** [comment]
I've updated the linked example above. With the latest commits in place, here is how the result now looks:

<img width="310" alt="screen shot 2015-10-24 at 22 45 32" src="https://cloud.githubusercontent.com/assets/213275/10712665/f7ac81fa-7aa0-11e5-963f-80749faa9dae.png">

**Comment by techninja** [comment]
Incredible work guys! Wahoo!
## :exclamation: :fireworks: :cake: :boom: :open_mouth: :astonished: :exclamation:

**Comment by Pomax** [comment]
aha! The above link still shows a slightly different capping for me, which could be because of the specific paper.js it's referencing?

![screenshot 23](https://cloud.githubusercontent.com/assets/177243/10734916/cba91a46-7bc2-11e5-804d-74da777ff61c.png)

**Comment by lehni** [comment]
That's because Sketch is still running the old version of the library. I need to update it!

**Comment by lehni** [comment]
Try again now, with force refresh!

**Comment by techninja** [comment]
Force refresh was the ticket for me, works great!

**Comment by Pomax** [comment]
That's pretty sweet @lehni =)

**Comment by lehni** [comment]
Please note that in order to get this open path / stroke-based behavior, you now need to call it like this:
```js
    var res = line.intersect(rect, { stroke: true });
```
