### ISSUE TITLE
Import SVG without adding it to the canvas.

### ISSUE THREAD

**Issue by kaelumania** [paperjs/paper.js#763]
Is it possible to load an svg via URL without adding it to the canvas? I need to load a bunch of SVGs and do not want to pollute/flicker the canvas.

**Comment by iconexperience** [comment]
@kaelumania I do not think loading an SVG without adding it to the canvas is possible at the moment. But as a workaround you could create a second project with an offscreen canvas, which will prevent your canvas from flickering when loading the SVGs. After loading you could copy the items from the offscreen project to your original project.

**Comment by lehni** [comment]
You can use an onLoad handler to remove the item from the DOM as soon as it's loaded. But we should offer an option to not insert it.

    project.importSVG(file, function(item) {
        item.remove();
    });

Or:

    project.importSVG(file, {
        onLoad: function(item) {
            item.remove();
        }
    });

**Comment by lehni** [comment]
We should also add this option to `importJSON()`
