### ISSUE TITLE
exportJSON then importJSON on a Group results in MAXIMUM CALLSTACK EXCEEDED

### ISSUE THREAD

**Issue by kaelumania** [paperjs/paper.js#764]
```js
var exported = item.exportJSON()
item = new Group().importJSON(exported)
```
where item is a loaded SVG

***UPDATE***
When I use the following Snippet:

```
this.item = paper.project.importJSON(memento.item)
```
no callstack is exeeded.

**Comment by lehni** [comment]
Yeah it's supposed to be called on Project... But I'll investigate the endless recursive loop.

**Comment by namwkim** [comment]
I recently observed the same problem.I am exporting a group and importing the group back (to revert an action or so).  In my case,  the problem seems to happen when a group has more than one-level hierarchy(e.g. a group has child groups).
