### ISSUE TITLE
Layer bounds sets itself to children bounds

### ISSUE THREAD

**Issue by kaelumania** [paperjs/paper.js#767]
I have a Layer and want its bounds to be exactly equal to paper.view.viewSize. But when I add items to the layer it resets its bounds to the items bounds. I try to resize all items in that layer according to the changing size of the canvas.

**Comment by lehni** [comment]
That's normal. The `bounds` property represents the bounds of the actual content, so whenever you add something, it will change. I am not sure I understand what you are trying to achieve though, perhaps you could illustrate it with a simple example on http://sketch.paperjs.org/?

**Comment by kaelumania** [comment]
Alright, I am looking for a simple solution to rescale the whole content (items) of a layer whenever the canvas is being resized. Currently, I am saving the last bounds of the View and whenever the size changes I calculate the ratio and scale the layer with pivot Point(0,0).

**Comment by lehni** [comment]
You could set `layer.applyMatrix = false;` and then simply set the bounds in the `view.onResize()` handler.

**Comment by kaelumania** [comment]
Thanks, I think I tried that already. But my current solution works good for now. Thanks very much.
