### ISSUE TITLE
Allow to select bounding box independent from path item

### ISSUE THREAD

**Issue by kaelumania** [paperjs/paper.js#769]
Is it possible to select only the bounding box and not the path itsself. It seems setting `item.bounds.selected = true` select all path segments etc. (as also stated in the documentation). 

Or what is the best solution to draw a custom selection rectangle? With custom handles etc.

**Comment by lehni** [comment]
That sounds like a bug, actually!

**Comment by kaelumania** [comment]
@lehni Okay thanks. Do you have any recommendations regarding my second question? Whats the best strategy to draw a custom 'selector' for each item?

**Comment by kaelumania** [comment]
@lehni Here is a snippet:

```js
svg = project.importSVG(
        '<svg width="400" height="200" viewBox="0 0 1200 600" xmlns="http://www.w3.org/2000/svg" version="1.1"> ' +
        '<title>Example quad01 - quadratic Bézier commands in path data</title>' +
        '<desc>Picture showing a "Q" a "T" command, along with annotations showing the control points and end points</desc>' +
        '<path id="my_curve" d="M200,300 Q400,50 600,300 T1000,300" fill="none" stroke="green" stroke-width="5" />' +
        '<rect id="my_rect" x="1" y="1" width="1198" height="598" fill="none" stroke="blue" stroke-width="2" />' + 
        '</svg>'
)

svg.bounds.selected = true
```

**Comment by lehni** [comment]
There is `paper.settings.handleSize` that you can use to control the handle size:

http://paperjs.org/reference/paperscope/#settings

And the possibility to customize selection style was already requested here #433

**Comment by kaelumania** [comment]
@lehni Thanks. About the issue setting bounds/path selection independently: I had a look at the source code and found the `drawHandles` and `drawSegments` methods. Should I investigate further to find the bug? Or have you already found the source and have an idea how to fix it?

**Comment by kaelumania** [comment]
I think here is the source of the issue:
https://github.com/paperjs/paper.js/blob/4e2fba660df6b3d2a5fa89ef836d85bfea86d513/src/basic/Rectangle.js#L918

I need this feature to only set the bounds of an item (svg item) to be selected.

**Comment by lehni** [comment]
Yes I have a pretty clear picture what's off, but the code needs some changing to separate selection of items from selection of bounds. I haven't had the time yet to look into it next to all the other ongoing issues...

**Comment by lehni** [comment]
@kaelumania this required quite a bit of refactoring to implement properly. Please test and let me know how it works for you!
