### ISSUE TITLE
does not install on nodejs 4

### ISSUE THREAD

**Issue by mogadanez** [paperjs/paper.js#772]
can't install on new nodejs 4 stable

**Comment by mogadanez** [comment]
due to jsdmo and canvas
see https://github.com/Automattic/node-canvas/issues/621

**Comment by sapics** [comment]
@mogadanez I don't have a nodejs4, so following solution has not checked yet, sorry.

For jsdom, i guess that we need to fix package.json as
```diff
- "jsdom": "~3.1.2"
+ "jsdom": "~6.3.0"
```
And `npm install --no-optional` would skip canvas.

**Comment by mogadanez** [comment]
Paper is not able to work without Canvas, seems it is optional because not required for browser version of paper

**Comment by lehni** [comment]
I will check right now!

**Comment by lehni** [comment]
I guess we need to wait until `node-canvas` is fixed for v4.0.0... I'll adjust the node version requirement accordingly for now.

**Comment by lehni** [comment]
Forgot to mention this issue in commit 608a1c088323533562c1380aa4e2bbf8906b652e

**Comment by lehni** [comment]
There is good progress being made over here: https://github.com/Automattic/node-canvas/pull/622

**Comment by jardakotesovec** [comment]
Awesome. @lehni Can we expect paper.js new release sometime soon? :-)

**Comment by lehni** [comment]
@jardakotesovec yes that merits a release indeed! Will work on it tomorrow.

**Comment by mogadanez** [comment]
any news on new package release?

**Comment by lehni** [comment]
v0.9.25 is finally released!
