### ISSUE TITLE
Assumptions for Self Intersections of Curves are not fully reliable

### ISSUE THREAD

**Issue by iconexperience** [paperjs/paper.js#773]
When checking for self intersection of a curve, the algorithm currently follows these steps:

1. Check if the handles or negative handles of the curve intersect. It is assumed that curves can only self-intersect if this condition is fulfilled.
2. Split the curve at <code>t=0.5</code> and check if the two curve parts intersect. A curve that self intersects always forms a loop, and the point at <code>t=0.5</code> is assumed to always lie within the loop.

This works for the vast majority (maybe more than 99.9%) of all curves. But there are actually cases, where both assumptions are not true.

<a href="http://sketch.paperjs.org/#S/lZNNb6MwEIb/isUpkVjH30CqHlY5rbSHSj2GHFyYAgoxlXFSrar+9x1MqqRptdJayMB8vY9n4C1x9gDJOnncQ6jaJE2qoZ7eVysytsMrqY7+BClprat7GFcOGhu6E3wYUoJ3ElogL0PnArGBhHtGdelWq5P15MWGltwTB6/kAR8XbyM0B3BhXG+3POMpkbpICYsXL6g0JjeyYFoKrSSaOKeK5SJXTEQf36Vkq4xOiTJZSn7IXOCulJmL7Hbvy7vS/a+y1IJKVlwW1udCUK7ZZRVRWhiqZa4Mn3fUVbmk2uRMZVJmIsv5hCVprgQGM6k1E0Vh4vFEzgrkVlobPmncIMdeI/OETp87P4bNZEHvbDn2/Z9H6KEKUGNY8Ec4Zx66GqdxdVy66XzVw+KmFG0gPEyD+hkWOKU01limREwIcxGM7vvN0A8ey5XJwTbYNFsmZ6Xz3Pm11u/OwSLC0/gVcDoen4K3VThb5ySOQp+ibF3fBEwYHwp0DH7YwwWl8QAugpxDxL8gxPcQ4jOE+AIhriHEFwgPdUQoXTW4ccB+9UMztxl7+8sF8CMOqEPnwuHAlrQH14R2GXNKh3/Ykwe7j+pjst4mXCW7978=">Here is an example.</a>

![image](https://cloud.githubusercontent.com/assets/2122773/9787255/75283dca-57c1-11e5-8f22-1b3ccc11643a.png)

As you can see there is a small loop, but the handles do not intersect and the magenta colored point at <code>t=0.5</code> is far outside of the loop.

*Note that this issue is currently merely for documentation purpose. I do not think that it causes problems in real world applications, but finally to have a perfect algorithm, this issue should be worked on.*

**Comment by lehni** [comment]
That's really useful, thanks! I'd like to get this fixed either way.

**Comment by iconexperience** [comment]
Here is an approach for a replacement of the `t=0.5` assumption.

I noticed that for self intersecting curves, if you calculate the *velocity extrema* (thanks to @kuribas for clarification on this), one of these points always lies inside the loop. A cubic curve can have zero to three of these extrema and it seems that in cases when the `t=0.5`assumption fails, there is only one extremum, which will be inside the loop. We can use this to find the best point for splitting the curve.

1. Calculate *velocity extrema*
2. If there is no extremum, there is no self intersection
3. If there is only one extremum, split curve at the extremum and check if curve parts intersect
4. If there are more than one extrema, split the curve at  t=0.5 and check if curve parts intersect

Unfortunately this approach is slower than the current, not fully reliable approach. Also, I cannot prove that this will cover all cases.

Please use <a href="http://sketch.paperjs.org/#S/lVZLc9s2EP4rOzrEVCwxfEmW5DidjpNDD20zTaYXWQeKhCxMIIBDgrIxjv97Fw9SpBk5Df0Qtfvttw/sAnga8fRARqvRl29EZvvRZJSJXH8/piUUqdzDDXDyAJ/x1XuqyP2BcFmt1uvwKpxAPFtOIDC/8Szy42B5emYTCKPID2fB6VluJrBOork/ixfJPLT/5xNIFrE/my+C5CqOr6KrBVJP49hfJBGCg3g2C6LlEnHh0o8WwTKZXyWz2TzUPrT3zeZ5fH3HdchZXR4JxqxD93e0rOStlqDWSmrG1BfCSCZJjjBZ1lpnbYugk6x/S8uMEe+pTHNaVyuIJrCjjN0KJsoVXJQkv2i9FuEvWN6XhPCObfQLtoowJh6s8R3Py/ThX8JERqX69ChLckiRa1fzTFLBvTE83XHA5907ODoYEIdLSwJyT6AQFBcUHvbECUzRICclPaaSYjHFzshNZVs+WkFByoLwnGY1wzSkAIo8FckEzzvm1kIn+qiLZFh84zT0H6872mighUsn2Kc8Z+QFPu7jowE+6uOTAb6jVYPYVFc7iE0NYuvhB7G9xEd9/CA2Zda30aePqJ9i/S4hhre6VFP7EqPkMekwbTXSqELEzC3YWcUdXGYYHbBh7ehTpfWq0anGo9IeVc+jch5V41E1HlXPo2o8dlh7WZZCYAPdwHpz3RfeippLM9PYcv5f9QGbK0uZXwl2JLf1lmbeEuk8LNNbXatLHT6+qfEEToqtVmxbRaQV275iq8YuNC9rubLWxApP8EwLTdRjF3E7HoTRA+WpJJAy5jITtaxoTiCA9yDxLwRsBTNaB5pjTxgYUA5ZWplRxIG0U4obhuXwrYOdKMHT1aFYlVOFphBeo+jDDQT4OZ22868fugPPcKzpBt4jBL5/h1aANmEPrh/rshCF1+TX1Rif02lH82xf3UcRoGlF9U7Ui/IDuv7Ndfs9kZ91w/8uXWwBHhB6Tx7DCjju1Y69CM9xhee5wjNc0Tmu6DxXNOR6Ns1r93ApBHO7+Fd89Zq93Q67++IOT2OmDXzB/xR1RT6KB97dtskRUe1iWApNfkrBMfWF2HUfBaSwpxIkwS0c8zMHuO4Wy1KtToOFsH9IVTPZHJYo+Ipm1r3dhybw1Fqa9LEIgpEy5RlZQQLPTV/o5moJB23XanypCkzlBi4s65TyC3jz5hSL32Y2OMEbVTRo07ZCAxq32f7Bu02Ks4nj9XpcOKq/HNhwfn4a2N+1PDs+JkBHYNe5x/9/l6+9sb26fq+vYb/lBsn8MIVmOnqNXqb35xv9lHA/USPSh/sN2NxywmTant4djHqJac7YTkldzD0XzaKYor3uqQ/9mcMf3M/M1qCLA2cucN7YVc7+4IV8W5L0m72mjVbrUZiMNs//AQ==">this Sketch</a> to see the velocity extrema in action.

**Comment by lehni** [comment]
Great, thanks! Before checking for self-intersection, we have another check in place that looks at the handles to avoid curves that cannot have self-intersections based on their handle configuration. How many false positives does this check give us for curves that are checked for self-intersections and don't have any? If it's not many, then I don't think it's an issue that this approach is slower. Also, how can it be faster than what we currently have? That's pretty much impossible : )

**Comment by lehni** [comment]
BTW: Instead of filtering out the roots that are out of bounds, why don't you include the `min, max`  arguments to `Numerical.solveCubic()` to not include them in the first place?

**Comment by iconexperience** [comment]
Because I think it is relevant to know how many roots there are, even for t < 0 and t > 1. But I am not entirely sure about this. The whole approach is a bit shaky at the moment, but it may turn out to be an easy solution.

**Comment by iconexperience** [comment]
The problem is, that the first check is not entirely reliable (see first post), so we cannot use it to cover all cases. Also for the current implementation the false positives are quite a few, including many normal curves like this one (handles intersect, curve is far from self intersecting):
![image](https://cloud.githubusercontent.com/assets/2122773/9811639/bdc50d58-5878-11e5-90ac-1d3f6f977ab6.png)
If we find a better (tighter) first check which covers all cases, the performance of the new approach would not be an issue anymore. And I am pretty sure such a check exists, we just have to find it :smile:

**Comment by iconexperience** [comment]
I read somewhere that one condition for a self intersection is that the curve must have a horizontal and a vertical tangent. I do not know if this approach helpful, but just want to add it to the collection of ideas for preconditions of a self intersection.

**Comment by lehni** [comment]
Well, you're not doing anything with the number of roots found before the filtering, so I guess we might as well filter them straight ahead : )
So what you used to call a 'peak' in the offestting code is actually a velocity extreme, as pointed out by @kuribas. This sounds like a useful method to have on Curve, so it can be shared by both modules later.

**Comment by lehni** [comment]
Speaking of your offsetting code, the getTangentT() method might be of use to find these horizontal and vertical tangents? The problem right now is that it does not handle vertical tangents, due to a devision by vTan.x == 0. In that case, we'd have to solve for y instead of x I guess...

**Comment by lehni** [comment]
This version should be fine, I think:

http://sketch.paperjs.org/#S/lVbbbts4EP2VgR8auVFUiZJ8hXdRuHlYYLct2mBfHD/IEm0LVURDohwThv99h6SuUZxulMCgZs6cuXA41HmQBk90MBv8/EV5uB+Yg5BF8v0YZHAI+B4WkNJn+I5L45zT3RNNeT5brZyxY4LrT02w1b/rE8u1p83jm+AQYjm+3TzTtQkrj4ws3514I0f/jkzwJq7ljya2N3bdMRlPkPrOda2JRxBsu75vk+kUcc7UIhN76o3Gnu+PHOlDel+vL8P5YypDDovsSDFmGbq1jbOcL6UEtVpSJIn4SRMachohjGeF1Gnbg91K1lrGWZhQ45wFUVzkMyAmbOMkWbKEZTO4yWh0U3s9OO+w3GWUpi1b8g5blgXpjmrjx3RbpCGPWQpRFjz/SxMWxlzcn3hGnwJjCOfHFPD59AmOpQ6oVkKQUeB7CgcW43bC856WAlUyiGgWHwMeYynZVslVXWu+OIcDzQ40jeKwSDAJziBGnpyGLI1a5tpCpnmSJVIslnLqWKd5S0t6WrgtBfsgjRL6Au928aSHJ12818O3tKIXm2hre7GJXmwdfC+2l3jSxfdiE2p3K31wQv0d1u8WXPgoS3WnFy5KTl6LaSORSuUgZqTBpZXbwoWKsQRWrC19IKReVDpReRTSo+h4FKVHUXkUlUfR8Sgqjy3WTpYZY9hAC1itW2acJRQ7PpQn+mvxhG0VBon18O3v+x+fvy7v513zJStSrs4+NqfV4HOWHOmy2MShoQ2qZ4phGFjej7LGtzJtXImheQ21kajN6ygiUZsuaiOGZbJGWHsJX7fXiMY2RIQuitmUAScglrl+Hc7lYaSnMCkiKiehozn178HGfspjNSAWrQL9ATb8WTbcjvLvsuc+c0P5Wtk4oeVQHMIMUhyWZYkPzjUu5zqXc4WLXOMi17lIn+ui+kcPUc5YUo7RB1wa1XDV5618KW8vZSYNLJb+w4qcfmHPMpJqmhr0iKh6fGoKSd6kUDJ1hbgVXxgEsI85cIpTFPNTN+iWVYHks6ZjEfaD5kXCq9sKBQ9opt3rUWDCubZU6bd6YQYeqHtAEsZbMGrCOvSexuLigKks4Eaz3sXpDXz40MRi1Zn1rtBKRTr0nQr1aMp591c6bywuQJOc/iYuVvB3B+a8P7BvBW9HppeXVklLAr3PHf7/u331J9Ob+/f2HnZbrpfMqylUp6PT6Fmwu97oTcLdRJVI3q8L0LlFNOFBfYG2MOIlprrmWiUtY+64qDZFFe1tT13o7xy++l1Ujg6Q1bkGaP7wi3iT0eCX/lIazFbry38=

**Comment by iconexperience** [comment]
There is a very simple way to check if vertical or horizontal tangents exist. In the </code>Curve.evaluate()</code> function the tangent is calculated as
<pre>
x = (3 * ax * t + 2 * bx) * t + cx;
y = (3 * ay * t + 2 * by) * t + cy;
</pre>

We want to know if x and y can be zero. For `x=0` we get

`0 = 3*ax*t^2 + 2*bx*t + cx`

We can either calculate the roots and see if there are any for 0<t<1 or even take a shortcut and simply check if 

`4*bx*bx >= 12*ax*cx`

which is the condition for existance of real roots. Here is the function.

<pre>
var checkCurveIntersectionPossible = function(curve) {
    var v = curve.getValues();
    var p1x = v[0], p1y = v[1],
        c1x = v[2], c1y = v[3],
        c2x = v[4], c2y = v[5],
        p2x = v[6], p2y = v[7];
    
    var cx = 3 * (c1x - p1x),
        bx = 3 * (c2x - c1x) - cx,
        ax = p2x - p1x - cx - bx,
        cy = 3 * (c1y - p1y),
        by = 3 * (c2y - c1y) - cy,
        ay = p2y - p1y - cy - by;
       
    return (4*bx*bx >= 12*ax*cx) && (4*by*by >= 12*ay*cy);    
}

</pre>


And <a href="http://sketch.paperjs.org/#S/lVVLc5swEP4rOxwS2yUEBPg5bg/JJYdOM02mF9sHjOXHhAgPCMcaD/+9qwcG6jZpZAYL7bf77a4+wcli0Su1xtbTC+Xx1rKtOF3J50OUwT7iW5gCo2/wiNPOKaebV8p4Pp7NvIFngx+ObHDV5YfE8d1RPUIbPEIcL3TrMVrYMAtI3wn9YdD39L1vQzD0nbA/dIOB7w/IYIihb3zfGQYEwa4fhi4ZjRDnjRwydEdBfxCEYd+THJJ9sSi7kzmTKcdFdqCYs0zdWe+ynN/JFbTqlSJJxBNNaMzpCmE8K6TN+G5p/KLgD4zTLEfQLmWPaZ7vlokMui6YWuooli6c5gxwSN8DmtWqs6H8V5QUNO/InCr73jsi4jBzsQN7T6i5t7A1QI7YAAgCYgPwWwCiAYEEEA0Im4C9AfQlhQEMFiaHOpNYonzoQUdS3sjMuo0oy9pMpBlBXfl3bGAiidkT462seFs2IbGoWYTCiRZLbSZCsQjFIposQrEYb2WVLKJVUT3LKC8yBp2gtzziBV+nqL9edOzFWMDVlTIIvCqD6MWie45VShFoGfA0TYzqn3HaqaS1jdgqoebBnASlHengpOx7WuT0Pn1jTaXQA6LOStEhZHDUoeE2kdqLt7dwn0IE2x0HTnMOKdOncZ1WieTjek8R9pPmRcIr5ePCM7ppemef7hi34XT2VLq3sdKEZhGL6RgCKKtm7NbQOQc8p35hcbjYYylTuNZRb3bsWva5BpwruziOlYm0wrc6dBHG0aYHNqk9SqBJTj/IKy34pxPzPp/Yj4I3M9PTstFSE0Dvcyv+/27f+fX77v69v4dtyV0U89cSyok+HS2hZ9Hm30KvC24XqpacI3yZgq5tRRMeOcfJBUb8ianOfaOlJucWRbUpqmnvM7WhHxAaoSTJXZrgGZx+8LWoPhHfYG5tMkrZ3IIxzjO6mlsT3VLQXZU//O4uMxq9qFRyazxblL8B">here it is in action</a> (drag handles, green means self intersection possible). Unfortunately there are many false positives, but it could be combined with another simple condition.

**Comment by iconexperience** [comment]
Sorry, I was wrong. If t=0.5 is outside the loop, there can be several extrema:

![image](https://cloud.githubusercontent.com/assets/2122773/9813202/e34f9312-5883-11e5-8e58-c05303eaaea4.png)

Magenta is the location at t=0.5, the others are velocity extrema. Aaargh.

**Comment by kuribas** [comment]
You can test if the derivative goes through more than 180 degrees, which is required for a loop.  It may give false positives though.

**Comment by kuribas** [comment]
For example test if the origin is inside the convex hull of the hodograph (derivative curve).

**Comment by kuribas** [comment]
There is a formula for determining when a cubic has a loop here, though I don't really understand all the math behind it: http://www.msr-waypoint.net/en-us/um/people/cloop/LoopBlinn05.pdf

**Comment by kuribas** [comment]
Then split where the tangent is halfway, which can be found by solving a quadratic equation.

**Comment by lehni** [comment]
@iconexperience If there are more than one extrema, take the middle one?

**Comment by iconexperience** [comment]
@lehni Unfortunately the middle one can be outside of the loop. We should really find a fast first condition (or two conditions) that will filter out as many negatives as possible. Then we should be able to find the correct one of the two or three extrema and split there. With @kuribas suggestions above we should be able to find a solution. But first I want to tackle #777

**Comment by lehni** [comment]
And here [a version](http://sketch.paperjs.org/#S/lVZbj9o4FP4rRzx0QiekuRCumq4qOg+VdtuqHe0Lw0MIBrL12ChxmIkQ/32P7SROhks7AaHE/s73nZtPOHRY9EQ6k87PX0TE247diflKPu+jFHaR2MIdMPIM3/HWOmRk80SYyCbzuTf0bAjCsQ2u+gah7wTu2FyhDZ7vO17ommu8sGHe9wdOGIz6A0//DmzojwInHIzc/jAIhv5whNS9IHBGfR/BbhCGrj8eI84bO/7IHfcHw34YDjypIdUXi2N3+siky3Ge7gn6LF131kmaiZlcwV29klNa/CSUxIKsECbSXO5p253bCNaZJWlMiXVIo1WSZxPwbVgnlM445ekEblKyuqlVd94bLDcpIaxh67/BlqcR2xBt/MhUaM6GiH8J5XEiivsXkZKnCAnXOYtFwpm178LhkQFe2tEX3NzPXSzEzivUvbewNUBecQnwERCXgKAF8DWgLwG+BoRNwK4EDKRECRhKgIFEEhHAe7CkXE9yduFWWfakiw22ZQ2Vrt9qaA8GuBK3gPErToR326KFARRKtNCihUIXTdHCiBZKtDCiTWD8ihPhbVHBKcGSxbIlv+ZPJE3iiDoP3/6+//Hp6+y+QZVyLjJEzRdTvWjgGad7MsuXSWwZvLzGUhmT+V5m9FZGiHfKg/OopUQtz6N8iVq2UUuVIR1frRKft9cIYxsjQgdlmyzgCcYs1Y/dKXz4AOQlpvmKyJPsac6UiDxl2hqzcTS9nrD/8OhaZUefdv7ENH7d9w3GSwfGEtskU+sRzUlmdbtlEVD62JXyFS2s0uj5tXXriFWFjC9pVdw719nxLFGsd9rMoYRtcOZ+BBf+MgzfecLEJ2EpjDq7cm51YQIM51lF512h8y7TeRfo/Ct0/mU6/5TuqIaVnnaCc1rOuwe8taopuI3YipLyoXzNKDNp4HD2D88z8pk/s+ZsI3tE1cnXFJLcRFEytRex5z5ziGCbCBAkE4AhqlfdmleOZBNTUIT9IFlORfVawYUHNNPymCUM34ZDbanCbzT9BPpwrIqerMGqCVst2tpxRLHDUO7gRrP2EnYD794ZX5w6spN3XbXlt+hbGTqhcfTWFzY1FkcgNCO/8Yvn4s2OeW937Fsump7Vh7NOXEmg69zi/9Py1f9trtbveg3bLXcSzNkQqtPRavQ02lxudBNwO1C15OAEvgMd24pQETkv0xNM8RpTTE9SWvrckqiKopJ2XakN/Z3g2alajg6Q2bkEMB/867pMSfRLCWadyXxx/B8=) that can be integrated into the library.

**Comment by iconexperience** [comment]
There has been a lot of progress and a possible solution in the comments to issue #788

**Comment by iconexperience** [comment]
@lehni
I think fixing this issue should also include a little bit of refactoring. Just like `PathItem`, the way to find a self intersection of a curve should be `mycurve.getIntersections(null)`. All the code for finding the self intersection, including the condition if a self intersection can exist, should be moved to `Curve.js`. This would make things cleaner, easier to read and there would be an API for getting a self intersection of a curve at no extra cost. What do you think?

**Comment by iconexperience** [comment]
@lehni
Please wait with implementing the solution for this issue. I am currently writing a summary and explanations of the findings. Also, I have found that performance can be improved because the check for inflection points is done too often.

**Comment by iconexperience** [comment]
### Summary and Explanation of the Fix for this Issue

Our algorithm for finding self intersections has four steps:

1. Apply a simple and fast condition to check if a curve can possibly have a self intersection. This condition must not produce any false negatives and the number of false positives should be as low as possible.
2. Find a point that, if the curve has a self intersection, is guaranteed to lie on the loop.
3. Split the curve at the point found in 2.
4. Locate the intersection between the two part of the split curve. If there is no intersection between the two curve parts, the curve has no self intersection.

Steps 3 and 4 work well in the original implementation, but for step 1 and 2 the assumtions were not fully reliable

### Condition for self intersection

It turned out that the original condition for determining whether a curve can have a self intersections produced false negatives. Therefore another condition needed to be found.

In issue #788 we found by observation that the sign of a curve's edge sum changes its sign when a self intersection appears and the handles are on the same side of the line that goes through the curve's end points. Using this behaviour can be a very simple and fast test for a possible self intersection, but it covers only the cases when both handles are on the same side.

If the handles are on opposite sides, we can use the fact that a cubic bezier curve with a self intersection never has an inflection point (see http://pomax.github.io/bezierinfo/#canonical for more information). This still leaves a certain numbers of false positives (curves that have handles on opposite sides, have no inflection points, but also have no self intersections), but these cases are rare in real world scenarios. 

This leads us to the following algorithm for deciding whether a curve can have a self intersection:

<pre>
if (handles are on same side) {
  if ((handles are on left side && edgeSum < zero)) or (handles are on right side && edgeSum > zero)) {
    curve has self intersection
  } else {
    curve has no self intersection
  }
} else { // handles are on opposite sides
  if (curve has no inflection points) {
    curve can have self intersection
  } else {
    curve has no self intersection
  }
}
</pre>

### Testing for inflection points

The inflection points of a curve are found where the cross product between the first and is zero, or in other words, where the acceleration and velocity have the same direction. The following is taken from Adrian Colomitchi's great website (http://www.caffeineowl.com/graphics/2d/vectorial/cubic-inflexion.html) on bezier curves.

The cubic bezier curve through points `P1`, `P1` with control points `C1`, `C2` can be written as

<pre>P = (1-t)^3*P1 + 3*(1-t)^2*t*C1 + 3*(1-t)*t^2*C2 + t^3*P2</pre>

The first and second derivatives can be written as

<pre>
P' = 3*t^2*(P2-3*C2+3*C1-P1) + 6*t*(C2-2*C1+P1) + 3*(C1-P1)
P" = 6*t*(P2-3*C2+3*C1-P1) + 6*(C2-2*C1+P1)
</pre>

This is simplified by introducing the following terms:

<pre>
a = P2 - 3*C2 + 3*C1 - P1`
b = C2 - 2*C1 + P1
c = C1 - P1
</pre>

<pre>
P' = 3*(a*t^2 + 2*b*t + c)
P" = 6*(a*t + b)
</pre>

Using this simplification the cross product between the first and second derivative looks like this:
<pre>
P'×P" = 18*(ax*t^2 + 2*bx*t + cx)*(ay*t + by) - 18*(ay*t^2 + 2*by*t + cy)*(ax*t + bx)
      = 18*(ax*ay*t^3 + ax*by*t^2 + 2*ay*bx*t^2 + 2*bx*by*t + ay*cx*t + by*cx 
            - ax*ay*t^3 - ay*bx*t^2 - 2*ax*by*t^2 - 2*bx*by*t - ax*cy*t - bx*cy)
      = 18*((ay*bx-ax*by)t^2 + (ay*cx - ay*cy)*t + by*cx - bx*cy)
</pre>

The inflection points are found by calculating the roots of the quadratic equation above. But we only need to know if inflection points exist, which makes things a bit easier.

A quadratic equation with `A*x^2 + Bx + C` has at least one real root if the discriminant `B^2-4*A*C` is non-negative. Here the terms are `A = ay*bx-ax*by`, `B = ay*cx-ax*cy`, `C = by*cx-bx*cy`;
        
This leads to the following condition for the existance of one or two inflection points:
        
<pre>(ay*cx-ax*cy)^2 - 4*(ay*bx-ax*by)*(by*cx-bx*cy) >= 0</pre>


### Finding a split point that is guaranteed to lie within the loop

In the original algorithm the point at `t=0.5` was always used to split the curve. This worked for the vast majority of curves, but we found cases where the point was outside the loop.

We found by observation that whenever a curve has a self intersection, one of the velocity extrema of the curve always lies within the loop. Further investigation showed that the extremum, where the curvature has the highest value, always lies within the loop. We have no mathematical proof yet, but extensive testing indicates that this is always the case, even for very small loops.

The extrema of the curvature occur where the first and second derivative of the curve are perpendicular. This can be calculated by finding the roots of the dot product between the first and second derivatives.

Again, we use the approach by Adrian Colomitchi (http://www.caffeineowl.com/graphics/2d/vectorial/cubic-inflexion.html) and our simplification from above, but this time we calculate the dot product.

The simplified first and second derivatives are:
<pre>
P' = 3*(a*t^2 + 2*b*t + c)
P" = 6*(a*t + b) 
</pre>

The dot product between the first and second derivative looks like this:

<pre>P'•P" = 3*(ax*t^2 + 2*bx*t + cx) * 6*(ax*t+bx) + 3*(ay*t^2 + 2*by*t + cy) * 6*(ay*t+by)
      = 18*(ax^2*t^3 + ax*bx*t^2 + 2*ax*bx*t^2 + 2*bx*bx*t + ax*cx*t + bx*cx) 
         + 18*(ay^2*t^3 + ay*by*t^2 + ay*cy*t + 2*ay*by^2*t + by*cy)
      = 18*((ax*ax  + ay*ay)*t^3 + 3*(ax*bx + ay*by)*t^2 + (2*bx*bx+2*by*by+ax*cx+ay*cy)*t + (bx*cx+by*cy))</pre>     

In order to find the velocity extrema, we need to find the roots of the cubic term

<pre>
(ax*ax  + ay*ay)*t^3 + 3*(ax*bx + ay*by)*t^2 + (2*bx*bx+2*by*by+ax*cx+ay*cy)*t + (bx*cx+by*cy)</pre>

There can be up to three roots. If more than one root exist, we use `Curve.getCurvature()` to calculate the curvature of each extremum and select the one with the highest curvature.

### Performance

Applying the new condition is probably a little bit slower than the original condition, but the new condition is tighter, which means it results in fewer false positives. This means that we can stop looking for a self intersection earlier in many cases, which should compensate for the slightly higher effort needed to apply the new condition.

Finding the split point is now certainly slower than in the original algorithm, but this should not be a problem because the new condition for a self intersection filters out the vast majority of curves with no self intersection and self intersections on a curve seem to be quite rare in a real world scenario. The calculation the split point will only be necessary in very few cases, hence the performance impact should be negligible.

All in all performance should not suffer by implementing the proposed fix.

**Comment by lehni** [comment]
@iconexperience thank you for the impressive work on this, and taking the time to do such a detailed write-down! It's moments like these that make me really happy to be working on open-source software. :smile: I shall implement this new approach in the coming days! :+1: :+1: :+1:

**Comment by iconexperience** [comment]
@lehni I had the feeling that the solution is very good, but difficult to understand with the provided information. So I decided it would be worth taking some time and write a summary that we can link to from the code.

For this issue I will either write a new implementation of the solution and post it here or directly create a pull request. Maybe you can first look at the other boolean-related issues and see if anything can be closed. I am a bit surprised that we still have so many issues open, while I can hardly find any test cases that fail :-)

**Comment by lehni** [comment]
Yes that's the case for sure! The reason is that I'm still busy traveling, in Mexico City right now, back in the office in a week : ) But I also don't have this fix here in place yet, so I am getting more failing tests than you probably.

**Comment by iconexperience** [comment]
Just take your time, I am in no hurry at all. If we have a working boolean implementation by the end of the year, it would be great. I just kept posting examples and ideas because I could feel that you were *in the zone*.

**Comment by lehni** [comment]
I'd like to get there earlier, if possible. Until when do you think you'll have the PR ready for this issue?

**Comment by iconexperience** [comment]
@lehni Thanks for merging. The change suggested in #784 is now the only difference between my codebase and the current boolean-fix branch. There are one or two glitches remaining, but I have to work really hard to provoke them.

**Comment by lehni** [comment]
I have just committed that change in #784. Now cleaning up code a bit. Which are the remaining glitches again?

**Comment by iconexperience** [comment]
One remaining glitch is Example 10 in #784.

**Comment by lehni** [comment]
Check the commit message in 12311535533a700cfd620f0531f7002e183e39a0 for some explanations of the clean-ups.

**Comment by lehni** [comment]
One question: 

You write if there is no inflection point, the curve *may* have a self-intersection, and then we search for velocity extrema as potential split points. Could `rootCount` there ever be `0`, leading to unexpected results since we would split at `tSplit` being undefined? Should we `return locations;` in case `rootCount` is `0`?

**Comment by lehni** [comment]
I am also wondering if we should add these things as methods to curve:

- `Curve.hasInflectionPoint()`
- `Curve.getVelocityExtrema()`

etc.

**Comment by iconexperience** [comment]
Regarding first question, maybe this could happen if we search the interval 0...1 and the extremum is outside that interval. Anyway, making sure an extremum exists would not hurt I guess.

Regarding the second question: More useful would be `Curve.getInflectionPoints()`, but that would require more calculation. And I am not sure if anyone but us is really looking for velocity extrema. Maybe as a non-public function?

**Comment by lehni** [comment]
I guess we can leave it this way for now and then see what's required in both places once we start adding curve offsetting / stroke expansion functionality, right?

**Comment by iconexperience** [comment]
Right!

**Comment by deanm** [comment]
A note after having just came across this discussion (I'm not a paper.js user).  There is an established projective geometry method of cubic Bézier classification (serpentine, cusp, loop... quadratic, line, point), covered in detail in Jim Blinn's Notation, Notation, Notation:

http://www.amazon.com/gp/product/1558608605

It is part of the pre-processing in the Loop Blinn GPU rasterization algorithm of cubic Bézier curves.

http://http.developer.nvidia.com/GPUGems3/gpugems3_ch25.html
http://research.microsoft.com/en-us/um/people/cloop/LoopBlinn05.pdf

Be careful there are some errors in the GPU Gems article:

http://research.microsoft.com/en-us/um/people/cloop/ErrataGPUGems3.pdf

As covered in the above you can directly solve for the two t values at the point of self intersection by finding the two roots of a quadratic equation.  This approach is more direct and avoids having to solve a cubic equation as is done in the current code.

A good reference is Kenneth Russell's webkit implementation of Loop Blinn:

https://bugs.webkit.org/show_bug.cgi?id=44729
https://bugs.webkit.org/attachment.cgi?id=65655&action=diff

Another is Skia's GPU backend:

https://skia.googlesource.com/skia.git/+/a1f4fa72303492e3ce496d9eae529dce6d592026/src/gpu/GrPathUtils.cpp#717
https://skia.googlesource.com/skia.git/+/a1f4fa72303492e3ce496d9eae529dce6d592026/src/core/SkGeometry.cpp#571

**Comment by lehni** [comment]
@deanm thanks a lot for writing this! @iconexperience would you like to have a look at this, and see how we can benefit from it?

**Comment by lehni** [comment]
@iconexperience check out the new code based on Loop and Blinn here, which largely simplified the handling of self-intersection: e7b53c8a227418c44c1afea3c6f5f7e1493b4ff2

It doesn't break any of my tests, but perhaps you should test against your code as well.

**Comment by iconexperience** [comment]
@lehni I have been following the discussion but had no time to contribute. Also, I was wandering what the whole point was until I saw <a href="https://github.com/paperjs/paper.js/issues/1235#issuecomment-271662304">this eye opener</a>.
I will test as soon as I can. Anyway, amazing stuff!
