### ISSUE TITLE
Undo smoothing of a path

### ISSUE THREAD

**Issue by kaelumania** [paperjs/paper.js#774]
How can I undo a smoothing of a path?

**Comment by kaelumania** [comment]
I found a solution for anyone interested:

```js
path = new Path(new Point(100,100), new Point(200,200), new Point(250,200))
path.strokeWidth = 2
path.strokeColor = 'black'
path.selected = true

path.smooth()

path.segments[0].handleOut = null
path.segments[1].handleOut = null
path.segments[2].handleOut = null

path.segments[0].handleIn = null
path.segments[1].handleIn = null
path.segments[2].handleIn = null
```

Should I create a PR to integrate this as `path.straighten()` method?

**Comment by lehni** [comment]
The `boolean-fix` branch contains the `clearHandles()` method on Segment, Curve and Path which does precisely that. It'll land as soon as we've finished working on the boolean operations improvements, which should be rather soon.
