### ISSUE TITLE
Strange behavior of path.simplify with large strokeWidth

### ISSUE THREAD

**Issue by sapics** [paperjs/paper.js#775]
This is just a report of strange behavior of `simplify` in current version 0.9.24. (black path of below image is original path, red path is `path.simplify`, green path is `path.smooth`)
Sorry, I could not follow current professional discussion about `path.smooth` and `path.simplify`, thus, I do not know if current working branches `boolean-fix` and `new-smooth` can fix this strange behavior.

http://sketch.paperjs.org/#S/XVKxbsMgEP0Vi8WJRCMDJnZcdWrXSpU6dKg7EIc2lgkgglpVUf69d9iWnA7P93jcvfMBF2LVSZOGvA46dkdCSecOuP5WIfMse8is/sleVDyuLm1obeaBPqmompY8V/VGUilMQQvDFhBUGE6ZKSFuaWmqBGkYp5XZ0S1AJlGkBGEkcEk5FDMo5AA04pMhS2YYBQANt6kBNzXw2WvWyoSRj7USgL0q0GvQsBfDv8SFTOZFajA2m6NIkzBMBvNxMowVQALKie8AdeJs0jhoDLRxEDl5iIX/HX7g2FqCh0rPMbhBv/WHeGx4sZAenXGhyfdGdUOO+nV9jwGRbojDDXm26YyzerWmmRc3AuZ5volB2bNRUa8KmjFZzPqiCZTlQR/yeac/edN//o4WSRS3NqKYbMR/m6+gtc3nvZNz8HhSKryufdBq8K638Uya94/rHw==

![ws000024](https://cloud.githubusercontent.com/assets/11169954/9813189/6f0ba29e-58be-11e5-89c2-d6f4a4e38b96.png)

**Comment by lehni** [comment]
This is not really a paper.js bug... Your path is going backwards again a little bit on the right-hand side, producing a backward pointing handle in the result of `simplify()`. This leads to the wrong rendering, which is actually different in different browsers. For example, on Safari and Firefox, even the green path is showing it.

I don't think this is really something we can fix in paper.js. Could could probably write some code to clean up such backward pointing paths (little hooks), either before or after simplify() / smooth()

**Comment by sapics** [comment]
@lehni Thank you very much for checking precisely!
I was checked only in Google Chrome.

This path was created by PencilTool.
As you pointed out, I try to remove or fix backward point in application processes.

http://sketch.paperjs.org/#S/VVLLboMwEPwV5AtEchC2cSBUPbXXSpVy6KH04BA3IMxDxkpVRfn37hqQ6GHY8bA7u37cSa86TQpyarWrakJJNVxwfVM2GFnwHPT6J3hXro7upS37YAT6qpwqSvKW5bGkUpiEJoZtIKgwnDKTQjzQ1GQe0jBOM3OkB4D0ovAJwkjgknIoZlDIAWjEF0PmzTAKABoefANucuCr16qlHjOfayUAe2Wg56BhL4ZT4kJ688Q3mJutUfidMEwG83lnGDOABKQLPwJyz9micdAYaPNG5OIhNv57/MCxlQQPlU7ODq3+aC6uLniykV4GM9giPBtVtSHqj90TBsTIYqu74aZP+trp3kUgTDOdYqP7q6v3Yrdm+/vkcJ+QVZmh19GOBqP4J3hXHjur+skop6OEBkwmq74ZCcpCqy/h+qfpRtN8/84W8IjOVqt2HBoYhRSfX48/

![aaa](https://cloud.githubusercontent.com/assets/11169954/9829007/10edbff2-5932-11e5-9e76-3b0959bc233e.png)

**Comment by nicholaswmin** [comment]
What does backwards mean here?

- The last vertex lies on the path itself but not at the very end of the path?
- The handle itself is pointing backwards?

I'm getting the same behaviour with a fairly simple path, illustrated [here](http://sketch.paperjs.org/#S/bc9NSwMxEAbgvxJyaYXtsDP5jnjSqyB48OB6SNPAlq2bJQ16KP3vZoWCBw8D7zwwMO+Fz+Ezcc9fp1TjyDse82HdhzLMt/kKhS3IHticvtlLqOP2sjJbWnwKNfiBPyMa6LWSolOoQPRkZEQEsg6p25EAoxUpRgqcM9Z0OxQtWkTFhAFtDclmWoNxpE1EAu1oNSFAKukkQwFWWtVOSYJAMu4fGn4f78615Cm9HQ919Nj/ocd8ysVv9qcQp83q17v7W81Wfl9SmJZ8nOuZ+/eP6w8=): 

What would the hooks described above achieve to fix this?

**Comment by sapics** [comment]
By cleaning up backward points, some of the situations might be better.
However, it could not fix all of the cases.
If `strokeCap:'round'` is acceptable for you, I guess that it would be good result.

**Comment by nicholaswmin** [comment]
@sapics 

Actually `strokeCap: 'round'` produces this behaviour as well, just not on your example Sketch.
I'm short on time right now but when I get back I'll write up a small Sketch to illustrate this.

**Comment by sapics** [comment]
Sorry, I am not good at English.
Thus, it would be difficult to explain about `cleaning hooks` in text.
So, I draw a Image to explain (it might be also difficult to see :) ).
This is a 1-dimensional 4-points path case.
![dv](https://cloud.githubusercontent.com/assets/11169954/10721511/16e5703e-7be8-11e5-8b9f-2b759736f21d.png)

**Comment by nicholaswmin** [comment]
Ah I get what you are saying.

Kind of tricky to do this as we need to be careful not to deviate from the original path as it would simply be different as to what the user intended to draw.

The question is how do we differentiate between small backward steps(that will produce this issue) and larger backward steps (if we correct those steps we significantly alter the original path). What's the `tolerance` here for a step to be identified as backwards?

Perhaps take into account the `strokeWidth` as `tolerance` I guess?

**Comment by sapics** [comment]
As you noticed, change tolerance depends on strokeWidth, I guess that it makes better result.

One of more aggressive proposal is removing backward points.
It might be too aggressive. :)
```javascript
var segs = toolPath._segments
  , preAngle, curAngle
  , p0, p1, p2, v0, v1
for(var i = simplifyFrom; i < segs.length; ++i){
	if(!p2){
		if(!p1){
			if(!p0){
				p0 = segs[i]._point
			} else {
				p1 = segs[i]._point
				v0 = p1.subtract(p0)
				if(v0.isZero()){
					p1 = null
					segs.splice(i--, 1)
					continue;
				}
				preAngle = Math.atan2(v0.y, v0.x)
			}
			continue
		}
	} else {
		p0 = p1
		v0 = v1
		p1 = p2
		preAngle = curAngle
	}

	p2 = segs[i]._point
	v1 = p2.subtract(p1)
	if(v1.isZero()){
		p2 = null
		segs.splice(i--, 1)
		continue
	}
	curAngle = Math.atan2(v1.y, v1.x)
	
	// epsilon might change by strokeWidth and v1.getLength() and v0.getLength()
	if (Math.abs(Math.abs(preAngle - curAngle) - Math.PI) < epsilon){
		if (v1.getLength() <= 2.1) { // 2.1 might change by strokeWidth and so on.
			p2 = null
			segs.splice(i--, 1)
			continue
		}
	}
}
```

**Comment by sapics** [comment]
Above script delete a point ② of the Image.

**Comment by nicholaswmin** [comment]
Nice.

I'm running for the moment but when I'm back I'll try and hack up a script to re-align the handles after the smoothing.

Removing segments seems a bit dangerous since the removed segment might be the only anchor for a path corner.

**Comment by sapics** [comment]
Thanks!

It's true that it includes dangerous patterns which change user's shape.
It needs more careful management to decide point remove or not.

Fixing after smoothing looks great idea. It would be better and more controlable appearance!
