### ISSUE TITLE
path.unite() results in empty path on current boolean-fix branch

### ISSUE THREAD

**Issue by iconexperience** [paperjs/paper.js#776]
Finally I have isolated a case where <code>path.unite()</code> fails on two paths in the boolean-fix branch. These are the paths:

<pre>
var path1 = new Path({segments:[[160.6075323767809, 330.85756555128285, 0, 0, 62.78549052923406, -23.18549160066485], [261.8383465819905, 262.07470247937476, -9.74481985788454, 21.733682765729938, 3.313092486907278, -7.389125928860111], [263.88935325438945, 244.19550800619407, 1.651523249297087, 4.207420633192619, 0, 0], [274.75095370188933, 239.93204418180093, 0, 0, 0, 0], [294.3629794398194, 193.7001742601214, 0, 0, 7.563190712050676, 3.2083818187949973], [319.740729241553, 222.27237409836766, -6.410840321333732, -16.33225681537532, 5.912463018702233, 15.062590798200258], [316.5868988511627, 286.622533838371, 11.8608907350936, -26.453114610111264, -13.413920693759984, 29.916807211880812], [181.3924676232191, 387.14243444871715, 86.42536270145004, -31.915248317855713, 0, 0]], closed:true});
var path2 = new Path({segments:[[268.3009827109457, 193.43046881012646, 0, 0, 7.359037047450392, -3.0624266286574136], [294.3629794398184, 193.70017426012097, -9.725038248996666, -4.12545935876628, 0, 0], [281.2635766386479, 224.57969147308265, 0, 0, 0, 0]], closed:true});
</pre>

You can see them in <a href="http://sketch.paperjs.org/#S/dVTLbhNJFP2VlleDZEr3/QhixQ8gzTLJIiStgELsyPEMC8S/zymbwIxgJC/a1VXnnlf1183u5nHdXGz+fFiPtx83283t/m7+//vmsDzdHD/y8nbZrV+W93j+4+vzev+47o7PF5eXHDSC0lU0I4t6u6jSKE8Pd2cpKd8udPqFjCy3JpcWNYrt8lp08FwDEEVY+fV2uZTgUVpq4cWN/dtFcJjSksSyFQ/zcI80ww6MqzI3bOORqlGS4SndWiA0lJVarKIpJbH0OodWs3hLVRAzn8fqqGqFGje8tznXbHC7U4Eft1FuFx7h7KJiLZ1UWLIhYCcUqtyg32fNJ9S0kU7tmsQTXoGqPVqFzLgYyK0vHv041TY0AN+mDYnQxq0jiRhzQFnYXg7k8MBYShZyimmNgg8cnOhA6E6doNgEx+ABzGD3SURkSCI8oy7F0WlrDGMqIxVW1VTBGsdQFfEohhCfaz7goIVCFWKRqYt9UMBVyi4hEq/z2BheUV3lzCHwSypGAE515pyMo4g8qHBUYZaeugEirswWPCOSsElEwU4bVqMG3l0zdbjJURDGcJiKZY6F+IGNBlXIihtDtHKwiamhN8nJSBhMDERAi9icaA5RBqCjMcporCd/z+cauLef98/r3cXx8Nf67dWbq8PV7uWWyP/dEokaipRRSybUKs9hmpJFFcRBWvxMU2EgymIJOhAw+UxbEXvAN0/oj990pH7tCHWer4kAqaCnO+KUMVqNkjvKXjlh/9U82Iab4FjWCty22RIbnh3Nlkol4f+p629NOX02xvPxsH9Y3+0/7w8w52pzWO+uNj/eyy/v7w/ruvu+A5+hD4f15uFp/wk2bi4ur7/9Aw==">this Sketch</a>

Calling <code>path1.unite(path2)</code> results in an empty path (only in current boolean-fix branch, in the Sketch version the result is identical to path1).

I suspect that solving this issue may resolve many similar issues that remain in my test app.

@lehni can you reproduce this behaviour?

**Comment by iconexperience** [comment]
Previously I wrote that I am still getting *"Boolean operation results in open path"* messages, but it seems they occured only when the unite() function was called on an empty path or with an empty path as an argument. Therefore I hope that everything will be fixed once the above problem is solved.

**Comment by iconexperience** [comment]
Wrong example. Will have to find another one.

**Comment by lehni** [comment]
Wait, what?

**Comment by lehni** [comment]
There seems to be an issue with this one though. `unite()` doesn't manage to actually merge the paths...

![screen shot 2015-09-11 at 16 29 38](https://cloud.githubusercontent.com/assets/213275/9817318/66b591de-58a2-11e5-8ca3-f996a3f60bb2.png)

**Comment by iconexperience** [comment]
Yes, these are the same paths as in issue #777

Closing this again, because to avoid duplicate with #777
