### ISSUE TITLE
Resolve self-intersections in current boolean operations code.

### ISSUE THREAD

**Issue by lehni** [paperjs/paper.js#779]
The good news: With all the recent progress on the `boolean-fix` branch it appears we are now in a position to fully support self-intersections! (especially since #778 is resolved).

The bad news: The impact on performance is measurable... So I am wondering if this should be turned on by default, or hidden behind an option.

To put things into perspective though: Until recently, due to lack of control point bounding box checks,  our boolean operations code was so much slower than it is now, that even with the new slow-downs due to self-intersection, it is still much faster than in the current release v0.9.24. And nobody complained about performance there.

Also, if we can improve the pre-checks before resolving self-intersection on curves, and also intersections between two curves based on control point configuration, we can hugely improve that performance again.

@iconexperience said we could probably scale the control points by 0.8 or even 0.78, but I'd like to see some scientific backing before putting something like that in... @kuribas is this something you could help us with?

**Comment by lehni** [comment]
I am running the separate '' test-suite with this activated in cdd0cee623f9e6022dd3b57ccf200c9b27309ca3 now, and while it generally works, there is a new row of issues appearing that needs resolving. Will start documenting test-cases here.

**Comment by lehni** [comment]
@iconexperience this means that with this you should now get the same results everywhere, wether you call that `cleanUp()` method or not.

**Comment by lehni** [comment]
Here the result of the union test. Not too bad! But before we had 0 failures.

 Test Report         [union]
----------------------------------------------------
  Tests run         - 40576
  Tests passed      - 40402 99.6%
  Tests failed      - 174 0.4%

  Elapsed           - 28 : 55 : 475.1
  Boolean op. time  - 8 : 48 : 690.0
  Boolean avg. time - 0 : 0 : 13.0

**Comment by lehni** [comment]
And now with 3da921a0b080d15e266c84b4273c18daedb68f02 in place : )
```
[union] Testing paperjs unite operator.
 
  Test Report         [union]
----------------------------------------------------
  Tests run         - 40576
  Tests passed      - 40576 100.0%
  Tests failed      - 0 0.0%

  Elapsed           - 30 : 16 : 809.2
  Boolean op. time  - 9 : 21 : 526.9
  Boolean avg. time - 0 : 0 : 13.8
```

**Comment by iconexperience** [comment]
Congratulations :clap:

**Comment by lehni** [comment]
This was surprisingly easy after all the other work was put in place. Closing already : )
