### ISSUE TITLE
Consider switching to newer JSDOM

### ISSUE THREAD

**Issue by iconexperience** [paperjs/paper.js#782]
Yesterday I tried to build PaperJS on a Windows 7 machine with cygwin and things turned out ot be a bit more difficult than expected.
The only way I could make it work was to change the version of jsdom in package.json to "~4.0.0", because since that version jsdom does not depend on contextify and gyp anymore, which were the reason for my problems. 

I do not know if anything has changed in the newer jsdom version that would cause new problems in other environments, but if there is nothing else stopping you from moving to a newer jsdom version (4.0.0 or newer), please do so because builing PaperJS on Windows would get much easier.

**Comment by lehni** [comment]
What version of Node are you using there?

**Comment by iconexperience** [comment]
version 4.0.0

**Comment by iconexperience** [comment]
Oh, and I had to use `npm install --no-optional` because of canvas.

**Comment by lehni** [comment]
Yeah and jsdom 4.0.0 doesn't run on the Node versions that support canvas... So for now, we're stuck with old Node.

**Comment by lehni** [comment]
You can track progress on that here: https://github.com/Automattic/node-canvas/pull/622

**Comment by lehni** [comment]
Kind of a dupe of #772, closing.

**Comment by iconexperience** [comment]
Alright, I can live with that.

**Comment by lehni** [comment]
"Note that as of this release, jsdom no longer works with Node.js™, and instead requires io.js. You are still welcome to install a release in the 3.x series if you are stuck on legacy technology like Node.js™."

: )

**Comment by lehni** [comment]
You can feel the heat between these platforms that were now finally merged again, producing a version jump in node from v0.12.7 to v4.0.0. Confusing!

**Comment by iconexperience** [comment]
Yes, does not feel nice to be a collateral damage in that fight.
