### ISSUE TITLE
Endless loop in Path.unite()

### ISSUE THREAD

**Issue by iconexperience** [paperjs/paper.js#783]
In the current boolean-fix branch this pair of paths creates an endless loop within `Path.unite()`. I think this problem was introduced in one of the last changes, as I do not remember that it occured before. Now I can always reproduce it.
<pre>
var path1 = new CompoundPath("M167.725562990546,329.179234378187c41.778178736119,-4.587407861221 62.900814833385,-13.942426619062 71.195474407838,-28.271900084455c8.870920028484,-15.324994596921 -0.79265520512,-32.447638851414 -2.981009270546,-37.45545634731c-5.581720984654,-12.77317982761 -2.560688305248,-21.86748284704 -2.108918606092,-23.325676128592l32.46809529928,10.059092872722l24.62060364636,-10.758898088218c5.331381704354,12.20030478531 21.540724986499,54.203899157575 -0.071070603559,91.539446043797c-14.091756435706,24.344272132416 -45.597558072786,50.061398278096 -116.574300854373,57.854922975682z M262.525971829521,249.016291681841c0,0 -28.6948623078,-8.890089863931 -28.6948623078,-8.890089863931c2.510642276652,-8.103690236581 7.359661428581,-13.207417300234 12.78931474548,-16.595996047791z")
var path2 = new Path("M262.526032366152,249.016388682072l-15.905608098962,-25.486182911946c5.528729020306,-3.450410655302 12.398020284073,-5.611649365643 21.041000324754,-4.112064192509z");
var path3 = path1.unite(path2); // endless loop here
</pre>

Unfortunately I have no idea what is goin on here, but I will try to simplify the paths.

**Comment by lehni** [comment]
that's fine, I think I'll have to revert the last change anyhow...

**Comment by iconexperience** [comment]
Seems to be fixed with <a href="https://github.com/paperjs/paper.js/commit/3ce7d88347c49117f2187341167aee24848adc4a">Second attempt at simplifying boolean code.</a>. Can be closed if you have no other reason to keep it open.

**Comment by lehni** [comment]
Yes indeed! Also, check these out, some good stuff happening : )

60a725b527251a960085da3a90e6220182c6fb50
ad276ba46aaeab34aa58327f563852e691e716f9

**Comment by iconexperience** [comment]
@lehni 
Here are my comments for the new commits:
- There seem to be fewer glitches than before, but I am still seeing `Unable to switch to intersecting segment, aborting #1.10` and  `Boolean operation results in open path` messages. If you need any examples, let me know.
- There seem to be two nonbreaking space characters (xA0) in `isCrossing()` in this part:
<pre>
if (crossing != null || !intersection)
	return crossing || false;
</pre>


And I just want to let you know that you are doing an awesome job.

**Comment by iconexperience** [comment]
@lehni
Here is one simple case that still fails:

<pre>
var path1 = new Path({segments:[ 
  [249.24510126397263, 283.83333170042175, 0, 0, 0, 0],
  [277.85789987955286, 236.81506113627674, 0, 0, 0, 0],
  [274.29372677718396, 266.6487398781239, 0, 0, 0, 0],
  [279.44684602965344, 267.8712515159605, 0, 0, 0, 0], 
  [302.2920306559521, 255.7972249435565, 0, 0, 0, 0],
  [319.21332156923756, 320.5578030609943, 0, 0, 0, 0]
], closed:true});
var path2 = new Path({segments:[
  [272.80741773705455, 279.0897928633323, 0, 0, 0, 0], 
  [277.8578998794977, 236.81506113627015, 0, 0, 0, 0], 
  [302.66329267340217, 253.20628730188844, 0, 0, 0, 0]
], closed:true});
path3 = path1.unite(path2);
</pre>

**Comment by iconexperience** [comment]
Here is another case. The problem here is that two points of the first path are very close together (but nowhere near geometric precision).

<pre>
var path1 = new Path({segments:[
  [300, 190, 0, 0, 0, 0], 
  [217.41008908365893, 201.82351976883552,0, 0, 0, 0], 
  [242.75250843178407, 185.9780158605971, 0, 0, 0, 0], 
  [242.75111068177952, 185.97226195550132, 0, 0, 0, 0], 
  [221.76665676356615, 164.43125089405925, 0, 0, 0, 0],], closed:true});
var path2 = new Path({segments:[
  [213.6939769725168, 178.17823182739406, 0, 0, 0, 0],
  [221.76665676351348, 164.43125089411055, 0, 0, 0, 0],
  [242.85080696571617, 186.07460241970486, 0, 0, 0, 0]
], closed:true});
</pre>

**Comment by lehni** [comment]
Thanks @iconexperience :)

Actually, locally I use different epsilons in a couple of places that I have not committed yet. Will check tomorrow if that solves these cases...

I am aware of a row of issues still but am getting an increasingly better hang of what's going on in tracePaths(). And it's definitely getting more robust : )

**Comment by lehni** [comment]
Since this is a closed issue, it would be better to create a new one with these new cases that are not directly linked to this issue. I'll create it.
