### ISSUE TITLE
exportJSON and ImportJSON with a selected Group produce weird behavior.

### ISSUE THREAD

**Issue by namwkim** [paperjs/paper.js#785]
I am trying to implement translating items with a mouse.

OnMouseDown:
![image](https://cloud.githubusercontent.com/assets/70299/9854836/d75ae122-5ad8-11e5-9a7f-0552a9854c40.png)
1. group.selected = true
2. json = group.exportJSON

OnMouseDrag:
![image](https://cloud.githubusercontent.com/assets/70299/9854875/19d8d98c-5ad9-11e5-84ec-da334d4d5989.png)
- the selection circles do not seem to be cleared on move.
1. group.importJSON(json)
2. group.position = group.position.add(event.point.subtract(event.downPoint))

If I add these two lines onMouseDrag, then it works okay:
1. group.importJSON(json)
2. selection.deselectAll();
3. group.position = group.position.add(event.point.subtract(event.downPoint))
4. group.selected = true

**Comment by lehni** [comment]
Selection status gets persisted. You either need to deselect before exporting the JSON data, or deselect after importing.

**Comment by namwkim** [comment]
Thanks for the answer. 
Interestingly, this problem seems to occur with a group. If I have one circle, then it works fine (i.e. selection status is preserved and I don't have to deselect all and select again).

**Comment by lehni** [comment]
You're right, there is a bug with the selection structures not being cleared correctly when the group content gets replaced in the import. Here the sketch to replicate:

http://sketch.paperjs.org/#S/nZJNa8MwDIb/isklCYSQDXZJ6amDwWBbocemB9dWGy+uVGynHZT899n52Be9dDoY+33lR7LwJUJ+gKiMVg04UUdZJEiG84kbtjfUHtmcIZzZU9gnlwqZD1ErLQ1gydaDECJkLbmr84UyQsOUO4UAdGD8jbuiyJhfNtnvBMOlam3JHopvvUuz2wvc/6fAlLxTWi9IkwfF51o5iEfDOkMNTNZWc9HEFXbprMIKw7TeLWF/2LUonCJkhC/UWnikMyZw8u2lbOy5n2xuQYNwIP2InWlhNniB45UhBT6OZNzz6u01CZW6q3zD91f56vB1OUDT2U/zSFb1lPkfIedSDjgvKb/adusMF24UpX/OMhjpBBSEljTkmvbJwJo+SN+z/1RbA7zpaTYq15vuEw==
