### ISSUE TITLE
Boolean operations sometimes fail when points are almost identical.

### ISSUE THREAD

**Issue by lehni** [paperjs/paper.js#786]
As reported by @iconexperience in #783:

Here is one simple case that still fails. The second points of both curves are almost identical, which may be the reason why this fails.

```js
var path1 = new Path({segments:[ 
  [249.24510126397263, 283.83333170042175, 0, 0, 0, 0],
  [277.85789987955286, 236.81506113627674, 0, 0, 0, 0],
  [274.29372677718396, 266.6487398781239, 0, 0, 0, 0],
  [279.44684602965344, 267.8712515159605, 0, 0, 0, 0], 
  [302.2920306559521, 255.7972249435565, 0, 0, 0, 0],
  [319.21332156923756, 320.5578030609943, 0, 0, 0, 0]
], closed:true});
var path2 = new Path({segments:[
  [272.80741773705455, 279.0897928633323, 0, 0, 0, 0], 
  [277.8578998794977, 236.81506113627015, 0, 0, 0, 0], 
  [302.66329267340217, 253.20628730188844, 0, 0, 0, 0]
], closed:true});
path3 = path1.unite(path2);
```
Here is another case. The problem here is that two points of the first path are very close together (but nowhere near geometric precision). And the last point of the first path is almost identical to the second point of the second path, so the reason why this fails is probably the same as in the case above.

```js
var path1 = new Path({segments:[
  [300, 190, 0, 0, 0, 0], 
  [217.41008908365893, 201.82351976883552,0, 0, 0, 0], 
  [242.75250843178407, 185.9780158605971, 0, 0, 0, 0], 
  [242.75111068177952, 185.97226195550132, 0, 0, 0, 0], 
  [221.76665676356615, 164.43125089405925, 0, 0, 0, 0],], closed:true});
var path2 = new Path({segments:[
  [213.6939769725168, 178.17823182739406, 0, 0, 0, 0],
  [221.76665676351348, 164.43125089411055, 0, 0, 0, 0],
  [242.85080696571617, 186.07460241970486, 0, 0, 0, 0]
], closed:true});
```

**Comment by lehni** [comment]
@iconexperience with the two commits above, both issues are resolved, and I think #777 is also working as it should now.

**Comment by lehni** [comment]
Speaking of epsilons, I'd like to use GEOMETRIC_EPSILON only for trigonometric checks such as isCollinear(). I've started experimenting with using the smaller EPSILON in addOverlap() for the handle checks here: https://github.com/paperjs/paper.js/blob/boolean-fix/src/path/Curve.js#L1690 and haven't seen any edge case failing. @iconexperience it would be great if you could compare the outcome with your tests and let me know what you find.

**Comment by iconexperience** [comment]
@lehni
There are still glitches, but they have become fewer again. Also, they seem to be of a differnt kind, because the always involve compound paths. I do not think there are any issues with calling `unite()` on simple paths anymore, at least not in my tests.

Anyway, I suggest to leave this issue open. I will open a new issue with an example of the remaining glitches and if that is resolved, I can see better if this is really 100% fixed.

**Comment by lehni** [comment]
@iconexperience great! : )

Like I said, I'm aware of a couple of outstanding issues that might well cause these remaining glitches. But new test-material is always welcome.

**Comment by lehni** [comment]
Perfect! That sure sounds like an edge case : )

**Comment by iconexperience** [comment]
There are other, very few problematic cases that look like the one I just described in #784.

**Comment by lehni** [comment]
Yeah for those I have a simple idea I want to test. No need to send more of em for now : )

**Comment by lehni** [comment]
I've just committed a whole bunch of new changes. The code now resolves self-intersections before the boolean operations, and figures out correct orientation for each sub-path. The results have become much more reliable in my tests.

As far as I can tell now, all errors that I still see is due to multiple intersections in one location, and that's code I still have to write to handle that.

**Comment by lehni** [comment]
Both examples work as they should with my new code now : )
