### ISSUE TITLE
Line.getSide() and Line.getSignedDistance() return values have opposite signs

### ISSUE THREAD

**Issue by iconexperience** [paperjs/paper.js#789]
Currently the return values of `Line.getSide()` and `Line.getSignedDistance()` have opposite signes for the same parameters. I do not know if there is a standard which is the correct behaviour, but both signs should be the same, if only for consistency.

<a href="http://sketch.paperjs.org/#S/rVTda9swEP9XhF5igzH2lXXD3ehDy542KHRvcR4c+ZKKOFKRlLSl5H+fznb81RI8WMCO7053vw9Zfueq2CPP+OMOnXjiERe6pPhYGObw1aXsB1P4wh60VO6PTwRdFKTfIgZJGN7kJlf14ngjq+pOV9r4tsW6KsRuMagK7R+Uo9rvwj3FVm5VsEX36P+xvJfWFUpgEIZNE11nHnCBB1xPicBFIjAkUsOXHnSMWepeOlG9k0ZUGLxTnfmf8O1oMrb8kkTsa7KKzgVTlPJgM3bVZToqGVsYLBeUP4UjtEoqTAlnCPnLJxvA3G2M3k/Acue0T6WUS/ukdUbv8IzXKP8E0euDWfrgvwmEGQLhE4VX/66Qrs1BCSe1Ylr9NP4lD/DoNYWsk0hbHBvtCodBGvV7EK/1QZU2bixohtL6bqNaDTX9vsvidu877DJZxc/0Xg5HdsW0LY7H0kGgsf2poOHxx6NRT2wmxK8tQBu+ncMjCqdNX25jX68VP2sryRdaME74Fc4csD1Huaurw4PU0PzOEnbLcu63Oucs809bg6hy3rZ1zTBxF+a4C1N34ZK7MNddGtt7Wrajx07C2EmYOAljJ2HqJHx08mbgxdRImGlkfz/RzX+i1waLXU3V8my5Ov0F">This Sketch demonstrates how the sign behaves for both functions.

![image](https://cloud.githubusercontent.com/assets/2122773/9982319/a8260a0e-5fd7-11e5-986c-43a7de9c7c84.png)
</a>

Please note that both functions are currently being used in the code, so these parts must be changed when changing the function's behaviour.

**Comment by lehni** [comment]
Which version do you think makes more sense? Should the "left" hand side be green, or the "right" one?

**Comment by iconexperience** [comment]
I am not sure if <a href="http://mathoverflow.net/questions/44096/detecting-whether-directed-cycle-is-clockwise-or-counterclockwise/44098#44098">this answer</a> on mathoverlow may help, but I feel I should link it from here. If the use the sign of the determinant and x1/y1 is the start point, x2/y2 is the end point, and x3/y3 is our free point, then the right side has a negative and the left side has a positive sign.

**Comment by lehni** [comment]
So `getSide()` is currently behaving the right way, and `getSignedDistance()` should flip the sign, right?

**Comment by lehni** [comment]
I think this is relevant: https://en.wikipedia.org/wiki/Graham_scan

**Comment by iconexperience** [comment]
Here is some more information:

http://stackoverflow.com/questions/1560492/how-to-tell-whether-a-point-is-to-the-right-or-left-side-of-a-line

When using the cross Product of [AB]x[AP] for determining the side of a point P relative to a line AB the sign is positive if the point is on the left side.

So all information so far says that the right side has a negative sign and the left has a positive sign. As you wrote, this means that `getSign()` is behaving correctly and `getSignedDistance()` should be changed.
