### ISSUE TITLE
Problems with gradient on chrome Version 45.0.2454.99 m 

### ISSUE THREAD

**Issue by arthursw** [paperjs/paper.js#790]
I encountered a strange problem when navigating to [the gradient documentation](http://paperjs.org/reference/gradient/) on my version of chrome (Version 45.0.2454.99 m ) on windows 8.1

I tried the following sketch and had strange results:

    var path = new Path.Circle({
        center: view.center,
        radius: view.bounds.height * 0.4
    });

    path.fillColor = {
        gradient: {
            stops: [['yellow', 0.05], ['red', 0.2], ['black', 1]],
            radial: true
        },
        origin: path.position,
        destination: path.bounds.rightCenter
    };

The result:
![gradient](https://cloud.githubusercontent.com/assets/1814799/10073687/0597036e-62cb-11e5-87fd-a90dad874a9b.png)

And then when I cliced on the result the circle streched to the correct size:

![gradient2](https://cloud.githubusercontent.com/assets/1814799/10073688/0599478c-62cb-11e5-9033-7731e70c1e4a.png)

I only got the following warnings in the chrome console:

`The specified value "!" does not conform to the required format.  The format is "#rrggbb" where rr, gg, bb are two-digit hexadecimal numbers.`
`ace.js:1 Automatically scrolling cursor into view after selection change this will be disabled in the next version set editor.$blockScrolling = Infinity to disable this message`
[... 11 times the same warning ...]
`ace.js:1 Automatically scrolling cursor into view after selection change this will be disabled in the next version set editor.$blockScrolling = Infinity to disable this message`

The result is not always the same, depending on how I resize my window. I even had the correct result once.

This might be a bug in my graphics card driver (Geforce GTX 750 Ti version 355.60) which I updated yesterday. I had a warning about it this morning.

It works fine on firefox (on the same computer) and on my mac with chrome canary (v 47.0.2517.0 canary 64 bit).

**Comment by lehni** [comment]
Oh wow that sure looks like a browser or driver bug! I don't think we can address this in any way, since any canvas gradient example would probably mess up similarly. Did you try and look at other examples? e.g. http://jsfiddle.net/razh/sA6Wc/

**Comment by arthursw** [comment]
[This jsfiddle](http://jsfiddle.net/razh/sA6Wc/) works fine... strange.

**Comment by arthursw** [comment]
By the way, [here](http://sketch.paperjs.org/#S/TVBBasMwEPyK0MVpESIt7UUhJ3+gkKPjgyxv7cWqZFZyTAn+eyXXcbsgtDM7zDJ7505/AVf8MkA0PRfc+DbjmyY26tizM3Mws4/UyhLJWDjcr3R1LJUBF4EUuyHM8heIx4x0i1PYZo2fXBtkD9j1kT2zo3zLuuXplL/88ir5idaW3npKS/clXXZK3uqPyhWiH5N9VRXfYK2fC5Fcj++1YFVB0K7wdUWN1WZI+KWuxX+H7KutYpEmePDLrvCEHTq13kCOPmBE7/ZpCyGi05nbJFtEygnL9RRrwlO6aEOgh9Gji4Grql5+AA==) is of the sketch which causes the bug (this time it's blue instead of black).

**Comment by arthursw** [comment]
Actually, it works as soon as my windows is small enough. 

The is the size where it starts working:
![gradient3](https://cloud.githubusercontent.com/assets/1814799/10074138/5e0178f6-62ce-11e5-9561-210b4b818abc.png)

**Comment by lehni** [comment]
You can try modifying the fiddle to see if a bigger canvas and using the same stops will create the mess as well:

```html
<canvas id="canvas" width="1000" height="1000"></canvas>
```
```js
var canvas = document.getElementById('canvas');
var ctx = canvas.getContext('2d');

var x = 200,
    y = 200,
    // Radii of the white glow.
    innerRadius = 0,
    outerRadius = 200,
    // Radius of the entire circle.
    radius = 200;

var gradient = ctx.createRadialGradient(x, y, innerRadius, x, y, outerRadius);
gradient.addColorStop(0.05, 'yellow');
gradient.addColorStop(0.2, 'red');
gradient.addColorStop(1, 'black');

ctx.arc(x, y, radius, 0, 2 * Math.PI);

ctx.fillStyle = gradient;
ctx.fill();
```

**Comment by arthursw** [comment]
When I inspect the canvas element I can see its size: <canvas id="canvas" width="281" height="235" style="-webkit-user-select: none; touch-action: none; -webkit-user-drag: none; -webkit-tap-highlight-color: rgba(0, 0, 0, 0);"></canvas>

When the canvas is bigger than 281x235 it stops working, when it is 281x234 it works again...

**Comment by arthursw** [comment]
Yep, [this jsfiddle](http://jsfiddle.net/jbtbe6n8/) does not work.

**Comment by lehni** [comment]
So it's either a browser bug or something is wrong with your system. Did you try and search in the chrome bugs database for similar issues? I will close this issue here as it's not a paper.js related problem

**Comment by dangyoungworld** [comment]
**ssss**_ssss_

> `ssss[sssssssss](url)``ssss`
