### ISSUE TITLE
Curve.getParameterOf() results in infinite loop for degenerate curve

### ISSUE THREAD

**Issue by iconexperience** [paperjs/paper.js#791]
If you call <a href="https://github.com/paperjs/paper.js/blob/develop/src/path/Curve.js#L575">`Curve.getParameterOf()`</a> for a curve that is so small in both dimensions that it is basically a point, an infinite loop can occur. This happens very rarely, but if it occurs it is a total desaster because it freezes the browser.

Here is a simple example (**WARNING: This may freeze your browser**):

```javascript
var v = [313.9819094822828, 263.1440516240392, 313.9819094822828, 263.1440516240392, 313.98190948228273, 263.144051624039, 313.98190948228273, 263.144051624039];
var x = 313.9819086893472;
var y = 263.144048452297;
var t = Curve.getParameterOf(v, x, y);
```

Within `Curve.getParameterOf()`the values `sx` and `sy` are both `-1`, which means there are ininite numbers of solutions in x and y direction. This happens, because the curve is seen as linear in both dimensions and the point is seen on the curve. In theory any value between 0 and 1 would be a correct return value (there is an infinite number of correct solutions). Therefore the function should simply catch this special case and return 0 (or 1 or 0.5) as a fallback solution. Returning `null` would be incorrect IMHO, because `null`in this case indicates *no solution*.

**Comment by iconexperience** [comment]
@lehni In `Curve.getParameterOf()` the values `sx` and `sy` are always calculated. I you want to improve performance a little bit, we could return `null` if `sx` is zero and save the second call to  `Curve.solveCubic()`. You should not expect miracles from this, but in the Boolean Study the function `Curve.getParameterOf()` is called 27104 times.

**Comment by iconexperience** [comment]
An update to the possible performance improvement: `sx` is zero in 11210 of 27104 calls to `Curve.getParameterOf()`. So yes, I think it makes sense to  return if `sx === 0`.

**Comment by lehni** [comment]
I've cherry-picked that commit form your pull request now. Thanks!
