### ISSUE TITLE
Curve.getParameterOf() returns wrong values for small hooks at the end of curves.

### ISSUE THREAD

**Issue by lehni** [paperjs/paper.js#799]
Here is an example that illustrates it well. 

It works as it should in this [Sketch Demo](http://sketch.paperjs.org/#S/lVTbattAEP2VxS+Sibrs/SLTp6SFPBQKeYxDUOSNI6KsiiQnhZB/7+xKjiXHgXQxhp05M2fmzKxeF754cot8cfXo+vJhkS3KZhPuz5V7wbdPRd9Wf9F35N0L+hUv6bUVVkqlsRZSS6utyRCJvxOOb4JyxoiQ1GJrrJCCg5ESwY1izCgsrJaamJvlau3X/rloUblrnx0dOc/DJeVWY64NI5IaoYSFHIpjzonWkjPJqGEZ+hJIcImpplZJsMK/zBAlUBqnUghGlAWg/iIslPxeMJsVfBzPP8bzdxroH0ycM25HGDOSCsIFNCNMgHFMlFHGUiuYhhyAoxS0YwpSKs2J0QpwzGIuiOVaEcKs1ANMEmkUqKMFgQkMQt/vfNlXjUdl64re/S76hzT2kaGyqZt2iV7XHsFpXb9rfWwtgkZzOJ3bPjnfdzm6jqF4NNAMze7sJpsE9W3z6M4DRz5QfXBelUVd+W2O7ou6c4P3LZT9dqLy86ota5dWvneHosNU/kC1MJPowOGyGnxl47umdrhutmkSWkKXFzlK0FmMwNXmUM4ZSjKwtvBCIMkA2ucbjcfgBvwzYDAsVye1xGPtE0lL5yPTJHgiT1tsqh3ITTAJh34ma2xkYvlPhffqhTd4vB4w26R1m2S/+wHHTuDgqSV39c4lh3cde+pcHF4HIZECb11/OXWkMWOImg3qZ7Pzm4OuezSund/CCEH8uSOPxHPsfdP+KMqHdL9Bw9JkqHrfmxnltKyBOdAMiSP4w/7hKd/nsOWpTbyour7wpTvenSDQ3neCZVywOLvlCj7fd0D3GI3dIr++efsH) using the old code-base.

But on the `boolean-fix` branch, the following output is printed. You can see how the second iteration gets the wrong parameter for the location on Path ID 1, and the two points have a distance between them that's way too big.

```
Found 2 intersections:
Intersection 0:
Path ID: 3, parameter: 0, point: { x: 435.17197, y: 109.93154 }
Path ID: 1, parameter: 1, point: { x: 435.17197, y: 109.93154 }
Distance 1.9742350317315248e-13
Intersection 1:
Path ID: 3, parameter: 0.0018325208116727982, point: { x: 435.17197, y: 109.93154 }
Path ID: 1, parameter: 1, point: { x: 435.17197, y: 109.93154 }
Distance 0.0000011446932516827401
```

```js
view._matrix = new Matrix([9495567.745759798, 0, 0, 9495567.745759798, -4132204519.9894543, -1043862286.4975708]);

var curve1 = new Curve(397.3782051846493, 63.3307753252182, 397.3782051846493, 63.3307753252182, 435.1719657759655, 109.93154420692527, 435.1719657759655, 109.93154420692527);
var curve2 = new Curve(435.1719657759653, 109.93154420692537, 435.1757020633239, 109.92851403482048, 433.06868919427154, 111.49269316730876, 429.3409376002957, 111.50586397740894);

function createPath(curve, color) {
    return new Path({
        segments: [curve.segment1, curve.segment2],
        strokeColor: color,
        strokeScaling: false
    });
}

function createCircle(inter) {
    var path = inter.path;
    console.log('Path ID: ' + path.id
        + ', parameter: ' + inter.parameter
        + ', point: ' + inter.point);
    return new Path.Circle({
        center: inter.point,
        radius: 0.000001,
        strokeColor: path.strokeColor,
        strokeScaling: false
    });
}

var path1 = createPath(curve1, 'red');
var path2 = createPath(curve2, 'blue');

var intersections = path1.getIntersections(path2);
console.log('Found ' + intersections.length + ' intersections:');
intersections.forEach(function(inter, i) {
    console.log('Intersection ' + i + ':');
    createCircle(inter.intersection);
    createCircle(inter);
    console.log('Distance ' + inter.point.getDistance(inter.intersection.point));
});
```

**Comment by lehni** [comment]
After a bit of digging, I found that this is caused by using `GEOMETRIC_EPSILON` in `Curve.getParameterOf()` for the comparisons of beginning- and end-points. This makes sense, as the hook is so small that this epsilon overshadows it.

So I reduced the epsilon to `Numerical.EPSILON` (`1e-12`). This solves almost all remaining glitches, but it introduces a ton of other issues for which I think we need to find separate solutions.

The work is not done yet!

**Comment by iconexperience** [comment]
When tuning the parameters there is this <a href="https://github.com/paperjs/paper.js/blob/boolean-fix/src/path/Curve.js#L1514">break condition in `addCurveIntersections()`</a> that we should take a close look at.

Using EPSILON there may not be sufficient, and I noticed that changing it to 

```
} else if (tDiff > Numerical.EPSILON || oldTDiff > Numerical.EPSILON) {
```

makes quite a difference. In the old code we were using `tDiff > 0` for the break condition.

**Comment by iconexperience** [comment]
@lehni 
Here is a very simple case that fails if I only set the epsilon in `getParameterOf()` to `1e-9`. Maybe this is helpful.

![image](https://cloud.githubusercontent.com/assets/2122773/10330705/9b1b0094-6ccf-11e5-827f-92b30bffc2e8.png)

```javascript
var path1 = new Path({segments:[
[240, 270, 0, 0, 0, 0],
[250.53466323186618, 221.0057178821544, 0, 0, 0, 0],
[237.67824477332854, 193.79795691566554, 0, 0, 0, 0],
[320, 240, 0, 0, 0, 0]
], closed:true});
var path2 = new Path({segments:[
[263.31216874462405, 248.04647709671602, 0, 0, 0, 0], 
[230, 250, 0, 0, 0, 0], 
[237.6782447781314, 193.79795691339606, 0, 0, 0, 0]
], closed:true});
```

**Comment by iconexperience** [comment]
I tried to check if end points are close at the end of `getParameterOf()`, but this causes new issues and one nasty infinite loop.

Anyway, for the record here is my implementation:

```javascript
    getParameterOf: function(v, point) {
		var x = point.x,
			y = point.y,
			epsilon = 0.000001,
			abs = Math.abs;
		var txs = [],
			tys = [],
			sx = Curve.solveCubic(v, 0, x, txs, 0, 1),
			sy = sx !== 0 ? Curve.solveCubic(v, 1, y, tys, 0, 1) : 0,
			tx, ty,
			t = null;
		if (sx === -1 && sy === -1)
			t = 0;
                for (var cx = 0; !t &&  sx === -1 || cx < sx;) {
			if (sx === -1 || (tx = txs[cx++]) > 0 && tx < 1) {
				for (var cy = 0; !t && sy === -1 || cy < sy;) {
					if (sy === -1 || (ty = tys[cy++]) > 0 && ty < 1) {
						if (sx === -1) {
							tx = ty;
						} else if (sy === -1) {
							ty = tx;
						}
						if (abs(tx - ty) < 0.000001)
							t = (tx + ty) * 0.5;
					}
				}
				if (sx === -1)
					break;
			}
		}
    
    	if (t == null || t < 0.000001 || t > 1 - 0.000001) {
      		if (abs(v[0] - x) < epsilon && abs(v[1] - y) < epsilon)
        		return 0;
      		if (abs(v[6] - x) < epsilon && abs(v[7] - y) < epsilon)
        		return 1;
    	}
		return t;
    },
```

**Comment by iconexperience** [comment]
@lehni Although my idea does not solve this problem, it causes an infinite loop in `linkIntersections(from, to)` that you may want to take a look at.

**Comment by lehni** [comment]
I've been playing with exactly this idea last night, and also found the infinite loop. This can still happen the way intersections are linked up when there are multiples. I will switch to using normal arrays on each segment for that, but need a bit more thinking before implementing it.

I've also played with a simpler implementation of `getParameterOf()` that is worth exploring once the infinite loop is fixed:

```js
getParameterOf: function(v, point) {
    // Handle beginnings and end separately, as they are not detected
    // sometimes.
    var x = point.x,
        y = point.y,
        epsilon = /*#=*/Numerical.EPSILON,
        geomEpsilon = /*#=*/Numerical.GEOMETRIC_EPSILON,
        tMin = /*#=*/Numerical.CURVETIME_EPSILON,
        tMax = 1 - tMin,
        abs = Math.abs;
    var roots = [];
    for (var c = 0; c < 2; c++) {
        var count = Curve.solveCubic(v, c, c === 0 ? x : y, roots, 0, 1);
        // console.log(count, roots);
        if (count === -1) {
            roots[0] = 0;
            count = 1;
        }
        for (var i = 0; i < count; i++) {
            var t = roots[i];
            // t = t < tMin ? 0 : t > tMax ? 1 : t;
            var pt = Curve.getPoint(v, t);
            if (point.isClose(pt, geomEpsilon))
                return t;
        }
    }
    return null;
}
```

**Comment by lehni** [comment]
But regardless of these nuisances as we try to improve precision, we should take a moment to celebrate the current state of the `boolean-fix` branch:

```
glitches: 1, 0 new, 0 solved
errors: 0, 0 new, 0 solved
boolCount: 42567
glitches = [5615]
new glitches = []
solved glitches = [5615]
errors = []
new errors = []
solved errors = []
```

**Comment by iconexperience** [comment]
Yes I noticed that this morning, absolutely fantastic. But we should also show some respect to the one badass glitch that decided to fight until the end.

**Comment by lehni** [comment]
@iconexperience interesting observation about the required epsilon for `tDiff`. How did you observe that the current value isn't enough? And how many iterations are required now?

**Comment by iconexperience** [comment]
@lehni Well, when I lowered epsilon, I noticed the number of glitches going up. Then I took a sharp look and found that the tDiff at the end could lead to too early breaks. When I lowered that threshold, the glitches began to disappear.

BTW, I am not such a big fan of the curve time parameter, because for curves of different sizes we will get results of different precision. So I was wondering what would happen if I used the distance between the curves' end points instead of the t differences to decide when precision is good enough. After some tuning of the parameters the function seems to work as well as before. I you are interested in that implementation I can post it here.

And one other thing, there seem to be cases when our overlap detection still fails, which results in an insanely slow `Curve.getIntersections()`, because `addCurveIntersections()` creates an enormous call tree. I will try to find one of these cases.

**Comment by lehni** [comment]
I think the current implementation of `Curve#getParameterOf()` is buggy too, especially once the tolerances are lowered. I switched to my alternative definition above and am seeing much more stable behavior. But a lot more testing is required. With that version, I haven't seen a difference in behavior based on the reduction of epsilon in `addCurveIntersections()`. But please note, it's dangerous to simply change such a value, observe the bigger picture and make assumption based on the general outcome. There is so much going on internally, the conclusions are often bound to be wrong. To be sure, we need to look at situations where the current implementation produces wrong results (e.g. wrong intersections) and then see how these situations can be addressed, and what that intervention means for the rest of the cases, and for the algorithm in general. It's complex.

Regarding curve-time, I agree, but comparing start- and end points is bound to cause problems, e.g. when dealing with loops. Curve-time is also not linear across the curve, so even within one curve, the same epsilon doesn't give us the same precisions. We would probably have to only look at positions and ignore curve time all together, which is pretty much what I'm already doing when merging found intersections (curve time is only used there to filter out intersections that are guaranteed to not be the same).

For the overlaps, we might always get such edge cases no matter how much we tweak the `addOverlap()` method. We could collect the found intersections in a separate array, count them and once there are more than 9, discard the intersections and handle the overlap, instead. If there is no overlap, the found intersections are inserted into the main intersection list at the end.

**Comment by lehni** [comment]
Another thought: Instead of calculating tDiff, we could calculate the distance between the point on the curve at the old t and the new t. Is this what you meant?

**Comment by iconexperience** [comment]
I am aware that what I am doing is no nearly ready for production and there can be many side effects that I am not aware of. But I just do not have the same insight as you, so I am simply trying out some things and if they totally fail, I know I was wrong. If they work, I keep them in mind as a potential good idea. If I post an idea here, it is usually meant just as an idea, not even a proposal. So please do not hesitate to brush me off if you think an idea is not worth following. I can take that :)

Regarding the overlaps I agree to your proposal. We should probably have a counter as a parameter in `addCurveIntersections()`. In Java this would have been done with an array of length one (so changes to the value persist if the function returns), maybe there is a more elegant way in Javascript to do this.

Finally regarding tDiff: No, that is not what I meant :) But if we have implemented that overlap fallback, we could simply use tDiff > 0. I think we introduced the tDiff > 1e-12 because we did not catch the overlap cases in advance at that time.

**Comment by iconexperience** [comment]
While trying to find a case of not correctly handled overlapping curves I found that finding self intersections may still be a weak spot. Here is a tiny curve that take exceptionally long to find a self intersection. The distance between the end points is `3.7227014968341204e-12`. It would probably be wise to handle these tiny curves in a special way.

Here it is:

```javascript
 var path = new Path({segments:[ 
[578.8341920603755, 304.57835489947115, 0, 0, -4.5250487801240524e-7, -0.000003089505412390281],
 [578.834192060375, 304.57835489946746, -8.092464440778713e-7, -0.0000030366062446773867, 0, 0],
], closed:false});; 
var ints = path.firstCurve.getIntersections(null); // takes exceptionally long time
```

**Comment by iconexperience** [comment]
My case above seems to be a numerical precision issue. If I change things just slightly, like two lines in <a href="https://github.com/paperjs/paper.js/blob/develop/src/path/Curve.js#L1334">getConvexHull()</a> from
```
dist1 = dq1 - (dq0 + (dq3 - dq0) / 3),
dist2 = dq2 - (dq0 + 2 * (dq3 - dq0) / 3),			
```

 to
```
dist1 = dq1 - 2 / 3* dq0 - dq3 / 3,
dist2 = dq2 - dq0 / 3 - 2 / 3 * dq3,
```
which should be absolutely equivalent, the self intersection is calculated much faster.

**Comment by iconexperience** [comment]
@lehni Do you know any resources that explain how to properly use EPSILON values? I have the feeling that the EPSILON used in `Line.getSignedDistance()` and `Line.intersect()` could be smaller without side effects, but I would like to learn a bit about the fundamentals first.

**Comment by lehni** [comment]
Interesting! In the slow version, did you find out where most of the time is spent, and why?

Regarding how to pick the epsilons, I have no idea really, I think @hkrish might have some hints. All I know is that you probably wouldn't want to go beyond (machine epsilon)[https://en.wikipedia.org/wiki/Machine_epsilon], wich in paper.js is defined as `1.12e-16`. Everything else was determined by testing, trial and error.

**Comment by iconexperience** [comment]
All the time is spent in the `addCurveIntersections()`, but no (or only one) intersections are found, therefore our idea of ending the search if more than 9 intersections are found will not help here. The differences in the `dist1`/`dist2` are really tiny (in the area of `1e-24` to `1e-26`), but obviously this makes a difference. Also, the problem disappears when test against machine epsilon in `getSignedDistance()`.

**Comment by lehni** [comment]
And does the same thing happen with the old convexHullCode()? Doe s switching to machine epsilon cause any new issues in your tests?

**Comment by iconexperience** [comment]
The problem does not occur with the old implementation of `getConvexHull()`. I first thought that the reason for this would be the usage of `getSignedDistance()` in the old implementation, which returns zero for dist1 < epsilon. But when is set dist to zero for dist < epsilon in the new implementation, the lag still occured.

And no, I could not see any negative effects by switching to machine epsilon. Even comparing to zero does not produce any new glitches.

**Comment by iconexperience** [comment]
I have looked a bit deeper into the `getSignedDistance()`function.For this I have written a test that runs though 100000 random lines, gets a random point on the line, and calculates the distance from the line, The maximum distance to the line over the 100000 cycles is recorded. I have done test runs for different line sizes and for two different `getSignedDistance()` implementations, the currently used implementation (using `isZero()` for `vx`and `vy` and another implementation (using `vx==0`and `vy==0`). Here are the results:

![image](https://cloud.githubusercontent.com/assets/2122773/10376643/42def544-6dff-11e5-8c23-65f434a0fd50.png)

<a href="http://sketch.paperjs.org/#S/zVVNj5swEP0rU06kSz73ljTtoT12W6lZ7aHZHFwwibXGpsYg6Cr/vTMGEiDRarWHqkj4Y+bNY3gehmdPsYR7S2/zxG148AIv1BHtC2ZACsU34g+HNcxneK0ezaOim5yh4czyH0xFOvmKwAcmMwTGuQqt0MofwTNBAa92prB0XiLqjtnDxLhYBL4/PSlooXSl8+rV0MXrWRcvsa5aqOE2Nwq2mG9AmQTuGWOo9+1y5/DHri57bmtRPmttouy7InG6wshGrADsnVA0srIjFnFYxJMTbi4S9Z19XEetesqSBC35drbrv3XVdc77zqIXuRg4e5G3u0uFSkzTYmoFKVO1m6qjTaPLRuwVj76IzDIV9jRJXWjgKAqcccKRZQ88tNp01BEx+O+u2JvXGK9RhtUgfTJWJ+NxkP+3POFGhExORPaTG+0X5ahL8IkoPq5hhquUjr2EJbjjL7uw5RWiakhUtkQVxVcYlNKq6hNhBnTQNWaEIyaA+/qZoxFM66LIfhtbQws6AQfCR16tyL7yi/9Eeqo71ONNalNZXsb+e4Hpnk7hnme2aYkZMKg/WPfZBBALFXWMqRbKglZgD7xBoKPhQZsCrKEwl46KMFH7wcQGw9uoCdzjKmGlSPLkjNFxw8SkhLAKJZKIDBUPsRvxaNItDAymksBqOLf2WBvUB53CmXH6UDd/Wt/cDBqVRNC1H4E/aE0Iu9oXfRnALIB5Hx7VSV3UrS+prYGk/oXjwo23OKbOnjq7NTk/002nLxEu3sB4Fs0VCW59og9ax6A+Qq0yLflE6r1/QuBv9heq9uRKIfOW293xLw==">Here is the sketch</a>

The precision of both implementation is almost the same for cuve sizes from 0.000001 to 100000000, but for smaller sizes the current implementation has a constant lower precision at around 1e-12, while the precision of the other implementation is getting better.

For the pure numerical reasons the usage of ìsZero()` does not seem to be necessary. I think they make only sense if we are expecting horizontal or vertical lines, and every line that is nearly vertical or horizontal should be treated as horizontal/vertical. But why should we do that?

**Comment by iconexperience** [comment]
Here is another test that creates a random curve with length between 0 and 1. Then it creates a random point outside the curve and calculates the distance. After that the length of the line is reduced by a certain ratio and the distance to the point is calculated again. The difference between both calculations shows the accuracy of the implementation for smaller curves.

<a href="http://sketch.paperjs.org/#S/zVZNc5swEP0rW04QY8eQm123h/bYtDNNpofGPsgg20ywRIVwoJn89+6KjxGYtJnMtFNmLCTt28fqabXyoyPYkTsL5+ae6+jg+E4kYxqfmII0Efwm+clhBcFyrdaCfmSIFGeaf2UilsdPCPrG0hxBu0JEOpHC9eCRoIBP+ya3LCgRdc30YaaMLwIvuq/4LZSeLKheDA1fzhr+jnXZQhXXhRJwh/H6FIlvvjGFetx2Nwb/ZOuy57oW5YOUKs6/CBLHFiZtxPJBXyeCWlZaYhGHRjwZYXIWqGvmp7XXsqcsSdCS3803/VVXtjHoG089z3Bg7Hlebc4VKjFMjaGdSJmqHVSWNo0uN8le8Phjkmsmop4mmXH1DcUJ3/jCluXfeKSlstRJduC+GZlvljFdoQzLQfg0WXWTT4P4PxdHrpKIpbMk/86VdE+lZxO8J4p3K5hjL6NtL2EBZvtLG7YYIaqGRGVLVJF/hU4Z9ao+EUZAG11jPGwxABzX3/Q8uKyTIv+hdA090Q4YEH5yNCP7yof/ifSUd6jHq9SmtDz3/fcC0+/yEm55rpuSmAOD+sCaY+PDLhGxNZnJRGiQhU7ymIM+cAMDNDZcmEJRkRomssbNrs3gFkeKx0XUWIxfysVeH/yhV8PVOgPbM6wb+BHQ7L5j3u244mTecv3AuYCt1IfOKbcX2WbTkZWURwHm0NxvR5RR8+562EmFGiNWMUwxc3M03bcQzK2nnb5AyNxKqY4gMbz4ah2xP5kMk4+uKQSO3UiutxxCM4SOFmk39WlJQd8lw1IKk/MbA+MZ4IIN5fufcBQCCRwEdRz9o+mmVLkhpRKNbWjaK2wzM5+Zea0Kfr4uIg1HScNXshISLlf1Jg0sV89YuuWFf2N5o6SvXZ6VyWbTcOyaDtvmbrNF02YxXpfqwShJ+CxJ2JKEFknonRfFSIpcpnyWyr27dqJC4cnUC1g7WHu6UCc49kHwh74hHFQl/A+3xdNwb2pN7izuNk+/AA==">Here is the sketch</a>

The precision of the current implementation stays at 8.5e-14 until for smaller curves it goes up to 70 and stays there. The other implementation that does not use epsilon has a constant precision over all ratios.

**Comment by iconexperience** [comment]
For small lines `getSignedDistance()` is running deep into trouble, because if `vx` and `vy` are both smaller than epsilon, the lines are always treated as being vertical. That means if we have a horizontal line and make it shorter than epsilon, suddenly it becomes vertical.

**Comment by lehni** [comment]
Very interesting! Thanks for this thorough analysis. But why do we even need to handle the special cases of vx == 0 / vy == 0? What happens if we skip those checks and always calculate `(vx * (y - py) - vy * (x - px)) / Math.sqrt(vx * vx + vy * vy)`?

**Comment by lehni** [comment]
Also, we should probably look through the code base and find other places where we use `Numerical.isZero()` checks or compare `Math.abs(value) < Numerical.EPSILON` (in all its variations, we'd have to look through the code searching for `Numerical.EPSILON`), and then figure out if these can be improved in similar ways.

**Comment by iconexperience** [comment]
Thanks, as a side effect with the new implementation the functions `getSignedDistance()` and `getSide()` always return the same result (although still with opposite signs). Before they were inconsistent for small curves.

**Comment by iconexperience** [comment]
@lehni I noticed that in some cases the new `getParameterOf()` function does not seem to work in properly. I found this by looking at cases in `Curve.addLocation()` where `t1` or `t2` is `null` and `getParameterOf()` for `p1`or `p2` returns null. In these cases I used `getNearestPoint()` and calculated the distance from the nearest point to `p1` or `p2`. In all these cases the distance was below epsilon (1e-12), so `getParameterOf()` should have returned a value. This never happened with the old implementation.

**Comment by iconexperience** [comment]
I have found something that I would consider an inconsistency. In the following example the curve is considered straight. The curve has an angle of 45°, but the tangent at the start point is calculated as being horizontal.

```javascript
var crv = new Curve([0, 0, .00000000000001, 0, 1000, 1000, 1000, 1000]);
console.log(crv.isStraight())
console.log(crv.getTangentAt(0.00000000000001, true));
```

Maybe straight curves should be handled separately in the curve's `evaluate()` function? I have tested this in out test kit. It has an effect, but it closes as many glitches as new ones are created.

**Comment by iconexperience** [comment]
@lehni And another observation. In curve's `evaluate` function if type is 0, we snap to the end points for `t < CURVETIME_EPSILON` and `t > 1-CURVETIME_EPSILON`. This is now inconsistent to our `getParameterOf()` function, because it can return t values closer to the end than `CURVETIME_EPSILON`tolerance, but if you apply the t value on `getPointAt()` you will always get the end point. Comparing to `t<0 || t>1` also reduces the number of remaining glitches down to six!

**Comment by lehni** [comment]
@iconexperience these are all great observations, thanks! I haven't had much time in the past days to look into these things but will spend some time on it later today. Next week I'll be quite consumed again, unfortunately. But we'll get there : )

**Comment by lehni** [comment]
PS: The same problem applies to `Curve#divide()` / `Path#split()`... I've been experimenting with reducing the tolerances there but got more glitches afterwards. With many of these edge cases we can only really tell after analysis of individual cases how to proceed...

**Comment by lehni** [comment]
Some observations regarding the reliability of the new `getParameterOf()`:

The cases where it does not produce a result is when the curves are extremely short, in the range of 1e-14 to 1e-13... I have managed to increase the reliability there by using MACHINE_EPSILON everywhere in `solveQuadratic()` and `solveCubic()` where so far EPSILON was used. Before I commit this change I want to do more testing though. There are still cases where no result is produced, but these are points that have a distance from the curve of about 1e-10. Since this only occurs on very short curves, I think it's probably save to then either match the beginning or the end of the curve, as you proposed.

**Comment by lehni** [comment]
And regarding `CURVETIME_EPSILON`: I think it's not a problem that `getParameterOf()` returns parameter outside of the range, since `CurveLocation` and `Curve#divide()` handles these cases. I believe that the fat-line clipping code was already able to find intersections at parameters outside that range.

**Comment by iconexperience** [comment]
Regarding `getParameterOf()` I think an ideal function would return a valid value if the point is somewhere on the light or dark green area below, but not outside that area.

![image](https://cloud.githubusercontent.com/assets/2122773/10416553/e36dd7fa-701b-11e5-938f-18ca5b98769e.png)

My proposed modification only makes sure that points in the dark green area are found, too. Therefore IMHO it is the correct thing to do.

**Comment by iconexperience** [comment]
I do not quite understand what you mean by *"I think it's not a problem that getParameterOf() returns parameter outside of the range"*. I do not seem to find any of these cases, it's always 0 <= t <= 1. Maybe this is a misunderstanding?

**Comment by lehni** [comment]
I meant this range: `NUMERICAL_EPSILON <= t <= 1 - NUMERICAL_EPSILON`.

**Comment by iconexperience** [comment]
I understand. But if `getParameterOf()` is part of the public API, it I think people would expect it to behave as I tried to visualize above. Do you agree?

**Comment by lehni** [comment]
I think it would slow things down substantially... I'm not sure how to achieve this without doing what we're currently doing in `getNearestLocation()`. And I don't think this is the source of the glitches we're currently dealing with still. While `getParameterOf()` is part of the API, it is way more low-level than most other exposed functions.

**Comment by iconexperience** [comment]
We should certainly make things work first. If you think that this would hurt performance, then let's leave it out. Since results seem to be not affected (according to my tests at least), we should save this discussion for later, once boolean operations are running. Then we can get more academic :)

**Comment by iconexperience** [comment]
I just had an idea to run through all the roots in `getParameter()` and select the root with the smallest distance to the specified point. This changed nothing at all and it seems we can save this idea for the academic discussion, too.

**Comment by lehni** [comment]
I tried this idea out too about two days ago :)

**Comment by lehni** [comment]
I think I am on to something: Many of the current glitches go away if I scale the paths slightly, e.g. with a factor 1.5 or 2. This hints at imprecisions at `getWinding()` overweighting the increased precision of the new `getParameterOf()` & co, which finds more intersections in edge cases, and in all the cases I looked at, the amount seemed to be correct. The problem now is that we are getting locations that are very close to each other, and the winding contributions are then sometimes wrong for such short curves in between them.

So I have experimented with reducing GEOMETRIC_EPSILON, and this is yielding some very interesting results. I am still looking into the details before I am able to tell for sure... But I have a feeling that the remaining glitches now often have something to do with these tiny overlaps as mentioned in https://github.com/paperjs/paper.js/issues/802#issuecomment-147187357

**Comment by lehni** [comment]
The of this simple statement in `Path#reduce()` reduces the number of glitches down to 9. Hundreds of such tiny curves are removed in your test-suite, which appears to produce a whole lot of such mean curves:

```js
            if (curve.getLength() < Numerical.GEOMETRIC_EPSILON)
                curve.remove();
``

**Comment by lehni** [comment]
I've committed a bunch of changes now that reduce the number of glitches to 8, and to 4 if I use the hack outlined in https://github.com/paperjs/paper.js/issues/799#issuecomment-147191404. That's very good!

**Comment by iconexperience** [comment]
So I had this glorious idea to set the handles to `[0,0]` for each curve that returns `true` for `isStraight()`, in order to check if handling of "almost" straight curves may cause any issues. The result was, that no glitches were solved, but two new ones were created :(

**Comment by lehni** [comment]
I think the remaining 8 glitches need proper analysis to find out if there is another strategy required to handle another type of edge case. I'm pretty confident we'll find something here too :)

**Comment by iconexperience** [comment]
Here is my theory for the cause of some of the remaining glitches. Below you can see two curves with end points closer than epsilon (green circle). The tangent at the points indicate that the upper curve actually runs below the lower curve, but it actually doesn't, because the upper curve moves away from the lower curve instead of crossing it.

![image](https://cloud.githubusercontent.com/assets/2122773/10424891/5440c8c2-70d3-11e5-8982-3280b5e538cf.png)


Maybe in this case one should take the crossing of the two tangents (blue dot), and if its distance from the points is larger than epsilon, use the lines to the blue point to calculate the winding contribution.

**Comment by iconexperience** [comment]
@lehni I dug a little deeper and probably found a bug in `CurveLocation.equals()`. In line <a href="https://github.com/paperjs/paper.js/blob/boolean-fix/src/path/CurveLocation.js#L322">line 322</a> you are calculating the difference of the index parameters. This usually works well, but it will fail if one location is at the end of the last curve in the path and the other one is at the beginning of the first path. It can also fail if there is only one curve in the path (this actually happens).

The problem with your while sorting and comparison is, that the locations are actually arranged circular, so a simple binary search will not necessarily return the nearest entry.

Here is a solution for searching through the circula array:
http://stackoverflow.com/questions/2834652/seaching-for-an-element-in-a-circular-sorted-array

**Comment by lehni** [comment]
I think this can be closed as we don't have any more glitches to test against :D
