### ISSUE TITLE
Duplicate point in segment causes bounds error on rasterization

### ISSUE THREAD

**Issue by techninja** [paperjs/paper.js#801]
See working [error sketch here](http://sketch.paperjs.org/#S/bZCxasMwEIZf5dBkgxCSJTnEpkPp2qHQoYPlQXEO27UjhbOa0oa8exXoUuht9/3D/91dWfAnZA17XTANE+NsiMf7fvEEIzxAwE948Wkqri5Ang3HE4a0NdB1u8oKaaxUHHSthbR7te85dDupRVVrW3OtrTBKm4wzNUJJpbmuK1FVypj/Yc9/mxLFBZ/iGqkBxwiPjv2J3nAep9SAceFWti64cJemLH2m+I5DEiOmxyHNF3z2X0hFKchvCWn+xsLKsgUXhhi2uKJY41iQOMSPcNzKNr/hQOiXc5zzqazp+tsP). When it runs, move your mouse over the canvas and watch the console fill with red (in Firefox at least).

Sorry I've been out of touch, there just SO much to work on and not a moment to breathe these days. I found this by accident as it was randomly killing my ability to rasterize a layer, was returning a completely empty bounds for the entire layer on rasterization if a path with a duplicate segment existed on it. I'm not totally sure where this would be fixed (or I'd just submit a PR).

As a quick fix to my app I'll be making a "clean" function to move through any user created/edited path and remove duplicated segments, though I'm not sure if this effects non-consecutive duplicate segments? I doubt it.

**Comment by lehni** [comment]
Thanks for reporting this. The problem can be reduced to this:

```js
var g = new Path({
    segments: [[0, 0], [10, 10],[10, 10],[10, 0]],
    strokeColor: 'red',
    strokeWeight: 1
});

console.log(g.strokeBounds); // { x: NaN, y: NaN, width: NaN, height: NaN }
```

So it looks like getStrokeBounds() is choking on duplicate points. I shall investigate!

**Comment by iconexperience** [comment]
What exactly does `strokeWeight` do? It looks like it makes not difference it it is used or not. Or is this just a typo and should be `strokeWidth`?

**Comment by techninja** [comment]
That's likely a typo originally by me, whoops! :)

**Comment by lehni** [comment]
@sapics thanks for tracking this down!
