### ISSUE TITLE
Try to further improve fat line clipping

### ISSUE THREAD

**Issue by iconexperience** [paperjs/paper.js#802]
Fat line clipping appears to be very robust, but there are still cases where too many intersections are found. Here is an example

```javascript
var path1 = new Path({segments:[
[336.419491262281, 248.58591415922817, 0, 0, -11.208218357492171, -19.828652449666066],
[337.80583988437974, 215.28794527855854, 5.591284704477459, -9.803791859547232, 0, 0]
], closed:true});
var path2 = new Path({segments:[
[337.8058398843797, 215.2879452785586, 0, 0, 1.9155494882755306, -3.35873586703201],
[336.732718807867, 220.9843569583478, 0.3415385678107441, -5.510116935664939, 0, 0]
], closed:true});
var result = path1.unite(path2);
```

Although these cases are rare and do not cause too much trouble, we should try to further improve fat line clipping to handle even these edge cases correctly.

**Comment by iconexperience** [comment]
@lehni Can you assign that issue on me? I cannot even assign my own  issues, I have no rights :)

**Comment by lehni** [comment]
I can only assign you once you're part of the team. Maybe it's time to accept the invitation? : )

**Comment by iconexperience** [comment]
I feel that I would accidently break something, so let me practice a little more outside of the danger zone. I promise I will join when I feel that I am ready, which may be not too far away.

**Comment by iconexperience** [comment]
One thing that is different in our implementation from the Sederberg/Nishita algorithm is the condition when to split one of the curve and continue clipping with both curve parts separately. Sederberg/Nishita recomment splitting if the clipping did not achieve a reduction of at leat 20%. We split if the clipping and the previous clipping did noch achieve a reduction by at least 50%. So we split more often, which probably leads to a larger call tree. But maybe there was a reason why our condition is different from the recommendation by Sederberg/Nishita.

**Comment by lehni** [comment]
This change was actually proposed by you a couple of months back! We used to have thresholds at 0.8 if I remember correctly, and you suggested to lower them to 0.5 and increase the maximum recursion. I'm on my phone right now so can't link to the discussion but will do so tomorrow. Do you remember the issue? It's from the time we started improving the intersection algorithms and you ran quite a few tests...

**Comment by iconexperience** [comment]
Thanks, I actually thought that I might have proposed something like that. But with out new `getSignedDistance()` things have changed quite a bit. Therefore I am planning to collect all the test cases from the old issues on fat line clipping and examine how they behave with the new code. Let's see what the result will be.

**Comment by iconexperience** [comment]
<a href="https://github.com/paperjs/paper.js/issues/565#issuecomment-63459266">Here is my old comment</a> proposing a change from `tDiff>0.8` to `tDiff>0.5`. So I am guilty :smile: but on the other hand this wroks pretty well. I only think that it could be even better and solve more edge cases.

**Comment by lehni** [comment]
Here's a simple path that creates an endless recursion. You can see how it's created in the attached screenshots: There are two segments that have handles causing the line to go backwards / forwards over the path itself. `getOverlaps()` doesn't detect this case, but should it?

Similar scenarios cause glitches in your test-suite, @iconexperience: Although no endless recursion occurs, too many intersections are found.

```js
var path = new Path('M529,379.4 C528.9,379.4,528.9,379.4,529,379.4L529,379.4L529,379.4C528.9,379.4,528.9,379.4,529,379.4L529,379.4L529,379.4L529,379.4');
path.strokeColor = 'red';

path.getIntersections();
```

The problematic segments are created in this way:

<img width="454" alt="screen shot 2015-10-11 at 14 10 46" src="https://cloud.githubusercontent.com/assets/213275/10416769/823d1f28-7024-11e5-82ff-b0b2ae91541b.png">

And then the overlap is produced:

<img width="451" alt="screen shot 2015-10-11 at 14 11 12" src="https://cloud.githubusercontent.com/assets/213275/10416771/858a3dc8-7024-11e5-9fd6-8ba212f470c7.png">

**Comment by iconexperience** [comment]
I finally understood what you mean (after finding out that zooming is necessary to see the path). Now that is interesting. I will see if I find an idea here.

BTW, I can work the next few days a little bit on Paper.js, but then I will be completely offline for two weeks until the end of October.

**Comment by iconexperience** [comment]
@lehni I cannot reproduce the endless recursion with your example above. Am I doing something wrong?

**Comment by lehni** [comment]
Yeah now it works here too. A couple of commits back it was looping endlessly. Hmm!

**Comment by lehni** [comment]
But it produces 26 intersections now : )

**Comment by lehni** [comment]
Ah no, it was the wrong SVG. I updated it now: 'M100,100h100c94.3,0-94.3,0,0,0h100v200H100V100z'. But I don't get the recursion anymore...

**Comment by iconexperience** [comment]
Yes, that was the wrong path, because all points were identical! For that case, each curve intersects twice with each other curve, so 28 intersections was actually correct :)

**Comment by lehni** [comment]
This appears to work as it should now. Closing : )
