### ISSUE TITLE
Gap between cursor and line while drawing.

### ISSUE THREAD

**Issue by vedtam** [paperjs/paper.js#803]
Hi,

I am trying to include and center a canvas inside a html document. Right now, with the canvas (500x400px) floated to the left and placed bellow the top (horizontal) menu, I get a gap between the cursor and the line drawn on the canvas (see picture). When centered, all drawings get off the canvas.

I am wondering how to fix this. My first taught was to change the context from the $(document) to let say the div holding the canvas, but I am not sure if this would help.

```javascript
 var doc = $(document);
	var win = $(window);
	var canvas = $('#paper');
	var ctx = canvas[0].getContext('2d');

doc.on('mousemove',function(e){
		if($.now() - lastEmit > 30){
			socket.emit('mousemove',{
				'x': e.pageX,
				'y': e.pageY,
				'drawing': drawing,
				'id': id				
			});			
			lastEmit = $.now();
		}
if(drawing){
drawLine(prev.x, prev.y, e.pageX, e.pageY);
	prev.x = e.pageX;
	prev.y = e.pageY;
		}
	});	
	

function drawLine(fromx, fromy, tox, toy){
	ctx.moveTo(fromx, fromy);
	ctx.lineTo(tox, toy);
	ctx.stroke();
	}

```

html:
```javascript
....
      <script type="text/javascript" src="/www/paper-full.js"></script>    
      <!-- My scripts -->
      <script type="text/paperscript" canvas="paper" src="/www/paper-client.js">
      <div id="cursors">
	    	<!-- The mouse pointers will be created here -->
		</div>
....
```

![screen shot 2015-10-11 at 21 13 24](https://cloud.githubusercontent.com/assets/4981592/10419062/47518c28-7074-11e5-82e8-d94946fd7dd1.jpg)

**Comment by lehni** [comment]
Are you on a Retina screen? You need to include some CSS to make the HiDPI canvas scaling work, see here: https://groups.google.com/forum/#!topic/paperjs/g5gFajlNIg4

**Comment by vedtam** [comment]
Hi Jürg,

I am not on retina, it is a standard screen resolution. It has to be something else wrong. Basically from what I have seen, if I remove the top menu, and the canvas gets back into the top left corner it works ok. 

So, as it gets pushed down by the menu, coordinates are still calculated from the top corner but when I reach down to the canvas I have the mouse already at about (ex: x=97 y=76) these values are transfered to the canvas which draws from its own top left corner.

If I use paperscript the issue goes away, but I need to build it via javascript.

**Comment by lehni** [comment]
Could you create a small test case for me to replicate the issue? It can e a link to a zip file to download

**Comment by vedtam** [comment]
Hi,

Of course:

http://edmondvarga.com/demo/test.zip

Regards.

**Comment by lehni** [comment]
Which archive? I didn't get anything yet.

**Comment by vedtam** [comment]
I have replied with a link to a zipped version, earlier.  
You can download the archieve from here:

http://we.tl/TsXjovRvH2

By then as a solution I have switched to PaperScript, which works. But the JavaScript issue still exists. Feel free to check the version attached.

**Comment by lehni** [comment]
You appear to be using the native `event.pageX`and `pageY` to create the drawing, so it is no wonder that it is offset. You don't need to use PaperScript to use paper.js handling of events that handles coordinates conversion for you, e.g.:

```js
paper.view.on('mousedown', function(event) {
    console.log(event);
});
```

**Comment by vedtam** [comment]
Ahaaa...thanks! :+1:
