### ISSUE TITLE
Improve CurveLocation.compare() and CurveLocation.equals() to respect circular nature of closed path

### ISSUE THREAD

**Issue by iconexperience** [paperjs/paper.js#805]
The functions `CurveLocation.compare()` `CurveLocation.equals()` are implemented for using sorting and binary searching of curve locations. This usually works well, but it will fail if one location is at the end of the last curve in the path and the other one is at the beginning of the first path, because they do not respect the circular nature of paths.

Search can be improved by comparing agains the first/last element when we reach the end/beginning.

One case where this problem occurs is this:

```javascript
var path1 = new Path({segments:[
[255.25224104545694, 206.56224024492892, 0, 0, 16.68595677007133, 1.8409632269558927],
[277.79318931146304, 219.9760029310676, 3.7208630240332923, 4.838358092973152, 0, 0],
[252.76462261689747, 239.22382762052413, 0, 0, 0, 0]
], closed:true});
var path2 = new Path({segments:[
[277.7931893114634, 219.97600293106805, 0, 0, 0.7613133898479418, 0.9899603337364908],
[272.37296700852835, 216.3030317897695, 3.9784444252700837, 1.5352586995409467, 0, 0],
[260, 230, 0, 0, 0, 0]
], closed:true});
window.reportIntersections = false;
var result = path1.unite(path2);
```

Here is the output from the example:
```
Intersection 6 id 5 i 0 t 0.9874834926032252 o false p { x: 277.9266687620355, y: 220.1477641676552 } Other 7 id 7 i 0 t 0.6435479647840718 o false p { x: 277.9266687620355, y: 220.1477641676553 }
Intersection 4 id 5 i 1 t 0 o false p { x: 277.7931893114631, y: 219.9760029310676 } Other 5 id 7 i 0 t 0 o false p { x: 277.7931893114634, y: 219.9760029310681 }
Intersection 10 id 5 i 1 t 0 o false p { x: 277.7931893114631, y: 219.9760029310676 } Other 11 id 7 i 1 t 0.9999971256286861 o false p { x: 277.7931893114631, y: 219.9760029310683 }
Intersection 14 id 5 i 1 t 0.012819003417486376 o false p { x: 277.7809561606656, y: 219.9854106428564 } Other 15 id 7 i 0 t 0.9975534217978637 o false p { x: 277.7809561606656, y: 219.9854106428571 }
```

Intersections 4 and 10 are identical, but their "counter" intersections 5 and 7 have different curves and are at different ends of the curve. But since intersections 5 and 7 are actually very close together, comparing them through the `equals()` function returns `true`.

The problem is that `CurveLocation.compare()` does not respect the circular nature of the intersections on a path. Intersection 4 is found first and it is added to the array of intersections, because no equal intersection is found. This is correct so far. But when intersection 10 is added to the array of intersections, the binary search faild to compared it to intersection 4, so it gets added, too, although an equal intersection already exists.

**Comment by iconexperience** [comment]
@lehni Or do you know about this and close intersections at the end and start of a path are handled elsewhere?

**Comment by lehni** [comment]
Very good observations! No I wasn't aware of this but you are very right of course!

**Comment by iconexperience** [comment]
I have hacked a first implementation (using linear search), and it doesn't work at all. But I am sure there is something behind this idea.

**Comment by iconexperience** [comment]
There was a bug in my linear search, now it works. Glitches down to 5, 4 solved/1new :+1:

**Comment by lehni** [comment]
Great!

**Comment by lehni** [comment]
Are you going to post the code?

**Comment by iconexperience** [comment]
Here it is. Not great at all, so I do not want to create a pull request. But it works and can be a start.

Instance functions:
```
  getIndexParameterDiff: function(loc) {
    var path = this.getPath();
    var d = this.getIndexParameter() - loc.getIndexParameter();
    if (this.getIndex() == 0 && loc.getIndex() == path.getCurves().length - 1) {
      var d2 = this.getParameter() + (1 - loc.getParameter());
      if (Math.abs(d2) < Math.abs(d)) d = d2;
    }
    if (this.getIndex() == path.getCurves().length - 1 && loc.getIndex() == 0) {
      var d2 = -(loc.getParameter() + (1 - this.getParameter()));
      if (Math.abs(d2) < Math.abs(d)) d = d2;
    }
    return d;
  },

  equals: function(loc, _ignoreOther) {
    var diff;
    return this === loc
      || loc instanceof CurveLocation
      && this.getPath() === loc.getPath()
      && ((diff = Math.abs(this.getIndexParameterDiff(loc))) < 0.000001
        || diff < 1 && this.getPoint().isClose(loc.getPoint(), 1e-7))
      && (_ignoreOther
        || (!this._intersection && !loc._intersection
        || this._intersection && this._intersection.equals(loc._intersection, true)))
    || false;
  },
```

and this:

```
  function compare(loc1, loc2) {
    var path1 = loc1.getPath(),
      path2 = loc2.getPath();
    return path1 === path2
        ? loc1.getIndexParameter() - loc2.getIndexParameter()
        : path1._id - path2._id;
  },

  function insert(locations, loc, merge) {
    var length = locations.length,
      l = 0,
      r = length - 1,
      abs = Math.abs;

    if (merge) {  
      for (var i = 0; i < length; i++) {
        var loc2 = locations[i];
        if (loc.equals(loc2)) {
          if (loc._overlap) {
            loc2._overlap = loc2._intersection._overlap = true;
          }
          return loc2;
        }
      }
    }
    var index = length;  
    for (var i = 0; i < length; i++) {
      var loc2 = locations[i];
    if (compare(loc, loc2) < 0) {
        index = i;
        break;
      }
    }
    locations.splice(index, 0, loc);
    return loc;
  }
```

That's all I think.

**Comment by iconexperience** [comment]
BTW, there can also be some funny cases like a path with only one curve and two intersections on that curve. But I think this is all handled by my code.

**Comment by lehni** [comment]
Thanks! But oh dear, all those 2-space indents : )

**Comment by iconexperience** [comment]
I didn't expect you were actually using it :) But I changed my settings to four space tab indents. Is that correct? BTW, in the last build there was something strange with the version string in paper-full.js, the quotation marks were missing. Not sure if this was a problem with the source or with my build.

**Comment by lehni** [comment]
Yes we're using 4-space indents. But I'm just teasing you, I know the cool JS kids love their 2-spaces : )

The change you witnessed is linked to this: https://github.com/paperjs/paper.js/commit/247e80f569ce10360c2331464a6516e01f517cdc

You need to run `bower install` in your paper.js directory probably.

**Comment by lehni** [comment]
Wow, with the code that filters ultra-short curves out we're now down to 2 glitches. Brilliant!

**Comment by iconexperience** [comment]
Can you give the cycle numbers of those?

**Comment by lehni** [comment]
First, I give you this : )

```js
    getIndexParameterDiff: function(loc) {
        var d = this.getIndexParameter() - loc.getIndexParameter(),
            curve1 = this.getCurve();
            curve2 = loc.getCurve();
        return curve1.isFirst() && curve1.isLast()
                ? d + curve2.getIndex() + 1
                : curve1.isLast() && curve1.isFirst()
                ? d - curve1.getIndex() + 1
                : d;
    },
```

**Comment by iconexperience** [comment]
I think this is not quite correct: `curve1.isFirst() && curve1.isLast()`?

**Comment by lehni** [comment]
Now it is : )

**Comment by iconexperience** [comment]
BTW, I already simplified the glitch in 7121 today. This may help finding the cause:

```javascript
var path1 = new Path({segments:[
[637.3592151281335, 243.6192144811356, 0, 0, 0, 0],
[607.2325866842342, 243.37720843408812, 0, 0, 0, 0], 
[620, 200, 0, 0, 0, 0]
], closed:true});
var path2 = new Path({segments:[
[637.3592151281586, 243.61921447802615, 0, 0, 0, 0],
[628.268568383062, 264.89274114454497, 0, 0, 0, 0],
[586.4501304710124, 221.8669552644933, 0, 0, 0, 0],
[577.3611508885493, 243.137252342873, 0, 0, 0, 0]
], closed:true});
var result = path1.unite(path2);
```

**Comment by lehni** [comment]
So here the two remaining glitches: 6547, 7121

**Comment by lehni** [comment]
But this is a super great find, @iconexperience!

**Comment by iconexperience** [comment]
Yes! I still do not understand the boolean algorithm, BTW :)

**Comment by lehni** [comment]
I shall write a proper documentation once this is all over!

BTW: You don't need all the `0, 0, 0, 0` in the notation above : )

**Comment by iconexperience** [comment]
How do you know I do not need them :) I will keep them, as they show more clearly that the handles are linear.

And I just saw that I had also simplified 6547. Here it is:

```javascript
var path1 = new Path({segments:[ 
[350.5443973754219, 382.4254196888169,0, 0, 0, 0],
[339.47213311515213, 403.82191565136117, 0, 0, 0, 0],
[369.4216603158747, 405.56147420202717, 0, 0, 0, 0],
[317.7637033727652, 424.4838085588162, 0, 0, 0, 0]
], closed:true});
var path2 = new Path({segments:[
[309.5226140075971, 402.08235773964503, 0, 0, 0, 0],
[280, 350, 0, 0, 0, 0], 
[369.42166032565046, 405.5614740337206, 0, 0, 0, 0]
], closed:true});
var ints = path1.getIntersections(path2);
```

**Comment by iconexperience** [comment]
Bedtime for me!

**Comment by lehni** [comment]
Great, thanks! : )

Oh, one more thing: It looks like your simplified version of `insert()` isn't adding to the fix. And my version should perform a bit better, due to the binary search. Why did you replace it?

**Comment by iconexperience** [comment]
Because with binary search you will not find equal (=very close) locations if one location is at the beginning and the other at the end of a path. I know that my implementation is slow, but I think it is quite tricky to write a binary search search that will handle the circular stuff correctly.

**Comment by lehni** [comment]
I'm not getting more glitches though... Just sayin' : )

**Comment by iconexperience** [comment]
Yes, because you are still using the old `insert()`function. You are still missing that the old function that does not find all equal curve locations, so you will have duplicates. Maybe I can implement a version today that uses binary search and still finds all equal locations.

**Comment by lehni** [comment]
I can't really test it but I'm pretty sure 2e552853fd39c7b28226e0c9d321712d6f3e1a52 now handles the case you're describing.

**Comment by lehni** [comment]
That and this: f6f6a58fe697a302cca41995c4ddde35f289c442

**Comment by iconexperience** [comment]
Hmm, I think that can still fail.

Here is a theoretical example:
If you have already a bunch of locations on the same path in the array, the first location in the array is on curve 1 and the last location is on the last curve (let's say curve 5) with parameter > 1-epsilon. Then you insert a new location on curve 0 with parameter 0. This should be equal to the last location, but the last location will never be found, because abs(diff) of the first location is larger than 1.

**Comment by lehni** [comment]
Yeah I just found a where this occurs. Fix coming up : )

**Comment by iconexperience** [comment]
Also, you may be doing too much work. I think if you find a insert index (without finding an equal location), then only the direct neighbors are potential merge candidates. If they are not, then the entries further away also have a larger tDiff, so they cannot be merged.

This is certainly different if the new location is on the first curve with parameter <= epsilon or on the last curve with parameter >= 1-epsilon, then you have to check the last/first location for the path.

**Comment by lehni** [comment]
You're right, the loop isn't needed!

**Comment by iconexperience** [comment]
Also, I am not sure if you are considering cases like these, when there is only one curve in a path (the same occurs with two curves in a path):

![image](https://cloud.githubusercontent.com/assets/2122773/10447308/c3dd698c-7183-11e5-9637-a9a6411bf255.png)

If you compare the green location with one of the red locations, it must calculate the diff in both directions and use the smaller one.

**Comment by lehni** [comment]
I think that should be handled now. Try it?

**Comment by lehni** [comment]
I don't think we need to start comparing proximity when there are more than one merge candidates, since we're in GEOMETRIC_EPSILON territory... Isn't that splitting hairs?

**Comment by iconexperience** [comment]
That's not what I mean. Here is the part of the code that I mean:

```
            diff = Math.abs(
                    ((c1.isLast() && c2.isFirst() ? -1 : c1.getIndex())
                            + this.getParameter()) -
                    ((c2.isLast() && c1.isFirst() ? -1 : c2.getIndex())
                            + loc.getParameter()));
```

Let's say the green location is at `t0 = 0`. 
For the red location at the right  (with `0 < t1 < epsilon`) this will return `(-1 + 0) - (-1 + t1) = -t1`, which is correct. For the red location at the left (with `1-epsilon < t2 < 1`) this will return `(-1 + 0) - (-1 + t2) = -t2` with `1-epsilon < t2 < 1`, which is larger than `epsilon`, so it will not be regarded as being equal.

**Comment by lehni** [comment]
Oh I see! Yes, indeed... Maybe we just don't allow paths with only one segment, like Illustrator : )

**Comment by iconexperience** [comment]
But SVG allows it, no?

**Comment by lehni** [comment]
Yes, also our boolean operations will produce it, e.g. with self intersecting loops. I was just joking. On another note, 2bb3df3314047e0f40d57767c40c668131dfb9cb produce one new glitch: 8000

**Comment by iconexperience** [comment]
I think we still do not handle the circular stuff (still looking for a good word) correctly. If you have locations arranged like this (the first digit meaning the path index, the second meaning the location on the path).

`[p11, p12, p13, p21, p22, p23, p24, p25, p31, p32]`

and you insert a new location p20 that will go before p21 but it is actually equal to p25, how do you compare equality to p25? I think this still is not done.

**Comment by lehni** [comment]
yeah now I remember why I had that loop in place. It was handling exactly this, just not across the beginning / end. I need to revert those past commits and then do another adjustment. I'm not concentrated enough, shouldn't be working on this actually right now...

**Comment by iconexperience** [comment]
Maybe I can give it a try so you can take a rest? I may have something finished by tonight.

**Comment by iconexperience** [comment]
Oh dear, I just realized that when we compare locations for equality, the "other" locations are always compared, too. That's why we cannot simply compare the previous and next location in the list, because the next location's "other" location may not be equal, but the one after may be equal, too, and its "other" location may match.

**Comment by iconexperience** [comment]
I have problems finishing a clean implementation. Here are some intermediate results.

1. The `equals()` function seems to be fine. Maybe at <a href="https://github.com/paperjs/paper.js/blob/9762d2c9e65396ed41ecd73e43ac3e2f0a4fd0bc/src/path/CurveLocation.js#L311">line 311</a> we may want to add the following line to handle paths with a single segment correctly.

    `if (c1 == c2 && c1.isFirst() && c1.isLast()) diff = Math.min(diff, 1 - diff);`

2. <a href="https://github.com/paperjs/paper.js/blob/9762d2c9e65396ed41ecd73e43ac3e2f0a4fd0bc/src/path/CurveLocation.js#L311">Lines 495 - 499</a> are either unnecessary or wrong (depending on the idea behind them). Since the path id is the primary sorting key, locations on a paths will never be partly at the beginning an partly at the end of the locations list.

3. The calculation of `diff`has to take into account the circularity of the path, as it is already done in `equals()`.

4. In order to find an equal location, we have to start at an insert index (this is calculated as `l` currently). **And here comes the difficult (or complicated) part**. We iterate to the left until we find an equal location or until `diff` is larger than one. Then we have to find the rightmost index of any intersection on the same path. From there we iterate to the left until `diff` becomes larger than 1. The same has to be done to the right.

The steps are clear, but implementing this in a clean way is really not easy.

**Comment by iconexperience** [comment]
Regarding (4): Maybe as a first solution we should iterate to the left and right while the paths of the locations are identical. This could result in performance issues if there are many locations on the same path, but for the beginning it should work.

**Comment by iconexperience** [comment]
Here is a relatively simple implementation of the `insert()` function. This compares all locations on the same path for equality, which may be slow for cases with many intersections. The `getInsertIndex()` can later be used to find the minimum and maximum index for locations on the same path by calling `getInsertIndex(pathId, 0, 0)` or `getInsertIndex(pathId + 1, 0, 0)`.

```javascript
   function insert(locations, loc, merge) {
        // Insert-sort by path-id, curve, parameter so we can easily merge
        // duplicates with calls to equals() after.
        var length = locations.length,
            abs = Math.abs;
            
        // returns the index where a location with the specified parameters
        // should be inserted into the locations array
        function getInsertIndex(pathId, curveIndex, t) {
            var l = 0,
                r = length - 1;
            while (l <= r) {
                var m = (l + r) >>> 1;
                var loc2 = locations[m],
                    pathId2 = loc2.getPath()._id;
                var compareResult = pathId === pathId2 ? 
                    (curveIndex + t) - (loc2.getIndex() + loc2.getParameter()) :
                    pathId - pathId2;
                if (compareResult == 0) {
                    return m;
                } else if (compareResult < 0) {
                    r = m - 1;
                } else {
                    l = m + 1;
                }
            }
            return l;
        }
        
        // Tries to find a location that is equal to the specified location at the specified
        // index and in the specified direction.
        function findEqual(loc, index, dir) {
            for (var i = index; i >= 0 && i < length; i+=dir) {
                var loc2 = locations[i];
                if (loc.getPath() != loc2.getPath()) break;
                if (loc.equals(loc2)) return loc2;
            }
            return null;
        }
        
        // The insert index is the index in the array of locations where the specified location
        // should be inserted to keep the array sorted.
        var insertIndex = getInsertIndex(loc.getPath()._id, loc.getIndex(), loc.getParameter());
        if (merge && length > 0) {
            // See if the specified location and the location at the insert index
            // are actually the same, and merge if they are. If they aren't check the
            // other locations on the same path.            
            var loc2 = loc.equals(locations[insertIndex]) ? locations[insertIndex] : null;
            if (!loc2) {
                loc2 = findEqual(loc, insertIndex - 1, -1) || findEqual(loc, insertIndex + 1, 1);
            }
            if (loc2) {
                // We're done, don't insert, merge with the found location
                // instead, and carry over overlap:
                if (loc._overlap) {
                    loc2._overlap = loc2._intersection._overlap = true;
                }
                return loc2;
            }
        }
        // We didn't merge with a preexisting location, insert it now.
        locations.splice(insertIndex, 0, loc);
        return loc;
    }
```

**Comment by iconexperience** [comment]
An alternative approach would be to use a two dimensional array and use one array for all locations on one path. Maybe this is not the worst idea.

**Comment by lehni** [comment]
I won't have time to look into all this in detail at the moment for a few days, as I am about to start a new guest-professorship in Germany, but I have a feeling you're making this too complicated now. I need to outline why the current implementation is written the way it is (especially the need for the loops in `search()`, which are related to imprecisions), and this morning I had an idea for a modification that would require only a few lines of code to change, and would address the problems you're highlighting as far as I am currently grasping it. So I'd suggest to not spend too much time on this right now until I had the time to think it all through...

**Comment by lehni** [comment]
Also, in order to compare implementations: I think it would be good to have test-cases that actually produce situations that we're trying to address here. Otherwise we're simply coding into the blue, and have no way to verify the assumptions...

**Comment by lehni** [comment]
What I am trying to say is: We should try to fix problems that actually occur, not chase ones that we haven't encountered yet. The 4 remaining glitches are all most probably not happening due to the issues outlined here. Some feedback to the points raised above:

1. This makes sense, and can perhaps be simplified:

    if (c1 === c2 && c1.isFirst() && c1.isLast() && diff > 0.5)
        diff = 1 - diff;

2. That's not the case, because there are actual situations where multiple intersections are found in the same spot, but due to numerical imprecisions, they all vary ever so lightly in their curve-time parameters, that they end up being arbitrarily sorted. This is why I am currently searching for potential candidates for merging both ways from the found insertion index, until the `diff` value `>= 1`, meaning in the vicinity of one full curve. This value could probably be `0.5`, but I didn't want to take chances. In my opinion it's fine to do this kind of search, not very expensive at all in most cases. The calculation of this `diff` value simply needs to address the beginning / end of the paths as well, and we should be fine here. That's the one change I wanted to implement, after realizing my changes this morning were wrong, and produced new issues.

3. Yes I agree, but only when comparing for merging, not when sorting. See my point 2.

4. I don't understand this. How is this better than what we currently have, and what does it address?

**Comment by iconexperience** [comment]
Hmm, but the locations array contains locations from different paths, and they are always grouped by path. Let's say the array has 10 entries. Entries 0 to 4 are on path 1, and entries 5 to 9 are on path 2. If you are at index 0 and diff is smaller than 1 (or maybe 0.5 in future) and you want to check the left neighbor, you will have to continue at index 4, not at index 9 (as it is currently done). That's what I mean with 2 and especially 4.

Anyway, regarding the professorship: Wow and congratulations! I will stop working on this now as I am busy preparing for my big trip Maybe I can still find the time to implement a test case.

**Comment by lehni** [comment]
Oh darn, you are right of course! I'm sorry, I'm half attentive today, due to the reasons stated above.

I'm glad we're on the same page now. I need to consider all this for a bit, I'm sure there's an elegant solution.

And thanks for the congrats! I'll still be based in Zurich for now, commuting bi-weekly to Nürnberg for 3-4 days...

**Comment by iconexperience** [comment]
Fully understandable, I am wondering where you still take the time from to work on this. Too bad Nürnberg is almost on the other side of the world from here :)

**Comment by iconexperience** [comment]
@lehni As I wrote before I will be offline for two weeks, but I wanted to share these two points before I pull the plug. Both issues do not necessarily cause any glitches, but I think the behaviour is just not correct.

1. I think the merging of intersections is a bit too ambitious in some cases. Here is an example:

![image](https://cloud.githubusercontent.com/assets/2122773/10525393/c5dbd8ec-7384-11e5-9cb9-6bc4e772750f.png)

We merge intersections if they are very close together (distance smaller than `epsilon`) and `diff`is smaller than 1. In the example above only one intersection is found, because the intersections i1 and i2 will be merged, although their distance on the path is longer than epsilon. They are only merged because the angle at the corner is very steep and the two curves are still very close to each other at the intersection points. Maybe we should limit the merging of close intersections to cases when both intersections are on the same curve?


2. In certain cases it can actually happen that we have two intersections between two lines. Here is the example:

![image](https://cloud.githubusercontent.com/assets/2122773/10525740/b85b559c-7386-11e5-8320-c69abbe96e6b.png)


The function `Line.intersect()` has a tolerance that allows finding intersection points that are slightly outside the line. Therefore in the example above an intersection between line 1 and line 3 is found at p. Another intersection is found at i, where lines 2 and 3 intersect. The two intersections cannot be merged if `diff` and distance are above thresholds, so we will get two intersections on two lines. A mathematical revolution ;)

**Comment by lehni** [comment]
@iconexperience before responding to https://github.com/paperjs/paper.js/issues/805#issuecomment-148503018, I believe with 63303a59f49ef036671128451cab0afd5c65f1dd I found a good solution for https://github.com/paperjs/paper.js/issues/805#issuecomment-147850806. Do you agree?

**Comment by lehni** [comment]
And now the responses to the last post:

1. I don't think that's the case. Do you have an example where this actually happens? The reason why I doubt it is that `equals()` will return `false` for these two intersections, even if they are that close to each other, due to the fact that the path they are intersecting with is different, and we only merge if `equals()` returns `true`.

2. That's indeed an issue, which I shall address. Do you know if this is the source of some of the remaining glitches? If so, which ones?

**Comment by lehni** [comment]
@iconexperience I've addressed your point 2. in 93e9e54ae57760d8ea1b580eae83281d80fec002, but the glitches remain unchanged.

**Comment by lehni** [comment]
I am closing this issue since I believe it's correctly handled now. Feel free to reopen if I'm wrong.

**Comment by lehni** [comment]
3ae0ca6c944afce83ff8946de41900967d44d61f has lead to big improvements again. I'm down to two glitches without filtering short curves out anymore!

**Comment by iconexperience** [comment]
@lehni I am back from my vacation and will look through all the new changes during the next days. I agree that 63303a5 is a good solution, basically it's an implementation of the two dimensional array that I was thinking of.

In general: Great work again. I will write more comments once I find the time to look through all the new changes  (and it looks like you have achieved quite a lot withing those two weeks).
