### ISSUE TITLE
Declarative animations

### ISSUE THREAD

**Issue by pmros** [paperjs/paper.js#807]
I like onFrame but sometimes I feel it would be better a declarative animation system, like CSS animations. So I was thinking about create a library for that. Do you know if  there is any similar library out there? What do you think about the idea?
Thank you.

**Comment by pmros** [comment]
I answer to myself. There is currently a project just for that: [animatePaper](https://github.com/Eartz/animatePaper.js). It would be nice if it would be part of Paper.

**Comment by lehni** [comment]
I'm reopening as this has been on my list of things for a while.

**Comment by iconexperience** [comment]
@lehni Just a suggestions: Maybe you should add to issues like these a label `feature-request`. This would make it easiert to search for actual bugs in the issues list.

**Comment by lehni** [comment]
Good point!

**Comment by eeropic** [comment]
http://paperjs.org/reference/tween/

**Comment by lehni** [comment]
Yes, let's close this!
