### ISSUE TITLE
Rounding error after repositioning paths

### ISSUE THREAD

**Issue by aureole82** [paperjs/paper.js#808]
Hi

I have RegularPolygon path and assign a new position [160, 20].
But I got **[160, 20.000000000000004]**!

Assigning the same position [160,20] a second time I got got [160, 20]? That's weird!

http://jsfiddle.net/r7trthm2/

**Comment by lehni** [comment]
It's not weird, it's completely normal for 64 bit floating point values to behave that way. Every time you transform / move a path that has `path.applyMatrix = true` defined, the transformation will be backed into its segment list, causing such small imprecisions.

**Comment by aureole82** [comment]
Yes, that would explain it. But than [160, 20.000000000000004] should be the final position.

**Comment by lehni** [comment]
No, because applying it translates it by 0.000000000000004 in y-direction, applying a new affine transformation that changes the coordinates again. and #position is defined as the center point of the bounds. etc.
