### ISSUE TITLE
onFrame (the function) and view.on('frame', function) create separate handlers

### ISSUE THREAD

**Issue by bmacnaughton** [paperjs/paper.js#810]
When I create a frame handler using the syntax `function onFrame(e) {...}` and also create a function using `view.on('frame', function(e) {...})` they both get called on the frame event.

Here's a sketch demonstrating the issue - each of the two handlers draws different colored circles.

http://sketch.paperjs.org/#S/vZPBTsMwDIZfxeplrTR1wLGIE4gb0iSQOFAOWequ0TK7StJVMO3dSdJuK0IIwYH0kMaO/3x24n1CYotJkTxu0MkmmSeSq7AuyYhKdRZu4PLiuiSJ5ND41U5hn1v1jvm20061+i1dsiKXG0EVb9Ms87tLqjuSTjFBZUR/q4zUmErWbDLYlwR+7ISB36mGKMIelsI1+ag5ioUxiBXjPD87hkyKcZ44rDO8wduA5cPC9MX5rCrXFHA12A9ZSYeQ3mIBrlEWZKSANTobM/WuScIzg9VsqMcx4FQXwp3PPAZKoTVWk5ox3Rt/LSmeijUVXWkhN1E2okgmyxpzzet0VrORCALqEB/3xMriVjnvjMY57A+fmSYQ/mhvQ6hZa+4VrcH1DCHcjlIjm7+zI+43mGuDSP+GGUJPhGeNHxjbzrR6ABgP+zumY9a+KuGBPvnfNFiDzfM8cGfxjnuaVu3cCBG6ro+SxzcWPt+QK4Ni04ZmsEnx8nr4AA==

**Comment by lehni** [comment]
It's not a bug that they both get called, that's intended behavior. If you call `view.on('frame')` twice with two functions it also installs them both, as it would be in almost any JS based event emitter class. The problem is that one of the events installed in this way doesn't seem to get called, but I understand now why, and I think it's a wont-fix:

The global `function onFrame() {}` is actually just a PaperScript convenience short-cut to `view.onFrame = function() {}`. If you have defined both, then the global one will replace the instance-based one at the end of the execution of the PaperScript code. This explains why manually triggering the event draws two green circles, while afterwards only black ones get drawn.

**Comment by bmacnaughton** [comment]
I think you're right on view.on('frame') multiple calls - that's the way most JS stuff works - it distinguishes based on the function signature.

My only thought is that maybe the global function, onFrame, should behave the same way as opposed to replacing the view.onFrame function. But it doesn't really matter to me that much - I rarely write paperscript except in sketch, so I would use one of the other two methods.

Thanks for looking.

**Comment by lehni** [comment]
It would be difficult to implement that... I think it really depends on how they are explained. If we write that these global functions are installed as `view.onFrame` / `tool.onMouseDown` etc for you, then there is no ambiguity. Keeping this open since the documentation of this should improve.

**Comment by bmacnaughton** [comment]
I'm seeing some odd behavior on handlers in general - maybe it should be another bug, but I thought I'd ask. Here I'm setting handlers on view.on('mousedown', function(e) {...}) and 'mousedown'. It results in the bounds of the item being selected when I click (either to create or just to perform a hitTest). If I set global onMouseDown(function(e){...}), etc. as opposed to view.on()  then it doesn't select the circles' bounds.

[sketch](http://sketch.paperjs.org/#S/tVQ9b9swEP0rFw0RDRtM0FGBl3oIChRFgQbo0HagxVNEmCINftRDoP9eUrRkyWbTqZwk3nv3+Y5vhWIdFlXx7YCubotNUWse/xuvaie0gp0wtURLVvD2U0E4rhWWvhrtj7AFhSd4jt9k9TQz1wPpi+/2aALqcW7j+qQ+Oewi20sZTMn4W+CJakXKTnuLEVVuYEyD4BR/wDIDrXDBxSUbGi5e0DqC9KiFcmNC8Tw8gGjghMAFV6UbuJEJqQ7GOTBISV9IgUHuAnIReYyewOcOfGWupalR5AobT43KoangnNjmFmEYF95W8OExY2yElDstdfBQGuRlBhKHGKwpqRLWt1PIkCxKrB3yChomLS4B/bx9y7HT0K5dKyQnKUAWOY+9Xj9BBjITQkJf+UmXdEwzwIY8r1AGnTdqdtkvxh5mHod9O91wS0WITvfaK27fC3Od7UidpNvTvVCcRNxq7EZO1P74HyQ9Lw+Y4iBcaUHpqHAEG5SxIDE73E/l5FQfXd7fT3XC3Xa7bEJ2JaRQi4X4HP5z69AY3VVLf6E8K2JTMjJ1uroM6x2cdUYfcFyUvWT1IbcqCfZdcNf+Zd/OjtgxuvHOlf/YjFh3kI/iL/pjCEqy+3D76k3+8hrqo7jScOy5q9NTPAgvvNV7g+wwKMMW1Y9f/R8=)

**Comment by bmacnaughton** [comment]
I shouldn't have closed the previous comment - it wasn't clear to me that `view.on('mousedown', function)` should work all - it's neither documented nor is there a `this._eventTypes` property for `'mousedown'`. I then tried substituting `project.activeLayer.on('mousedown', function)` and the same for `'mouseup'` and neither handler is called when I click the mouse.

Am I missing something fundamental? I read that a layer is an item and an item can have handlers attached to it.

**Comment by lehni** [comment]
What version are you on?

**Comment by bmacnaughton** [comment]
Whatever version is running on sketch.

**Comment by lehni** [comment]
Perhaps it's time to force reload the page? This was changed in the last release.

http://sketch.paperjs.org/#S/TU1LCoMwFLxKeBsVxAPoMdpdU0TjqwZ1npioiHj3RumisxiYDzMHoRqZcnr07E1HKRlpLr1a3jJBHI2yOG5kQ5SqzwLjbXB5ZfhEHRoqwAicDJwN0v6SQuO8SOM/uzfLu/HcJ3ZJEf7qmat+EgvvKH+9zy8=
```js
{
    frame: {
        install: function() {
            this.play();
        },
        uninstall: function() {
            this.pause();
        }
    },
    resize: {
        install: function(type) {
            this._installEvent(type);
        },
        uninstall: function(type) {
            this._uninstallEvent(type);
        }
    },
    mousedown: {
        install: function(type) {
            this._installEvent(type);
        },
        uninstall: function(type) {
            this._uninstallEvent(type);
        }
    },
    mouseup: {
        install: function(type) {
            this._installEvent(type);
        },
        uninstall: function(type) {
            this._uninstallEvent(type);
        }
    },
    mousemove: {
        install: function(type) {
            this._installEvent(type);
        },
        uninstall: function(type) {
            this._uninstallEvent(type);
        }
    }
}
```

**Comment by bmacnaughton** [comment]
OK, that shows why view works (and why it didn't in .22) But view leaves the items selected (check out my sketch link above). How can I clear that?

And if I replace `view` with `project.activeLayer` then the handlers never get called.

**Comment by lehni** [comment]
The item is selected because sketch adds a special tool button with which you can select items, the black arrow. this arrow is in operation and its handlers are called as well, after the ones from the view. For now, you can circumvent that simply by creating a new, empty tool:

```js
new Tool();
```

**Comment by lehni** [comment]
It would be good if this special tool wasn't called if the view handlers return false (to stop propagation). I will have to look into this on Sketch.

**Comment by bmacnaughton** [comment]
OK, I'll do that. Thanks for the information. Is it a bug that `project.activeLayer.on`  doesn't invoke the handler?

**Comment by lehni** [comment]
The way things are currently defined, items only receive events when they receive events on their actual content. If you click into an "empty" space inside a layer, how could paper.js know which layer you want to click on? Such events are currently only handled by the view, or by tools.

**Comment by bmacnaughton** [comment]
OK, view works fine now that it's implemented - fantastic addition. I had presumed that activeLayer would clicks that didn't hit anything else. Bad assumption on my part.
