### ISSUE TITLE
Latest build broke the paperjs.org website?

### ISSUE THREAD

**Issue by hovavo** [paperjs/paper.js#813]
Posting here as well as here: https://github.com/paperjs/paperjs.org/issues/19
(as I am about to start teaching a paper.js class in less then two days :/ )

Those assets are missing:
http://paperjs.org/assets/node_modules/prepro/lib/browser.js
http://paperjs.org/assets/src/load.js

**Comment by lehni** [comment]
https://github.com/paperjs/paperjs.org/issues/19
