### ISSUE TITLE
group.onMouseDown ToolEvent has null.item

### ISSUE THREAD

**Issue by bmacnaughton** [paperjs/paper.js#817]
When:

```
group = new paper.Group([circle, square]);
group.onMouseDown = function(e) {
}
```

`group.onMouseDown` is invoked and receives an event but `e.item` is undefined. Performing `group.hitTest(e.point)` returns the item that was hit and should be in the property `e.item`. Here's a [sketch](http://sketch.paperjs.org/#S/fZFPa4QwEMW/SvCiC0HsLr1YetqFngql7U09pNlRw+rMNhm7h8Xv3miUpVA2kH+PN/N7JNcIVQ9RHn2cgHUbyUjTcbqXWOKPskIbqzsQzwLhIt4Ut+l+VpJricIPDchgc1E8ZJn0s5JBt+poBpeLbbYItem6PXXkvbGFY7zIE94rAROXOG6eAth9D8r+Ab+DZoXNjV1b6j15+5hJ4ZcVzeTFnY8jdrc89/EBtuJDgMbScF74L9M5KUJKuWSrgnf2pYSvNDg40AV9TT2gZkOYwEasD0XoqIO0oyaJIT1zHkvhdzLIU6N/PGbxGIZ+tUzJDHsEt8alreFPcJzc6WNmdfQ/+2VBnWafi/KiGn8B).

**Comment by lehni** [comment]
Only `ToolEvent` objects define #item. `group.onMouseDown()` receives a more low-level `MouseEvent` object.

**Comment by bmacnaughton** [comment]
OK. Thanks again. So my logic to just handle mouse events for the whole view then use `group.hitTest(event.point)` is probably a pretty good way to accomplish what I'm trying to do. `targetItem` would be nice but if there are nested groups it could get tricky unless always defined as a path. Given a path the caller can always reference parent to find out if it is a member of a group, if they want to.

**Comment by bmacnaughton** [comment]
On second thought, if I attach a handler to a specific group I am interested in that group's children, not eventual ancestors. So it's probably not as tricky as I was thinking.
