### ISSUE TITLE
How to remove subtracted shape?

### ISSUE THREAD

**Issue by georg-paul** [paperjs/paper.js#818]
Hi there,

First of all, thanks a lot for the great work and effort especially in the last weeks!!

I've created the following sketch:
http://sketch.paperjs.org/#S/hVPLbsIwEPyVVS4EJYJILagijXroqTdUDj2UHkyyeQhjI9shlRD/3nVK0zhAGymxvY/x7Ozm6Am2Q2/hrbZo0tILvVRm9nxgCja8xldMDRMFR0hAYANLZspJZ/RnUQj2nUftZhyuBdCj641RLDWrku3bzJrzs0uhrrmxMK79cyk1We5nA4i3KmtDZ1H87VgLh9ckrzh/llwqChpZ1ygehmjktMeMIoyqkfxrkVOCb6usyBrFtDzCnJYgGMPxRhWX9VvWoSXt8rWCjOMrKC5bhdmoq8p+qxx84pMQo47FhWiD2s7wvnPPz+UnQK7xJtTv4T+cPsu2VUEyaFEAd9HVkhXu5AF9C3WyyvcuddQoFKKwevQCCEZozgz6NF8PpClMp9AZwTbRib/Wacp4gYYJA0ZCgQZUlYHMwZTYakkqnMVsY5uSGWA7yslkJQpolBTF03CkekX9PWv0S20Usu2ewIz2Fu8fpy8=

I want to get rid of the blue rectangle but it somehow doesn't work. Could you tell me what I'm doing wrong? (I've searched the known issues but haven't found anything similar)

**Comment by sapics** [comment]
@georg-paul 
I am also thankful to recent great work!

To get rid of the blueRectangle by `blueRectangle.remove()` looks work.
But path.substract create a new path, thus, we need to remove each resultPath.

Sorry, I am not good at English. The following sketch might be helpful :)
http://sketch.paperjs.org/#S/hVRba8IwFP4rh75Y8VbYHMNOhsw9CMOJCnuYe4j22BZjImmqA/G/76Tz0tS6Fdok5/Kd71zSvSPYGp2OM1mhXkRO3VnIwJy3TMGcpzjGhWYi5AhdELiDEdNR8yx0214dzPvgZZtqfSaAniSda8UWehKxTeaZcn5UKUxSrg2MLd8oilWu+h7JhCT37QL6Rxxkpm3P/1XMhEW5uYw5f5FcKjKqGFXFL5okyGmPAVlolSLpZ2JJDq4pQExSz6flCR5oqdWqsL+R4HVpDOu6IW3zNbWq+iUoNluFQeWclfnGS3CJT5cYnVlc1bOQ2xHeteKcgh8AeYI3oS6H/3BMycym1YJevz+YDt6HvTdoNGAy7Y2nF/ZWh60cLE1T4Vpu0c3hl83HhZ9/I/zrsH+ilk1QrVuYnBrceaWdyDHIssvVwmpSqBCFaVPOgGBEwplGl27EI7XaEDsLwcyWZV82gOQxgB0TGrSEEDWoOAC5BB1h1mJK/tjjzHYXMQ1sTT6BjEUIOyVF+Fyc9FxSf18B+gnMFbLVhsB04nQ+vw4/

**Comment by georg-paul** [comment]
@sapics thank you very much!! works for me!

closing the issue..
