### ISSUE TITLE
New jsdom version causes SVG Export error

### ISSUE THREAD

**Issue by georg-paul** [paperjs/paper.js#821]
Steps to reproduce and environment information:
* paper v0.9.25 (due to the dependancy ">=3.1.2", the latest release of jsdom (7.0.2) is used at the moment)
* node v4.2.1 and v4.2.2 for Mac OS X
* run "node SVGExport.js" (node_modules/paper/examples/Node.js/SVGExport.js)

You should see an error:
"TypeError: undefined is not a function at exports.domToHtml (...my_local_path.../node_modules/paper/node_modules/jsdom/lib/jsdom/browser/domtohtml.js:14:22)"

The problem is the for-of loop. If you switch to "for (const node in iterable)" instead of "for (const node of iterable)" it works.
**EDIT:** By "it works" I mean the error is gone, the function is broken either way. Only when I replace the whole "domToHtml" function (with the one in v3.1.2) it works as expected.

According to https://github.com/tmpvar/jsdom, jsdom requires Node.js 4 or newer. So this shouldn't be the problem.

Anyone else having this problem? Any ideas how to fix?

**Comment by georg-paul** [comment]
This commit seems to be the breaking change:
https://github.com/tmpvar/jsdom/commit/0f5f1a22d20a1495eaf1b7649129a9e1461f8410

**Comment by georg-paul** [comment]
changing "domToHtml(node)" to "jsdom.serializeDocument(node)" fixes the problem:
https://github.com/georg-paul/paper.js/commit/d6ece1fa4bdc340000bc14da29720e07a6094be1

I didn't manage to setup the building environment yet, so I temporarily commited also the distribution file.

**Comment by lehni** [comment]
I can confirm I am able to reproduce this. But only with v7.0.0 and newer.

**Comment by lehni** [comment]
Your fix works all the way down to v3.1.2 with some exceptions around v5.6.0 or so, but I think this is the way forward.

**Comment by semateos** [comment]
Are ya'll going to release a new tagged build with this fix?  I've got it working by using a build from the dev branch but still... would be nice to have the npm installed version working.  Thanks for all the awesome work btw!

**Comment by lehni** [comment]
Yes it's coming. I've been traveling, so had little time to get this rolled out, especially since it's v0.10.0 with lots of changes baked in.

**Comment by semateos** [comment]
Sweet!  Looking forward to it.
