### ISSUE TITLE
Rendering errors with large coordinates

### ISSUE THREAD

**Issue by pcorey** [paperjs/paper.js#823]
Hello,

I'm trying to use Paper.js to render some time-series data. Each point has an associated unix timestamp (like `1446912160`). Unfortunately, it looks like Paper.js doesn't handle these large numbers well.  Take a look at [this example](http://sketch.paperjs.org/#S/lZJPa4QwEMW/yuBllUpWl92FuvRU6LGU7rH2EONYgzGROKz9Q797R6UFaQ82h0DezJv3I8lHYGWLQRacGyRVB3GgXDmeL9ID6RZ7km0HN5Du98frdJcek1NuczuWJcsWB3iQVItHVCTti8Fwkpy2FP74Y0iiOLfw5xr7z/odwzRJYuAtijhCikobc+uM8xyzIddKcpspe7uFe0fgqqpHguKNPZN4x4YelGs7g4Qw6JJq7oLZC4V7FULM6MVqdLji8ev4D9x3mOmLJb3HcoHu0ZbIIkgCaQxjQRbOZOo/ZLuVZOl0sROZWpJ12jYz2kXjIBRaQv+N8PsRT/xBCo+y6cZaH2RPz59f).

```
var timestamp = 1446912160;

var a = new Path.Rectangle(new Point(timestamp, 0),
                      new Size(100, 100));
a.fillColor = 'tomato';

// Not offset by 10
// Fills complete width of tomato box...
var b = new Path.Rectangle(new Point(timestamp + 10, 0),
                      new Size(50, 50));
b.fillColor = 'red';

// Not rendered at all... :(
var c = new Path.Rectangle(new Point(timestamp + 20, 0),
                      new Size(10, 10));
c.fillColor = 'pink';

view.center = new Point(timestamp, 0);
```

You'll notice that I'm centering the view at `(1446912160, 0)`, and rendering a 100x100 rectangle. This works fine. Next, I try to render a 50x50 rectangle that's offset by 10 pixels. This rectangle isn't offset, and it looks to be 100px wide, instead of 50. Finally, I try to draw a 10x10 rectangle offset by 20px. This last rectangle doesn't render at all...

Any idea what's going on here? These numbers shouldn't be nearly large enough to be hitting Number precision issues...

Thanks!

**Comment by sapics** [comment]
@pcorey That's interesting problem.
As you noticed, `1446912160` is enough smaller than Number precision of javascript.
However, there are many n-th power calculations in paperjs.
Therefore, I guess that the degree of precision would be worse.
(For example, `1446912160 + 10 === 1446912160` is false, but `1446912160*1446912160 + 10 === 1446912160*1446912160` is true, in javascript)

**Comment by sapics** [comment]
I don't know what kind of time-series data that you need to draw, how about using timestamp which is deviation from `Date.now()/1000`?
It is smaller than `86400` in one day. :)

**Comment by lehni** [comment]
I'm pretty sure this is an issue in the canvas implementation, not in paper.js. Did you compare different browsers? There was a similar issue in the past, but I quick search turned out empty. Will have to search more properly when there is more time.

**Comment by pcorey** [comment]
@sapics Keep in mind these are unix timestamps, so seconds from epoch, not milliseconds from epoch. For the time being, I've scaled down my X axis, but it would be awesome if we could support this kind of scale. I don't see a compelling reason not to.

@lehni Hmm, interesting. I tried out the link I gave in Chrome, Firefox and Safari and all three have the same rendering issues. I don't think it's a canvas issue.

**Comment by lehni** [comment]
I have used our internal cancas debugging tool ProxyContext.js to export the canvas commands to the console, then have built a separate example from that which does not rely on Paper.js at all.

You can see it here: https://jsfiddle.net/lehni/8c5933gf/

You can see that it renders the squares the way you expect them to look:

<img width="149" alt="screen shot 2016-01-07 at 21 39 30" src="https://cloud.githubusercontent.com/assets/213275/12182225/2f541836-b587-11e5-886d-aed48e10b0a0.png">

But as soon as you set the offset variable to 0, it will distort the rectangles the way we've seen before, proofing that error is indeed in the canvas implementations, not in Paper.js:

<img width="199" alt="screen shot 2016-01-07 at 21 39 37" src="https://cloud.githubusercontent.com/assets/213275/12182227/348448bc-b587-11e5-86df-22be0817a796.png">

Unfortunately I don't think we can work around this in any easy way, so I am closing this issue...
