### ISSUE TITLE
blendMode "add" and "subtract" error in sketch.paperjs.org on Chrome

### ISSUE THREAD

**Issue by willpatera** [paperjs/paper.js#826]
`blendMode` "add" and "subtract" errors in Chrome 46.0.2490.86 and Chrome Canary (Latest) when using sketch.paperjs.org. No errors in Safari or Firefox. 

`blendMode` work as expected when using paperjs v0.9.25 on localhost using the above listed browsers but not within the sketch.paperjs.org environment (see attached screenshot).   

![screen shot 2015-11-12 at 09 26 40](https://cloud.githubusercontent.com/assets/1407224/11109099/9b0b5772-891f-11e5-8774-c25befe28be5.png)  

Chrome console shows a warning from `jquery` as follows:

```
The specified value "!" does not conform to the required format.  
The format is "#rrggbb" where rr, gg, bb are two-digit hexadecimal numbers.
```

**Comment by lehni** [comment]
Would you mind sharing the sketch here?

**Comment by willpatera** [comment]
This appears to be resolved when making a new sketch. But for sake of completeness [here is a link](http://sketch.paperjs.org/#S/jVJda8IwFP0rIU/V1ZBa9pLhk8+DwR6NDzG5xWCWlDRTh/jfl9qaWVbnAoH7fc653BO24gMww+87CHKLcyydav298MhVVQMBLVBB6Qu3bagWYbvUXhYxauGA3qJP2oCB7MQtevAk2ACerfYaDqRzyDG/9b5mHeo6fzzNC6U/G1YQOu2a/tFTaWOWzjjPLvwvZhYn5LT/0Z5we55EwUPJ8yg5ySfSOAtZW5XypHaNDtpZ9LTodzeaJkc0uxZMKXkeFCV+/YI7gj2xRPAXufKG3HyEXDmKPii4j3xFT8g/bQXZGLDqNR5NbONYKMXxQNDf+fJOPh7ixoPY1U7b0GC2Wp+/AQ==) to a sketch that demonstrates the behavior.

**Comment by lehni** [comment]
I don't understand... What do I need to do to reproduce it?

**Comment by willpatera** [comment]
Hi - sorry. Here is a [link to a sketch](http://sketch.paperjs.org/#S/jVJda8IwFP0rIU/V1ZBa9pLhk8+DwR6NDzG5xWCWlDRTh/jfl9qaWVbnAoH7fc653BO24gMww+87CHKLcyydav298MhVVQMBLVBB6Qu3bagWYbvUXhYxauGA3qJP2oCB7MQtevAk2ACerfYaDqRzyDG/9b5mHeo6fzzNC6U/G1YQOu2a/tFTaWOWzjjPLvwvZhYn5LT/0Z5we55EwUPJ8yg5ySfSOAtZW5XypHaNDtpZ9LTodzeaJkc0uxZMKXkeFCV+/YI7gj2xRPAXufKG3HyEXDmKPii4j3xFT8g/a9gYsOo1nkxs4lgoxfFAzt/58k4+nuHGg9jVTtvQYLZan78B) that demonstrates the issue observed using in Chrome v46.0.2490.86

I closed the issue because if I open the same link in a new chrome profile, blend modes work as expected. Which leads me to think that this is browser related and not a paper.js issue and I don't know how reproducible this error would be.
