### ISSUE TITLE
"importSVG(svg, onLoad)" does not trigger the "onLoad" function when loading the SVG as string.

### ISSUE THREAD

**Issue by lilltiger** [paperjs/paper.js#827]
When importing a SVG using the "importSVG(svg, onLoad)" function the "onLoad" function will not be triggered if the "svg" parameter is a string.
This seems to be the intented behaviour when reading the documentation, but the issue arises when the svg string contains a object like `<image>`.
When this is the case the item wont be ready to use right after the the import because the image is not loaded. And as the svg parameter is a string the "onLoad" callback will not be called when the item is ready.
This means that you have no way to aquire the information of this item.

example svg (use any image as the image.jpg):

    <?xml version="1.0"?>
    <svg xmlns="http://www.w3.org/2000/svg">
      <image xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="image.jpg"/>
    </svg>

example js, with the above svg as a string:

    <script>
        paper.install(window);
        p = new paper.PaperScope();
        p.setup("canvas");

        p.project.importSVG('<?xml version="1.0"?><svg xmlns="http://www.w3.org/2000/svg"><image xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="image.jpg"/></svg>', function() {
			console.log("This will not be triggered.");
		});
    </script>

**Comment by MikeBailleul** [comment]
Why is this closed? onLoad is still not called when importing from a string

**Comment by lehni** [comment]
Works for me:

http://sketch.paperjs.org/#S/bY/BbsIwDIZfJfKFVkJJ2U4NXTnuAUC7LDuUYNLQNImSQJAQ777QXeeLZf/f/8t+gB1mBA77CZMcYQ3SnV6zD+6CMlE9exfS/uuzWnW7+2zIDUPUzn4I2NBGwK7v4k2RothYdmNKnjOWc6b5nbqg2FvTNKwgAvpOz4PCP5bfjbbTv45N27ZskQWQpfMx4Lmwi59efAljffdK7Vdrcr5amcpJVU0ewpJS0tnoDFLjVCXgMOpIsjaGWJfIEUkKWikMeKIC6q2wz3pbHj8GHCbvtE0R+PfP8xc=

**Comment by MikeBailleul** [comment]
My bad, I was actually importing a CompoundPath, which makes no sense. All good, thanks.
