### ISSUE TITLE
Reverse Y axis (turn it from downside to up)

### ISSUE THREAD

**Issue by epsi1on** [paperjs/paper.js#832]
Hi,
I've added capability of zooming and panning with mouse wheel, to create a very simple CAD designer with paperjs, but currently the Y axis is from upside down, is it possible to reverse the y direction from bottom to up?
Please let me know if my question is not clear.

Thanks

**Comment by iconexperience** [comment]
You could try scaling each layer to 1,-1 to achieve this.

**Comment by epsi1on** [comment]
Actually i'm using methods like paper.view.viewToProject(), with this solution it is not possible to use these anymore. Is there a global solution for this, like another transform on top of every other transform for rendering?

**Comment by epsi1on** [comment]
@lehni if it is not so hard, can you please add this feature into your swiss army knife?! :)
Thank you

**Comment by lehni** [comment]
Yeah what we want probably is arbitrary matrix manipulation on the view. Rotation would also be nice... I need to think of a nice API for all that.

**Comment by lehni** [comment]
I just added `View#matrix` as a way to give more fine-grained control of the view transformation.

With this in place, it's possible, e.g.:

```js
var path = new Path.RegularPolygon({
    center: [0, 0],
    sides: 3,
    radius: 100,
    fillColor: 'red'
});

view.center = path.position;
view.matrix.scale(1, -1);
```

**Comment by lehni** [comment]
And since 3a3d46692bc56f7a2ba4b58e10115b84a69da2de, all the matrix transformation functions can also be used directly on the view!
