### ISSUE TITLE
How to get a color of a pixel

### ISSUE THREAD

**Issue by cullsin** [paperjs/paper.js#833]
Hello, 

I am new to paper.js .  Is it possible to get the color of a pixel from the rendered web page ?

Please suggest me on the same.

Raja K

**Comment by iconexperience** [comment]
To get the pixel of your rendering you have to do access the data of your canvas through Javascript. There are several similar questions with good answers on stackoverflow, for example this one:

http://stackoverflow.com/questions/7373851/reading-the-rgb-value-of-a-canvas-pixel

But please ask questions like these on the mailing list at http://groups.google.com/group/paperjs

**Comment by cullsin** [comment]
Thanks and sorry! !
