### ISSUE TITLE
Curve.evaluate() should handle straight curves separately

### ISSUE THREAD

**Issue by iconexperience** [paperjs/paper.js#838]
While working on path offsetting I ran into a very strange behaviour of straight curves in some cases.

Here is a simple boolean example that creates a path consisting of straight curves:

```
var p1 = new Path.Rectangle(100, 100, 200, 70);
var p2 = new Path.Rectangle(50, 150, 300, 80);
var result = p1.unite(p2);
```
This is how it looks:
![image](https://cloud.githubusercontent.com/assets/2122773/11468137/6efd8538-974d-11e5-8063-84cc4fc77eab.png)

As you can see <a href="http://sketch.paperjs.org/#S/tZJNasMwEIWvMmhlk6A4DqElaVe9QGmgmzgLRRnbwlPJyHJKCbl7R7b7B9lWmBH2vE/vjdFFWPWGYiN2DQZdi7nQ7hTfz8pDu4RHsPgOzyrU8gV1ULYiTJZZNoeh5LHcZem28IUdkPw2so5ELKtI3P8iPHY9BabapeytCZi0+djlD6UhenLkPPcL4aujSvL1eg7Z+MhVWohRm9/SxoRf8h/t6CjLnuhjh8QZ8cRM8D0O/cUCdI26AVOC7v0ZOzAWWh4IlEfoglemqkOUluyWxCkMH5BteXuYBpIjKQltFWruzGYpXCIDvLSznSOU5Krkj35vDtJ0u8kiScc/cZ1itd7YAGdFPWeK3opoivhvaSoMr4Phdxi+JEePqmkdp+nEZn+4fgI=">in this sketch</a>, `isStraight()` returns `true` for all curves in the path (which means the curves are lines), so everything looks alright.

But the full truth is that two curves in the path actually have tiny handles. `isStraight()` sees them within tolerance, which is the correct behaviour. Here are the values for the last curve:

`[ 50, 150, 49.99999999999999, 150, 100.00000000000001, 150.00000000000003, 100.00000000000001, 150.00000000000003 ]`

As you can see from the values, there is a tiny handle at the left with length 1e-14. This handle is pointing to the left, while to whole curve (or line) runs from left to right. 

The strange thing happens if you call `getNormalAt()` for the start and the end point of the curve. Since `isStraight()` returns true, one would expect that `getNormalAt()` returns the same value for all parameters on the curve, but this is not what happens. Insteat `getNormalAt(0, true)` returns `{x:0, y:1}` and `getNormalAt(1, true)` returns `{x:0, y:-1}`. <a href="http://sketch.paperjs.org/#S/lZHNasMwEIRfRehkgxG2gmlJ6aHkXkp8rHtQnI0sspHMep1QSt+9kt2/QygUpIHVzMcO6E16cwK5ls0RuOtlIbuwT/PZkBgqcS88XMST4V5toWPjLUJWlWUhZtFJbsr8rqXWz4i+jtSJSLJKxO0vgmCckCM1VGryjiEb9OLGh4ND3AQMFP1Wkt2ZTNd1IcrlqFXeyiWrr2VTw6/4T3bZqA4T4msDGDvCPjJME8x+ul3wY0BQGGz2mUcz8maiMyg3NkzG2Z6zfKn6Z9wCPwY6GXzg1Cjt+S9WfWPxh3YE5jgE53mU6+eX9w8=">Here is the sketch.</a>

The reason for this behaviour is that `getNormalAt` (or `evaluate()`) does not distinguish between straight and non-straight curves and <a href="https://github.com/paperjs/paper.js/blob/develop/src/path/Curve.js#L1249">always uses the direction of the handle at the end point for the tangent, if a handle exists.</a> Since we have tiny handle at the start point which is pointing to the opposite direction of the curve, the normal suddenly becomes inverted.

For path offsetting this is a real problem, because the offset curve of a straight line changes side, while we would expect it to simply be a parallel line.

While we are at this we should also look why the curves grow tiny handles in the boolean operation. Maybe this is unavoidable, but of course it would be better if a line stays a line in boolean operations.

**Comment by lehni** [comment]
I completely agree, this is far from ideal. I'll have to do a proper analysis of this soon!

**Comment by lehni** [comment]
I closed this issue too early, since my fix addresses the problem of tiny handles after boolean operations, but now how `Curve.evaluate()` handles them. Reopening.

**Comment by lehni** [comment]
Looks like my merging mess closed this one again...

**Comment by lehni** [comment]
Here a [simple sketch](http://sketch.paperjs.org/#S/dZFNi8IwEIb/ypBLK5TSynow4kG8i+Cx7SHWoUrTjKTRPYj/fTNuRFp1Apkv5pmX5CaM6lBIsWvR1UeRiJoOnF+VhfpirwhLMPgLa47jAmZZAjlfP/N0PrBQz7NsFEE1WZSGgWfljoG39WF8Kw1467Hp0LheQvFYmYZCnsAgn1ZJGHCWWlyTJishsniISnPnJf9r9Ml8lT0bqxvr5FOT6UljqqmJo4cEGT21NOg2ZDulVy72c85ecPKpl4ceMwc8Vsc49l9ob60XzP/Q3qJqz3TyLyZkUd3/AA==) illustrating the issue.

**Comment by lehni** [comment]
Hmmm... Since this handle is pointing to the left, do you think it's actually right that this is considered a straight curve? I'm not quite sure yet what's the right way to deal with this issue...

**Comment by lehni** [comment]
Let me know if this works for you @iconexperience

**Comment by iconexperience** [comment]
Yep, that seems to work. It's consistent with `isStraight()` and it's a very simple and elegant solution. Thanks.
