### ISSUE TITLE
strokeWidth issue on refresh

### ISSUE THREAD

**Issue by tejasdesai** [paperjs/paper.js#844]
I have used paperjs in my application. To draw a line, I have used following code:
````
function onMouseDown(event) {
var path = new Path({
        segments: [event.point],
	strokeColor: 'black',
	strokeWidth: 20
});
}

function onMouseDrag(event) {
	path.add(event.point);
}

````
It draws a line with proper stroke width. PFA screenshot for the same:
![screenshot from 2015-12-03 19 04 46](https://cloud.githubusercontent.com/assets/6938686/11561943/c0a3ebde-99f0-11e5-975e-1c26098d5f2d.png)

However, on refresh of the page, the stroke width decreases. PFA screenshot for the same:
![screenshot from 2015-12-03 19 06 06](https://cloud.githubusercontent.com/assets/6938686/11561975/ee9b2ca0-99f0-11e5-93d8-51693de9977a.png)

Can someone please help me on this?

**Comment by lehni** [comment]
Your example doesn't work here:

http://sketch.paperjs.org/#S/ZY9BC4JAEIX/yrAXFSSi40anugZBhw7qYdVJRZ2R3VUP4n9PzSjynWbemwffDIJUjUKKe4k2yYUvEk7n/dlSYgsmYLpya/DCPbnYIVkPhpBgUqc0NMrmcALCHm7T6K7RRwazeqoYCcHS3TVckI3875Wxmks8c8VaghNXKimdTfwoUptLOOzfwegdQxpDCmlDqVX2RzkT7lSauj8Aa3/6NtaoysUzQgbR+AI=

    Line 10: Uncaught ReferenceError: path is not defined

**Comment by tejasdesai** [comment]
Please use following code:
````
var path;
function onMouseDown(event) {
var path = new Path({
        segments: [event.point],
    strokeColor: 'black',
    strokeWidth: 20
});
}

function onMouseDrag(event) {
    path.add(event.point);
}
````

**Comment by sapics** [comment]
I got an error
```
Line 11: Uncaught TypeError: Cannot read property 'add' of undefined
```

I fixed a little bit. Is this a what you expect?
http://sketch.paperjs.org/#S/bY+xCoNADIZfJdyigpTS8Uqndi0UOnRQh1NTFTWRu1MH8d3riYW2NENI/vwJXyZBqkUhxb1Gm5UiFBnnrh+Uhk7Z8hjrmJ49ZbZiAqYr9wYvPJKPA5INYHIG54QTEI5wW0p/FWELg0W7WI2EaN3ZdVyRTcK3x1jNNZ65YS3BSxuV1d7P8FHltpRw2Dt5Dlao2aW/dFoVX3TujiPcqTz3PxC2O8vTqUZVr5oRMkrmFw==

**Comment by tejasdesai** [comment]
Yes. The output is fine. But, on refresh of the page, the stroke width decreases.

**Comment by iconexperience** [comment]
The Sketch seems to work fine now. Can you say how you refresh the page so the problem occurs? Minimizing/maximizing the browser window, reloading, nothing seems to cause the described behaviour.

**Comment by lehni** [comment]
I can't replicate either. Please provide more context, used browser, steps to reproduce, etc.

**Comment by lehni** [comment]
I am going to close this for lack of reproducibility. Feel free to reopen with an actual test-case. Thanks!
