### ISSUE TITLE
Raster onerror does not exist/work

### ISSUE THREAD

**Issue by alex-taffe** [paperjs/paper.js#849]
I have an application where image URLs may be provided to then be loaded onto a canvas. Because I cannot guarantee the URLs will be right, I need a way of detecting this and alerting the user rather than an error being dumped into the console. Unfortunately, the onerror method is either not working/not implemented/I did it wrong.

    function setImage(URL){
        this.image = null;
        this.image = new Raster(URL);
        this.image.onLoad = function () {
            //this works
            //handle the image load
        };
        this.image.onerror = function(){
            //this does nothing when an incorrect/non existent URL is provided
        };
    }

**Comment by lehni** [comment]
Did you see a mention of onError? I don't think we're saying it's supported right now. But you're right; I guess it should be?

**Comment by alex-taffe** [comment]
I didn't see anything in the API but the API appears as if it doesn't show all methods. And either way, I just assumed it would be like JavaScript which uses `onerror`. (Although I'm not sure why because `onError` looks much nicer). I just assumed it used a native call to either JavaScript or the jquery library to fetch the image so the on error message could then just be passed back through paper.js
