### ISSUE TITLE
project.getItems how to only get root items

### ISSUE THREAD

**Issue by kaelumania** [paperjs/paper.js#853]
Is it possible to only receive root items in this method? When I have complex svgs and use this method, it returns all subitems of the svg.

**Comment by kaelumania** [comment]
I solved it this way
```js
          let rect = this.selectionRectangle.bounds
          let children = this.editor.document.foregroundLayer.children
          let items = Item._getItems(children, (item) => {
            if(item.parent == item.layer) {
              let bounds = item.getBounds()
              if(rect.intersects(bounds) || rect.contains(bounds)) {
                console.log('match root' + item)
                return true
              }
            }
            return false
          }, null, {items:[]}, false)
```
But thats not very clean:

1. I couldnt use the `project.getItems` method due to my last comment at https://github.com/paperjs/paper.js/issues/751
2. There is room for optimization, because line https://github.com/paperjs/paper.js/blob/2366e032653e62f3d1f34fea06af2af36aa1eb86/src/item/Item.js#L2030 always gets called. Ideally, it should be an opt-in/opt-out, e.g. if I only want to receive root elements, this call is needless.

**Comment by kaelumania** [comment]
@lehni what do you think? I could provide a PR for the switch (opt-out)

**Comment by lehni** [comment]
I agree, it would be nice to implement further filtering. The problem really is that sometimes you'd want to still walk through the children of an item, even if the function call results in the parent not being included.
One option is to stop further iterating through children if `false` is returned, but keep iterating if `undefined` (or nothing) is returned. We probably also only want to offer this control if the function is provided, not when simply matching bare properties?

**Comment by lehni** [comment]
Here's a better idea:

- I add support for `match.recursive`, default to `true`. If you set it to false, there is no recursive looping through children.
- I add support for `getItems({ match: function() {} })` as an alternative to `getItems(function() {})`, so it can be combined with setting `recursive: false`.

**Comment by kaelumania** [comment]
I agree that we have to traverse through the children, if the function call returns false. But when the function/statement holds for the parent we can immediately return and don't have to check the children. At least in my current use case this is the case. Thus there are basically two options:
1. The caller only wants to get root objects returned, if the root or any child holds the criteria
2. The caller only wants to get root objects returned, if the root holds the criteria (children are ignored)

The second options is what i currently need, but maybe the API could fit more use cases.

**Comment by kaelumania** [comment]
@lehni I like your idea :+1:

**Comment by lehni** [comment]
@kaelumania you mean the second proposal?

**Comment by kaelumania** [comment]
@lehni i meant this one:

>Here's a better idea:

>I add support for match.recursive, default to true. If you set it to false, there is no recursive looping through children.
>I add support for getItems({ match: function() {} }) as an alternative to getItems(function() {}), so it can be combined with setting recursive: false.

Could this support the use case i mentioned? 
> 1. The caller only wants to get root objects returned, if the root or any child holds the criteria

Maybe it can be solved returning all matching items (e.g. children) and then find the root of each matching child and lastly filter duplicate roots. Otherwise it could easily be baked into the `getItems` function due to its recursive nature, which would have a lot performance advantages.

**Comment by lehni** [comment]
Yes if you call it on `project` or any other group / layer with `recursive: false`,  you'd only get root items.

**Comment by kaelumania** [comment]
I think here is a misunderstanding, there are two different concepts:

1. I only want the root items, if the root item ***itself*** matches the criteria
2. I only want the root items, if the root item or any of its children or children's children match the criteria

In case 1. we can stop recursively iterating the children, but in case 2. we must continue iterating the children, but ***only add the root item*** to the result list.

**Comment by lehni** [comment]
I think I will not add support for 2. to the API. That's best covered by providing a match function and doing your own looping through the children inside it, or post-filtering of the resulting items array. We can't cover all cases and keep a consistent API... Sounds good?

**Comment by kaelumania** [comment]
Sounds like a good API :+1:
