### ISSUE TITLE
Draw path only in png area

### ISSUE THREAD

**Issue by Hsantos** [paperjs/paper.js#855]
I using de path simple (http://paperjs.org/examples/path-simplification/) to painting in canvas
but is that possible to insert  image and path  draw only png area?

**Comment by iconexperience** [comment]
You can draw the image onto a canvas and then draw on that canvas. Would that work for you? In any case you will need a canvas, there is no way of drawing on an image element directly.

**Comment by Hsantos** [comment]
I was not very clear , let me explain is possible insert a image and path draw only in png transparency area like mask?

**Comment by iconexperience** [comment]
You could have a paper project with two layers. Your image is on the top layer and the path is on the layer below. This should give the desired effect.

**Comment by lehni** [comment]
You could also create a group with a clipping mask and a path, and then draw into that. But I'm closing this issue since this is not an issue, it is a discussion / request for help, which should take place on the mailing list, not the issue tracker database.

**Comment by Hsantos** [comment]
Thank's
