### ISSUE TITLE
Possible scaling issue

### ISSUE THREAD

**Issue by aleksey-leontiev** [paperjs/paper.js#857]
Hello!

Looks like scaling value loses his value after any position changes on node.

See [Sketch](http://sketch.paperjs.org/#S/dVDBasMwDP0V4UsTFtyEURgpJYeynQc7Nj14jtK49eQgu2tLyb/PyULZZdJJ7z2J93QXpL5QlOLjhEF3IhPaNeP8rRi0YW0RNkB4gXcVOrmdkOReE8TSSAG5hN1LnsEq32e/MKvGnH0Jz6sZaI21W2ddlC4Ym0VNQ7quaez2TDoYR+DojaOTJIX5eM/uiDpIq27IXraOX5XuksdCMhEP+VgTInvnzaiQV3jaQPEvfftDD+mcaMonvVbW0CEmL2RewHIJVVVF1/E9n4zq1DtDwYtytx9+AA==)

**Comment by lehni** [comment]
It's all explained here:
https://groups.google.com/forum/#!searchin/paperjs/applymatrix/paperjs/4EIRSGzcaUI/seKoNT-PSpwJ
This question keeps popping up though. We should address this in documentation somehow...

**Comment by aleksey-leontiev** [comment]
Thanks a lot. I'll check it.
