### ISSUE TITLE
No key up event for control characters in Chrome

### ISSUE THREAD

**Issue by bmacnaughton** [paperjs/paper.js#860]
Chrome doesn't generate an event for onkeypress when the control key is active (or the alt key).

In Key.js the `keydown` function only calls `handleKey` if the key is in `specialKeys` or the `command` modifier is set. The code relies on `keypress` to occur so `handleKey` will be called to insert the key into `charCodeMap`.

But Chrome doesn't generate a `keypress` event for the key when the control key or alt key is active. So the key is never inserted into `charCodeMap` and the `keyup` function never calls `handleKey`.

**Comment by lehni** [comment]
On what system and Chrome version are you observing this? I cannot confirm that this is the case on OSX / Chrome 47.0.2526.106

**Comment by bmacnaughton** [comment]
I've run it on Ubuntu 14.04/Chrome Version 47.0.2526.106 (64-bit) and on Windows 7/Chrome Version 47.0.2526.80. I don't have a Mac.

**Comment by iconexperience** [comment]
Is there a test case somewhere? I could try to reproduce it with Crome on Windows 7

**Comment by bmacnaughton** [comment]
Here you go [sketch]. (http://sketch.paperjs.org/#S/VZDBbsIwDIZfxcoBigQVFy5UfYJdkOhOZIcuuFvUYldJVkCo7z6H0MF8iezvzy//vimqT6i2at9iMN9qqQwfYz/UDgJeApRAeIYdWwqV9Nmi0BRBblheigKtKvRBq4n07G2wTIIGi+fciAydUE3ND5k7YnrD63uf4SBwATdNICWenjvMO/56kCIB26Q+b/EKZQnzYQ6zGaTZiY+2sej8fSfH3Z9frJhEIlQpTFq9Y8Js8o71ELyu/j/K6nmGbLNebtbT7xFA01jI5T4d1m0fFV5tDx/jLw==)

To watch I just set conditional breakpoints on paper-full lines 11829, 11840, and 11847 - the three DOM event handlers. The conditional breakpoints always fail but just do a console.log (u, d, or p for up, down, and press).

**Comment by bmacnaughton** [comment]
Here's a case that doesn't use paper at all. I think it will run fine without the CSS but let me know if it doesn't.

```
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>Test</title>
    <link rel="stylesheet" href="styles/styles2.css">
    <script src="vendor/paper-0.9.25.js"></script>
</head>
<body>
    <main>
        
        <div id="canvas-view">
            <h3 id="title" class="">Testing Template</h3>
            <div id="canvas-outer">
                <div id="canvas-wrap">
                    <canvas id="canvas" class="" data-paper-resize="true"></canvas>
                </div>

            </div>
            <nav class="controls">
                <ul>
                    <li id="ctrl-start" class="button">button</li>
                    <li id="ctrl-one-step" class="button">button</li>
                    <li id="ctrl-reset" class="button">button</li>
                </ul>
            </nav>
        </div>
    </main>
    
    
    <script>
     // initialization code.
     (function() {

         function logKeyEvent(ud, e) {
             var csam = '';
             if (e.ctrlKey) csam += 'c';
             if (e.shiftKey) csam += 's';
             if (e.altKey) csam += 'a';
             if (e.metaKey) csam += 'm';
             console.log(ud, csam, e.key, e.keyCode, e.which);
         }

         document.onkeydown = function (e) {
             logKeyEvent('d', e);
         }
         document.onkeyup = function (e) {
             logKeyEvent('u', e);
         }
         document.onkeypress = function (e) {
             logKeyEvent('kp', e);
         }

         return;

     })();
     
    </script>
</body>
</html>

```

**Comment by lehni** [comment]
It's OK, I'm able to reproduce this. Investigating...

**Comment by bmacnaughton** [comment]
I haven't tested the code but it looks like the change might not generate keyup on an alt-v because the line.
```
fixCommand = browser.chrome && (browser.mac && event.metaKey
                       || !browser.mac && event.ctrlKey);
```

only checks for `event.ctrlKey`. Maybe I'm reading it wrong or that's your intention though.

**Comment by lehni** [comment]
You are right. I forgot about alt. Will address in a bit! Thanks :)
