### ISSUE TITLE
Uncaught TypeError: Cannot read property 'x' of null

### ISSUE THREAD

**Issue by EmilStenstrom** [paperjs/paper.js#867]
I had a bug in my program that was very hard to track down because of an uncatched TypeError. I suggest this TypeError is catched so that a better error message can be shown.

It seems to happen when you have a symbol that you scale to zero, and then have an onClick handler on another element. When you click **outside** of the element where youdefined the onClick you get the TypeError. Here's a complete testcase to reproduce. Click anywhere outside the black rectangle:

As you see in the example I'm using 0.9.25. I can reproduce this on latest Chrome and latest Firefox.

```html
<!DOCTYPE html>
<html>
<body>
<style>
html, body{height: 100%; width: 100%; margin: 0;}
canvas[resize]{display: block; height: 100%; width: 100%;}
</style>
<canvas id="myCanvas" resize="true"></canvas>
<script src="https://cdnjs.cloudflare.com/ajax/libs/paper.js/0.9.25/paper-full.min.js"></script>
<script type="text/paperscript" canvas="myCanvas">
var symbol = new Symbol(new Path.Rectangle(100, 100, 100, 100));
var placedSymbol = symbol.place(0, 0);
placedSymbol.scale(0);

var rect = new Path.Rectangle(100, 100, 100, 100);
rect.fillColor = "black";
rect.onClick = function() {}
</script>
</body>
</html>
```

Let me know if I missed something, or if you can't reproduce.

**Comment by lehni** [comment]
This is actually the same error as #617, which I still need to fix! Closing this one again.

**Comment by EmilStenstrom** [comment]
Thanks for fixing it so quickly, and sorry for the duplicate!

**Comment by lehni** [comment]
No worries, it's hard to track down sometimes! And it served as a reminder that the other one should have long been fixed.
