### ISSUE TITLE
unite() results in open path on compound path

### ISSUE THREAD

**Issue by iconexperience** [paperjs/paper.js#868]
Here is my currently last known issue with the boolean code. Calling `unite()` on the following `CompoundPath` results in an 'Open Path' message:

```javascript
var cp = new CompoundPath();
cp.addChild(new Path({segments:[
        [383.65000000000003, 170.15, -1.9500000000000455, 4.050000000000011, 0.05000000000001137, -0.5500000000000114],
        [383.75000000000006, 168.55, -0.05000000000001137, 0.549999999999983, 0, 0],
        [256.00000000000006, 127.05000000000001, 0, 0, 0, 0]
    ], closed:true}));
cp.addChild(new Path({segments:[
        [383.65, 170.15, 0, 0, 0.05000000000001137, -0.5500000000000114],
        [383.75, 168.55, -0.05000000000001137, 0.549999999999983, 0, 0]
    ], closed:true}));
cp.fullySelected = true;
cp.unite();
```

The second child is pretty nasty, because it runs closely along one curve of the first child, while self-intersecting.

This problem only seems to occur on the `develop` branch.

**Comment by lehni** [comment]
The problem was introduced by deafacdad026bacabe3c6f2353910db4a6c04b16. Hmm!

**Comment by lehni** [comment]
So I reverted deafacdad026bacabe3c6f2353910db4a6c04b16 and checked against the other situation that it claims to solve. Both seem fine now! I will do some more testing and perhaps revert this one then.

**Comment by lehni** [comment]
Alright, this passes all my tests : ) The nice added benefit is also that with the new code, your example here then results in a `Path`, not a `CompoudPath`!

**Comment by lehni** [comment]
Stop the clock! =D

**Comment by iconexperience** [comment]
Amazing!
