### ISSUE TITLE
Intersections of rectangles don't make sense 

### ISSUE THREAD

**Issue by ludwick** [paperjs/paper.js#870]
Rectangles sharing two parallel co-linear segments don't intersect in the way I'd expect.

Here's a [sketch](http://sketch.paperjs.org/#S/xVffa9swEP5XhF9qU8/YaU0hWTdGGWUw2Fgf9tDkQbHlWI0jBVlpWUv+953kOPKvMMGczbTBPp1O33336WS/OQxviDN1HtZEJrnjOwlP1fNW8CeSyCApCBauN5uzOct2LJGUM1Tm/OVe0NSlTBLxjAsflfSVeOhtzhBcz1igleC7LbpFjLyge3V/CKLGMy6Qq5woONQxZvD0XsdRd5dm4BhWXTpsgNP0LqdFKghzH82gutR637HMg6+UEVc/cYjkhj6ino+MQa2kbJ5vF4D6KGwFoIesPTN/oXJUN/s61QpvKQVfk580lTlkHM36Y3e8AFIquvS9AhwGsdfyTXGZfxIC/wLPx9hHk0U1rH8EkTvBKk8w73sl+6IILYk2lG6Bl0QVLoL/Sat0tOkHK5VRsCKyPRumHJAl8MgLEhR8VcVEl2jufEDdKVOw+u3YRhEtcwD6+IyT3K3Ru83hlhxOLU7Lb89EFHj7sbtocBxyoZpqdKuqedvz0+Y6yZoabTyUSYvkjgrYIu5bW0MJUZGmAwE7YhM4pTugJu7YG6KYtjQR+pGvZGHc90fNGTqPVayqd4TRKJu2dcR3sSxwsr4Y8DDSRQdlVXucpmqFuh3EoNk4DCscygE3qfoBADBbGbY0IVMQsp62OFCg9hQYo47VwDBsnWAJFB1Wf5qovcGztMJzMzIemBj18fR35NzJuaCvnElcwG5OZKlEiX20NBkk1oxGvRS0NRyZ0tQe0E08HiB7TmGzS5o0GU18lFb+VQrEKoVJCKtNwp4uwjPoNLNDNIlHRjTEahYILrEk7rvr+DTLkhaSpIZjOFqzJscrq4yuwsGtdw6KcztAiuKebkdmeJjRJYeOm1JRn8M8y0oiEa8OL8P0ykd5k2lqvSGvhqUzeot4suu6wDTQ/T+oPrYIykqagnQbffgU7fD299SkfW23ZTXvY2Z5mvbirxAp4Z+bd5kLQpCivIQ3uQLetwH2keG1jwqTzcZuv8b/oklvei1RIWR2CJXO+0fhyDpnDYTwzRJUL6R/aDbdHr6BmSY9bn9KXvcKcI6Xua39IdkHdNPu62eRN2eVuAe0zeGzw5vB5/ZSELzWWEtn+rjY/wY=)

And the code for reference: 
```
project.clear();

function showGrid(interval, size) {
    var group = new Group();

    for (var i = interval; i < size; i += interval) {
        group.addChildren([
            new Path.Line(new Point(0, i), new Point(size, i)),
            new Path.Line(new Point(i, 0), new Point(i, size))
        ]);
    }

    group.strokeWidth = 1;
    group.strokeColor = new Color(0, 0.5);
    group.dashArray = [5, 2];
   
   return group;
}

function showIntersections(label, s1, s2) {
    var intersections = s1.getIntersections(s2);
    console.log(label + "> getIntersections: ", intersections);

    intersections.forEach(function(intersection) {
        console.log(label + "> isOverlap?", intersection.isOverlap(), ", point=", intersection.point);
        var point = new Path.Circle({
            center: intersection.point,
            radius: 5,
            strokeColor: new Color(0,0,1,0.5)
        });
    });

    var inter = s1.intersect(s2);
    inter.strokeColor = 'black';
    inter.strokeWidth = 1; 
}

var grid = showGrid(50, 500);

var a = new Path.Rectangle({
    point: [50, 50],
    size: [150, 50],
    strokeWidth: 5,
    strokeColor: new Color(1, 0, 0, 0.5)
});

var b = new Path.Rectangle({
    point: [70, 50],
    size: [150, 50],
    strokeWidth: 5,
    strokeColor: new Color(0, 1, 0, 0.5)
});

showIntersections("horizontal rects", a, b);

var c = new Path.Rectangle({
    point: [50, 150],
    size: [50, 100],
    strokeWidth: 5,
    strokeColor: new Color(1, 0, 0, 0.5)
});

var d = new Path.Rectangle({
    point: [50, 175],
    size: [50, 100],
    strokeWidth: 5,
    strokeColor: new Color(0, 1, 0, 0.5)
});

showIntersections("vertical rects", c, d);


var e = new Path.Rectangle({
    point: [200, 200],
    size: [100, 50],
    strokeWidth: 5,
    strokeColor: new Color(1, 0, 0, 0.5)
});

var f = new Path.Rectangle({
    point: [225, 200],
    size: [100, 50],
    strokeWidth: 5,
    strokeColor: new Color(0, 1, 0, 0.5)
});
f.rotate(-45);

showIntersections("tilted rects", e, f);


var g = new Path.Rectangle({
    point: [300, 50],
    size: [100, 50],
    strokeWidth: 5,
    strokeColor: new Color(1, 0, 0, 0.5)
});

var h = new Path.Rectangle({
    point: [325, 75],
    size: [100, 50],
    strokeWidth: 5,
    strokeColor: new Color(0, 1, 0, 0.5)
});

showIntersections("both directions offset overlap rects", g, h);


var i = new Path.Rectangle({
    point: [50, 300],
    size: [100, 100],
    strokeWidth: 5,
    strokeColor: new Color(1, 0, 0, 0.5)
});

var j = new Path.Rectangle({
    point: [75, 325],
    size: [100, 50],
    strokeWidth: 5,
    strokeColor: new Color(0, 1, 0, 0.5)
});

showIntersections("vertical inside, horizontal offset overlap rects", i, j);


var k = new Path.Rectangle({
    point: [250, 325],
    size: [100, 50],
    strokeWidth: 5,
    strokeColor: new Color(1, 0, 0, 0.5)
});

var l = new Path.Rectangle({
    point: [250, 325],
    size: [125, 50],
    strokeWidth: 5,
    strokeColor: new Color(0, 1, 0, 0.5)
});

showIntersections("three sides colinear rects", k, l);

var m = new Path.Rectangle({
    point: [350, 200],
    size: [100, 50],
    strokeWidth: 5,
    strokeColor: new Color(1, 0, 0, 0.5)
});
m.rotate(-45);

var n = new Path.Rectangle({
    point: [375, 175],
    size: [100, 50],
    strokeWidth: 5,
    strokeColor: new Color(0, 1, 0, 0.5)
});
n.rotate(-45, n.center);

showIntersections("both tilted rects", m, n);

var o = new Path.Rectangle({
    point: [200, 400],
    size: [50, 50],
    strokeWidth: 5,
    strokeColor: new Color(1, 0, 0, 0.5)
});

var p = new Path.Rectangle({
    point: [225, 400],
    size: [75, 75],
    strokeWidth: 5,
    strokeColor: new Color(0, 1, 0, 0.5)
});

showIntersections("one side colinear rects", o, p);
```

Am I just completely misunderstanding how this works? As an example, here's a [fiddle](https://jsfiddle.net/gg2rw8p4/) using basic canvas detecting a similar overlapping rectangular area (as the top-left set of rectangles).

**Comment by lehni** [comment]
No you're right, there's something wrong with overlaps and intersections still. If you test union instead you should get better results. It seems we've been neglecting intersection a bit in the recent boolean code overhaul. I'll look into it soon!

**Comment by ludwick** [comment]
Thanks for such a quick response!

FWIW, I'm not sure what version sketch.paperjs.org is on (seriously awesome way to present paperjs for fiddling!) but I also tried this with the develop branch with similar results.

**Comment by lehni** [comment]
Thanks! You can always run `console.log(paper.version)` to find out. It's the latest release at the moment.

**Comment by lehni** [comment]
Luckily that was really easy to fix! And here is how it looks with some coloring in now:

<img width="483" alt="screen shot 2015-12-28 at 02 43 51" src="https://cloud.githubusercontent.com/assets/213275/12013006/f9ed38bc-ad0c-11e5-8b69-2377f2a12f4c.png">

I'm aware of your questions on the mailing list. I haven't found the time yet to write back but hopefully soon!

**Comment by lehni** [comment]
Oh no, I think those are not right yet!

**Comment by ludwick** [comment]
Wow that was quick (for a partial fix)! I've been sort of trying to understand the source code to try to figure out if I could fix it but it's going to take a while probably. :)

**Comment by lehni** [comment]
Be warned: the bezier based boolean operations code has been the most complex piece of software I've ever worked on... : )

**Comment by lehni** [comment]
I need to look at it again tomorrow with a fresh pair of eyes.

**Comment by lehni** [comment]
So it looks like c6b1a8067f5045e94294735a21aa2fa222fbb2a1 fixes it, but it's too early to tell if it's not creating new problems. I will do some proper testing before closing this issue.

**Comment by lehni** [comment]
And to explain why the code is complicated in comparison to what the native Canvas does: Canvas is doing these operations in pixels as it's rendering the shapes to the frame buffer, while paper.js is calculating the actual resulting bezier paths, before rendering them. The interest is in code that actually gives us these shapes, e.g. for further processing.

**Comment by ludwick** [comment]
Oh! I know that Canvas is very different (since it's just layering renders on top of each other). I just went to look at how it did things to make sure I wasn't just completely misunderstanding how intersection works. Thanks for looking at this so quickly!

**Comment by lehni** [comment]
the canvas way is fine, and super fast, if the visual result is all you need. As soon as you want to work with the geometries though, you need the swiss army knife : )

**Comment by lehni** [comment]
It looks like this fixed intersection handling for good! The only issues I can still find now are linked to the pending PR #863

**Comment by lehni** [comment]
And here the link to the [Updated Sketch](http://sketch.paperjs.org/#S/xVffa9swEP5XhJ8c6hknrSkk68YoowwGG9tDH5o8KLYcq1GkICsta+n/vpOUWP6RMMGczbTBPp1O33336WS/BhxvSDANfq6JysogCjKR6+dixzNFBUdVKZ7vJM1DyhWRT5hFqKIvZIRe5xzB9YQlWkmx26IbxMkzutP34Wg253a8EBKF2omCwyHGDJ7emzj67sIN1GH1ZcLGOM9vS8pySXj44Ab1pdf7jlUZf6WchOZJQKQwiRAdRcgZ9EraNor8AtAIJa0AdJ/1yM1f6Bz1zdshVYu3UlKsyT3NVQkZj2f9sVvBgBRLl7nXgJM4HbV8c1yVn6TEv8DzIY3QZGGHzY8kaie59QSzgdAq2RdNaEWMoQoZXhJduDH8T1qlo00/WKkaxyui2rNhyh5ZBo+CkZiJlY2JLtA8+IC6U6ZgjdqxnSJa5hj08RlnZXhAHzaHW3I4tTitvj0RyfD2Y3fRuB4KoZp6dKuredPzM+ZDkgdqjHFfJiOSWyozRsLXtoYyoiNNjwTsiE3inO6AmrRjb4hi2tJEEo0jLQvn/lZrztFZV9FWr4bRKJuxxQVlrC89kAT8tQVo/btCRnud2R1Pc73eoTmkECBNEotKO+AmcT8ADuYrx52hZwqyNtMWe0L0DgPjuGN1MBx3JzjbZ2KTAbgOz9ILz/XAeJImuTWe/v6cB6WQ9EVwhRns7UxVWqI4QkuXQebN6LiXgrEmA1Oa+wO6TocD5M8pbH1FsyajWYRy629TIF4pTBJYbZL0dJGcQaeFH6JJOjCiY6wWsRQKKxK+u0pPs6woUyR3HMNBWzQ5XnlldJkc3XrnoLj0A6Qp7ul2YIaPM7oU0HFzKg+nsiiKiigk7FHmmF5FqGwyTb035OVx6QzeIh79ui4wDXT/D6rrFkF5RXOQbqMPn6Id3gUfm7Sv/bas4X3ILE/Tzv4KkRb+uXlXpSQEacoreK9j8PYNsGuG1xFiLpuN335N/0WT3vRaokbI/RBqnfePwoF1zhsI4Qsmtq+nf2g23R6+gZkuPeF/Sl71CnCOl7mt/yHZB3Td7utnkbfgVtxHtC3gI2Q0gw/tpSR4bbBWwfRh8fYb) with the yellow fills.

**Comment by lehni** [comment]
I think we're good here! Closing until further notice.

**Comment by lehni** [comment]
Unfortunately this fix above has caused new issues with edge cases from #784:

[Case 1](http://sketch.paperjs.org/#S/lVPBbtswDP0VwZemQCKQlChKLnbaDwzoMe4hTdQ2iGsXtrMdiv77KCcd2kOw1hZgmtIjn96TXqtu85yruro95Gn7VC2rbb8r/783g3nZTE9ofpgu/zG/NF68Nl0zjfnxOXfTWJt105nzs3Yx2kSonwTEENzSEDnrCDk5jEEi0dLAPJDAkgR0UCZBkizNiix5F2JIgikKs/i75Yf6nMQGjJiYEUE4an1PNvnIQCDkKEX33qCMT+hA0YJjH8RFjymlgnaaCpEFMIpz+I/eCnQCwSNi9MIUAwdliGCVHmk/DCIeIH5qoWV1UzGhL0sAFeGC1xSIsJfITqKcqZ1gBd5M27Yf864203DMc2Kchv6Qf/ZtP9Tmasi7qw/p2+2m3XePtXnYtGNuurfrm6Z794q+6BWHWQ0hUC0TJTxpqZsrOdRYgC5qyRIsJU9ewT5BMTo461VDwRBQa4Si4QUjVCUmAO84gIRUbCS0ario4qyEYrzc+r826ukpaM3oq7SQVXcA55TlSg30ruw5BmCFC3/fjvv2mL/kx5DHYzupIfMlsvtuysOYt9NiNqqsarrTGvuwb9u5/tm+OV6oKXjiZ4mvb/Rm3g95c3jptdRY1eu7t78=):

```js
var path1 = new Path({
    segments: [
        [388.9213889025063, 223.3215931867822, 0, 0, 120.27613015930797, -2.2436869719875574],
        [597.6181955110758, 242.94850207232983, 0, 0, 0, 0],
        [628.0354673841999, 243.03685701873312, 0, 0, -0.031041118475286567, 10.686285016774008],
        [419.2789142850017, 364.27077547853787, 0, 0]
    ],
    closed: true,
    strokeColor: 'red',
    strokeScaling: false
});
var path2 = new Path({
    segments: [
        [568.0357205119291, 242.86257201242702, 0, 0, 0, 0],
        [576.294245114903, 263.4873716612576, -0, 0, 0, 0],
        [619.5200435607698, 221.87571045051882, 0, 0, 0, 0],
        [628.0354673841999, 243.03685701876972, 0.030302631585300333, -10.432051860541975, 0, 0]
    ],
    closed: true,
    strokeColor: 'blue',
    strokeScaling: false
});
var result = path1.intersect(path2);

result.fillColor = new Color(1, 1, 0, 0.25);
```

[Case 2](http://sketch.paperjs.org/#S/pVPBbtswDP0VIZemQCqIpChSLnbaDwzoMenBTdQ2iGsXtrMdiv77GCcBlnYYCkwQDIkmH5/eA99mbf1SZtXsblfG9fNsMVt3m8P9Z92713p8BvfNteWX+2Hn+duqdbaG8vRS2nGo3PIYOKwlafIxZIrEHDFFWTiU4IUCJs4p5pSEFy5MW8RHSDkQgnJMAAsH7EUEVNS+iUn4fvEHPKP6RAwxMytrMnTNFklq4ISBDg1vAL0SU0KIUZkl6MIZbgy2DTqkiOFE4hKdyYORYQDJRsOwKEZ7j4JEggAS8Mx9Kj7WnjHWTTeUTeXGfl9OoWHsu1353jVdX7mrvmyuLn7cretm2z5V7rFuhrJq369vV+1ZdPyy6B9UYf0si55J3wRPwFFBSTQkTGGSwkMECEgAmJLZpB91R58DCyVBtUqTATN7IspRErKa2GQxT1kxmFLRFEPI0RpGDyEBZ7ArKkb4m/ISvflNweA0iKUQsudMmgUZKZBcCP8v1/Jn14L8j20Pzb580be+DPtmNOOmqfHbdiz9UNbjfDL0kLVqjzn+cds0U4eTzdN5fhiBI0uPfH1ro/jQl3r32hnUMKuW9++/AQ==):

```js
var path1 = new Path({
    segments: [
        [386.4093435542647, 270.73026596496675, 0, 0, 77.41690321854611, 15.777187877165375],
        [528.635149558586, 289.6368596320347, -12.835362144855708, 5.740740187064205, 0, 0],
        [553.1321511797777, 344.4081743101702, 0, 0, 0, 0]
    ],
    closed: true,
    strokeColor: 'red',
    strokeScaling: false
});
var path2 = new Path({
    segments: [
        [528.6351495585858, 289.6368596320348, 0, 0, -0.31548183780626005, 0.14110231126664985],
        [522.9057367288372, 295.33394762583623, 2.3982010141742194, -4.106159119428241, 0, 0],
        [574.716309478071, 325.5938972523037, 0, 0, 0, 0],
        [553.1321511797779, 344.40817431017007, 0, 0, 0, 0]
    ],
    closed: true,
    strokeColor: 'blue',
    strokeScaling: false
});
var result = path1.intersect(path2);

result.fillColor = new Color(1, 1, 0, 0.25);
```

**Comment by lehni** [comment]
This time the fix is solid.
