### ISSUE TITLE
Failing boolean unite() case

### ISSUE THREAD

**Issue by lehni** [paperjs/paper.js#871]
[This example](http://sketch.paperjs.org/#S/hVVNjxNHEP0rI1/YiFGru/rbiFNyHCRG3MAcjHciHJyx5Z0FrRD/nfeqx2EPUbJaWeXq6ldVr161v2/m/d/TZrt592VaDp83/eZwvuf3r/trd9kvn133upunb91b2Hffd3OHP/r/2C/7bbfbvPEumdRLSiaM3svN7n3wpvSSxZTRxwirGul9kl5KpS/V3lvLSMTgxHmTRp8jPZJwd7WDJXKzY1A/cYAGjIJ8vnh+JseIGkdGSR9sq0LwGYDN6izigmhOx+rUHqXm1Ssl0qvRkgOjFUVSZl5gS3JrPonFtDrSKLFVF9Xfqna//NoN44vmFaCwY6lV2dLPwn4kZ/DEOCnsjOyBE7AkN1Z/sf2+A/fg1ZN5xkuzFREIIWkFZEWiVhAURzFFqubAmZAtb9HhKK5qvZlxzQ6R0c1OiiKR8WRqFO/AUFBsTj64iozKvveai9lD40I7CtGiB0eWo8VEVgt5yAIiMdPMOx45ciKSg4IGD2aeWaJqoxV09tkrNlSV2WPIovVqTUU5hAJDFU4AN4BfC72aP6IDMhubBb7JcfNCG/iMVtYOBLbV+VhFSWQhax5Fp1KQv+hMknZXbC+qzYDayiCSbzamUDQ6c6Zeu62qg0AOo9NMkTONDtGq9qj8i2ow4j71q370kqivZo2t+9Wruo7U8hhsRUanGwILOxEGWoIpibL7zNKKOYfU7HU6EpX16BCLffNhrb+xqNb73aZvr8Wfx9Pp9/PpfN12L67T/YvVfb7sD8fladtZE3fzj99e7ebdfHt15H9fHWyTExW5zYMXKL7J3A26eq5tFOh22URMnXrECDFUiw32Bdd6h/GlqIpIaXS8UFWJEnqHEWa0mIx3OArM5pM3vuAompj02SoBZ1khITMPRAwagTWYHAaBVJzjVgBx4LB9JetGBN+8cVkjo4MQwAIwksFbxG1DIBEtd69oWTkbcqtYKnjk5jXHBxG3fU9IniXmwRlK152FD4tqKt/IwEp8FObx4ozHoBGSeQ1YccAjZyw6iPiGMwol6sZKHYLHkkKRFenyENiP6LsW/cCHsJT2ygPl+Xj+XQqfTo/Tf2vhOH0zh2lepivUcLme/5oOi9kfluPXadg/TVdzOT8cl+N5ftWEc50eGMgfLfM4H5fpTqVENByZf5Kv2lL7zvUd/m3P1LfIG2738nX3AUPE4ccV4/F0eno3nVDJdA+c5fo44RJ+Nj9dp/2Xy/k4Lw+b7YePP34C) currently fails on the `develop` branch:

**Comment by lehni** [comment]
@iconexperience so this is a failing case because I removed the line in `#resolveCrossings()` that enforces `Path` items to always be clockwise.

**Comment by lehni** [comment]
Turns out it's missing an intersection in that orientation. So not directly linked to clockwise.

**Comment by lehni** [comment]
And it boils down to this failing intersection: [Sketch](http://sketch.paperjs.org/#S/jZJPT8MgGMa/CuGyLmFv+Nd2rfE0PXgwMfFoPTDGtmYVFsr0sOy7W1oXMdHE50Dh15f2eV44Y6veDK7x88EEvccEa7eJ63fl0VGFPUO3yJoP9DTMs3Nj0aDI71RQNWrwI2cVSCJkDoWmhElgIhGXiEGVElEywkvIU0QFyqGsEi0FkRRYiqoGk+n/ffDuYFauc75GM282s8Ze5jeNbezVNv+PbT74LgUspaZQ8CJRzsmCA6cJkhWPUQqaqCzJQgLlSRTGkSSLHKRM0/zlfd2dzE/zrQ3G94P7sfmwM+FhJEaH1tk+G8PFcj2sXGegc7ts2hTpNIOt8/dK77PtyY77poo5+urEtTOwar3uzLVBUdrEynryAUc3PMn3W6827amvkUjYb6cR+RhqHIZbtfZGHcav9bh+eb18Ag==)

**Comment by iconexperience** [comment]
Does it work with #859 implemented?

**Comment by lehni** [comment]
And some good news: @iconexperience's #863 fixes it already!

**Comment by lehni** [comment]
Haha, good timing!

**Comment by iconexperience** [comment]
So what about the `resolveCrossings()` code?. I have become a little confused recently.

**Comment by lehni** [comment]
These variations also made trouble, just for reference:

[Sketch 1](http://sketch.paperjs.org/#S/hVVNj9s2EP0rgi/ZogJBDr8d5NQeVaBCbolzcLwq4saVDa82wSLIf+97Q3k3h6BdLKQhOXoz8+YN/W0z7/+ZNtvN28/Tcvi06TeH8z3XX/bX7rJfPrnuTTdPX7s/Yd99280d/rj/+37Zb7vd5g/vkkm9pGTC6L3c7N4Hb0ovWUwZfYywqpHeJ+mlVO6l2ntr6QkfnDhv0uhz5I4kfLvawRK52THoPnGABoyCeL54PpOjR40jvaQPtmUheAZgMzsLvyAa0zE7tUeped2VErmr3pIDvRVFUmZcYEtyazyJxbQ80iixZRd1v2XtXva1GvoXjStAYcVSq7Klz8J6JGfwRD8prIzsgROwJDdWX9h+14F78OrJPP2l2YoIhJA0A7IiUTMIiqOYIlVj4EzIlreocBRXNd9Mv2aHSO9mJ0WRSH8yNYp3YCgoNjsfXEVEZd97jcXooXGhFYVoUYMjy9GiI6uFOGQBnuhp5jceMXIikoOCBg9mfrBE1UYraO+zV2yoKrPGkEXz1ZyKcggFhirsAL4Afi3c1fgRFZDZ2CzwTY7bLrSBZ7SyViCwrfbHKkoiC1njKDqVgvhFe5K0umJ7UW0G5FYGkXyz0YWi3pk99VptVR0EchidRorsaXTwVrVH5V9UgxHfU7+6j1oS9dWssVW/7qquI7U8BlsR0emEwMJMhIGWoEui7P5gacbsQ2r22h2Jynp08MW8+bDm31hU691u07fb4q/j6fTb+XS+brtX1+n+1bp9vuwPx+Vp21kTd/P3X17v5t18u3Xk/24dZKCzkFE+pCdxXSG4GGTuXTEeYsSLK0x38b1Y0I35BWtRRofWJnxH3l3vqjPUHHQYRlfiqh4HniMuKogI0+/wspQ8hqLirBI1iDe2NDiKHYSCDWRjIbkoJqZBXDQVZIM2nwZiCqSL0bQVK7woU6C4wUMLHmcA81xVg8suJHxXB8mcqYA7xUMiEUJBcEybB+UhqyOyJyOtpIDZdRzwbCoCYJMXGEaZAwRemGXkwmXkihPHBWojIGYtY1iYAO+FQCQdLtCI6YNgfGT5GizBM+JyhR5QcA3rSu8/Ky9n2biqq5wGz9khzeArYKW/DkCOMgjq1f7Cn5UWvJ77+9z4nyvs4+lx+m+JHaev5jDNy3SFyC7X89/TYTH7w3L8Mg37p+lqLueH43I8z6+bHq/TAx35W2ge5+My3alCiYYj8xx8lazad67v8G97hr553nC7X99078Xy8MOK8Xg6Pb2dTshkugfOcn2c8BF+jT9ep/3ny/k4Lw+b7fsP3/8F)

[Sketch 2](http://sketch.paperjs.org/#S/hVPBbpwwEP0Vi0u2KrKwx4Ahyqk9ulJXuTXkQFhHIaGAWG+iVZR/7xtgm01VtQjZzzPjmTdv4DXq658+KqPrJx+ahyiOmmHH5+d6EmMdHpS4Er1/Ed+BN69VL/Cw/Wsd6lJU0TdtSdpYZanUbsFa54yNldlHnObvMWeYrJV2u2CTkNSxthnijdKwFtLERid8p0AN4FRmW0pUbCiBjxSvhrTUW1IF5yBYiXh3lBbve4LdEEcnZkuULgixcwZUhlUvVs28tGYWCWqvmamwvKp5ZTaw5zNWiFyxBT+34KVLrn2GZkVW/xmeFfxRRfGi8X3bdV+GbphKcTH53cVqHsa6acOxFIlMq/7t02XVV/1pVvp/s+K+MsiLlorMqQKKq7kR67TKZ5mzzOncSMhHWS6VXdlRnkhClIUN+vAVJo4xqThFF0ahOS3zApGYYOFMRjLXUEPJwvx5wrBwj/ircAROig9K6tTxdC0Yzpv7wPfv2tx1B/9vcVr/IhvfBz9BnnEaHn0TZN2E9tm7+ugnOQ77NrRDf7koOfk9B/K3Lw99G/xm1pazwSV/F1/FnvFGxQJvEnPpU+Qpr/h8JW7QA5y3a45D1x2vfQcmfoc8YTp4XMLfdzf5+mkc2j7so/Lm9u0X)

**Comment by lehni** [comment]
@iconexperience `resolveCrossings()` is definitely fine! I just need to implement your index suggestion now.

The only issue I am currently aware of now after fixing overlaps in `intersect()` is the fat-line edge cases.

**Comment by iconexperience** [comment]
Aaah, good news. You are moving at a very high speed, I could not even tell if your posts mean good news or bad news.

But what are those **the fat-line edge cases**?

**Comment by lehni** [comment]
I'm sorry for the speed! With edge cases I just meant #859

**Comment by iconexperience** [comment]
Great, thanks. I am working on this.

**Comment by lehni** [comment]
Some update of what I'm working on (completely in the wrong place, but because it's so crazy that I kinda need to share it :)

I started implemented boolean operation unit tests. But because there is so many ways to get to the right result, I thought that a pretty decent way of testing against regressions is by comparing the rasterized output. So I added that to QUnit.js through Resemble.js. And the result is super sweet, image diffing included! Here a first screenshot:

<img width="408" alt="screen shot 2015-12-28 at 22 18 58" src="https://cloud.githubusercontent.com/assets/213275/12025673/7f89563c-adb1-11e5-968e-5820e5ac6a00.png">

**Comment by iconexperience** [comment]
Very nice. Do you allow any errors, or do the results always have to be 100% identical? Probably depends on the test.

**Comment by lehni** [comment]
At the moment it's 100%, yes, but I think it has some built in tolerance in the handling of antialiasing. Once I hit issues, I think I'll relax the tolerance on a case to case basis, through an option passed to the call. So far it's been working really well : )

But I made a tricky discovery yesterday, that made me a bit weary: I realized that the current implementation of  `Path#reduce()` is a bit too aggressive in its treatment of consecutive collinear straight curves:

The idea was to merge multiple following straight lines that go in the same direction to one line, and it does that, but it also removes lines that go 180° against the previous / next line, and that's certainly changing the geometry. But not filtering these out opens a huge can of worms again, as your test suite produces dozens of errors with it again. Most of them appear to happen in the removal of self-intersections in `resolveCrossings()`, but I haven't quite figured out what's happening yet, as the geometries are very often very complex. Perhaps I'll need your reduction magic here soon.

You can find the new code in the https://github.com/paperjs/paper.js/commits/boolean-fix branch, the changes are in e3e9ee75e193fab2ad130abdefbb879c4185448c
