### ISSUE TITLE
Path disappears during substract() operation

### ISSUE THREAD

**Issue by iconexperience** [paperjs/paper.js#875]
This one is bizarre. In the subtract operation of the following example, the original path (the small orange circle) is deleted, although it does not even touch the path that is subtracted.

<a href="http://sketch.paperjs.org/#S/dVHLbsIwEPwVy6dUDVZIIIFUnLijSj0mORhnG6IYO1qb9oD499oQ2vCo5V3Z3pnxPo5U8T3QnH50YMWOhlTo2t+/OBLRkxVR8E3eud0FRwPNHpQ1eVFiqYhbxXS+YFlIksWSJSGJznsyY8t5SLyvQnIPnUUZi39BI+wTRpay9J4x9pN/GEM6D9BnjJsCbrC+muoKdBwhtYE6t3iA08ubD4ieGYu6g7WWGl2vSqqRqwZKeo57830ct5GtWxQSgjh1+kns3DSKLnI9+2yl/NNCqAchL+Lf/IeHrUUubNAPOWhltAQmdRMgE5Ibs3ETJa9OIHfmDsiuk7tQ3JC3CLzrdeveaF5Upx8="> Here is the sketch</a>

```javascript
var cp = new Path({segments:[
    [158.7, 389.3, 0, 0, -4.95, 4.95], 
    [158.7, 407.2, -4.95, -4.95, 4.95, 4.95], 
    [176.6, 407.2, -4.95, 4.95, 4.95, -4.95], 
    [176.6, 389.3, 4.95, 4.95, -4.95, -4.95], 
    [158.7, 389.3, 4.95, -4.95, 0, 0]
    ], closed:true});
cp.strokeColor = "orange";

var p = new Path.Circle(260, 320, 100);
p.fillColor = "red";
var r = cp.subtract(p);
console.log(r.className + ": " + r.segments);
```

![image](https://cloud.githubusercontent.com/assets/2122773/12039383/43164778-ae60-11e5-9d5e-12da04f7802e.png)

The result of the subtraction is an empty path.

This has something to do with the shape of the original path, but there is nothing special that I can see. If I set the handles of the first segment from 4.95 to 5, everything works.

BTW, this bug is not new to me. I have seen it for a while, but I was sure it was caused by my code, so I did not examine it until now.

**Comment by iconexperience** [comment]
Hmm, after `preparePath()` the first segment has a handle-in and the last segment has a handle-out added. Not sure if this is correct.

**Comment by lehni** [comment]
I think it merges the first and last segment to one, since they're in the same spot anyway and just close the shape. Should be fine!

**Comment by lehni** [comment]
Bizarre indeed. For some reason, the winding contribution of every segment is 0, not 1! How is this possible? I guess some imprecision in `getWinding()`?

![screen shot 2015-12-29 at 20 19 45](https://cloud.githubusercontent.com/assets/213275/12040485/a5e106f0-ae69-11e5-99ae-68c2ce92f90b.png)

**Comment by lehni** [comment]
If you look at the code of `propagateWinding()`, you will see that we do something quite strange there, which appears to fail for this particular path:

We sample the winding contribution in three different spots along the curve, to find a value that works. This code is based on work by @hkrish and I'm not quite sure why we have to do this, but one theory (and also perhaps the reason why it's not working here) is, that due to imprecision, we don't get the correct winding for every point *on* the actual curve. Some of these end up outside of the shape, instead of inside. Now I have a feeling that in this particular case, all of them end up outside.

https://github.com/paperjs/paper.js/blob/develop/src/path/PathItem.Boolean.js#L476

**Comment by lehni** [comment]
To further confirm that suspicion: I temporarily switched from 3 to 4 samples, and it works fine in this case... But there are probably others where it doesn't. Oh dear.

**Comment by iconexperience** [comment]
To be honest, I do not understand a word. But I will look into this part of the code and try to figure out what is going on.

**Comment by lehni** [comment]
More forensics and insight:

I realized that the amount of sampling subdivisions along a chain of segments (3) leads to the segment chain to be divide into 4 even bits. Now a circle is also made out of 4 curves of the same lenght. This then leads to each sampling point sitting directly on a segment.

There is code that is supposed to handle this (https://github.com/paperjs/paper.js/blob/develop/src/path/PathItem.Boolean.js#L485), but in this particlar case (a circle rotated by 45°), all these points are either on perfectly horizontal or vertical parts of the curves:
```js
// If the selected location on the curve falls onto its
// beginning or end, use the curve's center instead.
if (length < epsilon || curveLength - length < epsilon)
    length = curveLength / 2;
```

And indeed, I can produce the same problem by using a rotated circle: [Sketch](http://sketch.paperjs.org/#S/lZJNawIxEIb/SsjFLcq6a7uXFQ9FKPRSChZ6cD3E7HQNxmSZzNaC+N87UWm1INhAvuZ5ybwzZCed2oAs5WwNpFdyILWv471ynwpFq2iVi4lwsBWvfE6nBrWFZFc5wUODI8BSzPMsGwheFoMjQFWbLpSiyE6BQOjXMPXWs7yHUPcuwEwra1xTig9lA1Rufzeu3CF5ip4UQfJQxNCvq9ENrkb5v1wtbQc32Krc1rjab9PAFJ6UJo9sJkuLsRgOec/iKMY/OoIvenSNBVbdn8URWo/0zhfOERgSdvAXP8daAmgy3l3TzKDZcM3X8BsqDWcwthAPgWOHQ7ckllBy6GsskWna+mBiUtGfiHnsY54tGGm24S2k1jdJlGmrQnjhPyT6opIlTz5EEE6mUguuoVV8ln/XEkGtW28YyHK+2H8D)

Rotate by one degree more or less, and it will work.

**Comment by lehni** [comment]
What if we use the curve's derivative do determine a good place to sample the winding contribution? That should work, right?

**Comment by iconexperience** [comment]
We can even calculate the inflection points, I have the code ready.

But I still do not know exactly what is going on here.

**Comment by lehni** [comment]
I don't understand 100% either, but once all the paths are split in all the crossings, any sequence of segments that has no intersection / crossing (the sequence is called 'chain' in the code) , is guaranteed to have the same winding contribution along the way. `propagateWinding()` calculates this and then assigns it to all the segments of a chain.

**Comment by iconexperience** [comment]
What does "winding" or "winding contribution" mean here anyways? In my desperation I just watched great presentation by Cary Clark (https://www.youtube.com/watch?v=OmfliNQsk88) again, and he uses this to determine wheter a point is on the inside or outside of a path. Are we trying to find out the insideness or outsideness of the curve chain?

**Comment by iconexperience** [comment]
I think if I manage to stare a the code for twelve hours without break, I will understand it :smile:

**Comment by lehni** [comment]
The way I understand it, it is the overall winding number of the path "next" to the chain of curves, that the chain is part of. It is then used to determine if any given segment is going to be part of the boolean result or not.

**Comment by iconexperience** [comment]
I thought something like this, but there is always a left and a right side of a path, and they have different winding numbers.

Anyway, I just found that the calculated windings are actually 0, 1, 0 (not all 0 as I thought). So if we divide the winding sum by the number of found non-zero windings, we would be fine here. But this is more a hack than a solution.

**Comment by iconexperience** [comment]
Maybe we simple need to extend 

  `hor = curve.isHorizontal();` 
to 
  `hor = curve.isHorizontal() || Numerical.isZero(curve.getTangentAt(length).y);`

This way the horziontal points would get winding numbers.

**Comment by lehni** [comment]
Indeed! Gee you learn fast!

**Comment by lehni** [comment]
But do you think the sampling in multiple places is still required? I would love to not do that...

**Comment by iconexperience** [comment]
I have no idea. My suggestion will certainly not improve performance, so I would rather find another solution. Let's keep looking and thinking...

**Comment by iconexperience** [comment]
Why do you think it is not necessary anymore? What has changed since Hari wrote the code?

**Comment by lehni** [comment]
Well I wonder if this was the main reason for it... There is no reason really why the winding contribution should be different in any point along such a chain.

**Comment by iconexperience** [comment]
What do you mean by **this**? The horizontal stuff?

**Comment by lehni** [comment]
Yes. Also, Hari's code was sampling in random places. This was the reason for changing behavior between executions. I implemented the change that samples in equals positions, and then averages the result.

**Comment by lehni** [comment]
This is how isHorizontal is currently defined:

    isHorizontal: function() {
        return this.isStraight() && Math.abs(this.getTangentAt(0.5, true).y)
                < /*#=*/Numerical.TRIGONOMETRIC_EPSILON;
    },

I guess we can skip calling it now?

**Comment by iconexperience** [comment]
Yes. And just for the record, there are also really horizontal curves defined, those have winding 0. They are really v[1] === v[7], no tolerance.

**Comment by iconexperience** [comment]
Ah, I remember the random results, that was funny.

Where I see a problem is if two curves run vertically really close, like this:

![image](https://cloud.githubusercontent.com/assets/2122773/12043035/f3042798-ae80-11e5-9444-729427a8e41f.png)


If I remember the `getWinding()`function correctly, a point on the green line may get located outside the red path if the distance is less than `2e-7` or something. If you ask me, the `getWinding()` function is not really stable yet, this is not bullet-proof yet.

**Comment by lehni** [comment]
Yes but this is not about the winding of curves, it's about the winding of the path "next" to it!

And yes this must be the reason for the sampling!

**Comment by iconexperience** [comment]
But why is the tolerance used at all?

**Comment by lehni** [comment]
So that points on curves are considered inside the path, I believe?

**Comment by lehni** [comment]
Reduce it and you will hit all kinds of issues.

**Comment by iconexperience** [comment]
Yes, I think they should be inside the path (just a feeling). And yes, I tried to reduce them and it all blew up.

**Comment by lehni** [comment]
Yes I think so too. Also, they need to be inside, as otherwise we wouldn't be able to propagate the winding contribution the way we currently do : )

**Comment by iconexperience** [comment]
Oh, while we are at this, I never understood the `testContains` parameter of `getWinding()`. Do you know anything about this?

**Comment by lehni** [comment]
Me neither! Hari implemented it. We might be able to remove it now, perhaps not required any longer. Let me try.

**Comment by lehni** [comment]
I need to call it a day, been at it too much lately. Let's keep this issue open for a bit longer, to test if 6aa9f94f93eb987274e4bc2761f3fdee714da324 introduced new issues and to figure out this `testContains` thing. But my big worry is still #874. That's a total bummer that didn't need to happen now...

**Comment by lehni** [comment]
(From running tests it really looks like `testContains` won't be missed : )

**Comment by iconexperience** [comment]
Alright. Thanks for all the explanations and your time. I hope I can assist on #874.

**Comment by lehni** [comment]
That'd be great! I think we need to rethink the resolving of self-intersections all-together : /

**Comment by iconexperience** [comment]
I am not sure if removing `curve.isHorizontal()` is correct, because we can still get wrong results for the tangent due to #838. But this is just a theory, I do not have a test case that shows any problems.

**Comment by lehni** [comment]
I don't think it makes a difference since we're checking the y-coordinate of a normalized vector. But we might want to check against TRIGONOMETRIC_EPSILON as well there. I am currently getting 3 new failing cases in Hari's massive test suite, haven't investigated yet.

**Comment by lehni** [comment]
The rare failing cases are due to our change in the handling of orientation in `#resolveCrossing()`. Will investigate in a bit.

**Comment by lehni** [comment]
I think we can close this issue now, yes?
