### ISSUE TITLE
Del and Backspace keys no longer work

### ISSUE THREAD

**Issue by tjunnone** [paperjs/paper.js#876]
In Paper 0.9.25, hitting the Del key produces a
{event: KeyboardEvent, type: "keydown", key: "delete", character: ""}

On current 'develop' git head (6aa9f94) it's missing the key info:
KeyEvent {event: KeyboardEvent, type: "keydown", key: "", character: ""}

Seeing the same issue with Backspace as well, running Chrome 47, Ubuntu Linux 14.04.

Probably related to the refactoring in https://github.com/paperjs/paper.js/commit/a3546e7a79aa3bee66e0f13ef7952c1bc71378c4

**Comment by tjunnone** [comment]
Oh, apparently there was a glyph in the key value, just not one Chrome or the Github preview box could show.

**Comment by lehni** [comment]
Thanks for spotting this! Does ae002be90fcd90a5274a393f8c00dafcab740060 address this on your system?

**Comment by lehni** [comment]
PS: I think the glyph was `'\b'`, a.k.a backsapce.

**Comment by tjunnone** [comment]
Indeed that fixed the problem, thanks!

**Comment by lehni** [comment]
:+1:
