### ISSUE TITLE
Path completely disappears in subtract operation

### ISSUE THREAD

**Issue by iconexperience** [paperjs/paper.js#878]
Unfortunately another issue. This happens fequently if horizontal edges of two paths are close to each other.

```javascript
var p1 = new Path({segments:[
    [431.90000000000003, 479.99999999999994],
    [128.00000000000003, 370],
    [80.00000000000003, 479.99999999999994],
], closed:true});

var p2 = new Path({segments:[
    [400, 480, 10, 0, 0, 0],
    [140, 480, 0, 0, -10, 0],
    [300, 300]], closed:true});


var r = p1.subtract(p2);
p1.strokeColor = "red";
p2.fullySelected = true;
r.fillColor = "yellow";
```

<a href="http://sketch.paperjs.org/#S/hVFfa8IwEP8qIU8OupC0BduOPe0LCD62fYjpOaWxKddUEfG772LnVhzM43KQ/P7wO3LhnT4AL/i6BW92POLGNeF+1Mh6xd5ZBye20n63uAzweYDOD0VZYdUxqjJNlMjlrJKIpctc5PNK6+hHoOJMyAdBspQzRib/EP5zrCNmrBugKTyOcH15C0A4twXipwtISf4ZDUXnu+d50zs+9at6ICTBgEb9NNA9FFKmXolh3HjUxi/6eOKEN4+uhQ9nXSBVHKGp+ATGYjtae16DBeOhITjY3zAU2721v6ozWOtOJKTf3CDotnd72poXZX39Ag==">Here is the sketch</a> and here is how it looks (yes, the font is Comic Sans)

![image](https://cloud.githubusercontent.com/assets/2122773/12057024/3bd2d458-af3d-11e5-9852-0c54159889f0.png)

The problem goes away if the handles are removed or if the lines at the bottom have the same y value (currently the line of the red path is slightly higher).

**Comment by iconexperience** [comment]
This looks suspiciously like #865

**Comment by iconexperience** [comment]
Four intersections, but only two crossings are found. After removing the handles, four intersections and three crossings are found.

**Comment by iconexperience** [comment]
Interesting, if I remove only one handle I get three crossings, but the operation still fails. < a href="http://sketch.paperjs.org/#S/hVHbioMwEP2VkCcLEuIFqpZ96g8s9FF9sHGq4jSRJG4ppf++iXtzL2yHzMDknDOcSW5UNmegBT2MYEVPQypU6/uXRpMpIk9EwoU8N7YPbga6M0hrirLSlSQuyjSJWM5XkYQk3eYsX0dah5+CKM4Y/yFItnzFyPgvwn8T65AIVAbawuoZ7pudB3wuC8QPF+Dczc9ciVy+n7Xf9AP/E0683JX6oR2hpFEIDFUXTBHrwO61MmaQnQmmeMMQZGf77/a1c++4Zj5a3QjreQvu76xWI+wVKk+qqIa2om9gzE4z4vUACMJC62BvZcE0Ow2IX6orIKqLE7p/P2poxkkN7n1oUdb3Vw==">Here is the sketch</a>

**Comment by iconexperience** [comment]
The problem here again is that the `winding` for all segments is `0`. So this issue is actually related to #875

**Comment by iconexperience** [comment]
Unexpectately rotating the paths by 90 degrees does not improve the situation. <a href="http://sketch.paperjs.org/#S/jVLBboMwDP2VKCcqMZQAWoFpp/3ApB6BQwruWpESFMyqquq/z6FlQ53QZtmWYr9n+0m58FYdgWd80wBWe+7zytTu/aks6yR7ZS2c2LvCvXfp4eMILfZZXtiiZWR5HMkgFTOLfBav0yCdW1z63wQZJoF4IETP62VCIn7hlxaUPqu06aHO0A5wXb244jxGTeGfmoSgHQklSXH3uYR46t/8ST4AIjcgFKJcPKiTgTWoELyUoOM15tCiNzIprW7QLvwXbJJmSRlN7octWlWh14X3MVRDaxp4M9o4UMEt1AWfduwGrc8b0FAh1NR2x449G+wOWv+wzqC1ORGRvsnWgmo6d07Ps7y8fgE=">The path still disappears.</a>

**Comment by iconexperience** [comment]
So I found that in the original, failing example for all intersections `overlap` is `false`. If the set the exact same y value, `overlap` becomes `true` for two intersections. More specifically, the function `getOverlaps()` in `Curve.js` always returns null in the original example, but finds two overlaps if we set y identical. I think this is not correct, `getOverlaps()` should be using a certain tolerance and find the overlaps in the original example, too.

**Comment by iconexperience** [comment]
The problem is that our check for overlapping handle bounds in `Curve._getIntersections()` does not allow any tolerance at all. This become a problem in cases like these, if curves are lines and completely vertical or horizontal. I think we need to allow a certain tolerance here.

**Comment by lehni** [comment]
Watch out when looking at winding values: They are supposed to be the winding of the boolean result, so when you subtract, a whole lot of segments are supposed to have winding 0.

Good observation about the bounds. I shall give it a go now!

**Comment by lehni** [comment]
So I deactivated the check and there's the result! Now adding tolerance : )

**Comment by iconexperience** [comment]
Code size should almost be the same, because you can delete the equals signs :)

```javascript
if (!(	max(c1p1x, c1s1x, c1s2x, c1p2x) + epsilon>
	min(c2p1x, c2s1x, c2s2x, c2p2x) &&
	min(c1p1x, c1s1x, c1s2x, c1p2x) - epsilon <
	max(c2p1x, c2s1x, c2s2x, c2p2x) &&
	max(c1p1y, c1s1y, c1s2y, c1p2y) + epsilon >
	min(c2p1y, c2s1y, c2s2y, c2p2y) &&
	min(c1p1y, c1s1y, c1s2y, c1p2y) - epsilon <
	max(c2p1y, c2s1y, c2s2y, c2p2y)))
```

**Comment by lehni** [comment]
Yes exactly, already on it.

**Comment by lehni** [comment]
At the same time, I think we can start checking for start / end points with GEOMETRIC_EPSILON again further down, since we now handle line intersections separately before. Don't you think?

**Comment by iconexperience** [comment]
I do not know much about which epsilon where to use. I think you have been tinkering with these values a lot in the past, so you probably know best.

**Comment by lehni** [comment]
So now we have some new edge cases in your test suite, @iconexperience: One caused by better fat-line clipping finding more intersections, the other by better bounding-box checks finding more intersections. 2 tests failing here now: 244, 5296

**Comment by iconexperience** [comment]
Adding the tolerances for bounds checking was correct, I am sure about this. And the new fat line clipping may still cause problems, I suspected that this is not the final version.

Even though there are new glitches, I think the current version of the boolean code is really great. My little real world app (cannot show at the moment) almost runs without flaws. We will certainly try to fix the new glitches (and I am confident that we will), there will be a few new issues coming up (they always do), and there is the big one about self touching points, but wow, the boolean operations are really great.

Fixing the recent bugs has been a great finish for 2015. The boolean operations have taken Paper.js to a new level and there is a whole new world of possible applications for Paper.js. I wish you all the best also with the 3d.js (which I know nothing about) cooperation.

Thanks for all and all the best for 2016 :fireworks:

**Comment by lehni** [comment]
@iconexperience I fully agree! Thank you for all the commitment and great work, and happy new year's celebrations! more in 2016 (tomorrow? : )

**Comment by iconexperience** [comment]
@lehni Not tomorrow, but in early 2016 :)

**Comment by lehni** [comment]
Yes I figured, just teasing. : )
