### ISSUE TITLE
Uniting the children of compound paths doesn't work as expected

### ISSUE THREAD

**Issue by kevinmcvey** [paperjs/paper.js#880]
Hey y'all! I'm experiencing an issue with the `unite` boolean operation. In my mind, a union operation would be commutative:  A u B == B u A. In practice, however, I'm seeing some different behavior. Please see the following sketch:

[Uniting the children of compound paths iterating forward and backward](http://sketch.paperjs.org/#S/5VZRb9owEP4rN/ZAUNs0rOoLrJNa1krTpm1im/ZQePCSC/EIdmQ7QFXlv++clOBAuqF1fZoliH357u67893BfUewBXYGnS9zNGHSOe6EMrLn01O4XrNFliKETOMAPqI2GEEoF5nMRQQZM4mGFTcJaLlAEFKcGJmHCRczwBQXKIyeiCVTtc5nUoELELiCkSPy7icCaJFqGikUA7itBHZZsAX5I67CFDfYzQrJC6pBBZNcGO88OIbzoHfcxCkW8VwP4CzYygsX9I/99P/oZ4yhYWJGripLm88uuC1TNau2jB0Y0eOR9dtD+10qW0N9MpFXwUFE+s9O5MCMtBNpyqZuXVR7EhW94URMhNsovjZKznEkU6moabov4zig1R3uwGKepi4opNUtrVELfxPcILA0rUsFZAwmwUZZAYEUM7Zxbz6Nv1+O3xJEyXyWlEa40ZBybazqxow/ERnLUPmuHT9T0khzl6E/Q3O9JqtcKvvmRqoVUxFRjHMRGi6F14OH9NsJkQsSDatz9R1TQF45PKzHdyLCNWkHQ/f8mmhy7decUhQzk7iQo6PazcZV+ZJMNVRvtypTP5TZ3VfpUTA/qUd9RnyX+IHdoeoNt7a2Ox6D96KMoOHMrlJKzkrzjnJBE1LjY+jy6ef27rxS0/VbVNvCTZZCkytRZ7H429u/uhy9f47rH+MSFcX71Otvu244gX6jKt7slsnJBfT/2zKo07ttwcb4aG9Uz7py1XyjmNApIyo0Cmke7gF2x5UdVnHc3YU1x5UdVhXIYXrFwvkBVB+Kakt1o9fkehYE+4h9sna6dvdwu2zteO0O6V/SD4VsntkfB90Z3E6LXw==)

As you can hopefully see, my end-goal here is to add a function to the CompoundPath prototype that returns a new CompoundPath representing the exterior of the shape, regardless of whatever it contains. As a decent test case, I've constructed a complicated CompoundPath that includes another nested CompoundPath and some non-touching elements. The sketch demonstrates that iterating through its children forward and backward using `unite` to construct this exterior path returns different results. (Forward returns what I consider an "incorrect" result, whereas Backwards returns what I was hoping for)

I think this could be a bug in how `unite` works with CompoundPaths, but it's also possible that I'm misunderstanding how this code works. Either way, I'd greatly appreciate some clarification.

Thanks so much in advance for your help!

**Comment by iconexperience** [comment]
@kevinmcvey 
You are absolutely correct, the result should be the same.

Please note that Sketch does not use the latest codebase, which includes quite a few changes and bugfixes on boolean operations.

Using the new codebase of the `develop` branch gives this result:

![image](https://cloud.githubusercontent.com/assets/2122773/12070683/6f136312-b084-11e5-9b2c-ed1b0d1ec8f6.png)

Is this what you expected?

**Comment by kevinmcvey** [comment]
That's exactly what I was expecting to see iterating both forward and backward. Thanks for the quick response!
