### ISSUE TITLE
addCurveIntersections() very slow for quasi-straight curves

### ISSUE THREAD

**Issue by iconexperience** [paperjs/paper.js#882]
It is known that fat-line clipping has problems with straight, collinear curves. Since we handle straight curves without fat-line clipping, this is usually not a problem for us, but there are certain cases that cause trouble.

Look at this harmless looking pair of curves:

```javascript
var crv1 = new Curve([87.34388521634617, 0, 76.75904513292927, 0, 73.54763183962362, 0, 75.20314002403848, 0]);
var crv2 = new Curve([0, 0, 0, 0, 162.51045673076925, 0, 160.90144230769232, 0]);
console.log("ints : " + crv1.getIntersections(crv2).length);
```

If you <a href="http://sketch.paperjs.org/#S/VZC7bsMwDEV/RdBko4YgkXo6yJSpc8c4g+sKThBXKmTVHYr+e+XYQFGQCw94eUl+09C/e9rSl7vPw5U2dIhva730iQxpEeRIgv8ip8+0+OpsDUOJ1ioQGqUWpiG8IUYzoxyXSiC4EjtFpqTRKCw6Dahho4oBRyE5B8nRSlvopT50qQu7Jfy35A/ZlkIDU6IYaYPcaAdqx5w5LqSEjSL8DR1imOPk2RTHqqO3kGfSko6Sp8d1bPT5OWSfZj/kW2mt1gVqNvkw5mt9KP94Tb6/f8RVSdvz5ecX">run the code</a>, you will notice that finding the intersection takes very long (a few seconds on my machine).

The reason is that the fat lines of the curves are actually thin lines (width = 0), and they are perfectly collinear. So each curve lies within the fat line of the other curve. Subdividing the curves does not help, because this results in two subcurves, that are again collinear to the original curve. So each of these curves' fat line is again within the other curve's fat line. As a result we build an enormous tree of subcurves with **16,777,215** calls to `addCurveIntersections()`.

The reason why the curves are not treated as straight lines is that while the handles and end points are perfectly aligned, one (or both) handle(s) is outside of the curve's end points (these curves can occur when scaling a path to zero in one direction). I think it is correct to not treat these curves as straight, therefore we need to find a solution within `addCurveIntersections()`.

As it turns out, the solution is very simple. We already calculate the distances for all points and handles to the line that runs through the end points of curve 2. If all these distances are zero, the curves are perfectly collinear and we can stop our search.

I will create a pull request for the fix of this issue.

**Comment by iconexperience** [comment]
@lehni These curves may be relevant for #874, as the end points and control points are exactly on a line, but `isStraight()` returns false for these curves.

**Comment by lehni** [comment]
Very interesting! Yes I agree, and investigation is in order. Perhaps you could craft a little test-case and post it in #874?

**Comment by iconexperience** [comment]
@lehni I just saw that you already mentioned these curves in October 2015 (https://github.com/paperjs/paper.js/issues/802#issuecomment-147187357)

**Comment by lehni** [comment]
Haha, yeah! I'm doing a lot of analysis at the moment of the situation. One thing I realized is that the fault in `reduce()` actually seems to produce the desired result when there are no handles, something I never could have thought up : ) I will write about it soon.

**Comment by iconexperience** [comment]
@lehni Please do not forget to mention in the marketing section of the next release that paper.js has just become *up to* 16,777,215 times faster :smile:

**Comment by lehni** [comment]
Yes but is that in the average, or in extremely rare edge cases? Oh wait, marketing doesn't care about such details :)

**Comment by iconexperience** [comment]
Ooh, marketing cares a lot about details, that's why the 'up to' is in there :)
