### ISSUE TITLE
contains() returns false for interior point

### ISSUE THREAD

**Issue by iconexperience** [paperjs/paper.js#884]
In some cases `path.contains()` returns `false` for points that are actually inside a path. <a href="http://sketch.paperjs.org/#S/bZDNasMwEIRfZdHJpq6jfzkOPfTYW6DH2AdX2SQmjmQkpT2EvHvllkAPFQg0HzOzrG7EDRckLXk/Y7InUhHr94v+HALM8AIOv2A7pFNxi3i8oEux3XWhc5DPTjJaa66Z4lIzTqWqgFNTr41QkmpJFVOir/6xK8EoM/yvXa2FVJrJCp5pTSlVmTBt1o0wUvFGPLjRTW5oGGfGMMFkv9T3FdjJR9y3KVzxXm4WuNzVCuY62mHCgtEKGC03kNnVWX9ZtoF0GiMkDxExvxH24+GAAZ3FR4X1LvoJ68kfi44MAYcWOgJPufiI6TXrovwd+Nc511mlYXSx+PG9uYRh9GHrR5dyoNzkv/7I4fO8kEjaXX//Bg==">Here is an example:</a>

```javascript
var p = new Path({segments:[
    [410.6261524612045, 207.9735406405153],
    [410.6261525310172, 207.97354059345614, -0.0005059167983745283, -0.0007686158121771314]
], closed:true});

console.log("area: " + p.getArea());
console.log(p.contains(p.getInteriorPoint()));
```

Visual debuggind indicates that the point is inside the path:

![image](https://cloud.githubusercontent.com/assets/2122773/12085967/f1c596a2-b2c5-11e5-906f-3cd2f36f2d2b.png)

The reason for this behaviour is probably that `getWinding()` uses a tolerance to exclude points directly on a curve. This should not be done when checking if a point is contained by a path.

Until recently there was a `testContains` parameter in the `getWinding()`function. Maybe the purpose of this was to distinguish between winding calculations for 'contains' tests and 'winding propagation'?

**Comment by lehni** [comment]
No, the removal of `testContains` is not the cause of it. I went back to the commit before it was removed (92904e95c2ab32ca1fc3e48f41ed5b7c66f9900b), and it also returns `false` there too...

**Comment by iconexperience** [comment]
The reason why it fails is fairly simple.

In `getWinding()` we do not count the intersection of the horizontal ray if the x value of the point is within a certain tolerance of the intersection's x value. If a point is in the light blue regions in the image below, the intersection with the vertical curve at that point is not counted. This way we make sure that these points are inside the path.

![image](https://cloud.githubusercontent.com/assets/2122773/12193685/a186f816-b5ea-11e5-980c-dc42e564f99b.png)

This works quite well, but it fails if two curves are too close together. For any point in the darker blue area below no intersection of the horizontal ray is counted, therefore winding is zero, which means the point is outside the path.

![image](https://cloud.githubusercontent.com/assets/2122773/12193724/dd202636-b5ea-11e5-8265-609a0dbff1b8.png)

I do not have a solution, but at least we understand now why the problem occurs.

**Comment by lehni** [comment]
Yes that makes a lot of sense! We could calculate a path's area in `_getMonoCurves()` and decide on an epsilon value based on that, then store it along with the first curves in the array.

**Comment by iconexperience** [comment]
This si difficult. And it seems like it is not very important, because although we have a problem in theory, we have not encountered a real world scenario where this has any consequences.

Of course the most simple solution would be to have `getWinding()` always return `1` if we find any non-horizontal curve that contains the point.

**Comment by lehni** [comment]
That's a good thought! And that would be easy to add to your code?

**Comment by iconexperience** [comment]
`if (x >= xBefore && x <= xAfter) return 1`

It's quite a hack, although it should work.

**Comment by lehni** [comment]
Right after `if (x != null) {` ?

**Comment by lehni** [comment]
I was thinking the same just now about compound paths... didn't see that before. Yeah, I'm reluctant as well :)

**Comment by iconexperience** [comment]
Here is a test case that currently works, but any solution that solves the initial example in this issue should be tested agains this test case. The difference to the initial test case is that the two close curves are inside the rest of the path, which means the horizontal ray starting from the point crosses the path one more time in each direction.

![image](https://cloud.githubusercontent.com/assets/2122773/12215379/96c5ba18-b6ba-11e5-8798-ac3d924eb1f4.png)

```javascript
var path = new Path({segments: [
    [100, 100],
    [150, 100],
    [150, 150],
    [150.000000005, 150],
    [150.000000005, 100],
    [200, 100],
    [200, 200],
    [100, 200]
    ], closed: true, strokeColor: "OliveDrab"});
    
var point = new Point(150.000000003, 120);
new Path.Circle({center: point, radius: 2, fillColor: "FireBrick"});
console.log("contains = " + path.contains(point));
```

<a href="http://sketch.paperjs.org/#S/hVHBTsMwDP0VK6dORFUp6qWIy4a4gsSx6SFLzRY1S5CTjUO1fycNZFAQwlIS51n2e3qemJUHZC17HjGoPeNMuWH+nyTBqwx7uAOLb/AU02LyuDugDb6FTpCwEKO7rioO8er5F9T8ATU/oLL6jOa/4mJY/ZsyQfWSMkMZ6Tko4zwOLQQ6IgcfyI24ccZRC4I9Gn3Ce5Jbwc6r29w1v8kMp23Ibsx58V3jTRRUVx9d2a9yo0kZLCYVPcNIkUZwIDnoY/Sw5vCijbnwP2jCNWk1XviVs94ZLI3bFSJuxgaprY8iBIOrtJ4yg0Uavlrqnk9c6ZZQjqnuWdv153c=">Here is the Sketch</a>

**Comment by lehni** [comment]
Yes that makes perfect sense. I guess one would have to compare the x coordinates of the intercepts to distinguish the two?

**Comment by iconexperience** [comment]
That could work, but it requires to compare each intersection of the ray with each other intersection.

I just had another idea. We could have a flag `isOnCurve`, which will be set if we encounter `if (x >= xBefore && x <= xAfter) return 1'. Then, if at the end our winding is even and `isOnCurve`is `true`, we simply increase the winding by one. I have to think this through with all kinds of scenarios, especially with compound paths.

**Comment by iconexperience** [comment]
In order to solve this issue we should first decide when `contains()` should return `true`. Currently for all points in the following example `false` is returned. I though this would be correct, because the linese there have a discance of exactly zero, so there is no "content" between the lines. Could you live with `contains()` returning `true`for all these points? I think then I would have a nice solution.

![image](https://cloud.githubusercontent.com/assets/2122773/12222560/3e4f3718-b7c0-11e5-8b27-d2927cab58c6.png)

**Comment by lehni** [comment]
That's a good question. I tend to think yes, it should be false (e.g. since we're also discarding such parts in the boolean ops), except for one doubt: We do consider the line as part of the inside of the paths, don't we? So wouldn't we have to do the same here then?

**Comment by iconexperience** [comment]
I would make things much easier to have these points part of the path. And there is another weirdness in the way we currently handle these points: If they are on a vertical tip of two vertical lines, `contains()` returns true, but if we are somewhere in the middle of the lines it returns `false`.

![image](https://cloud.githubusercontent.com/assets/2122773/12223685/0beb7c96-b7de-11e5-90c2-0633b815776a.png)

<a href="http://sketch.paperjs.org/#S/fVFBbsIwEPzKyqdERFEA9RJa9UBVrkgckxxcs4AVx0Zr06qK8vdukkJpi/DB9o52xjvjVljZoMjFpsagDiIRym37+l0SHGU4wBNY/IA1X6PW475BG3wORWmBVzHNsgRmWVYlZ+DhFjC91zH7qzEA82vKGRjrKgFlnMdtDoFOmIAP5GpcOuMoh1K8SKo3RgZckfwsRRcvRl5pe1cBfVg7zTbYW3F3St7+j/09w0Vz5wiiXlizXrbg4/HqjdSg3YcDw5NJDO1I6rvVVbLpUpMyGLWK00X28MMvNLsludUnTn1+saLSnTZmcMw6/UelytkgtfXRL3IMz5zIqyMGV4RoSwF9RkvSjXdcsWDH3/5GKOvjwBJ5UXVf">The Sketch</a>

**Comment by iconexperience** [comment]
@lehni Actually my proposal is very simple. If the point at `getWinding()` is on a curve, we ignore that intersection but set the flag `onCurve` to `true`. At the end, if the point was on a curve, we make sure that the winding is odd through `return onCurve ? absWinding | 1 : absWinding;`

I will check how this works in theory with compound paths and if I am confident enough, I will create a pull request. No action from your side required.

**Comment by iconexperience** [comment]
My proposals fails with intersect boolean operations. Unfortunately it's not as easy as expected.

**Comment by iconexperience** [comment]
Here is another promising approach.

The first time we encounter an intersection very close to the point (`x >= xBefore && x <= xAfter`), we ignore the intersection. But after that if we find more intersections close to the point, the winding left and right get incremented for each additional intersection.

This seems to work quite well so far.

**Comment by lehni** [comment]
Sounds promising! Define "quite"? : )

**Comment by iconexperience** [comment]
"quite" means it looks good at the start, but eventually fails. This one fails if we have two intersections inside the path, like in this example:

![image](https://cloud.githubusercontent.com/assets/2122773/12233305/6fc2c3b8-b866-11e5-8662-183d9dbf1c10.png)

This is hard.

**Comment by lehni** [comment]
Maybe not worth fixing?

**Comment by iconexperience** [comment]
Maybe you are right, but I will try a little more.

Here is another approach that so far passes all tests:

- If there is an intersection very close to the point, we return `Math.max(1, absWinding)`.

That's all. I need to test this with some compound paths.

**Comment by lehni** [comment]
I had a hunch that by telling you to give up, you'd dig in deeper and find a solution :P

**Comment by iconexperience** [comment]
My weak spot :)

**Comment by lehni** [comment]
Do you still want to tackle this or shall we close the issue?

**Comment by iconexperience** [comment]
If you accept my pull request, you can close the issue :smile:

**Comment by lehni** [comment]
Very cool! I'm on a train in Germany with very spotty reception, but am trying my best at pulling : )

**Comment by iconexperience** [comment]
This can finally be closed after the `fix-winding`branch has been merged into the `develop` branch in https://github.com/paperjs/paper.js/commit/5a46620768796d3b433c59427cf041a6e5a55f17

**Comment by lehni** [comment]
:+1:
