### ISSUE TITLE
Calling unite on two identical paths results in empty path

### ISSUE THREAD

**Issue by iconexperience** [paperjs/paper.js#885]
When I try to unite two identical paths, the result is an empty path.

<a href="http://sketch.paperjs.org/#S/VY/BCsIwEER/JeSUQgnWY8WD+AOiR+shxrFK427YpoqI/25s8eBl2Z03A7MvTe4GXetdh+QvutSeT9/77kTFSi0V4aGiixC7celit/DJURtgqtmsVH+jWDTS0Jic52SsrA9MMJP+Y4J+ggNdE0ycTzgLfRLusObAkh2NbgWgRo84p+x5COG5Q8gVcMqOJANG6Jl6DrCBW/M1tkgrgTNFscgfHfPaRb5S6nW9P7w/">Here is a simple example:</a>

```javascirpt
var p1 = new paper.Path.Rectangle(100, 100, 100, 100);
var p2 = p1.clone();

var res = p1.unite(p2);
p1.strokeColor = "green";
res.fullySelected = true;
console.log(res.getArea());
```

**Comment by iconexperience** [comment]
The same problem occurs with circles, more complex paths, and even compound paths. Is this due to all intersections being overlaps?

**Comment by lehni** [comment]
Might be .Perhaps we don't start in segments with intersections? I need to check this later, now off to other things non-paper.js

**Comment by lehni** [comment]
I love it when the solution to a new problem emerges beautifully and minimally from another fix that was just implemented. This now also gives us tools to compare the results of boolean operations structurally.

And oh dear, another mess with branches here : ) I struggle with keeping `boolean-debug` (before `boolean-fix`) and `develop` in sync but hopefully soon that won't be required anymore.
