### ISSUE TITLE
Bragging:  Paper.js driving a Laser Cutter

### ISSUE THREAD

**Issue by openhardwarecoza** [paperjs/paper.js#886]
Hi.   I wanted to let you know how I used Paper.js in an application i bet the developers never expected.   I am using paper.js to parse Image data raster,  to GCode to drive laser engravers runnig on marlin,  grbl,  lasaurgrbl and smoothieware.   

More details in thread on https://github.com/openhardwarecoza/LaserWeb/issues/32

Getting raster data for lasers is hard.  But paper.js made it easy

**Comment by openhardwarecoza** [comment]
https://cloud.githubusercontent.com/assets/7695323/12094187/e56642b8-b30f-11e5-8ab4-317b6ef1eb46.png

**Comment by lerouxb** [comment]
This is pretty awesome!

I'm actually using paper.js right now to visualize a five-arm SCARA bot I'm working on's kinematics. Was just wondering if I could parse/create gcode a moment ago, actually.

**Comment by lehni** [comment]
Congrats, that looks great! I am also using paper.js to drive some machinery, in my case it's drawing machines, so your use case is actually not *that* far away from one of the reasons why I am working on this library : )

You can see some of it here:
https://vimeo.com/129666491
http://juerglehni.com/works/viktor
http://juerglehni.com/works/hektor

**Comment by lehni** [comment]
Perhaps we could feature your application in the http://paperjs.org/showcase/ section of the site?

**Comment by openhardwarecoza** [comment]
You are more than welcome!

**Comment by lehni** [comment]
I will close this issue since there is no actual bug involved : )
