### ISSUE TITLE
Potential CompoundPath.contains bug

### ISSUE THREAD

**Issue by kevinmcvey** [paperjs/paper.js#888]
Hey folks,

I believe I've encountered a bug in `CompoundPath.contains` in which, by inspection, it's clear that a CompoundPath does not contain a particular point but Paper.js is returning that it does. I've taken a crack at isolating what I believe to be the source of the problem and would greatly appreciate having more trained eyes looking into the matter.

[Here's an example sketch demonstrating the potential bug](http://sketch.paperjs.org/#S/pVdtc5tGEP4rW/cDVgKne4M77PF0Mu50xtOXZGp/SKbuJAgdEjUCBVBsJ5P/3r0DSUi2Yqflg4C93Wf3ud1jV1+OymRhjk6OLm9Mm86P/KO0mtr38YsXcF3CC/jZLKqyaeukzasSqgwSWFatKds8KeC8WiyrVTl9k7RzSKuyTfKygclq5kzdz/ncpDd5OYMPQ2WyVv4AyczeW8R9U+VlC1mSFw2gnqkhNbXVckBpnbemzhMf/TdNPinuoTZF0poptBUkJZjpzARp0hho5wYQytSNSV3YdXKPC63XOCS3lHQrt7mNfFV/QphmnixNQwax415AUy3M7TzBAKfV0nrL6mrhXFgiF61ZbMhAa5q28zFv22VzMh7PEH81QY3FeIno9T9Ndyf4MCmqyTjmU51k0zjMVEKpUJOJmkRpjJI4k2HExBTvE5aOLbb7acZrx+/Pe8eIZr2Or3GrPiU1zF1CzqA0tzs5OvZ+lxFhQkfKF5ooISOVMiKZUn4QEkYjyYBxoqjW0g8k4YLTCFhIdGxtaNqL/JBETGoOASehVsxnkoRhKGOgPmeExkKIlBI0otLnRMZMCxAkjlXE/UAQxaSIICJShkJYR5riQ4ohcPTLCdcCDRgqhpwLK2EhFyEwRZTFRswQtVUc8siPSKSYloAoLJaRL1CgacTQoRK0oyqVQnzEUREVoe+iZRg+ko05jyOUiIhj/AGSjVVHNuiFfhARzjXqUyK0wnhQiTOlFdINOEe/PA0oYSqmytILGeMRoCRGKySkLNGYAe5xSLV9ZzK28aB7hJHcp0RpHUlAYx1isD5HEpGMBKBvqe0u8ZjEWA9oJYigEhMkEYYpVMHdlxiNTQujWDSOhUZWyKEXYcyaiJjHCtaZxkg10YqH2tIIFeER+vnsjU6vS1dBJMuL4rwqqhpryfsxxSvLvM0qfhWqG7Ndp3h1610VzmpjyovDpcgoJVTzQS0W20orqM8o0bwItrLPMLAJMYcs2rWQWMta7pg4NttIHlDKsjT1dlUe8soySre8ajP9Fiu+f8KewWpj8z2s1nHscbKMOk4bhX1Gls+QUYvf1XJWmJ5RzyTEs0xtAIIWgq69rnUPFsdG4an6aD6uknrPJ+bXObX+Os/B1nVncDCF/fKT6bPJunzMd0c4ZaE94NDfHo1kgHF49wc630rAeAxX+FmHvOuttgfmzbqbYr+Z3KO8WZo0z3J8dQm9LrNV2XUw2xJc5zzG/rjwOwQfm1yTT80IvmBjwAvB3fqmVx07vRH8cHa2r2svVGsqzGFRzY69K2x2XWAevOyfXm51AcXNvFoVGKtxKscdIvwEXvdEPDgBr1q19sUb7VtPVo7znula3Zp2Um9kN9/afAVTYKc/FPHrX72N5nX5dbjNGabAdu9lbRpTpsbNNOWj84IdW3CYId0Q46yyqiiqW1w4cYgAjMDF8xK3xMT1RtwZtXaq6OwWlR1Afnn1JyRFhV6tq7eQ3CHePqSLfQsltlBvkUrWmF3MBK4u/ngHyQKrsR2gv3uI3iPiNXBDnPRVUXTDDdhTY+6QVD941aZd1SVObZiOB2Vpz1Vflfi4KTB3+Nuk7uoWD8Sy+4rVTXtpZgscLomjcLpVv3vtqF0OrdzRdZW/BSPv77CImD1d1Ieh/H40hLv//3gQoNwEjK6B90/iVtvv9ueQ4gNyT+k/iH5g4Ip95zAEQeBK35bzetremdzdEHxuh+CrClC7+86vE+iavT/o5qPT/+jiN6yyxzxsof1Nc32mk2fE37UFf/jd/27wQ5Gve53fN7PRKf6FmtQmuXEF3Byd/PX3138B)

My suspicion is that this is related to the use of x-axis raycasting in order to determine containment. It's possible that there is a small error in in this process, particularly with curved lines, that causes a path to believe it contains any point with the same y value as its own starting point. Perhaps only one intersection is made with the curved line, instead of two, causing an even/odd check to return a different value than we would expect.

Please have a look at the test cases I provide in my sketch and let me know if there are any further questions about my issue I can answer. Thanks so much for the help!

**Comment by iconexperience** [comment]
We had a similar bug recently (#819), which is closed now, but I am aware that this part of paper is not bullet proof yet and I guess it still contains bugs.

But please let us know if your bug still occurs with the latest code, as this part has seen quite a few changes recently.

**Comment by kevinmcvey** [comment]
I just switched to the current nightly build and the issue is resolved. Thanks for the help and quick work of my issue!

**Comment by iconexperience** [comment]
Well, that was easy :) Please keep on testing an posting issues if you find anything, the boolean operations are almost finished and it would be great to find and close all remaining bugs now.
