### ISSUE TITLE
path.subtract() results in open path

### ISSUE THREAD

**Issue by iconexperience** [paperjs/paper.js#889]
This very simple subtract operation fails for some reason. The case is so simple that I am not sure if maybe I am doing something wrong here.

```javascript
var cp = new paper.CompoundPath();
cp.addChild(new Path({segments:[[340.26, 358.4],  [576, 396.8], [345.78, 396.8]], closed:true}));
cp.addChild(new Path({segments:[ [691.2, 685.76], [672, 550.4, 0, 0, 10, 0], [729.6, 608, 0, -20, 0, 0], ], closed:true}));
var p = new Path({segments:[[739, 418], [637, 704], [205, 704],[204.30709922574619, 356.553500194953]], closed:true});
cp.strokeColor = "green";
p.strokeColor = "red";
var res = cp.subtract(p);
res.fullySelected = true;
```

<a href="http://sketch.paperjs.org/#S/jZHBbsMgDIZfBXFqpQwRCBBS7dQXmNRj0kMavKZqGhAhm6aq7z5I21N3mISE7Q/99m+ueGwvgCu8O0PoepzhzpqUf7UedQ69oxG+kWsdeLK1F2fn0Xy0oV+tN41vxs6R1phtfxrMKj1c0HWC4wXGMFV1zQtKmMwQFyUp9hlCtVAp1ZKUMY1cEFU+C7HSDXYCUwU/w239vyaoljonLEOyjGIyyUoVUyEoKTJEl5OnKyHFNIkTSFou9Td254n93T5t4rmIF3+K6wwV+eJFcpUhRZPNmlHxiGNYEE4V1ZoxoQqZ67QOSYTggtJcF1rwF+dP41Pw9gxbO1gfR2jw0QOMDV7wK/VgHiwN7WGK1SQyH4Jvu7Byd90IyOc8DD87GKALYOKz1HYTv//goT07e4r2cFXvb78=">It works on code base of the current Sketch.</a>

![image](https://cloud.githubusercontent.com/assets/2122773/12128703/55cb2f1a-b3ff-11e5-9fb7-a6506f2ecb46.png)

More information will follow tomorrow.

**Comment by lehni** [comment]
It works for me on `develop`... What are you seeing?

**Comment by iconexperience** [comment]
I am seeing a "Boolean operation resulted in open path segments = 3 length = 779.4471907186205" message, but I probably forgot to undo an experimental change in my code base.

Will close this now and investigate what happened here.

**Comment by lehni** [comment]
Oh yeah I'm getting that too. I just compared with your image, didn't look at the console...

**Comment by lehni** [comment]
It looks like the winding gets wrongly distributed... Weird.

**Comment by lehni** [comment]
Perhaps it's linked to the `testContains` removal this time?

**Comment by iconexperience** [comment]
It's not easy to reproduce this. Seems to be another edge case, although it does not look like one.

**Comment by lehni** [comment]
I think it's linked to the horizontal line at the bottom...

**Comment by lehni** [comment]
It is linked to the changes in how orientation is handled somehow... Weird!

**Comment by iconexperience** [comment]
If I change the line at the bottom slightly to be non-horizontal, the message disappears. This coulb be a problem with `getWinding()`.

**Comment by lehni** [comment]
But it somehow is linked to the orientation code in `resolveCrossings()` also. Still trying to figure out how.

**Comment by lehni** [comment]
Alright, so with the old `reorient()` code, for some reason the first child of the boolean path is clockwise, while the second is counter-clockwise, but they're not within each other. And for some reason this works.

With the new code, they are both correctly clockwise, and it doesn't work.

**Comment by iconexperience** [comment]
<a href="http://sketch.paperjs.org/#S/jVI9b8MgEP0riMmRKMIfgHHVyVO3SB3tDNS+OFZsYwFphyj/veA0UzpUQuLuHvfu3hNXvOgZcIU/zuC7Eya4M33Mv7RF3Yre0ALfaNUrWFqbeTWXpd9rf0p2r61tl26luu/r0zj1SXy4QVcHwwyLd1XT5AWjmSAo5yUtDgShhsuYKkHLkAacU1k+CqHSTcZBX3l7gdvuf0NQI1RKM4JEGchEpBUypJwzWhDEtpPGK0IyUzRsIFi51V+yOx6xv8dHJx5GPOmTuSKoSDctIpcESRZlNhnjv3EIC5ozyZTKMi4Lkapoh6Cc55yxVBWK50/KH8Kdt+YMtZmMDSu0eLAAS4s3+Bm10P9icWkLLlQDybh4sA46n6x34ocUWo+2myC5dhCfVLGFHkfr/OY2HcC/R2A0dm8CS7IjyOp+vLgKBYOP4zRtw6sWz3oIHLrFYffwiz4t6PMaexyumsPtBw==">Please take a look at this sketch</a>. The interior point of one sub path is just on the edge of p.

**Comment by lehni** [comment]
Hmm not anymore in this [sketch](http://sketch.paperjs.org/#S/hVJNb+sgEPwriJMjuQh/gI2rnnLqrVKPdg7U3iYojrGAtIeo//0tuDnlSZU4sDu7s7MDN7roC9COvp8hjCea09FOMf7SjowreSELfJNVr+DY3l5We12mNx1O2e55cMOSqk4Flo0r09O0P5l5ymJLKrp5OF5gCb7r+6rmrJQ5qUTL6kNOSC+aGCrJWgwRF6xp7wnMjLP1MHXBXeFnt43DUWy13gRjF/L0ghQ8J/ywYX8IIL1UBStzIlscJONI2WAoBGc1sqRTJD6EmlIxVCd5m/JP5YZH7P/SohN3ux52byqVk7pIe8qqyUnDowV9ycXvHa81q3jDlSpL0dSyUNEqyYSoBOeFqpWoHly5L+6Ds2fY29k6lDDQowNYBprgR9TB9ItF0Q789nxmCeA8jCFbN+L7Kmxv3DhDdhshlnSxhX0a50Nymx0hvEbAWPdmkSXb5cTpyVx9R9DgTzPPaXg30Is+IoceKGrHv/bhQJ/X2ONp1x9+/gE=), but it still happens.

**Comment by iconexperience** [comment]
This is ridiculous. I need to get some sleep now and try again tomorrow. Sorry for bringing this up :)

**Comment by lehni** [comment]
For some absurd reason, the red circle at the bottom has a winding of 2 while all other sampled points have next to it have 0. Why? The coordinates are `{x: 510.9235946817198, y: 704}`

<img width="674" alt="screen shot 2016-01-05 at 23 35 56" src="https://cloud.githubusercontent.com/assets/213275/12129653/39a75740-b405-11e5-8770-8716e1e40292.png">

**Comment by lehni** [comment]
I think problem is in the code that @hari has written to handle horizontal lines:

https://github.com/paperjs/paper.js/blob/develop/src/path/PathItem.Boolean.js#L320

I don't fully understand what this is doing, but the way I see it, it shoots a vertical line through the curves and finds the interception points, then determines their vertical center to shift the sample point.

This way, the sample point gets vertically shifted to `{ x: 510.9235946817198, y: 550.4 }` which is still not inside anything else (but actually it could be, this is a problem in itself!).

Why it then results in `2` instead of `0` I don't understand yet...

**Comment by lehni** [comment]
<img width="636" alt="screen shot 2016-01-05 at 23 51 09" src="https://cloud.githubusercontent.com/assets/213275/12129955/3865b672-b407-11e5-9e03-f688f22584ce.png">

**Comment by lehni** [comment]
Alright, here some debugging help...

This code emulates what's happening internally, and returns `2` from getWinding, but shouldn't.

But in order for it to work, you need to modify one line of code to export the internal `getWidning()` method. Change line https://github.com/paperjs/paper.js/blob/develop/src/path/PathItem.Boolean.js#L287 to:

```js
var getWinding = PaperScope.prototype.getWinding = function getWinding(point, curves, horizontal) {
``` 

Then execute this PaperScript:

```js
var cp = new paper.CompoundPath();
var ch1 = cp.addChild(new Path({segments:[[340.26, 358.4],  [576, 396.8], [345.78, 396.8]], closed:true}));
var ch2 = cp.addChild(new Path({segments:[ [691.2, 685.76], [672, 550.4, 0, 0, 10, 0], [729.6, 608, 0, -20, 0, 0], ], closed:true}));
var p = new Path({segments:[[739, 418], [637, 704], [205, 704],[204.30709922574619, 356.553500194953]], closed:true});
ch1.clockwise = true;
ch2.clockwise = true;
p.clockwise = false;
var monoCurves = [];
var paths = [ch1, ch2, p];
for (var i = 0, l = paths.length; i < l; i++) {
    var path = paths[i];
    monoCurves.push.apply(monoCurves, path._getMonoCurves());
}

cp.strokeColor = "green";
p.strokeColor = "red";

var pt = new Point({ x: 510.9235946817198, y: 550.4 });
console.log(paper.getWinding(pt, monoCurves, false));
```

**Comment by lehni** [comment]
**Update**:

You can use this [sketch](http://sketch.paperjs.org/#S/vVoLb9tGEv4rGx/QSLHMSLIlWXaUQ+ukBwN1WiS+C3CKUVDkStqY4jLkUo+m/u+dmV2+xIeUFHeEEYn7mJ2Z/fabmVW+nvj2ip9cnXx45MpZnnROHOni+9oOmROwCfP5hgV2wEPrRq4CGfvub7ZattrXn8JPPo1a9mCYE1i2694shee2cAoN+hrxxYr7KrqaTs8vulZ/2GHng0vr4qHD2HQwwtfx0LqEV+gfWKPLpAFaHE9G3L1SYcyf2vnl+kcsx6bDcc/qd9jwEsQOcYHhCF4Hg6510WFd+uvhB3aN+mMLdBl2L6n9rK/7sa9ekcQ5JUtH5+MOu+iRVcPzUYeNumjwtN8dmO/w9cI6746643G/PxhdDHtjdMzQGgzOB91ub3wxHpyXfEArg7ctaHUeNyLioAF2mY5+dUdQaJ7bXsRTG1bSlzdxuOYRdE0fMtvAJmqC5Tro8g4LdO9chqyFQwR0g488+KDRlsf9hVpeQ8cr5sHH6WmbfcUpDJ5EaDJ6KrQ47MuUsII4Wlp2EHi7VtbaoSnW7wuu7tLGltmJJ/yH7A+sSIXykd9ID3ScsE8ni5Bz/9OJ8cJ+b8hd05darZItlcJXra9se8UGva417p8PxhfDy96oNwaE7K40jFiyJdKPpMctTy5aoONH4bvCX7QC1WF5I8jzRmvyZOw7Skif5efgwuBwM2UpQ/GH9JXt7bmSB5HwYOqEvXzxj8mLl+/iFQ+FY3vWx9t3b27f/ev3t799uP3l13edZBY+6k5UTbn59/v/vL2/vXtbM8newqQeO6P5hb4Ae0hna1vs2KUdu0LHBgz9hc8VgWe/471YLMs9Gld45jVG9HthSCil0gguNNszbLxD8MDXFG8vX7IfZ7BjseLeLudjswBb2TsWchWHPtuE0l/ASxR7CvYjEr7Dc2LUkieT7JDTbivpC4eBn3fMFSHXO2z7LowVEYM/288JAKO54uFK+LbiLFLwr5V0izlrVQIgAcHuXiIHnd36c+ELVXQ0PrufpFJyBWMahnA40UgMsGVnCa7Kw36cg5p61Gky6jo/Coz5WZCZXLNWpJgC/dD0mVYD0MBDhwewVcgiODKC4MPWPFQIxD1xnvAzZ+BTpB5DNAnpFNgm76W17cVEb3qjgHgs3VQyEh8HAhxCkA6tBSBZ85t4JpyWmYOUF2w7GnE6iLSv9wWlin7GZUniGetdw+trUvzz2VmFsum2pssDMWgmShanVaefH9rWrrRoApkdeCXZ1R9+AGmvCSg1C9LmahxVi3xiHGjLSH6dAIEEv0oA1iQ7hWCN+P3GQsPTHiQ+LAVQBwKHuIV5OyBNBgcMm8oHebbbm7+0vTmT88MALeDO+KdFn6dwBNrsJesXzMnMbCVfqweSH1HO6+zctvd9kCPJXGzIAhMCkPY0iRTt8hpGi1escZWEceuXMTtcXskAo8RK24xRtg2Msk0ZZZsxSmkUMGKoSq0ctgwPUiF+QCrIWQu7ElaogCXJg7kwrARHwMcbQ8acADXjC+H7iDDECEoG6GCHJ2XQYbaHsWEjIDZBY4W0uQgBYzjXs+ELOVCP96V/9gcPJe2BMFKEnwq/qiIyEkfEgFlK7HmVBIZL0aB6VkL6JEccQ6HJ6o5ZOGXRWgKiEZaxrIEacOyzzKgSPgu65213Ks0rOaBxZIl3itr7fKvYs0lmLmC099BgjIYkDavVbBZy+/E7WBAfgNNH23sEhIQyXiyB8zhmIwtPA4ZITadHVdCh3b7BQMTdpAaoRE8Q8jU5r4MrIkz3WRVOBR1vk/qEUPPojtLC+KAfD8iziQeOE4fq3Teh38kdj6MPAJJBA/oJpyS4Yf9Tx4Ho+iNYcgtuRgrtQ/H32IOV1+UbT8A3nnI2mUwyYxpUyhucnbBa/xgyz2ZBvvEsfTvCBftrZnMb1630SWVjObNsyirJJkP1yXDzXqkLpjpYatQUGHyvvuiwDQyzffY5jlSNPEeuAtucWwA85U9REtD0ZirJ3DQAinlVVDPCQqiQ5iGkF19iHu5MMqbj4enZNlf4bITn6bQqgpYaaahBapl2DnuvSy409EsssDYSC1/MoUyAlaKAczcOKikCsZm4GlCTfkek9prgAoOhuIEEXe/jtPdgml6lTaOHJgF//lkUMCoLgBBSJwGG1tYcPag5dsWaQ9vTcAIQoJjp6JKhW32QzQa8iWnz/eRGABnEERFuoIgiUkFtJMN7Du7ESqwrcWGEFYrohYiQ3QGaaW4NooQD8cBWpF8PE6QGcWAtbOmOKmdvJSGP4l9iUBH0RbgYAOcR3SAsO04W+ylWup7Pa+xgZALMrXSIy2r1CmG4fDH2mjqf1DGHwtQmGBIO+Qzl2FriRsaeC+FSQbRNvQih24YlmCvjmVcdvo04YAMfTgj6aC48E14jpAioekq5ZfJQnGvh/AnpPJeeJzd4dsArrsDzHOkDDUrxrePFLndrpRlVMKN2dBJspuSvAQADz8FXz9F0NDw6IE2Tksnic8k426BnPMiv3J0uuLlbyQ7Jo6D+oostOHaF5Ajes8iWBvLjjOyDkehivZG505KZfIA/FGQjdEmHxEG5jlazfSDUUd1Vf22g2nvXc1VP5MmA52Xc2/6CF6WU74/2H6eYZNayjvHcvf2IsAzJZwRPiP08zAW+5EwdEISMxYno9SxgMrzcUzJ2APokDoOWkhs7dA/BrBDDOmwGTBGE0oEjFeGZSi+uIuHyBsIx0szaFrvHG0AeReBUYXsecRqeccBKKCPM5hsxi+czu7QV0X+hgGzRrjWWTsmDKZTeWxF9UKGNlb/Z26PmI86lcaXGilybxD0rlJ0lguafx8irgPvBs7Znj1bjRRmyx8rAJ13YSsMtAB006/5Nr2AQ+FZ/ZKyUZqz/b39kqXJ65Wn8cYCE8EGMbsGKbXYBuYWp+rLniPn4nJ4m91+N7FEcThdZR43PGCr9haxpeGX2n3ZmxdkW0zxj9hGGpld8pxPWVAl8p+YFxSAlPXoDskvB/5FiB8jyzg4fyzGefjmEEH9MaC8Wp7n7pcPG712T5OnJrPx9ttV2JPcZ1cjNbeKzwyUvOO92nrsbh+CCvzyVrsUpoBpxTSkpMVcE3K42nPvJtQ9OLtzY4NUO5JsKcq+mDJd+/aL09TnFZK3k89qdRKPxR8RJrnY6tH1Y7pnB3YeUdbDZtA4fMmo6JAzoODetQlg3J+xgAM0HuG9i9/zE5MoAGL50F3IEPx/Jq8fwaS2g8ZqSs0fOA8IHuYru3TTSIXmy11K4pobRp6oZh8AA6f0BVSC2SqOrzrPzWaI+ws3icBjd7xr08jXAG/Bm+zssgWewyzAqOzaHa12ROyYSmKrmJpY8V/GrSf7J33D+nR/M0i/mh2z6EXxlb1v2LGolOGh3WPJK+53/LxUnnRO6r9Zl9cnV9OHpLw==) instead that comes with its own version of `getWinding()`

**Comment by lehni** [comment]
And I just went back to the older version of `getWinding()`. There too I get `2`, so it's not due to your recent work on `getWinding()`, @iconexperience. But since you're quite familiar with the code now, perhaps you'd like to debug to find out what's going on?

**Comment by lehni** [comment]
So it has something to do with that vertical coordinate of `550.4`. If I move it up or down by just `0.1`, I get `1` instead of `2`. It might be that the ray touches the tip of the shape on the right, but doesn't detect it as a touch?

**Comment by lehni** [comment]
I can confirm that it is linked to `ch2`. If I remove it from the `paths` array, the winding number goes down to `1`, although the point is far away from that shape.

**Comment by lehni** [comment]
So it boils down to this [simple test-case](http://sketch.paperjs.org/#S/TVDLbsMgEPyVLRc7kksct3YSop7yA5Vy6MGOKgdWNgqBCHAfsvLvBaeuihahnUGzszMS3V6QMHI4o+c9yQg3IvYfrQXeF/ACGj/htfV9OjrsLqi9YzXU1XZFiwyqTUnX1TELwDq0ZZnT5wzyqVbxidS62NIq/M03E/5Y3PnIheLKOBTM2wFvi11jGx3mUuetOePeKGODh4Z0FlE3ZOLjjf6ufrZnpPbpCF8Myjwof7O7E5gFjXZGIVWmS6P4e4f+TWohdZde/WKxg+USDr0ZlIATQg5Oao4gfeLADN5JgQ/z4DkOupeWK0zHCEI4PESDlgVX2QzZVsjBMXj6Q/6txSCxKJLI/NoM6Z8studrXMcRVh9vPw==):

```js
var ch2 = new Path({segments:[ [691.2, 685.76], [672, 550.4, 0, 0, 10, 0], [729.6, 608, 0, -20, 0, 0], ], closed:true});
ch2.strokeColor = "green";

var pt = new Point({ x: 500, y: 550.4 });
console.log(ch2._getWinding(pt)); // Should be 0 since it's outside!

new Path.Circle({
    center: pt,
    radius: 3,
    strokeColor: 'red'
});
```

**Comment by lehni** [comment]
And here a close-up of the location where the ray touches but doesn't cross the shape:

<img width="388" alt="screen shot 2016-01-06 at 00 28 37" src="https://cloud.githubusercontent.com/assets/213275/12130653/73f5369a-b40c-11e5-9731-1fdf8debe933.png">

It turns out that the slope is not `0`, and that the next curve has a tangent of 0!

And this then leads to the change of direction not being detected, because our current checks are like this:
```js
slope * Curve.getTangent(prevCurve.values, 1).y < 0
```
An simple change to `<= 0` is all it takes to make this work, and it doesn't appear to introduce new errors! Phew.

**Comment by iconexperience** [comment]
Wow, I feel a bit bad for having you left alone with this bug, but my days start early again. 

The odds are not too bad for finding these bugs. After having tested all those tiny loops, self intersections, multile intersections, I am now testing with real world paths, and these include horizontal and vertical lines and are often aligned by a raster. There will be much more testing at the end of this week.

**Comment by iconexperience** [comment]
Actually, I have found that doing testing has become quite difficult, because there may not always be error messages if a boolean operation fails. Therefore I will try to implement something like your image diff. For subtractions I can simply draw the path to be subtracted in background color on top of the other path on one canvas. Then I will do the acutal subtraction on another canvas, and then compare the results.

**Comment by iconexperience** [comment]
I have written a simple implementation for automated testing of subtract operations.

<a href="http://sketch.paperjs.org/#S/pVZLk+I2EP4rXb6s2fEIYzDPmRwyueSQqq3d3DAHYQvsGiMRSx6ymeK/b7dkG8OQVFJhpspudffXT33w7kl+EN7S+/YqTJp7gZeqjOQ3XkFhxGEEzyDFCY78KCr2og5HVcvsCze5P1gl0pownmUveVFmPlla3bsW+4OQRi/X6/EkZNE0gHE8Z5NNALCOZyQupmyOIupjNpu3B3iSlkqLbGmqWpwH/zIKrKeLEYsCmM4RbUq40xmKcRyySQCh/R/Rg1SzaMEwhWk4t+ePkdOT7l78thlR04wPJc7GiwAmI1vOdDwLYBZSpesojJt3fJ2wcTgLF4soimeT6WhBHZmyOB7HYThaTBbx+EPxGDuRwyHw47EshAaTC9gVZQlcZqBNpV4FpKpUFRhllZSlVfKyLIyGTOhUyIxjmq4MQvr+Qi4ai9nVMjWFkj75BRba6oIG3AoDeE8k4IeMWGdD7u37qmfQ80STntQa7cCGYykNsxKyw6fPDr182290Dlf4eIIra1YKuTc5ah4erjzp06vuOsa62PxteasLxtm94uNsW0+JpBwf1Ky3QpyYKAUNPXCGqZJG/GlQ6azYXpgXd+YnXpQlXot+KjKTX+ys2IDkotjnPQwnr9zgMxwlnHIsBiqeGi73paBhHziOniZOWYE68j9q4fLd7r+K1PQ2lZFsHf33oyqkWcK6WXZd/CVQctk0ifQbtYRPNvan8yCRDphp3Kff1c88ffXdft42fRRA4m1LNEi8AGRdlt0e6+JQlxxr0fXWUD24e7D97uZWyH1TabfS9tJ9jBBRBGvaj2DnUx8zxLeZUTyjKtFOEBUcdpU6tGlg8OZuH/he/IJqYrtmpjTKX9tz3/HD1fCux9WV2FxErK3mZb9OF6oStEqO0Fqlq4kQ+oWi5d1GOt9KHNSb6Dg46h/8h0bcptd1IvpfncDc+wnZFNJK0OSpOVmx29ksmp7st23zL5NgpF9dGUR9g6hvQIDf6oOljER2HKJ2O+1oxL49dZE6EqHzh+dJRyQtGHq1tmuy2cBjl4U7aO71jdWNGzzA6N5htGlSbQnRxnyC8IrRPmCPojl8Bv/RWg8hiuOWXs4gSi0uUD/9E1SblYO7gK069qNH29OHZ/iNWIRvtcWmkOdL27+ICr9hiG9GYdjAkdsQfITEA8d8nxt2GUCzDjWmy5HTtBH2qutcne4tB4lfnZWjNCfYvbroWMuv9nmt6vi1I9ae8qh0YVmo4UviR9+CDKOWEYfRTTDdvxCXlQ16EHRNBvcuYyLxWmlVClaqPX5J7ApZ6FxkgSv86NqJkJhR4uGoek12/vf+8IfbFu/Xq+V37S3Xm/MP">Here is the Sketch</a>

It works like this:
- set item 1 to black and item 2 (the one to be subtacted) to white and bring item 2 to front
- store the image data of the canvas
- perform the subtract operation (item1.subtract(item2)), set the result to black and remove item 1 and item 2
- store the image data of the canvas
- caculate the diff between the two image data snapshots and display it in a raster, also calculate the diff percentage

**Comment by iconexperience** [comment]
For the automated subtraction test I found that when comparing the results, a threshold for the pixel diff should be used to filter small rendering differences. After doing that, all cases that have a diff dercentage != 0 are suspicious.

<a href="http://sketch.paperjs.org/#S/pVZLc6NGEP4rXVwWrfEIIaGnvYd4Lzmkasu7N+EDgpGYMswoDNjZuPTf0z3DIGQrqaSi3Sro6dfXj/nwmyfTintr7/szb7LCC7xM5SS/pDWIhlcTuAfJX+GYHnnNHlR1VK3Mv6VN4Y82iTQmLM3zh0KUuU+WRvem+aHistHr7XY6C1k0D2AaL9nsKQDYxgsSV3O2RBH1MVss3QGeZKXSPF83dctPo3+ZBbbz1YRFAcyXGG1OcecLFOM4ZLMAQvN/Qg9SLaIVQwjzcGnObyOrJ921/K4ZUdeMDyUupqsAZhNTzny6CGARUqXbKIy7d3ydsWm4CFerKIoXs/lkRR2ZsziexmE4Wc1W8fRD8Zg7keMxpMdjKbiGpuCwF2UJqcxBN7V65pCpUtXQKKMklEaZlqVoNORcZ1zmKcK0ZVCknw/korGYfSuzRijpk19gQhtd0AU3wgjeEgn4IyPW25C7e98MDAaeaDKQnNEeTDqW0TBrLvv49Nujl2/6jc7hBh93cGHNSi4PTYGam5sLT/oNqrvMsRVPf1ve5hzjZF/xcTKtJyBZig9q1ovgr4yXnIYeWMNMyYb/0aDSWrEDbx7smZ94UZ54LvqryJvibGfELkjBxaEYxLDyxg4+x1HCa4HFQM2zJpWHktOwqxRHTxMnVKCO6e8tt3h3h0c0HGwqe3SO/ttRCdmsYdstuxZ/cpQsmg7IsFFr+GRyfzqNEmkDM4379EP9kmbPvt3P902fBJB4uxINEi8A2ZZlv8daVG2ZYi263TV1anYPdj/t3IQ8dJX2K20u3ccMEWUwpsMMZj7tMcf4Bhnla1TN3QRRkcK+VpWDgcm7u12lB/4V1cR23UxplL+6c9/yw8XwLsfVl5jbi4i1tWk5rNOmqjmtkiU0p7Q1UYRhoWh5tZHWt+aVeuE9B0fDg//QiPfw+k5E/6sTiH0IyEDIak6Tp+bkYr83KLqeHHau+edJMNJvLgyioUE0NKCA39vKUEYiew5R+722NGLe7vpMPYnQ+c39rCcSFwy9nO2WbJ7gtkdhD7p7/c7qnRvcwOTaYfTUQXWEaHLeQXjBaB9iT6IlfAb/1liPIYpjRy8n4KXm51Bf/imUQ2XDnYNtevZzrUh3+qvtxm9EJCia8C4rTlXJ8qdhqX6uiEE0IDQ64/yRvTJeN6mQaIFrUagyZ/CjELoPgWzTcPwc6Qo/WnhBZM5r4gKKxlHMcJnOnXKQviD8xaif/M29A4vYTuet+MZr/AASHU7CsKuW7MfgY8V4YIn5c0d+I+i2tdUEvU41QiMmQuCv13aXxEdrZRnXCmbtzzrm6N88L1U9/fe8P1AelRaGJDs6J/r2TZBx5Ah7HL1Lpof39XyjgkEIusWja1yRSLz1WpWcleqA37C9kEIXPA9s4UfbTgyJiBIPN2nQZOt/7R/+XbnD6/9sPj/aW2+fTn8B">Updated Sketch</a>

**Comment by lehni** [comment]
That sounds good! But why not using `rasterize()` and resemble.js for comparisons, the way I do in the unit tests? It handles a lot of this already.

**Comment by lehni** [comment]
Also, I really hope this test case of yours doesn't find a ton of new bugs : ) I need to consider boolean operations finished at one point, or I will go slowly (or rapidly) insane.

**Comment by iconexperience** [comment]
I did not really look at how you did the comparison, because it was so easy to code. If you look at the sketch, it's only a few lines.

Since #885 is closed now, I consider boolean operations as finished. Tests are running now and I think there was one glitch, but I let it go accidentially.

Do I have permission to search for bugs until the end of the week? I promise not to find more than three :)

**Comment by lehni** [comment]
Yes sure : ) It's great, of course! Could you also test `intersect()` and `exclude()` if possible? Those we haven't looked at as much. And yes, I'm sure there are more glitches. But it's also really, really, really sturdy already : )
