### ISSUE TITLE
passing URL of "" to PaperScript execute function results in TypeError

### ISSUE THREAD

**Issue by bmacnaughton** [paperjs/paper.js#902]
I've been updating the dandelion example Zack Grossbart wrote to work with recent versions of paper. It uses CodeMirror and worked with an ancient version of paperjs. I end up with something like:

```js
// read the code from the editor
code = editor.getValue();

// now setup a paper scope to execute it
scope = new paper.PaperScope();
scope.setup(canvas)

url = "";
scope.execute(code, url, {source: code});
```

when I do so I get an exception in PaperScript.js on the line:
```js
	offset = html.substr(0, html.indexOf(code) + 1).match(lineBreaks).length + 1;
```

The reason is that the previous line:

```js
    if (window.location.href.indexOf(url) === 0) {
```

succeeds, i.e., the indexOf("") is 0, so the logic thinks that the URL matches the current location and attempts to find the code in the HTML.

My fix is:
```js
    if (url && window.location.href.indexOf(url) === 0) {
```

**Comment by lehni** [comment]
That's a good observation, I shall fix it. I think we should bring the url parameter into the options object also...

**Comment by bmacnaughton** [comment]
Moving the url parameter into options makes sense - it's optional.
