### ISSUE TITLE
Method for adding a layer to a project is not documented

### ISSUE THREAD

**Issue by bmacnaughton** [paperjs/paper.js#903]
`project#addChild` is not documented. If a layer has been removed 'addChild' seems to be the only way to add it back.

**Comment by lehni** [comment]
Yes, that makes sense! Although I consider `#addChild()` more an internal helper than anything else, as it can be called on Layer, Group and Project (See `Item#bringToFront()` and `Item#copyTo()`).

For Project, it would make more sense if it was called `Project#addLayer()`, and `#addChild()` could be an undocumented alias to it, for internal use only.

**Comment by bmacnaughton** [comment]
Agreed - it makes more sense to have a function `#addLayer()` as it's not obvious that the `#addChild()` will add layers - projects have other "children".

**Comment by lehni** [comment]
Resolving this just has created all kinds of simplifications in the code, and has triggered solutions to other issues, e.g. #832. I love when that happens.

**Comment by lehni** [comment]
Do you think we also need a `#insertLayers()` and `#removeLayers()` for reasons of symmetry? Or is that not really necessary. I think not...

**Comment by bmacnaughton** [comment]
No, I don't think so. It doesn't seem like adding multiple layers is a common use case and it's easy enough to 1) add this later if it's an issue - it's non-breaking, and 2) do it in one's own code.

**Comment by lehni** [comment]
Great! So all that's missing is the documentation now.

**Comment by bmacnaughton** [comment]
The old `insertChild()` documentation needs to be changed too so it doesn't say it can be used with layers.

**Comment by lehni** [comment]
Well, it can: Layers can have sub-layers!

**Comment by bmacnaughton** [comment]
Makes sense. I've never used it but flexibility is usually a good thing.
