### ISSUE TITLE
GradientColor constructor is gone

### ISSUE THREAD

**Issue by bmacnaughton** [paperjs/paper.js#905]
The constructor GradientColor disappeared between versions 0.9.24 and 0.9.25. I think the change log should document it as removed even though it's one version past. It should also note the new way to do the same thing. My guess is that using the `Color(gradient, origin, destination[, highlight])` or object form of the Color constructor yields the same result.

It looks like your 2014-09-06 commit "Remove legacy Color constructors" removed them.

**Comment by lehni** [comment]
Yes, using the `Color` constructor has long been the recommended way of using any type of color. We can list in the change-log, and mention that this actually happened earlier.

Regarding write access to the changelog, I can only make you a collaborator with full write access to the repo, or you can fork the repo, change it there and create pull requests for the updated changelogs. Perhaps we start with the pull requests and see how that goes?

**Comment by bmacnaughton** [comment]
That works fine. You'd offered it so I was checking.
