### ISSUE TITLE
Rename Path#length to Path#pathLength and Curve#length to Curve#curveLength?

### ISSUE THREAD

**Issue by lehni** [paperjs/paper.js#909]
The aim would be to avoid JS confusion with arrays.

Thoughts?

**Comment by bmacnaughton** [comment]
I'm not for this. While the API is up for change, it seems like this would break many people and for no real gain. A path is an object, not an array. I don't see problems with overloading a name; it's done all the time in JavaScript.

**Comment by lehni** [comment]
Yeah I think we can close this. I was just wondering.
