### ISSUE TITLE
Open Path items within CompoundPath items cause exceptions in boolean operations.

### ISSUE THREAD

**Issue by lehni** [paperjs/paper.js#912]
The reason being that the the current check for closed paths is not good enough. Simple to fix, but I need to do so later in the week.

**Comment by lazydaze** [comment]
Possibly. Altho this doesn't directly explain why it sometimes returns a Group. I like the fact he's talking about fixing it later in the week tho.

**Comment by lehni** [comment]
If you want to help, provide examples of situations where you think it doesn't return the expected result. Groups are returned in the `divide()` operation and when you perform boolean operations on open paths, as described here: https://github.com/paperjs/paper.js/issues/757#issuecomment-132998373

Adobe Illustrator also produces Groups on `divide()`, it doesn't make sense for these results to be CompoundPaths, because they are guaranteed to not overlap.

Oh, and you can talk to me directly, no need to use the third person.

**Comment by lehni** [comment]
145135b4f525401c176182a5c17c83374ed6356a basically fixes this issue, now the question is how we want to deal with open paths that are not part of compound paths, but which have a fill-style applied to them. They do appear filled visually, but currently they are treated as an open path, and deal with as outlined in https://github.com/paperjs/paper.js/issues/757#issuecomment-132998373.

@iconexperience what do you think?

**Comment by lehni** [comment]
@lazydaze not sure when you're week starts / ends, but this was pretty much what I had in mind.

**Comment by iconexperience** [comment]
I do not really have an opinion on open paths, but it feels strange to change the behavior of a boolean operation depending on whether a path has a fill. Also, what if the open path has a stroke style and a fill style. Since the fill indicates that we have a closed path, but the stroke shows that the path is open, what would be the expected behaviour?

**Comment by lehni** [comment]
Yes I think so too. We don't look at style anywhere else in the boolean code, so why would we here. This issue can be closed then, as the capability to deal with open paths is only needed when they're part of compound paths, in which case their context makes them act like they are closed, while they are still open.

**Comment by lazydaze** [comment]
Sorry, my comment wasn't meant for here, and I couldn't find a way of deleting it!

The problem I was having was that the API indicates that the result of a PathItem.subtract should itself be a PathItem. So, I was expecting a - b - c to work OK. Of course if a - b returns a Group, that doesn't have a subtract function, so it breaks. Just wanted clarity as to whether I should expect PathItem.subtract to sometimes return a Group. Thanks.

**Comment by lehni** [comment]
@lazydaze oh I see, that makes more sense now. Subtract shouldn't return a Group, and if it does I think that's a bug. Could you provide a test-case where this occurs?

**Comment by williamsokol** [comment]
I am not sure if this is how it is intended but when I try to do boolean operations on a compound path containing 2 paths it will cause errors:

[example](http://sketch.paperjs.org/#V/0.12.17/S/hVLBcoJADP2VDBdhpIi0XLCevHV66LSHHtTDskTZYd11lqUeGP69WdQiY6cNcMgjeclL0nqKHdDLvI8KLS+90OO6cP4XM2CQW1iCwhO8MVtG7+QztZfotxsFZDujDxms53EcQpLG2/AMW03gY0rg4wDW1ugKV1pqk8HEYDHZqC5YbJR7XDWL9bXaSh+OulGFq+rfxkih8LajV/L93tNCWT+hRugLQhhjT4QFA0PyB8U8vadw2IXCpUc3UohpkkvGK1LjBESsKFalkIXvIoPfwCS4qjFYU34fUTe5NYxb3808hPYyrgysaRC6PmU2g4exgS1FDSchJZy0qSBvLAh6a+A0QSk4s1j0iUO5+/n2ATvS4kuk5GW8APHcd8Vd0wZVJFHtbbkQ02nQ9uHOiG9QNopfi+2/isDtlZi683YdWY32elnja9kbRDUZHdKnKGyZQTq+LnZ0t+WkjaNfaI8/fy53R7eeG2TV0e249rL1tvsG)

I does get fixed though when I do a for loop and do the boolean operation individually through the children.
