### ISSUE TITLE
paper-node.js Issue: Losing Raster's source reference after importJSON.

### ISSUE THREAD

**Issue by Billydwilliams** [paperjs/paper.js#914]
I apologize in advance since this issue is not an easy one to make a sketch to show.

So in my project I create two raster based images in my browser.  I export the JSON of the layer and get the following (which is what I would expect to receive)

STRING VERSION

    '[["dictionary",{"#107":["Symbol",["Raster",{"applyMatrix":false,"crossOrigin":"","source":"http://i.imgur.com/6jpPa3A.png"}]],"#184":["Symbol",["Raster",{"applyMatrix":false,"crossOrigin":"","source":"http://i.imgur.com/QwzcDsc.png"}]]}],["Layer",{"applyMatrix":true,"visible":false,"children":[["PlacedSymbol",{"applyMatrix":false,"matrix":[2,0,0,2,291.86362,215.93181],"symbol":["#107"]}],["PlacedSymbol",{"applyMatrix":false,"matrix":[1,0,0,1,297.80382,236.17182],"symbol":["#184"]}]]}]]'

READABLE VERSION

    [
        ["dictionary", {
            "#107": ["Symbol", ["Raster", {
                "applyMatrix": false,
                "crossOrigin": "",
                "source": "http://i.imgur.com/6jpPa3A.png"
            }]],
            "#184": ["Symbol", ["Raster", {
                "applyMatrix": false,
                "crossOrigin": "",
                "source": "http://i.imgur.com/QwzcDsc.png"
            }]]
        }],
        ["Layer", {
            "applyMatrix": true,
            "visible": false,
            "children": [
                ["PlacedSymbol", {
                    "applyMatrix": false,
                    "matrix": [2, 0, 0, 2, 291.86362, 215.93181],
                    "symbol": ["#107"]
                }],
                ["PlacedSymbol", {
                    "applyMatrix": false,
                    "matrix": [1, 0, 0, 1, 297.80382, 236.17182],
                    "symbol": ["#184"]
                }]
            ]
        }]
    ]

As you can see the source for each dictionary entry is populated as I had defined them in my project.

Now when I send the data off to my node server and do an import to a layer using the above string everything works as expected and the images are drawn properly (verified by a `canvas.toDataUrl()` call )
However when I make a call on each item's `exportJSON` the server cannot seem to access the source property properly and returns the following JSON strings for each.

STRING VERSIONS

    '[["dictionary",{"#4":["Symbol",["Raster",{"applyMatrix":false,"crossOrigin":"","source":{}}]]}],["PlacedSymbol",{"name":"0:p:1329:1453145483562","applyMatrix":false,"matrix":[2,0,0,2,291.86362,215.93181],"symbol":["#4"]}]]'
    '[["dictionary",{"#6":["Symbol",["Raster",{"applyMatrix":false,"crossOrigin":"","source":{}}]]}],["PlacedSymbol",{"name":"1:p:1329:1453145483562","applyMatrix":false,"matrix":[1,0,0,1,297.80382,236.17182],"symbol":["#6"]}]]'

READABLE VERSIONS

    [
        ["dictionary", {
            "#4": ["Symbol", ["Raster", {
                "applyMatrix": false,
                "crossOrigin": "",
                "source": {}
            }]]
        }],
        ["PlacedSymbol", {
            "name": "0:p:1329:1453145483562",
            "applyMatrix": false,
            "matrix": [2, 0, 0, 2, 291.86362, 215.93181],
            "symbol": ["#4"]
        }]
    ]

    [
        ["dictionary", {
            "#6": ["Symbol", ["Raster", {
                "applyMatrix": false,
                "crossOrigin": "",
                "source": {}
            }]]
        }],
        ["PlacedSymbol", {
            "name": "1:p:1329:1453145483562",
            "applyMatrix": false,
            "matrix": [1, 0, 0, 1, 297.80382, 236.17182],
            "symbol": ["#6"]
        }]
    ]

As you can see somehow the 'source' property is not properly accessed by the paper-node version and returns back an empty object `{}` instead of the url string it parsed earlier.

**Comment by Billydwilliams** [comment]
├─┬ paper@0.9.25
    │ ├─┬ canvas@1.3.0
    │ │ └── nan@2.1.0
    │ ├─┬ jsdom@7.0.2
    │ │ ├── abab@1.0.3
    │ │ ├── acorn@2.7.0
    │ │ ├── acorn-globals@1.0.9
    │ │ ├── browser-request@0.3.3
    │ │ ├── cssom@0.3.0
    │ │ ├── cssstyle@0.2.30
    │ │ ├─┬ escodegen@1.8.0
    │ │ │ ├── esprima@2.7.1
    │ │ │ ├── estraverse@1.9.3
    │ │ │ ├── esutils@2.0.2
    │ │ │ ├─┬ optionator@0.8.1
    │ │ │ │ ├── deep-is@0.1.3
    │ │ │ │ ├── fast-levenshtein@1.1.0
    │ │ │ │ ├── levn@0.3.0
    │ │ │ │ ├── prelude-ls@1.1.2
    │ │ │ │ ├── type-check@0.3.2
    │ │ │ │ └── wordwrap@1.0.0
    │ │ │ └── source-map@0.2.0
    │ │ ├─┬ htmlparser2@3.9.0
    │ │ │ ├── domelementtype@1.3.0
    │ │ │ ├── domhandler@2.3.0
    │ │ │ ├─┬ domutils@1.5.1
    │ │ │ │ └─┬ dom-serializer@0.1.0
    │ │ │ │   └── domelementtype@1.1.3
    │ │ │ └── entities@1.1.1
    │ │ ├── nwmatcher@1.3.7
    │ │ ├── parse5@1.5.1
    │ │ ├── symbol-tree@3.1.4
    │ │ ├── webidl-conversions@2.0.1
    │ │ ├─┬ whatwg-url-compat@0.6.5
    │ │ │ └── tr46@0.0.2
    │ │ └── xml-name-validator@2.0.1
    │ └─┬ request@2.61.0
    │   ├── aws-sign2@0.5.0
    │   ├─┬ bl@1.0.0
    │   │ └─┬ readable-stream@2.0.4
    │   │   ├── core-util-is@1.0.1
    │   │   ├── inherits@2.0.1
    │   │   ├── isarray@0.0.1
    │   │   ├── process-nextick-args@1.0.3
    │   │   ├── string_decoder@0.10.31
    │   │   └── util-deprecate@1.0.2
    │   ├── caseless@0.11.0
    │   ├─┬ combined-stream@1.0.5
    │   │ └── delayed-stream@1.0.0
    │   ├── extend@3.0.0
    │   ├── forever-agent@0.6.1
    │   ├─┬ form-data@1.0.0-rc3
    │   │ └── async@1.5.0
    │   ├─┬ har-validator@1.8.0
    │   │ ├── bluebird@2.10.2
    │   │ ├─┬ chalk@1.1.1
    │   │ │ ├── ansi-styles@2.1.0
    │   │ │ ├── escape-string-regexp@1.0.3
    │   │ │ ├─┬ has-ansi@2.0.0
    │   │ │ │ └── ansi-regex@2.0.0
    │   │ │ ├─┬ strip-ansi@3.0.0
    │   │ │ │ └── ansi-regex@2.0.0
    │   │ │ └── supports-color@2.0.0
    │   │ ├─┬ commander@2.9.0
    │   │ │ └── graceful-readlink@1.0.1
    │   │ └─┬ is-my-json-valid@2.12.2
    │   │   ├── generate-function@2.0.0
    │   │   ├─┬ generate-object-property@1.2.0
    │   │   │ └── is-property@1.0.2
    │   │   ├── jsonpointer@2.0.0
    │   │   └── xtend@4.0.0
    │   ├─┬ hawk@3.1.0
    │   │ ├── boom@2.10.1
    │   │ ├── cryptiles@2.0.5
    │   │ ├── hoek@2.16.3
    │   │ └── sntp@1.0.9
    │   ├─┬ http-signature@0.11.0
    │   │ ├── asn1@0.1.11
    │   │ ├── assert-plus@0.1.5
    │   │ └── ctype@0.5.3
    │   ├── isstream@0.1.2
    │   ├── json-stringify-safe@5.0.1
    │   ├─┬ mime-types@2.1.7
    │   │ └── mime-db@1.19.0
    │   ├── node-uuid@1.4.3
    │   ├── oauth-sign@0.8.0
    │   ├── qs@4.0.0
    │   ├── stringstream@0.0.5
    │   ├── tough-cookie@2.2.0
    │   └── tunnel-agent@0.4.1

**Comment by Billydwilliams** [comment]
The following code will reproduce this issue simply
    var raster = new drawing.Raster('http://i.imgur.com/6jpPa3A.png');
    raster.position = project.view.center;
    raster.name = 'test';
    console.log(project.exportJSON());

**Comment by lehni** [comment]
Hmm, it seems to work alright [here](http://sketch.paperjs.org/#S/RU67CsIwFP2VkiUtSDoIDhUHVwcVO1qHGC9t+rg3JNdWEP/dVBHH8z5PgXoAUYiyAzaNWAhDtxmP2ideBwafbBKEKTl9QCobZlfkuVV2qO9eGRryVeuOerlVDmuZrSv85pSjYNkSxgLnqQXDarQwKQMY5b9vfhA9kiGwjLQhDNSD6qlOf0F4OPK8Kw/7NJsnKoxXrx5058giB1GcL683)?

**Comment by Billydwilliams** [comment]
It works great for me on my browser version

    [
        ["Layer", {
            "applyMatrix": true,
            "children": [
                ["Raster", {
                    "name": "test",
                    "applyMatrix": false,
                    "matrix": [1, 0, 0, 1, 575.5, 472.5],
                    "crossOrigin": "",
                    "source": "http://i.imgur.com/6jpPa3A.png"
                }]
            ]
        }]
    ]

My node server however, 

    [
        ["Layer", {
            "name": "Layer 1453158036485",
            "applyMatrix": true,
            "children": [
                ["Raster", {
                    "name": "test",
                    "applyMatrix": false,
                    "matrix": [1, 0, 0, 1, 300, 200],
                    "crossOrigin": "",
                    "source": {}
                }]
            ]
        }]
    ]

**Comment by lehni** [comment]
This works in node, but it prints the dataURL of the actual content... This is indeed a bug.
```js
var paper = require('paper');
paper.setup(new paper.Canvas(600, 600));
var raster = new paper.Raster('http://i.imgur.com/6jpPa3A.png');
raster.position = paper.project.view.center;
raster.name = 'test';
raster.onLoad = function() {
    console.log(this.toDataURL());
}
```

**Comment by Billydwilliams** [comment]
Any reason why mine is throwing back an empty object `{}` instead of the image data?
If I do `project._view._element.toDataURL()` I get back the image data as intended.

**Comment by lehni** [comment]
I observe the same here... These are bugs that need fixing.

**Comment by Billydwilliams** [comment]
Thank you for verifying that I'm not crazy.  I fought with this for quite a bit this morning.
