### ISSUE TITLE
pointText.clipMask looks not work

### ISSUE THREAD

**Issue by sapics** [paperjs/paper.js#918]
It would be my misunderstanding about clipMask, I cannot use pointText.clipMask. [sketch](http://sketch.paperjs.org/#S/fVNRS8MwEP4rR1/aQandcIKTPWjV4YMgKPgwfcia2xYWk5Kkzin+d5O02TIFx1aW+767+7679CsR5A2TSfK4QVOvkzypJXXnd6KgZqrmCFMQuIUHYtZF5SPZ14t6EWA/ilDW6gmMxnkILRnnleRSTSBdKUSROuR74J5dwaKRmhkmRagsmTDZuMxhXHqa+7n+Bj9MzHmy5+yQcdpl+BRHLfatbVKqkKYHRArzyD6dl+HZxVH4Gdlq7dqcl+UBqS2CwoXTy6vq+uZ2ll4EaScnwIQ1QDislGybIFfIirNm5kK9av8/8wIjsCCUVmvGqUKRzbuZ5N7s6yDq4d3XNqlBCotdv43QrDu5mq5XVLzmUmAWjdtBhVFEaE4MZsPSjq38jYc+UzCqxUhFfwciHU5XD94BfjRYGwtQphtOduBX7oeW5rBoDTD71VahCRSkRbzg/y0ERmRgdDBgJSyZ0ga2ZHfEDhPO9hHP87Hjun+N26Ia7f5pqNrvwtM56av4xHuiN1GmfXsWCsmmcddTJ5P56/cP)
I have checked by Windows 8.1 (with Google Chrome, FIrefox, IE11)

From the reference of paperjs, I guess that clipMask would be work for PointText. Is it right?
http://paperjs.org/reference/pointtext/#clipmask

**Comment by lehni** [comment]
Yes only paths and compound paths work as clip-masks right now.

**Comment by sapics** [comment]
I understand. Thank you!

**Comment by lehni** [comment]
I think it's correct to expect this to work... We could support it through a pixel-based compositing operation (e.g. `destination-in` through [https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/globalCompositeOperation](globalCompositeOperation))

**Comment by lehni** [comment]
Maybe that's how we should do all clipping, since there were antialiasing issues on Chrome... Or are these gone now?

**Comment by sapics** [comment]
I am really looking forward to fixed antialiasing in Chrome.
However, there have been development status, over one year :). (https://www.chromestatus.com/features/4871530282483712)

I know little about `compositing operation`, but your idea looks very impressive.
If it is possible, many users must be very happy, because we don't need to take care of chrome antialias problem!

**Comment by lehni** [comment]
The only problem with my idea is that it needs to happen in a separate buffer, and then blitted over, as it affects everything that's already there otherwise... So performance-wise, this is far from ideal.

**Comment by sapics** [comment]
Tricky idea sometimes causes performance problem. :)
"Separate buffer" is something like `direct=false` in `item.draw`?

Anyway, if there are some good responses, it would help us :)
https://code.google.com/p/chromium/issues/detail?id=422984

**Comment by lehni** [comment]
Yes exactly. I am waiting with applying any changes to that at the moment because I am also going to work on the separate canvas per layer idea for performance improvements soon. So I'll most probably merge those things to one sub-project.

**Comment by sapics** [comment]
Interesting improvements!
Dose it include another canvas for selection drawing?

**Comment by lehni** [comment]
Yes I think that would make a whole lot of sense. The idea is that one could even imagine mixing backends per layer, a sort of hybrid mode, all layered in the DOM through elements that are dawn on top of each other. And who knows, maybe we do get a WebGL backend in the future one day, with ultra-fast asm.js backed rendering, compiled through Emscripten : )

**Comment by sapics** [comment]
Really great future!
When I saw http://tympanus.net/Development/RainEffect/, I am very amazed with power of WEBGL.
I love "ultra-fast" so much :)

**Comment by lehni** [comment]
Yes that demo is insane! : ) Would you be interested in helping out with the work on different backends?

**Comment by sapics** [comment]
I am checking WEBGL feature now :)
I am not sure about WEBGL and its expression is similar with `2d` or not.
I am sorry, currently, I have not enough powers and experience to make WebGL backend.

**Comment by lehni** [comment]
WebGL is very different, since it's 3D oriented and everything is built using vertexes, and there is a shader language that can run directly in the GPU and is extremely fast (the rain effect is built using that). People have found tricks to use in-GPU memory textures to store all kind of information that is then used by shaders to render things. The problem will be to find ways to rasterize bezier curves efficiently using such an infrastructure. There have been papers on the subject, it's definitely very advanced stuff. e.g. 

http://http.developer.nvidia.com/GPUGems3/gpugems3_ch25.html

There are some JS examples out there too:

http://codeazur.com.br/experiments/webgl_curve_1/index.html

But I think to get serious performance out of this, we'd probably have to go a similar route as Figma, using Emscripten and ASM.js

https://medium.com/figma-design/building-a-professional-design-tool-on-the-web-6332ed4f1fcc#.42j72wbbc

Complicated stuff...

**Comment by lehni** [comment]
More materials on this:

http://research.microsoft.com/en-us/um/people/cloop/LoopBlinn05.pdf
http://research.microsoft.com/en-us/um/people/hoppe/ravg_tr.pdf
http://on-demand.gputechconf.com/gtc/2012/presentations/S0024-GPU-Accelerated-Path-Rendering.pdf

https://github.com/mrdoob/three.js/issues/4746
