### ISSUE TITLE
event.stop() not stopping event propagation

### ISSUE THREAD

**Issue by scerbos** [paperjs/paper.js#919]
Maybe I am misunderstanding the behavior. This is my test case:

```javascript
var selectTool = new Tool();

selectTool.onMouseDown = function(event) {
    console.log('tool');
}

var target = new Target(new Rectangle(new Point(100, 20), new Size(100, 20)), new Size(2, 2))

function Target(rectangle, cornerSize) {
    this.path = new Path.Rectangle(rectangle, cornerSize);
    this.path.strokeColor = 'black';
    this.path.fillColor = 'grey';

    this.path.onMouseDown = function(event) {
        console.log('target');
        event.stop();
    }.bind(this);
}
```

When clicking on the target both *target* and *tool* get printed in the console. Shouldn't it only be *target*?

**Comment by lehni** [comment]
This is by design: Tools are treated separately from all the other events, and are not interfered with.

You can install mouse events on the view object, and those do bubble up from the items, so you can stop them.

J

**Comment by scerbos** [comment]
Thanks!
