### ISSUE TITLE
simplify behaves weirdly with fairly simple shapes

### ISSUE THREAD

**Issue by ludwick** [paperjs/paper.js#920]
It's not clear when one should use `simplify` to be honest, but it does some pretty surprising things. Take this [example sketch](http://sketch.paperjs.org/#S/3VdLT9tAEP4rq1wA1V7t7HtBPaHeK3HogXAIiSEuiR05SasW8d87+3DimISiFugjUiTvzOzO9+3sfPbeD6rRvBicDi7uitV4OsgG43rix4um/lyMV3Q8K0bN8cnZsBpWX0YNWYxW04tVU1a3S/KeXA4rEn/DwZwIzqllUrsMwOITM5bkloJznGeMsCzn1GnmJAFHnTJMBGtrxFAuLLfRKKjzZpILqsApH/qdzNHDhoNsN62CFAKCUdAMNMmBUWm00mExRw1YowgA1UYZ26YF43yooqA0VwmijtAISKqUVa4TbDAYKNKCyMfGvMQnQ+ImhVokwQ+j1dQD44jWxgxkTMA/IdiUW1ArlJMZUA+XEx12xm3GYgNNUS20gSwHao11sDUgfGe0jtsecWKQFEZluKdpy1Vigw+YUGC9JBXOSukXjOByQwEMOD/Lel/HYqiWTHOfQ8Y6I7S47+gToCUQGzd/a+CBBCB42T4FzByxx1MBVHAmOJmRnAWkwu+qB4hbhabANMtTiQny01hJ5zFzY0TglRBuLCLFsJa0XzNC3hgkZcIxHYqYKhsIikxEpCRtU6bS1PaMQPLrgA3DYx3T0KTTwzBDOp+CMosc0RUn5i6WZjNGTgzC+UV4UoL0fJMvLYvk4rk+dNQsT1netB8lS8n6aZWAPWlFaqbfTivMPyQDUmIbaDCPZCAg6MgANlxPBmxXBiJgFftwRwWi4SVVgAPrqUC07FcB/yZ4WgWQflKB+LRVgdDyf5UKeGQ7KqCwzh0V8HXYFQHoqQAckIGQ8wkZCPVLMhDK1pMB+KkOSG3/iA44uV8HXjet4mK/Dmxac0cH4ml4cR1IonMQo93f/THDq7d/eJ082f6ScfEftD8HeKr7eb/7+cFvAN77Bnij7u9+BPxa96NSJWrPeh0/vw3xgMjeEb8K94TtTcHfETo3BjofLY5v1tV4VdYVOd56Tsi9x9xOw1lV8ZWc1/NFva4mH9HUDT7zsX5Ml6umvivO61nd4Jyj26YoqqO++1M5CUseQcd1U85mm3lNMYku/2+K1bqpQhTaHk4SpUCH3tTNh9F42iFRN+VtWY1mHuRjGl0v3qXqqjjuwF/UyzKs8g6vUiwjil2dtQuMp+Vs0hRV2kHajkNAO9iDZ7m+Xmyh+F+y0GU5X8zKm28JQWCW6OG977opRneLuqxWy8Hp5dXDDw==). 

Screenshot as well:

![screen shot 2016-01-21 at 1 18 05 pm](https://cloud.githubusercontent.com/assets/2992145/12494888/76d76cfc-c041-11e5-890e-f1e82c480081.png)

The top is the original display of `CompoundPath` objects creating from svg path data. The bottom is applying `simplify` to a copy each child path of the original (re-positioned down obviously).

Now obviously `simplify` is more useful on complicated curvy paths, but if you're processing arbitrary inputs you don't know in advance if it would make sense to simplify. In our code we do guard this by checking for the number of child paths and count of segments in those child paths, but it seems weird to just arbitrarily threshold.

**Comment by ludwick** [comment]
Also note that changing the parameter to `simplify` doesn't substantially improve this.

**Comment by ludwick** [comment]
Digging into source, I think it's just not suitable to use `simplify` as it is currently written on things that aren't similar to Bezier curves. In [PathFitter](https://github.com/paperjs/paper.js/blob/e14b7b2024ca5b4242b92793944712774135cfcf/src/path/PathFitter.js#L54) it seems to be trying to fit everything to a cubic bezier.

**Comment by lehni** [comment]
No, that's not really what it's doing. The algorithm as originally developed to fit bezier curves to large datasets of just points connected by lines, the way you would get them from a pointing device, e.g. the mouse. So takes these points and tries to create similar lines by fitting as few curves through them as possible. The parameter controls the allowed error.

In your example, the curve information (the handles / control points) is actually ignored, only the points that the curves pass through (the anchor points) are taken, and passed through the algorithm. And since there are so few and they are wide apart, you get unpredictable results.

You could try to use `flatten()` with a low `maxDistance` first, creating a path with many points, and then use `simplify()` on that.

**Comment by lehni** [comment]
So I don't think this is a bug... But perhaps the issue here is that the documentation is not clear about this?

**Comment by ludwick** [comment]
Thanks that's what we basically concluded once we started looking into it. How do you normally document this kind of thing? Is there some kind of jsdoc on the actual simplify call in the correct js file? I could send a PR when I get a chance (and maybe also update the part of the tutorial that demonstrates simplify.)

**Comment by lehni** [comment]
Yes the source is JSDoc comments, which are translated [into this](http://paperjs.org/reference/path/#simplify) by a customized version of JSDoc 2 that we're using. You can find the source to it here: https://github.com/paperjs/paper.js/blob/develop/src/path/Path.js#L1045

The current description is indeed very vague, always happy to accept PRs with improvements, of course!
