### ISSUE TITLE
Allow control over automatic view updates.

### ISSUE THREAD

**Issue by lehni** [paperjs/paper.js#921]
It was requested to allow a manual update mode where people explicitly need to call `view.update()` to redraw the view. This would be very easy to implement and should be offered through an option property either on the `PaperScope#settings` object (accessible through `paper.settings`, or just `settings` in PaperScript), or a property on the `View` class. The question is how to call this property?

Some possibilities:

```js
view.autoUpdate = false;
view.manualUpdates = true;
settings.autoUpdate = false;
settings.manualUpdates = true;
```

I think shorter = better. Not sure about view VS settings, maybe `settings` makes more sense? We also have `settings.handleSize` and `settings.hitTolerance` and those are in a way view related settings too.

**Comment by nicholaswmin** [comment]
I really like `view.autoUpdate` since redraw updates pertain to the `View` specifically. `autoUpdate` makes more sense to me since it eers on the side that everything happens automatically unless otherwise specified.

**Comment by lehni** [comment]
Yes but we could argue that handleSize and hitTolerance should also be bound to the view. So perhaps we need `view.settings`?

**Comment by nicholaswmin** [comment]
I've skimmed the last part when reading but now that makes sense. Oh well.

**Comment by lehni** [comment]
From the mailing list, pasting here because discussions happened in both places:

I have implemented a rather important change now where views are not immediately drawn in the mouse event handlers. Instead, they request an animation frame and the update happens after the processing, the next time where it makes sense for the browser to redraw things.

This has the great side-effect that for many events with changes, only one update will take place after.

Such updates can also be requested by yourself, through `view.requestUpdate()`, but I doubt there will ever be a situation where this is necessary.

Do we still need the possibility to turn updates completely off?

**Comment by nicholaswmin** [comment]
Well, here's one case.

Someone might want to call 5-6 times `importJSON()` before actually drawing his scene.
If the `json`'s contain many items, not calling `view.update()` after each import will shave off some time.

In this case the user would call manually `view.update()` after all imports are done.

**Comment by lehni** [comment]
It's using the `window.requestAnimationFrame()` method to request an update, and this is only going to happen once the current blocking code has completed. If this person is loading separate SVG files from external sources, then yes, updates would occur in between. I can see that this could still be useful!
