### ISSUE TITLE
Touch devices/Pen tablets sometimes allow sequential mouse-downs

### ISSUE THREAD

**Issue by nicholaswmin** [paperjs/paper.js#922]
#### Test case ####

- Create a `Tool` which logs to the console it's `mousedown` and `mouseup` events.
- Tap the screen quickly, with many fingers, simultaneously and keep repeating.
- Check the logged events.

##### Expected Result ####

- Mouse/Touch events are *always* logged in the following order
 - `mousedown` --> `mouseup` --> `mousedown` --> `mouseup` ....

##### Actual Result ####

- Mouse/Touch events are *sometimes* logged in the following order
 - `mousedown` --> `mousedown` -- >`mouseup` --> `mousedown` --> `mouseup` ....
 - `mousedown`'s are sometimes logged *sequentially* with the 2nd `mousedown` not having an equivalent `mouseup`.
- If tapping fast enough, sometimes even 3 `mousedown`'s can be logged sequentially.

##### Device/Browser ####

- Touch-enabled devices & Pen tablets
- Originally observed in Chrome Canary  47.0.2526.111(64-bit) on Mac OSX Yosemite (10.10.5)

====

[Test Sketch here](http://sketch.paperjs.org/#S/jY4xDsIwDEWvYnlKJNQDFLGxMgETYQipgaqpHTUJHarenUSIjQFP/+s/PXlBtiNhi8eBknviBp10tb/sBIliOol42AHTDDUqvTVs+Ls0wgfJkfYyc6HumV3qhZWGxTCUc8JRPDVeHsrgWNmusAa14fWX6Rz+9eTwsZSfbxPZIUjPKWJ7ua5v)

**Comment by lehni** [comment]
Your test-case is broken. It looks like not all code is there?

**Comment by lehni** [comment]
And could you tell me what kind of device and OS you're observing this on? I've been testing with the iOS Simulator on OSX and it doesn't happen there (of course, since there's only one mouse pointer, and the touch emulation with multiple fingers would follow the expected sequence).

**Comment by nicholaswmin** [comment]
Apologies - fixed the test case although it's a ridiculous test Sketch I thought it would make your life a tad easier by copying/pasting.

So the Simulator is not going to work because the actual events are coming from a mouse where it is impossible to simulate multi-touch I guess?

**Comment by lehni** [comment]
So with tablet you mean an iPad, then?

**Comment by nicholaswmin** [comment]
Yes.

**Comment by lehni** [comment]
Could you try my change in 52017340d2b005bc2afd7a0243aa17e3e755757c and let me know if it works now?

**Comment by nicholaswmin** [comment]
Fixed, thanks Jurg.

**Comment by lehni** [comment]
perfetto!
