### ISSUE TITLE
unite() fails on compound path if other path is identical to child

### ISSUE THREAD

**Issue by iconexperience** [paperjs/paper.js#923]
When calling `unite()` on a compound path, a child is dropped if the other path is identical to one of the compound path's children. Here is an example:

![image](https://cloud.githubusercontent.com/assets/2122773/12512741/520b63c2-c11a-11e5-9c88-6488f7679c98.png)

```javascript
var p1 = new Path.Circle({center: [100, 100], radius: 20});
var p2 = new Path.Circle({center: [150, 100], radius: 20});
var cp = new CompoundPath([p1, p2]);
cp.fillColor = "rgba(255, 0, 0, 0.3)";

var p3 = new Path.Circle({center: [100, 100], radius: 20, fillColor: "rgba(0, 0, 255, 0.3)"});

var r = cp.unite(p3);
r.fullySelected = true;
```

<a href="http://sketch.paperjs.org/#S/lZDNisMgFIVf5eIqBQn5IRvLrPICA10mWVhzO5ValVudUkrffUxsuywMiCD3nPOd651ZeUYm2O6EQR0ZZ8rNy/tXEvgavsDiFb5lOJa9JmWwuCu0AUnAUFcVh3RNHEjOOl4ENNVjsx1ptKu9+WzvPtuVf9p7d/Yu2nmJKQZf85Q8ZZ3y5UEb0zvjKKlHRj97WTRdx6HKp2w3I1u171rt/7fi8MaIFyUDMmulPLu/OEuh1C9aHbDwbR5SeYjG3HZoUAWckyRQxG369z2hPHmnbbgwMUyPPw==">And here is the sketch.</a>

As you can see, the result includes only one circle, while it should include both circles.

This bug is similar to #885, but this only happens when calling `unite()`on the compound path. The same operation on the simple paths works.

**Comment by lehni** [comment]
Hmmm! how do you even find these cases! : )

**Comment by lehni** [comment]
Not a show-stopper for a roll-out for me, but it should be addressed.

**Comment by iconexperience** [comment]
Another interesting thing is that `substract()` and `intersect()` return the correct result. I will look into this.

**Comment by lehni** [comment]
I'm not surprised that fully overlapping shapes produce issues with compound paths. We currently only detect this case on simple paths, so my fix for the previous related issue (which was very simple) does not go far enough.

**Comment by iconexperience** [comment]
If we want to fix with out standard way of resolving boolean operations (without a special comparison of paths), we have to look at the `tracePaths()` function. The input there seems to be correct, but the return value is wrong in these cases.

**Comment by lehni** [comment]
The solution looks simple in the end, but a whole lot of trial and testing went into it... Glad it works now!
