### ISSUE TITLE
Decide if mouse events should automatically call view.update(), or trigger an update in the next animation frame instead.

### ISSUE THREAD

**Issue by lehni** [paperjs/paper.js#925]
Title says it all. I think the latter would improve animation smoothness.

**Comment by nicholaswmin** [comment]
If the one-canvas per layer is eventually adopted wouldn't it be OK to retain mouse events triggering `view.update()` whilst the user himself is responsible for moving animatable items to the "bottom canvas/layer" where the mouse won't be triggering anything?

**Comment by lehni** [comment]
No, that's not really the same. The fix to this issue helped solve your other issue #830. Try it out and you'll see why b71ffdbe71838681d8e5e21a6a1e1a107be42883 is really great news!

**Comment by nicholaswmin** [comment]
Ah I got you now. Confused this with `view.update()` when hovering the mouse. 

I'll give it a spin soon, thanks a lot :)
