### ISSUE TITLE
Safari (9.0.3 OS/X) doesn't attempt to load scripts with "text/paperscript"

### ISSUE THREAD

**Issue by SundialServices** [paperjs/paper.js#928]
I have these statements in the page:

`<script type="text/javascript"   src="images/skins/hsi2014/paintMe/paper-full.min.js"></script>
<script type="text/paperscript" src="images/skins/hsi2014/paintMe/paintMe.js" canvas="canvas1"></script>`

and find that Safari will not *attempt* to load it unless the statement says `type='text/javascript`, which of course causes PaperScript not to recognize it.  (The `paper-full.min.js` file is loaded; `paintMe.js` is never attempted.)

No HTTP transaction requesting that file ever occurs, *and* no messages appear in any log on either side.  This is __not__ a "404 issue."  But, what can I do?

Any ideas?

**Comment by lehni** [comment]
Is this locally, or from a web-server?

**Comment by lehni** [comment]
Or try inserting the paper.js script tag after your paperscript... If this is in the body, then the automatic loading might get called before your other script tag is available.

**Comment by SundialServices** [comment]
Closing this issue ... it must have been something else.  In other words, "all of the sudden, it works now," I saw what I saw, and very carefully documented what I saw, and-d-d-d... I don't see it happening anymore.  Now, Safari and everyone else _is_ loading the script.

**Comment by lehni** [comment]
:+1: sounds al too familiar : )
