### ISSUE TITLE
strokeWidth is not taken into account when calculating bounds

### ISSUE THREAD

**Issue by nicholaswmin** [paperjs/paper.js#929]
#### Test case ####

- Create a path that resembles a vertical line. E.g segment1 @ 100,100 - segment2 @ 100,200
- Assign a big `strokeWidth` to the path, e.g `strokeWidth = 10`;
- Log the path width via `path.bounds.width`.

##### Expected Result ####

- Console logs a width of `path.bounds.width = 10`.

##### Actual Result ####

- Console logs width of `path.bounds.width = 0`.

##### Device/Browser ####

- Chrome  47.0.2526.111(64-bit) on Mac OSX Yosemite (10.10.5)

====

[Test Sketch here](http://sketch.paperjs.org/#S/VY4xD8IgEIX/CjmXNiENdaxx8g+YODiUDhSIbcC7BtAOxv8usDlc8t27917uA6ieFga4OZv0Ahw0mbK/VWCbSgs7M7Q7u2Zsxl4InmfilY6Z2pPEYutiCuTsfTU10ot//UKeQtYlHIQQEvJVoiaM5G3n6dFU70wvNLHbS0krMT8zB6vcRiumCMM4fX8=)

====

Notes:

- As far as I'm aware this should also cause `Invalid State Errors` on the canvas when rasterizing. 
- I sometimes get these errors on Safari but nothing is logged in the console (canvas just stops responding).
- I can't replicate any of the `Invalid State Errors` at the time being. I'll try and reproduce reliably so I can include such a case in the test-case.

Quoting from [W3C Canvas Element specs](https://www.w3.org/TR/2009/WD-html5-20090423/the-canvas-element.html)

> If the image argument is an HTMLCanvasElement object with either a horizontal dimension or a vertical  > dimension equal to zero, then the implementation must raise an INVALID_STATE_ERR exception.

**Comment by lehni** [comment]
This is not a bug: 

- `path.bounds` is the pure bounds of the geometry
- `path.strokeBounds` is the bounds including the stroke

I'm not sure what you mean about the Invalid State Errors.

**Comment by nicholaswmin** [comment]
Apologies. Major diagnostic hiccup.

Closing.
