### ISSUE TITLE
Calling Path.add after accessing the curves property on an empty path causes an error.

### ISSUE THREAD

**Issue by jwiener88** [paperjs/paper.js#935]
The issue is that calling `path.curves` will set `path._curves` to `[]`. When `path.add` is called, there is a check to see if the path is empty. It reads as `if (path._curves) { ` Since the empty list is truthy this check becomes invalid. 

http://sketch.paperjs.org/#S/q1bKS8xNVbJSCs5OLUnOUNJRSs5PAfHLEosUChJLMhRsFfJSyxUCgEwNTeuYPJCYXnJpUVlqMYyXmJKiAVaTn5lXomGqY6qpaQ00KKkoNTG7ACRWrGQVHVsLAA==

Line 7336: Uncaught TypeError: Cannot set property '_path' of undefined

**Comment by lehni** [comment]
This is already fixed on the `develop` branch. You can get prebuilt versions of it here: https://github.com/paperjs/paper.js/tree/prebuilt/module
https://github.com/paperjs/paper.js/tree/prebuilt/dist
