### ISSUE TITLE
curves drawed by mouse turned to be straight lines

### ISSUE THREAD

**Issue by immortalCockroach** [paperjs/paper.js#942]
Hello,I'm using paper.js([the way of using javascript directly](http://paperjs.org/tutorials/getting-started/using-javascript-directly/)) to [draw a curve according to the track of mouse](http://paperjs.org/tutorials/interaction/creating-mouse-tools/).And it work correctly.The code is showed blow.
`    var tool = new Tool();`
`    tool.onMouseDown = function(event) {`
     `        if (path) {
                path.selected = false;
                path.remove();
            }`

            // Create a new path and set its stroke color to black:
            path = new Path({
                segments: [event.point],
                strokeColor: 'black',
                strokeWidth: 40,
                // Select the path, so we can see its segment points:
                strokeCap: 'round',
                strokeJoin: 'round',
                opacity: 0.5,
                fullySelected: false
            });
        }`

`    tool.onMouseDrag = function(event) {
        path.add(event.point);
    }`

However,after I draw a background using the method [Path.Rectangle](http://paperjs.org/tutorials/paths/creating-predefined-shapes/).**The lines drawed by mouse turned to be straightline(not curves).**
The essential code of drawing the background is showed blow(others do nothing with paper.js).
`var rectangle = new Rectangle(new Point(x, y), new Size(xstep + 1, ystep + 1));
                var pathr = new Path.Rectangle(rectangle);
                var color = new Color(color.r / 256, color.g / 256, color.b / 256);
                pathr.style = {
                    fillColor: color
                };`
**And the most strange is:
 if I delete the 'pathr.style = { fillColor: color }; 'sentence,everything gonna be ok.**
I wonder why would this happen?
thanks

**Comment by immortalCockroach** [comment]
The correct curve is like this.
![image](https://cloud.githubusercontent.com/assets/15799308/12839712/1166f0e0-cc17-11e5-8bd3-f1fb6251409e.png)
while the unnormal curve is like this(you can see straight lines clearly),and it's happening when I draw the background using the code above
![image](https://cloud.githubusercontent.com/assets/15799308/12839734/3921be62-cc17-11e5-8c1c-5b953d1f6351.png)
thanks

**Comment by lehni** [comment]
I can't see any part of your code that would indicate that your tool is drawing anything else but straight lines. All you do is adding segment points without any handles, and you're not calling `smooth()` or `simplify()` on the path, so you will naturally end up with segments connected by straight lines.

**Comment by lehni** [comment]
I can see straight lines on both curves. It just looks like the first one has more segments, resulting in more and shorter lines, reducing the appearance of the "straightness" of the polygon (not a curve).

**Comment by immortalCockroach** [comment]
Sorry lenhi,it's my fault that I haven't described the problem clearly(there is a curve class of paper.js and what I mean is curve in our daily life).
And thanks,I solve this problem by using smooth.
