### ISSUE TITLE
Blending

### ISSUE THREAD

**Issue by m-2k** [paperjs/paper.js#946]
Hello again
I have a question
Whether it is possible to change the brightness in png (translucent) sprites for example through blendmode?

The layer structure is as follows:
```
background
sprite-1 <– the possibility of change the brightness
  | image-1-1
  | image-1-2
    ?  Path.Rectangle with color (0,0,0,0.5) maybe as variant
sprite-2
  | image-2-1
  | image-2-2
menu
text
```

**Comment by lehni** [comment]
We don't have pixel manipulation filters in paper.js (yet), but perhaps using a blendMode together with a backdrop of which you can change the color / gray-level can be of use? You could then rasterize the result into a new Raster, for faster display:

http://sketch.paperjs.org/#S/VVBBboMwEPyK5UtAQoZLL456aa+tVKXHkIMxG3Bi1shrgqqIv9eQINo5eTyzs6u5c1QdcMm/rxB0yzOuXT3zm/Ks8qZpAwIRe2WFeNmXWOIseEUBfPxEGNlhIcm9RBZBbvAaJNu1IfQyzxURBBK96sFfSDjf5KZTDVDeKW/sD4pL3+yyx3BlAevPeECcJ+0BcFUcfjhVS3YeUAfjMEnZc+GM5SbQ4XnRlwqtOESusLGQ/DHO8KsgWWgNicoNWFP233Q21r4767xcEpdnsvWRbu4p3W9kzhadu8EbWDcmc/4qTyUu1tiggVFowEeFxyJjxSkKsfvKg7r2zmAgLo+n6Rc=

**Comment by m-2k** [comment]
I can change the brightness with the blendMode. The problem is that the sprite image with transparent areas, and is also subject to changes in the underlying part of the background

I tried to make the background and sprites in different layers but in this case, the background color is subject to the same

```js
r = new Path.Rectangle(sprite.bounds);
sprite.addChild(r);
r.opacity = 0.5;
r.fillColor = '#444';
r.blendMode = 'source-atop';
im = sprite.children['image-1'];
im.blendMode = 'destination-atop';
view.draw()
```

any ideas?

**Comment by lehni** [comment]
Not sure I fully understand, but does it sound like this problem here #474?

**Comment by m-2k** [comment]
Yep!
