### ISSUE TITLE
Raster pivot bug

### ISSUE THREAD

**Issue by petrbrzek** [paperjs/paper.js#948]
Problem:
The pivot settings is changed but the `rectangle.center`  is used for position in the **initial** render. When I click on the run button then it works perfectly.

Sketch: http://sketch.paperjs.org/#S/bZLBitswEIZfZfDFDhg5LbSHhD30vpTS9pb4oMhjWxtFI6Rx0mXZd+9I63RLqRGI0czo/7+xXiqvL1jtqh9nZDNXbWVoyPFVR1iigweoZ+aw6zqdEnJSQQeMT0lRnDp70ROm7qKjdc9ePYWp3h99bo06MUbp9niD7yVo5LqNpI++674w8GwTBLKeW6DlT4ccemK4oXOSTZYteRxaOC0MlhNw1D6NFC86Z0C2aH/lLkMxomE4HD60sJXVt3CQPUd9n2XfFFSwVxF4WAXViRY/JMUUHnHk/XvZKr4yfMtOm227vSN8pVsrEAjBGl4iQsG5Gwbri93gtEHQXCpFA5yIZK9eWGksx0PUN+snMFpGl/6DeqecdYITolDTYEcrKnfYj58+v+PmoIfGOGvORaAWF891vpeFR5zlw/yfIcnEMqM4ETyMWsLrmmOCiGPENG/UX+Mj/0h6kKmMiy/NzQZejh7kM+QTOVSOpqb+KRrlfRTbTnpwUHWe3r+l68VvkLngdS/v8BRRn8v7SNXu0L/+Bg==

Screenshots:

Initial render:
<img width="509" alt="paper_js_sketch" src="https://cloud.githubusercontent.com/assets/879564/12875015/01f32054-cde1-11e5-912c-182da15f455c.png">

Rerun render:
<img width="700" alt="paper_js_sketch" src="https://cloud.githubusercontent.com/assets/879564/12875022/27bb8592-cde1-11e5-876d-ec851e2f460c.png">

**Comment by lehni** [comment]
It's most probably because in the first execution of the script, the image is only ready once `onLoad()` is called, and you're using the bounds before the content is loaded, which means the size must be 0. When you execute again, the image is in the cache so the size is not 0. This is most probably not a bug.

**Comment by lehni** [comment]
Try this instead: [Sketch](http://sketch.paperjs.org/#S/XY8xDsIwDEWvYmUBpKplDuIGTDACg2lNG6B2FLsghHp3UmDiT37S87f8cow9Oe92V7K6c4WrpZn4jgkSqlGCNTA9YPuB+evAkKMypJo8zDqz6KsKVcm0jBgpXbSU1Fahx5a06jGF25PLS2xnxXdZeCPYeDgPXFsQni/gVzvFupCLwl0sX/7ASQZutDSJGzrb6l8VDVNLtvfLApbHnzAeeFzkOf90SoTXKIFNnd8fxzc=)

**Comment by petrbrzek** [comment]
You are right! 
Btw: Is there any way to support the work behind Paper (something like https://gratipay.com/)?

**Comment by lehni** [comment]
Nice, donations are always welcome of course! At the moment there is just good ol' PayPal: http://paperjs.org/donation/
