### ISSUE TITLE
View sizing behaviour

### ISSUE THREAD

**Issue by drew-r** [paperjs/paper.js#949]
I am trying to scale down the size of the canvas & it's contents nicely for smaller viewport devices.

I am detecting the viewport size and setting the height & width attributes on the canvas with Javascript.
For the large viewport this works fine, but on the smaller viewport, Paper applies some CSS height and width that distorts things and also the contents don't scale down i.e they occupy roughly a third of the canvas in the large viewport but around half in the smaller one. I am looking to have them occupy a third in both viewports. 
The contents are a couple of imported SVGs which I then set the bounds and positioning on. 
````javascript
                var w = Math.max(document.documentElement.clientWidth, window.innerWidth || 0);
				var h = Math.max(document.documentElement.clientHeight, window.innerHeight || 0);

				var canvW;
				var canvH;
				if (w < 768) {
					canvW = 300;
					canvH = 200;
				}

				if (w > 768) {
					canvW = 500;
					canvH = 300;
				}

				var paper = $window.paper;
				var canvas = element[0];


				paper.setup(canvas);
				canvas.height = canvH;
				canvas.width = canvW;

				paper.project.importSVG('path.svg', function(item) {

					item.bounds = new paper.Rectangle(0, 100, 50, 100);
					var item2 = item.clone();
					item2.bounds = new paper.Rectangle(100, 100, 50, 100);
                                       
                                       
					paper.view.draw();
                               });

````

The result in the smaller viewport (< 768 width) is correct attribute width and height on the canvas but with an inline css height set to 150px, width to 300px.
What am I missing here? 
Also are the rectangle sizes I am passing in some kind of absolute heights irrespective of the size of the canvas i.e they will be 50px wide and 100px high regardless of canvas size?
Setting `view.viewSize` seems to just distort things further and actually overrides the smaller attribute dimensions I set.

**Comment by lehni** [comment]
You should use CSS to size your canvas element, and allow paper.js to do the pixel sizing accordingly. The library has internal support for hiDPI, so will multiply your pixel count to cover native pixels. If you don't want the hiDPI support, you can set the hidpi="off" attribute on the canvas element. If your CSS is dynamically scaling the canvas, then you need to define / set the resize attribute on the canvas.

**Comment by lehni** [comment]
Please note that this is a bug database, not a place to get help with scripts. The mailing list is much better suited for that: http://groups.google.com/group/paperjs

Here I am trying to keep bug count low to keep the overview as we approach 1.0.0

**Comment by drew-r** [comment]
Thanks - will give that a try.
