### ISSUE TITLE
Assumptions for skipping shadow painting are wrong

### ISSUE THREAD

**Issue by iconexperience** [paperjs/paper.js#955]
Currently an item's shadow is not painted if the shadow blur is set to zero. This is wrong if the item has a translucent color or if the shadow has an offset.

<a href="http://sketch.paperjs.org/#S/rZFBCsIwEEWvMmTTFkJJAwGpuLEHUHBpXaRpakNjImnUhXh30xYRFXHjZmD+n+HPY67I8INEOdp00osWYSRsPfRn7kAoJ7SEBRh5gTX3bVqMSnwV0njpcthSQjCEssPgeK1OfQ7ZIDVK68JqG2Yit694TBkbBzFkdIaBpCyJbsm8NKWZYtK+5bW9jEshMqo0F100f7OX+jS4GXk3Vk3TS/+41Srj4/GyKaI0Tx76G4j9A4j+IKKvSOTD+I4U3lQ5ybvjIPYo3+5udw==">Here is a sketch</a>

The first shadow is painted, because blur is non-zero, but the second shadow does not get painted, although it should be.

This behaviour is caused by <a href="https://github.com/paperjs/paper.js/blob/develop/src/item/Item.js#L3962">Item.js line 3962</a>, where the shadow painting is skipped if the shadow has no blur.

If I see it correctly the shadow painting can only be skipped 
- if the item has no fill color
- or if there is no shadow color
- or if the shadow color has an alpha of zero
- or if the alpha value of the item's fill color is 1 and the shadow has no offset and the shadow blur is zero

So it's probably the easiest to simply remove lines <a href="https://github.com/paperjs/paper.js/blob/develop/src/item/Item.js#L3962">3962</a> and <a href="https://github.com/paperjs/paper.js/blob/develop/src/item/Item.js#L3968">3968</a>.

**Comment by lehni** [comment]
you're right. but for performance we don't want to constantly set shadows... I think I've messed this up recently, will have to find the corresponding commits and revert.

**Comment by iconexperience** [comment]
I think this is an old bug. because it is in the code base from December 2014, too.

And I do not think you will see a performance difference in the vast majority of cases, because you alreay skip painting the shadow if no shadow color is set, which is correct. If someone sets the shadow color to a non-null value, usually drawing a shadow is desired. I think there are only very few cases when a shadow color is set but no shadow blur, and these are the only cases that would be affected.

**Comment by lehni** [comment]
Here the commit in which I thought I broke this: 7969e4647cfcedfd32717748ae0de2c01b7cf4fe

**Comment by iconexperience** [comment]
You could also add a check for alpha != 0 like this:

```
if (shadowColor && shadowColor.alpha) {
```

If alpha is zero, the shadow will always be invisible anyways.

**Comment by lehni** [comment]
True that...

**Comment by lehni** [comment]
I've done something even better here: c6bcf4351a06d409de3c4ad80729489b0104bfba : )

**Comment by iconexperience** [comment]
I just realized that the fill color can also be a gradient. Do you take this into account? AFAIK gradients are not possible on shadows, right?

**Comment by iconexperience** [comment]
My little test shows that your `hasFill()` function always returns `true` for gradients. I also tested for fully transparent gradients, and it still returns true, but this is not a problem I think.

<a href="http://sketch.paperjs.org/#S/TVFNb4MwDP0raQ4taAi1lXoBbZdKO0/bsXAI4IaoqY2SdDtU/Pc5BapakfPxnp9j+y5RXUEW8ucCoe1lJlvq4v1XOdEr/2msFe/ifMM2GMIkFfcKBVvEW7LkGB1yDSEyj/EhScuJ4iDcHIrVauKt11NAruzQK/EhtswbK6wwag2sg/AnvlTo829og0JtIdltt5l4uP18iupDfl6ycdj8I+1UZwBDsTxE84EGX4jTaeN0oxKWmFe6YVdnYgb2hwOneLoHvKvrSWjMpp2c0QYLrrehG3Y+Z/EjZwQ3EzrwwaCKnXphNRQCXZ/E8VGAD44usJRQSe0AsJJl7EdL6MlCbkknlZynUDBJvC0zSV5akKYlz61xoC4DGQxeFqd6/Ac=">Here is the sketch</a>

**Comment by lehni** [comment]
Yeah I think they always have alpha = 1... It's OK that way, I think : )
