### ISSUE TITLE
npm hangs at custom jsdom install

### ISSUE THREAD

**Issue by iconexperience** [paperjs/paper.js#957]
I am currently not able to install the dependencies through `npm install`. Running it with the `-verbose` parameter shows that it hangs at the custom `jsdom` package. Here are the latest lines from the output:

```
npm verb cloneResolved git://github.com/lehni/jsdom.git#bd86dd16666241edd5f25bc4f4e144f24da3c889 clone Cloning into 'C:\cygwin64\tmp\npm-2764-96cdc9d9\git-cache-ae0b00d9\bd86dd16666241edd5f25bc4f4e144f24da3c889'...
npm verb cloneResolved done.
npm info git [ 'checkout', 'bd86dd16666241edd5f25bc4f4e144f24da3c889' ]
npm verb checkoutTreeish git://github.com/lehni/jsdom.git#bd86dd16666241edd5f25bc4f4e144f24da3c889 checkout Note: checking out 'bd86dd16666241edd5f25bc4f4e144f24da3c889'.
npm verb checkoutTreeish
npm verb checkoutTreeish You are in 'detached HEAD' state. You can look around, make experimental
npm verb checkoutTreeish changes and commit them, and you can discard any commits you make in this
npm verb checkoutTreeish state without impacting any branches by performing another checkout.
npm verb checkoutTreeish
npm verb checkoutTreeish If you want to create a new branch to retain commits you create, you may
npm verb checkoutTreeish do so (now or later) by using -b with the checkout command again. Example:
npm verb checkoutTreeish
npm verb checkoutTreeish   git checkout -b <new-branch-name>
npm verb checkoutTreeish
npm verb checkoutTreeish HEAD is now at bd86dd1... Allow scripts to be pulled down from Github through NPM.
npm info git [ 'submodule', '-q', 'update', '--init', '--recursive' ]
```

The same happens when I call 

`npm install git://github.com/lehni/jsdom.git#bd86dd16666241edd5f25bc4f4e144f24da3c889`

direclty.

**Comment by iconexperience** [comment]
Oh, I am running this on Window 7, which may be relevant.

**Comment by iconexperience** [comment]
Actually, it does not really hang but it creates an error after a while:

```
npm ERR! git submodule -q update --init --recursive: error: unable to create file custom-elements/registering-custom-elements/unresolved-element-pseudoclass/unresolved-element-pseudoclass-css-test-registered-custom-tag-ref.html (Filename too long)
```

And there are many of these errors.

**Comment by iconexperience** [comment]
It appears this is actually a Windows specific problem:

http://stackoverflow.com/questions/26155135/node-npm-windows-file-paths-are-too-long-to-install-packages

**Comment by lehni** [comment]
If it's the path issue, could you try installing it at the root level, e.g. `C:\paper.js`?

**Comment by iconexperience** [comment]
I tried, but it failed again. I even set the npm cache directly into `C:/`, but this again did not work. It seems there still is the git cache at `C:\\cygwin64\\tmp\\npm-9048-1ca9f6f0\\git-cache-863f763f\\bd86dd16666241edd5f25bc4f4e144f24da3c889` which has a too long path name.

**Comment by iconexperience** [comment]
BTW, installing the tmpvar/jsdom works without any problems. I think it is just the SHA-1 behind your project that breaks things here on Windows.

**Comment by lehni** [comment]
to explain why that one works: It's a normal published module, received from the NPM registry, while my version is a specific commit retrieved from GIT. Both methods are supported by NPM and I do follow standards. This is a NPM bug, not a paper.js bug... Not sure what I can do, other than getting my PR in JSDom to pass as quickly as possible. At the moment it still lacks unit tests: https://github.com/tmpvar/jsdom/pull/1366

**Comment by lehni** [comment]
I believe the problem is actually that the JSDom git repository has too many recursive folders with too long file-names internally... What file-system are you on? NTFS?

**Comment by iconexperience** [comment]
I know that this is not a paper bug, I just wanted to say that the sha1 probably makes the difference here. My file system is NTFS.

Please do not spend too much time on this. You cannot test anyway due to lack of WIndows and I will get along somehow.

**Comment by lehni** [comment]
I could send you a ZIP file of the project for you to replace it in your node_modules. That's probably the easiest solution here.

**Comment by iconexperience** [comment]
You mean of your custom jsnode? That would be great.

**Comment by lehni** [comment]
Can you try downloading and installing this directly into your `paper.js/node_modules/` folder?

https://www.dropbox.com/s/s1nuh8xy8jymbe9/jsdom.zip?dl=0

And after that, `cd` into the newly copied `jsdom` folder and run `npm install` for it.

    cd node_modules/jsdom
    npm install

**Comment by iconexperience** [comment]
That worked, thanks. Should we keep this issue open as a reminder?

**Comment by iconexperience** [comment]
Closing this as everything seems to work.

 @lehni maybe you can keep the dropbox link alive? If other Windows users run into trouble, they can workaround this issue using the zip file.

**Comment by lehni** [comment]
Yes I'll keep the link alive for the time being!
