### ISSUE TITLE
CurveLocation.isCrossing() may return point instead of boolean value

### ISSUE THREAD

**Issue by iconexperience** [paperjs/paper.js#959]
Since the big overhaul in https://github.com/paperjs/paper.js/commit/75928954454764ff7f1053fa19e3405dedfda7f9 the function `isCrossing()` in `CurveLocation` may return a `Point` instead of a `boolean`. The relavant code is <a href="https://github.com/paperjs/paper.js/blob/develop/src/path/CurveLocation.js#L460">CurveLocation.js lines 460/461</a>

Here is a simple example:

![image](https://cloud.githubusercontent.com/assets/2122773/13000927/ce149e4c-d160-11e5-8323-dd887e92ed3d.png)

```javascript
var p1 = new paper.Path.Rectangle(100, 100, 200, 100);
var p2 = new paper.Path.Rectangle(120, 100, 20, 20);
p1.strokeColor = "red";
p2.strokeColor = "green";
console.log(p1.getIntersections(p2)[0].isCrossing());
```

<a href="http://sketch.paperjs.org/#S/fY89C4MwEIb/SsikIEEzKp06dSvtqA6pHlG0d+ES2qH0vzd+QIdChzvu5eG5414SzR1kKa8ThG6QmeyoX/LDsHCFOAiEp3DGAauzCYO6QBcM2hmSIs8zsTa9T2nVcIOrqf+a+msutXmuUD4wTXCkmTj6jWToG7lB/QMtA+COO0JPM6iZbBL3WAgnDMA+nhwjSpxO67xVoz8yeT+iTdK0is/eGMzkaMTgZVm37w8=">The Sketch</a>

The output is `{ x: 120, y: 100 }`, while a `boolean` value would be expected. Of course the point could be counted as `true`, but I am sure it is not meant this way.

This leads to the second question, which is why the function returns `true` (or a `Point`) at all in this case. I do not see a crossing here, so I think it should return false. This may also be the reason why #951 fails.

**Comment by iconexperience** [comment]
Thanks. This bug was so confusing, because I debugged using

```
console.log(intersection.point);
console.log(intersection.isCrossing();
```

And this produces two points on the console :smiley:

**Comment by lehni** [comment]
: )

**Comment by lehni** [comment]
A point result can be treated as a falsy thing, of course : )

**Comment by iconexperience** [comment]
Yes, but not by a human brain :)

**Comment by lehni** [comment]
Perhaps your brain is falsy too sometimes?

**Comment by iconexperience** [comment]
About half of the time.

**Comment by lehni** [comment]
From the past hundred solved issues or so, I have a feeling the ratio is more in our favor.
