### ISSUE TITLE
Tiny imprecisions in Curve.evaluate() cause problems

### ISSUE THREAD

**Issue by iconexperience** [paperjs/paper.js#960]
I found some cases when the new implementation of `Curve.evaluate()` causes problems (but I have a solution, see further below). Here is an example:

![image](https://cloud.githubusercontent.com/assets/2122773/13003888/4fd54758-d178-11e5-9356-e2641fa1fcfd.png)

```javascript
var p1 = new Path({segments:[
    [178.58559999999994, 333.41440000000006], 
    [178.58559999999994, 178.58560000000008],
    [333.4143999999999, 178.58560000000008], 
    [333.4143999999999, 333.41440000000006]], closed:true});
var p2 = new Path({segments:[
    [318.15298928061804, 184.6830880641364], 
    [327.31691193586363, 290.952139494413], 
    [221.04786050558695, 184.6830880641364]], closed:true});

var res = p1.subtract(p2);
p1.strokeColor = "green";
p2.strokeColor = "red";
res.fullySelected = true;
```

The result of the subtraction should be the outer rectangle minus the triangle, but it is only the triangle.

The reason behind this behavior is a tiny imprecision in the new implementation of `Curve.evaluate()` that removed snapping to the end points for `t < tmin` and `t > tmax`. In the new version if the point on the curve is calculated for `t==1` the result may be slightly different from the curve's end point, caused by the calculations 'x = ((ax * t + bx) * t + cx) * t + p1x' and `y =  ((ay * t + by) * t + cy) * t + p1y`.

Here is a en example of the imprecision (in this case `-2.842170943040401e-14`):
```
var crv = new paper.Curve({
    segment1: [178.58559999999994, 333.41440000000006],
    segment2: [178.58559999999994, 178.58560000000008]
});
console.log(crv.getPointAtTime(1).y - crv.point2.y);
```

This can become a problem for our winding calculation, because we apply no tolerance at all in `y` direction. So even a point with an `y` offset near machine epsilon may be counted outside the path by the winding.

The easiest solution now is to shortcut the calculation of `x` and `y` for `t==1`. <a href="https://github.com/paperjs/paper.js/blob/develop/src/path/Curve.js#L1341">Curve.js lines 1341/1342</a> would then simply become
```
x = t === 1 ? p2x : ((ax * t + bx) * t + cx) * t + p1x;
y = t === 1 ? p2y : ((ay * t + by) * t + cy) * t + p1y;
```

BTW, the imprecision cannot occur for `t === 0`, because all summands except `p1x`/`p1y` will become zero, hence the result is exactly `[p1x, p1y]`.

**Comment by lehni** [comment]
I decided to match both t=0 / 1, to avoid performing unnecessary calculations, and for the sake of symmetry : )

**Comment by iconexperience** [comment]
Actually, I had that before but decided that the lines are a bit long :)
