### ISSUE TITLE
Project.getItems() by intersection doesn't match when Item is fully contained

### ISSUE THREAD

**Issue by georeith** [paperjs/paper.js#961]
When you `Project.getItems` looking for overlapping items like so:

```js
Project.getItems({
    overlapping: rectangle
});
```

If the item is fully contained within `rectangle` it is not matched. If you:

```js
Project.getItems({
    overlapping: rectangle,
    inside: rectangle
});
```

Then it has the correct behaviour. This is counterintuitive because the rest of the options are inclusive and not exclusively matched.

**Comment by lehni** [comment]
This sounds like a bug that I fixed recently. Did you test against prebuilt?

**Comment by georeith** [comment]
@lehni Nope I had to get off it as for some reason NPM wasn't pulling down the `dist` folder anymore

**Comment by lehni** [comment]
That sounds weird. You can also manually install it from the ZIP: https://github.com/paperjs/paper.js/tree/prebuilt/dist

**Comment by lehni** [comment]
I can't replicated this: http://sketch.paperjs.org/#S/XZDBbsIwDIZfJcqlIKGqoJ2CduK027QdKYeQmhJqnMpJ2QHx7nPXdGiLIsux//j7k7smewVt9GcHyZ31SrvQjOebZdXbdFaviuBLvUta7jw7hMW9JiWLbeOHaNS6qlZTxQElYKP2GykpCYfcOHnEXcAgvYKhKWp6LLc11TRSGFzKlA9JLbXCkPuyX6opTOJfH0/ZbGUumJ80U2Pi0MHMPeIARe60g29Em3iAf1bigKOZnsNFBpUtpLcE1ziDHNooTx5d5FHhBoy27z21f+AZcbIYnwwXKAaEEkO7mFjLrXz5kcF2ffCUojb7w+Mb
