### ISSUE TITLE
Unable to access segments from importSVG

### ISSUE THREAD

**Issue by owzzz** [paperjs/paper.js#963]
Hi,

I'm trying to manipulate the points of a logo in the similar style to the example on the paperjs: 

http://paperjs.org/examples/smoothing/

I'm using the importSVG to get the SVG into the paper project, but I've been unable to access segments to iterate over and animate on mousemove.

This is my basic code to grab SVG and access segments

``` javascript
   // Get a reference to the canvas object
			let canvas = document.getElementById('myCanvas');

			// Create an empty project and a view for the canvas:
			Paper.setup(canvas);

			Paper.project.importSVG('images/foret-music.svg', {
				onLoad: (group) => {
					group.scale(0.62);
					group.position = new Paper.Point(Paper.view.center);
					group.onMouseMove = this.onMouseMove;

					console.log(Paper.project.activeLayer.segments); //Undefined
					console.log(Paper.project.activeLayer.children[0].segments); //Undefined
					console.log(Paper.project.activeLayer.children[0].paths); //Undefined
				}
			});

			Paper.view.draw();
```

I notice when I grab the active layer, and inspect the children, it's just one item. I would of expected to have a child for each letter of the logo.

Whats the best way to get hold of each point?

Secondly is there a Slack channel or git chat room for the project? It'd be great to share ideas and knowledge.

Thanks

**Comment by lehni** [comment]
A few things:

- layers never have segments
- `paths` doesn't exist as a property on any item
-  try `exppandShapes: true` in the options object passed to `importSVG()`. You're probably receiving `Shape` items
- You can log `item.className` to figure out what you're receiving.
- The issue database is for bugs, not supports questions. Please write to the mailing list for such questions: http://groups.google.com/group/paperjs
