### ISSUE TITLE
Tool docs event examples broken

### ISSUE THREAD

**Issue by arctwelve** [paperjs/paper.js#967]
In the reference for the `Tool` object:
http://paperjs.org/reference/tool

The examples for the mouse events and the key down event are not working. Tested on latest Chrome and Edge on Windows 10.

**Comment by lehni** [comment]
You mean it doesn't have a canvas? Not all examples do... But this one would benefit of one : )

**Comment by arctwelve** [comment]
Wrong, the existing examples are broken.

**Comment by lehni** [comment]
Oh yeah, now I see it.
