### ISSUE TITLE
Information on orientation of subpaths gets lost during Path.unite()

### ISSUE THREAD

**Issue by iconexperience** [paperjs/paper.js#973]
Whenever we perform a `path.unite()` to break down a self intersecting path into non-intersecting subpaths, there is no way afterwards to determine the orientation (clockwise/anti-clockwise) that the subpaths.had before the `unite()`. This happens because all children will automatically receive the orientation of the original path.

Here is an example. The center part of the path has an anti-clockwise orientation, while the right and left parts have clockwise orientation. But at the end, all parts have clockwise orientation.

![image](https://cloud.githubusercontent.com/assets/2122773/13042921/ad4407a0-d3c4-11e5-90eb-5cb4e338f89a.png)

```javascript
var path = new Path.Ellipse(100, 100, 150, 110);
path.segments[1].point.y += 60;
path.segments[3].point.y -= 60;
path.strokeColor = "green";
path.fillColor = "lightgreen";
console.log("path clockwise: " + path.isClockwise());

var compPath = path.unite();
for (var i = 0; i < compPath.children.length; i++) {
    console.log("child " + i + " clockwise: " + compPath.children[i].isClockwise());
}
```

<a href="http://sketch.paperjs.org/#S/ZZHBbsMgDIZfBXFKlA4lmrZDup6q3Sv1GHLIqJugEBMBXTVVffeZRF3UBQlj+D/h33Dj2AzAS37sIaiOb7iyp7j/bhwbm9CxHUO4sgOl4tMYPXpIijzfsDm8xVDk6VZipIWHdgAMvipqMVqNQfywbMfe8xXwugAvT0Bwtoe9NdZRbclbB4CSP+SzNmYRjW67sBDKorcGhLFtIvlkXxmr+qv2UBLOsqknof3+cZyk0bvE2K+yw3iYe56wC+pAAOlnqpdERJOWb2n5+KOF6rQ5OUBhANvQkZplKbtJZDSeLU3obETTpOS/v9Wtla7Xfu/RskT6ri8HTT89pOdlVd9/AQ==">The Sketch</a>

**Comment by lehni** [comment]
Is this causing issues anywhere?

**Comment by iconexperience** [comment]
Not directly, but I need this information for path offsetting. Here is an example:

![image](https://cloud.githubusercontent.com/assets/2122773/13043066/fac56cb6-d3c5-11e5-9c44-6121e084b35b.png)

The green path is the path offset for the red rectangle. In order to get a final result, the triangles at the corner need to be removed. But in order to know that they should be removed, I need to know if they are clockwise or anti-clockwise, but I do not have that information.

I know that this is a special case, but I thought that there may be other applications where the information about the original winding may be useful.

**Comment by iconexperience** [comment]
This is definitely not something that needs to be fixed for v0.10

**Comment by lehni** [comment]
That makes sense. For this you can directly call `resolveCrossings()` instead of `unite()`, btw.

**Comment by lehni** [comment]
This is produced by your code in `resolveCrossings()` which reorients the curves, correct?

**Comment by iconexperience** [comment]
Thanks, I did not realize that `resolveCrossing()` is accessible.

And yes, as I see it the orientation is changed by <a href="https://github.com/paperjs/paper.js/blob/develop/src/path/PathItem.Boolean.js#L878">PathItem.Boolean.js lines 878/879</a>. Maybe a simple argument `preserveOrientation` would do the job.

**Comment by lehni** [comment]
We could also separate the two again... `resolveCrossing()` / `reorient()` perhaps did make sense, after all?

**Comment by iconexperience** [comment]
I have added the parameter as proposed above and only do the reoorientation if the parameter is not set to `true`. This works very well, but you are right, separating the `resolveCrossings()` from the reorientation would be better, as they are actually two different operations.

**Comment by lehni** [comment]
@iconexperience 3f058e6471c11845e12d00ae120730afcd7a8e47 should resolve this. Please let me know if it works for you!

**Comment by lehni** [comment]
@iconexperience I've separated the methods now and they landed in `develop`, but I have one concern:

The way `#reorient()` is currently implemented, it removes unnecessary children. This is great, and required when it's used for boolean operations in conjunction with `#resolveCrossings()`, but if we're going to remove the automatic orientation of sub-paths of a compound-path on insertion, and recommend `#reorient()` as the new way to fix orientation (which we will), I think we can't have it remove these children by default...

I am now wondering, can we hide this behind a switch, and have it keep the children by default? since you wrote the method, this easy to implement?
