### ISSUE TITLE
Hit testing with tolerance is inconsistent between shape and path

### ISSUE THREAD

**Issue by iconexperience** [paperjs/paper.js#977]
The result of a hit test using a tolerance is not consistent between `path` and `shape` items.

Here is a little test:

```javascript
  var point = new Point(20, 20);
  var size = new Size(40, 40);
  var hitPoint = new Point(10, 10);
  var options = {
    fill: true,
    tolerance: 20
  };
  
  var shapeRect = new Shape.Rectangle(point, size);
  shapeRect.fillColor = 'black';

  var pathRect = new Path.Rectangle(point, size);
  pathRect.fillColor = 'black';
  
  // show where our hit point is
  new Path.Circle({center: hitPoint, radius: 3, fillColor: "red"});

  var shapeRectHit = shapeRect.hitTest(hitPoint, options);
  var pathRectHit = pathRect.hitTest(hitPoint, options);

  // no hit found for Shape.Rectangle
  console.log("hit result shape:")
  console.log(shapeRectHit);
  
  // hit found for Path.Rectangle
  console.log("hit result path:")
  console.log(pathRectHit);
```

<a href="http://sketch.paperjs.org/#S/fVPLbsIwEPyVlS8kUsSrnIx64tIjKr01PRhnIVZcO3KcIhXx713nRaAtl8hez87s7ChnZsQnMs52BXqZs4RJm4U7wJdwUFplPDyDwRNswzlazhNYzuN1alpEpb6xA+zoGK3ofTV6z5Xf/iJZEGgxAtnSK2sqwpxDCeCgtObgXY1JW/BWoxNGIif1ULo0zcMUuSjxFWUvswv3aSgIc9QYNT6SZthWdWiYBqmN1dZR62SvhSwmhOiJS+HzEe+Wro9oe/g/rO3AsxnJ2xOccnQItm6W1K1aVQExSG2Uk6Rzlmg8Oj5sMwEnMlVXHJ4SGLQ4pMxhlrJLPLIwWH1RwcbVOZG9YeWjK2mXwzWY3k/bOrh72NlZNLaxdbC1yejr7jMJMEktFOxU22OUsgB3WNXat0PylMX3qLGZeLzRW63bnB5KBVN/KY2sx2v6L/YORdGEVDH+/nH5AQ==">And here is the Sketch</a>

For me this issue has the lowest priority possible, as I do not use shapes anymore. This was found in an old chunk of code, but I thought it should be reported for completeness.

**Comment by iconexperience** [comment]
Just want to confirm that bugfix solves the issue in my old code, great work again.

**Comment by lehni** [comment]
Sweet! That reminds me, I shall implement some unit tests for this. Opening again.
