### ISSUE TITLE
Cannot bundle paper.js as a submodule because paper = function{ ... }(this.self)

### ISSUE THREAD

**Issue by louisremi** [paperjs/paper.js#982]
In the past few days I've spent quite some time trying to bundle paper.js as a dependency of plumin.js

The last remaining issue I am having is caused by the fact that paper is defined through a self invoking function that uses `this.self` as an argument, see https://github.com/paperjs/paper.js/blob/develop/src/paper.js#L126
When bundled with Webpack (or another similar build tool), Paper is wrapped in a function, which results in `this.self` to always be undefined.

In my tests, replacing this this line with `typeof self !== undefined ? self : undefined` fixes the problem without any side effect (I've got four tests failing, but never managed to get those to pass).

There might be a very good reason why you're using this, though... If not, would that change be acceptable to you?

**Comment by lehni** [comment]
Oh dear, I'm sorry it's been so much work to update to this. There are so many ways of using JS libs out there, tricky to tick all the boxes. What you propose certainly works, but let me look into it a bit to see if there's a better way. More on this later.

**Comment by lehni** [comment]
What Webpack is doing will probably lead to slower execution, BTW. It results in the paper.js code being wrapped in two functions, since we're already scoping the full library in a function, and look-ups have to walk up that hierarchy until an object is found...

**Comment by lehni** [comment]
Basically your proposal, just a few bytes shorter : )

**Comment by louisremi** [comment]
Excellent! You're not to blame with my update issues. It was quite a bit of work right now, but following the progresses of Paper will now be MUCH easier, thanks to your work on the Web Worker compatibility.
