### ISSUE TITLE
Event delta incorrect in develop branch

### ISSUE THREAD

**Issue by tjunnone** [paperjs/paper.js#983]
I've been testing git versions for a while and I've noticed a regression on the develop branch:

In 0.9.25 and in git versions from early January, a mouseup event (inside of a ToolEvent in my case) will have a delta value from the mousedown point measuring how far you've moved.

In current develop branch head, the mouseup delta is very small no matter how far you've moved, delta.length is always somewhere around 0.90 for me. So it seems to me it's probably just using the last two points, not the entire travel delta.

I may do a git bisect to find the exact point of change a bit later.

**Comment by lehni** [comment]
Is this still the case now, since my fix for #981 (that I just pushed now, on the road at the moment). I believe it's already fixed.

**Comment by tjunnone** [comment]
Yep, that appears to have fixed it. Thanks!

**Comment by lehni** [comment]
Sweet! Two birds, on stone : )
