### ISSUE TITLE
Hit test ignores stroke scaling, mouse listeners aren't triggered

### ISSUE THREAD

**Issue by sebastian-nowak** [paperjs/paper.js#987]
Current hit test implementation appears to ignore `strokeScaling: false`, it's matched against the unscaled stroke.

You can test it with below code, it's impossible to trigger `onMouseEnter`:
```
var path = new Path.Circle({
	center: [100, 100],
	radius: 1000,
	strokeColor: 'red',
	strokeWidth: 15,
	strokeScaling: false
});
path.onMouseEnter = function(){ alert('ok'); }
view.zoom = 0.01;
```

If you change the zoom to 0.05, `onMouseEnter` will be triggered on some parts of the scaled stroke - exactly where the unscaled stroke would be.

**Comment by lehni** [comment]
Have you tested against the `develop` branch already? This sounds like issue #697 which has already been fixed: 

https://github.com/paperjs/paper.js/tree/prebuilt/module
https://github.com/paperjs/paper.js/tree/prebuilt/dist

**Comment by sebastian-nowak** [comment]
I've checked it only against the latest stable version (0.9.25). You're right, it appears to work fine in develop. Thank you for quick answer.

**Comment by lehni** [comment]
Glad to hear it : )
