### ISSUE TITLE
Request: Like Item.transform() but local

### ISSUE THREAD

**Issue by georeith** [paperjs/paper.js#990]
So it seems that `Item.transform(matrix)` uses pre-multiplication and thus the matrix is applied as if in the global space.

Here is a sketch comparing the two methods, notice how the green rectangles rotation affects its final translation (it was rotated in the global coordinate space).

http://sketch.paperjs.org/#S/tZHNCsIwEIRfJeRiC6W0FS8VT54F0aP1EOOqpelGtkFF8d3dpPh7NyELGb5kNpObRNWCLOWyAacPMpHabv3+pEi0uZgIhLOYKUf1JYpTRwo7oxxEwyxLBJd4XGFgi1+WrPNgwdwoLI/20x8g0O55/1y5Q7pgQeHeQHSrUPDo6iuUYpV7Jy7rpJePtkbHepa8pF1tzNQaS6UY7AkABxXee7unVfEHK4Lt26jC8KI+op2lNmrz+HNXeC608sWk2lgEzktb1BwY+tAYjsf8GRsC1YQuOlmu1vcH

That's fine although but I can't find any simple methods for doing what I would presume is more common which is wanting to apply stuff locally without manually calling `concat()` on the matrices and then swapping it out.

Think this would be really useful.

**Comment by lehni** [comment]
Did you mean to create both this issue and #989 ?

**Comment by lehni** [comment]
We felt that pre-multiplication was more intuitive than post-multiplication, because when working with an item, you tend to look at it from its outside coordinate system. Next to using `item.transform()`, you can perform: `item.matrix.append(...)` and `item.matrix.prepend(...)` (which will do the same as `item.transform()`. Do you have a suggestion for a method name that would perform `item.matrix.append` but could be called directly on the item?

**Comment by lehni** [comment]
Also, could you elaborate why you assume post-multiplication to be more common than pre-multiplication?

**Comment by georeith** [comment]
@lehni Apologies no didn't realise I had opened that too.

That's a good point I hadn't thought about using the matrix functions directly on the items matrix. This feature is unnecessary.

I assume its more common because its easier to think in that regard (e.g, for rotation and translation, easier to think of it first as rotation then as translation than rotation about a single point in the global space) and will have the same effect as chaining the transformation as a sequence of `scale()`, `translate()`, `rotate()` and `skew()`. It came as quite a surprise to me when my tests showed a different output between the two.

But yeah really not an issue... end of the day feature request for some reason the I didn't think about mutating the items matrix directly.

**Comment by lehni** [comment]
Our logic was that the people who use these methods directly on item may not be trained to think this way, and expect them to feel *logical*... But perhaps it was a mistake to then have `transform()` also premultiply the matrix. It's tricky to reverse this now as it will potentially break tons of things out there. `Matrix` then should behave like all Matrix2D libraries too, we though.

**Comment by georeith** [comment]
@lehni Yeah I wouldn't reverse it now.

Its just an assumption on my behalf anyway. `Item.matrix#concatenate()` and `Item.matrix#preConcatenate()` (append and prepend don't seem to exist for me but will check that out later today) are enough for this.

**Comment by lehni** [comment]
Note that those are deprecated in favor of the shorter prepend() / append()
