### ISSUE TITLE
Minified version in Bower distribution is broken

### ISSUE THREAD

**Issue by ste93cry** [paperjs/paper.js#996]
While I was trying to use the minified version of the script found in the bower distribution (`paper-full.min.js`), I found out an error that prevents it from running correctly. The console reports this error:

> SyntaxError: missing ] after element list
...xports"],e):[object Object]0}(this,function(t){"use strict";function e(t){ce=t|

Unfortunately, console does not provide any error line/column. I'm using Firefox 44, but my colleague using Safari and Chrome had the same problem. This led me think that the minified version is broken.

**Comment by lehni** [comment]
Curious! Did you try the prebuilt versions also?

https://github.com/paperjs/paper.js/tree/prebuilt/module
https://github.com/paperjs/paper.js/tree/prebuilt/dist

**Comment by lehni** [comment]
I just tested this and installed `paper` `v0.9.25` from bower. The minified version that comes with it works without problems in any of my browsers. Which version are you experiencing this with?

**Comment by ste93cry** [comment]
Version `0.9.25` is ok, `0.9.23` is broken. Sorry for not checking myself the version before opening an issue on a old version

**Comment by lehni** [comment]
Yes I remember there was an issue with an older version. So it's fine to close this, yes?

**Comment by ste93cry** [comment]
Yes it's fine
